### ISSUE TITLE
onComplete callback of microsoftTeams.settings.setSettings() is not invoked on Android mobile

### ISSUE THREAD

**Issue by stejura-sfdc** [OfficeDev/microsoft-teams-library-js#1014]
### Problem
The `onComplete` callback of [microsoftTeams.settings.setSettings()](https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/microsoftteams.settings?view=msteams-client-js-latest#@microsoft-teams-js-microsoftteams-settings-setsettings) is never invoked on Android (possibly on iOS as well, but I haven't tried). 

Note that `onComplete` is successfully invoked on a desktop browser and desktop app. 

### Details

<details>
  <summary>Code snippet</summary>
  
```html
<html>
  <body>
    <div>
      <strong>Teams Tab - Click "Save"</strong>
      <p>
        <span id="display"></span>
      </p>
    </div>

    <script src="https://statics.teams.cdn.office.net/sdk/v1.11.0/js/MicrosoftTeams.min.js"></script>

    <script type="text/javascript">
      microsoftTeams.initialize();

      microsoftTeams.authentication.getAuthToken({
        successCallback: function (token) {
          console.log(`Teams Auth Token: ${token}`);
          const div = document.getElementById("display");
          
          microsoftTeams.settings.setValidityState(true);
          microsoftTeams.settings.registerOnSaveHandler((saveEvent) => {
            display.textContent = 'Clicked Save.';
            
            const now = Date.now();
            
            microsoftTeams.settings.setSettings({
                websiteUrl: 'https://phrygian-amused-griffin.glitch.me/public/tab.html',
                contentUrl: 'https://phrygian-amused-griffin.glitch.me/public/tab.html',
                entityId: now,
                suggestedDisplayName: `SFDC Demo ${now}`
            }, (status, reason) => {
              div.textContent += ` Status: ${JSON.stringify(status)} Reason: ${JSON.stringify(reason)}`;
              console.log(`Status: ${status}. Reason: ${reason}`);
              
              if (status) {
                saveEvent.notifySuccess();
              } else {
                saveEvnet.notifyFailure();
              }
            });
          });
        },
        failureCallback: function (error) {
          console.log(`Teams Auth Token: ${error}`);
          const div = document.getElementById("token");
          div.textContent = error;
        },
      });
    </script>
  </body>
</html>
```
</details>

**Glitch app**: https://glitch.com/edit/#!/phrygian-amused-griffin?path=public%2Ftab.html%3A52%3A0

**Manifest**: [teamsAppManifest.zip](https://github.com/OfficeDev/microsoft-teams-library-js/files/8328517/teamsAppManifest.zip)

**Android recording**: https://user-images.githubusercontent.com/53920805/159596240-517fbfcd-77cf-429d-bf0a-db0a873efd27.mp4

**Desktop recording**: https://user-images.githubusercontent.com/53920805/159596253-17fbc62b-9891-4d2b-8d97-67c4470ca34a.mov

**Comment by Prasad-MSFT** [comment]
We are checking the issue. We will get back to you shortly.

**Comment by Prasad-MSFT** [comment]
@stejura-sfdc - We tried this at our end and can observe that its working in both MS Teams Desktop and Android devices. 
`MS Teams Version(Android): 1416/1.0.0.2022262002/0313`

**Comment by stejura-sfdc** [comment]
@Prasad-MSFT Thanks for checking!

I'm on MS Teams Version (Android): `1416/1.0.0.2022244301/0308` and I can still reproduce the issue. I've tried checking for new updates on the Play Store (none available), enabled "Developer preview" in the Teams mobile app, cleared cache/storage data - none help.

<details>
  <summary>Manifest</summary>
  
```json
{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.11/MicrosoftTeams.schema.json",
  "manifestVersion": "1.11",
  "version": "1.0.0",
  "id": "4a307d9c-d923-49ef-829a-13824cf3cd64",
  "packageName": "com.sfdc.demo",
  "developer": {
    "name": "Salesforce",
    "websiteUrl": "https://www.salesforce.com",
    "privacyUrl": "https://www.salesforce.com",
    "termsOfUseUrl": "https://www.salesforce.com"
  },
  "icons": {
    "color": "color.png",
    "outline": "outline.png"
  },
  "name": {
    "short": "SFDC Demo",
    "full": "SFDC Demo"
  },
  "description": {
    "short": "Demo app/bot for SFDC",
    "full": "Demo app/bot for SFDC"
  },
  "accentColor": "#FFFFFF",
  "configurableTabs": [
    {
      "configurationUrl": "https://phrygian-amused-griffin.glitch.me/public/tab.html",
      "canUpdateConfiguration": true,
      "scopes": [
        "team"
      ],
      "context": [
        "channelTab"
      ]
    }
  ],
  "composeExtensions": [
    {
      "botId": "4a307d9c-d923-49ef-829a-13824cf3cd64",
      "canUpdateConfiguration": true,
      "commands": [
        {
          "id": "dynamicSearchQuery",
          "type": "action",
          "title": "Search records",
          "description": "Find the record to mention",
          "initialRun": false,
          "fetchTask": true,
          "context": [
            "compose",
            "commandBox"
          ],
          "parameters": [
            {
              "name": "param",
              "title": "param",
              "description": ""
            }
          ]
        }
      ]
    }
  ],
  "permissions": [
    "identity",
    "messageTeamMembers"
  ],
  "validDomains": [
    "phrygian-amused-griffin.glitch.me",
    "*.githubusercontent.com",
    "*.ngrok.io",
    "*.botframework.com",
    "*.glitch.me"
  ],
  "webApplicationInfo": {
    "id": "4a307d9c-d923-49ef-829a-13824cf3cd64",
    "resource": "api://phrygian-amused-griffin.glitch.me/4a307d9c-d923-49ef-829a-13824cf3cd64"
  }
}
```
</details>

Can you try with the manifest attached above this line? 

The steps I followed are outlined below:

1. From the desktop app (or browser), import the manifest above via App Studio
2. Navigate to `Finish -> Test and Distribute` section in App Studio
3. Click on `Install`
4. From the drop-down on the right, select `Add to a Team`
5. Select a Team
6. Click on `Set up a tab`
7. Once the app loads, click on `Save` (this will pin a tab to the Team)
8. Next, switch to Android and find the pinned tab (under [team-name] -> More)
9. Click on the three dots to the right (this should bring up a menu with options)
10. Select `Settings`
11. Wait for the app to load, and then click the checkmark icon on the top-right corner. 

**Expected Result**: After clicking on the checkmark, the app/tab should automatically close

**Actual Result**: The app/tab remains open because the `onComplete` callback is never invoked. The `onComplete` is responsible for calling `notifySuccess` which closes the app/tab (source provided in my initial comment)

Let me know what you find.

**Comment by Prasad-MSFT** [comment]
@stejura-sfdc - While trying to repro by using the manifest file following the steps provided, we are getting below error, Could you please share any deployed app creds so that we can try it out. Thanks!
![image](https://user-images.githubusercontent.com/62237649/159954903-a11decc2-ec65-418c-b5bb-7a1ed82b91d8.png)
FYI, we followed this sample(https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-conversations/csharp) and got no issues. Please try this once and check if it helps.

**Comment by Prasad-MSFT** [comment]
@stejura-sfdc - Thanks for the detailed explanation. Now we have  repro for this issue (Not working in Android) and we have raised a bug for this. We will inform you once we get any update from engineering team. Thanks!

**Comment by Prasad-MSFT** [comment]
Engineering team is still investigating the issue. We will inform you once there is any update. Thanks!

**Comment by Prasad-MSFT** [comment]
@stejura-sfdc - Engineering team has identified the issue and fixing it. It will get rolled out in upcoming month. There is no specific ETA to share.

**Comment by varunk29** [comment]
any update on this?
