### ISSUE TITLE
Having issue on navigator.mediaDevices.getUserMedia({ audio: true, video: false }) on tab pop up screen.

### ISSUE THREAD

**Issue by Rashid-Cal4care** [OfficeDev/microsoft-teams-library-js#1024]
We are facing the issue on getUserMedia whlie only on popup screen and it stucks on that part of the code for a while, then it shows user permission denied error, without even ask for the user permission. 

But everything works fine on the normal tab.

**Comment by v-chetsh** [comment]
Can you please share some sample/code snippets or documentation link, so that we can check on it.

**Comment by Rashid-Cal4care** [comment]
Hi, i just have this simple function to test the permissions, but its not working
`function ackPermision(){		
		navigator.mediaDevices.getUserMedia({ audio: true, video: false })
			.then(function(stream) {
			console.log('Permission Done');
		}).catch(function(error) {
			console.log(error);
		});
	}`

**Comment by tdwhite0** [comment]
@Rashid-Cal4care @v-chetsh  Yes I see this issue too when popping out a tab, and also when trying to navigator.mediaDevices.getUserMedia from the meeting stage. I am using the Windows client. My app has the permission and it does work from a regular tab. The iframe that the popout tab and meeting stage use does look like its the same as the one for the regular tab, maybe its an electron issue.

**Comment by Meghana-MSFT** [comment]
Thanks for the information, we will look into it and update you.

**Comment by cal4carerv** [comment]
Hello 
Is there any solution on this?

**Comment by Meghana-MSFT** [comment]
Apologies for the delay in response. We are also able to reproduce the issue. But we do not see permission denied error in the popout tab. It is stuck and doesnt show anything in the console logs. In regular tab it shows Permission Done in console logs. We will report this to the engineering team. We will let you know on the updates.

**Comment by Meghana-MSFT** [comment]
@Rashid-Cal4care  - We got an update from the engineering team saying "We do not have device permission support in any of  React-rendered experiences (i.e. anything in the popped out windows or in meetings)".

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
