### ISSUE TITLE
Native Loading Indicator Not Showing

### ISSUE THREAD

**Issue by bcage29** [OfficeDev/microsoft-teams-library-js#1025]
Following this documentation to [Show a native loading indicator](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page#show-a-native-loading-indicator), I am trying to show the loading indicator in a task module. When loading, the task module shows a blank canvas (no loading indicator) and when `microsoftTeams.appInitialization.notifySuccess()` is called, the loaded DOM will appear.

Manifest version: 1.11
@microsoft/teams-js: 1.11.0
`"showLoadingIndicator": true,` is included in the manifest

**Comment by v-chetsh** [comment]
We will check on it from our end and get back to you.

**Comment by Prasad-MSFT** [comment]
@bcage29 - Could you please provide any repro steps or sample code you are referring to?
Please add your manifest as well if possible.

**Comment by bcage29** [comment]
1. From the compose box open the app
2. The bot returns back a URL to open a task module
3. Task module opens and shows a blank canvas
4. Async await code runs and returns
5. microsoftTeams.appInitialization.notifySuccess(); is called to let it know that the page has finished loading.
6. The fully loaded page in the task module shows correctly.

During the `async away fetch` call, the task module shows a blank canvas and doesn't render the spinner.

```ts
microsoftTeams.initialize();

// async await fetch

microsoftTeams.appInitialization.notifySuccess();
```

Manifest
```json
{
	"$schema": "https://developer.microsoft.com/json-schemas/teams/v1.11/MicrosoftTeams.schema.json",
	"manifestVersion": "1.11",
	"version": "1.0",
	"id": "{{MicrosoftAppId}}",
	"packageName": "com.microsoft.teams.samples",
	"developer": {
		"name": "Microsoft",
		"websiteUrl": "https://example.com",
		"privacyUrl": "https://example.com/privacy",
		"termsOfUseUrl": "https://example.com/tou"
	},
	"name": {
		"short": "New Form",
		"full": "New Form"
	},
	"description": {
		"short": "Create a New Form",
		"full": "Create a New Form"
	},
	"icons": {
		"outline": "icon-outline-32.png",
		"color": "icon-color-192.png"
	},
	"accentColor": "#FFFFFF",
	"bots": [
		{
			"botId": "{{MicrosoftAppId}}",
			"needsChannelSelector": false,
			"isNotificationOnly": false,
			"scopes": ["team", "personal", "groupchat"]
		}
	],
	"composeExtensions": [
		{
			"botId": "{{MicrosoftAppId}}",
			"commands": [
				{
					"id": "newForm",
					"type": "action",
					"context": ["compose"],
					"description": "New Form",
					"title": "New Form",
					"fetchTask": true
				}
			]
		}
	],
	"permissions": ["identity"],
	"showLoadingIndicator": true,
	"validDomains": ["*.example.com"]
}
```

**Comment by Abhikumar2193jan** [comment]
Hello I am also facing the same issue...
as previously my loader was coming  in Teams app for my application...
but know no loader was coming...

{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.11/MicrosoftTeams.schema.json",
  "manifestVersion": "1.11",
  "version": "1.7.0",
  "showLoadingIndicator": true,
  "id": "*******************************",
  "packageName": "com.microsoft.team.co",
  "developer": {
    "name": "*** ***",
    "websiteUrl": "https://www.crmnext.com/",
    "privacyUrl": "https://qag.us.crmnextlab.com/teamsapp/login/login",
    "termsOfUseUrl": "https://qag.us.crmnextlab.com/teamsapp/login/login"
  },
  "icons": {
    "color": "color.png",
    "outline": "outline.png"
  },
  "name": {
    "short": "Dev ****",
    "full": "Dev *** ***"
  },
  "description": {
    "short": "For testing",
    "full": "Testing "
  },
  "accentColor": "#FFFFFF",
  "configurableTabs": [
    {
      "configurationUrl": "https://qag.us.crmnextlab.com/teamsapp/Setup/FeatureForm?x=qx2turf8zw2jmjgxhpzqybsb9urkljqyv56kn3pq5nz8ljlarmjmenbtahhpt39bgvn7qa5gnz64a",
      "canUpdateConfiguration": true,
      "scopes": [
        "team",
        "groupchat"
      ],
      "context": [
        "channelTab",
        "privateChatTab",
        "meetingSidePanel",
        "meetingDetailsTab",
        "meetingChatTab"
      ]
    }
  ],
  "staticTabs": [
    {
      "entityId": "*****",
      "name": "Content",
      "contentUrl": "https://qag.us.crmnextlab.com/teamsapp/CRMNextObject/Home/Summary",
      "scopes": [
        "personal"
      ]
    },
    {
      "entityId": "about",
      "scopes": [
        "personal"
      ]
    }
  ],
  "permissions": [
    "identity",
    "messageTeamMembers"
  ],
  "validDomains": [
    "qag.us.crmnextlab.com"
  ]

**Comment by Prasad-MSFT** [comment]
Engineering team is looking into the issue. We will inform you once we get any further update. Thanks!

**Comment by Abhikumar2193jan** [comment]
> 

thanks...
I am waiting for it,,,

**Comment by Abhikumar2193jan** [comment]
Hello @Prasad-MSFT
hope you are doing well ...
Can you please update on the above issue by one we get fix ....
Thanks

**Comment by Prasad-MSFT** [comment]
Engineering team is investigating the issue. There is no such ETA to share. We will inform you once we get any further update. Thanks!

**Comment by Prasad-MSFT** [comment]
Hi @Abhikumar2193jan , @bcage29 - We got update from engineering team that this issue is fixed. Please do verify. Thanks!

**Comment by Nivedipa-MSFT** [comment]
We are closing this issue for now. Please feel free to reopen if required. Thanks!
