### ISSUE TITLE
Angular Change Detection on the tab does not work

### ISSUE THREAD

**Issue by MajaEffenberg** [OfficeDev/microsoft-teams-library-js#1035]
SKD version: 1.11.0
Angular 13

In our custom Angular tabs, the view does not automatically refresh when data is received. It seems that the change detection in Angular, which should ensure the automatic synchronization between the data of a component and its HTML template view does not work.

https://user-images.githubusercontent.com/89073193/160778033-156cc6b0-4f86-4bac-8487-43393eb2ec3b.mp4

The problem always appears in the Microsoft Teams App for Android and sometimes in the desktop version of the app. However, the data is always displayed correctly in the web app.

https://user-images.githubusercontent.com/89073193/160778042-b9522469-3c97-4c6c-bac6-48967aa9a9c3.mp4

**Comment by sayali-MSFT** [comment]
@MajaEffenberg-We are looking into this I will get back to you soon.

**Comment by v-chetsh** [comment]
@MajaEffenberg -  Have you tried forcefully rendering your components if there is any data change.
React is the alternative best solution for re-rendering the components or part of it, if there is any change in data.

**Comment by sayali-MSFT** [comment]
@MajaEffenberg -did you get chance to check the above suggestion?

**Comment by MajaEffenberg** [comment]
@v-chetsh If we force a change detection after receiving data with `ChangeDetectorRef.detectChanges()`, the component is rendered again and most of the data is displayed correctly. However, sometimes we need to force the change detection again with a few seconds timeout after receiving the data in order for the data to be displayed correctly.
But forcing the change detection to re-render the component to refresh the data should not be necessary in Angular as this should be automatically done by the app and works fine in teams web app.

**Comment by sayali-MSFT** [comment]
@MajaEffenberg - Could you please share sample which you have refer or any link so we can try it from our end?

**Comment by ChetanSharma-msft** [comment]
@MajaEffenberg - Hope you are doing well!!

Could you please share sample code snippets, which you have referred or any link so we can try it from our end?

**Comment by Wajeed-msft** [comment]
Closing this for now. Please re-open this with requested details.
