### ISSUE TITLE
Adaptive card, display preview file 

### ISSUE THREAD

**Issue by amitShimon1983** [OfficeDev/microsoft-teams-library-js#1045]
Hi, 
I'm sending an Adaptive card containing a deep link to a file in the "files" tab in 2 different ways and getting 2 different experiences

Sending an Adaptive card through a bot

Sending an Adaptive card through the compose extension

in #2 the file opens successfully as expected but in #1 Teams opens the browser and then goes back to the desktop app which is a bad experience

how can I solve that problem?

**This is the adaptive card I'm using Office 365 connector card in both its the same card exaclly**
`{
  contentType: "application/vnd.microsoft.teams.card.o365connector",
  content: {
    title: "attachments",
    sections: [
      {
        activityTitle: "<div style=\"width:99999px\"><b>From:</b> <span class=\"mp_address_group\"><span class=\"mp_address_name\">Amit Shimon</span> &lt;<a href=\"mailto:amitsharmonie@gmail.com\" class=\"mp_address_email\">amitsharmonie@gmail.com</a>&gt;</span></div>",
        activitySubtitle: "<b>To:</b> <span class=\"mp_address_group\"><span class=\"mp_address_name\">Amit Shimon</span> &lt;<a href=\"mailto:amits@harmon.ie\" class=\"mp_address_email\">amits@harmon.ie</a>&gt;</span> <p>Sun 04/03</p>",
      },
      {
        text: "<html><body>  <div style=\"display:flex;height:40px\">  <div style=\"height:40px;display:flex;border:1px solid gray;margin-right:10px;align-items: center;padding: 0px 5px;\"> <img style=\"margin-right:15px\" src=\"https://spoprod-a.akamaihd.net/files/fabric-cdn-prod_20200921.001/assets/item-types/32/pptx.png\" /> <div style=\"display:flex;flex-direction: column;margin-right:10px;overflow:hidden;text-overflow: ellipsis;\"><a href=\"https://teams.microsoft.com/l/file/0AE1ECE7-6152-4516-9145-46DF951AE30B?&fileType=pptx&objectUrl=https://MYSite.sharepoint.com/sites/TestTaskModule/_layouts/15/Doc.aspx?sourcedoc=%UNiqeId%7D&file=Broken%20access%20control%203.pptx&action=edit&mobileredirect=true&baseUrl=https://harmonie.sharepoint.com/sites/TestTaskModule&serviceName=teams&threadId=15:u2wJZ36OJmpLiZuTOs2YSs_7EL83sn_RUwaN3iP9nNg1@thread.tacv2&groupId=b1e9c8a7-654d-44f5-b5c8-9ef5c8028384\" style=\"max-width: 240px;white-space: nowrap;overflow: hidden;text-overflow: ellipsis;height: 20px;\">Broken access control.pptx</a><div style=\"font-size:0.9rem\">null B</div></div></div>    </div></body>\n      </html>",
      },
      {
        startGroup: true,
        activityText: "<html><head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"></head><body><div dir=\"rtl\"><br></div></body></html>\n",
      },
      {
        text: "<div style=\"position:absolute;width:6px;left:0;top:0;bottom:0;background-color:#6264A7\"></div>",
      },
    ],
    potentialAction: [
      {
        "@type": "OpenUri",
        "@id": "openBoard",
        name: "Open Task",
        targets: [
          {
            os: "default",
            uri: "https://teams.microsoft.com/l/task/7b543fab-bff2-4759-bde3-b1ecfc1977f2?url=https%3A%2F%2FMYDomain.ngrok.io%2Ftask-board%2Ftab?context=%7BchannelId:19:u3wJZ36OJmpLiZuTOs2YSs_7EL83sn_RUwaN3iP9nNg1@thread.tacv2,%20expandedTaskId:%20624989bbce4428dc419051b1,%20entityId:%20MYName@Domain.ie%7D&height=large&width=large",
          },
        ],
      },
      {
        "@type": "HttpPOST",
        "@id": "answerEmail",
        name: "👋 \t I Will Take It",
        body: "{\"taskId\": \"624989bbce4428dc419051b1\"}",
      },
    ],
  },
}`

**Comment by Nivedipa-MSFT** [comment]
@amitShimon1983 - We are investigating your query. We will get back to you once we have any update.

**Comment by amitShimon1983** [comment]
Thanks

**Comment by Nivedipa-MSFT** [comment]
@amitShimon1983 - Could you please share your code snippet (code for sending card in bot and in compose extension) to test at our end?

**Comment by amitShimon1983** [comment]
From the bot, this is my code
`
this.connectorClient = adapter.createConnectorClient(this.serviceUrl);
return await this.connectorClient?.conversations.createConversation({
      isGroup: true,
      channelData: { channel: { id: channelId } },
      activity: MessageFactory.attachment(newCard as Attachment) as Activity,
    } as ConversationParameters);

`
from the UI I'm using the client sdk
`
 microsoftTeams.tasks.submitTask({
      mailId,
      card,
   });
`

**Comment by Nivedipa-MSFT** [comment]
@amitShimon1983 - We are investigating your issue again. We will update you soon.

**Comment by Nivedipa-MSFT** [comment]
@amitShimon1983 - We have tested this scenario.
We have created an Adaptive card which contains a deeplink of file.
We have send this adaptive card through Bot using connectorClient.  File is opening in browser but its not going back to the desktop app.

We have used following code to send card.
   ```
         using var connector = new ConnectorClient(new Uri("XXXXXX"), appId, appSecret);
            var replyActivity = new Activity();
            replyActivity.Type = "message";
            replyActivity.Conversation = new ConversationAccount(id: "XXXXXXXX");
            var adaptiveAttachment = FetchConnector(filepath);
            replyActivity.Attachments = new List<Attachment> { adaptiveAttachment };
            var respons e = connector.Conversations.SendToConversationAsync("XXXXXXXXXX", replyActivity).Result;
```
Could you please check once and confirm that still you are facing this issue?

**Comment by ChetanSharma-msft** [comment]
@amitShimon1983 - Can you please check once and confirm whether you are still facing the issue or not?
