### ISSUE TITLE
iOS deeplink behaviour issue for a few days

### ISSUE THREAD

**Issue by LaurentSmeethy** [OfficeDev/microsoft-teams-library-js#1050]
Hello,

After one the last updates (could not pinpoint which), deeplinks no longer work as they should. What we do is we use deeplinks to a message in a team the user already has access to.

**What we do:**
Using a deeplink to the message (example: https://teams.microsoft.com/l/message/CHANNELID/1648702936306?groupId=TEAMID1&tenantId=TENANTID&createdTime=1648702936306&parentMessageId=1648702936306) we run microsoftTeams.executeDeeplink on click. It works on Desktop/Web & Android.

**What it yieds:**
Upon clicking on an element with a deeplink to a team, this is what it yields, asking for a permission to join? (The user is already in the target team.
![example](https://user-images.githubusercontent.com/48674899/162169117-4110a82a-ffc3-4996-8526-3342ca60b26c.png)

**What it should have done:**
Redirected the user to the teams message like it does on Android.

Please note that the code to run deeplinks did not change in a month so we're confident it is not on our end. Could you provide pointers?

BR,
Laurent

**Comment by Prasad-MSFT** [comment]
We are checking the issue. We will inform you once we get any information

**Comment by Prasad-MSFT** [comment]
We checked at our end, but it's working fine for us in Teams desktop, web, android and iOS as well.
Used deeplink to message : `microsoftTeams.executeDeepLink("https://teams.microsoft.com/l/message/{channelId}/1648741500652?tenantId={tenantId}&groupId={groupId}&parentMessageId=1648741500652&teamName={teamName}&channelName={channelName}&createdTime=1648741500652");`
Please update MS Teams version and check.
iOS Teams version details:
![image](https://user-images.githubusercontent.com/62237649/162197006-9350adc9-d45d-4e0f-9c06-bbc4788d3a35.png)

**Comment by LaurentSmeethy** [comment]
Hello,

No, i have the version 4.6.0 which is the latest (5 april on app store). The 4.4.0 is from early March. 

![IMG_0002](https://user-images.githubusercontent.com/48674899/162205610-c03a53c1-eb96-44e6-8294-8de9628a919c.PNG)

BR

**Comment by Prasad-MSFT** [comment]
@LaurentSmeethy - Could you please check deeplink to message format once ?
FYI we have this version of Teams as latest.

Used deeplink to message : microsoftTeams.executeDeepLink("https://teams.microsoft.com/l/message/{channelId}/1648741500652?tenantId={tenantId}&groupId={groupId}&parentMessageId=1648741500652&teamName={teamName}&channelName={channelName}&createdTime=1648741500652");

**Comment by LaurentSmeethy** [comment]
Hello,

So i tested with the link (pretty much the link we get from the 'Copy Link' option for a chat message) https://teams.microsoft.com/l/message/{channelId}/1648741500652?tenantId={tenantId}&groupId={groupId}&parentMessageId=1648741500652&teamName={teamName}&channelName={channelName}&createdTime=1648741500652.

Verdict, it works on iOS 4.6. But i still have a question regarding the disparities in how it work accross devices & versions.

For example, https://teams.microsoft.com/l/message/{channelId}/1648741500652?tenantId={tenantId}&groupId={groupId}&parentMessageId=1648741500652&createdTime=1648741500652 works fine on Android (Latest version) even on iOS on previous versions. But the change with the additional query parameters **&teamName={teamName}&channelName={channelName}** are not documented (useful when we want to dynamically generate deeplinks). Is this intended?

We're dynamically generating them, so that would be good to know before-hand (unless i missed a piece of documentation on breaking changes?).

Thank you.

**Comment by Prasad-MSFT** [comment]
There doesn't seem to be any official documentation mentioning the format of deeplink to conversation.

**Comment by karamem0** [comment]
Hi @Prasad-MSFT,
I met the same issue. I want to navigate to a team using team's URL like this `https://teams.microsoft.com/l/team/{teamId}/conversations?groupId={groupId}&tenantId={tenantId}`. Is it any progress?

Microsoft Teams app iOS version: 4.7.0

**Comment by Prasad-MSFT** [comment]
@karamem0 - Could you please try with below URL format instead of what you are using?
`https://teams.microsoft.com/l/team/{channelId}/conversations?groupId={groupId}&tenantId={tenantId}`

**Comment by karamem0** [comment]
@Prasad-MSFT I mean `{teamId}` is like `19%3aba1a14f7bb3f44f5b7be501abc4fc567%40thread.tacv2`. Is it same that you say `{channelId}`?

**Comment by Prasad-MSFT** [comment]
@karamem0 - Yes, and it works at our end

**Comment by v-chetsh** [comment]
@karamem0  - Could you please confirm if your issue has resolved with above suggestion or still looking for any help?

**Comment by karamem0** [comment]
@v-chetsh I still have the problem. I am using `@microsoft/teams-js@2.0.0-beta.6`.

```
import { app } from '@microsoft/teams-js';

app.openLink('https://...');
```

<img src="https://user-images.githubusercontent.com/4537204/167076841-985893bc-db43-4ec7-8295-8db1fff6e774.png" width="300px"/>

**Comment by Prasad-MSFT** [comment]
@karamem0 - Could you please use executeDeepLink as mentioned here:
https://docs.microsoft.com/en-us/microsoftteams/platform/m365-apps/using-teams-client-sdk-preview?tabs=manifest-teams-toolkit%2Cjavascript#core-namespace

**Comment by karamem0** [comment]
@Prasad-MSFT I found that `core.executeDeepLink` has been moved to `app.openLink` in `v2.0.0-beta.3`.
https://github.com/OfficeDev/microsoft-teams-library-js/releases/tag/v2.0.0-beta.3

**Comment by Prasad-MSFT** [comment]
@karamem0 - Could you please try with core.executeDeepLink and check if its working using that?

**Comment by karamem0** [comment]
@Prasad-MSFT

`core.executeDeepLink` does not exist in `@microsoft/teams-js@2.0.0-beta.6`. So I tried two ways:

- Use `executeDeepLink` (Marked as deprecated)
- Install `@microsoft/teams-js@2.0.0-beta.2` and use `core.executeDeepLink`.

But results are same and I could not resolve the issue.

The URL is like below:

<img src="https://user-images.githubusercontent.com/4537204/167247063-6ff16785-27f9-4646-b072-9ca0713d2930.png" width="320px" />

**Comment by Prasad-MSFT** [comment]
> Hi @Prasad-MSFT, I met the same issue. I want to navigate to a team using team's URL like this `https://teams.microsoft.com/l/team/{teamId}/conversations?groupId={groupId}&tenantId={tenantId}`. Is it any progress?
> 
> Microsoft Teams app iOS version: 4.7.0

Is the issue only specific to iOS? And is it only for this specific Teams version? Have u checked by upgrading or degrading the version ?

**Comment by karamem0** [comment]
@Prasad-MSFT Yes, iOS only. And I have updated latest version (4.7.2) but I could not resolve.

**Comment by LaurentSmeethy** [comment]
Hello,

Thank you for your feedback. However, there is another Deeplink issue on iOS which i am not sure we want to open it here as well but here it is.

Deeplink used is the one provided by a click on the team channel tab, then "Copy link to tab". With that link, we run executeDeeplink function from teams-js/ on it.

(It generates this deeplink: https://teams.microsoft.com/l/entity/2a527703-1f6f-4559-a332-d8a7d288cd88/_djb2_msteams_prefix_4161279558?context=%7B%22channelId%22%3A%22{channelID}%22%7D&tenantId={tenantID})

When we want to deeplink to a tab in teams, it works on Android and Desktop but not on iOS where we get a message:
"Link not supported".
![linkerror](https://user-images.githubusercontent.com/48674899/167816808-69f9d669-6e16-4cd8-81ae-04d2f9aa4d72.JPG)

I also updated to the last version 4.7.2 but the issue remains the same. I am sure it worked during the last months, done for our users and it is no longer working. (Unless if between the 1.10.0 of teamsjs and the current 1.12 there are breaking changes and we need to upgrade).

I doubt it is, but is it an expected behavior not to be able to deeplink to channels or tabs in those channels?

Thank you again for your help.
BR

**Comment by LaurentSmeethy** [comment]
Hello,

Yes, here it is.
In the code, we simply retrieve the Url and use executeDeeplink
`			<a className="cursor-pointer flex flex-grow gap-2" onClick={() => { microsoftTeams.executeDeepLink(props.linkUrl);}}>
				<Link labelTitle={props.linkName} />
				<Sublink labelTitle={props.linkCategory} />
			</a>`

The link that we use is generated by Teams through a right click on a channel tab "Get link to tab". This is that url we retrieve in the code and run executeDeepLink on (i.e https://teams.microsoft.com/l/entity/2a527703-1f6f-4559-a332-d8a7d288cd88/_djb2_msteams_prefix_4161279558?context=%7B%22channelId%22%3A%22{channelID}%22%7D&tenantId={tenantID})

Is it enough for you to investigate?

Thank you,
BR

**Comment by Prasad-MSFT** [comment]
@LaurentSmeethy - We tried with below deeplink as mentioned by clicking 'Copy link to tab' and it worked for us. Its getting redirected to particular tab.

```
 microsoftTeams.executeDeepLink("https://teams.microsoft.com/l/entity/b6fa50ae-6a60-4c23-b3fe-b8f2feb77282/_djb2_msteams_prefix_4215212359?context=%7B%22channelId%22%3A%2219%3A787993ede7dd48718a049acd303b05a7%40thread.tacv2%22%7D&tenantId=36a708ef-700d-4d60-9de0-0a5f7b7693df");
```

**Comment by karamem0** [comment]
@Prasad-MSFT Could you please check this?
https://github.com/karamem0/teamtile/blob/main/source/client/src/components/team-card/container.tsx
