### ISSUE TITLE
Trying to close MS Teams meeting app sidepanel view programatically

### ISSUE THREAD

**Issue by shafaaf** [OfficeDev/microsoft-teams-library-js#1059]
Hi, I developed an MS Teams meeting app which based on documentation, when added to a meeting would have a tab-config dialog for example like below: 
![Screen Shot 2022-04-11 at 3 20 26 PM](https://user-images.githubusercontent.com/7485184/162814100-b53f90c5-daff-4062-bbc9-8799d124f67f.png)

After we click Save, we would get the sidepanel view of the app for example like here: 
![Screen Shot 2022-04-11 at 3 19 05 PM](https://user-images.githubusercontent.com/7485184/162814061-587e21f7-fee5-4cfa-9ca9-fe87b191e445.png)

I am wondering if there is an meeting api available to close the sidepanel view  or close the app programmatically rather than the user clicking the cross icon or removing the app.

Thanks!

**Comment by Meghana-MSFT** [comment]
@shafaaf - Currently there is no option to close the meeting sidepane programmatically.
