### ISSUE TITLE
Configurable icons and titles from manifest.json

### ISSUE THREAD

**Issue by v-royavinash** [OfficeDev/microsoft-teams-library-js#1062]
Hi Team,

We have created the team's custom app. The manifest folder contains the icons and the manifest json. 

![image](https://user-images.githubusercontent.com/94480537/162980732-bac22ae2-6c64-4715-b2fe-93fc82a664d3.png)

The app Icon and title can be configured from the Manifest ZIP. Is there any way to access the Icons and titles from the manifest folder by the teams-js to create our own customs designs which can be customized during the deployment?

![image](https://user-images.githubusercontent.com/94480537/162981622-1cbd4690-f823-4244-a263-e6ee76d79ed1.png)

**Comment by sayali-MSFT** [comment]
@v-royavinash -We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
@v-royavinash - There is no way to access the icon from the manifest. But after uploading app you can customized  icon through [Admin ](https://admin.teams.microsoft.com/)portal.

**Comment by sayali-MSFT** [comment]
@v-royavinash - Could you please confirm if your issue has resolved with above suggestion or still looking for any help?
