### ISSUE TITLE
How can I be notified when the current tab is closed or toggled

### ISSUE THREAD

**Issue by simon5057** [OfficeDev/microsoft-teams-library-js#1079]
Hi there! 
I need to do something when my tab(and task module view) is closed or toggled. Please tell me what I should do. 
Thanks!

**Comment by Prasad-MSFT** [comment]
Could you please provide more details on your ask?

**Comment by simon5057** [comment]
It's like listening for the `unload` event in the browser, which is triggered when the window resource will be unloaded. Is there a similar event that can be listened to via the SDK when the Personal Tab/Teams tab is closed by some action in Teams (e.g. switch Tab, or switch channel. As shown in the image below when the user clicks on the red box area causing my tab to be closed)?
![image](https://user-images.githubusercontent.com/28774478/163509387-32f1a5fd-a222-48aa-a47f-1c7067bb5e8b.png)

Or can I do what I want to do by listening to the `unload` event, like sending a log collection
Thanks!

**Comment by Prasad-MSFT** [comment]
Currently there doesn't seem to have any such event.

**Comment by simon5057** [comment]
Thank you, I have found that the `unload` event can work properly.
