### ISSUE TITLE
Configuration tab 'next' option?

### ISSUE THREAD

**Issue by benpolinsky** [OfficeDev/microsoft-teams-library-js#109]
Hi. 

I just noticed how SharePoint's Teams App configuration presents a wizard-like behavior to the user, where after each 'step' is finished the save button changes to a 'next' button, finally changing to 'save' after all steps have been completed.

Any chance this will trickle down into the library? 

Space for configuration is a concern: I've seen other apps doing configuration in a non-config tab, presenting only authorization to the user in the config tab. 

Obviously I can implement my own little wizard that doesn't rely upon the save button until all steps are complete, but this would be a nice 'recommended' way of dealing with the configuration tab's small real estate.

Thanks!

**Comment by arun-msft** [comment]
Hi @benpolinsky , 
Could you please share the screenshot which you are able to see for SharePoint's configuration?

**Comment by benpolinsky** [comment]
Sure. It's actually the 'document library' app:

![teams-wizard](https://user-images.githubusercontent.com/10874030/40181331-db3569e0-59b6-11e8-97ba-143f411e3409.PNG)

**Comment by Wajeed-msft** [comment]
We don’t have public support to be able to build this streamlined experience yet.

**Comment by billbliss** [comment]
While the extensible tabs platform does not support this type of experience directly, you could implement it yourself inside the configuration pane.
