### ISSUE TITLE
submitHandler not called when dialogs closed with X on Mobile 

### ISSUE THREAD

**Issue by itstaby** [OfficeDev/microsoft-teams-library-js#1104]
Tested with release [v2.0.0-beta.4](https://github.com/OfficeDev/microsoft-teams-library-js/releases/tag/v2.0.0-beta.4).

Dialogs are not calling completion callbacks on mobile if they're closed using the X sign at the top.
The dialog is successfully closed, but the callback is not triggered.

**Comment by Nivedipa-MSFT** [comment]
@itstaby - We are investigating your query. We will inform you once we have any update.

**Comment by Nivedipa-MSFT** [comment]
@itstaby - Could you please share which sample are you referring for this?

**Comment by itstaby** [comment]
Hey, if you mean code sample, I'm not sure how to share that with you. 
Here's a screen recording of the same code running on teams desktop and iOS. I added an alert in the submit handler, but it only triggers on desktop.

Desktop: https://www.loom.com/share/71ab887a68dc4157825d0d4b8eeae881 (Alert will pop up)
Mobile: https://www.loom.com/share/5d543b13dc064634a2c8c2e68b1e35c9 (No alert)

**Comment by itstaby** [comment]
Looks like this is specific to iOS.

**Comment by Nivedipa-MSFT** [comment]
@itstaby - Could you please share some minimal code to test at our end?

**Comment by v-chetsh** [comment]
@itstaby - If you are following any Microsoft docs, can you please share ?

**Comment by Nivedipa-MSFT** [comment]
@itstaby - Could you please share on which mobile OS (IOS or Android) are you facing the issue?

**Comment by itstaby** [comment]
I'm testing this on iOS, and not currently following any documentation. I had ported my app using the initial MetaOS developer milestone documentation. The latest documentation shared with me is [this](https://docs.microsoft.com/en-us/microsoftteams/platform/m365-apps/overview).

**Comment by Nivedipa-MSFT** [comment]
@itstaby - We are investigating this. We will update you soon.

**Comment by sunziping2016** [comment]
I have experienced the same issue on Android. I can make a repro repo if you need. Besides `submitHandler`, `postMessage`/`PostMessageChannel` seems not working as well. This problem seems to exist in both v1.9.0 and v2.0.0 on latest Android Microsoft Teams (Version: 1416/1.0.0.2022294302/0524).

**Comment by Nivedipa-MSFT** [comment]
@itstaby - We are checking the status of the bug with the engineering team. We will let you know once we have any update on it.

**Comment by ChetanSharma-msft** [comment]
I apologize for delay in response.
We are actively checking the status of bug fixes with engineering team and will update this thread, once it is fixed.

Thanks!!

**Comment by SaiPratap-MSFT** [comment]
@sunziping2016  - Issue is resolved, we have tested this in android version 13 and IOS version 16.2  in teams version 1416/1.0.0.2023203702  and SDK VERSION-v1.9.0 and v2.0.0

Could you please check and confirm the same.

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
