### ISSUE TITLE
Can't detect whether application is in Teams environment

### ISSUE THREAD

**Issue by benlieber-codaio** [OfficeDev/microsoft-teams-library-js#1150]
Similar question as reported in this issue - https://docs.microsoft.com/en-us/answers/questions/382718/detect-whether-website-is-being-hosted-within-a-te.html - it would be great if the Microsoft Teams JS lib provided a canonical way to determine whether you are in a teams environment. Is there a recommended pattern currently that is more robust than checking the window name?

**Comment by AE-MS** [comment]
We made a fix to the 2.0 TeamsJS library to allow an app to call `initialize()` and leverage the rejected promise to determine if it's running inside a supported host application (Teams, Outlook, or Office). The call to `initialize()` will timeout (and reject the promise) if the app is not being hosted in one of those M365 applications. Is this the sort of thing you are looking for?
PR: #730 
This was to address the issue discussed in #719

**Comment by benlieber-codaio** [comment]
Appreciate the prompt response. I think this question is indeed similar to the one you pointed out.

Sort of what I'm looking for - ideally would be able to detect based on the environment without making a network call (not ideal as in many scenarios our app also won't be used in a Teams context). I think the sentiment in this comment form the issue you linked captures it https://github.com/OfficeDev/microsoft-teams-library-js/issues/719#issuecomment-985945866

**Comment by AE-MS** [comment]
> Appreciate the prompt response. I think this question is indeed similar to the one you pointed out.
> 
> Sort of what I'm looking for - ideally would be able to detect based on the environment without making a network call (not ideal as in many scenarios our app also won't be used in a Teams context). I think the sentiment in this comment from the issue you linked captures it [#719 (comment)](https://github.com/OfficeDev/microsoft-teams-library-js/issues/719#issuecomment-985945866)

Calling `app.initialize()` does not require a network call. Can you elaborate on the situation you are concerned about? Maybe there is some environment that I'm not familiar with?

**Comment by benlieber-codaio** [comment]
> Calling `app.initialize()` does not require a network call. Can you elaborate on the situation you are concerned about? Maybe there is some environment that I'm not familiar with?

Indeed this seems not to be the case. I think the recommended solution will work, will report back if otherwise, thanks kindly for the help!

**Comment by AE-MS** [comment]
> > Calling `app.initialize()` does not require a network call. Can you elaborate on the situation you are concerned about? Maybe there is some environment that I'm not familiar with?
> 
> Indeed this seems not to be the case. I think the recommended solution will work, will report back if otherwise, thanks kindly for the help!

Absolutely! Please feel free to post back here or open a new issue if you find that it doesn't work for your scenario. Thanks!
