### ISSUE TITLE
v1.12.1 cdn link returns blob not found

### ISSUE THREAD

**Issue by TheBluLion** [OfficeDev/microsoft-teams-library-js#1169]
https://statics.teams.cdn.office.net/sdk/v1.12.1/js/MicrosoftTeams.min.js" integrity="sha384-HmRb1xX74v8jZiukR88bXWmRgVO/3uU7eHP64Ng+fnU0kc9JPBauRiQCPkvEtSGF

returns 
<Error>
<Code>BlobNotFound</Code>
<Message>The specified blob does not exist. RequestId:2f19716c-301e-006a-54a8-64c9a6000000 Time:2022-05-10T20:02:40.3094761Z</Message>
</Error>

**Comment by Prasad-MSFT** [comment]
@TheBluLion - Could you please provide more details or any repro steps so that we can check from our end?

**Comment by TheBluLion** [comment]
You can browse to the url referenced in our documents or add the script source to a html page as described in the instructions.

both methods generate a 404 error.

https://statics.teams.cdn.office.net/sdk/v1.12.1/js/MicrosoftTeams.min.js" integrity="sha384-HmRb1xX74v8jZiukR88bXWmRgVO/3uU7eHP64Ng+fnU0kc9JPBauRiQCPkvEtSGF

**Comment by Prasad-MSFT** [comment]
Please follow below docs and check if you are missing anything:
https://docs.microsoft.com/en-us/azure/cdn/cdn-troubleshoot-endpoint
https://elcamino.cloud/articles/2020-03-30-azure-storage-blobs-net-sdk-v12-upgrade-guide-and-tips.html

**Comment by AE-MS** [comment]
Hi @TheBluLion, thanks so much for bringing this issue to our attention. It looks like something went wrong when we released v1.12.1 and it only got published to npm and not the CDN -- and our release validation didn't catch it. We will be looking into the issue ASAP to resolve it and get the latest package published to the CDN. We appreciate you reporting this issue!

**Comment by AE-MS** [comment]
One small update here: the [2.0 release](https://www.npmjs.com/package/@microsoft/teams-js/v/2.0.0) of the library is now available and has been [published to the CDN](https://res.cdn.office.net/teams-js/2.0.0/js/MicrosoftTeams.min.js). If you are able to consider using that newer version, the CDN option is available to you again.

We are still looking into the technical issue blocking the publishing of 1.12.1. Thanks for your patience with this.

**Comment by TheBluLion** [comment]
Thank you

**Comment by AE-MS** [comment]
@TheBluLion This issue should now be resolved and the link from your initial post now works.
