### ISSUE TITLE
Image is displaced when single image is viewed with media.viewImages

### ISSUE THREAD

**Issue by ngRevan** [OfficeDev/microsoft-teams-library-js#1188]
Hello everyone

I don't know if this issue belongs here but I wouldn't know where else to put this.

I've got the problem that when I try to view a single image via `media.viewImages`, the image gets displaced/transformed to the top left corner.
<img width="360" alt="Teams Picture Bug" src="https://user-images.githubusercontent.com/16115801/169978154-07f65fed-1d08-4a63-b046-e045ec2cfb0e.png">

I'm currently using version 1.11 of teams js but I also tried it out with version 2. I guess it's more of a problem with the native image viewer.

**Comment by Meghana-MSFT** [comment]
Could you please share any sample/documentation you are referring to?

**Comment by Meghana-MSFT** [comment]
We are checking this issue, we will update you.

**Comment by Meghana-MSFT** [comment]
We were able to repro this issue in library version 1.12.0 and version 2.0.0. We have raised a bug for the same. We will keep you posted on the updates.

**Comment by goamn** [comment]
> We were able to repro this issue in library version 1.12.0 and version 2.0.0. We have raised a bug for the same. We will keep you posted on the updates.

Any updates on this? Thank you

**Comment by Meghana-MSFT** [comment]
The team is looking into the bug. Currently we do not have any update to share.

**Comment by goamn** [comment]
Hello @Meghana-MSFT, are there any updates for this?

**Comment by Meghana-MSFT** [comment]
@goamn - We do not have any update to share. I will post here as soon as we have any update. Thanks.

**Comment by goamn** [comment]
Hi @Meghana-MSFT, is there any update on this?

**Comment by Meghana-MSFT** [comment]
Engineering team is working on the Fix, we do not have any exact timelines to share. We will keep you posted on the updates.

**Comment by Meghana-MSFT** [comment]
@ngRevan - Issue is fixed and the fix is now available publicly.

**Comment by goamn** [comment]
@Meghana-MSFT Is the fix available in v2.4.1?

**Comment by Meghana-MSFT** [comment]
Team has informed that since the fix is on Teams side and not on npm package (SDK), it should be available in all versions including v2.4.1.

**Comment by goamn** [comment]
Ok great thanks, it's working now. I guess this ticket can be closed now?

**Comment by Meghana-MSFT** [comment]
Thank you for confirming. We will close the question. Please feel free to reach out if you have any issues. Thank you.
