### ISSUE TITLE
Should err in the completion handler be a string, or an Error object?

### ISSUE THREAD

**Issue by billbliss** [OfficeDev/microsoft-teams-library-js#120]
https://github.com/OfficeDev/microsoft-teams-library-js/blob/7fece089ec1a5ff5bf9b829aaa6b2868f5c2833b/src/MicrosoftTeams.ts#L1949

Should this be:
```typescript
 completionHandler?: (err: Error, result: string) => void 
```
instead?

**Comment by ydogandjiev** [comment]
As discussed offline we are sticking with a simple string error for now. Will re-evaluate in the future if this becomes a problem.
