### ISSUE TITLE
Context returned from app.getContext does not contain expected userInfo properties. displayName is missing

### ISSUE THREAD

**Issue by donaldmcn** [OfficeDev/microsoft-teams-library-js#1202]
I am developing a Teams Tab App, and recently upgraded to the V2.0 version of the SDK.

When I get the context using the app.getContext() API, its promise resolves to a context object that looks like the following (personal data has been removed)

context: {
  "app":{
    "locale":"en-us",
    "sessionId": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "theme":"default",
    "iconPositionVertical":23,
    "parentMessageId":"",
    "userClickTime":1654625022255,
    "userFileOpenPreference":"web",
    "host":{
      "name":"Teams",
      "clientType":"web",
      "sessionId":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      "ringId":"ring1"
      },
    "appLaunchId":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  },
  "page":{
    "id":"arcade",
    "frameContext":"content",
    "subPageId":"",
    "isFullScreen":false,
    "isMultiWindow":false,
    "sourceOrigin":null
  },
  "user":{
    "id":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "licenseType":"Unknown",
    "loginHint":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "userPrincipalName":"XXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "tenant":{
      "id":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      "teamsSku":"enterprise"
    }
  },
  "chat":{
    "id":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"},
    "meeting":{"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  },
  "sharePointSite":{
    "teamSiteUrl":"",
    "teamSiteDomain":"XXXXXXXXXXXXXXXXXXXXXX",
    "teamSitePath":"",
    "mySitePath":"XXXXXXXXXXXXXXXXXXXXXXXXXX"
  }
}

I am expecting that the user: {} object should have had displayName filled in, based on the SDK documentation.

**Comment by Nivedipa-MSFT** [comment]
@donaldmcn - We are investigating your query. We will get back to you once we have any update.

**Comment by AE-MS** [comment]
The `displayName` field is optional so some hosts may choose not to provide it in different circumstances. Hopefully this is reflected in the typing on the property by the question mark:
https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/app.userinfo?view=msteams-client-js-latest#@microsoft-teams-js-app-userinfo-displayname

**Comment by AE-MS** [comment]
Thanks for helping provide the feedback for this! Can you suggest a clearer way for us to consider indicating to developers that a field may or may not be included?

If having that data is required for your scenario, you could consider using a token retrieved from calling [`authenticate.getAuthToken()`](https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/authentication?view=msteams-client-js-latest#@microsoft-teams-js-authentication-getauthtoken) to call the [`/me` endpoint on the Graph API](https://docs.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0&tabs=http#http-request) and use the `displayName` property from the response.

**Comment by MarcinJuraszek** [comment]
In addition to what Aaron said, this is a fairly new context property. Because of that, we can't really guarantee it's available on all the already shipped versions of Teams/Outlook/Office across different platforms. We're working on getting this information exposed from as many hosts as possible, but until we can get to all of them and make sure majority of users updated their clients to versions with that new context property exposed, your code should be resilient to it not being present. That's true to not just this property.

**Comment by Nivedipa-MSFT** [comment]
@donaldmcn - Could you please confirm what exactly you want to indicate that a field may or may not be included?

**Comment by donaldmcn** [comment]
I would recommend putting something in the documentation that indicates what apps / platforms the property is supported on.

**Comment by Nivedipa-MSFT** [comment]
@donaldmcn - We will check the displayName property on different platform and inform engineering team accordingly

**Comment by MarcinJuraszek** [comment]
IMO adding information on what hosts/platforms properties are available to documentation seems like a bad idea, as it's very likely it'll eventually run out of sync with reality. Also, I'm not 100% sure how helpful it is, as you'd still need to make sure your app can work around it not being present.
