### ISSUE TITLE
isFullScreen true not available for store applications

### ISSUE THREAD

**Issue by plamber** [OfficeDev/microsoft-teams-library-js#1204]
Hello,
I hope this channel is right to provide this type of feedback. 

We have a personal app application that is being published to the Microsoft Store. Our application has the requirement for providing dynamic navigation based on the settings configured by an administrator. Mainly, for this reason, we have to provide second-level navigation to guide our users. Unfortunately, the Teams navigation and our second-level navigation consume a lot of space. Lately, we found the setting isFullScreen which allows us to hide the Teams navigation and shows only the application content. This is exactly what we were looking for. Unfortunately, this setting is only available for org-store applications as stated [here](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#isfullscreen).

I would like to ask you how we could achieve this type of result like some of your applications are doing:
![image](https://user-images.githubusercontent.com/18241305/172758297-69c6b1d1-1308-4ef0-a592-3b504c72408b.png)

- Tasks by Planner and To Do has an extension of the menu in the upper right corner and no additional tabs

![image](https://user-images.githubusercontent.com/18241305/172758332-dc26766f-b4f0-46a7-9079-783dbd213143.png)
- Approvals has two tabs and an action button in the upper right corner

I was hoping to find a way to achieve the same goal with our application.

Thank you,
Patrick

**Comment by MarcinJuraszek** [comment]
This functionality is not available to non-Microsoft built applications published to Store. I'm afraid what you're trying to do isn't possible at this time.

**Comment by plamber** [comment]
Hello @MarcinJuraszek,
thank you for your feedback. 

Do you think it might be possible to share the concerns why this capability is available for org apps only?

Thank you,
Patrick

**Comment by MarcinJuraszek** [comment]
I can't speak for the team that made the decision, but I can think of one big reason - not having the header there with the name of the app for the user to see makes it very hard for them to know what it is they are interacting with. And for external application we can't really control if the app itself makes it crystal clear that it is indeed and app, and not part of Teams client itself. In addition to being potentially confusing, it opens up doors for things like phishing attacks.

**Comment by plamber** [comment]
Thank you @MarcinJuraszek for your feedback. Your thoughts about this topic are highly appreciated. 

The apps coming from the store undergo a validation from the app submission team. They are already ensuring that most design guidelines are applied to an app. In theory, the first issue could be solved with some additional design guidelines.
I think the phishing attack problem remains for apps that are in full screen or not. The only difference is that I am seeing a header coming from Microsoft. 

I am going to close the issue here for now since you answered all my open questions.

Thank you again,
Patrick
