### ISSUE TITLE
'appInstallDialog.openAppInstallDialog()' does not work

### ISSUE THREAD

**Issue by karamem0** [OfficeDev/microsoft-teams-library-js#1207]
The install diaog does not open when called `appInstallDialog.openAppInstallDialog()` function. The loading icon remains visible all the time.

![image](https://user-images.githubusercontent.com/4537204/172966402-88f12f62-47df-4a40-a02a-b2f8aca05c46.png)

`appInstallDialog.openAppInstallDialog()` is tring to open `https://teams.microsoft.com/_#/l/app/{appId}/`.  But correct URL is `https://teams.microsoft.com/_#/l/app/{appId}`. (The slash must not be added)

**Comment by jadahiya-MSFT** [comment]
This isn't what we expect to happen, I will investigate and then provide an update here once that is done.

**Comment by jadahiya-MSFT** [comment]
I found the root of the issue and have a PR out for the fix here https://github.com/OfficeDev/microsoft-teams-library-js/pull/1208

**Comment by jadahiya-MSFT** [comment]
@karamem0 This fix has now been merged in, I will close this issue once you have verified this.

**Comment by karamem0** [comment]
Thanks, it works fine!
