### ISSUE TITLE
optional submitHandler in dialog.open not checked before use 

### ISSUE THREAD

**Issue by antpowell** [OfficeDev/microsoft-teams-library-js#1210]
Although submitHandler is optional in the signature of dialog.open, it doesn't get checked before trying to use it in sendMessageToParent function causing an error and fail out without an explanation why.

[dialog.ts](https://github.com/OfficeDev/microsoft-teams-library-js/blob/release/2.0.0/packages/teams-js/src/public/dialog.ts)

error message from console:
![image](https://user-images.githubusercontent.com/10569986/173418874-3cf4f561-e654-4b54-aa77-53fc55db5def.png)
![image](https://user-images.githubusercontent.com/10569986/173419483-ef6f1a76-7b40-4c41-9299-773bfc3edec4.png)

**Comment by MarcinJuraszek** [comment]
@lakhveerk can you take a look?

**Comment by lakhveerk** [comment]
Thank you for catching this Anthony! I am working to fix the bug :)

**Comment by MarcinJuraszek** [comment]
Closing now that the fix is in. This will be released with next version.
