### ISSUE TITLE
microsoftTeams.tasks.submitTask not working with SDK v2

### ISSUE THREAD

**Issue by rabwill** [OfficeDev/microsoft-teams-library-js#1211]
When upgrading to the Teams JavaScript SDK v2, we are unable to get the microsoftTeams.tasks.submitTask() function working to our existing demo sample. It works as-is with the old version of SDK.
we also tried converting the tasks to dialog but looks like the submitHandler is not called when dialog.submit() is invoked.
Please see the code for any triage and advise on what can be done. https://github.com/microsoft/app-camp/pull/39/files. Thanks.

**Comment by AE-MS** [comment]
@lakhveerk In case you were short on things to investigate.  ;-)

**Comment by Nivedipa-MSFT** [comment]
@rabwill - We are investigating your query. We will get back to you once we have any update.

**Comment by lakhveerk** [comment]
Hello! 
This is a known issue in >2.0.0-beta.4 versions, that when you submit a dialog without any appIds (optional parameter), the dialog.sumit does not work properly. A fix for this is in place, but not out yet. 
Meanwhile, could you try 2.0.0-beta.4 and let us know if you see the same issue?

**Comment by lakhveerk** [comment]
For a work around, you can call dialog.submit (or tasks.submitTask) using your appID. Even though the appId is an optional parameter, it will help to get past this bug. 
The fix in Teams code is already in R3 and will take around 3 weeks to get into the general ring.

**Comment by rabwill** [comment]
@lakhveerk yes the workaround with the appId works thanks for that, but noticed the return params in submitHandler function now has changed. It now returns a single object parameter containing both err and result. So in my code I had to replace 
```
let submitHandler = (err, result) => { //use result }
```
to 
```
 let submitHandler = (response) => {  //use response.result }
```

This is interesting so, is it going in a direction where the dialog.open could be a promise rather than the do a callback.

**Comment by lakhveerk** [comment]
Yes, the submitHandler was changed to take one object along with many other changes that we made for v2. You can see the changelog [here](https://github.com/OfficeDev/microsoft-teams-library-js/blob/main/packages/teams-js/CHANGELOG.md#200).

There is no plan to use promises over callbacks for dialogs.

**Comment by Nivedipa-MSFT** [comment]
@rabwill - We are closing this issue now. Please feel free to reopen if required.
