### ISSUE TITLE
getUserJoinedTeams throw errors in Teams Channel 2.0

### ISSUE THREAD

**Issue by NewFuture** [OfficeDev/microsoft-teams-library-js#1212]
Hi team.
We got an error when getUserJoinedTeams(with v1.x Teams SDK) in Teams Channel 2.0.

> Error in processing request: getUserJoinedTeams with error No joinedTeamsService provided

is it a bug?

**Comment by NewFuture** [comment]
![image](https://user-images.githubusercontent.com/6290356/174001743-1842fd67-4cc0-4e50-97d3-9977694d6db5.png)
@Prasad-MSFT
1. open channel 2.0
2. create an ComposeExtension TaskModule App and Open it in the channel
3. call `getUserJoinedTeams`  from the SDK

**Comment by NewFuture** [comment]
@Prasad-MSFT switch Teams to ring0, and then you can select Channel 2.0

**Comment by Prasad-MSFT** [comment]
@NewFuture - Got it. Could you please share the sample you are referring where you called `getUserJoinedTeams` ?

**Comment by Prasad-MSFT** [comment]
There is already bug raised for this. We have assigned the bug to engineering team. We will inform you once we get any update . Thanks!

**Comment by tdwhite0** [comment]
> @Prasad-MSFT switch Teams to ring0, and then you can select Channel 2.0

How do you switch Teams to ring0? There are things I would like to test on ring0.

**Comment by Prasad-MSFT** [comment]
Switch to Ring R0 by as below:
![image](https://user-images.githubusercontent.com/62237649/174720948-d0c8420d-998b-440b-afd5-fc48e828ae6a.png)
 then turn on Channel2.0 in Ring0 as below:
 
![image](https://user-images.githubusercontent.com/62237649/174721027-b82b7c84-f6fb-49ce-9184-93e1cb4131d1.png)

**Comment by Prasad-MSFT** [comment]
@NewFuture - Engineering team is not able to repro the issue and at our end also we are not able to repro it.
Please refer the bug which was raised by you for updates.
