### ISSUE TITLE
calendar.isSupported() should return true but returns false instead?

### ISSUE THREAD

**Issue by ftliou** [OfficeDev/microsoft-teams-library-js#1222]
I have installed the latest release of teams-js library (2.0.0), wanting to try out the `calendar.composeMeeting()` function from my custom app/tab inside windows teams desktop app, however when I called `calendar.isSupported()` it returned false, thus blocking my pursuit...

Am I missing something? From documentation it says calendar capability is supported by Teams & Outlook hosts. https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/using-teams-client-sdk?tabs=javascript%2Cmanifest-teams-toolkit#microsoft-365-support-running-teams-apps-in-office-and-outlook

Btw I have actually tried to modify MicrosoftTeams.js source code to return true, and was able to successfully call `composeMeeting()`.

Code snippet:
```
  const createBooking = useCallback(() => {
    alert(`${chat.isSupported()}, ${calendar.isSupported()}, ${conversations.isSupported()}`)
    // print true, false, true
    if (calendar.isSupported()) {
      const calendarPromise = calendar.composeMeeting({
        attendees: [],
        content: "test content",
        // endTime: "2018-10-24T10:30:00-07:00"
        // startTime: "2018-10-24T10:00:00-07:00"
        // subject: "test subject"
      })
        .then((result) => {})
        .catch((error) => {
          alert(error.message)
        });
    }
```

**Comment by sayali-MSFT** [comment]
@ftliou - We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
@ftliou - Please have look into this -https://github.com/OfficeDev/msteams-docs.ru-RU/blob/d9630fa4457b126d5e2e6937506fcc93cf7011aa/msteams-platform/concepts/build-and-test/deep-links.md#teamsjs-%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D0%B8-2-2
hope it's helpful.

**Comment by AE-MS** [comment]
Hi @ftliou! Thanks for raising this issue. Unfortunately, Teams as a host has not yet fully implemented the `calendar` capability so it cannot yet be used in Teams for showing the scheduling dialog. Once Teams is able to provide an implementation for all the functions in this capability (both `openCalendarItem` and `composeMeeting`), it will be able to be used in the way you are attempting. Currently, only Outlook supports the `calendar` capability.

You can still use the original deep-link URL-based way of opening the scheduling dialog in Teams:
```
// Open a scheduling dialog from your tab
microsoftTeams.executeDeepLink("https://teams.microsoft.com/l/meeting/new?subject=test%20subject&attendees=joe@contoso.com,bob@contoso.com&startTime=10%2F24%2F2018%2010%3A30%3A00&endTime=10%2F24%2F2018%2010%3A30%3A00&content=​​​​​​​test%3Acontent​​​​​​​​​​​​​​");
```

The documentation here is incorrect and should be fixed. I have filed two documentation bugs to correct the issues until Teams has added support for the `calendar` capability:
https://github.com/MicrosoftDocs/msteams-docs/issues/6302
https://github.com/MicrosoftDocs/msteams-docs/issues/6303

Sorry for the error in the docs!
