### ISSUE TITLE
Invite participant SDK functionality

### ISSUE THREAD

**Issue by artsiomrusak** [OfficeDev/microsoft-teams-library-js#1224]
Hello!

After looking through the SDK, unfortunately, I didn't find any way to _invite someone to already existing call programmatically_?

Could you please help to understand whether such SDK functionality exists in general?

Thanks!

**Comment by artsiomrusak** [comment]
Thanks a lot for quick response!

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
