### ISSUE TITLE
Unable authenticate on MS Teams Desktop App with MSAL v2

### ISSUE THREAD

**Issue by tiennguyen1293** [OfficeDev/microsoft-teams-library-js#1229]
## Object
- Because user logged in on Teams Desktop App, the user doesn't need to re-login in App on Tab. I'm researching and found Silent Auth solution. but it's not working. Please help me investigate this issue. Thanks

## Library
```
"@azure/msal-browser": "^2.26.0",
"@microsoft/teams-js": "^2.0.0",
```

## Template
Using template [tab-aad-msal2](https://github.com/pnp/teams-dev-samples/tree/main/samples/tab-aad-msal2)

## Description
`instance.loginRedirect()` func working on Teams Web, but not working on Teams Desktop App

```
instance.loginRedirect({
      ...loginRequest,
      prompt: "none"
});
```

## Error Message
- InteractionRequiredAuthError: AADSTS50058: A silent sign-in request was sent but no user is signed in. The cookies used to represent the user's session were not sent in the request to Azure AD. This can happen if the user is using Internet Explorer or Edge, and the web app sending the silent sign-in request is in a different IE security zone than the Azure AD endpoint (login.microsoftonline.com). Trace ID: f6450045-e435-4fa7-8dcb-b1e7da7f2300 Correlation ID: b88afb3e-7b95-48fc-a68e-5875238dd1d3 Timestamp: 2021-01-28 08:56:59Z

## Reproduction Steps
1. Login in Microsoft Teams Desktop App
2. Select Tab
3. Click Login
4. Observe popup authenticate shown.
5. Open devTool in Iframe Auth
6. Observe

![image](https://user-images.githubusercontent.com/26110369/176343705-32c028a3-9939-417c-8033-664ff0bc0985.png)

**Comment by Nivedipa-MSFT** [comment]
@tiennguyen1293 - It looks like your issue is resolved on [@azure/msal-browser](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4918).
Could you please confirm is your issue is resolved or are you still facing the issue?

**Comment by Nivedipa-MSFT** [comment]
@tiennguyen1293 - Could you please confirm is the sample code helped you in any way or are you still facing the issue?

**Comment by Nivedipa-MSFT** [comment]
@tiennguyen1293 - Are you getting a login popup after clicking on Tab?
Could you please share more details?

**Comment by Nivedipa-MSFT** [comment]
@tiennguyen1293 - Apologies for delay response.
We have tested the below sample and it was working fine at our end.
https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/app-auth/nodejs/src/views/tab/silent/silent-start.hbs#L35

Could you please verify all the configurations again and test once? and also share the screen recording of your issue?

**Comment by Nivedipa-MSFT** [comment]
@tiennguyen1293 - The Active Directory Authentication Library creates a hidden iframe for OAuth 2.0 implicit grant flow. But the library specifies prompt=none, so Azure AD does not display the sign-in page. User interaction may be needed if the user needs to sign in or grant access to the application. If user interaction is necessary, Azure AD returns an error that the library reports to your app. If necessary, your app can now display a sign-in option.

Ref Doc: 
![image](https://user-images.githubusercontent.com/92150070/183028498-e2fd820f-69c2-412e-a4f0-7ab783de5cae.png)

**Comment by ydogandjiev** [comment]
@tiennguyen1293, the only way to achieve true SSO is by leveraging Teams to generate auth tokens for you (i.e. calling the microsoftTeams.authentication.getAuthToken API). Using MSAL in any of our native clients (i.e. iOS, Android, and Desktop) will not achieve SSO and will require users to again login to your app. Please follow our extensive documentation here if you want to implement the best possible authentication experience for our Teams Apps:
https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-overview
