### ISSUE TITLE
microsoftTeams.getContext callback is never fired

### ISSUE THREAD

**Issue by DoctorGester** [OfficeDev/microsoft-teams-library-js#123]
The code is simple:

```html
<script src="https://statics.teams.microsoft.com/sdk/v1.2/js/MicrosoftTeams.min.js"></script>
<script type="text/javascript">
    microsoftTeams.initialize();
    microsoftTeams.getContext(function (ctx) {
       // Do very important stuff and redirect to the next page
    });
</script>
```

But the case itself is a bit more complicated.
In manifest.json the configuration looks like this:

```json
"configurableTabs":[
    {
      "configurationUrl": "https://alpha.wrke.io/gws/msteams_config",
      "canUpdateConfiguration": true,
      "scopes": ["team"]
    }
  ],

"validDomains": [
    "*.wrke.io"
  ]
```

The "https://alpha.wrke.io/gws/msteams_config" iframe is then internally redirected to "https://alpha-eu.wrke.io/gws/msteams_config" (different subdomain) which contains the same javascript code, at which point microsoftTeams.getContext stops working correctly.

I investigated as much as I could and it seems that the issue is associated with window-iframe communication after a redirect to a different subdomain, although there are no visible errors or warnings in console.

Any pointers on how could I tackle this?

**Comment by ydogandjiev** [comment]
Cross-domain navigation needs to be initiated client-side via a call to:
microsoftTeams.navigateCrossDomain(“<new_url>“);

We are working on eliminating this requirement and allowing 302 over to a new domain to also work but if you want to fix this right away then the approach above is your best bet.

**Comment by DoctorGester** [comment]
@ydogandjiev thanks, that worked!
