### ISSUE TITLE
`appSessionID` should be `appSessionId` on Teams Mobile App Android

### ISSUE THREAD

**Issue by tiennguyen1293** [OfficeDev/microsoft-teams-library-js#1234]
`context` (Teams Mobile App Android) must be consistent with other apps.

Version:
```
 "@microsoft/teams-js": "1.11.0",
 ```

<img width="763" alt="image" src="https://user-images.githubusercontent.com/26110369/176935081-d4fbedfe-48ba-4ff6-8a20-0df2666434ed.png">
<img width="639" alt="image" src="https://user-images.githubusercontent.com/26110369/176935061-d30698a6-20fa-4cbc-82b3-f1539529c495.png">

**Comment by Prasad-MSFT** [comment]
@tiennguyen1293 - We are checking the issue.

**Comment by ChetanSharma-msft** [comment]
@tiennguyen1293 - We have raised a bug for it. We will let you know if any updates.

**Comment by Prasad-MSFT** [comment]
@tiennguyen1293 - We are checking the status of the bug with engineering team. We will inform you once we have any update.

**Comment by Prasad-MSFT** [comment]
@tiennguyen1293 - We got update from engineering team that this issue is fixed.
Please do verify. Thanks!
