### ISSUE TITLE
v 2.0.0 getContext() allways undefined 

### ISSUE THREAD

**Issue by Reder137** [OfficeDev/microsoft-teams-library-js#1239]
Hello ! 
I have problem with getContext return undefined everytime when i try did that. Why its, happen ?
Authorization work fine.
```
          microsoftTeams.initialize(window);
          // Get the current Teams context for the tab
             microsoftTeams.getContext((context) => {
                message.innerText = 'Congratulations ' + context.upn + '! This is the tab you made :-)';
                console.log("Congratulations", context);
             });
```

**Comment by Meghana-MSFT** [comment]
We are looking into this, we will update you.

**Comment by AE-MS** [comment]
> Hello ! I have problem with getContext return undefined everytime when i try did that. Why its, happen ? Authorization work fine.
> 
> ```
>           microsoftTeams.initialize(window);
>           // Get the current Teams context for the tab
>              microsoftTeams.getContext((context) => {
>                 message.innerText = 'Congratulations ' + context.upn + '! This is the tab you made :-)';
>                 console.log("Congratulations", context);
>              });
> ```

Hi @Reder137! I don't know for sure that this is causing the problem you are reporting, but one issue I noticed is that your sample code does not appear to be waiting until initialization is complete. In the [promise-based version of `initialize`](https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/app?view=msteams-client-js-latest#@microsoft-teams-js-app-initialize), you should wait until the promise is resolved before calling other teamsjs methods. If you're using [the older version of `initialize`](https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/?view=msteams-client-js-latest#@microsoft-teams-js-initialize), it should pass a callback method and only call other teamsjs method after the callback has been called.

Can you try this to see if it addresses your issue?

**Comment by Meghana-MSFT** [comment]
@Reder137 - Did you get a chance to chance to look at the above comment? Could you please confirm if the above comment has solved your issue?

**Comment by Reder137** [comment]
@AE-MS, @Meghana-MSFT hi ! 
Sorry for delay. 
Yes @AE-MS helped me with my issue ! 
Thanks a lot !
