### ISSUE TITLE
call.startCall() and chat.openChat() is not allowed from Dialog

### ISSUE THREAD

**Issue by n1jmbt** [OfficeDev/microsoft-teams-library-js#1253]
When trying to start a call or chat from a dialog, i get this error:

```
Uncaught (in promise) Error: This call is only allowed in following contexts: ["content"]. Current context: "task".
```

Steps to reproduce:
1. dialog.open(...), and from this dialog:
2. call.startCall(...) or chat.openChat(...)

Why is this a restriction?
I can easily circumvent this, using
app.openLink("callto:...")
app.openLink("https://teams.microsoft.com/l/chat/0/0?users=...")

Your own [documentation](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?tabs=teamsjs-v2#navigate-to-a-chat) states:
> While use of the strongly typed APIs is recommended, you can alternatively use the following format for a manually created deep link ...

**Comment by sayali-MSFT** [comment]
@n1jmbt -We will look into it and get back to you.

**Comment by jadahiya-MSFT** [comment]
@n1jmbt Thanks for bringing this to our attention! This was an oversight on our part and I have a PR https://github.com/OfficeDev/microsoft-teams-library-js/pull/1254#pullrequestreview-1045719439 with a fix in place. This will enable starting calls from Dialogs Contexts. It will be available in our next release.

**Comment by n1jmbt** [comment]
> @n1jmbt Thanks for bringing this to our attention! This was an oversight on our part and I have a PR [#1254 (review)](https://github.com/OfficeDev/microsoft-teams-library-js/pull/1254#pullrequestreview-1045719439) with a fix in place. This will enable starting calls from Dialogs Contexts. It will be available in our next release.

How about `app.openChat()`? that throws the same error, and I cannot see that in the PR.

**Comment by AE-MS** [comment]
> > @n1jmbt Thanks for bringing this to our attention! This was an oversight on our part and I have a PR [#1254 (review)](https://github.com/OfficeDev/microsoft-teams-library-js/pull/1254#pullrequestreview-1045719439) with a fix in place. This will enable starting calls from Dialogs Contexts. It will be available in our next release.
> 
> How about `app.openChat()`? that throws the same error, and I cannot see that in the PR.

Thanks for raising this issue as well. Because of this issue that you opened, we are working on a comprehensive review of all the capabilities that have transitioned from deep link forms (e.g. `call`, `chat`, `calendar.composeMeeting`, etc.) to ensure that we have the right list of allowed contexts (e.g. personal tab, dialog, etc.) for each one. Since it takes a bit of time to ensure we have the right list and validate that each works as designed, we didn't fix them all at once immediately, instead prioritizing the specific context and function you reported.

We will prioritize ensuring support for `chat` from the dialog context next.

**Comment by AE-MS** [comment]
FYI support for use the `chat` capability from dialogs has also now been added:
https://github.com/OfficeDev/microsoft-teams-library-js/pull/1271

**Comment by jadahiya-MSFT** [comment]
@n1jmbt You can test out both `chat` and `call` APIs in version 2.1.1-beta.0. Please let us know if you run into any more problems.

**Comment by ChetanSharma-msft** [comment]
@n1jmbt - Can you please test it and let us know the updates?

**Comment by n1jmbt** [comment]
Sorry for the delay, I have been out of office. I can confirm that both ```chat.openChat()``` and ```call.startCall()``` works as expected in a Dialog in version 2.2.2. Thanks!
