### ISSUE TITLE
How to use stopSharingAppContentToStageMessage

### ISSUE THREAD

**Issue by xerosanyam** [OfficeDev/microsoft-teams-library-js#1279]
The method `stopSharingAppContentToStageMessage` is private. My question is, how to use it and what were the reasons behind making it private?

Thanks

**Comment by ChetanSharma-msft** [comment]
@xerosanyam - Currently this method is private and can be used to develop only 1st party applications and it's not available for 3rt party apps development.

**Comment by xerosanyam** [comment]
@ChetanSharma-msft can you please explain what you mean by 1st party and 3rd party?
I am building an app for ms teams, my app is 1st party? if not what counts as first party

**Comment by Nivedipa-MSFT** [comment]
@xerosanyam - First party apps are those which is created and published by Microsoft.
Third-party apps aren't controlled or owned by Microsoft and aren't governed by the Microsoft Online Subscription Agreement.
Your app is coming under the Third-party app.

**Comment by xerosanyam** [comment]
Thanks for the explanation, @Nivedipa-MSFT 
I wanted to use this because "stop presentation" is slightly difficult to reach / hidden on ipad.
Any other work arounds to solve this issue? is it possible to generate an error that can cause stage to unload?

**Comment by Nivedipa-MSFT** [comment]
@xerosanyam - We are checking this internally. We will update you soon.

**Comment by xerosanyam** [comment]
@Nivedipa-MSFT thanks for the nice explanation! really appreciate it.
