### ISSUE TITLE
Microsoft Teams Free + AAD login

### ISSUE THREAD

**Issue by DoctorGester** [OfficeDev/microsoft-teams-library-js#128]
I'm not sure if this issue is completely MS Teams related but the accounts created for the free edition require changes to AAD login process, as described there: https://docs.microsoft.com/en-us/microsoftteams/platform/troubleshoot/faq

The question is how to setup regular AAD login for those accounts *outside* MS Teams? Since we don't have any kind of context we don't know the Tenant ID and can't perform the initial redirect correctly. Anything I'm missing there?

**Comment by Wajeed-msft** [comment]
You can [get context by using the Microsoft Teams JavaScript library](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/tabs/tabs-context#getting-context-by-using-the-microsoft-teams-javascript-library). Tenant Id (tid) is part of the context object which can be used to create login URL.

**Comment by DoctorGester** [comment]
@Wajeed-msft that much is clear. However what I'm getting is that I want those MSTeams Free users to login from outside the MS Teams app. We have an AAD login button on our website, that button does not work with the MsTeams Free users.

**Comment by billbliss** [comment]
Looking into this for you, hope to have a suggestion soon.

**Comment by Wajeed-msft** [comment]
Right now this is not supported for 3P apps. You can not login using freemium accounts outside Micrsoft Teams without specifying the tenant ID.
One option, although super out-of-the-box, is that you can support MSA logins, and then once you know the tenantId you can silently login the user to AAD.

**Comment by ydogandjiev** [comment]
Closing as per @Wajeed-msft's comment above
