### ISSUE TITLE
getAuthToken() method returns empty SSO token in success callback

### ISSUE THREAD

**Issue by AndrewCraswell** [OfficeDev/microsoft-teams-library-js#1290]
**Describe the bug**
Our SSO Tab app uses the TeamsFx React SDK get the user's SSO token. This in turn is just wrapping the Teams SDK. We're able to fetch the SSO token when running the app using Teams Toolkit, or when previewing/publishing the app from the Developer Portal. 

Our AAD instance has been configured for SSO, and we use the same ClientId for all our test environments in all tenants. However, when we deploy the app in Ring0, suddenly the SSO token is returned as is an empty string.

When debugging the TeamsFx code, we're hitting this code block on line 308 of the `teamsUserCredential.browser.ts` file:
https://github.com/OfficeDev/TeamsFx/blob/c326d0a30d9e58219f401cb25d6dfb9f78249a5a/packages/sdk/src/credential/teamsUserCredential.browser.ts#L307-L312

It seems like the Teams SDK `getAuthToken()` method is calling the success callback, but the resulting token is just the empty string. It is not clear to me what would cause someone to encounter this in the first place. Unfortunately, my research hasn't turned up any helpful materials, and we haven't received much clarity to date. This is blocking an upcoming release to implement SSO into our app.

Since the code works fine when running the app locally, or when previewing the app via the Teams Developer Portal, I think we can rule out AAD settings. Since the same Manifest and app package is being used, I feel like that can be ruled out as well.

I'm happy to connect offline and review our app manifest and app definition in Ring0.

**Additional context**
This issue was originally filed in the TeamsFx repo, since that is the library which makes the call to the `microsoftTeams.authentication.getAuthToken()` method. However, this library is working as expected.

We also filed in the Teams Developer Questions team, under the Authentication channel:
https://teams.microsoft.com/l/message/19:17162c6217f74e329f06316033d1185b@thread.skype/1659389672553?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=e6142543-e676-4276-8555-6232b0e3a89f&parentMessageId=1659389672553&teamName=Teams%20Developer%20Questions&channelName=Authentication&createdTime=1659389672553

**Expected behavior**
A non-empty SSO token should be returned by the `getAuthToken()` success callback. Or, an error should be returned in the failure callback.

**Comment by Nivedipa-MSFT** [comment]
@AndrewCraswell - We are investigating your query. We will update you soon.

**Comment by Nivedipa-MSFT** [comment]
@AndrewCraswell - We are checking this with engineering team. We will let you know once we have any update.

**Comment by AndrewCraswell** [comment]
Thanks, @Nivedipa-MSFT! I just updated the title and the issue description, because I realized I had the wrong code block selected in the reference. The teams-js method that is returning the empty token is actually the `getAuthToken()` function, not `authenticate()`.

**Comment by Nivedipa-MSFT** [comment]
@AndrewCraswell - Could you please share the repro steps to try at our end?

**Comment by AndrewCraswell** [comment]
Referencing this issue for additional context:
https://github.com/OfficeDev/TeamsFx/issues/5978

I suspect this issue could be closed with the resolution of this bug, although it would be nice to see some updates to the docs to reduce confusion as it relates to SSO and Full Trust apps.

**Comment by Nivedipa-MSFT** [comment]
We are closing this issue for now. Please feel free to reopen if required.
