### ISSUE TITLE
case: Azure - Files are not copied from a container

### ISSUE THREAD

**Issue by jhonnyff** [OfficeDev/microsoft-teams-library-js#1293]
Dear, I am creating an image of a web service application, through docker.
When executing the file "dockerfile", it doesn't show any error.
When consuming the created image through a "deployment" or "web application", it does not show that the project folder is located in the "wwwroot" path.
The Dockerfile is not in the project folder, it is in another path
x:\Folder\Folder 1\DevOps\[SettingsService] - Dockerfile
x:\Folder\Folder 1\OEM\[SettingsService] -- Project
Run to create image:
docker build -t settingtest -f ./DevOps/SettingsService/Dockerfile .
The image is displayed

![image](https://user-images.githubusercontent.com/82425889/183219131-4fb26026-45cd-4bfe-b644-e7de1304b17c.png)

Right click on latest run option

![image](https://user-images.githubusercontent.com/82425889/183219162-c4ad198d-6911-424d-bf06-49dddeb4f1e9.png)

![image](https://user-images.githubusercontent.com/82425889/183219174-2db5d5d0-3220-481d-8335-89c7e33cb8b2.png)

![image](https://user-images.githubusercontent.com/82425889/183219188-db803ddc-c154-4af8-a181-81a08c39dd5b.png)

When reviewing the log

![image](https://user-images.githubusercontent.com/82425889/183219219-1ffb4d13-ff8b-4249-abc0-43c61d5893d3.png)

It shows the following message:
Failed to determine the https port for redirect

![image](https://user-images.githubusercontent.com/82425889/183219232-abefe256-43dd-4d7f-b71c-c8b2fc49c7b3.png)

**Comment by sayali-MSFT** [comment]
We are mainly responsible for Microsoft Teams app development related issues.  

For Microsoft Teams product issues/failures your tenant Admin can reach out to [Microsoft 365 Product Support](https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-support?view=o365-worldwide&tabs=online).  

For general questions about Microsoft Teams please post your question on [Microsoft Teams Community](https://answers.microsoft.com/en-us/msteams/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1).

**Comment by jhonnyff** [comment]
Thank you
