### ISSUE TITLE
microsoftTeams.getContext is not called in MessageExtension-authentication window

### ISSUE THREAD

**Issue by oiparraguirre** [OfficeDev/microsoft-teams-library-js#1296]
I have the following problem with **Microsoft Teams JavaScript client SDK**. I am using action-based MessageExtension link unfurling which invokes an Authentication card, in the section where messages are written, but the authentication window is not shown. What it shows me is a card with a login button.

Details of where the problem occurs are provided:

1. A custom url is pasted in the team message typing section.
![image](https://user-images.githubusercontent.com/38538304/183171804-137e7f0b-847d-49c8-b784-079b42af9e75.png)

2. It should show the following popup:
![image](https://user-images.githubusercontent.com/38538304/183435897-d566f489-2cd1-43e7-ac3b-07d5493ea801.png)

but instead Teams shows a different card with a login button.
![image](https://user-images.githubusercontent.com/38538304/183172498-944b3f63-ab85-49fe-886b-9420d201c202.png)

3. When you click the login button, it shows a custom authentication window of your own..
![image](https://user-images.githubusercontent.com/38538304/183174909-4721962a-53b1-4fc5-8766-9688d1bc4ff0.png)

4. When this page loads, it calls the microsoftTeams context (microsoftTeams.getContext), but it returns this empty object. The Teams Client SDK version I use is:: **sdk/v1.5.2/js/MicrosoftTeams.min.js**
![image](https://user-images.githubusercontent.com/38538304/183180143-a8c6b93f-cd9b-4f2b-8e51-f750ef01ebea.png)

5. The login page that is displayed has the following structure:
![image](https://user-images.githubusercontent.com/38538304/183197007-9ff777d8-573f-444f-b78d-249a3c8faa76.png)
	
6. The data sent to validate a Controller are: user, password, userObjectId. userObjectId is a value to be filled with the context.userObjectId object, which is empty.

7. The application manifest file I use has the following settings:
![image](https://user-images.githubusercontent.com/38538304/183191094-76ffc3f6-36d9-4c2c-8dc3-dc37fab108d0.png)

I use these packages:
- Microsoft.Bot.Builder.Integration.AspNet.Core, Version="4.7.0"
- AdaptiveCards, Version = "2.7.3"
- Net 6

Thank you in advance for your support. Waiting for any query.

**Comment by sayali-MSFT** [comment]
@oiparraguirre - We are looking into this we will get back to you soon.

**Comment by sayali-MSFT** [comment]
@oiparraguirre -Are you facing same issue https://github.com/OfficeDev/microsoft-teams-library-js/issues/975

**Comment by sayali-MSFT** [comment]
Hello @oiparraguirre  - There is already an bug raised for it.
We will check the update on it with engineering team and get back to you.

**Comment by sayali-MSFT** [comment]
We are checking the status of the fix release with the engineering team. We will let you know once we have any updates on it. Thanks.

**Comment by ktjbrowne** [comment]
Hi, @sayali-MSFT, any update on fix for this.
Everything has been working for me on v1.10.0, but now has stopped working, where getContext() callback is never executed.
thank you.

**Comment by ChetanSharma-msft** [comment]
Hello @ktjbrowne - Sorry for delay in response.
We will check the bug status with engineering team and let you know the updates.

**Comment by sayali-MSFT** [comment]
@ktjbrowne -Could you please check it once with the below sample?
We are trying the below sample to repro the issue, It is working fine from our end. 
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/app-complete-auth/csharp

-  Microsoft.Bot.Builder.Integration.AspNet.Core 4.18.1
-  Net 6
-  microsoft/teams-js: v1.10.0 and 2.5.0
-  Microsoft Teams Version 1.6.00.2979 (64-bit)

**Comment by ktjbrowne** [comment]
Hi. 
I'm sorry, I thought I already responded with update. 
Thanks for chasing this.
I have resolved my issue.
We had added a new redirect subdomain on the backend which caused no response from the getting the context. (I was not aware of this at the time)
Once the domain was added to the app, all worked as normal. 
Again. Thanks for following up. 
K.

**Comment by sayali-MSFT** [comment]
@ktjbrowne - We are closing this issue for now, Please feel free to reopen it, if required.

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
