### ISSUE TITLE
Load another app with a Task Module in tab

### ISSUE THREAD

**Issue by msmichaelwoo** [OfficeDev/microsoft-teams-library-js#1301]
Hello,

I am trying to load another app inside of a different app's tab using a Task Module.
I have a button that calls the startTask function with a TaskInfo object that has the url pointing to our other apps url.

I was wondering in this case, would the manifest used be based on the tab app or the url app? Also when I do this call the Task Module renders but with no App Icon or App's Short Name. Is there a way to specify this?

**Comment by AE-MS** [comment]
Hi @msmichaelwoo! Unfortunately, you cannot load a different TeamsJS app inside of a task module/dialog. When loading an app within a dialog, the loading information and context will be based on the manifest of the app that triggered the dialog.

Can you tell us more about the scenario you are trying to enable to see if we could help provide an alternative or consideration for future support?

**Comment by msmichaelwoo** [comment]
Hi, we have a messaging extension app that we were hoping to integrate into other apps. We were thinking that other apps could integrate easily by using Task Modules and pointing the iframe url to our apps url. Experimenting with this we've found that it seems to work but does not display the app icon and app name in the task module, only the title and iframe.

**Comment by embailie** [comment]
Hey @msmichaelwoo - jumping in for my colleague AE here, with a few more questions. 

What is the desired view for the task module? You mentioned having a messaging extension app - are you hoping that the task module will show the search/selection menu from message extensions? 

This scenario is not supported in Task Modules, so I'm not surprised you're not seeing the app name / logo. Once we know more about the desired Task Module contents, we can provide more guidance on how you might achieve that.

**Comment by msmichaelwoo** [comment]
Hello,

My desired view is for a third party app to launch our app in a Task Module the same way it gets launched when you select the app from the message extensions menu.

**Comment by embailie** [comment]
@msmichaelwoo thanks for clarifying. 
Unfortunately, that scenario is not supported. It would be a poor UX for a user to click one app's icon, and then see content from another app - not to mention considerations of data storage or privacy between the two apps. 
If you are in content with the developer of the third-party app, you could ask them to make an enhancement to support your app in the Message Extension context.

**Comment by embailie** [comment]
The OP and I have discussed, and deeplinking will be used to support their scenario. Closing out this ticket.

**Comment by msmichaelwoo** [comment]
Was able to use Deeplinks instead of tasks.startTask method

https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/?view=msteams-client-js-latest#@microsoft-teams-js-executedeeplink
