### ISSUE TITLE
invoking Stage view with deep linking

### ISSUE THREAD

**Issue by aubreyquinn** [OfficeDev/microsoft-teams-library-js#1305]
I am working on a JavaScript project, and we are using this library:
`"@microsoft/teams-js": "1.7.0"`

I am trying to get started with opening a teams stage view with deep linking: Tabs link unfurling and [Stage View - Teams | Microsoft Docs](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/tabs-link-unfurling#invoke-stage-view-through-deep-link)

My use case is to click on a button and open stage view containing a website.

```
import * as React from 'react';
import { DefaultButton } from '@fluentui/react/lib/components/Button/DefaultButton/DefaultButton';
import * as Teams from '@microsoft/teams-js';

export const TestComponent: React.FC = (): JSX.Element => {

    // Component Lifecycle
    React.useEffect((): any => {
        Teams.initialize();
    }, []);

    const onTestClick = (): void => {
        // <https://teams.microsoft.com/l/stage/7c316234-ded0-4f95-8a83-8453d0876592/0?context>={"contentUrl":"https://google.com", "name":"Contoso"}

        // <https://teams.microsoft.com/l/stage/7c316234-ded0-4f95-8a83-8453d0876592/0?context>={"contentUrl":"https://www.msn.com/en-ie/"}

        const url =(
            'https://teams.microsoft.com/l/stage/34c9f4d6-b589-4f08-9c7d-9a73caa0e543/0?context=%7B%22contentUrl%22%3A%22https%3A%2F%2Fwww.msn.com%2Fen-ie%2F%22%7D'
        );

        console.log(url);

        Teams.executeDeepLink(url);
    };

    return <DefaultButton onClick={onTestClick} text='Try to Open Stage View'></DefaultButton>;

};
```

I am then getting this error in my app:
![stage_view_error](https://user-images.githubusercontent.com/80953505/184913524-42e5705e-a926-4d85-b3c2-6cc9cea47a74.png)

**Comment by ChetanSharma-msft** [comment]
Hello @aubreyquinn - Looks like you are trying to access the 1st party Approvals app which you don't have permissions to access.
You can check for the access & also you can try with any other app which you have access or try with 3rd party custom app.

**Comment by aubreyquinn** [comment]
@ChetanSharma-msft Thank you for the response. I am not familiar with the permissions for using stage view in the approvals app. Could you please advise?

**Comment by ChetanSharma-msft** [comment]
Hello @aubreyquinn - Approvals app is a first party app developed by Microsoft. So I don't think you can get access for it.
But you can develop and try with the custom 3rd party apps.

**Comment by Prasad-MSFT** [comment]
Hi @aubreyquinn - We tried to repro this by using below snippet and it was not working on invoking from task module via deep-link and also from adaptive card inside task module.
```
        microsoftTeams.app.initialize();
        function createLink() {
            // Client id
            var appId = '@(ViewBag.AppId)';
            // Application base url and this redirects to Index view
            var contentUrl = window.location.origin;
            // Passing the values and encoding the url while implementing the deeplink from tab
            let url = "https://teams.microsoft.com/l/stage/" + appId + "/0?context={\"contentUrl\":\"" + contentUrl + "\",\"websiteUrl\":\"" + contentUrl +"\",\"name\":\"DemoStageView\"}";
            microsoftTeams.app.openLink(url);
        };
```

![image](https://user-images.githubusercontent.com/62237649/186659667-b6980b64-59a4-46ba-a16f-7de62fdf0208.png)

**Comment by Prasad-MSFT** [comment]
@aubreyquinn -We got update from engineering team that; we cannot open any random website url in stage. we don't support that for stage today.

**Comment by barrida** [comment]
@Prasad-MSFT Could you explain what you mean by "any random website url"?

We want to display our custom popup in stage view using deep linking. 

We also had the same error "... is unable to show this view". However, when we used redirect uri, we could open popup but we get ""something went wrong" error with 404 in logs.  

```
        var redirect_uri = "https://my.another.domain.dev/api/...";
        queryParams.set('redirect_uri', redirect_uri);
        var contentUrl = "https://my.ngrok.io" + '?' + queryParams.toString();
        var encodedUrl = encodeURIComponent('{\"contentUrl\":' + "\"" + contentUrl + "\""  + ',\"websiteUrl\":' + "\""  + contentUrl + "\""  + ',\"name\":\"Name\"}');
        var appId = "my-app-id";
        let url = "https://teams.microsoft.com/l/stage/" + appId + "/0?context=" + encodedUrl ;

        microsoftTeams.app.openLink(url).then(
          function(value) { /* code if successful */
             console.log("openLink success: " + url);
          },
          function(error) { /* code if some error */
             console.log("openLink fail: " + url);
          }
        ).catch((err) => {
             console.log("openLink error: " + err);
        });

```

**Comment by aubreyquinn** [comment]
Thanks @barrida, I have the same issue!

**Comment by ChetanSharma-msft** [comment]
Hello @aubreyquinn - We are getting error while opening the Stage View from Adaptive Card on Task Module.
Also, we have tested it directly on Task Module without Adaptive Card and still face the issue, so we have already raised a bug for it.

**Comment by aubreyquinn** [comment]
@Prasad-MSFT thank you for the reply :) So can you tell me more? What is a 3rd party app? Also, can I use Stage View for opening a word document via a sharepoint link to the document?

**Comment by Prasad-MSFT** [comment]
@aubreyquinn - https://docs.microsoft.com/en-us/microsoftteams/overview-third-party-apps

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
