### ISSUE TITLE
[macos] Initialization Failed. No Parent window found

### ISSUE THREAD

**Issue by mihcm-chathuranga** [OfficeDev/microsoft-teams-library-js#1314]
microsoftTeams.authentication.authenticate() opens up an external browser window on mac os. This window will redirect the user to the login page, and upon successful login, we are invoking the microsoftTeams.authentication.notifySuccess();

However, microsoftTeams.initialize() fails with the error "Initialization Failed. No Parent window found", and notifySuccess() is never invoked.

The auth flow works fine on windows desktop client and browser client, but not on mac os desktop client.

macOS  - 12.3.1
Teams  - 1.5.00.21551
Javascript SDK - 2.2.0

**Comment by Nivedipa-MSFT** [comment]
@mihcm-chathuran - We are investigating your query. We will update you soon.

**Comment by mihcm-chathuranga** [comment]
@Nivedipa-MSFT I already have version 1.5.00.21551 installed and the issue appears on the same version. 1.5.00.21551 is the latest version according to this. [https://docs.microsoft.com/en-us/officeupdates/teams-app-versioning#mac-public-cloud-version-history](https://docs.microsoft.com/en-us/officeupdates/teams-app-versioning#mac-public-cloud-version-history)

**Comment by Nivedipa-MSFT** [comment]
@mihcm-chathuranga - We have tested this. On windows also we are getting this error. We are checking this internally. We will update you soon.

**Comment by mihcm-chathuranga** [comment]
@Nivedipa-MSFT - Any update on this?

**Comment by sayali-MSFT** [comment]
@mihcm-chathuranga -We are still investigating the problem internally. We will update you soon.

**Comment by Nivedipa-MSFT** [comment]
@mihcm-chathuranga - When running Microsoft Teams in a browser on desktop client, this typically means that the window was blocked by a popup blocker.
Could you please verify the window is blocked by popup blocker or not?

**Comment by mihcm-chathuranga** [comment]
@Nivedipa-MSFT disabled the popup blocker in safari, but the same results. Tried changing the default browser to chrome/firefox but still the same.

**Comment by Nivedipa-MSFT** [comment]
@mihcm-chathuranga - Can you please share your authentication code?
Have you wait for the initialization to complete before calling the authenticate API.
Please refer below code.

```
microsoftTeams.initialize(() => {
  microsoftTeams.authentication.authenticate({
    url: config.BASE_URL + '/app/microsoft-teams/tabs/auth',
    width: 600,
    height: 535,
    successCallback: onAuthSuccess,
    failureCallback: onAuthFailure,
  });
});
```

**Comment by ChetanSharma-msft** [comment]
Hello @mihcm-chathuranga - We have tested using [tab-sso](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-sso/csharp) sample. 

We are not able to repro this issue on Windows Teams desktop client. In Windows Teams desktop client, we are getting popup window & It's not redirecting to the browser.

In Windows Teams web client whenever it will redirect to the browser then on login page we are getting "Initialization Failed. No Parent window found" because its outside of Teams. So, it's by design.

**Comment by mihcm-chathuranga** [comment]
> @mihcm-chathuranga - Can you please share your authentication code? Have you wait for the initialization to complete before calling the authenticate API. Please refer below code and sample:
> 
> ```
> microsoftTeams.initialize(() => {
>   microsoftTeams.authentication.authenticate({
>     url: config.BASE_URL + '/app/microsoft-teams/tabs/auth',
>     width: 600,
>     height: 535,
>     successCallback: onAuthSuccess,
>     failureCallback: onAuthFailure,
>   });
> });
> ```
> 
> Sample link: https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/tab-sso/csharp/TeamsTabSSO/Views/Auth/Start.cshtml

@Nivedipa-MSFT, the authentication code is exactly like yours.

**Comment by mihcm-chathuranga** [comment]
> Hello @mihcm-chathuranga - We have tested using [tab-sso](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-sso/csharp) sample.
> 
> We are not able to repro this issue on Windows Teams desktop client. In Windows Teams desktop client, we are getting popup window & It's not redirecting to the browser.
> 
> In Windows Teams web client whenever it will redirect to the browser then on login page we are getting "Initialization Failed. No Parent window found" because its outside of Teams. So, it's by design.

@ChetanSharma-msft We didn't notice the error on Windows either. It was the mac os. The desktop client on mac os opens up a browser when the microsoftTeams.authentication.authenticate() is invoked. We don't have control over if the Teams clients open up a popup or the browser itself.

**Comment by Nivedipa-MSFT** [comment]
@mihcm-chathuranga - We are checking this internally. We will update you soon.

**Comment by manizm** [comment]
This can be related to [COOP](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Opener-Policy)
You might have to add this policy header in your server

**Comment by Nivedipa-MSFT** [comment]
@mihcm-chathuranga - Have you added the above policy mentioned by @manizm

**Comment by manizm** [comment]
@Nivedipa-MSFT I am seeing this issue on desktop application, despite having COOP setup properly

**Comment by mihcm-chathuranga** [comment]
@Nivedipa-MSFT Configuring COOP did not help. Also, I was not using isExternal  as mentioned by @man.izm 

Further, I have tried the Teams SSO sample app, generated by the VS Code with different Teams clients. It seems like the Teams client dictates whether to open a popup or an external browser.

Desktop Client ( Windows Laptop)
When we click the "Authorize" button, the popup opens. No issues there.
(Microsoft Teams Version 1.5.00.21668 (64-bit). It was last updated on 9/2/2022)

Desktop Client (Azure VM - AVD)
When we click the "Authorize" button, the browser opens. The popup does not appear.
(Microsoft Teams Version 1.5.00.9163 (64-bit). AVD Media Optimized.)

Desktop Client (MacBook pro-2020 - macOS 12.3.1)
When we click the "Authorize" button, the browser opens. The popup does not appear.
(Microsoft Teams Version 1.5.00.22362. It was last updated on 2022-09-05)

**Comment by Nivedipa-MSFT** [comment]
@mihcm-chathuranga - Could you please share which sample you are referring for this? and also please share your code zip to try at our end?

**Comment by Nivedipa-MSFT** [comment]
@mihcm-chathuranga - There is an ICM raised for this. We will let you know once we have any updates on it.

**Comment by Nivedipa-MSFT** [comment]
@mihcm-chathuranga - We are checking the status of the fix release with the engineering team. We will let you know once we have any updates on it. Thanks.

**Comment by ctawiah** [comment]
@Nivedipa-MSFT thanks. Please keep us posted.

**Comment by Nivedipa-MSFT** [comment]
@mihcm-chathuranga - The issue was due to Samesite Cookies which was resolved after raising an ICM. Could you please confirm if your issue is resolved?

**Comment by ChetanSharma-msft** [comment]
Hello @mihcm-chathuranga - 
Hope you are doing well!!

As per discussion that it is the issue because of SameSite cookie is not configured properly in the application and you have edited the SameSite configuration and testing is in-progress.

Could you please let us know if you need any further help here?

**Comment by mihcm-chathuranga** [comment]
Hello @ChetanSharma-msft,

It was due to the SameSite cookie was not configured correctly. I can confirm it's working fine with updated configurations.

**Comment by ChetanSharma-msft** [comment]
Hello @mihcm-chathuranga - Thanks for the confirmation.
Could you please share the steps that you have performed to fix the issue, so that others can also be benefited out of it?
