### ISSUE TITLE
Custom app in Teams desktop client

### ISSUE THREAD

**Issue by Arthurqin20227** [OfficeDev/microsoft-teams-library-js#1315]
Hi Team,

We have a custom app, and we encounter an issue. We find that in one of our devices, we cannot access to the backend page of the app. Authentication not pop out. However, in other device, with the same app, same Teams desktop version, and same code, authentication windows can pop out.

To Reproduce

1.Go to test channel, click the tab( app already pin on the channel tab)
2.Waiting for authentication windows pop out but it didn't. Just blank screen.

Expected behavior:
an Authentication windows will pop out like below
![image](https://user-images.githubusercontent.com/110021957/185613915-b56bda84-eb87-483d-a28d-e3ad6c4631e0.png)

When we check the Develop tools in Teams desktop client for this app, we can see error report in Console:
Refused to display 'https://login.microsoftonline.com/' in a frame i-frame-container.htm...Invalidation=true:1 because it set 'X-Frame-Options' to 'deny'
![image](https://user-images.githubusercontent.com/110021957/185614007-c3c9aeff-b9f2-46b2-88c6-8547dd1d20f0.png)

For SSO code part
![image](https://user-images.githubusercontent.com/110021957/185614089-32e776c1-97ac-4a54-8f21-2dd9962d062b.png)

Anyone got any ideas about this issue? any reply will be appreciated~ It is quite strange that this issue only happen on 1 single device, once we use affected user account to sign in another device, this issue will not happen. How could this issue happen with the same app which code is the same but authentication behavior is different?

**Comment by sayali-MSFT** [comment]
@Arthurqin20227 - We are looking into this we will get back to you soon.

**Comment by sayali-MSFT** [comment]
@Arthurqin20227 - Login pages don't render in iFrames, as a safeguard against clickjacking. Your authentication logic needs to use a method other than redirect. For example, use token-based or cookie-based authentication.
It works fine in browser but MS Teams is implemented on I-frame, that is why you are getting this error.

Please have a look into [Microsoft Teams authentication flow for tabs](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-flow-tab) flow.

Here is a ink for [Auth code sample](https://github.com/OfficeDev/microsoft-teams-sample-complete-node/tree/master/src/views/tab-auth)

**Comment by Arthurqin20227** [comment]
Hi @sayali-MSFT  Thank you for your reply~

In fact this app is working on all the other device without any problems, and all other device can pop out authentication windows properly in Teams desktop client. Only this specific affected device got this issue. 

May I know whether you got any idea about the possible cause of this behavior? is it because of some device setting issue that not using token or cookies based authentication? 

Any reply would be appreciated~

**Comment by sayali-MSFT** [comment]
Hi @Arthurqin20227 -Could you please try with the latest version of teams?
and also share the Teams version where it is working and weather it does not work. Thanks!

**Comment by Arthurqin20227** [comment]
Hi @sayali-MSFT - Actually, when we test at that time, Teams version is the latest version in July. It's Teams/1.5.00.17656. All the device are in the same version.

I will also try what if update to latest version now. But I'm afraid Teams version will update automatically.

**Comment by sayali-MSFT** [comment]
@Arthurqin20227 -Ensure that you adhere to the following prerequisites while building your Teams personal and channel or group tab:

  Allow your tab pages to be discovered in an iFrame, using X-Frame-Options and Content-Security-Policy HTTP response headers.

- Set header: Content-Security-Policy: frame-ancestors teams.microsoft.com *.teams.microsoft.com *.skype.com
- For Internet Explorer 11 compatibility, set X-Content-Security-Policy.
- Alternately, set header X-Frame-Options: ALLOW-FROM https://teams.microsoft.com/. This header is deprecated but still accepted by most browsers.

Ref Doc-https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-requirements

**Comment by Arthurqin20227** [comment]
Hi @sayali-MSFT  

Thank you for your suggestion, we will test it and see whether it will work on our side.

Thank you for your insights~

**Comment by Arthurqin20227** [comment]
Hi @sayali-MSFT 

Thank you so much for your guidance~

We try your suggestion, and it resolve our blank screen issue while we click the app in Teams.

Thank you for your help and I think we can archive this one.

**Comment by Nivedipa-MSFT** [comment]
We are closing this issue now. Please feel free to reopen if required.
