### ISSUE TITLE
Error code 10000 / SIZE_EXCEEDED on microsoftTeams.media.selectMedia

### ISSUE THREAD

**Issue by MarksPoint** [OfficeDev/microsoft-teams-library-js#1317]
We've been using the ```microsoftTeams.media.selectMedia``` sdk function to allow users to select multiple images in our custom message extension.

Recently we've had complaints from users on modern Android devices that they run into errors when they select more than a certain number of images. The underlying error we capture and log is code 10000 / SIZE_EXCEEDED.

Apparantly there's a (hidden?) file size limit of ~30 MB that applies to total file size that a user can select at once. Users trying to select photos that can be over 6MB a piece, force the function to fail when they select > 5 files.

Our biggest concern is that there's no way to prevent the error from occurring. We can only detect/handle it when it happens and tell the user to select fewer images at once, but they'd have to do the selection over and since there's no indication of the total size they already selected, it's hard to predict if it will fail again. 

This whole limitation renders using the microsoftTeams.media.selectMedia pretty much useless for this scenario, as we cannot rely on it working correctly on all devices. With more and more mobile phones taking big > 5MB images, this is becoming a bigger issue over time.

Am I using the function incorrectly? 
Is there some way to change this 30MB limit that I don't know of?

I'd love to get some feedback on this.

My 2 cents on different ways that this might be handled by the selectMedia functionality:
- Remove the limit alltogether. I'm not even sure why this limit is even there. I can put an ```<input type='file' multiple />``` in my app that allows the user to select as many photos as they like without problems, so why is this a necessary limitation of the function?
- Allow automatic resizing of images to make their size more manageable
- Make sure the user can't select more than the maximum allowed (based on size) number of images. This could work the same way it works right now when a user tries to select more than 10 images

**Comment by Prasad-MSFT** [comment]
@MarksPoint - Yes, you are using the function correctly. You are getting this error because it has exceeded the platform size boundaries.
Error code 10000 means "Return value is too big and has exceeded the platform size boundaries".

**Comment by MarksPoint** [comment]
Thanks for the confirmation that we're using it correctly.

How can we use this function properly on modern phones, where images are typically bigger than 5MB?
I want my users to be able to select 10 (more would be even better) images without causing an exception.

**Comment by Prasad-MSFT** [comment]
The platform's size boundaries seem to be limited.
You can change the `maxMediaCount` value as mentioned in below code.
https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/media-capabilities?tabs=mobile#code-snippets

**Comment by MarksPoint** [comment]
Thank you, but I am aware of the documentation. 

Could you please answer these 3 questions:

- What does "platform's size boundaries" mean exactly? What platform are we talking about?
- How should I know the `maxMediaCount` if I have lots of different users, all with different mobile phones? I don't know the default size of an image on my user's phone. On most phones selecting 10 images is no problem, but on some modern phones the limit seems to be 5 or even 3 images.
- How is it possible that I can select 10 high-resolution images of >6MB **at once** using the "attach images" button, which apparantly uses the same Image picker without issues?

_Using this button I can select 10 big images but it's using the same 'picker':_

<img width="652" alt="image" src="https://user-images.githubusercontent.com/16799069/186360285-9364a6eb-a90f-4d6b-a43f-257c3dd86735.png">

**Comment by Prasad-MSFT** [comment]
@MarksPoint -
`selectMedia` API is supported in Mobile Platforms. Mobile platform has size boundary limit beyond which it will throw `Error Code 10000 / SIZE_EXCEEDED` .  `maxMediaCount `is only configurable.

**Comment by MarksPoint** [comment]
Hi @Prasad-MSFT,

Thanks for the reply, but I would really appreciate it if you answered my questions instead of repeating what's already in the documentation.

**Comment by Prasad-MSFT** [comment]
@MarksPoint - It doesn't count each image size individually; it counts total size of the images selected.

**Comment by alicialu-MSFT** [comment]
Hi @MarksPoint -- I am a PM on M365 Platform team and I focus on media-related scenarios for apps. Outside of this issue, I'd love to learn more about the scenarios you are trying to enable and the device capabilities you're trying to leverage for your app. If you'd like to chat more, please email me at alicialu@microsoft.com. Thanks!

**Comment by MarksPoint** [comment]
I don't see why this item needs to be closed as I haven't received a proper reply to the questions I asked on August 24.

**Comment by ChetanSharma-msft** [comment]
Hello @MarksPoint - Please let us know if you have any further query here?

**Comment by MarksPoint** [comment]
Looking into it this week. I'll let you know.

**Comment by Prasad-MSFT** [comment]
@MarksPoint - As discussed, `selectMedia` returns array of metaData of images and has has a size limit of 4MB, so whenever the metaData will go higher than 4MB it will return an error. There is no direct relation between size of images and this error code, because it does not send the actual image back to webapp, it only sends metaData.
For eg: try selecting 3 images each images around 40 MB(~120 MB total), but still here metaData might be less than 4MB and it should not throw an error. But if you try selecting 8 images of 6MB each(~48 MB total), metaData will contain 8 objects data and still might be more than 4MB and return 10000 error.

If this issue is a blocker for you, please provide tenant name and tenant ID to discuss the solution further with engineering team.

**Comment by MarksPoint** [comment]
> because it does not send the actual image back to webapp, it only sends metaData.

I just did some testing and this doesn't seem to be entirely true because it has a compressed version of the image in the `preview` property of the `Media` object (the attachments returned in the callback). 

If I select 7 photos on my iPhone 13 Pro, everything is fine. If I select 8 or more, it crashes with the 10000 error. 
There is nothing special with the metadata of these photos. 

Below is the code I use to trigger the media picker:

``` TypeScript
let imageProp: microsoftTeams.media.ImageProps = {
    sources: [microsoftTeams.media.Source.Gallery],
    startMode: microsoftTeams.media.CameraStartMode.Photo,
    ink: false,
    cameraSwitcher: false,
    textSticker: false,
    enableFilter: true,
};

let mediaInput: microsoftTeams.media.MediaInputs = {
    mediaType: microsoftTeams.media.MediaType.Image,
    maxMediaCount: 10, // Allow the maximum
    imageProps: imageProp,
};

microsoftTeams.media.selectMedia(
    mediaInput,
    (error: microsoftTeams.SdkError, attachments: microsoftTeams.media.Media[]) => {
        if (error && error.errorCode !== microsoftTeams.ErrorCode.USER_ABORT) {
            // It fails here with err 10000 if I select 8 or more photos on iPhone 13 Pro
            const err = new CustomError({
                data: error,
                message:
                    '[PhotoSelectionScreen][handleCameraButtonClicked] Failed capturing image, error code ' +
                    error.errorCode,
            });
            Logger.error(err);
            handleError(err);
        } else if (attachments.length > 0) {
            // It works ok if I select 7 photos or less on iPhone 13 Pro
            handlePhotosCaptured(attachments);
        }
    }
);
```

I write the `size` property of the selected Media objects to the screen and this is never more than around 1MB:

![image](https://user-images.githubusercontent.com/16799069/203531084-fa8d5826-4ac3-4843-a00a-131e83e6ba95.png)

Below is the code where I process the incoming attachments, but this is only triggered if the callback doesn't give the error.

``` TypeScript
const handlePhotosCaptured = useCallback(
    async (files: microsoftTeams.media.Media[]) => {
        for (let i = 0; i < files.length; i++) {
            try {
                if (!files[i].mimeType.startsWith('image')) {
                    throw new Error('Provided file is not an image.');
                }

                const dataUrl = `data:${files[i].mimeType};base64,${files[i].preview}`;

                const blob = await (await fetch(dataUrl)).blob();
                const filename = `${uuidv4()}.jpg`;

                if (blob) {
                    setSelectedPhotos((prevSelectedPhotos) =>
                        prevSelectedPhotos.concat([
                            {
                                id: Math.random().toString(36).slice(2),
                                file: new File([blob], filename),
                                size: files[i].size,
                                name: filename,
                                imageDataUrl: dataUrl,
                                selectionStageStatus: 'succeeded', // data url is already available
                                uploadStageStatus: 'idle',
                                thumbnailStageStatus: 'idle',
                                uploadProgress: 0,
                            },
                        ])
                    );
                } else {
                    throw new Error('Unable to get file blob for dataUrl.');
                }
            } catch (err) {
                Logger.error(
                    new CustomError({
                        base: err,
                        message:
                            '[PhotoSelectionScreen][handlePhotoCaptured] Failed handling captured photo',
                    })
                );
                handleError(err);
            }
        }
    },
    [selectedPhotos]
);
```

All in all I don't understand why selecting 8 or more photos triggers the 10000 error. Maybe the limit is 10MB instead of 30MB? But then why are the previews so big?

Any help?

I will also give a look at an Android device, but this is my analysis so far...

**Comment by reenudeswal** [comment]
@MarksPoint the preview which you are getting in selectMedia is part of the metaData only and its size will depend on the actual image size. for eg; if Image is around 1MB there will be very less compression and preview size will also be similar but if image size is more, we will do compression internally to reduce preview size. Also the selectMedia limit that we are talking about is on complete response and not on individual preview or `Media` object. You can verify this by logging the response size of selectMedia, it will always be less than 4MB when the callback is successful and you are not receiving 10000 error. When you are receiving 10000 error in selectMedia it is only because the metaData array is going above 4MB.

Also I am bit confused on `it crashes with the 10000 error` is it crashing or it is returning 10000 error because ideally both should not happen.

**Comment by MarksPoint** [comment]
> You can verify this by logging the response size of selectMedia

I am not sure how to calculate the size of the total response.

If I use the following method to calculate the size of the returned array of `attachments`, I do get some information, but this doesn't match with what you stated.

``` JavaScript
function memorySizeOf(obj) {
    var bytes = 0;

    function sizeOf(obj) {
        if(obj !== null && obj !== undefined) {
            switch(typeof obj) {
            case 'number':
                bytes += 8;
                break;
            case 'string':
                bytes += obj.length * 2;
                break;
            case 'boolean':
                bytes += 4;
                break;
            case 'object':
                var objClass = Object.prototype.toString.call(obj).slice(8, -1);
                if(objClass === 'Object' || objClass === 'Array') {
                    for(var key in obj) {
                        if(!obj.hasOwnProperty(key)) continue;
                        sizeOf(obj[key]);
                    }
                } else bytes += obj.toString().length * 2;
                break;
            }
        }
        return bytes;
    };

    function formatByteSize(bytes) {
        if(bytes < 1024) return bytes + " bytes";
        else if(bytes < 1048576) return(bytes / 1024).toFixed(3) + " KiB";
        else if(bytes < 1073741824) return(bytes / 1048576).toFixed(3) + " MiB";
        else return(bytes / 1073741824).toFixed(3) + " GiB";
    };

    return formatByteSize(sizeOf(obj));
};
```

If I select 1 image it's 1.890 MiB
2 images: 3.797 MiB
3: 4.376 MiB
4: 4.916 MiB
5: 5.482 MiB
6: 6.125 MiB
7: ? I get the 10.000 error here. (previously I was able to select 7 images but the selection was slightly different).

Is there another way to know the size? And what is taking up all that space?

> Also the selectMedia limit that we are talking about is on complete response and not on individual preview or Media object.

But if previews are already up to 1 MB, and the limit for the TOTAL response is 4 MB, how can I select up to 7 images? 7 * 1  > 4, right?

> Also I am bit confused on it crashes with the 10000 error is it crashing or it is returning 10000 error because ideally both should not happen.

Crashing is probably not the right word. It is the error I get in the callback and in that scenario I handle it as an error that I need to show to the end user. So it's a situation I handle 'gracefully', it doesn't really 'crash'.

**Comment by MarksPoint** [comment]
If I remove the preview from the calculation, then each attachment is only 104 bytes:

``` TypeScript
const atts = attachments;
atts.forEach((a) => {
    delete (a as any)['preview'];
});
// Result is always the number of attachments * 104 bytes
console.log(memorySizeOf(atts));
```

So it appears that the `preview` property takes up the most part of the result.

**Comment by Prasad-MSFT** [comment]
@MarksPoint - 
If this issue is a blocker for you, please provide tenant name and tenant ID to discuss the solution further with engineering team. The limit can be increased at tenant level with some caveats to resolve this issue.

cc: @reenudeswal

**Comment by MarksPoint** [comment]
Yes, this is **absolutely a blocker** for us because this is used in a core feature of our software solution.
No, I cannot provide you with a tenant name/ID because we have many customers that all have their own tenant.

It is essential in our solution that a user can **consistently select multiple images** from his (mobile) device. We tried a different approach as well, using a 'regular' `<input type="file" multiple />` but this doesn't work correctly on Android devices, [as I mentioned here in this other issue](https://github.com/OfficeDev/microsoft-teams-library-js/issues/1316).

**Comment by reenudeswal** [comment]
@MarksPoint  the size you are verifying, is it after decoding the response and converting to image because I am talking about the raw response that we sent which includes base64 encoded string for preview field.

Is it possible for you to share any test account with repro steps and tenantID for that account so we can try the changes we are suggesting on that account and verify if it is working. If that will work, then we need to look into next steps how can we apply the changes for all your customer tenants.

**Comment by MarksPoint** [comment]
> @MarksPoint the size you are verifying, is it after decoding the response and converting to image because I am talking about the raw response that we sent which includes base64 encoded string for preview field.

There are multiple ways to look at this:
- Get the `size` property of the Media object (the attachment)
- Use a method like the one I mentioned (using the `memorySizeOf(obj)` method) to get the size of the attachments array
- Create a blob based on the base64-preview and get the size of that (this one is not representative I guess since I create the Blob myself)

All these options give different results.
Do you know of a different way to get this info?

> Is it possible for you to share any test account with repro steps and tenantID for that account 

I've created a reproduction app using Yo Teams:
[SelectMediaReproTab.zip](https://github.com/OfficeDev/microsoft-teams-library-js/files/10092516/SelectMediaReproTab.zip)

It includes a Personal Tab that has a Select Media button to see the issue.
You can use any Tenant to try this on. I just created a tenant using CDX and I was able to reproduce the issue there.

Steps:
- Unzip the package
- npm install
- gulp ngrok-serve (This hosts the app locally on a random ngrok url)
- upload the automatically generated package (./package/selectmediaissueinvestigation.zip) to Teams
- activate the app
- use a mobile device (I used iPhone 13 Pro, but issue is also present on modern Android devices and iPhone XS)

You should see something like this when you open the Tab on mobile:
![image](https://user-images.githubusercontent.com/16799069/203982680-9c2ef8db-48f5-4429-b516-9aeb2bbe595e.png)

If you successfully select files, in my case I can select 6 images without an error, you'll see this (calculated size in the top):
![image](https://user-images.githubusercontent.com/16799069/203983110-3b269acb-5f7f-408a-831b-8e7c3d6ee198.png)

If it fails, you'll see this (in my case when I select 7 images):
![image](https://user-images.githubusercontent.com/16799069/203983317-7979d057-6cb3-4a92-a2fe-7ce1aa2eedfd.png)

> If that will work, then we need to look into next steps how can we apply the changes for all your customer tenants.

I don't see how updating all tenants would work. We have 100's of installations and every day we get new installations...

**Comment by reenudeswal** [comment]
@markspoint There is some issue with gulp in latest Mac OS and I am unable to use gulp. Can you share the manifest with a proper URL where this app is running that will be faster to debug.

**Comment by MarksPoint** [comment]
The app is not running anywhere publicly, so I cannot share a url with you.

I am running MacOS myself with Ventura and I don't have any issues using gulp.

![image](https://user-images.githubusercontent.com/16799069/204259479-b51275e2-c490-48c0-bfd3-05952af37934.png)

![image](https://user-images.githubusercontent.com/16799069/204259912-16f1f6d7-47ac-491c-afc2-a4b1c884275e.png)

Please try again to run it in your own environment.

**Comment by reenudeswal** [comment]
Tried multiple things but this is not working, @MarksPoint please build and run the app locally and created ngrok url and share that. Or if this is already working in some test account, please share that test account details for repro.

**Comment by Wajeed-msft** [comment]
@MarksPoint - Apologies for delay.  Could you please set it up and share the manifest? We will let you know as soon as we try and have repro so that you can stop running it.

**Comment by MarksPoint** [comment]
[selectmediaissueinvestigation.zip](https://github.com/OfficeDev/microsoft-teams-library-js/files/10244512/selectmediaissueinvestigation.zip)

It's running now. Please let me know if you're on it and when you're done.

**Comment by Wajeed-msft** [comment]
@MarksPoint - Thanks for sharing the manifest. FYI - Team already started looking into it.

**Comment by Wajeed-msft** [comment]
@MarksPoint - we tested your app manifest in a **test tenant** where we increased the 4 MB limit to 20 MB. Could you please share any one of your test tenant Id on [Microsoft Teams Community Help](mailto:microsoftteamsdev@microsoft.com) email id so that we could increase the limit for you to test? 

![MicrosoftTeams-image (9)](https://user-images.githubusercontent.com/31851992/208080019-fc87caca-697a-4c03-8988-abf376dd86f0.png)

**Comment by MarksPoint** [comment]
You can use our tenant id: 2abb2d8a-ba2e-42a7-a14e-e9ad14343663

**Comment by Wajeed-msft** [comment]
@MarksPoint - you can stop the sample app which is running on your machine.

**Comment by Wajeed-msft** [comment]
Team is marking changes for your test tenant to increase the limit. I'll share the update as soon as I get confirmation from engineering team.

**Comment by MarksPoint** [comment]
Ok!
But just out of curiosity: if this makes it work in my tenant, how is this gonna be a fix for all my (future) customers?

**Comment by Wajeed-msft** [comment]
@MarksPoint - The change to increase limit for iOS is rolled out, could you please test it in your demo tenant?

> how is this gonna be a fix for all my (future) customers?

If the fix works on your tenant, we will then discuss this internally if we can remove the tenant filter and increase the limit overall. We would need more information on how many tenants and users impacted due to this for prioritization.

**Comment by MarksPoint** [comment]
I've just tested it and it works without any issues now. I am able to select 10 photos and I see no 10000 error:
![image](https://user-images.githubusercontent.com/16799069/208464891-025e8602-eeb1-4c63-9c27-89e20435858d.png)

Also with a different set of images (taken outside yesterday) it works, although the Media.size is now often over 2 MiB:
![image](https://user-images.githubusercontent.com/16799069/208465900-a826849d-4f15-491a-8c07-fc99cd646f02.png)

How would you like to proceed?

**Comment by Wajeed-msft** [comment]
@MarksPoint - Could you please share following information which will help with way forward?

1. How many tenants are there is production using this scenario?
2. How many users are impacted due to this issue?

**Comment by MarksPoint** [comment]
Is this the info you're looking for?

![image](https://user-images.githubusercontent.com/16799069/208881301-2a0ceefe-d9e1-422f-ba08-b7723fe61b15.png)

![image](https://user-images.githubusercontent.com/16799069/208881578-87a16c1d-71b0-4e4d-8985-d6e43b075c2b.png)

[Photo Filer - Teams usage - Tenants45f01bfebab7d78db23b6a67de2f6d9eaf2350ada8ba14d4b320ee7cd47f527f.pdf](https://github.com/OfficeDev/microsoft-teams-library-js/files/10276796/Photo.Filer.-.Teams.usage.-.Tenants45f01bfebab7d78db23b6a67de2f6d9eaf2350ada8ba14d4b320ee7cd47f527f.pdf)

[Photo Filer - Teams usage - Usersb91d48067f74b3be1cb5009a9b1e31eb3fbf58dd132994dd2b4bdb7f10f51944.pdf](https://github.com/OfficeDev/microsoft-teams-library-js/files/10276798/Photo.Filer.-.Teams.usage.-.Usersb91d48067f74b3be1cb5009a9b1e31eb3fbf58dd132994dd2b4bdb7f10f51944.pdf)

**Comment by MarksPoint** [comment]
Please give me an update.

**Comment by ChetanSharma-msft** [comment]
Hello @MarksPoint - Sorry for delay in response.
I will check on it and let you know the updates.

**Comment by Wajeed-msft** [comment]
@MarksPoint - Engineering team confirmed that they are actively investigating the right solution for the issue based on the findings shared. Based on investigation results we will plan the fix timeline. We will get back with another update on this in 3 weeks' time.

**Comment by Wajeed-msft** [comment]
@MarksPoint - The fix identified so far is to increase the metadata size limit from 4mb to 20mb. We suspect that this increase of metadata would cause a crash on low end devices. We are getting this tested to gain some confidence. If low end device testing goes through well, then we will make this change available to all production. Currently we do not have fix timeline to share. Meanwhile we can offer this change to only some tenants, so that the risk is limited to few tenants only. Please let me know if we can make this change for 3-4 tenant ids.

**Comment by ChetanSharma-msft** [comment]
Hello @MarksPoint - Engineering team has increased the metadata size limit from 4MB to 20MB for below provided tenant ids:
c79d06da-a1a6-4879-bf9c-21f6f8fb9d97
605b6217-dd09-4ad6-9881-1ec0e25f20a3

Could you please test on these and let us know if you face any issue.

Thanks!!

**Comment by ChetanSharma-msft** [comment]
Hello @MarksPoint - Hope you are doing well!!

Did you get a change to test the issue on above tenants where metadata size limit is increased?

**Comment by Wajeed-msft** [comment]
@MarksPoint -Could you please confirm whether your app is working fine now with increased metadata size limit?
