### ISSUE TITLE
[Question] Authentication with hydra

### ISSUE THREAD

**Issue by dcgenius** [OfficeDev/microsoft-teams-library-js#1319]
Hi there,

we've got a `Tab` app that allows logging in with Google, but we're using Hydra (https://www.ory.sh/docs/hydra/concepts/login) which does the auth flow [within the same browser window](https://console.ory.sh/login) (no popup). 
This of course has issues with iframes used in Teams, so I tried using the [authentication](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-oauth-provider) function of the sdk, but it will open the popup, the login will be successful and the app will render **inside** the popup, which is not the desired behavior.
How can I make my login with 3rd parties compatible for my app distributed in Teams?

Thanks

**Comment by Meghana-MSFT** [comment]
We are looking into this issue, we will get back to you.

**Comment by Meghana-MSFT** [comment]
@dcgenius - Currently authenticate function in the SDK will always open a new window. If you want to use auth flow in the SDK, then you have to support the new window flow, which means you have to close the new window by calling notifySuccess in the SDK.

**Comment by iambmelt** [comment]
> 

Correct - if Hydra supports overriding its default behavior, such that a 3P developer can intercept the successful auth result and invoke `notifySuccess`, this is proper API/mechanism to use to implement this scenario
