### ISSUE TITLE
app and Context not found in module

### ISSUE THREAD

**Issue by andre-atos** [OfficeDev/microsoft-teams-library-js#1322]
This small code has this error as result, 
**The requested module 'https://res.cdn.office.net/teams-js/2.2.0/js/MicrosoftTeams.min.js' does not provide an export named 'Context'**

I don't understand what happen here, this must work everywhere

<script type="module">
import { app, Context } from "https://res.cdn.office.net/teams-js/2.2.0/js/MicrosoftTeams.min.js";

app.getContext().then((context) => {
   console.log("Andre");
});
</script>

**Comment by Nivedipa-MSFT** [comment]
@andre-atos - We are investigating your query. We will update you soon.

**Comment by Nivedipa-MSFT** [comment]
@andre-atos - As a workaround could you please try the below code:
```
 <script 
src="https://res.cdn.office.net/teams-js/2.2.0/js/MicrosoftTeams.min.js" 
integrity="sha384-yBjE++eHeBPzIg+IKl9OHFqMbSdrzY2S/LW3qeitc5vqXewEYRWegByWzBN/chRh" 
crossorigin="anonymous" 
></script>
 <script type="text/javascript">
 microsoftTeams.app.getContext().then((context) => {console.log("Andre");}); 
</script>
```

**Comment by nwojod-MSFT** [comment]
@andre-atos can you verify if the above suggestions worked for you.
