### ISSUE TITLE
reload button is not reloading staticTab content

### ISSUE THREAD

**Issue by unikoski** [OfficeDev/microsoft-teams-library-js#1326]
We have a teams app with a static tab, that displays 3 cards. When I hit the reload button on the top right hand side of the tab toolbar, I see the tab toolbar refresh, but nothing is sent to the bot to cause me to reload the cards within the tab. Shouldn't the reload button send the bot something to let it know the user wants to reload? Is there something I need to set up to allow this?

**Comment by sayali-MSFT** [comment]
@unikoski - Thanks for reporting your issue.
We will investigation this issue and get back to you.

**Comment by sayali-MSFT** [comment]
@unikoski -Currently teams does not provide reload tab button pragmatically. Could you please build your own reload within the tab.
You can register a before unload handler to detect/handle when Teams is going to unload your tab with latest Teams SDK. The rules can vary depending on the type of client (mobile versus webapp, versus desktop).

`microsoftTeams.registerBeforeUnloadHandler()`

Reference Code-
https://github.com/OfficeDev/microsoft-teams-library-js/blob/1478c384cf4131d7755d8edfc9876acc5160dd8e/test/public/publicAPIs.spec.ts#L869

**Comment by sayali-MSFT** [comment]
@unikoski -Did you get chance to check?
