### ISSUE TITLE
executeDeepLink  does not work with teams Channel 2.0

### ISSUE THREAD

**Issue by NewFuture** [OfficeDev/microsoft-teams-library-js#1328]
When Teams Channel2.0 enabled, calling executeDeepLink doesn't work

 ![image](https://user-images.githubusercontent.com/6290356/187674635-34515916-2f41-4e89-b980-193d758b069c.png)

using teams SDK v1.x

**Comment by nwojod-MSFT** [comment]
Hello @NewFuture, please provide us with more details to help us identify the issue. 
Please provide: Teams JS SDK version you are using, the version of Teams you are running, and any code snippets.

**Comment by Nivedipa-MSFT** [comment]
@NewFuture - Could you please share repro steps to try at our end?

**Comment by NewFuture** [comment]
@Nivedipa-MSFT ping in teams

**Comment by Nivedipa-MSFT** [comment]
As discussed internally there is bug raised for this issue.

**Comment by Nivedipa-MSFT** [comment]
@NewFuture - We have tested this again. Issue is not reproducible on Approvals Template. Could you please check and confirm?

**Comment by NewFuture** [comment]
I will test it tomorrow.

**Comment by Nivedipa-MSFT** [comment]
@NewFuture - Did you get a chance to test this?

**Comment by NewFuture** [comment]
It works now
