### ISSUE TITLE
SDK initialization times out using @microsoft/teams-js

### ISSUE THREAD

**Issue by mballav** [OfficeDev/microsoft-teams-library-js#1329]
Hello there:

I created a Teams tab application by customizing the SSO react app sample from the Teams toolkit. The application redirects the user to our website (inside one of the tabs). I can grab the id-token in react (```teamsfx.getCredentials().getToken("")```) and pass it to our web application via a query parameter. 

This id-token is validated and then passed around to various microservices that comprise our backend.

This part works well, but then, we had the need to refresh the token. So, we decided for the web application (written in Angular) to fetch the token using @microsoft/teamsfx and @microsoft/teams-js npm packages.

While I am not certain if that is the way to go, when I execute the following code inside an angular service, it throws the "<b>SDK initialization timed out</b>" error.

```
    try {
      const teamsFx: TeamsFx = new TeamsFx(IdentityType.User, {         
        "clientId": "ee89fb47-a378-4096-b893-**********",
        "objectId": "df568fe9-3d33-4b22-94fc-**********",
        "oauth2PermissionScopeId": "4ce5bb24-585a-40d3-9891-************",
        "tenantId": "5d65ee67-1073-4979-884c-**************",
        "oauthHost": "https://login.microsoftonline.com",
        "oauthAuthority": "https://login.microsoftonline.com/5d65ee67-1073-4979-884c-****************",
        "applicationIdUris": "api://localhost/ee89fb47-a378-4096-b893-***************",
        "frontendEndpoint": "https://localhost",
        "initiateLoginEndpoint": "https://localhost:8101"
      });

      const creds = await teamsFx.getCredential().getToken('https://graph.microsoft.com/User.Read');
      const token = creds?.token;

      console.log("New Token: ", token);

      const expirationTimestamp = creds?.expiresOnTimestamp;
      this.scheduleRefresh(expirationTimestamp);
      this.tokenRefreshed.next({ token: token, expiresOnTimestamp: expirationTimestamp });
    }
    catch (error) {
      console.error("Error in getNewTeamsToken(): ", error);
    }
```

Am I missing anything here, or is the approach itself wrong? Please advise.

**Comment by sayali-MSFT** [comment]
@mballav - We are looking into this we will get back to you soon.

**Comment by mballav** [comment]
Just fyi, I checked the node_modules folder and I have version 2.28.1 of @azure/msal-browser installed.

If you need any other information, please do let me know.

**Comment by sayali-MSFT** [comment]
@mballav -Are you facing same issue?
https://github.com/OfficeDev/microsoft-teams-library-js/issues/1181

**Comment by sayali-MSFT** [comment]
@mballav - Thanks for providing details, We are try it from our end and let you know.

**Comment by nwojod-MSFT** [comment]
Issue is related to this [5998](https://github.com/OfficeDev/TeamsFx/issues/5998)
