### ISSUE TITLE
Need to add completionBotId as a member of TaskInfo

### ISSUE THREAD

**Issue by billbliss** [OfficeDev/microsoft-teams-library-js#133]
That's actually how it's implemented, but it's essentially an undocumented member. (It's how we get the result of an Adaptive Card when invoked from a tab.)

**Comment by ydogandjiev** [comment]
@billbliss this issue is resolved in the latest version of the SDK:
https://www.npmjs.com/package/@microsoft/teams-js/v/1.3.6
