### ISSUE TITLE
app.getFrameContext() reports 'content' on iOS when in TaskModule.

### ISSUE THREAD

**Issue by bjnsn** [OfficeDev/microsoft-teams-library-js#1330]
I have an unfurl card button with a card action like this:
```
{
      type: "invoke",
      title: "open taskModule",
      value: {
        type: "task/fetch",
        data: targetUrl,
      },
}
```

When the button is clicked it is handled by a subclass of botbuilder `TeamsActivityHandler` - the handler `handleTeamsTaskModuleFetch` responds with a TaskModule response like this:
```
{
    task: {
      type: "continue",
      value: {
        url: targetUrl,
        fallbackUrl: targetUrl,
        height: 800,
        width: 800,
        title: "example title",
      },
    },
  }
```

When the task module is launched I'm checking `frameContext` to conditionally add UI elements (submitting doesn't make sense in some cases, for example if page is launched in a Stage View instead).

In desktop Teams app and web Teams app the frameContext for a task module launched this way is `task`. But on iOS it is reported as `content` – the same as for a Stage View. I can work around it, by modifying the URLs... but this feels like a bug – possibly in teams-js, possibly in the mobile app.

**Comment by sayali-MSFT** [comment]
@bjnsn - Thanks for reporting your issue.
We will investigation this issue and get back to you.

**Comment by sayali-MSFT** [comment]
@bjnsn -We are not able to repro the scenario,
Could you please share any sample/documentation that you are following? So that we can check this locally.

**Comment by AE-MS** [comment]
This is a bug in the Teams iOS app. We will ensure the right engineering team investigates and addresses this and report back as we have updates.

**Comment by ChetanSharma-msft** [comment]
Hello @bjnsn - Sorry for delay in response.
We are checking the updates with engineering team and let you know.

**Comment by ChetanSharma-msft** [comment]
I apologize for delay in response.
We are actively checking the status of bug fixes with engineering team and will update this thread, once it is released publicly.

Thanks!!

**Comment by sayali-MSFT** [comment]
@bjnsn -Issue is resolved. Could you please check it once confirm the same.
Version details-
iOS 16.4.1
Teams Version-5.8.1(5.8.77.2023083301/0506)
