### ISSUE TITLE
register*Handler back compat APIs are throwing errors in v2, but not v1

### ISSUE THREAD

**Issue by MarcinJuraszek** [OfficeDev/microsoft-teams-library-js#1331]
The back compatibility layer seems to have a bug for many (all?) `register*Handler` APIs. In v1 application developer was able to call them even if in a given context particular `register*Handler` API made no sense - the callback would simply never get invoked. With v2 these `register*Handler` APIs have been moved to appropriate capabilities, a set of `isSupported` checks has been added and the old functions were preserved as back compatibility layer. However, the back compatibility layer calls into the new function in v2 capabilities, which means they run the `isSupported` check and ultimately fail. This is a breaking change, as a v1 developer would expect that using the back compatibility layer 'just works' without change in behavior for these APIs.

An example:

In v1 `registerChangeSettingsHandler` works just fine even in a context that's not related to Configurable Tabs. App can register for it, and will simply never be called. With v2 the same function throws `{ errorCode: ErrorCode.NOT_SUPPORTED_ON_PLATFORM }` because the `isSupported` check in `pages.config` fails.

**Comment by sayali-MSFT** [comment]
@MarcinJuraszek - Thanks for reporting your issue.
We will investigation this issue and get back to you.
