### ISSUE TITLE
Does microsoftTeams.settings.initialize() need to be called?

### ISSUE THREAD

**Issue by rggammon** [OfficeDev/microsoft-teams-library-js#1342]
In the latest SDK's, there is now a microsoftTeams.settings.initialize() api. Does this need to be called, or can it safely be ignored?

This method is documented, but with no detail -

https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/microsoftteams.settings?view=msteams-client-js-1.12.1#@microsoft-teams-js-microsoftteams-settings-initialize

Thanks for your guidance!

**Comment by sayali-MSFT** [comment]
@rggammon - We are looking into this we will get back to you soon.

**Comment by sayali-MSFT** [comment]
@rggammon -The settings.initialize() API is an internal method that the SDK automatically calls when its being constructed. There is no need for app developers to call it.

**Comment by rggammon** [comment]
Thank you for clarifying!
