### ISSUE TITLE
Deep links to personal tabs working on all platforms except iOS

### ISSUE THREAD

**Issue by xNiallC** [OfficeDev/microsoft-teams-library-js#1357]
**Context**

Coming here similair to #1201 

We currently have a Teams app with a personal and team context, but using personal context for this issue. The personal context has a bot used to deliver a welcome message and one-way proactive communication about activity in the tab.

The link was created [using the deep link documentation](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links?tabs=teamsjs-v2#deep-link-to-your-tab), and works perfectly on Windows, Mac and Android.

An example of a link we are using is this:

https://teams.microsoft.com/l/entity/dbf692fe-35c1-4511-9178-9131e6511712/dbf692fe-35c1-4511-9178-9131e6511712

The bot sends this as part of a proactive message, and clicking it directs to the personal app. This works as expected on all other devices, and is valid to the documentation.

**Problem**

On all iOS devices however, when this link is clicked, it returns an error: "Link not supported. You can't open this link on the mobile app", despite it being openable on the _Android_ mobile app. This happens regardless of query parameter provided.

Thanksw

**Comment by Meghana-MSFT** [comment]
We are checking this issue.

**Comment by Meghana-MSFT** [comment]
Can you confirm if you are facing the same issue when you directly paste the link to tab in chat and click on it? Please share your device and Teams version details as well.

**Comment by xNiallC** [comment]
Hello, apologies for late reply!

Yes we face the same issue when pasting directly. FWIW, an identical link works on the same iPhone for one tenant, but shows the error for a different tenant.

MS Teams app version: 4.16.1 2022Aug-T2
MS Teams app build: 4.16.77.2022.163501/0912 (general)

Device: iPhone 13 running iOS 16.0

**Comment by Meghana-MSFT** [comment]
We have tried this issue in iOS and it is working fine at our end. We will check internally why it is working in one Tenant and not in another tenant. We will get back to you.

**Comment by Meghana-MSFT** [comment]
Could you please confirm if the app is installed for the other tenant? Do you see this issue in app version - 4.16.1 2022Aug-T2. Engineering team has recommended to upgrade to the latest version.

**Comment by Meghana-MSFT** [comment]
@xNiallC - Could you please confirm if the app is installed for the other tenant? Do you see this issue in app version - 4.16.1 2022Aug-T2. Engineering team has recommended to upgrade to the latest version.

**Comment by Meghana-MSFT** [comment]
Engineering team has also verified the fix. Sharing the version screenshot where it is working. Please let us the exact version that you are on?
![image](https://user-images.githubusercontent.com/81138249/194844608-7fdd04b1-32de-48c6-9efd-e7c770269514.png)

**Comment by Meghana-MSFT** [comment]
@xNiallC - Did you get a chance to check it again?

**Comment by xNiallC** [comment]
Hello, here's the screenshot from my end. It appears to be the same version.

![IMG_6544](https://user-images.githubusercontent.com/21990112/195353496-e675561b-2774-4dc0-b792-83b06563aacc.PNG)

**Comment by Meghana-MSFT** [comment]
Can you please confirm if the app is added in that account? Have you added the app from desktop? If the app is not added in that account, then it will not work on mobile.

Since we cannot repro this issue, could you please help by providing a test account where you see the issue repro'ing?

**Comment by Meghana-MSFT** [comment]
@xNiallC - Can you please help with above question?

**Comment by xNiallC** [comment]
Hi @Meghana-MSFT I'm seeing with a colleague if I can setup a test account to help out.

**Comment by xNiallC** [comment]
Hi @Meghana-MSFT at this time we are unable to offer a test account in our tenant to help with this - Perhaps we could send over the app manifest and you could add this to your tenant and can then test the deep link? Sorry about this.

**Comment by Meghana-MSFT** [comment]
Sure, please share the manifest. We will create a deeplink to the app(your manifest) and verify it.

**Comment by xNiallC** [comment]
[simplydov1.zip](https://github.com/OfficeDev/microsoft-teams-library-js/files/9859907/simplydov1.zip)

Hi @Meghana-MSFT - Here is our manifest. Thanks for your help.

**Comment by Meghana-MSFT** [comment]
We uploaded the above app package to our demo tenant. We tried it in below 2 ways

1. Pasted the deeplink directly in chat - https://teams.microsoft.com/l/entity/dbf692fe-35c1-4511-9178-9131e6511712/dbf692fe-35c1-4511-9178-9131e6511712 
2. Bot has sent an adaptive card with an action which redirects to above tab like below 
```
`{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.3",
  "body": [
    {
      "type": "TextBlock",
      "text": "deeplink test"
    }
  ],
  "actions": [
    {
      "type": "Action.OpenUrl",
      "title": "Navigate",
      "url": "https://teams.microsoft.com/l/entity/dbf692fe-35c1-4511-9178-9131e6511712/dbf692fe-35c1-4511-9178-9131e6511712"
    }
  ]
}`
```

It is working fine in both scenarios. Can you please share if you are trying it differently?

https://user-images.githubusercontent.com/81138249/198336205-66663810-18cd-4faa-ad17-33a9f17caab6.mp4

**Comment by Meghana-MSFT** [comment]
@xNiallC - Could you please let us know how you are installing Personal Tab to which you want to redirect? Are you uploading the app through Admin center and then adding it using Teams web/Desktop? If yes, can you please try uploading app as mentioned below and then verify if the deeplink is working?
![image](https://user-images.githubusercontent.com/81138249/198685333-76c6efda-e63c-4747-b1ad-496ac10d48fd.png)

**Comment by Meghana-MSFT** [comment]
@xNiallC - Did you get a chance to check my comment above?

**Comment by xNiallC** [comment]
HI @Meghana-MSFT I am waiting on some things from my boss around this and will get when I can :)
