### ISSUE TITLE
How can we open a pop-up inside MSTeams Tabs app ?

### ISSUE THREAD

**Issue by adityap31** [OfficeDev/microsoft-teams-library-js#1366]
We are looking to open a pop-up that will be opened when the User clicks on the SSO button on the login page.
The pop-up will open the SSO IDP page for the user to authenticate and on success we ask the IDP to redirect to a tabs app URL inside the pop-up which closes automatically.

We are using msteams-js library directly inside our react app without YoTeams. So we don't want to evaluate Task Tab. Opening a pop-up like window.open will solve our problem.

**Comment by sayali-MSFT** [comment]
@adityap31 -Thanks for reporting your issue.
We will investigation this issue and get back to you.

**Comment by sayali-MSFT** [comment]
@adityap31 -You can enable SSO in Teams for all apps that support Azure AD as an identity provider. In addition to using SSO for authenticating app users in a tab app, you can also use it to enable seamless access across Teams.
You can also use the SSO API to authenticate app users in [task modules](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/what-are-task-modules) that embed web content.

Here is sample Link Tab SSO-https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-sso/csharp

Reference Link-https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-overview

**Comment by adityap31** [comment]
I tried the task modules with the below code 

![image](https://user-images.githubusercontent.com/2426723/192523431-e1e660fe-eb88-4a9e-bad4-9324a1aa6a48.png)


Inside the ssoIpdRedirect i have the below code.

![image](https://user-images.githubusercontent.com/2426723/192523341-b176311c-f876-4c65-bebc-77c6efc9ce40.png)


I am trying to open login Microsoft just for a demo purpose.

<img width="639" alt="image" src="https://user-images.githubusercontent.com/2426723/192522633-d9ec4ec5-cad0-416e-83a4-467cf91e7773.png">

**Comment by AE-MS** [comment]
Hi @adityap31!

If I understand the scenario you described in your original post correctly, the [`authentication.authenticate`](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/authentication?view=msteams-client-js-latest#@microsoft-teams-js-authentication-authenticate) method is intended to be used for situations like this: where you want to open a pop-up window for the purposes of authentication. There's also some further documentation and examples [here](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-tab-aad?tabs=teamsjs-v2).

Is this an option for you? Or am I misunderstanding the use case you're looking to enable?

**Comment by adityap31** [comment]
@sayali-MSFT Will I be able to open the Authentication URL (IDP) than which is other then Microsoft login url.
Example: Our users when click on SSO, we want the users to authenticate on their IPD which has its own URL. Post successful Authentication the user is redirected to the Teams tab and that tab is programmed to be closed automatically.

**Comment by adityap31** [comment]
@sayali-MSFT I tried the authentication.authenticate however inside the pop-up I am not able to open the URL which is not the same domain as of the app. It only works when the teams app is opened inside any browser.

**Comment by adityap31** [comment]
This Can be closed, the recommended solution with authentication. authenticate worked. Thank you !
