### ISSUE TITLE
Integrated Teams Spell Checker Should be an Option for Custom App Tabs on Desktop Client

### ISSUE THREAD

**Issue by mmwoodfo** [OfficeDev/microsoft-teams-library-js#1368]
There are a few closed issues regarding this (#393 & #293), but the core problem still persists. It seems as though there should be an option (either by default or a togglable feature) to allow custom tab apps to hook into the team's desktop clients' spell checker.

It doesn't seem reasonable to assume all custom tabs will do their own spellchecking as it is inconsistent between the web and desktop versions and it introduces inconsistencies between the different areas of teams. (e.g. users will experience different spellchecking rules depending on the tab they are in). Additionally, as noted in the linked issues, this will fix many broken custom app tabs as well as introduce a plug-and-play option for spell check instead of forcing developers to roll their own version of it.

Is there any ETA or plan for the implementation of this feature?

**Comment by Meghana-MSFT** [comment]
@mmwoodfo - we are checking internally about this feature, and we will update you. Thanks.

**Comment by Meghana-MSFT** [comment]
Currently this feature is not available. There is no ETA or plan for the implementation of this feature. To achieve your requirements, we recommend you give your feedback in [Microsoft Teams feedback portal](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472). 

Microsoft will always focus on customer’s feedback and experience. Some new features would be added to the services based on customers' feedback in the future, and your good ideas will be very helpful for them to improve the service.

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.

**Comment by mmwoodfo** [comment]
Opened the same ticket on the feedback portal...
https://feedbackportal.microsoft.com/feedback/idea/ac5fb3dd-7154-ed11-a81b-000d3a7e4185
