### ISSUE TITLE
[Question] single app, multiple tenant scenario 

### ISSUE THREAD

**Issue by hbnrmx** [OfficeDev/microsoft-teams-library-js#1378]
Hi everyone, a question on behalf of my organization:
We have a single teams application with a Tab that is supposed to serve each tenant their own self-hosted version of our `teams-tab-app` a la:

```html
<html>
  <body>
    ...
    <script>
      await app.initialize()
      
      // find out which tenant the user belongs to
      const context = await app.getContext()
      const tenantId = context.user.tenant.id
        
      // redirect to their version of the tab
      const tenantEndpoint = await getTenantEndpoint(tenantId) 
      window.location.replace(tenantEndpoint + "/teams-tab-app")
    </script>
  </body>
</html> 
 ```
 
And then also try to initialize teams within the tenant specific app like:
```
...
await app.initialize()
...
```

However, the initialization fails with:

```
VM5:2 Failed to execute 'postMessage' on 'DOMWindow': 
The target origin provided ('https://our-tab.westeurope.cloudapp.azure.com') does not match
the recipient window's origin ('https://our-app.the-tenants-server.com').
```

Before we dive into identifying a possible solution;
Is this single-app proxying to multiple tenants scenario supported?

Thank you!

**Comment by Nivedipa-MSFT** [comment]
@hbnrmx - Could you please share the details asked by @AE-MS?

**Comment by hbnrmx** [comment]
@AE-MS 

Hi again. Sorry for the delay.
The only frame that is involved in this exchange is the

```
<iframe id="extension-tab-frame" src="https://our-tab.westeurope.cloudapp.azure.com" ...>
```

 which teams uses to embed our tab. I suspect the issue is that the hosts expects us to stay within the confines of the `validDomains`. Thanks for pointing me there! I will also experiment with the `validMessageOrigins?: string[]` option in `app.initialize()` and report back if we still face this issue. 
 
 Thank you both for your time!
