### ISSUE TITLE
microsoftTeams.authentication.notifySuccess not working in Firefox

### ISSUE THREAD

**Issue by nastassiar** [OfficeDev/microsoft-teams-library-js#1386]
notifySuccess does not work as expected in Firefox or on iOS. This is the snippet of code.

microsoftTeams.initialize();
microsoftTeams.authentication.notifySuccess({
            parameters: "data"})

It works as expected on Edge, Chrome and in the Desktop app, which is that it closes the pop up and calls OnTeamsSigninVerifyStateAsync and everything works as expected. 

But on Firefox and Mobile the window remains open and when closed nothing happens.

**Comment by sayali-MSFT** [comment]
@nastassiar - Thanks for reporting your issue.
We will investigation this issue and get back to you.

**Comment by nastassiar** [comment]
No it is not. I am currently using 1.11 and there doesn't appear to be any errors. It just doesn't call OnTeamsSigninVerifyStateAsync

**Comment by nastassiar** [comment]
Any updates on this?

**Comment by ChetanSharma-msft** [comment]
Hello @nastassiar -  We recommend you to please use the latest version of Edge/Chrome browser.
Is there any specific reason to user Firefox browser?

Also, please confirm whether you are testing it in Teams client in Firefox or Teams app in mobile client?
Please share the error logs, if any.

**Comment by nastassiar** [comment]
For desktop I am using the Firefox browser and for Mobile the Teams app. The users of my app may use Firefox and I would like to support that scenario. Is Firefox not supported? I can't recreate the issue on Edge or Chrome. There are no errors I can see. OnTeamsSigninVerifyStateAsync is just never called.

**Comment by sayali-MSFT** [comment]
@nastassiar -We are checking the scenario on Firefox, It's working fine from our end.
Could you please share any error log so that we can investigate from our end? Thanks!

**Comment by nastassiar** [comment]
@Marcopelegrini

@sayali-MSFT 

There aren't any errors. The problem appears to be  origin/parent is null so the call to sendMessageToParent('authentication.authenticate.success', [result]); doesn't work.

**Comment by nastassiar** [comment]
We've found out the issue. Our auth service was using Window.Open to do the redirect so in FireFox, Safari and iOS this was opening a new page with no history, so when it got to notifySuccess there was no parent. It would be great if the SDK threw an error if parent was null so the issue would be more clear to future developers.
