### ISSUE TITLE
This tab is not available on mobile

### ISSUE THREAD

**Issue by nbelyh** [OfficeDev/microsoft-teams-library-js#1387]
Have been notified recently that our (published) app stopped working on mobile, with the above message, "This tab is not available on mobile". The app is a custom teams tab basically.

What may be causing this issue?

It seems that we have not changed anything (neither in the manifest nor in the hosting). 
Are there some changes in the teams policy or maybe new requirements or changes?

In the destop/web the app works like it did before.
On the mobile, if you try to click a link to the tab, it shows this notification instead of opening the tab like before.

Manifest version: 1.9
"@microsoft/teams-js": "^1.12.1",

Not sure if the versions are related, since the client shows that tooltip without even trying to open the tab?

Looks like the problem appears with some latest update of the Teams client (our app still works on older teams mobile client), i.e. it's quite new. The app is still working fine with Teams client from June 2022, but starts showing that message "tab is not available on mobile" if the Teams client is updated to the latest version.

Now there is also a button to "Add an app.." in the teams app on mobile. Are there some new requirements for existing apps because of this maybe (so that existing apps won't work on mobile unless adapted)?

Related observation: all our app tabs created disappeared on "More..." tab after mobile teams client is updated

![image](https://user-images.githubusercontent.com/528366/194886707-faa5f866-c354-4bd6-a983-c56e6d5b35f3.png)

**Comment by nbelyh** [comment]
Looks like the problem appears with some latest update of the Teams client (it works on older teams client), i.e. it's quite new.
The app is still working fine with Teams client from June 2022, but shows that message "tab is not available on mobile" if I update the Teams client to the latest version.

**Comment by Meghana-MSFT** [comment]
We are checking with the engineering team about this issue, we will update you.

**Comment by Meghana-MSFT** [comment]
Can you please share your app name or app id?

**Comment by nbelyh** [comment]
@Meghana-MSFT Yes, sure. The app is VisPlan, it is not exactly my app though, but an app of a company I'm working on. The app id is: e4640daf-2fd5-4ea8-8c9c-991cca4ab17f. The partner id (MPN ID) of the company: 3124604

May be related: found out that there is a problem in the app when trying to add it using the mobile experience (a possiblity to add apps on mobile, from the "more" page was added this year to the mobile clients). The 'teamsSiteUrl' is missing from the context in this case, and the app is not starting properly in this case (was last published before this feature existed). Not sure if this can be related?

**Comment by Meghana-MSFT** [comment]
@nbelyh - Engineering team is also able to reproduce this issue, Team is working to find the RCA. We will get back to you with the update.

**Comment by nbelyh** [comment]
@Meghana-MSFT thank you for the update. We could for now just disable adding our app on mobile (show something like "Please add the app using desktop/web", and then add the support for this feature properly from our side). Would that remove the problem with blocking our app on mobile (if it was blacklisted/blocked somehwere by the teams infrastructure)?

**Comment by Meghana-MSFT** [comment]
Engineering team has shared the below RCA - 

The tab is not visible in More section and clicking on tab chiclet shows error is because of websiteUrl entity missing in settings json of tab object.
When user configures the tab for an app in chat/channel, through setSettings API teams receive settings json which has websiteUrl, web/desktop doesn't care about this entity but mobile client(Android) does care about this entity and if the entity is not available, it doesn't allow the tab to be displayed in More section as well as doesn't open the tab from tab chiclet.
Adding app on mobile will also have similar issue as from web/desktop, so there's no need to disable Add app on mobile.
 
Could you please check with app developers if they have stopped setting websiteUrl in the settings json for setSettings API, if so, please request them to enable it so that they can access the tabs on Android.

**Comment by Meghana-MSFT** [comment]
@nbelyh - Engineering has said that - 

Enabling websiteUrl for existing tabs(new tabs as well) will surely help in displaying the tabs back on Android.

You can try it for a particular tab, once you enable the websiteUrl in the setSettings API you'll have to update the settings of the tab by going into Settings option of the tab on web/desktop, through this way the existing tabs will get updated with the websiteUrl.
 
If you face any issues with this, kindly share test credentials where you see the issue, we'll check from our side and share further approach.

**Comment by nbelyh** [comment]
@Meghana-MSFT Thank you for your help. Adding `websiteUrl` propery to tab settings worked.
Now, the application does open the tabs on mobile (like it did before). When opening a tab on desktop, we verify that there is no `websiteUrl` set and if it is the case, we set it then for this tab.

The strange thing is, the `websiteUrl` **was never set by our application**, since the very first deployment in 2020. But until recent, the tabs were opening on mobile just fine, and were listed on "more" tab...
