### ISSUE TITLE
Need to be able to constrain the surfaces where our app (VSB Hub) is offered/can be installed.

### ISSUE THREAD

**Issue by whelanjohn** [OfficeDev/microsoft-teams-library-js#1394]
We need to limit the visibility of our app to a specific host for our MVP release. The telco scenario which we are supporting for that release works targets that surface (e.g. one of our main initial tasks to help users achieve on VSBHub is getting their copy of the Office clients installed). I expect in the future that we will have scenarios for VSB Hub which would make it useful for it to appear in other surfaces like Teams or Outlook, but not for our MVP release. This could be implemented either as an opt in or opt out mechanism in the app manifest.

**Comment by Nivedipa-MSFT** [comment]
@whelanjohn - Could you please help by suggesting this feature on - [Microsoft Teams · Community](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472)

**Comment by nwojod-MSFT** [comment]
Hi @whelanjohn, thank you for your request. Your request is outside of our team's scope. We are working to route it to the right team and will provide you with an update as soon as possible. Thank you.

**Comment by nwojod-MSFT** [comment]
@whelanjohn we have shared your feature request with the appropriate engineering team. We will provide further updates.

**Comment by ChetanSharma-msft** [comment]
@whelanjohn, @nwojod-MSFT - As you already have a separate thread going on, I am closing this issue.
Please feel free to reopen it, if required.
