### ISSUE TITLE
Copy to Clipboard not working in MS Teams iFrame because of blocked Clipboard API

### ISSUE THREAD

**Issue by StefanH114** [OfficeDev/microsoft-teams-library-js#1402]
Currently it's not possible to use the Clipboard API in an Teams iFrame.

The reason seems to be that the Clipboard API is blocked.
Error Message:
"Uncaught (in promise) DOMException: The Clipboard API has been blocked" 

Are there any plans to unblock the Clipboard API in MS Teams??

**Comment by Prasad-MSFT** [comment]
@StefanH114 - This feature is currently not supported. There is already a UserVoice raised for this:
[Allow Clipboard API access on Custom Teams Apps – Welcome to UserVoice!](https://microsoftteams.uservoice.com/forums/555103-public/suggestions/43055961-allow-clipboard-api-access-on-custom-teams-apps).

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.

**Comment by AE-MS** [comment]
@StefanH114 Does the new [clipboard capability](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/clipboard?view=msteams-client-js-latest) meet your needs?
