### ISSUE TITLE
GetAuthToken fails in Office.Com

### ISSUE THREAD

**Issue by twgolds** [OfficeDev/microsoft-teams-library-js#1405]
I have integrated Teams with SSO into a SAAS application.

When signing in via the Teams (desktop or web) everything works as expected.

The app also appears in Office.Com ( desktop and web ) but when accessed it fails with the error:

**"Error: Error: Unable to get access token"**

This occurs when the following code is executed:

`microsoftTeams.app.initialize().then(() => {
	microsoftTeams.app.notifySuccess();
		microsoftTeams.authentication.getAuthToken()
                    .catch((e) => {
                        alert(e);
                    })
                    .then((token) => {
                        ... do some stuff ...
                    });
            });`

The call to getAuthToken() does not appear to be supported in Office.Com.

I am unsure whether I am missing any additional configuration to ensure `getAuthToken` works.

Could you confirm that getAuthToken is expected to work in Office.com?  And if so, could you point me in the direction of the configuration required to get it to work.

If it is not supported within Office.Com, what is the proposed Microsoft approach to SSO into an Teams-App-Hosted-In-Office?

Thanks

**Comment by sayali-MSFT** [comment]
@twgolds - Thanks for reporting your issue.
We will investigation this issue and get back to you.

**Comment by AE-MS** [comment]
Hi @twgolds. Thanks for providing the error message and the code you're using. `getAuthToken()` is (in theory) supported in Office.com so I'm sorry that you're running into an issue here (and that the error message is unhelpful!)

Two things would help us with the investigation:
1. Can you verify that you have added the two Office.com client IDs as authorized client applications for your app? You can find information about doing this [here](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-register-aad#to-configure-authorized-client-application). The two client IDs in question are `4765445b-32c6-49b0-83e6-1d93765276ca` and `0ec893e0-5785-4de6-99da-4ed124e5296c`.
2. If that doesn't fix the issue, can you just check in the browser developer tools to see if any obviously related errors are showing up in the console when you are calling `getAuthToken()`?


Thanks!

**Comment by twgolds** [comment]
Thanks.  That did the trick.  Working fine with no issues now.

When I originally set up the app registration the GUID's for Office weren't in the documentation.  I have a similar problem with SharePoint, hopefully, the solution is just as simple.
