### ISSUE TITLE
Runtime supports information not correctly relayed to Auth window

### ISSUE THREAD

**Issue by MarcinJuraszek** [OfficeDev/microsoft-teams-library-js#1408]
When opening a popup window via `authentication.authenticate` API the newly created window does not get the correct runtime support information, which means `isSupported` checks in capabilities aren't correct.

After configuring a test host to only support a handful of capabilities and loading a test app, I see following runtime information set in the main page:

![image](https://user-images.githubusercontent.com/6841973/196493854-e82ebc45-14c8-4e16-b014-2149b0788c38.png)

After opening an auth popup window with `authentication.authenticate` from that page, the runtime information is missing and TeamsJs falls back to the default set of based on version number:

![image](https://user-images.githubusercontent.com/6841973/196494314-c732174c-6ac9-48e7-a64b-0a47b2cb53e0.png)

I believe the issue is in how TeamsJs handles `authentication.authenticate` for web hosts and how it registers a handler for `initialize` calls coming from that window [here](https://github.com/OfficeDev/microsoft-teams-library-js/blob/main/packages/teams-js/src/public/authentication.ts#L349):

```ts
    // Set up an initialize-message handler that gives the authentication window its frame context
    registerHandler('initialize', () => {
      return [FrameContexts.authentication, GlobalVars.hostClientType];
    });
```

This response should include runtime support information for the flow to work correctly.

**Comment by sayali-MSFT** [comment]
@MarcinJuraszek - Thanks for reporting your issue.
We will investigation this issue and get back to you.

**Comment by AE-MS** [comment]
Thanks for the details here. We've opened a tracking bug for this and will look to prioritize fixing it.

**Comment by nwojod-MSFT** [comment]
The bug has been added to our backlog and we'll keep the community informed when it's fixed. We couldn't find any implications that would cause issues, so it will be prioritized with other bugs. Feel free to reopen this issue if you encounter any problems. Thank you.
