### ISSUE TITLE
"SDK initialization timed out." error in Teams Mobile client

### ISSUE THREAD

**Issue by tavikukko** [OfficeDev/microsoft-teams-library-js#1437]
Started to get this error "SDK initialization timed out." in Teams mobile app, when trying to load SharePoint page in iframe. Seems related teams sdk v2 rollout.

Here is simple sample SPFx tab in Teams, works in browser and in Desktop, but not in ios/android Teams mobile app, shows error in console 'SDK initialization timed out.' This code used to work before teams sdk v2 rollout.

```typescript
import * as React from 'react';
import { IHelloWorldProps } from './IHelloWorldProps';

export default class HelloWorld extends React.Component<IHelloWorldProps, {}> {
  public render(): React.ReactElement<IHelloWorldProps> {
    return (
      <iframe src="https://tenant.sharepoint.com/sites/site" />
    );
  }
}
```

**Comment by sayali-MSFT** [comment]
@tavikukko - Thanks for reporting your issue.
We will check it from our end and get back to you.

**Comment by sayali-MSFT** [comment]
@tavikukko - We are able to repro that issue , We have raised bug for the same and concerned team is looking into it. We will inform you once we get any update.
![sdk](https://user-images.githubusercontent.com/93527375/200554525-3e91dba1-b003-4a05-ac07-0f040c78608e.png)

**Comment by ChetanSharma-msft** [comment]
Hello @tavikukko - Just wanted to confirm whether you are getting error in SDK V1 or SDK V2?

**Comment by sayali-MSFT** [comment]
@tavikukko-

**Comment by anmaur** [comment]
@tavikukko, The teamsJs App in an iframe requires a teamsJs App running as its parent to act as a hosting layer and ensure communication working with the Host. In your example, Is the Hello world app also a teamsJs App? Where is the Hello world deployed? If you followed a sample, Could you pls share a link to that?

Also, as you mentioned that it's not working in v2 but it worked in v1, Could you pls share more details here as I could not get to repro it?

**Comment by Rookie-zrx** [comment]
![image](https://user-images.githubusercontent.com/54833166/220594351-4e4a7ae6-e5db-42da-a810-b6d8e27d7e0c.png)
@tavikukko

**Comment by AE-MS** [comment]
> ![image](https://user-images.githubusercontent.com/54833166/220594351-4e4a7ae6-e5db-42da-a810-b6d8e27d7e0c.png) @tavikukko

Hi @Rookie-zrx! In your example with the screenshots, are you also creating this as an SPFx app like @tavikukko described?
