### ISSUE TITLE
`registerOnLoadHandler` and `registerBeforeUnloadHandler` not working on Teams Mobile

### ISSUE THREAD

**Issue by tiennguyen1293** [OfficeDev/microsoft-teams-library-js#1445]
`registerBeforeUnloadHandler` and `registerBeforeUnloadHandler` not trigger when user changes personal tab on Teams mobile

Please help me to investigate.

`"@microsoft/teams-js": "1.11.0"`
`Teams Mobile App: 4.20.0`

**Comment by Nivedipa-MSFT** [comment]
@tiennguyen1293 - Thanks for reporting your issue. We will test this and update you soon.

**Comment by tiennguyen1293** [comment]
Updated "@microsoft/teams-js": "^2.5.0", but it's still not work

**Comment by ChetanSharma-msft** [comment]
Hello @tiennguyen1293 - We will test with both the versions and get back to you.

**Comment by Nivedipa-MSFT** [comment]
@tiennguyen1293 - Could you please confirm if you are getting same results on web Teams client and Desktop Teams client?

**Comment by tiennguyen1293** [comment]
Both functions work well on Web and Desktop Teams excluding iOS and Android Teams.

**Comment by Nivedipa-MSFT** [comment]
@tiennguyen1293 - We have tried below code and tested on web, desktop and on android mobile. But we are getting error code 100 which is not supported on platform.

 ```
  microsoftTeams.teamsCore.registerBeforeUnloadHandler().then((readyToUnload) => {
            console.log("Got Before Unload for teams");
            readyToUnload();
            return true;
        }

        );

        microsoftTeams.teamsCore.registerOnLoadHandler().then((data) => {

         console.log("Got load from teams",data.contentUrl,data.entityId);
            microsoftTeams.appInitialization.notifySuccess();
        }

        );
```
Could you please share your code to check at our end?

**Comment by ChetanSharma-msft** [comment]
Hello @tiennguyen1293 - We have also created the custom Teams app and used the above code & it is not working.
Could you please elaborate how you have created your Custom app & it's working for you in Teams Web/Desktop client?

However, we have tested it in the internal version of Teams, and it is working fine.
Looks like it is not publicly rolled out.

We will confirm with engineering team and let you know the updates.

**Comment by tiennguyen1293** [comment]
Hi @ChetanSharma-msft, i'm meaning the callback didn't execute if you don't understand what i mean, please see the video.

https://user-images.githubusercontent.com/26110369/201316820-e81c025a-6af8-4ab8-9ab1-fba628b23eba.mp4

**Comment by ChetanSharma-msft** [comment]
Hello @tiennguyen1293 - If I am not wrong, you have created 2 personal tabs and showing a html page directly?

Could you also share your manifest and reference sample code, so that we can try it from our end?

**Comment by Nivedipa-MSFT** [comment]
@tiennguyen1293 - We have thave created 2 personal tabs and called registerOnLoadHandler and registerBeforeUnloadHandler .
But we are getting error code 100.
Please see the video for your reference.
[recording-2022-11-12-11-06-33.webm](https://user-images.githubusercontent.com/92150070/201459222-2e05c3f5-9d5a-4035-982f-a6c7e178b1d8.webm)

Could you also share your manifest and reference sample code, so that we can try it from our end?

**Comment by ACBatosalem** [comment]
Hi, we are also experiencing this issue in our custom Teams app. `registerBeforeUnloadHandler` works in Teams Desktop and Web but not in iOS and Android devices. We are currently using `@microsoft/teams-js: 1.12.1` and Teams Desktop version is `1.5.00.31168` .

Is it expected that `registerBeforeUnloadHandler` does not work for mobile devices?
Here is a sample code
```
export default async () => {
  await new Promise((resolve) => {
    setTimeout(() => resolve(), 1000)
    microsoftTeams.initialize(() => {
      microsoftTeams.registerBeforeUnloadHandler((readyToUnload) => {
        alert('unload handler')
        readyToUnload()
        return true
      })
      resolve()
    })
  })
}
```

Thank you.

**Comment by Nivedipa-MSFT** [comment]
@ACBatosalem - We will test this using @microsoft/teams-js: 1.12.1 and update you soon.

**Comment by Nivedipa-MSFT** [comment]
@ACBatosalem - We got an update from engineering team saying that it is expected behaviour. `registerBeforeUnloadHandler `does not work for mobile devices.

**Comment by ACBatosalem** [comment]
@Nivedipa-MSFT , is there an alternative to `registerBeforeUnloadHandler` that we can use for mobile devices?
Our use case is that we need to perform an action when the user changes tabs in our custom app and when the user leaves the custom app.

Are there any plans to support `registerBeforeUnloadHandler` in mobile devices?

Thanks.

**Comment by Nivedipa-MSFT** [comment]
@ACBatosalem - We are checking this with engineering team. We will let you know once we have any updates on it. Thanks
