### ISSUE TITLE
Windows/Mac MS Teams native app SSO with pop up and require to input password 

### ISSUE THREAD

**Issue by vonguyen1982** [OfficeDev/microsoft-teams-library-js#1449]
I am implementing SSO authentication. I follow SimpleAuth .Net Core sample with latest version of MS Teams library.

With any browser even in private mode, the SSO flow is working fine but with MS Teams Native App in Windows/Mac we see the login pop up screen coming all the time with email same as in login_hint and it requires to input password.

If I go to In Windows\Settings\Accounts\Access work or School and connect the ms teams account then the login pop-up never pop up again. Otherwise if the MS Teams account is not connected then the pop up will appear and require to input password.  

Is that the pop up with the MS Teams native app expected behavior of SSO flow?  We expect it should login silence all the time and in any environment.

**Comment by ChetanSharma-msft** [comment]
Hello @vonguyen1982 - Could you please confirm whether you have implemented Tab SSO or Bot SSO in Teams?

**Comment by vonguyen1982** [comment]
I implemented Tab SSO in Teams app

**Comment by vonguyen1982** [comment]
<img width="922" alt="image" src="https://user-images.githubusercontent.com/68211937/201581642-28c9b219-91d0-48cb-a03d-e7cb522162ff.png">

**Comment by vonguyen1982** [comment]
Javascript version 
<script src="https://res.cdn.office.net/teams-js/2.0.0/js/MicrosoftTeams.min.js" asp-append-version="true"></script>

**Comment by ChetanSharma-msft** [comment]
Hello @vonguyen1982 - Thanks for sharing the details.
We will try it from our end and let you know the updates.

**Comment by Meghana-MSFT** [comment]
We tried setting up [tab-sso sample](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-sso/csharp) and we see the same behavior as shown in the sample in both web and Desktop clients. My account is not connected in Windows\Settings\Accounts\Access work or School. 
This sample uses SDK V2.

**Comment by vonguyen1982** [comment]
I think you are use different sample. I am using this https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-channel-group-config-page-auth/csharp

I will try with your new sample(https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-sso/csharp) and see. Thanks for your help

**Comment by vonguyen1982** [comment]
@Meghana-MSFT Could you please try to run https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-channel-group-config-page-auth/csharp on your local and see if you have same issue with me. Thanks.

**Comment by Meghana-MSFT** [comment]
Thank you for confirming, we will also try the sample you have mentioned and update you.

**Comment by Meghana-MSFT** [comment]
We did setup the sample [tab-channel-group-config-page-auth](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-channel-group-config-page-auth/csharp). The login popup to enter password is appearing after clicking on Login to Simple Azure AD --> Sign in, only when the account is not connected in Windows\Settings\Accounts\Access work or School. 
It does SSO silently in browser and in desktop(when the account is connected) which is correct. We will check the behavior related to when the account is not connected and back to you. Thank you.

**Comment by vonguyen1982** [comment]
@Meghana-MSFT Appreciated your help. Please let us know as soon as you get solution. This issue currently blocks us from submitting our app to app store. Thank you.

**Comment by Meghana-MSFT** [comment]
Sure, I will post here as soon as I have an update.

**Comment by Meghana-MSFT** [comment]
Engineering team has given the below suggestion -

It is expected behavior. If an app is opening an auth popup then it's not going to support SSO in all scenarios. To support SSO in all cases, an app developer needs to implement auth as described here:
https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-overview

**Comment by vonguyen1982** [comment]
Thank you for your quick response. @Meghana-MSFT I saw many place said MSAL does not work with 3rd idp(keycloak) and I am using that idp. Could you please check if MSAL will work with the idp?

**Comment by AE-MS** [comment]
@vonguyen1982 just as a small and mostly unrelated side note: I notice that in your sample code you aren't waiting for the call to `initialize` to finish. Waiting for this call to finish is required in order to use the rest of the functions in the teams-js library. This probably isn't causing you any problems like what you're asking about here, but making other calls in teams-js without waiting for `initialize` to finish is a race condition (note the remarks section [here](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/app?view=msteams-client-js-latest#@microsoft-teams-js-app-initialize)).

**Comment by vonguyen1982** [comment]
Thank you for your suggestion @AE-MS. I did try multiple options and even your one as well but it does not seem to help.

**Comment by Meghana-MSFT** [comment]
@vonguyen1982 - As you correctly said MSAL does not work with 3rd party idps. We will still confirm once and get back to you.

**Comment by iambmelt** [comment]
> Thank you for your quick response. @Meghana-MSFT I saw many place said MSAL does not work with 3rd idp(keycloak) and I am using that idp. Could you please check if MSAL will work with the idp?

@vonguyen1982 The MSAL auth SDK supports authentication only with the Microsoft Identity Platform; it does not support 3rd party IdPs. For more information see [learn.microsoft.com](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-overview) or the [GitHub project page](https://github.com/AzureAD/microsoft-authentication-library-for-js#microsoft-authentication-library-for-javascript-msaljs).
