### ISSUE TITLE
profile.isSupported() not working properly

### ISSUE THREAD

**Issue by matthiasdilger** [OfficeDev/microsoft-teams-library-js#1450]
Using 2.5.0, the following code
```
if(microsoftTeams.profile.isSupported()) {
microsoftTeams.profile.showProfile({targetElementBoundingRect:DOMRect.fromRect({x:0, y: 0, width:300,height:300}), triggerType: 'MouseClick', persona:{identifiers:{AadObjectId:"<userObjectId>"}}});
}
```
produces an error "API is not supported on platform" with error code 100 on Teams web. Shouldn't isSupported() catch that?

**Comment by Nivedipa-MSFT** [comment]
@matthiasdilger - isSupported() method only return true or false value. It will not catch the error. You have to add custom code for catch and handle errors when you are calling API.

**Comment by matthiasdilger** [comment]
@Nivedipa-MSFT If calling isSupported() returns true but calling the method produces an error "is not supported", what exactly is isSupported() checking for?

**Comment by Nivedipa-MSFT** [comment]
@matthiasdilger - We will test this and update you soon.

**Comment by Nivedipa-MSFT** [comment]
@matthiasdilger - We have tested the below code on Windows web Teams client and on Edge Browser, but we are getting false value as a result. We are not getting error code 100 error.
```
    microsoftTeams.app.initialize();
    if (microsoftTeams.profile.isSupported()) {
    
       console.log("true");
    }
    else
    {
console.log("false");
    }
```
Could you please share on which browser you are testing this? It will help us to repro the issue.

**Comment by matthiasdilger** [comment]
@Nivedipa-MSFT Thanks for the quick reply. I am using Chrome 107.0.5304.110 and Teams Js 2.5.0

My code looks essentially like this (meeting chat tab):

```
<script
  src="https://res.cdn.office.net/teams-js/2.5.0/js/MicrosoftTeams.min.js"
  integrity="sha384-0lOzlvRkoNWAcLkbUTuao6TaDa7zI7v+q2PUAm3lrMxUp43PFwf2kaQu7FYT9fjS"
  crossorigin="anonymous"
></script>
<script>
microsoftTeams.app.initialize();
microsoftTeams.app.getContext().then((context) => {    
    microsoftTeams.app.notifySuccess();  
    alert(microsoftTeams.profile.isSupported());
});
</script>
```

<img width="434" alt="Screen Shot 2022-11-14 at 14 03 35" src="https://user-images.githubusercontent.com/5625718/201587166-efdc645d-6171-41e7-b914-dab76c1794ad.png">

**Comment by Nivedipa-MSFT** [comment]
@matthiasdilger - We will test this on chrome browser and let you know the updates.

**Comment by Nivedipa-MSFT** [comment]
@matthiasdilger - We have tested this and able to repro your issue. We will raise the bug for the same. We will let you know the updates.

**Comment by Nivedipa-MSFT** [comment]
@matthiasdilger - We are checking the bug status with the engineering team. We will let you know once we have any update.

**Comment by TrevorJoelHarris** [comment]
Hi @matthiasdilger, I'm really sorry that you ran into this bug. The profile capability is current in beta, and you are right that we are incorrectly returning isSupported() true when it should be false (The profile capability isn't supported on your platform right now). We should get a beta release of our npm package out that fixes your problem next week, and an official 2.6.0 release that contains the fix sometime on the week of December 5th.

Apologies once again, let us know if you have any other questions!
