### ISSUE TITLE
Deep links to tabs is not working on iOS

### ISSUE THREAD

**Issue by ceroles** [OfficeDev/microsoft-teams-library-js#1451]
We are currently using deeplinking in our Teams custom app for users to be able to open directly to a specific tab/page. It is working fine for Windows, Mac, and Android. It also used to work for iOS until recently.

We have tried the following formats for the generated deeplinks:
`msteams:/l/entity/<appId>/<entityId>?context={"subEntityId":"<subEntityId>"}`
`https://teams.microsoft.com/l/entity/<appId>/<entityId>?context={"subEntityId":"<subEntityId>"}`

For the `msteams:/...`, it is only opening the Teams app but not going to the custom app.

For the `https://teams.microsoft.com/...`, it only works if the Teams app is already open in the background, otherwise same issue as the `msteams:/...` above.

Additionally, unlike others who seem to be encountering similar issue, we are not getting the "Link not supported" error message.

Thank you.

**Comment by Meghana-MSFT** [comment]
We will check this at our end and get back to you.

**Comment by Meghana-MSFT** [comment]
We are also able to repro this behavior. We will check internally and get back to you.

**Comment by ceroles** [comment]
Thank you for checking. May I know the estimated timeline for the fix?

**Comment by Meghana-MSFT** [comment]
Currently we do not have any ETA to share, I will keep you posted on the updates.

**Comment by Meghana-MSFT** [comment]
This bug has been fixed and we have verified the fix. We checked with iOS 16.3 & Teams version: 5.6.0. Could you please check once? Thanks!
