### ISSUE TITLE
stopSharingAppContentToStage is private and mostly not working

### ISSUE THREAD

**Issue by marekcis** [OfficeDev/microsoft-teams-library-js#1464]
Hi,
I'd like to ask, why is `stopSharingAppContentToStage` method private and if there are any plans of making it public.
I cannot imagine single use-case where you can programatically start sharing and then let the user close it for some reason in MS Teams UI.

Thank you in advance for explanation.

**Comment by Meghana-MSFT** [comment]
We are checking this with the engineering team, we will update you.

**Comment by marekcis** [comment]
@Meghana-MSFT thanks, friendly reminder since it's been a week already :)
