### ISSUE TITLE
Can we use openChat funtion from chat in production environment?

### ISSUE THREAD

**Issue by Anandks1993** [OfficeDev/microsoft-teams-library-js#1470]
We have a requirement to open teams chat to specific user from Personal app. We tried `<a href="https:[//teams.microsoft.com/l/chat/0/0?users=XXXXXXXX@YYYY.com](mailto://teams.microsoft.com/l/chat/0/0?users=XXXXXXXX@YYYY.co.jp)">` creating this deep link but it is replacing our Personal app url and opening teams app. But what we need is the exact feature of `openChat` function that is to open chat inside teams from teams personal app. I see openChat is mentioned as a preview in documentation. 

![image](https://user-images.githubusercontent.com/26414695/206169070-65e43dbf-7bd2-47f6-b65f-9daece15b0f7.png)

Is there any other way to achieve this functionality without using `openChat` function?

**Comment by Anandks1993** [comment]
I found a solution with `app.openLink` and it is working fine. But my question is still open for `openChat` function.

**Comment by sayali-MSFT** [comment]
@Anandks1993 - Currently we do not have an ETA to share when this will be available in production. Please [subscribe to RSS feed](https://learn.microsoft.com/en-us/microsoftteams/platform/whats-new?pivots=ga-feature#to-configure-rss-feed) to get notified about the changes.

**Comment by Anandks1993** [comment]
@sayali-MSFT Thank you, will subscribe to the feed.
