### ISSUE TITLE
GetAuthToken failing with RenewalTimeout or Cannot start retry fetch of ADAL tokens. 

### ISSUE THREAD

**Issue by picorel** [OfficeDev/microsoft-teams-library-js#1473]
Hello!
We noticed that `getAuthToken` sometimes fails with the reason `RenewalTimeout`.
We have seen the error using the versions `@microsoft/teams-js 1.10.0` and `2.5.0`, happening intermittently for some users.

We could reproduce it in the Teams Browser Client by leaving the app in the background or sleeping the computer for some time. When we come back (maybe on the next day), there’s the error `RenewalTimeout`, with this in the console

<img width="547" alt="renew timeout console" src="https://user-images.githubusercontent.com/74991114/206277350-303768da-0696-402f-8b48-bc82de0f2cba.png">

I don’t know if there are other situations where this error could arise. 

Can you provide more information on which is the expected behavior and what should we do when `getAuthToken` returns this error? 
E.g., should we call getAuthToken again, reload our app, ask the user to reload Teams, etc.?

We have also seen the error `“Cannot start retry fetch of ADAL tokens, isPassive: false”` for multiple users, but we don’t know the steps to reproduce it. 
Can you provide more info on what this error means and how to prevent it or mitigate it? 

Thanks!

**Comment by sayali-MSFT** [comment]
@picorel - It appears this is an issue on the Teams client's site which can be avoided by re-install.
renewalTimeout error means Token has expired and cannot renew it, so needs to generate a new token.

**Comment by Zenyatta11** [comment]
Hi, I am working with @picorel on this issue.

Yes, we can confirm that end users face this issue as well. Not when idle but when put to sleep and later woken up

**Comment by picorel** [comment]
Thanks @sayali-MSFT.

We have also seen the following errors: 

- Cannot start retry fetch of ADAL tokens, isPassive: false.
- Cannot start retry fetch of ADAL tokens without relogin. Rejecting token request.
- tpmError.

Can you provide us more info about them, and what should we do when they happen? 
We don’t know the steps to reproduce them, but we have seen them multiple times for multiple users.

**Comment by sayali-MSFT** [comment]
@picorel -We are not able to repro the issue, as you mention above, we are trying to repro like Teams Browser Client by leaving the app in the background or sleeping the computer for some time.
We are checking it internally and let you know once we get any updates.

**Comment by sayali-MSFT** [comment]
@picorel - We got the update from engineering team, "This error typically indicates that the Teams Client is offline (or thinks that it is); in such cases our auth stack doesn’t even attempt to fetch an auth token "

 When you received one of these errors, please check your network connection and then reload the app or all of Teams.

> Thanks @sayali-MSFT.
> 
> We have also seen the following errors:
> 
> * Cannot start retry fetch of ADAL tokens, isPassive: false.
> * Cannot start retry fetch of ADAL tokens without relogin. Rejecting token request.
> * tpmError.
> 
> Can you provide us more info about them, and what should we do when they happen? We don’t know the steps to reproduce them, but we have seen them multiple times for multiple users.

**Comment by picorel** [comment]
Assuming it’s an intermittent network issue, can we call `getAuthToken` again to retry the operation? Will Teams try to get the token?
If not, could it help if we reload our app programmatically?
I’m wondering what can we do to avoid dead ends and try to provide a good user experience.
Thanks!

**Comment by sayali-MSFT** [comment]
@picorel -Yes, we can call `getAuthToken` again to retry the operation. `getAuthToken()` is a method in Microsoft Teams JavaScript library. It requests an Azure AD access token to be issued on behalf of app. The token is acquired from the cache, if it is not expired. If it's expired, a request is sent to Azure AD to obtain a new access token.
Always call `getAuthToken()` only when you need an access token.

**Comment by picorel** [comment]
Hi @sayali-MSFT, 
`GetAuthToken` is still failing multiple times for multiple users (mainly with `Cannot start retry fetch of ADAL tokens, isPassive: false`).
There was a spike of errors on January 4, where `getAuthToken` failed +7800 times in our app.
We added some retry logic. The changes will be deployed soon in all our environments and we'll verify if it helps to reduce the amount of errors. 
I don’t think it will prevent all of them, considering that for some users it fails multiple times per day.

**Comment by sayali-MSFT** [comment]
@picorel - We will check it internally and get back to you, once we get any update.

**Comment by sayali-MSFT** [comment]
@picorel -Got the reply from engineering team, "This error is returned by our auth stack whenever Teams believes the user to be offline. If Teams is offline, we cannot refresh the auth token so we short circuit an return this error to the app. App developers should retry the token fetch and if that still fails, display a friendly error to the customer indicating that they appear to be offline and should check your Internet connection."

**Comment by picorel** [comment]
Thanks, @sayali-MSFT. 
Is there any situation where Teams could incorrectly believe that the user is offline? E.g., if the app is in the background, if the connection is unstable, etc.?
We retry getAuthToken up to 5 times, and we can see that for some users it sometimes fails the 5 times. However, we are able to track the errors after each failure, so the user must have some connectivity.  
Thank you!

**Comment by sayali-MSFT** [comment]
@picorel -Could you please provide a Fiddler trace by any chance in failure case?

**Comment by picorel** [comment]
> @picorel -Could you please provide a Fiddler trace by any chance in failure case? If your internet connection is unstable in that case, it teams believe that user is offline and if you are working for some time and away for few hours that time also teams believe that user is offline.

Hi @sayali-MSFT, 
Not really. We don’t know how to reproduce the errors. We just happen to see them in our logs for some of our customers, intermittently.

**Comment by sayali-MSFT** [comment]
@picorel - We are not able to investigation further due to unavailability of network traces and repro steps.


Could you please monitor this error and try to provide [network trace ](https://learn.microsoft.com/en-us/azure/azure-web-pubsub/howto-troubleshoot-network-trace)when it reappears.

**Comment by Wajeed-msft** [comment]
@picorel - would it be possible to add more logs to get exact repro? Also, did you see reduction in errors once you added retry mechanism?

**Comment by ChetanSharma-msft** [comment]
Hello @picorel - Once you face this issue again, please share the error logs for further investigation.

We are closing this issue for now, please feel free to reopen it.
