### ISSUE TITLE
Teams SDK 2.5.0 uograde in .net solution

### ISSUE THREAD

**Issue by LALITAMITTAL18** [OfficeDev/microsoft-teams-library-js#1476]
I previously created my solution using Teams Toolkit in Visual Studio. The code is based on Blazor application. As New Teams SDK realesed I am tring to change TeamsJsBlazorInterop.js file as per new SDK. However I am stuck in getcontext. Get context works on edge but not in chrome. Always the context is null. Below is the code I am having:

TeamsJsBlazorInteroj.js:

`
export function getContextAsync() {
    return new Promise((resolve, reject) => {
        try {
            microsoftTeams.app.getContext().then((context) => {
                resolve(context);
            });
        } catch (e) {
            reject(e);
        }
    });
}`

TeamsContext.cs

`
using Exact.Office365.TeamsApp.Interop.TeamsSDK;
using System.ComponentModel;
using System.Text.Json.Serialization;

namespace Exact.Office365.TeamsApp.Interop.TeamsSDK
{
	public class TeamsContext
	{
		public App app { get; set; }
		public Page page { get; set; }
		public User user { get; set; }
		public Channel channel { get; set; }
		public Team team { get; set; }
		public Sharepointsite sharePointSite { get; set; }
	}

	public class App
	{
		public string locale { get; set; }
		public string sessionId { get; set; }
		public string theme { get; set; }
		public int iconPositionVertical { get; set; }
		public string parentMessageId { get; set; }
		public long userClickTime { get; set; }
		public string userFileOpenPreference { get; set; }
		public Host host { get; set; }
		public string appLaunchId { get; set; }
	}

	public class Host
	{
		public string name { get; set; }
		public string clientType { get; set; }
		public string sessionId { get; set; }
		public string ringId { get; set; }
	}

	public class Page
	{
		public string id { get; set; }
		public string frameContext { get; set; }
		public string subPageId { get; set; }
		public bool isFullScreen { get; set; }
		public bool isMultiWindow { get; set; }
		public object sourceOrigin { get; set; }
	}

	public class User
	{
		public string id { get; set; }
		public string licenseType { get; set; }
		public string loginHint { get; set; }
		public string userPrincipalName { get; set; }
		public Tenant tenant { get; set; }
	}

	public class Tenant
	{
		public string id { get; set; }
		public string teamsSku { get; set; }
	}

	public class Channel
	{
		public string id { get; set; }
		public string displayName { get; set; }
		public string relativeUrl { get; set; }
		public string membershipType { get; set; }
		public string defaultOneNoteSectionId { get; set; }
	}
public class Team
{
	public string internalId { get; set; }
	public string displayName { get; set; }
	public int type { get; set; }
	public string groupId { get; set; }
	public string templateId { get; set; }
	public bool isArchived { get; set; }
	public int userRole { get; set; }
}

public class Sharepointsite
{
	public string teamSiteUrl { get; set; }
	public string teamSiteDomain { get; set; }
	public string teamSitePath { get; set; }
	public string teamSiteId { get; set; }
}

}`

**Comment by nwojod-MSFT** [comment]
Hi @LALITAMITTAL18, thanks for raising this issue. Based on your code snippet, we recommend to initialize first, then await for it to complete before calling getContext. Try wrapping the getContext using the sample code below. 

microsoftTeams.app.initialize().then(() => {
  function getContextAsync() { return new Promise((resolve, reject) => { 
    try { 
      microsoftTeams.app.getContext().then((context) => { 
        resolve(context); }); 
    } 
    catch (e) { reject(e); } }); }
});

It is interesting that it works in edge but not chrome. Kindly verify and let us know. Thanks.

**Comment by LALITAMITTAL18** [comment]
The issue is resolved. Edge was not having issue in typecast errors but Chrome did not worked.
