### ISSUE TITLE
getTabInstances doesnt resolve in Personal chat

### ISSUE THREAD

**Issue by LALITAMITTAL18** [OfficeDev/microsoft-teams-library-js#1487]
I am trying to get Tab information for a personal chat but getTabInstances never resolves. I saw the same behaviour on Mobile(iphone) as well

This is how my code looks like:

   return new Promise((resolve, reject) => {
        try {
            microsoftTeams.pages.tabs.getTabInstances().then((tabInfo) => {
                resolve(tabInfo);
            }, tabInstanceParameters);
        } catch (e) {
            reject(e);
        }
    });

**Comment by Prasad-MSFT** [comment]
@LALITAMITTAL18 - This JS API is not implemented on Mobile. 
Please refer [this ](https://github.com/OfficeDev/microsoft-teams-library-js/issues/544)thread for reference:
Also refer: https://github.com/OfficeDev/microsoft-teams-library-js/issues/154

**Comment by LALITAMITTAL18** [comment]
ok checked. But this one also not get resolve on personal chat

**Comment by nwojod-MSFT** [comment]
@LALITAMITTAL18, are you also experiencing this issue on web? This API is currently not implemented on Mobile.

**Comment by Prasad-MSFT** [comment]
Okay. We are checking this and will get back to you within few hours with our findings.

**Comment by Meghana-MSFT** [comment]
@LALITAMITTAL18 - Could you please confirm if you tried by passing NULL instead of TabInstances parameters, and was it giving the same issue?

**Comment by LALITAMITTAL18** [comment]
Hi Team, My apologies for delayed response. Yes I tried with Null, and it is still no teamstab results.

return new Promise((resolve, reject) => {
try {
microsoftTeams.pages.tabs.getTabInstances().then((tabInfo) => {
 if (tabInstances.teamTabs != null && tabInstances.teamTabs.length > 0) {
resolve(tabInfo);
}
}, null);
} catch (e) {
reject(e);
}
});

![image](https://user-images.githubusercontent.com/51710902/211625224-b81e2bdc-7b5f-4e0a-a8b4-2a1d867f5a35.png)

**Comment by Prasad-MSFT** [comment]
We also tried and same is happening at our end as well. We are checking this with engineering team. We will inform you once we have any update from engineering team. Thanks!

**Comment by Prasad-MSFT** [comment]
@LALITAMITTAL18 - We got update from engineering team that "The **getTabInstances** API only enumerates configured tabs of the app in the user's teams & channels (and only for the ones that the Teams Client has synced/cached locally). This API will get deprecated, and it is advised not to use it. Its performance is very poor, and we do not have the ability to enumerate all tab instances of an app across all chats/channels."

**Comment by LALITAMITTAL18** [comment]
Which one is the new api to use instead of this one?
