### ISSUE TITLE
OpenPurchaseExperience: what to pass as 'term'?

### ISSUE THREAD

**Issue by matthiasdilger** [OfficeDev/microsoft-teams-library-js#1491]
Using the following code
```
<script
  src="https://res.cdn.office.net/teams-js/2.5.0/js/MicrosoftTeams.min.js"
  integrity="sha384-0lOzlvRkoNWAcLkbUTuao6TaDa7zI7v+q2PUAm3lrMxUp43PFwf2kaQu7FYT9fjS"
  crossorigin="anonymous"
></script>
<script>
if(microsoftTeams.monetization.isSupported()) {
    microsoftTeams.monetization.openPurchaseExperience({planId: "XXX", term: "YYY"});
 }
</script>
```
I open the "choose a subscription plan" popup. The ``planId`` is clear and seems to work, how can I pre-select the billing term? I have a monthly and a yearly plan and tried to select the monthly plan by passing "P1M" as ``term`` but that does not seem to have any effect.

**Comment by Meghana-MSFT** [comment]
We are looking into this, we will get back to you with an update in the next 48 hours.

**Comment by JulianDeng** [comment]
Thank you for contacting us!

Unfortunately the pre-select plan feature is not supported yet. The optional parameter "termInfo" is just a placeholder and hidden from public API. We may continue developing to support it in the future.

Also, code below is not in correct syntax. At this moment, parameters only accepts a call-back function.
`microsoftTeams.monetization.openPurchaseExperience({planId: "XXX", term: "YYY"});`

Please view this help doc for more details.
https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow?tabs=jsonV11#purchase-experience-api

**Comment by matthiasdilger** [comment]
@JulianDeng Thanks for letting me know. As you can see from my code sample I am using v2 of the library, I believe the syntax is correct.
