### ISSUE TITLE
Can't click on share button in dialog when executing method `sharing.shareWebContent()`

### ISSUE THREAD

**Issue by quentin-pla** [OfficeDev/microsoft-teams-library-js#1495]
When I want to share content with a long url or message without spaces, I can't see button to share :
![share dialog bug](https://user-images.githubusercontent.com/25415408/209208710-a2f5bd2a-87c9-45fe-82de-9d3bec0ce24f.gif)

I'm using Teams web version.

**Comment by sayali-MSFT** [comment]
@quentin-pla - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by sayali-MSFT** [comment]
@quentin-pla - We are not able to repro the scenario. It's working fine from our end.
Could you please check it once?
```
     shareTeamsHandler = () => {
        microsoftTeams.sharing.shareWebContent({
        content: [
          {
            type: 'URL',
            url: `${window.location.origin}?linkunfurling`,
            preview: true
          }
        ]
      });
    }
```
 Microsoft Teams Version 1.5.00.35276 (64-bit)
 
 

https://user-images.githubusercontent.com/93527375/209934250-89a9d880-4519-43d0-a865-b539d906855f.mp4

**Comment by Wajeed-msft** [comment]
Please feel free to re-open if you are still facing this issue.
