### ISSUE TITLE
mediaDevices.getUserMedia({audio: true}) returns "DOMException: Permission denied".

### ISSUE THREAD

**Issue by MuhammadAli-208** [OfficeDev/microsoft-teams-library-js#1499]
i can enable permission via settings page. but i want it to enable myself via code.

**Comment by Nivedipa-MSFT** [comment]
@MuhammadAli-208 - Thanks for reporting your issue. We are checking this internally. We will update you soon.

**Comment by Nivedipa-MSFT** [comment]
@MuhammadAli-208 - We got a confirmation from engineering team saying that It's not advisable for software to enable permission by code. This will take away the control from the user as camera, media permissions can be provided without user's permission then. We should typically not advise this flow. 
Could you please confirm why do you want to build such a support?

**Comment by Nivedipa-MSFT** [comment]
@MuhammadAli-208 - Could you please confirm why do you want to build such a support?
