### ISSUE TITLE
deep link to tab and task modules during meeting

### ISSUE THREAD

**Issue by ftliou** [OfficeDev/microsoft-teams-library-js#1500]
I have a two-part question related to tab/task module deep links **DURING meeting**.
Now since I am already inside meeting, there are two Teams windows, one is **meeting window**, the other is **main Teams window**.

My observations:
1. **deep link to task module** 
If I type in following URL addresses from browser:
``https://teams.microsoft.com/l/task/<appId>?url=https://localhost:53000/index.html#/<entityId>&title=test``
the task module will be shown in the **main Teams window** (popup with light background).
If I type the same url from chat side panel inside meeting window and click on that url, the task module will be shown in **meeting window** (popup with dark background).

2. **deep link to tab**
If I already have tab installed to the meeting/chat, and then type in following URL addresses from browser:
``https://teams.microsoft.com/l/entity/<appId>/<entityId>?context={"chatId": "<chatIdForMeeting>.v2","contextType":"chat"}``
the tab will be opened automatically from the meeting in **main Teams window**.
But I cannot get the deep link to open the tab in the **meeting window** at all.

Please correct me if my above observations are wrong, also, here are my 2 additional questions: 
1. Task module - Is it possible if user clicks on deep link from external sources, Teams can directly open the task module in **meeting window** (ie NOT main Teams window)?
2. Open Tab - similar to above, Is it possible at all if user clicks on deep link from external sources, Teams can directly open the tab in **meeting window** (NOT main Teams window)?

**Comment by sayali-MSFT** [comment]
@ftliou - Thanks for reporting your issue.
We will check this at our end and will get back to you

**Comment by sayali-MSFT** [comment]
@ftliou - We are also facing the same behavior as you mentioned for task module and tab deep link.
We are checking with the internal team as it is ByDefault behaviour/bug or is there any workaround for this.

**Comment by sayali-MSFT** [comment]
@ftliou - For Tab behaviour is as per design, engineering team changed the behaviour of deep link to tab for chat/meetings as you mention above, i.e.
if a meeting is on going and a deep link to tab which is part of the same meeting is clicked from somewhere, it'll route the user to meeting window not main teams window. ETA for the above scenario is mid Feb.
 
For Task module behaviour is ByDesign. Currently there is no plan to change the behaviour for Task module.

**Comment by ftliou** [comment]
@sayali-MSFT thanks for your confirmation. Looking forward to the tab deeplink in meeting window :)

**Comment by sayali-MSFT** [comment]
@ftliou - Could you please share your valuable feedback via [Microsoft Teams Developer Feedback](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u) link.
