### ISSUE TITLE
Mobile iOS: Invoking an external teams chat does not work for some contacts (returns "Invalid URL")

### ISSUE THREAD

**Issue by StefanH114** [OfficeDev/microsoft-teams-library-js#1502]
For some contacts - on the iOS  - invoking a teams chat via DeepLink to external contacts does not work while it works on the desktop version (macOS Teams client in my case). 
Example:
` app.openLink(
                      `https://teams.microsoft.com/l/chat/0/0?users=${imEmailArray[0]},`
                    );`

In the iOS we get an Invalid Url as return.
![image](https://user-images.githubusercontent.com/88711548/210553912-68de5835-a24b-441b-9740-ccdb28a18750.png)

**Comment by Prasad-MSFT** [comment]
@StefanH114 - In iOS while invoking chat with external user using `app.openLink();` it throws Invalid Url. Right?

**Comment by StefanH114** [comment]
> @StefanH114 - In iOS while invoking chat with external user using `app.openLink();` it throws Invalid Url. Right?

Correct. 
It works fine on any other platform.

**Comment by Prasad-MSFT** [comment]
Hi @StefanH114 - We tried to repro the scenario by invoking chat with external user using below deeplink
`microsoftTeams.app.openLink("https://teams.microsoft.com/l/chat/0/0?users=xxxxxx@xxxx.com");` and both in Android and iOS devices it is navigating to respective chat thread.
Attaching video for reference. The MS Teams version is also highlighted in the attachment.

**Comment by ChetanSharma-msft** [comment]
Hello @StefanH114 - Please let us know if you have any further query around this issue?
