### ISSUE TITLE
dialog.submit not working, keeps the dialog window opened

### ISSUE THREAD

**Issue by marekcis** [OfficeDev/microsoft-teams-library-js#1503]
Hi,
I have issues closing the dialog window via code.
Here is sample code I use to open and close dialog. 

```
open(): void {
  const urlDialog = {
      url: 'https://my-nice-page.com',
      size: {
        width: 640,
        height: 480
      },
      title: 'Opened popup title',
      fallbackUrl: 'https://fallback.com'
    }

  // now open the dialog  
  dialog.open(urlDialog, (sdkResponse) => console.log('sdk response on dialog close: ', sdkResponse));
},

submit(): void {
  // in appIds array I put appId and botId to be extra sure.
  dialog.submit("dialog close", ["xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",]);
},
```

The `submit` method is not closing the dialog window. 
I am using Teams JS version 2.6.1

Tried submit with and without optional parameters as discussed in couple of threads in StackOverflow or in this Issue page.

Thanks for any kind of help.

**Comment by marekcis** [comment]
Also tried to wrap `dialog.submit` to try-catch block, but there is no exception thrown. The call seems just have no effect on window.

Version of Teams client: 1.5.00.34862. 
Updated on 04/01/2023

**Comment by lakhveerk** [comment]
Hi Marek, 

Thank you for bringing this to our attention. Where are you seeing this behavior? on desktop/web or on mobile?

**Comment by lakhveerk** [comment]
I am trying to reproduce the issue. Do you mind providing me more information about how you are calling the submit function? dialog.submit can only be called from inside of a dialog.

**Comment by marekcis** [comment]
@lakhveerk thank you very much! This solved my issue. 
This task can be closed now, but please add to documentation (I haven't found it nowhere) that this call needs to be done from dialog itself. It kind of makes sense, but on the other side, there are couple messaging methods that points toward using to communicate between dialog and hosting app. By that I assumed that opening and closing dialog should be done from hosting app.
Thank you very very much for help :)

**Comment by lakhveerk** [comment]
I am glad that I was able to help.  
Thank you for the feedback. I will update the documentation.
