### ISSUE TITLE
Need an event while switching tabs in Microsoft Teams on Mobile platform

### ISSUE THREAD

**Issue by Vallarasu6** [OfficeDev/microsoft-teams-library-js#1507]
I have multiple tabs in Microsoft Teams on Mobile Platform. Need an event while switching the tab , need to check before showing the tab. Simply, when I click the tab , i need an event or something.

**Comment by sayali-MSFT** [comment]
@Vallarasu6 - Could you please elaborate more on your requirement, so that we can try it from our end.

**Comment by ChetanSharma-msft** [comment]
Hello @Vallarasu6 - Please let us know if you have any further query around this issue?

**Comment by Vallarasu6** [comment]
Thanks For your suggestion. What I need is, For example, I have Three Tabs , I do some changes in tab 1, it should be reflected in Tab 2 and Tab 3 automatically before or after switching tabs. Do you have any options to do this?

**Comment by ChetanSharma-msft** [comment]
Hello @Vallarasu6 - We will investigate your query and let you know the updates.

**Comment by sayali-MSFT** [comment]
@Vallarasu6 - Are you rendering same page in tab2 and tab3 or all three are different?

**Comment by Vallarasu6** [comment]
All three are different, but some changes I do in tab 1 should reflect in tab 2 and tab 3. In other words, based on the changes in tab 1, data should be showed in tab 2 and tab 3.

**Comment by sayali-MSFT** [comment]
@Vallarasu6 - Currently, this functionality is not possible.
Could you please help by suggesting this feature on - [Microsoft Teams · Community](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472)

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
