### ISSUE TITLE
Custom activity feed notifications sent from daemon(nodejs app), not getting the data assigned to subEntityId in teams mobile client using using @microsoft/teams-js sdk version ^2.4.1

### ISSUE THREAD

**Issue by Anik-Roy** [OfficeDev/microsoft-teams-library-js#1518]
We're using `activityFeedNotification` graph api to send push notification to the users of our teams tab app from backend using nodejs. The notification is sending successfully in both teams desktop and mobile client but we're not getting the `data` assigned to `subEntityId` in mobile client(In desktop client and browser we're getting it).

We are encoding the `data(object) `and assigning it to the `subEntityId` in teams context in our nodejs application as per the documentation. Then in teams client, we get that data from teams context using `microsoft teams javascript sdk` and redirect user to the respective page in our application based on whatever data we get in subEntityId

In desktop, `deeplinking` is working perfectly but in android client, we're not getting any data in subEntityId. It is just opening the homepage of our tab app but I need to redirect user to specific page based whatever data is assigned to `subEntityId`.

Below I've provided how we're encoding the data and assigning it to subEntityId.

Server Side Code:

```
const context = encodeURIComponent(
      JSON.stringify({
        "subEntityId": {
         "type": "PROGRAM_PROFILE",
         "program_id": "12345",
          uid: uuidv4(),
        }
      })
    );

const body = {
  topic: {
    source: 'text',
    value: notificationTopic,
    webUrl: `https://teams.microsoft.com/l/entity/${TEAMS_APP_ID}/index?context=${context}`,
  },
  activityType: 'commonNotification',
  previewText: {
    content: notificationSubtitle,
  },
  templateParameters: [
    {
      name: 'title',
      value: notificationTitle,
    },
  ],
};

const url = `https://graph.microsoft.com/v1.0/users/${userId}/teamwork/sendActivityNotification`;

await axios.post(url, body));
```

Client Side Code:

```
const context = await app.getContext();
console.log(context?.page?.subPageId); // getting undefined
```
**Is this a bug? Any kind of help is appreciated!**

**Comment by Prasad-MSFT** [comment]
We are checking this issue. We will get back to you shortly.

**Comment by Anik-Roy** [comment]
In ios also it is not working.

**Comment by Prasad-MSFT** [comment]
@Anik-Roy - We are able to repro this issue. In desktop/web client, deeplinking is working fine. However, in android and iOS,  we're not getting any data in subEntityId. It is just opening the homepage of our tab app but not redirecting to specific page based whatever data is assigned to subEntityId.

There is a bug raised for similar issue. We are following up with engineering team regarding the fix. We will inform you once we get any update. Thanks!

**Comment by Prasad-MSFT** [comment]
We are checking the status of the bug with engineering team. We will inform you once we have any update.

**Comment by Prasad-MSFT** [comment]
Hi Everyone, the issue seems to be fixed now. We tested using `@microsoft/teams-js version 2.8.0` in `iOS 16.7`
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/62237649/2520c035-dc00-4720-88df-88d637bbee36)

Microsoft Teams Version:
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/62237649/7e44c37b-fcaa-4b1f-829d-52cf6f9586a2)
