### ISSUE TITLE
shareAppContentToStage not working with MS Teams for iPad app v4.22.1

### ISSUE THREAD

**Issue by xerosanyam** [OfficeDev/microsoft-teams-library-js#1535]
Hi Team,

`microsoftTeams.meeting.shareAppContentToStage` was working fine with MS Teams app for iPad app v4.20 but when we updated the app to latest version (v4.22.1), the API stopped working all of a sudden.

It doesn't open meeting stage now nor it returns any error. 

It seems to be working fine on MS Teams for desktop v1.5.0.

we are on `@microsoft/teams-js: v1.11.1`

**Comment by sayali-MSFT** [comment]
@xerosanyam - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by xerosanyam** [comment]
Updated our package to latest version `v2.7.1`, still facing the issue.

**Comment by ChetanSharma-msft** [comment]
Hello @xerosanyam - We are checking your issue and let you know the updates.

**Comment by xerosanyam** [comment]
Team, this is a regression, and must be dealt accordingly(with a higher priority).

Even Microsoft's own app isn't working, try clicking on "Share Full Screen"
![image](https://user-images.githubusercontent.com/3167278/213262582-2644fc3c-1166-415f-833b-060eb68c0020.png)

**Comment by SupritiBhan** [comment]
Hey @xerosanyam Thanks for notifying the issue. I am from the Mobile Platform team. Can you provide more details as to the issue. 
- Is this happening only in Ipad post the Upgrade? We just checked in AND mobile device and their it works
- Is there an account where we can check or get some logs
Thx!

**Comment by xerosanyam** [comment]
Hey @SupritiBhan! Thanks for replying.
- I just checked, it is not working on both iPad and iPhone (v4.22.1, v4.23.1)
It works on Desktop(1.5.0), Android(1414/1.0.0.../1218) and WebApp.

|MS Teams app for iPad version| status|
|--|--|
|v4.19.0 |working|
|v4.20.0 |working|
|v4.22.1| Not working|
|v4.23.1  (latest)| Not working|


- You can try any valid Teams account. Try adding Microsoft's own app "Games for work" then try clicking "Share Full Screen" on iPad/iPhone. It will never open the meeting stage.

Could you please escalate this? This is "P0 - High Severity bug" for us and affecting multiple users.
In the meantime if you could help us in downgrading the version to v4.20.0, that would be super helpful too.

**Comment by SupritiBhan** [comment]
Thanks @xerosanyam we are looking into it. Can you share more details to help move this into P0:

- Partner Name and MAU impact due to this API not working. 
- Some details on the scenario where the API is used by you

**Comment by xerosanyam** [comment]
@SupritiBhan 
- Partner Name - Tact.ai Technologies, Inc.
- Some details on the scenario where the API is used by you:
We have a button, similar to "Share Full Screen" button denoted above, on clicking this "custom sharing button" the user can open the meeting stage.

1. We wanted control over who is able present content i.e only logged-in user should be able to present. Therefore only logged in people are able to see the custom sharing button.
2. We use this API to load a custom `contentURL` in the meeting stage. We append user identification in the url which helps us easily identify "who" is presenting.

3. The Native Button to open meeting stage is not clearly visible on some devices making it difficult to find.
![image](https://user-images.githubusercontent.com/3167278/213405110-c9167712-ac4e-4e5f-a154-2a378d39a812.png)

4. Lastly, because the Native Button to open meeting stage wasn’t available on iPad few months back - therefore we had to build our solution using this API.

**Comment by SupritiBhan** [comment]
Hi @xerosanyam let me start an email thread with you and the engineers on my team to take this forward. We did check Internally on Ipad and for us it is working

**Comment by xerosanyam** [comment]
@SupritiBhan that would be helpful. looking forward to your email.

**Comment by xerosanyam** [comment]
Hi @SupritiBhan, when are you planning to start the email thread? (we were waiting...)
Kindly include - `mudit.saxena@tact.ai` & `venkat.natarajan@tact.ai`.


> We did check Internally on iPad and for us it is working

That's very surprising - this check was on which version of Teams?

**Comment by xerosanyam** [comment]
> Hi @SupritiBhan, when are you planning to start the email thread? (we were waiting...) Kindly include - `mudit.saxena@tact.ai` & `venkat.natarajan@tact.ai`.
> 
> > We did check Internally on iPad and for us it is working
> 
> That's very surprising - this check was on which version of Teams?

received the email. please ignore the message.

**Comment by SupritiBhan** [comment]
Hey @xerosanyam I have already started the email thread and added the folks you mentioned. Did you not receive it?

**Comment by ChetanSharma-msft** [comment]
Hello @xerosanyam - Could you please confirm whether your issue has resolved or need any further assistance?

**Comment by ChetanSharma-msft** [comment]
Hello @xerosanyam - As per @SupritiBhan - your issue has been resolved.
We are closing this issue for now, please feel free to reopen it, if required.
