### ISSUE TITLE
[Teams Mobile]: Several issues on iOS and Android

### ISSUE THREAD

**Issue by garrytrinder** [OfficeDev/microsoft-teams-library-js#1548]
Several issues on iOS and Android mobile apps.

- [ ] #1580
- [ ] #1581
- [ ] #1582 
- [ ] #1583

**Comment by ChetanSharma-msft** [comment]
Hello @garrytrinder - Thanks for sharing this issue.
We will further investigate and let you know the updates.

**Comment by garrytrinder** [comment]
Sure @ChetanSharma-msft.

I will create separate issues for each and use this issue as a tracking issue to keep things together.

**Comment by garrytrinder** [comment]
@ChetanSharma-msft apologies for the delay on this, I've created separate issues for the problems I have encountered.

**Comment by Prasad-MSFT** [comment]
@garrytrinder - Above issues are being tracked as Issue No: [1580](https://github.com/OfficeDev/microsoft-teams-library-js/issues/1580), [1581](https://github.com/OfficeDev/microsoft-teams-library-js/issues/1581), [1582](https://github.com/OfficeDev/microsoft-teams-library-js/issues/1582) & [1583](https://github.com/OfficeDev/microsoft-teams-library-js/issues/1583) respectively. 

Closing this thread. Please track respective threads for further updates.
