### ISSUE TITLE
OAuth cookie/token do not work into iOS

### ISSUE THREAD

**Issue by Tower450** [OfficeDev/microsoft-teams-library-js#1553]
I am facing an issue on iOS 16, we are using an OAuth token coming back from an HTTP response `set-cookie: <cookie/token>` to authenticate our users, it is working on android/desktop/web but on iOS the login is just failing. Is it possible that WebKit WebView cookies are not well manage by the library?

We are also respecting the cookie settings recommanded by the following documentation.

https://learn.microsoft.com/en-us/microsoftteams/platform/resources/samesite-cookie-update

**Comment by Prasad-MSFT** [comment]
@Tower450 - Could you please provide more details on your issue or the sample you are referring to? Any repro steps would be really helpful. Thanks!

**Comment by Prasad-MSFT** [comment]
@Tower450 - Could you please provide more details on your issue or the sample you are referring to? Any repro steps would be really helpful. Thanks!
