### ISSUE TITLE
Determinating if in Teams

### ISSUE THREAD

**Issue by OfirArviv** [OfficeDev/microsoft-teams-library-js#156]
Hi,

Is it possible to determinate if we are currently in Teams context?
We mainly want to have a easy way to debug our app outside of Teams and we need to recognize if we are not in Teams in order to replace the Team Api calls with some mock

**Comment by Wajeed-msft** [comment]
You can try [getting context by using the Microsoft Teams JavaScript library](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/tabs/tabs-context#getting-context-by-using-the-microsoft-teams-javascript-library).

`microsoftTeams.getContext(function(context) { /* ... */ })`

You get Microsoft Teams context only when your webpage is loading inside Teams tab.

**Comment by ydogandjiev** [comment]
We've considered adding an SDK API that can determine if you are running in Teams (e.g. something like microsoftTeams.isInTeams() or something long those lines); however, it's not technically feasible to determine that we are running inside of Teams across all browsers and clients we support. Most browsers do not let you check the origin of your parent iframe which means it's not possible for you to reliably determine if you're being hosted by Teams.

The best way to handle this is by adding an explicit QSP to your tab configuration and content pages (e.g. &inTeams=true) that you set in the app manifest (for configurableTabs > configurationUrl or staticTabs > url fields) or in code when dynamically constructing the URL of your configurable tab instances.

**Comment by OfirArviv** [comment]
Thanks for your replies.

What about using the browser version or user-agent header?
I noticed the Team containers set them to:

> Browser Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) **Teams/1.1.00.31152** Chrome/61.0.3163.100 Electron/2.0.10 Safari/537.36
User-agent header: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) **Teams/1.1.00.31152** Chrome/61.0.3163.100 Electron/2.0.10 Safari/537.3

Is it something one can rely on?

**Comment by billbliss** [comment]
When you are running in the browser or a mobile client (tabs will work on mobile next year) that won't work. @Wajeed-msft's suggestion is not a _secure_ way of determining whether you are running inside Teams (you could be running inside a page pretending to be Teams) but it would suffice for automation purposes.
