### ISSUE TITLE
`dialog.submit()` not working when optional parameters are provided

### ISSUE THREAD

**Issue by marekcis** [OfficeDev/microsoft-teams-library-js#1562]
Hi,
I've discovered (the hard way), that `dialog.submit()` method is not working when optional parameters are provided.

Failed use-case:
1. In-meeting notification from bot opens pop-up window with external URL.
2. Once the Teams SDK calls `dialog.submit({result: 'ok', vote: 'yes'}, [manifest-app-id, manifest-bot-id]);` the pop-up window closes external URL and shows error message saying: _Unable to reach app. Please try again._

![wont-close](https://user-images.githubusercontent.com/91459425/215497752-aec50d08-c16b-4307-b28e-a66e9aa103ed.png)

I am referring to [this submit method specifically](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/dialog?view=msteams-client-js-latest#@microsoft-teams-js-dialog-submit). I understand, that the method is still in Beta, but as from the version 2.0.0 the `task.submitTask()` predecessor is deprecated already. You just have to make up your mind here, right? :)

Working use-case:
1. In-meeting notification from bot opens pop-up window with external URL.
2. Once the Teams SDK calls `dialog.submit();` with no optional parameters, the pop-up window closes itself as it should.

It took me couple of days to realise this, many trials and errors.. Since there is **so much documentation** of tasks and notifications that behave differently in various contexts (like tab/bot/private channel, etc.) and many of similar issues directed me to long running operations, I'd kindly ask you to fix the issue (maybe also provide better error message to begin with). 

Version of MS Teams SDK: 2.6.1

**Comment by Nivedipa-MSFT** [comment]
@marekcis - Thanks for reporting you issue. We will test this and update you soon.

**Comment by marekcis** [comment]
@Nivedipa-MSFT on Teams desktop app, mac os 13.2

**Comment by Nivedipa-MSFT** [comment]
@marekcis - Thanks for providing more details. Could you please share the console error. Meanwhile we are trying this out. We will update you soon.

**Comment by marekcis** [comment]
@Nivedipa-MSFT there is no such thing as console error, since the web app context is closed. The error message is part of Teams desktop app I suppose.

**Comment by aneeshdk** [comment]
@marekcis from what @Nivedipa-MSFT mentioned above it looks like the issue reproduces only in Mac. Are you able to repro the issue in both desktop and web ? If so, can you please try the scenario in web and see if there are any specific errors showing up on the console. We can have a debug session if you are available some time on Wednesday (2/8).

**Comment by marekcis** [comment]
@aneeshdk thanks for reply, tomorrow I will confirm the situation on windows / mac platform and desktop / browser clients respectively. 
I'd certainly like to have a debug session on Wednesday. I am in CET timezone.

**Comment by marekcis** [comment]
@aneeshdk I've tested the `dialog.submit()` with and without optional params.
The issue still persists, it occurs in Mac and Windows platform as well. When called `dialog.submit({result: 1})` call ends up with HTTP error 502 (see attached images).

![teams-1](https://user-images.githubusercontent.com/91459425/217252402-719d26b2-9bee-42bd-83d1-3fc055bdab03.png)
![teams-2](https://user-images.githubusercontent.com/91459425/217252415-c84f04d1-d379-490d-9cd7-fc1960042ee9.png)
![teams-3](https://user-images.githubusercontent.com/91459425/217252421-cef60c90-e8b3-4b02-8484-ca84b667b633.png)
![teams-4](https://user-images.githubusercontent.com/91459425/217252426-10677343-1786-4aa7-82bb-c086a1eed2b2.png)

Please suggest a debug session for tomorrow and send me invitation at: `teams@chren.co`

Looking forward to it!

**Comment by aneeshdk** [comment]
Looks like an error is happening on the Bot side that is when the BotError error code is normally used. It might as well be coming from the client SDK code as well. Will it be possible to put a try catch around the invoke handler and see what error you are getting? I sent out a meeting invite for 5:30pm your time. Hope that works!

**Comment by aneeshdk** [comment]
Is the email id "teams@chren.co" or "teams@chren.com"?

**Comment by marekcis** [comment]
Hi :)
You've got it right, I've just accepted the invitation for debug session.

See you soon!

Marek Chrenko
________________________________

**Comment by marekcis** [comment]
@aneeshdk do you manage to reproduce the issue on your demo project as discussed on call?

**Comment by Nivedipa-MSFT** [comment]
@marekcis - Could you please confirm is your issue resolved on call or are you still having queries?

**Comment by aneeshdk** [comment]
Hello @marekcis, sorry for the late response. We tried to repro the issue with some test app but couldn't succeed. Will you be able to share the part of the code where you are handling the dialog and doing the submit? If you can share that it would be a huge help. Want to cross check what we are missing. You can share it in our meeting chat if that works for you.

**Comment by Nivedipa-MSFT** [comment]
@marekcis - Could you please share the part of the code where you are handling the dialog and doing the submit? It will help us to investigate further.
