### ISSUE TITLE
Mobile support for microsoft teams context

### ISSUE THREAD

**Issue by cagdasdavulcu** [OfficeDev/microsoft-teams-library-js#157]
Hello everyone,

If i click on my tab app via. IOS Teams App, the tab will be shown as popup in Safari. Bacause of that i cannot read values from teams context settings. 

I think, that is not possible to create teams context using browser at the moment (for mobile Scenarios). 

<img width="322" alt="via browser" src="https://user-images.githubusercontent.com/1059729/48415334-618e1680-e74d-11e8-8e7b-60b793135bdf.png">
<img width="315" alt="teams hosted" src="https://user-images.githubusercontent.com/1059729/48415335-618e1680-e74d-11e8-9eef-58f7ac1c9bd5.png">

Can you please confirm that? Do you have any alternative approach for this?

Thanks and regards,
Cagdas

**Comment by billbliss** [comment]
Full tab support for mobile devices is being developed now. No dates to announce, but it's under active development.
