### ISSUE TITLE
An error has occurred  in  /users/{userId}/onlineMeetings/{meetingId}/attendeeReport

### ISSUE THREAD

**Issue by chandan86605** [OfficeDev/microsoft-teams-library-js#1579]
Hello, 
when i make the request get attendee report graph api(/users/{userId}/onlineMeetings/{meetingId}/attendeeReport)
i was getting an error "Meeting Id is corrupted." 

https://github.com/OfficeDev/microsoft-teams-library-js/issues/11696   this one solved my issue

but now i a facing new issue 
```
{
    "error": {
        "code": "BadRequest",
        "innerError": {
            "client-request-id": "9bff84c2-5f3a-4898-87cc-4de6a7049ec9",
            "date": "2023-02-10T06:37:07",
            "request-id": "557ce210-5604-4225-971b-66fd8bdf4d6c"
        },
        "message": "An error has occurred."
    }
}
```

is their any solutions
thank ypu

**Comment by Meghana-MSFT** [comment]
We also tried this at our end, we are getting bad request 400. We will check internally and get back to you.

![image](https://user-images.githubusercontent.com/81138249/218044810-1a3f38fd-470c-42c8-bd0c-50310d3ce397.png)

**Comment by chandan86605** [comment]
thank you for your response.
waiting for the solution

**Comment by Meghana-MSFT** [comment]
We have raised a bug for the same, we will keep you posted on the updates. Thank you.

**Comment by yuyaolian-msft** [comment]
Hello @chandan86605 , if you are trying to do a LIST operation, please use the following API:

GET /me/onlineMeetings/{meetingId}/attendanceReports

You can also see more details about this api here: https://learn.microsoft.com/en-us/graph/api/meetingattendancereport-list?view=graph-rest-1.0&tabs=http

Please let us know if fixing the endpoint help resolve the issue.

**Comment by Meghana-MSFT** [comment]
@chandan86605 - Did you get a chance to try out the above suggestion?

**Comment by chandan86605** [comment]
i got another solution thanks for your response

**Comment by Meghana-MSFT** [comment]
Thank you for confirming, we are closing this issue. Please feel free to reach out to us if you have any questions. Thanks!
