### ISSUE TITLE
Notification of File Downloads in Teams App

### ISSUE THREAD

**Issue by benpolinsky** [OfficeDev/microsoft-teams-library-js#158]
When downloading a file in the Teams Desktop App, inside of a 3rd party tab, there is no indication to the user that a download has started or completed. 

The file does indeed download, but the lack of any notification has confused our users. I've verified this behavior by installing the Egnyte app and noted the same behavior.

In browser, everything works as expected.

It'd be great if the same toast-like notification that appears when downloading a file from Teams' native file tab could be used in this case.

**Comment by billbliss** [comment]
Working on this now, should be out by early next year given our holiday code lockdown.
