### ISSUE TITLE
[Adaptive Cards]: Mobile - Card is not replaced cross device

### ISSUE THREAD

**Issue by garrytrinder** [OfficeDev/microsoft-teams-library-js#1580]
Related to https://github.com/garrytrinder/msteams-dalle-2-image-generator-bot/issues/40

Not sure if this is expected behaviour but seems odd and can result in out of sync conversations when submitting Adaptive Cards.

Repro steps

- Submit an Adaptive Card using `Action.Execute` action, passing a verb (ex: https://github.com/garrytrinder/msteams-dalle-2-image-generator-bot/blob/385d0962eb64ba5e472107734cbec91389f8a970/bot/src/cards/settings.card.json#L1-L79)
- Handle action and respond `InvokeResponse` with Adaptive Card attachment (ex: https://github.com/garrytrinder/msteams-dalle-2-image-generator-bot/blob/385d0962eb64ba5e472107734cbec91389f8a970/bot/src/actions/settings-save.ts#L8-L28)
- The card is replaced with the InvokeResponse card on the device where the original card was submitted, but other devices (mobiles) show the original card still, i.e. as if it was never submitted.

I would expect that when a card is updated on one device, that the other devices would reflect the update when used in a personal app context as there are no other users involved.

**Comment by Nivedipa-MSFT** [comment]
@garrytrinder - Thanks for reporting your issue. We will test this and update you soon.

**Comment by garrytrinder** [comment]
Thank you for the update @Nivedipa-MSFT

Whilst I understand that this is by design, it feels like a gap in functionality. 

This could lead to confusion when moving cross device for scenarios where cards are replaced as the current state is not reflected. Are there any plans to update this behaviour to work across multiple clients?

**Comment by Nivedipa-MSFT** [comment]
@garrytrinder - We are checking this with engineering team. We will let you know once we get any updates from them.

**Comment by Nivedipa-MSFT** [comment]
@garrytrinder - Could you please share your valuable feedback via [Microsoft Teams Developer Community Response Feedback](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u) link.
