### ISSUE TITLE
[Adaptive Cards]: iOS - Input.TextField default value not set

### ISSUE THREAD

**Issue by garrytrinder** [OfficeDev/microsoft-teams-library-js#1581]
Related to https://github.com/garrytrinder/msteams-dalle-2-image-generator-bot/issues/41

Repro steps

- Implement command to return an Adaptive Card (ex: https://github.com/garrytrinder/msteams-dalle-2-image-generator-bot/blob/385d0962eb64ba5e472107734cbec91389f8a970/bot/src/commands/settings.ts#L9-L26)
- Return Adaptive Card that uses an Input.Text field and a default value set using data binding (ex: https://github.com/garrytrinder/msteams-dalle-2-image-generator-bot/blob/385d0962eb64ba5e472107734cbec91389f8a970/bot/src/cards/settings.card.json#L1-L79)
- Field value is not set when rendered in iOS client

Works fine on web client and Android, but not iOS. I expect that when the value property is set it will be reflected in the mobile UI.

**Comment by Prasad-MSFT** [comment]
@garrytrinder - Thanks for providing details. We will check this at our end and will let you know the updates.

**Comment by Prasad-MSFT** [comment]
@garrytrinder - We tried to repro the issue with [this sample](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-request-approval/csharp) sending an adaptive card having default value for Input.TextField. However it rendered properly in iOS with default selected value.
![image](https://user-images.githubusercontent.com/62237649/218733033-6e971376-e885-4f0e-9757-cdd8aea6ee9d.png)

Card JSON Used:
```
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "body": [
    {
      "type": "TextBlock",
      "size": "Medium",
      "weight": "Bolder",
      "text": "Please fill the details for your request"
    },
    {
      "type": "Input.Text",
      "label": "Request title",
      "placeholder": "Request title",
      "id": "requestTitle",
      "value": "${createdBy}"
    },
    {
      "type": "Input.Text",
      "label": "Request description",
      "placeholder": "request description",
      "id": "requestDescription"
    },
    {
      "type": "TextBlock",
      "size": "Medium",
      "weight": "Bolder",
      "text": "Select manager"
    },
    {
      "type": "Input.ChoiceSet",
      "choices": [],
      "choices.data": {
        "type": "Data.Query",
        "dataset": "graph.microsoft.com/users?scope=currentContext"
      },
      "id": "AssignedTo",
      "isMultiSelect": false
    },
    {
      "type": "ActionSet",
      "actions": [
        {
          "type": "Action.Execute",
          "verb": "requestCard",
          "title": "Submit",
          "data": {
            "CreatedBy": "${createdBy}",
            "AssignedTo": "${assignedTo}",
            "UserMRI": "${userMRI}",
            "RequestTitle": "${requestTitle}",
            "RequestDescription": "${requestDescription}"
          }
        }
      ]
    }
  ],
  "type": "AdaptiveCard",
  "version": "1.2"
}
```

Tested in `iOS 16.3` 
![image](https://user-images.githubusercontent.com/62237649/218734051-12fd126b-2ad9-4ca8-ac9a-0791078d1029.png)

**Comment by Prasad-MSFT** [comment]
Thanks for informing. Glad to hear that your issue is resolved.

**Comment by garrytrinder** [comment]
Not quite @Prasad-MSFT in my scenario the `password` style is important as the user is entering an API key. Removing it will also remove the password masking from desktop and Android clients which is undesirable as it works fine on those clients.

This seems to be a bug in the way that the iOS client renders the value of the field when that password style is applied.

**Comment by Prasad-MSFT** [comment]
Okay @garrytrinder - We will test this scenario at our end and will get back to you shortly.

**Comment by Prasad-MSFT** [comment]
@garrytrinder - We are able to repro the issue, on using `"style": "Password"` on the text field, it's not showing default value in iOS. Tested in `iOS 16.3`
**Teams version:**
![image](https://user-images.githubusercontent.com/62237649/219359076-55b80e02-1219-4fc5-a17c-7f9de624a930.png)

![image](https://user-images.githubusercontent.com/62237649/219359208-bfaa8304-f117-49db-8619-4e385367093c.png)

We have raised a bug for the same and engineering team is looking into it. We will inform you once we get any further update. Thanks!

**Comment by ChetanSharma-msft** [comment]
I apologize for delay in response.
We are actively checking the status of bug fixes with engineering team and will update this thread, once it is fixed.

Thanks!!

**Comment by Prasad-MSFT** [comment]
This issue is fixed in internal ring. We will update in this thread when it is released publicly. Thanks!

**Comment by Prasad-MSFT** [comment]
@garrytrinder - We have checked at our end and this issue seems to be fixed now. Please do verify.
Tested in iOS. Microsoft Teams Version: 5.10.0
Build: 5.10.77.2023103002/0531
