### ISSUE TITLE
[Typing]: Android does not render indicator

### ISSUE THREAD

**Issue by garrytrinder** [OfficeDev/microsoft-teams-library-js#1583]
Related to https://github.com/garrytrinder/msteams-dalle-2-image-generator-bot/issues/37

https://user-images.githubusercontent.com/11563347/218134581-ecf3aac8-5dce-466f-b4bc-cfe8b4bb89bd.mp4

Repro steps

- Send an activity object with type of `ActivityTypes.Typing` (ex: https://github.com/garrytrinder/msteams-dalle-2-image-generator-bot/blob/385d0962eb64ba5e472107734cbec91389f8a970/bot/src/helpers/openai.ts#L36-L44)

Works on web and iOS, but not Android. I would expect the typing indicator to show on all devices.

**Comment by Meghana-MSFT** [comment]
We are looking into this, we will get back to you.

**Comment by Meghana-MSFT** [comment]
@garrytrinder - We have added below code block in a C# bot. We see below behavior.

1. If you send a message to bot from Android, then it sometimes shows typing indicator and sometimes it does not. We see this intermittently.
2. If you send a message a bot from web/desktop it doesn't show typing indicator in Android.


` await turnContext.SendActivityAsync(new Bot.Schema.Activity { Type = ActivityTypes.Typing}, cancellationToken);`

**Comment by garrytrinder** [comment]
Thanks for the update @Meghana-MSFT.

> If you send a message a bot from web/desktop it doesn't show typing indicator in Android.

So this is a bug?

**Comment by Meghana-MSFT** [comment]
@garrytrinder - We have raised a bug for the same, we will keep you posted on the updates. Thank you.

**Comment by ChetanSharma-msft** [comment]
I apologize for delay in response.
We are actively checking the status of bug fixes with engineering team and will update this thread accordingly.

Thanks!!

**Comment by Meghana-MSFT** [comment]
@garrytrinder - We have tested this in Android, and it is working now. We checked in Android OS13 and Teams version 1416/1.0.0.2023183501/1009. Could you please check and confirm.

**Comment by garrytrinder** [comment]
Thanks for the update, closing the issue.
