### ISSUE TITLE
How to show a native loading indicator in a pop up window?

### ISSUE THREAD

**Issue by catmanjan** [OfficeDev/microsoft-teams-library-js#1585]
We are using the "AdaptiveOpenUrlAction" to open a preview window in the Teams interface

The problem is that while the preview loads it is just a blank white screen

How do we show the native loading indicator here instead? We have tried the instructions here https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/microsoftteams.appinitialization?view=msteams-client-js-1.12.1&viewFallbackFrom=msteams-client-js-latest

but it does not seem to apply to popups

**Comment by Nivedipa-MSFT** [comment]
@catmanjan - Are you opening popup in Tabs? 
You can provide [native loading indicator](https://learn.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#showloadingindicator) for [tab content page](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?tabs=teamsjs-v2#integrate-your-code-with-teams), [configuration page](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page), [removal page](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page), and [task modules in tabs](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/task-modules-tabs).

Ref Doc: https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?tabs=teamsjs-v2#show-a-native-loading-indicator

**Comment by catmanjan** [comment]
> @catmanjan - Are you opening popup in Tabs? You can provide [native loading indicator](https://learn.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#showloadingindicator) for [tab content page](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?tabs=teamsjs-v2#integrate-your-code-with-teams), [configuration page](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page), [removal page](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page), and [task modules in tabs](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/task-modules-tabs).
> 
> Ref Doc: https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?tabs=teamsjs-v2#show-a-native-loading-indicator

No we are building a command bar integration bot, so we have no tab whatsoever

**Comment by Nivedipa-MSFT** [comment]
Currently you can provide a [native loading indicator](https://learn.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#showloadingindicator) for [tab content page](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?tabs=teamsjs-v2#integrate-your-code-with-teams), [configuration page](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page), [removal page](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page), and [task modules in tabs](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/task-modules-tabs).

Could you please suggest this feature here: [Microsoft Teams Community](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472).

**Comment by catmanjan** [comment]
> Currently you can provide a [native loading indicator](https://learn.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#showloadingindicator) for [tab content page](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/content-page?tabs=teamsjs-v2#integrate-your-code-with-teams), [configuration page](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page), [removal page](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page), and [task modules in tabs](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/task-modules-tabs).
> 
> Could you please suggest this feature here: [Microsoft Teams Community](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472).

Is there any way we could just get the native loading indicator graphic? That way we could render it in our pop up content

**Comment by Nivedipa-MSFT** [comment]
@catmanjan - Currently, there is no way to get the native loading indicator graphic. Thanks.

Please let us know if you have any further query here.

**Comment by catmanjan** [comment]
Okay thanks
