### ISSUE TITLE
[Extending Teams Personal Tab to Office.com] Unable to load requested application. No static tabs are configured error message

### ISSUE THREAD

**Issue by angelzhu923** [OfficeDev/microsoft-teams-library-js#1587]
Hi, ISV has updated Teams manifest to extend the Teams Personal Tab to Outlook and M365.com following this documentation:https://learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/overview

During testing, The Personal Tab works fine in Outlook.com and Teams, however is getting the "Unable to load requested application. No static tabs are configured." error on microsoft365.com/office.com.

Personal Tab loads fine on Outlook.com
<img width="1512" alt="Screenshot 2023-02-13 at 15 57 26 (002)" src="https://user-images.githubusercontent.com/102253761/218524923-dda2ffdf-79f6-4e97-ae22-e8b23d41bf96.png">

Personal Tab loads fine on Teams 
<img width="1512" alt="Screenshot 2023-02-13 at 15 57 21 (002)" src="https://user-images.githubusercontent.com/102253761/218524989-9aafdf5c-e327-4fde-bb13-8b9c7822abbf.png">

Personal Tab receiving the erorr message:Unable to load requested application. No static tabs are configured." on microsoft365.com/office.com.
<img width="1512" alt="Screenshot 2023-02-13 at 15 57 17" src="https://user-images.githubusercontent.com/102253761/218525032-99818c5e-0c25-438a-a5d7-597235cacd05.png">

please advise on how to debug/resolve this issue

**Comment by nwojod-MSFT** [comment]
Thank you @angelzhu923 for raising this issue. We are currently investigating and will update this thread.

**Comment by stojanovic** [comment]
It works now! I just reloaded the office.com website this morning, and everything seems fine. Thanks!

<img width="1512" alt="Screenshot 2023-02-14 at 11 17 49" src="https://user-images.githubusercontent.com/613478/218707423-8898ed03-0c38-429d-9607-c6d1a77dbb74.png">

**Comment by nwojod-MSFT** [comment]
Thank @stojanovic for confirming that the issue was resolved. I will be marking this issue as closed. Please feel free to reopen this if you have any questions.
