### ISSUE TITLE
Upload button is invisible (Bot Chat)

### ISSUE THREAD

**Issue by cagdasdavulcu** [OfficeDev/microsoft-teams-library-js#159]
Hello everyone,

i'm trying to send an image to bot via. teams chat but the upload button is invisible.

![uploadactioninvisible](https://user-images.githubusercontent.com/1059729/48575531-82ec2f80-e912-11e8-89ed-79e749010fb8.jpg)

Is this not supported at the moment?

Thanks and Best regards,
Cagdas

**Comment by billbliss** [comment]
Yes it's supported - see https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-files. When you turn on the `supportsFiles` setting in the manifest, it makes the paperclip icon (upload button) appear.

**Comment by cagdasdavulcu** [comment]
Hello @billbliss,

thank you very much!
