### ISSUE TITLE
(Shopping App) Ability for Teams apps to access local storage

### ISSUE THREAD

**Issue by AE-MS** [OfficeDev/microsoft-teams-library-js#1592]
(this is a repost on behalf of @Shama-Bildikar that has been edited for privacy)

For the First Run Experience on shopping app, we would like to store information for later retrieval on local storage. Need a way to access this programmatically from within Apps..

Context : meeting on 2/6 between Shoppin app team, @chrisyanasak & one other person.

Comments from PM copied here :
We have a scenario from Adobe where the app wants to access local files on users' devices on Teams and they don't ask for user consent today, as we haven't figured out the permission logic yet. You can park this ask with us and we will include you in the conversations when we implement this feature in hosting runtime. This is in our roadmap for FY23. Further, you can also sync up with @ydogandjiev from Teams to see if they have something figured out.

**Comment by Nivedipa-MSFT** [comment]
@AE-MS - Thanks for reporting your issue. We have redirected this to concerned engineering team. They are looking into it. Thanks.

**Comment by Shama-Bildikar** [comment]
WE have resolved this with a workaround. Issue can be closed.

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
