### ISSUE TITLE
(Shopping app) Customizable app header for Teams apps on Outlook Mobile

### ISSUE THREAD

**Issue by AE-MS** [OfficeDev/microsoft-teams-library-js#1593]
(this is a repost on behalf of @Shama-Bildikar that has been edited for privacy)

For the Shopping app, we are requesting support for customizable header on Outlook Mobile. OM team has confirmed this is in the purview of the Teams platform.

**Comment by nwojod-MSFT** [comment]
This is not a TeamsJS feature ask, but Outlook mobile. Feature request raised with Outlook mobile team.
