### ISSUE TITLE
(Shopping app) Access to clipboard for coupon clip scenario

### ISSUE THREAD

**Issue by AE-MS** [OfficeDev/microsoft-teams-library-js#1594]
(this is a repost on behalf of @Shama-Bildikar that has been edited for privacy)

For the coupon clip scenario on shopping app, we would access the system clipboard. Need a way to access this programmatically from within Apps.

Context: meeting on 2/6 between Shopping app team, @chrisyanasak & another PM

Comments from PM copied here:
Regarding the clipboard access, Android/iOS provide access to the clipboard content from other applications by default ([Content providers | Android Developers](https://developer.android.com/guide/topics/providers/content-providers) and [Clipboard Manager | Android Developers](https://developer.android.com/reference/android/text/ClipboardManager)). It looks like hosting runtime should probably provide this functionality for the apps. But we might not get to it within FY23. If you want this right away, you can probably do a custom implementation for your Android and iOS apps.

**Comment by Nivedipa-MSFT** [comment]
@AE-MS - Thanks for reporting your issue. We have redirected this to concerned engineering team. They are looking into it. Thanks.

**Comment by AE-MS** [comment]
@Shama-Bildikar Can you confirm that the new [clipboard capability](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/clipboard?view=msteams-client-js-latest) meets your needs before we close this issue?
