### ISSUE TITLE
How to use microsoftTeams.authentication.authenticate without triggering a pop up

### ISSUE THREAD

**Issue by catmanjan** [OfficeDev/microsoft-teams-library-js#1595]
We require a user token in a pop up window, the problem is every time we call microsoftTeams.authentication.authenticate an authentication window pops up which is very annoying

How do we silently acquire the token? The user is already signed in and we are using AzureAD as our APIs identity provider so ideally we should just be able to use any existing AzureAD token

**Comment by AE-MS** [comment]
Thanks for reaching out, @catmanjan! Depending on your exact scenario, you should be able to use the `authentication.getAuthToken` method, which was intended for enabling silent sign-on like you describe. The overall flow describing enabling SSO is described on [Enable SSO for tab apps](https://learn.microsoft.com/microsoftteams/platform/tabs/how-to/authentication/tab-sso-overview).

Does that help?

**Comment by catmanjan** [comment]
@AE-MS I just tried that and I got this error:

getAuthTokenForApp: Failed with error - App resource defined in manifest and iframe origin do not match

Where in the manifest am I meant to add my iframe origin?

**Comment by AE-MS** [comment]
> @AE-MS I just tried that and I got this error:
> 
> getAuthTokenForApp: Failed with error - App resource defined in manifest and iframe origin do not match
> 
> Where in the manifest am I meant to add my iframe origin?

The resource property on the [webApplicationInfo](https://learn.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#webapplicationinfo) property in your manifest is where you should put your app's AAD ID and resource URL. The domain of the URL listed as the resource in the manifest needs to match the URL of your app (which is the URL loaded in the iframe).

Do these match in your situation? If not, can you say a bit more about the scenario you're looking to enable (e.g. which resource url are you trying to acquire a token silently for?)

**Comment by catmanjan** [comment]
> > @AE-MS I just tried that and I got this error:
> > getAuthTokenForApp: Failed with error - App resource defined in manifest and iframe origin do not match
> > Where in the manifest am I meant to add my iframe origin?
> 
> The resource property on the [webApplicationInfo](https://learn.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#webapplicationinfo) property in your manifest is where you should put your app's AAD ID and resource URL. The domain of the URL listed as the resource in the manifest needs to match the URL of your app (which is the URL loaded in the iframe).
> 
> Do these match in your situation? If not, can you say a bit more about the scenario you're looking to enable (e.g. which resource url are you trying to acquire a token silently for?)

Okay thanks, what else is webApplicationInfo used for? I could swap the webApplicationInfo to be our API endpoint but currently it is a special domain just for the Teams integration

Can we have multiple webApplicationInfos? 

We have a bot that is serving cards that trigger popups, the popups are loading content from an API that is hosted on a different domain to the bot

**Comment by AE-MS** [comment]
> > > @AE-MS I just tried that and I got this error:
> > > getAuthTokenForApp: Failed with error - App resource defined in manifest and iframe origin do not match
> > > Where in the manifest am I meant to add my iframe origin?
> > 
> > 
> > The resource property on the [webApplicationInfo](https://learn.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#webapplicationinfo) property in your manifest is where you should put your app's AAD ID and resource URL. The domain of the URL listed as the resource in the manifest needs to match the URL of your app (which is the URL loaded in the iframe).
> > Do these match in your situation? If not, can you say a bit more about the scenario you're looking to enable (e.g. which resource url are you trying to acquire a token silently for?)
> 
> Okay thanks, what else is webApplicationInfo used for? I could swap the webApplicationInfo to be our API endpoint but currently it is a special domain just for the Teams integration
> 
> Can we have multiple webApplicationInfos?
> 
> We have a bot that is serving cards that trigger popups, the popups are loading content from an API that is hosted on a different domain to the bot

The manifest only allows zero or one `webApplicationInfo` object(s). As far as I know, the `webApplicationInfo` object is only used for this SSO scenario when calling `getAuthToken`.

**Comment by ChetanSharma-msft** [comment]
Hello @catmanjan - Please let us know if you have any further query here?

**Comment by catmanjan** [comment]
@AE-MS it seems the webApplicationInfo resource value must be set to the Application ID URI of the Teams bot, otherwise you pop up windows do not work

**Comment by Meghana-MSFT** [comment]
@catmanjan - Could you please let us know if your issue is resolved or you need any help? Thanks!

**Comment by catmanjan** [comment]
@Meghana-MSFT I solved this on my own - I think this needs to be better documented, for example I can find no information about having to add the Teams Client IDs to my app registration in order for the sign in to occur

**Comment by Meghana-MSFT** [comment]
Thank you for the feedback, we will look into it and take necessary action. Thanks!

**Comment by AE-MS** [comment]
> @Meghana-MSFT I solved this on my own - I think this needs to be better documented, for example I can find no information about having to add the Teams Client IDs to my app registration in order for the sign in to occur

Hi @catmanjan! Thanks for the suggestion! From [the link](https://learn.microsoft.com/microsoftteams/platform/tabs/how-to/authentication/tab-sso-overview) I referenced in my first response above, one of the sub pages (from the navigation tree on the left or by clicking on the "Register your tab application Azure AD" button at the bottom) is the [Configure your tab app in Azure AD](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-register-aad) page. On this page, there is a section titled [To configure authorized client application](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-register-aad#to-configure-authorized-client-application) which contains a list of each of the client IDs that can be added to your app's AAD registration. Is this the type of documentation that you are looking for? Or is there other information that would be more helpful?

Also FYI because of our interaction on this issue, I also pushed a change last week (#1588) which adds direct links to these SSO tab pages from the teams-js library reference documentation. Do you think this will this be helpful when using these methods in the future? It will show up on the [authentication module](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/authentication?view=msteams-client-js-latest) page when the March release gets published this week.

**Comment by catmanjan** [comment]
Yes excellent thanks
