### ISSUE TITLE
How to invoke SidePanel or save Config dialog through MeetStage

### ISSUE THREAD

**Issue by lschutze** [OfficeDev/microsoft-teams-library-js#1597]
I'm using [this ](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-in-meeting?tabs=method-1) deeplink approach to invoke directly the MeetStage of an app that I'm developing for internal use at a company.
I would like to invoke the SidePanel or save Config dialog through MeetStage instance created when the deeplink was opened. I tried to use some functions of the lib, but the only ones that seems to work are not allowed in the MeetStage frame context.

Is there a known way to do it? 

The Config dialog that I'm talking about is this one:
![image](https://user-images.githubusercontent.com/118461120/220406182-ba88361b-5e48-4944-922b-d96f8ce254ef.png)

My project is based on the live share sample:
https://github.com/microsoft/live-share-sdk/tree/main/samples/typescript/21.react-media-template

**Comment by sayali-MSFT** [comment]
@lschutze - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by sayali-MSFT** [comment]
@lschutze -You can Generate meeting side panel using below steps -
https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-meetings-sidepanel?tabs=vs

We are checking it internally if there is any other way to do as per your requirement.

**Comment by lschutze** [comment]
> @lschutze -You can Generate meeting side panel using below steps - https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-meetings-sidepanel?tabs=vs
> 
> We are checking it internally if there is any other way to do as per your requirement.

But this doc is teaching how to add it through the installation mode, with the user clicking and following installation steps. I would like to do it by code, when the MeetStage opens, invoking SidePanel or the Config dialog, where the "save" button appears.

**Comment by Wajeed-msft** [comment]
We are currently working on adding support where developers can create a deeplink to meeting side panel similar to [deep link to your tab](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-application?tabs=teamsjs-v1#generate-a-deep-link-to-your-tab) deeplink. We do not have an ETA to share. 

You can get notified with Teams platform updates by subscribing to the RSS feed. For more information, see [configure RSS feed](https://learn.microsoft.com/en-us/microsoftteams/platform/whats-new?pivots=ga-feature#get-latest-updates).
