### ISSUE TITLE
getAuthToken promise never fullfills when MS Teams is inactive for longer duration.

### ISSUE THREAD

**Issue by akshayrohatgi94** [OfficeDev/microsoft-teams-library-js#1606]
# Context
Adobe Acrobat can be configured as default PDF Viewer in MS Teams as explained in
`https://learn.microsoft.com/en-us/microsoftteams/adobe-acrobat-pdf-viewer-teams`

# Usage
We are using below snippet to get the Auth Token.

<img width="1074" alt="image" src="https://user-images.githubusercontent.com/4975895/221844641-fb15662a-c51c-40ac-ae47-07be0abe2e37.png">

# Issue
When MS Teams, is left inactive for longer duration say 5-6hours and we directly click on any PDF file then above code is executed and `getAuthToken` promise never fulfills. Hence, user keeps on seeing the loader and PDF file is not previewed.

<img width="1627" alt="image" src="https://user-images.githubusercontent.com/4975895/221845867-a19b3345-d8c7-40aa-b519-1a887da14ab8.png">

# WorkArounds
We have discussed this with Microsoft internal team and for now we auto restart our application if this promise is not fulfilled within 3 seconds.

**Comment by Nivedipa-MSFT** [comment]
@akshayrohatgi94 - Thanks for reporting your issue. We will test this and update you soon.

**Comment by Nivedipa-MSFT** [comment]
@akshayrohatgi94 - Thanks for reporting your issue. Could you please share the Teams JS version which you are using to test at our end? Thanks.

**Comment by akshayrohatgi94** [comment]
Hi @Nivedipa-MSFT 

Version is 2.0.0

**Comment by Nivedipa-MSFT** [comment]
@akshayrohatgi94 - Apologies for the delay. We are testing this out. We will update you soon.

**Comment by akshayrohatgi94** [comment]
Hi @Nivedipa-MSFT 

This is because we have deployed the work around where application reloads if token is not resolved within 3 seconds. And on reload the application always works.

Request you to create dummy application that works with Filehandler.

**Comment by Nivedipa-MSFT** [comment]
@akshayrohatgi94 - Apologies for the delay response. We will test this at our end and update you soon.

**Comment by Nivedipa-MSFT** [comment]
@akshayrohatgi94 - Access tokens obtained through getAuthToken have a limited lifespan. After a certain period, they expire and become invalid. Make sure you check for token expiration and handle token renewal appropriately in your code.
If the system has been inactive for an extended period, the authentication state may have changed. Verify that the user is still authenticated before making the getAuthToken call. If the user is no longer authenticated, you may need to guide them through the authentication flow again. This is by design behaviour.

Please let us know if you have any further queries here?

**Comment by akshayrohatgi94** [comment]
@Nivedipa-MSFT How can we do this ?

`If the user is no longer authenticated, you may need to guide them through the authentication flow again. This is by design behaviour.`

**Comment by Nivedipa-MSFT** [comment]
@akshayrohatgi94 - You have to execute your authentication code again if the promise is not fulfilled.
