### ISSUE TITLE
Can you move and resize pop ups?

### ISSUE THREAD

**Issue by catmanjan** [OfficeDev/microsoft-teams-library-js#1609]
Our add in creates pop ups, but other than the initial size we don't seem to be able to set its position or size.

Can you move and resize pop ups?

**Comment by Prasad-MSFT** [comment]
@catmanjan - Using integers for `TaskInfo.width` and `TaskInfo.height`, you can set the height and width of the task module in pixels. https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/invoking-task-modules#task-module-sizing.  Apart from that there doesn't seem to be any way.

**Comment by AE-MS** [comment]
> Our add in creates pop ups, but other than the initial size we don't seem to be able to set its position or size.
> 
> Can you move and resize pop ups?

You can request that the host resize the dialog using [dialog.update.resize](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/dialog.update?view=msteams-client-js-latest#@microsoft-teams-js-dialog-update-resize). However, the host may not be able to honor the request depending on factors related to the UX environment in which the dialog is displayed (e.g., the screen resolution, whether it's on mobile or web/Windows/Mac/etc.).

(in older-but-still-supported versions of teamsjs you can use [tasks.updateTask](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/tasks?view=msteams-client-js-latest#@microsoft-teams-js-tasks-updatetask) with the same constraints)

It is not possible to explicitly set or change the position of a dialog.

**Comment by catmanjan** [comment]
@AE-MS @Prasad-MSFT thanks, whats the process for requesting an enhancement so that users can move and resize popups?

**Comment by AE-MS** [comment]
> @AE-MS @Prasad-MSFT thanks, whats the process for requesting an enhancement so that users can move and resize popups?

@nwojod-MSFT can you please track this as a feature request?

@catmanjan to help us prioritize this request, can you provide more information about the user scenario you're looking to enable with moving and resizing? And what expectations (or special requirements) you would have on mobile platforms where all the dialogs are full screen? Thanks!

**Comment by catmanjan** [comment]
@AE-MS sure, we are using the pop up to display a document preview.

Resizing and moving the pop up would be useful to users who want to refer to content behidn the pop up. In addition sometimes users want to expand the pop up to be larger to see more information at once, but not always, so we can't just give a very large window.

Users expect the limitation with mobile, they don't mind not being able to resize there.
