### ISSUE TITLE
Authentication notifySuccess never completes in a meeting

### ISSUE THREAD

**Issue by mdbollman** [OfficeDev/microsoft-teams-library-js#1612]
When using `authentication.authenticate` in a Meeting context, neither of the callbacks or the promise then/catch will fire from the authentication dialog via notifySuccess.

When using the exact same authentication flow in a Team Tab context, everything works perfectly.

OS: Mac Ventura
Teams version: 1.6.00.4464
Teams JS SDK: 2.8.0

Similar issues #629 #1181?

Downgrading to SDK v1.12.1 also works in a meeting, but only when in Developer Preview.

**Comment by Meghana-MSFT** [comment]
We are looking into this, we will get back to you.

**Comment by ChetanSharma-msft** [comment]
Hello @mdbollman - We are looking into it and will let you know the updates.

**Comment by Meghana-MSFT** [comment]
@mdbollman - A fix has been rolled out publicly for this issue. We tested this with on Mac with Teams JS 2.10.0 version. It is working fine at our end. Could you please check if you are still seeing the problem at your end?

**Comment by mdbollman** [comment]
Confirmed that this issue has been fixed. Thank you.
