### ISSUE TITLE
In the Teams context object, parentMessageId is a string on desktop and web, but an integer on mobile

### ISSUE THREAD

**Issue by GyllionElderen** [OfficeDev/microsoft-teams-library-js#1615]
When retrieving the context of Microsoft Teams through the function `microsoftTeams.app.getContext()`,  and the field `parentMessageId` is not filled, it is a string in desktop and web, but an integer on mobile (Android). This can cause complicated situations since often you would like to return this context object to your C# enviroment. Can someone take a look at this?

Desktop and web:
![image](https://user-images.githubusercontent.com/32705616/222408882-13e513d0-2c62-4d36-acb7-1ae53e291741.png)

Mobile:
![image](https://user-images.githubusercontent.com/32705616/222408964-d367f709-685f-42de-adf4-8b801a3fa40e.png)

**Comment by Nivedipa-MSFT** [comment]
@GyllionElderen - Thanks for reporting your issue. There is an already bug raised for the same. We will let you know once we get any updates on it. Thanks.

**Comment by GyllionElderen** [comment]
> @GyllionElderen - Thanks for reporting your issue. Could you please share the Teams JS version which you are using to test at our end? Thanks.

Yes, currently we are using version 2.5.0

**Comment by Nivedipa-MSFT** [comment]
@GyllionElderen - We will test this using TeamsJS 2.5.0 and update you soon.

**Comment by Nivedipa-MSFT** [comment]
@GyllionElderen - We have tested this on Android 11 and below Teams version. But at our end parentMessageId coming as string.

![image](https://user-images.githubusercontent.com/92150070/222950009-7a93b35f-7d97-454c-9aa1-f3c8f1a1d011.png)

![image](https://user-images.githubusercontent.com/92150070/222950030-25e75ed3-48f0-4a79-8f5d-f58d75d49fe9.png)

Could you please share in which context you are calling getcontext? Are we doing in a right way or we have missed any step here?
