### ISSUE TITLE
Share to Teams from personal tab app platform/browser support

### ISSUE THREAD

**Issue by danielkrausz** [OfficeDev/microsoft-teams-library-js#1616]
When using `sharing.shareWebContent()` in the Teams web client in Safari, the following errors are thrown and the sharing modal doesn't open:
 - `EC::EntityCommandQueue: enqueueEntityCommand failed - {\"correlationId\":\"daf425f9-dd1a-4d41-b643-0e74110461ab\",\"reason\":\"ExperienceContainerNotEnabled\",\"ecReady\":false}"`
- `TabContentSharingService: Unable to open shareFormDialog with id daf425f9-dd1a-4d41-b643-0e74110461ab`

As far as I understand the Safari support is currently in preview, but I haven't found anything regarding this issue. Are you aware of this problem, or do you have a timeline for when this will be supported in Safari?

Teams JS SDK: `2.8.0`
Safari: `Version 16.3 (17614.4.6.11.6, 17614)`

As an additional question regarding the support of the Share to Teams feature:  it's noted in the [documentation](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams-from-personal-app-or-tab) that the feature isn't available on mobile platforms, but calling `sharing.isSupported()` still returns `true` on mobile, which I don't think is the expected behaviour. Could you look into this?

Thank you!

**Comment by nwojod-MSFT** [comment]
@danielkrausz thanks for bringing this up. We'll look into it and inform you if we come across a similar situation on Safari. As for checking capability support, it's advisable to use **sharing.isSupported()**. This function should indicate false if the capability is not available and true if it is. We'll examine this on our end to make sure the call returns **false** for mobile and resolve the issue appropriately.

**Comment by Nivedipa-MSFT** [comment]
@danielkrausz - Thanks for reporting your issue. We will test this and raised a bug accordingly. thanks.

**Comment by nwojod-MSFT** [comment]
@danielkrausz we have made the fix to return **_false_** when calling _**sharing.isSupported()**_ on mobile. However, we have not rolled out an official teamjs versions that contains this fix, but should certainly have one by the first week of April. In the meantime, the beta version https://www.npmjs.com/package/@microsoft/teams-js/v/2.10.0-beta.2 should contain the fix.

**Comment by nwojod-MSFT** [comment]
Closing this issue as the fix was rolled out in teams js v2.10.0. Please this if issue persists.
