### ISSUE TITLE
Deeplinks to schedule-meeting handled incorrectly in Teams WebApp

### ISSUE THREAD

**Issue by ParadoxSpiral** [OfficeDev/microsoft-teams-library-js#1626]
From inside a Teams Tab in personal scope: A deeplink that is opened via `app.openLink` (or manually in a new browser tab) with this format `https://teams.microsoft.com/l/meeting/new?attendees=user1,user2` (kind of) works in the native Windows App, and the Android client. The user that opens the app is added as an attendee which does not make sense as they are the organizer.

In Chrome/Edge the specified attendees are not added at all. Specifiying a start / end date works as expected. Furthermore about 50% of the time if hitting the "close" button to cancel scheduling the meeting, it disappears for a second and then opens again with it being impossible to close. Sometimes after hitting close the dialog disappears and leaves an empty white window instead of navigating back. This also happens when hitting "send", an empty dialog comes up but the meeting is scheduled correctly. If hitting "send" empty meetings with no attendees are scheduled:

![image](https://user-images.githubusercontent.com/9111171/223365399-b97e5e1a-fb27-4252-884b-80dd6d6b698b.png)

**Comment by Wajeed-msft** [comment]
Thanks for reporting this. We will try to repro this at our end and let you know updates.

**Comment by Meghana-MSFT** [comment]
@ParadoxSpiral - Please find the below observations

> In Chrome/Edge the specified attendees are not added at all 

We have a bug raised for this issue, we will keep you posted once the fix is publicly available. 

> 50% of the time if hitting the "close" button to cancel scheduling the meeting, it disappears for a second and then opens again with it being impossible to close.

We are not able to repro this issue, could you please share a recording of this?

> Sometimes after hitting close the dialog disappears and leaves an empty white window instead of navigating back. This also happens when hitting "send", an empty dialog comes up but the meeting is scheduled correctly. If hitting "send" empty meetings with no attendees are scheduled:

Please find the attached videos and could you please confirm if you are facing the same issue? 

https://user-images.githubusercontent.com/81138249/223711760-d5b818b0-20d4-40f7-880c-307570d821ce.mp4

https://user-images.githubusercontent.com/81138249/223711794-fa4d1054-a12d-40c7-9e53-057b5f19301a.mp4

**Comment by ParadoxSpiral** [comment]
Hi @Meghana-MSFT, thanks for checking this out!

> Please find the attached videos and could you please confirm if you are facing the same issue?

That is the issue, yes. I would expect that if the link is opened from within an App that the user is redirected back to the App afterwards.

> We are not able to repro this issue, could you please share a recording of this?

Refer to the attached screen recording. I think it may be the same bug as the one above, just with a slightly different outcome if opened from inside a personal App.


https://user-images.githubusercontent.com/9111171/223938314-8dca30d6-5281-4d6f-90cf-30454c88dbcb.mp4

**Comment by Meghana-MSFT** [comment]
@ParadoxSpiral - A bug has been raised for these issues. We will keep you posted on the updates. Thanks.

**Comment by Meghana-MSFT** [comment]
> In Chrome/Edge the specified attendees are not added at all. 

This bug has been fixed. We checked the deeplink in web version. It populates the attendees and the content correctly. Could you please check? Thanks for your patience!

**Comment by ParadoxSpiral** [comment]
> This bug has been fixed. We checked the deeplink in web version. It populates the attendees and the content correctly. Could you please check? Thanks for your patience!

Awesome, I can confirm that this has been the fixed 🚀

The other issue that occurs when closing the dialog is still present

**Comment by hq-duanyq** [comment]
I also encountered the same problem

**Comment by Meghana-MSFT** [comment]
The remaining issue is no longer reproducible in the new Teams T2.1. Could you please check and confirm once?

**Comment by ParadoxSpiral** [comment]
> The remaining issue is no longer reproducible in the new Teams T2.1. Could you please check and confirm once?

Thanks! I can confirm that this is fixed :)
