### ISSUE TITLE
TeamsSDK MicrosoftTeams TeamsContext.HostClientType always return Android

### ISSUE THREAD

**Issue by phong101665** [OfficeDev/microsoft-teams-library-js#1629]
I created a application in Visual Studio by Teams Tookit extension. I also deployed the app on cloud and published on Microsoft Teams.

But I check the "**HostClientType**" when I open the app in Microsoft Teams (desktop and iPhone) it always detect the "**HostClientType**" is Android, instead of Desktop or iOS as my expectation.

Could you please help to explain about this case?

For additional information, I followed the article below to create the app.
https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-csharp

Many thanks

Phong Truong

**Comment by Nivedipa-MSFT** [comment]
@phong101665 - Thanks for reporting your issue. We will test this and update you soon.

**Comment by Nivedipa-MSFT** [comment]
@phong101665 - We will test this using TeamsJS library version 2.9.1 and update you soon.

**Comment by therealjohn** [comment]
This was an issue in the Tab template of Teams Toolkit and reported here: https://github.com/OfficeDev/TeamsFx/issues/8090

There is a workaround available: copy the TeamsContext class in that issue and replace `Interop/TeamsSDK/TeamsContext.cs` with that content.

**Comment by AE-MS** [comment]
Closing this issue here as it is being tracked by the above issue in the Teams Toolkit project.
