### ISSUE TITLE
New Teams meeting experience breaks authentication flow in AVD

### ISSUE THREAD

**Issue by cgvalayev** [OfficeDev/microsoft-teams-library-js#1631]
We started to get complaints that authentication stopped working in teams task module in our app tab. The issue was due to the fact that authentication would open in a browser in a new tab instead of a popup window which breaks `microsoftTeams.authentication.notifySuccess` communication back to the task module tab. 

We were able to reproduce this in a new virtual desktop env with teams installed there. Everything worked ok but when we clicked on "Restart" 
<img width="752" alt="image" src="https://user-images.githubusercontent.com/88786064/223777372-67bd00dd-7b25-4ef6-a79e-40bc01fa9309.png">

Teams restarted and authentication stopped working through the popup.

Is this expected? 
If yes, can you please point us to correct docs so that we can fix our auth?
If no, can you let us know how to revert the new experience? And when will this be resolved?

**Comment by sayali-MSFT** [comment]
@cgvalayev - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by cgvalayev** [comment]
Hey @sayali-MSFT, any updates on this?

**Comment by sayali-MSFT** [comment]
@cgvalayev - We have tested this issue with desktop teams client and it is working fine from our end.
Could you please confirm once, is it repro only on new virtual desktop env or Desktop client also facing issue?

also please share the teams and JS version so that we can try it again from our end.

Microsoft Teams Version 1.6.00.7068 (64-bit)
Teams JS-2.0.0

**Comment by cgvalayev** [comment]
The only place we were prompted for the new meeting experience is in Teams inside Azure Virtual Desktop. Click Restart was what broke it 
<img width="756" alt="image" src="https://user-images.githubusercontent.com/88786064/226468974-5950ba26-3592-4f06-9bc2-b046f8573ba6.png">

Microsoft Teams Version 1.6.00.1381 (64-bit). AVD Media Optimized.
Teams JS-^1.11.0

**Comment by cgvalayev** [comment]
It really seems like it is related to Azure Virtual Desktop, looks like new meeting experience is enabled everywhere by default but in AVD (which uses Windows Enterprise) it was disabled and auth worked, then we saw that notification to restart to enable, and afterwards authentication broke because it started launching Edge browser for the auth instead of using pop up window.

**Comment by sayali-MSFT** [comment]
@cgvalayev - We are checking it internally and let you know once we get any updates.

**Comment by cgvalayev** [comment]
Hey @sayali-MSFT, did you guys get a chance to investigate this in AVD?

**Comment by sayali-MSFT** [comment]
@cgvalayev -We are not able to repro the issue, we are checking the other scenario as well and get back to you.

**Comment by cgvalayev** [comment]
Ok. Make sure you are running on Microsoft Teams Version 1.6.00.1381 (64-bit). AVD Media Optimized.

**Comment by cgvalayev** [comment]
@sayali-MSFT Did you get a chance to reproduce in AVD environment?

**Comment by sayali-MSFT** [comment]
@cgvalayev -We have tried with the Microsoft Teams Version 1.6.00.1381 (64-bit) version but not able to repro the issue.
Could you please share the steps to reproduce in AVD environment?

**Comment by cgvalayev** [comment]
Hey @sayali-MSFT you create AVD as usual and mimic configs with ours:
```
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "hostpools_threaddevmachine_name": {
            "defaultValue": "threaddevmachine",
            "type": "String"
        }
    },
    "variables": {},
    "resources": [
        {
            "type": "Microsoft.DesktopVirtualization/hostpools",
            "apiVersion": "2022-10-14-preview",
            "name": "[parameters('hostpools_threaddevmachine_name')]",
            "location": "eastus",
            "properties": {
                "publicNetworkAccess": "Enabled",
                "description": "Created through the Azure Virtual Desktop extension",
                "hostPoolType": "Pooled",
                "customRdpProperty": "drivestoredirect:s:*;audiomode:i:0;videoplaybackmode:i:1;redirectclipboard:i:1;redirectprinters:i:1;devicestoredirect:s:*;redirectcomports:i:1;redirectsmartcards:i:1;usbdevicestoredirect:s:*;enablecredsspsupport:i:1;redirectwebauthn:i:1;use multimon:i:1;",
                "maxSessionLimit": 2,
                "loadBalancerType": "BreadthFirst",
                "validationEnvironment": false,
                "vmTemplate": "{\"domain\":\"\",\"galleryImageOffer\":\"office-365\",\"galleryImagePublisher\":\"microsoftwindowsdesktop\",\"galleryImageSKU\":\"win11-22h2-avd-m365\",\"imageType\":\"Gallery\",\"customImageId\":null,\"namePrefix\":\"threaddev\",\"osDiskType\":\"StandardSSD_LRS\",\"vmSize\":{\"id\":\"Standard_D2s_v3\",\"cores\":2,\"ram\":8},\"galleryItemId\":\"Microsoftwindowsdesktop.office-365win11-22h2-avd-m365\",\"hibernate\":false,\"diskSizeGB\":0,\"securityType\":\"Standard\",\"secureBoot\":false,\"vTPM\":false}",
                "preferredAppGroupType": "Desktop",
                "startVMOnConnect": false
            }
        }
    ]
}
```

Once you are inside, open teams, and make sure it says this version when clicking About -> Version
> Microsoft Teams Version 1.6.00.1381 (64-bit). **AVD Media Optimized.**

**Comment by sayali-MSFT** [comment]
@cgvalayev -Thanks for providing information, we are checking with the engineering team and get back to you once we get any update.

**Comment by sayali-MSFT** [comment]
@cgvalayev -Engineering team is able to repro the issue and investigate on this issue. We will let you know once we get any update.

**Comment by cgvalayev** [comment]
Hey @sayali-MSFT, how is it going? Any progress on this?

**Comment by sayali-MSFT** [comment]
@cgvalayev -Issue has been fixed in internal rings. We will let you know once we get update about the fix publicly being rolled out.

**Comment by cgvalayev** [comment]
Hey @sayali-MSFT, do you have an approximate date for the release of the fix?

**Comment by sayali-MSFT** [comment]
@cgvalayev -Apologies for the delays, currently we don’t have exact ETA or Update on this thread. We will let you know once we have any updates on it. 

Thanks.

**Comment by revilo-1994** [comment]
@sayali-MSFT Do you have an update on this bug? Or a possible workaround? We are using Teams wide installer on a Citrix environment.

**Comment by sayali-MSFT** [comment]
@revilo-1994  -Issue has been fixed in internal rings. We will let you know once we get update about the fix publicly being rolled out.

**Comment by sayali-MSFT** [comment]
@cgvalayev ,@revilo-1994 -Bug is resolved.Could you please check it once and confirm the same?
Microsoft Teams Version -1.6.00.18681

**Comment by revilo-1994** [comment]
> @cgvalayev ,@revilo-1994 -Bug is resolved.Could you please check it once and confirm the same? Microsoft Teams Version -1.6.00.18681

Hi Sayali, I can confirm that it works again in this update.

**Comment by sayali-MSFT** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
