### ISSUE TITLE
How to get a tab/app to appear within the tab + menu of a team

### ISSUE THREAD

**Issue by Admiral-Skye** [OfficeDev/microsoft-teams-library-js#1634]
I have an app that I am developing which involves a Tab, bot and message extension. 

I have noticed that if I define a "configurableTab" in the manifest, my app is available for selection when selecting the + next to the channel tabs. 

Additionally, it appears that when I define this configurable tab and select my app from the menu, click Add from the app page, the tab appears before the configuration menu is shown. If I close the configuration window without saving changes, my app is still added to the team and functions correctly. 

What I would like to know is:
- is this actually necessary for my app to be available through the + menu? or 
- is there some way that I can have my users able to add my app from that menu without the need to define a configuration page as my app does not require one?

I have tried implementing a form of dummy configuration page that immediately just marks the configuration as done and informs the user that no changes are necessary however the UX of this approach is not amazing so I would prefer not to use it.

**Comment by sayali-MSFT** [comment]
@Admiral-Skye - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by sayali-MSFT** [comment]
@Admiral-Skye - We are not able to repro the scenario as you mention above. Could you please confirm once are you trying the same as mentioned below-

https://user-images.githubusercontent.com/93527375/224713921-eee3ab30-069c-41e0-a4c2-617cc5bc267b.mp4

**Comment by Admiral-Skye** [comment]
@sayali-MSFT So by your answer It is required to include the configurable tabs component of the manifest in order to be able to add my tab to a team via the [+] icon next to the tabs of a team?

If so could you tell me which sample are you using there? If possible I'd like to compare my manifest settings and also what the configuration page is actually doing before the save button is clicked.

**Comment by sayali-MSFT** [comment]
@Admiral-Skye -Yes. We are referring the below sample to repro the scenario.
Sample link - https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/tab-sso/csharp/TeamsTabSSO/Manifest/manifest.json

**Comment by Admiral-Skye** [comment]
@sayali-MSFT I see, I have re-implemented my configurable tab however i have noticed that when the user clicks to "save" both the static tab and the configurable tab are added to the team. Is there a way i can work around this?

**Comment by Admiral-Skye** [comment]
@sayali-MSFT I think I worked out my issue there, I had defined the static tab as both a personal and teams tab, removing that fixed the issue

**Comment by sayali-MSFT** [comment]
@Admiral-Skye -Glad to hear that your issue is resolved.
Shall we close this issue or still looking for any help?

**Comment by Admiral-Skye** [comment]
@sayali-MSFT Yes thank you, this has answered my question
