### ISSUE TITLE
`authenticate({isExternal: true})` external window on mobile could not initialize teams-js

### ISSUE THREAD

**Issue by gazben** [OfficeDev/microsoft-teams-library-js#1635]
Hi,

Can I get some clarification on how to use the `isExternal` flag? Should the `context` be available in the opened window? 

I call the `authenticate()` method this way:

```
authentication.authenticate({
        isExternal: true,
        url: '/auth-start?oauthRedirectMethod={oauthRedirectMethod}&authId={authId}',
        height: 610,
      })
``` 

If I try it from a desktop browser the opened page can call `window.microsoftTeams.app.initialize()` and get the context and I can query the token. 
If do the same thing on a mobile browser (chrome on android, safari on ios) I cannot initialize the `teams-js` in the external window: "Teams init error Error: Initialization Failed. No Parent window found."

Is this a bug or a feature? Should I be able to query the token on the external page?

**Comment by sayali-MSFT** [comment]
@gazben - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by nwojod-MSFT** [comment]
@gazben This does work in the browser but is not currently supported in mobile scenarios. Apologies for the inconvenience. We will notify the community once we have support for mobile.

**Comment by nwojod-MSFT** [comment]
@gazben please can you share a bit more information on what you are trying to achieve so that we can provide guidance. Thanks.

**Comment by gazben** [comment]
When the user opens the external login window, I wanted to query the token so i can validate it on the backend. But without this I just stick to the authentication result code to  query the user.
