### ISSUE TITLE
"Auth Library Error" issue on iOS 16

### ISSUE THREAD

**Issue by goamn** [OfficeDev/microsoft-teams-library-js#1640]
Our customers are getting the "Auth Library Error" on iPhone iOS version 16. We are using package `@microsoft/teams-js` version `2.0.0`.
I believe it is happening while calling `microsoftTeams.authentication.getAuthToken()`
I noticed that this was marked as fixed in iOS 15 ( [Ticket 654](https://github.com/OfficeDev/microsoft-teams-library-js/issues/654), [and ticket 791](https://github.com/OfficeDev/microsoft-teams-library-js/issues/791) )

We also observed it for customers with the following iPhone/iPad versions:
iPhone 15.4
iPhone 15.6
iPhone 16.1
iPhone 16.3
iPad 16.1
iPad 16.3

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this issue, we will look into this and get back to you.

**Comment by Meghana-MSFT** [comment]
@goamn - Engineering team is checking this issue and 98% of `authentication.getAuthToken` call are succeeding on iOS 16+.

To investigate further, could you please follow these steps in iOS and Send feedback.
Teams app under Settings > Help and feedback > Send feedback

Send feedback option should attach the logs automatically. Please note that it needs to be done after reproducing the issue. 

Could you also share the test user details where this is call is failing.
