### ISSUE TITLE
AdaptiveCard search result height inconsistency between web and desktop

### ISSUE THREAD

**Issue by catmanjan** [OfficeDev/microsoft-teams-library-js#1644]
We have an AdaptiveCard search result that is 4 or more lines long

This renders correctly in web teams, but in desktop teams it seems to be hardcoded to only show 4 lines

See below

![image](https://user-images.githubusercontent.com/137350/225486988-9a1e82d8-bafb-4fe5-af2d-73de63a89524.png)

**Comment by Prasad-MSFT** [comment]
Hi @catmanjan - Thanks for raising your issue. Could you please share repro steps along with sample code used or any deployed one, so that we can try once from our end?

**Comment by catmanjan** [comment]
@Prasad-MSFT here is a sample of how we're making the AdaptiveCard

```

                var adaptiveMetadataElements = new List<AdaptiveElement>
                {
                    new AdaptiveTextBlock()
                    {
                        Text = $"[{result.Title!.Raw}]({result.Url.Raw})",
                        Size = AdaptiveTextSize.Medium,
                        Weight = AdaptiveTextWeight.Bolder,
                        Spacing = AdaptiveSpacing.None
                    },
                    new AdaptiveTextBlock()
                    {
                        Text = result.Metadata!.ContentSourceId,
                        Size = AdaptiveTextSize.Small,
                        Weight = AdaptiveTextWeight.Default,
                        Spacing = AdaptiveSpacing.None
                    },
                    new AdaptiveTextBlock()
                    {
                        Text = $"Modified: {result.Metadata!.LastUpdated.ToString("d MMMM yyyy")} | Creator: {result.CreatedBy?.Raw}",
                        Size = AdaptiveTextSize.Medium,
                        Weight = AdaptiveTextWeight.Lighter,
                        Spacing = AdaptiveSpacing.None,
                    }
                };

                // previewCard Title should not be a link, as links are not clickable in compose action search results
                var previewCard = new ThumbnailCard
                {
                    Title = $"<div>{result.Title?.Raw}</div>",
                    Subtitle = result.Body?.Snippet,
                    Text = $"{result.Metadata!.ContentSourceId}<br>Modified: {result.Metadata!.LastUpdated.ToString("d MMMM yyyy")} | Creator: {result.CreatedBy?.Raw}",
                    Images = new List<CardImage> { new CardImage { Url = $"{_url}/icon/{imageType}" } },
                };

                var adaptiveCard = new AdaptiveCard(new AdaptiveSchemaVersion(1, 3))
                {
                    Body = new List<AdaptiveElement>()
                    {
                        new AdaptiveColumnSet()
                        {
                            Columns = new List<AdaptiveColumn>()
                            {
                                // Icon Column
                                new AdaptiveColumn()
                                {
                                    Height = AdaptiveHeight.Auto,
                                    Width = AdaptiveColumnWidth.Auto,
                                    Items = new List<AdaptiveElement>()
                                    {
                                        new AdaptiveImage()
                                        {
                                            Url = new Uri($"{_url}/icon/{result.Icon.Raw}"),
                                            Size = AdaptiveImageSize.Medium,
                                            Style = AdaptiveImageStyle.Default
                                        }
                                    }
                                },
                                // metadata column
                                new AdaptiveColumn()
                                {
                                    Height = AdaptiveHeight.Auto,
                                    Width = AdaptiveColumnWidth.Stretch,
                                    Items = adaptiveMetadataElements
                                }
                            }
                        },
                        new AdaptiveTextBlock()
                        {
                            Text = result.Body.Snippet?.Replace("<b>", "").Replace("</b>", ""),
                            Size = AdaptiveTextSize.Default,
                            Weight = AdaptiveTextWeight.Default
                        }
                    }
                };
```

**Comment by Prasad-MSFT** [comment]
@catmanjan - We checked this issue having search result that is 4 or more lines long, however in both Teams desktop `(Microsoft Teams Version 1.6.00.6661)` and web client it renders the same.
**Teams desktop:**
![image](https://user-images.githubusercontent.com/62237649/225618257-93812629-edd3-448f-b4e1-d07f5d597123.png)

**Teams web:**
![image](https://user-images.githubusercontent.com/62237649/225618140-94e818a7-1590-449d-b49a-be12d1c0bb59.png)

**Comment by catmanjan** [comment]
Try putting a really long title in to make it more than 4 lines

**Comment by catmanjan** [comment]
@Prasad-MSFT okay this isn't what we are seeing, what information do you need?

**Comment by catmanjan** [comment]
I notice the middle text "An Adaptive Card..." is shorter than mine and it seems to be a different size too?

**Comment by catmanjan** [comment]
Are you using a ThumbnailCard as the Preview? 
![image](https://user-images.githubusercontent.com/137350/225793058-4051342e-be8c-4114-95af-c5f6c8d456e3.png)

**Comment by catmanjan** [comment]
@Prasad-MSFT okay I'm pretty sure I worked it out - I think you're serving a HeroCard, but I am serving a ThumbnailCard

My problem is that if I have to serve a HeroCard then how do I restrict the image size? HeroCard does not seem to resize the image in a desirable way:

![image](https://user-images.githubusercontent.com/137350/225816631-09d3b7e6-8600-4c66-909b-665bcd922807.png)

**Comment by Prasad-MSFT** [comment]
> Are you using a ThumbnailCard as the Preview? ![image](https://user-images.githubusercontent.com/137350/225793058-4051342e-be8c-4114-95af-c5f6c8d456e3.png)

@catmanjan - We are using thumbnail card only
```
var previewcard = new ThumbnailCard
            {
                Title = "Adaptive Card supports only Incoming Webhook O365 Connector type and not any other O365 Connector types.For Adaptive Cards in Incoming Webhooks, all native Adaptive Card schema elements, except Action.Submit, are fully supported. You can pass dynamic values in an Adaptive Card using the dollar symbol ($) and curly braces.You can pass dynamic values in an Adaptive Card using the dollar symbol ($) and curly braces.You can pass dynamic values in an Adaptive Card using the dollar symbol ($) and curly braces.You can pass dynamic values in an Adaptive Card using the dollar symbol ($) and curly bracesYou can pass dynamic values in an Adaptive Card using the dollar symbol ($) and curly bracesYou can pass dynamic values in an Adaptive Card using the dollar symbol ($) and curly bracesYou can pass dynamic values in an Adaptive Card using the dollar symbol ($) and curly bracesYou can pass dynamic values in an Adaptive Card using the dollar symbol ($) and curly bracesYou can pass dynamic values in an Adaptive Card using the dollar symbol ($) and curly bracesYou can pass dynamic values in an Adaptive Card using the dollar symbol ($) and curly braces",
                Subtitle = "An Adaptive Card is a customizable card that can contain any combination of text, speech, images, buttons, and input fields.Media elements are currently not supported in Adaptive Card on the Teams platform.An Adaptive Card is a customizable card that can contain any combination of text, speech, images, buttons, and input fields.An Adaptive Card is a customizable card that can contain any combination of text, speech, images, buttons, and input fields.An Adaptive Card is a customizable card that can contain any combination of text, speech, images, buttons, and input fields.",
                Text = "Teams platform supports v1.5 or earlier of Adaptive Card features for bot sent cards and action based message extensions.",
                Images = new List<CardImage> { new CardImage { Url = "https://fastly.picsum.photos/id/650/200/300.jpg?hmac=iNg9Umek-SwBR_yU0igvABZSTcRJFdhp1zyaqp0PdIw" } },

            };
```

**Comment by catmanjan** [comment]
@Prasad-MSFT can you link me your whole repo so I can see what the difference is? I've tried your code and I still get a maximum of 4 lines

**Comment by catmanjan** [comment]
@Prasad-MSFT I did my own investigation and I've found the issue - Teams desktop has different size logic based on the number of results you return - if I return a single result I get more lines to appear than if I return more than one

I think this is a bug/bad feature - especially since it is inconsistent with web version

![image](https://user-images.githubusercontent.com/137350/226216326-c4022919-6c0f-4015-b024-a0f9bd962554.png)

**Comment by Prasad-MSFT** [comment]
@catmanjan - We did check the same scenario, however at our side it renders the same in both MS Teams desktop `(Microsoft Teams Version 1.6.00.7879 )` and web client.
Teams Desktop:
![image](https://user-images.githubusercontent.com/62237649/226297176-3f1e2098-e9d5-4e2f-a0f3-791a01853c34.png)

Teams Web:
![image](https://user-images.githubusercontent.com/62237649/226297277-3c5e48ab-fb94-47fe-83fe-676813c8afa1.png)

**Comment by catmanjan** [comment]
@Prasad-MSFT my Teams version updated overnight to 16.0.0.4472 and now the behavior has changed again, now I see all the text in the desktop version, there is never a cut off no matter how long the text is...

What is the behavior we're meant to be seeing here?

![image](https://user-images.githubusercontent.com/137350/226492165-41a80923-24e6-458f-b366-b2d18b641a5e.png)

**Comment by Prasad-MSFT** [comment]
@catmanjan - This is quite strange. Ideally it should show the behavior as below:
![image](https://user-images.githubusercontent.com/62237649/226570304-6673863f-18bf-44b4-aefb-19dee368c641.png)

**Comment by catmanjan** [comment]
@Prasad-MSFT this is still happening intermittently and we have no idea why

**Comment by Prasad-MSFT** [comment]
We also tried recently using` Microsoft Teams Version 1.6.00.10677`, however it works fine for us. It looks similar in both Dsktop and web client.
![image](https://user-images.githubusercontent.com/62237649/234004141-058da441-225f-44b3-9dc1-accce0d62da8.png)
