### ISSUE TITLE
Deeplink redirect issue when performing external OAuth

### ISSUE THREAD

**Issue by cgvalayev** [OfficeDev/microsoft-teams-library-js#1652]
Due to [this issue](https://github.com/OfficeDev/microsoft-teams-library-js/issues/1631), we are trying to implement [external OAuth](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-oauth-provider). However, we are facing the following issue after authentication succeeds in the browser and it attempts to deeplink back into Teams.

Deeplink URL its constructing is this (looks correct): `msteams://teams.microsoft.com/l/auth-callback?authId=1679418368180&result=Vch8RE4ptDUNqT30XGBHw8m4vvPMfJCkfPDoQXOKLve-b`

But once it reaches MS Teams we get the following errors in the console.

```
2023-03-21T16:57:14.385Z callingDeepLinkService: Error while parsing the url: SyntaxError: Unexpected end of JSON input
2023-03-21T16:57:14.386Z callingDeepLinkService: Couldn't get context for calling deep link: SyntaxError: Unexpected end of JSON input
```
![image](https://user-images.githubusercontent.com/88786064/226686917-1bb583bf-b6f0-4947-873b-88c3c54b98f6.png)
Screenshot from Teams Dev Tools.

Example how auth starts:
```js
function loginWithMSTeams() {
  return app.initialize().then(() =>
    authentication.authenticate({
      url: `${Config.BASE_DOMAIN}/auth-start`,
      width: 600,
      height: 535,
      isExternal: true
    }),
  );
}
```

Eventually this promise times out and rejects.

Microsoft Teams Version 1.6.00.1381 (64-bit). AVD Media Optimized.
Teams JS: 2.9.1

**Comment by sayali-MSFT** [comment]
@cgvalayev - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by sayali-MSFT** [comment]
@cgvalayev -Looks like the deeplink URL is incorrect. 

as mentioned in document when it opens in browser like below-
`https://BASE_DOMAIN/auth-start?oauthRedirectMethod=deeplink&authId=1234567890`

In the above provided deeplink miss the parameter `oauthRedirectMethod=deeplink`

The following are added to the authenticate() API to support external OAuth providers:

- isExternal parameter
- Two placeholder values in the existing url parameter

1.  **oauthRedirectMethod**: Pass placeholder in {}. This placeholder is replaced by deeplink or web page by Teams platform, which informs app server if the call is coming from mobile platform.

2. **authId**: This placeholder is replaced by UUID. The app server uses it to maintain session.

Could you please pass these 2 parameters and check it once.

`/auth-start?oauthRedirectMethod={oauthRedirectMethod}&authId={authId}`

**Comment by cgvalayev** [comment]
Hey @sayali-MSFT, snippet i shared a was from another commit. We did what you are describing:
```js
function loginWithMSTeams() {
  const options = {
    state: JSON.stringify({ oauthRedirectMethod: 'deeplink', authId: Date.now() }),
    redirect_uri: `${Config.BASE_DOMAIN}/auth-end`,
    ...
  };
  return app.initialize().then(() =>
    authentication.authenticate({
      url: `https://${Config.AUTH0_DOMAIN}/authorize?${parse.qs.stringify(options)}`,
      width: 600,
      height: 535,
      isExternal: true
    }),
  );
}
```

This part works as expected, it redirects to microsoft oauth and afterwards redirects back to `redirect_uri`. On the redirect page we have the following logic: 
```    const queryParams = parse(window.location.href, true).query;
    const state = JSON.parse(queryParams.state);

    if (state.oauthRedirectMethod === 'deeplink') {
      // This case happens for Teams in Azure Virtual Desktop (Motiva one of our partners that had this case)
      // https://learn.microsoft.com/en-us/azure/virtual-desktop/teams-on-avd
      // https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-oauth-provider
      window.location.assign(`msteams://teams.microsoft.com/l/auth-callback?authId=${state.authId}&result=${queryParams.code}`);
    } else {
      app.initialize().then(() => {
        authentication.notifySuccess(queryParams.code);
      });
    }
```
This code constructs the following URL: `msteams://teams.microsoft.com/l/auth-callback?authId=1679418368180&result=Vch8RE4ptDUNqT30XGBHw8m4vvPMfJCkfPDoQXOKLve-b`, we get a pop up to open in desktop app. It brings up desktop teams app and nothing happens. All we see is these errors in teams' dev tools console:
```
2023-03-21T16:57:14.385Z callingDeepLinkService: Error while parsing the url: SyntaxError: Unexpected end of JSON input
2023-03-21T16:57:14.386Z callingDeepLinkService: Couldn't get context for calling deep link: SyntaxError: Unexpected end 
of JSON input
```

**Comment by sayali-MSFT** [comment]
@cgvalayev - Thanks for sharing information, we will try it from our end and get back to you.

**Comment by cgvalayev** [comment]
@sayali-MSFT any updates on this?

**Comment by sayali-MSFT** [comment]
@cgvalayev -Checking with the internal team and we will get back to you once we get any update.

**Comment by sayali-MSFT** [comment]
@cgvalayev -Got the reply from engineering team that, the external auth working just as expected even when these errors are shown in the console. there is something wrong with the developer's implementation of the auth flow. It looks like they are providing their own authId which is not correct. As per our docs, they should specify {oauthRedirectMethod} and {authId} placeholders in their auth URL which Teams will replace as part of the authenticate call.

 
Could please try like below to fix your code by changing it to something like this:

```
function loginWithMSTeams() {
  const options = {
    state: JSON.stringify({ oauthRedirectMethod: 'OAUTH_REDIRECT_METHOD', authId: 'AUTH_ID' }),
    redirect_uri: `${Config.BASE_DOMAIN}/auth-end`,
    ...
  };
  const qsps = parse.qs.stringify(options)
    .replace("OAUTH_REDIRECT_METHOD", "{oauthRedirectMethod}")
    .replace("AUTH_ID", "{authId}");

  return app.initialize().then(() =>
    authentication.authenticate({
      url: `https://${Config.AUTH0_DOMAIN}/authorize?${qsps}`,
      width: 600,
      height: 535,
      isExternal: true
    });
  );
}
```

**Comment by cgvalayev** [comment]
Can be closed

**Comment by sayali-MSFT** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
