### ISSUE TITLE
Authenticate Method(NotifySuccess/NotifyFailure) doesn't call the respective callbacks properly in the Appointment.

### ISSUE THREAD

**Issue by titusannadurai** [OfficeDev/microsoft-teams-library-js#1655]
While using the microsoftTeams method from `@microsoft/teams-js` in a appointment/meeting cases, it fails to trigger the callbacks either successCallback or failureCallback in the authenticate method when firing the notifySuccess/NotifyFailure (microsoftTeams.authentication.notifySuccess() / microsoftTeams.authentication.notifyFailure() ) methods.

Initially on loading, the failureCallback gets initiated and fired even though the notifyFailure() method is not been called anywhere. Prior to that when initiating the notifySuccess(), the successCallback doesn't get fired which is present inside the authenticate method.

The schema and the manifest versions are listed below,
$schema - https://developer.microsoft.com/en-us/json-schemas/teams/v1.9/MicrosoftTeams.schema.json
manifestVersion - 1.9
version - 2.0.1
@microsoft/teams-js - ^1.6.0
@microsoft/teamsfx - ^0.1.0

Similar issues #1612

Could you please analyze on this behavior and provide solutions?

**Comment by Meghana-MSFT** [comment]
Thank you for reporting, we will check this and get back to you.

**Comment by anmaur** [comment]
Hi @titusannadurai, Thanks for reporting it. While the relevant team is still investigating the issue of authentication.notify* APIs not working in meeting, Could you pls share the steps that you are doing at below to repro? Thanks

'Initially on loading, the failureCallback gets initiated and fired even though the notifyFailure() method is not been called anywhere. Prior to that when initiating the notifySuccess(), the successCallback doesn't get fired which is present inside the authenticate method.`

**Comment by titusannadurai** [comment]
Hi,

Please find the below sample code snippet

Two Components we have used for Authentication
Component 1 - testComponent1
Component 2 - testComponent2

```
import React from "react";
import * as microsoftTeams from "@microsoft/teams-js";

class testComponent1 extends React.component {
      constructor(props) {
         super(props);
      }
      componentDidMount(){
          microsoftTeams.initialize();
          microsoftTeams.getContext((context) => {
               this.setState({
                 context: context
              });
          });
      }
      render() {
          const triggerAuthentication = () => {
               microsoftTeams.authentication.authenticate(
                    {
                        url: "sample redirect URL - reactComponent2",
                        width: 600,
                        height: 515,
                        successCallback: () => {
                           window.location.assign("redirectURL");
                        },
                        failureCallback: () => {
                           alert(`Authentication Error`);
                      }
                  }
              )
          }
          return(
             <section>
                 <button  onClick={triggerAuthentication}>Sign In</button>
             </section>
          )
      }
}

export default testComponent1;
```

```
import React from "react";
import * as microsoftTeams from "@microsoft/teams-js";

class testComponent2 extends React.component {
      constructor(props) {
         super(props);
      }
      componentDidMount(){
          microsoftTeams.initialize();
          microsoftTeams.getContext((context) => {
               this.setState({
                 context: context
              });
          });
          this.checkAuthentication();
      }

      checkAuthentication(){
         axios.get(`sample api URL`, {
         timeout: 5000
         }).then(response => {
              //Condition to check the Authentication
              if (response.data.indexOf('isAuthenticated') >= 0) {
                    microsoftTeams.authentication.notifySuccess();
              } else {
                   microsoftTeams.authentication.notifyFailure();
              }
         }).catch(error => {
              //Condition to check Auto Logoff
              if (error.message.indexOf("5000ms") >= 0) {
                  microsoftTeams.authentication.notifySuccess();
              } else {
                  microsoftTeams.authentication.notifyFailure();
              }
         })
      }
      render() {
          return(
             <section>
                  <section>Authentication</section>
             </section>
          )
      }
}

export default testComponent2;
```

#Issue 1 - As soon we the triggerAuthentication methods get fired, the failureCallback method gets executed in testComponent1.
#Issue 2 - After successful response from the api in the testComponent2, either the successCallback or the failureCallback method doesn't been called.

Kindly suggest if anything missing for further investigation.

**Comment by Meghana-MSFT** [comment]
A fix has been rolled out publicly for this issue. We tested this with on Mac with Teams JS 2.10.0 version. It is working fine at our end. Could you please check if you are still seeing the problem at your end?
