### ISSUE TITLE
Can i display configuration tab in personal Tab? 

### ISSUE THREAD

**Issue by ZipiTubul** [OfficeDev/microsoft-teams-library-js#1657]
Hey,
I've created a personal tab in teams, and I want to add some settings or configuration before the user adds the app to teams...
or maybe add this 
![Capturess](https://user-images.githubusercontent.com/50840403/226938464-6467b6c2-d415-4293-961e-ef161743377f.PNG)

how can i do that?
Thanks

**Comment by Prasad-MSFT** [comment]
@ZipiTubul - Unfortunately no. You can't display a configuration tab inside static tab. 
Ref: https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/what-are-tabs

**Comment by Prasad-MSFT** [comment]
@ZipiTubul - In personal tab, you can't add configurable tab using settings.
![image](https://user-images.githubusercontent.com/62237649/230049914-7af2164b-a4ad-4a76-b9c0-8bf5ba7dc31a.png)
