### ISSUE TITLE
Telemetry support for Shopping Apps

### ISSUE THREAD

**Issue by Shama-Bildikar** [OfficeDev/microsoft-teams-library-js#1658]
We would like to get an insight into:

How many users click on the "..." ellipsis in Outlook Mobile (to access app drawer)
How many users click on Shopping app in the app drawer
How many users click on Shopping app from NAv bar
Hoe many users have re-ordered app sequence so that Shopping app appears be default in nav bar.

**Comment by nwojod-MSFT** [comment]
Issue addressed internally.
