### ISSUE TITLE
SDK incorrectly process third-party messages from iframes with same origin as sdk current window origin

### ISSUE THREAD

**Issue by gavagava** [OfficeDev/microsoft-teams-library-js#167]
For example:
We have page loaded from **https://mydomain-ms-teams-app.com**
Code of this page looks like:
```
<html>
  <head>
    <script src="<!--path to ms-teams-sdk 1.3.7-->"></script>
   <!--some other scripts and links>
  </head>
  <body>
    <iframe id="myIframe" src="https://mydomain-ms-teams-app.com/path/to/my/component"/>
  </body>
</html>
```
Then iframe with id **myiframe** `postMessage` to main window and ms-teams-sdk try to process this message because code in `updateRelationships` function decide that this iframe is `childWindow`. In most cases it's fine, and sdk continue to work, because message doesn't  fit ms-teams-sdk format and simply ignores. But potentially it may cause problems. In our case, we get issue with EDGE-browser, when it store our iframe as `childWindow`, and then try to access its `closed` property, when iframe is out of DOM (EDGE throw exception in this case).

**Comment by gavagava** [comment]
https://codepen.io/gavagava/project/editor/DyJKbK you can fork this project and then make manifest like [this](https://drive.google.com/file/d/1VOmMm_qOYYmi7yk6ztWBdAw_uZs9cNoD/view?usp=sharing), but with your config url to debug view for CodePen project. Edge throw [exception](https://drive.google.com/file/d/1dxkasJrwq98k9hrr-Lzy8XR9S6FbA9Ef/view?usp=sharing) on this config page after call to settings.setSettings().

**Comment by Wajeed-msft** [comment]
Closing old questions from the tracking items. Please feel free to re-open.
