### ISSUE TITLE
Unable to retrieve “clientType” on web on 2.9.1 package

### ISSUE THREAD

**Issue by ktcodebite** [OfficeDev/microsoft-teams-library-js#1671]
Reporting on behalf of partner Whiteboard.chat for EDU:

Unable to retrieve “clientType”. 
[https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/app.apphostinfo?view=msteams-client-js-latest](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fjavascript%2Fapi%2F%40microsoft%2Fteams-js%2Fapp.apphostinfo%3Fview%3Dmsteams-client-js-latest&data=05%7C01%7CKiran.Thomas%40microsoft.com%7C952efe6146c44c4ccffe08db2ca57fa6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638152861691650541%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=tazDdhPO2zxzFo7vLpWfGKIb%2FgPVVRy5Gv4v%2Fm47drU%3D&reserved=0)
 
We have tried with the latest 2.9.1 package, running inside teams in browser, does not return clientType. It keeps saying undefined. I can only test this in browser because otherwise I can’t see the debug logs if I run it in the teams desktop app. Per documentation it should return “web”.

**Comment by AE-MS** [comment]
Hi @ktcodebite, thanks for reaching out about this; sorry that Whiteboard.chat for EDU is running into trouble here. I tried this myself with teamsjs 2.9.1 using the web version of Teams and I didn't have the same issue (I successfully retrieved the `clientType` property). That doesn't mean there isn't an issue, though -- just that we need to dig deeper to figure out what's going on!

Can you try enabling logging to see if we can get more detail about what values Teams is providing to the teamsjs library for the `clientType` property? Here are the instructions for enabling logging:
https://github.com/OfficeDev/microsoft-teams-library-js/wiki/TeamsJS-Logging#enabling-logging
(there are also parallel instructions for [disabling logging](https://github.com/OfficeDev/microsoft-teams-library-js/wiki/TeamsJS-Logging#disabling-logging) once we are finished).

Once logging is enabled, this is the going to be the first line to look for in the console logs:

```
teamsJs:communication:sendMessageToParentHelper Message 1 information: {actionName: 'getContext', args: Array(0)}
```

The message number might be different -- but once you see that line with `actionName: 'getContext'`, take note of the message number and look for the corresponding response, which will look like this:

```
teamsJs:communication:handleParentMessage Received a response from parent for message 1
```

(note the same message number). The next line should start with "Invoking the registered promise..." and contain the data sent by Teams back to teamsjs in response to the `getContext` call. Once you expand that line, there should be a structure in element zero and it should have all the context properties. There should be many of them (e.g., `appIconPosition`, `appLaunchId`, etc.) The one we're looking for is `hostClientType` -- mine looks like this:

```
hostClientType : "web"
```

Are you able to enable logging and look for that same response with the `hostClientType` property to see what it says in your case? Are there other context properties in that same response or are they all `undefined`? 

If you could share the `ringId` property in the response, that could also be helpful.

Thanks!

**Comment by ktcodebite** [comment]
Thank you for jumping on this @AE-MS, update from developer, apparently using this code block resolved the issue, and they are now getting the right response:

microsoftTeams.app.getContext().then((context) => {
          window.msHost = context.app.host;
          console.log("Detected clientType = ", context.app.host.clientType);
        })

Do you see any issues with the developer following this^ implementation? Otherwise, we are good to close this issue out.

**Comment by AE-MS** [comment]
> Thank you for jumping on this @AE-MS, update from developer, apparently using this code block resolved the issue, and they are now getting the right response:
> 
> microsoftTeams.app.getContext().then((context) => { window.msHost = context.app.host; console.log("Detected clientType = ", context.app.host.clientType); })
> 
> Do you see any issues with the developer following this^ implementation? Otherwise, we are good to close this issue out.

That looks okay to me.
