### ISSUE TITLE
Why is my Microsoft Teams custom app staying in the login popup window?

### ISSUE THREAD

**Issue by FE-POLY** [OfficeDev/microsoft-teams-library-js#1676]
Hi everyone,

I'm currently deploying my (React) web app in a Microsoft Teams custom app. More specifically, I'm trying to use Azure AD SSO to log my users. I'm using the `@microsoft/teams-js` package to generate a login popup window, which works just fine. But when I login inside this popup window, the logged in session in my application is opened in this popup while the main window, inside Microsoft Teams, stays on the login page. If I refresh my custom app, I'm properly logged in though.

Here's how I use the authenticate method when I click the login button :
```js
onClick={
              isDisplayedInTeams()
                ? async (): Promise<void> => {
                    try {
                      await microsoftTeams.authentication.authenticate({
                        url: "/loginUrl",
                        width: 600,
                        height: 555,
                        isExternal: true,
                      });
                    } catch (error) {
                      // eslint-disable-next-line no-console
                      console.log(
                        "Application could not connect in Teams : ",
                        error
                      );
                    }
                  }
                : (): void => {
                    window.open("/loginUrl", "_self");
                  }
            }

   ```
What am I doing wrong here ?

Note : I'm using Teams in my browser for now.

Edit : I just found this question which seems related : https://stackoverflow.com/questions/62329833/teams-auth-popup-wont-close-or-redirect-after-completing-sign-in-react
But I only call `initialize()` once... In a `useEffect` though.

**Comment by AE-MS** [comment]
Hello again @FE-POLY, welcome back! I have a clarifying question first to ensure I'm helping in the best way I can. In your post, you say:

> I'm trying to use Azure AD SSO to log my users.

...but I also see that you are using [authentication.authenticate](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/authentication?view=msteams-client-js-latest#@microsoft-teams-js-authentication-authenticate), which should not be strictly necessary if the only goal is AAD SSO.

Can you tell me more about the full scenario you're looking to enable? For example, are you only looking to get the identity token for the user to ensure they are signed in? Or are you looking to then use the token to call some other APIs on a service?

**Comment by FE-POLY** [comment]
Hello @AE-MS and thank you for your answer,

As far as I'm aware, it is only used to sign users in. Right now, in our web app, users can identify through classic login/password or several SSO solutions (Google, AAD). AAD is the only one causing problem inside Teams (ironic, isn't it ?) due to redirect mechanism.
I have seen tutorials explaining that the solution is to use `authentication.authenticate` to put the Microsoft login page inside a pop-up. And it's working just fine.
The problem seems to be that my main page (inside Teams) isn't receiving the information back. If I modify my code like this :
```js
onClick={
              isDisplayedInTeams()
                ? async (): Promise<void> => {
                    try {
                      await microsoftTeams.authentication
                        .authenticate({
                          url: "/loginUrl",
                          width: 600,
                          height: 555,
                          isExternal: false,
                        })
                        .then((result) => {
                          // eslint-disable-next-line no-console
                          console.log("Application connected : ", result);
                          history.go(0);
                          microsoftTeams.authentication.notifySuccess();
                        })
                        .catch((error) => {
                          // eslint-disable-next-line no-console
                          console.error(
                            "Application could not connect in Teams : ",
                            error
                          );
                          history.go(0);
                          microsoftTeams.authentication.notifyFailure();
                        });
                    } catch (error) {
                      // eslint-disable-next-line no-console
                      console.error(
                        "Application could not connect in Teams : ",
                        error
                      );
                    }
                  }
                : (): void => {
                    window.open("/loginUrl", "_self");
                  }
            }
```
I never get the part inside the `then` (no console log, no refresh). But when I close the popup window, even though the AAD authentication process is complete (I'm logged in inside the popup window), it triggers the `catch` : I get both the corresponding console log and the page refresh.

**Comment by AE-MS** [comment]
Thanks for the extra details. Based on what you said, I think I have good news for you: if all you care about is ensuring users are signed-in, you don't need to do anything (except in one specific case I'll mention below). The fact that the user is using Teams indicates that they are already signed in to AAD and no further authentication action needs to be taken by your app.

If you wanted to get information about them, since they are signed in, you can call [app.getContext](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/app?view=msteams-client-js-latest#@microsoft-teams-js-app-getcontext), then look at the [user property](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/app.context?view=msteams-client-js-latest#@microsoft-teams-js-app-context-user) on the [resulting interface](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/app.userinfo?view=msteams-client-js-latest#properties) to get the users name, tenant, etc.

The only case in which a user could be using your app inside of Teams and not signed in is if you are writing a meeting app that supports anonymously-joined participants -- if this is your situation, we can revisit the "how to sign in" question. 😁

Now if you care about more than just having the user signed in, e.g., you want to get a token to call a backend-service/middle-tier you are running, that's also a different situation that I can help with.

Does that help in your situation?

**Comment by FE-POLY** [comment]
Once again, thank you for your answer. So if I understand correctly, I can use app context to get the same information that I get with `authentication.authenticate` or with the Azure AD SSO when my app is not inside Teams ?
I would still need to adapt my auth process, right ?

**Comment by AE-MS** [comment]
Assuming that by "the same information" you mean one of the properties available in the [UserInfo interface](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/app.userinfo?view=msteams-client-js-latest), then yes.

If you are expecting some other information than what you see documented in that interface (e.g., an access token), you may need to use one of the other authentication methods (I can help identify which one).

Do you see the information you want in the [UserInfo interface](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/app.userinfo?view=msteams-client-js-latest)?

**Comment by FE-POLY** [comment]
Thank you for your answer @AE-MS . When I check the UserInfo interface, most fields are marked as "this value should be used only as a hint as to who the user is and never as proof of identity", so it doesn't look recommended to use them.

There's the `getAuthToken` method but it seems like it would require changes to our auth process.

`authentication.authenticate` is perfect for us really, I just don't get why I don't receive any confirmation when the authentication is completed inside the popup. I thought it was handled automatically, but maybe this is something that I should add somewhere ? Is the use of another library, like [@azure/msal-react](https://www.npmjs.com/package/@azure/msal-react), required to make this work ?

**Comment by AE-MS** [comment]
The comment to which you refer is not intended to suggest you should not use them. It is specifically indicating that you should not use them for authorization purposes (e.g., you shouldn't look at the upn property, compare it to some internal property, and say "Oh user example@example.com is listed as having access to this, therefore this person should have access to this.") If you need authorization, that's what access tokens should be used for (hence my question from earlier in the thread). I will update the documentation to make this clearer.

Again, if all you want is to ensure the user is logged in, then you don't need to do anything -- the user must already be logged into Teams using AAD to access your app in the first place. It doesn't seem like a great user experience to unnecessarily require your users to unnecessarily sign-in another time.

Can you say more about what benefit/data you're looking to get by calling `authentication.authenticate`?

**Comment by FE-POLY** [comment]
Thank you again for your answer @AE-MS .
The benefit in calling `authentication.authenticate()` is that it preserves our auth flow as it is : 
- user clicks on a login button
- users is redirected toward another url of our domain (1), that redirects toward https://login.microsoftonline.com/
- when user is logged in, he's finally redirected to a callback url of our domain (2) which handles all the auth process (logging in or creating an account) and finally redirects toward our home page

Right now, using `authentication.authenticate`, a popup window is opened with the url 1 and user can authenticate without any issue. But the missing part is that the redirect toward the callback url 2 should be done back in Teams. It's especially problematic for the desktop Teams application since being logged inside the popup (which is what happens right now) doesn't mean being logged inside the application.

Is there any way to achieve this ?

**Comment by AE-MS** [comment]
Thanks for the extra details -- I'm still not 100% sure I understand the goal here. Maybe if I ask a few more questions it will help me understand to ensure I'm giving you the best advice.

When your app is running in Teams, the user is already logged in and already has an account. There would not be any need to redirect them through login.microsoftonline.com or handle any auth process since Teams has already that on behalf of any app it hosts. When you say that the benefit is that it "preserves our auth flow" -- do you mean that the benefit is that you're able to avoid changing any of your code even though you'll be putting users through the unnecessary auth and login experience (since they are already logged in)?

**Comment by ChetanSharma-msft** [comment]
Hello @FE-POLY - Hope you are doing well!!
Could you please provide the further details asked above?
