### ISSUE TITLE
Microsoft Teams JS SDK initialization timed out.

### ISSUE THREAD

**Issue by RishavNice** [OfficeDev/microsoft-teams-library-js#1681]
We are facing an issue in the SDK - 

**Version** - "@microsoft/teams-js": "2.9.1",

**Issue** - SDK initialization timed out.

**Troubleshoot** - SSO works fine in the browser (Chrome) case. But when we run the same manifest, the same app in the MS Teams Desktop application then after SSO when it returns back to the application from IDP and re-initializes the library it fails saying that the SDK initialization timed out.

It's weird that **the issue only happens in the desktop application but not when we run inside the web Chrome browser.**

I saw multiple issues logged in Github pertaining to this, but I did not get any reliable solution.

[LINK - 1](https://github.com/OfficeDev/microsoft-teams-library-js/issues/1181
)
[LINK - 2](https://learn.microsoft.com/en-us/answers/questions/1190790/microsoftteams-js-sdk-initialization-timed-out)

**Screenshot** - 
<img width="889" alt="SDK_Timeout" src="https://user-images.githubusercontent.com/117259142/229046524-c1ff4cce-7fb8-432f-b00f-d77cc6de5abb.png">

Please help us out.

**Comment by sayali-MSFT** [comment]
@RishavNice - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by RishavNice** [comment]
Hi @sayali-MSFT 

We can still face the issue. We are using React JS. As discussed previously, it works fine in browser Teams but fails in the case of Desktop App Teams. I believe if the code is the same how can it partially work on one platform and fail on another?

**Comment by RishavNice** [comment]
The scenario is - 

- We open the popup using Authentication.authenticate method
- We load our application login page (server side hosted) and enter the user ID. 
- After entering the user ID the login page redirects the user to related IDP (MSFT) in this case.
- Once we go to the IDP we select the MSFT user which is mapped to our database.
- Once MSFT validates it sends an code and success back to our redirect URL we configured in Azure.
- But once it reaches the application, it tries to re initialize the SDK which then gets timed out due to some reason!

This only happens in Teams Desktop App not in browser application.

**Comment by sayali-MSFT** [comment]
@RishavNice -Thanks for providing the information, we will check it from our end and get back to you.

**Comment by andreidutu** [comment]
> The scenario is -
> 
> * We open the popup using Authentication.authenticate method
> * We load our application login page (server side hosted) and enter the user ID.
> * After entering the user ID the login page redirects the user to related IDP (MSFT) in this case.
> * Once we go to the IDP we select the MSFT user which is mapped to our database.
> * Once MSFT validates it sends an code and success back to our redirect URL we configured in Azure.
> * But once it reaches the application, it tries to re initialize the SDK which then gets timed out due to some reason!
> 
> This only happens in Teams Desktop App not in browser application.

I encounter exactly the same error using 2.9.1 microsoft/teams-js. 
As a workaround i do this:
1. Attach a new button on the page with event window.close.
2. Save the code ( from the PKCE flow) in localStorage: localStorage.setItem("code", codeFromQueryParams)
3. When that button is pressed, an error is caught in catch of the authenthicate method
4. In that catch i try to get value of code, then remove it from local storage and aqcuire a token with that code.

On web teams (teams.microsoft.com) works perfectly with normal flow, but on desktop this is the workaround i could find.

@sayali-MSFT  Please let us know how is this going!

**Comment by RishavNice** [comment]
We have troubleshooted the MSFT JS SDK from our side, here is our overview - 

There is a function - `initializeCommunication`
Inside that function there is an internal try statement - 
 ```
 try {
        // Send the initialized message to any origin, because at this point we most likely don't know the origin
        // of the parent window, and this message contains no data that could pose a security risk.
        Communication.parentOrigin = '*';
        return sendMessageToParentAsync('initialize', [
            version,
            latestRuntimeApiVersion,
        ]).then(function (_a) {
            var context = _a[0], clientType = _a[1], runtimeConfig = _a[2], clientSupportedSDKVersion = _a[3];
            return { context: context, clientType: clientType, runtimeConfig: runtimeConfig, clientSupportedSDKVersion: clientSupportedSDKVersion };
        });
    }
```

The issue is the code snipper never goes inside the `.then` function.
As it never goes inside `.then` so it never returns the expected output. This happens only in case of desktop client and not in case of web app. I think debugging in this direction would help. Thanks ! @sayali-MSFT

**Comment by sayali-MSFT** [comment]
@RishavNice - We are checking with the internal team, we will let you know once we get any update.

**Comment by RishavNice** [comment]
@sayali-MSFT  Any updates?

**Comment by sayali-MSFT** [comment]
@RishavNice - Apologies for the delays, we are informing to the engineering team, and they will look into this. We will let you know once we get any update.

**Comment by SethuRamanAlfanar** [comment]
Same issue I am Also Facing 
![Screenshot 2023-04-05 160038](https://user-images.githubusercontent.com/121424128/230055609-329972f8-69a3-4f59-9212-840932f0da4a.png)

**Comment by nwojod-MSFT** [comment]
@RishavNice thanks for the information you provided. Could you explain what you meant by, "server side hosted"? Are you referring to a server-side rendering tool? Additionally, could you provide more details on the specific scenario you are trying to achieve and why initialization is being called the second time? This additional information could help us better understand the problem as we are unable to reproduce the issue you described. Thanks

**Comment by RishavNice** [comment]
@nwojod-MSFT 
No, we are not talking about server-side rendering tools. It's just that the app redirects me to a web page hosted in a different domain for login purposes. We don't have a login page embedded in our application but we redirect our user to a different webpage for login and then we bring tokens from that page to our application.

Secondly, initialization is being called for the second time because once the user enters the user name on the login page they leave our application domain and get redirected toward the IDP (Azure in this case.) After successful redirection when they are authenticated from the IDP they are redirected back to our application by the return URL we have configured on the IDP side. Once they come back to the application, to close the authentication popup we need to initialize the library again inside the popup to utilize the SDK methods. So when we try to initialize the library it gets timed out.

I hope this makes sense.

**Comment by RishavNice** [comment]
@nwojod-MSFT  @sayali-MSFT Any updates?

**Comment by sayali-MSFT** [comment]
@RishavNice -Engineering team is looking into it. We will inform you once we get any update.

**Comment by RishavNice** [comment]
@sayali-MSFT ?

**Comment by nwojod-MSFT** [comment]
@RishavNice apologies for the delay in my response; I was out of the office. Thank you for providing additional information about the flow and the objective you're trying to achieve. Our team is still investigating the issue to determine its root cause, and we're currently attempting to reproduce the issue. I'll provide an update once we're able to resolve it. Thanks

**Comment by anmaur** [comment]
Hi @RishavNice, Is the hostname (aka domain) from where you start authentication.authenticate (i.e. the hostname of URL passed to this API) is different from the hostname of the return URL (which IDP redirects to)? If yes, Pls try using the same domain for both the URLs

**Comment by RishavNice** [comment]
Hi @anmaur 

The hostname (aka domain) from where I start authentication.authenticate is - `https://cxone.staging.niceincontact.com/auth/authorize?abc`


The hostname of the return URL is -` https://cxone.staging.niceincontact.com/auth/authorize?xyz`

I believe both the URL's have the same domain except for the query params appended which is obviously different in both the cases

**Comment by anmaur** [comment]
Hi @RishavNice, Thanks for the information. I am unable to repro this from my end and would need more information if :

- What is the Teams desktop version you are using?
- Is your App having the same hostname as the authentication url: https://cxone.staging.niceincontact.com/auth/authorize?abc ?

**Comment by RishavNice** [comment]
> * s your App having the same hostname as the authentication url:

If you're unable to get the issue while multiple other people are getting the same issue, would you mind sharing the complete code sample using JS.
Is your App having the same hostname as the authentication url: YES.
Teams Desktop Application Version - 

Windows OS - 11 / Teams Version - 1.6.00.6754 /  Teams JS Sdk Version - 2.9.1;

**Comment by RishavNice** [comment]
Fixed in recent version of MSFT JS SDK. Closing now.
