### ISSUE TITLE
Where is the full name of an add in used as described in the manifest

### ISSUE THREAD

**Issue by catmanjan** [OfficeDev/microsoft-teams-library-js#1682]
Every manifest has the following:

```
  "name": {
    "short": "blah",
    "full": "full blah"
  },
```

Where is name full actually used? As far as we can tell it isn't

**Comment by Meghana-MSFT** [comment]
@catmanjan - We will check this internally and get back to you.

**Comment by catmanjan** [comment]
@Meghana-MSFT any update?

**Comment by Meghana-MSFT** [comment]
@catmanjan - Apologies for the delay. We are following up with the engineering team for an update. We will keep you posted on this issue. Thank you for your understanding.

**Comment by sim4r4** [comment]
Hello, you can take a look at the raw Manifest Schema ([link here](https://developer.microsoft.com/json-schemas/teams/v1.16/MicrosoftTeams.schema.json)), and you can find the description to the attributes you are looking for:

`
"name": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "short": {
          "type": "string",
          "description": "A short display name for the app.",
          "maxLength": 30
        },
        "full": {
          "type": "string",
          "description": "The full name of the app, used if the full app name exceeds 30 characters.",
          "maxLength": 100
        }
      },
      "required": [
        "short",
        "full"
      ]
    },
`
![image](https://user-images.githubusercontent.com/105516488/232900450-1baf57f3-a32c-4997-8279-a6a6136c70ea.png)

I am getting in touch with the Store team and checking in which situations we are presenting the `name.short` vs `name.full` attribute. I hope I can get an answer within the next day. Thanks!

**Comment by ChetanSharma-msft** [comment]
Hello @catmanjan - Please confirm whether your query has resolved with above suggestions or still need any further assistance?

**Comment by catmanjan** [comment]
@ChetanSharma-msft no the schema doesn't actually say where short/full name are used in practice

**Comment by Meghana-MSFT** [comment]
@sim4r4 - Could you please let us know if you got a chance to get in touch with the Store team and check in which situations, we are using the name.short vs name.full attribute. Thanks!

**Comment by Meghana-MSFT** [comment]
@catmanjan - We got the below update from engineering team -

> There is no place the full name is used, and it is going to be deprecated.
