### ISSUE TITLE
Could not find the Task "Start Teams App Locally"

### ISSUE THREAD

**Issue by Baadshah769** [OfficeDev/microsoft-teams-library-js#1685]
Hello Team,

I'm new to the developing and Teams Toolkit too. I tried to follow learn path and different to start my Journey with the Teams App Development but I'm unable to debug the app and gets the error - Could not find the Task "Start Teams App Locally". Please need your help with it.

**Comment by Nivedipa-MSFT** [comment]
@Baadshah769 - Could you please refer below documents for Creating Teams app using Teams Toolkit.
1. https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/create-new-project?pivots=visual-studio-code
2. https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-blazorupdate?tabs=vs

**Comment by Baadshah769** [comment]
Hello Team,

It was due to the error with the Node.js installation in the Visual Studio. It's fixed now after reinstallation and tried in another laptop/device too. 
Thank you for the help.
