### ISSUE TITLE
Teams add in icon is missing from admin page

### ISSUE THREAD

**Issue by catmanjan** [OfficeDev/microsoft-teams-library-js#1690]
For some reason the teams app icon is missing from office 365 admin

The icon appears as expected to end users, its only the admin page that has the issue

![image](https://user-images.githubusercontent.com/137350/229963078-eb4529be-3174-4e30-b222-c71a8da1051b.png)

https://admin.microsoft.com/Adminportal/Home#/Settings/IntegratedApps

**Comment by Meghana-MSFT** [comment]
@catmanjan - We are also able to repro this issue, we will check this internally and get back to you. Thank you.

**Comment by catmanjan** [comment]
@Meghana-MSFT any update?

**Comment by Meghana-MSFT** [comment]
@catmanjan - Apologies for the delay. We are following up with the engineering team for an update. We will keep you posted on this issue. Thank you for your understanding.

**Comment by catmanjan** [comment]
Looks like this has been fixed
