### ISSUE TITLE
DeepLink not being handled properly by app.openLink for a channel webUrl if user is not a member of a team

### ISSUE THREAD

**Issue by sonam-serchan** [OfficeDev/microsoft-teams-library-js#1694]
We have a console app where we deep link back to team/channel using `app.openLink(webUrl)`

Scenario:
### User is a member of the team
- For both teams' and channels' webUrl, `microsoftTeams.app.openLink(webUrL)` is working fine. It redirects to the respective team or channel ✅ 

### User is not a member of the team
- For teams' webUrl, `microsoftTeams.app.openLink(webUrL)` asks user to join the team as expected ✅ 
- However for channels' webUrl, `microsoftTeams.app.openLink(webUrL)` doesn't ask user to join the team and instead redirects to the first team in microsoft teams 🙁

Upon investigation, I found that the webUrl of a channel looks like this - 
`"webUrl": "https://teams.microsoft.com/l/channel/19%3A204ef5505f1083440-0178d919%40thread.tacv2/mychannel?groupId=034343f-9098-sf45-45go-897230fgfg3&tenantId=f487fjk3-fg343-oiu889-34df-dsf343400&allowXTenantAccess=False",`

Not sure what `allowXTenantAccess=False` does!

After playing for a while, I removed `allowXTenantAccess=False` from query param, and now `microsoftTeams.app.openLink(newWebUrL)` asks me to join the team if I am not a member of the team ✅ 

Could you please check if this is the right behaviour?

**Comment by Prasad-MSFT** [comment]
@sonam-serchan - Thanks for raising the issue. We will check it from our end and update you.

**Comment by Prasad-MSFT** [comment]
@sonam-serchan - We tried to repro this issue and on appending `&allowXTenantAccess=False` as you mentioned it doesn't ask user to join the team and instead redirects to the first team.


However, when we got the channel link as below, we observed that for channels' webUrl, microsoftTeams.app.openLink(webUrL) it asks user to join the team  if user is not a member of the team.
`https://teams.microsoft.com/l/channel/19%3a41a1a7fdb51a49ff9a0d8e65e6af4635%40thread.tacv2/Channel101?groupId=6503889f-0dcf-4345-9b94-68e07e1cd4d5&tenantId=36a708ef-700d-4d60-9de0-0a5f7b7693df`

![image](https://user-images.githubusercontent.com/62237649/230310443-42043645-5f3f-409b-b268-45535f3e596c.png)

**Comment by sonam-serchan** [comment]
@Prasad-MSFT Yes, that's because it doesn't have `&allowXTenantAccess=False` when you get link from there.

However, I am calling this endpoint `https://graph.microsoft.com/v1.0/teams/${teamsId}/channels` to get list of channels and in it's response the `webUrl` for all channels have `&allowXTenantAccess=False` at the end by default. That is why I get that issue.

Could you please check that?

**Comment by Prasad-MSFT** [comment]
Right @sonam-serchan - When we query using Graph API, we get webUrl in below format
`"webUrl": "https://teams.microsoft.com/l/channel/19%3a41a1a7fdb51a49ff9a0d8e65e6af4635%40thread.tacv2/Channel101?groupId=6503889f-0dcf-4345-9b94-68e07e1cd4d5&tenantId=36a708ef-700d-4d60-9de0-0a5f7b7693df&allowXTenantAccess=False"`

However, this is not the right deep link format to use. We should use the format as mentioned in documentation.
https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links

**Comment by ChetanSharma-msft** [comment]
Hello @sonam-serchan - Hope your query has resolved.
Please let us know if you need any further assistance here.
