### ISSUE TITLE
App in Teams mobile  can‘t open the camera or photo album ;error code 1000 

### ISSUE THREAD

**Issue by yuhongwei380** [OfficeDev/microsoft-teams-library-js#1702]
Hello, we published the app in Teams, but the app opened in Mobile Teams cannot open the camera or photo album. Our third-party application development engineer helped us check the reason, saying that the SDK reported an error, and the error code was 1000; Tried the 1.8version and 2.0version libraries, but still doesn't work. How to solve it?

**Comment by nwojod-MSFT** [comment]
@yuhongwei380 thanks for reporting this issue. Please can you share some code sample on how you are trying to call this so that we can investigate this issue. Thanks

**Comment by yuhongwei380** [comment]
![image](https://user-images.githubusercontent.com/44333391/230697583-7d34cdb2-5630-4a1d-bd8a-75b1f988be02.png)
This is our   third-party application development engineer given to me  about the code ; then it will  met this problem. 
![image](https://user-images.githubusercontent.com/44333391/230697611-8c1c865a-f479-46bc-92cf-b00a5e9c88c9.png)

**Comment by Nivedipa-MSFT** [comment]
@yuhongwei380 - We have tested this using [tab-product-inspection](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-product-inspection/csharp) sample.
For Teams library version 1.8 the media.scanBarCode is not working but for 1.10 and 2.0.0 its working fine at our end.

TeamsJs 1.8

https://user-images.githubusercontent.com/92150070/230888352-f9ae53e9-ad05-49f7-b771-59b1daf51d89.mp4



TeamsJs 1.10

https://user-images.githubusercontent.com/92150070/230888384-b9197fb1-641d-4494-8fb0-212c3b099e16.mp4



TeamsJs 2.0.0

https://user-images.githubusercontent.com/92150070/230888411-675755aa-18ae-4ae4-ab13-a1984293dffb.mp4


We have raised a bug for the TeamsJs version 1.8 
We will let you know once we get any updates on it.

**Comment by yuhongwei380** [comment]
Thank you very much, I have reported this result to our third-party application engineers, and they will test and verify teamsjs 2.0 this week. I will also synchronize the subsequent results to this page

**Comment by yuhongwei380** [comment]
Our third-party development engineer switched weapons and tested the version of teamsjs 2.3; but another failure occurred. You can see the picture for details
![98e4249c8d1516ae7485874b345b5929_](https://user-images.githubusercontent.com/44333391/232264004-15234d24-16a5-4112-b4c6-422b7ba29911.jpg)

**Comment by yuhongwei380** [comment]
> @yuhongwei380 - We have tested this using [tab-product-inspection](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-product-inspection/csharp) sample. For Teams library version 1.8 the media.scanBarCode is not working but for 1.10 and 2.0.0 its working fine at our end.
> 
> TeamsJs 1.8
> 
> TeamsJs 1.10
> 
> TeamsJs 2.0.0
> 
> We have raised a bug for the TeamsJs version 1.8 We will let you know once we get any updates on it.

Our third-party development engineer switched weapons and tested the version of teamsjs 2.3; but another failure occurred. You can see the picture for details；
![image](https://user-images.githubusercontent.com/44333391/232391047-611f4998-9a5a-48d8-b09f-dbfb399026fe.png)

**Comment by anmaur** [comment]
@yuhongwei380 , Thanks for trying the version teamsJs 2.3. Could you pls try using `media.scanBarCode` to access the barCode feature?

**Comment by yuhongwei380** [comment]
> @yuhongwei380, Thanks for trying the version teamsJs 2.3. Could you pls try using `media.scanBarCode` to access the barCode feature?

It can't work !See the vedio； We try the scancode； Scan the invoice in the video, the corresponding function is media.scanBarCode, it still doesn’t take effect

https://user-images.githubusercontent.com/44333391/232647155-e6cfc962-0d2d-43eb-86a2-435ac5cd61de.mp4

**Comment by erinha** [comment]
Hi @yuhongwei380, thanks for your reply! I'm sorry this still isn't working for you.

Can you please share if you're receiving an error using `media.scanBarCode` with teams-js@2.3.0? I appreciate you attaching the video, but unfortunately I can't read the text on the screen so it's difficult to understand what's going on. 

Also I wanted to check and confirm that you've included the `media` permission in the app manifest? More information is available on this page: [Integrate QR or barcode scanner capability - Teams | Microsoft Learn](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/qr-barcode-scanner-capability#update-manifest).

Regarding the original issue with `scanBarCode` not working in teams-js version 1.8.0 - that is expected as the `media.scanBarCode` API was originally introduced in version 1.9.0.

Thank you.

**Comment by yuhongwei380** [comment]
> Hi @yuhongwei380, thanks for your reply! I'm sorry this still isn't working for you.
> 
> Can you please share if you're receiving an error using `media.scanBarCode` with teams-js@2.3.0? I appreciate you attaching the video, but unfortunately I can't read the text on the screen so it's difficult to understand what's going on.
> 
> Also I wanted to check and confirm that you've included the `media` permission in the app manifest? More information is available on this page: [Integrate QR or barcode scanner capability - Teams | Microsoft Learn](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/qr-barcode-scanner-capability#update-manifest).
> 
> Regarding the original issue with `scanBarCode` not working in teams-js version 1.8.0 - that is expected as the `media.scanBarCode` API was originally introduced in version 1.9.0.
> 
> Thank you.

anmaur  said  i need to given the  result by using media.scanBarCode  ;this  vedio  contain the use of media.scanBarCode( in the vedio，the function name is ‘ 扫描发票 ’)  ；So  that is we need to given to you  by the result  of trying the `media.scanBarCode`  .  Unfortunataly,  that does not work .  I need more help ,Thank you !

**Comment by erinha** [comment]
> anmaur said i need to given the result by using `media.scanBarCode` ;this vedio contain the use of media.scanBarCode( in the vedio，the function name is `扫描发票` . When I use the fuction `扫描发票`，it crashed so that I can't open my camera . That is we need to given to you by the result of trying the `media.scanBarCode` . Unfortunataly, that does not work . I need more help ,Thank you !

Hi @yuhongwei380, 

I'm sorry you are still running into this problem. We are doing some testing with teams-js@2.3.0 on our end and will get back to you in 24 hours. 

Thank you.

**Comment by nwojod-MSFT** [comment]
@yuhongwei380 apologies for the delay response. We are still investigating this issue. We should have an update for you next week. Thanks.

**Comment by yuhongwei380** [comment]
> @yuhongwei380 apologies for the delay response. We are still investigating this issue. We should have an update for you next week. Thanks.

any result or response?

**Comment by Nivedipa-MSFT** [comment]
@yuhongwei380, @nwojod-MSFT - We have tested this using [tab-product-inspection](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-product-inspection/csharp) sample.
For Teams library version 2.3.0 and 2.10.1 the media.scanBarCode is working fine at our end.
We have tested this on Android 12.


https://user-images.githubusercontent.com/92150070/234262522-8a1ab808-488a-4f9f-909a-cf5067ecd0f7.mp4

**Comment by anmaur** [comment]
Hi @yuhongwei380, Could you pls confirm if your app manifest has the right device permission set: "media"?  More information is available on this page: [Integrate QR or barcode scanner capability - Teams | Microsoft Learn](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/qr-barcode-scanner-capability#update-manifest).

**Comment by yuhongwei380** [comment]
![c5ccbce52dc76f727b07d47c432601e](https://user-images.githubusercontent.com/44333391/234503165-f6a13118-f344-4762-a7c5-e50802449aa0.png)
After checking by our third-party engineers, the relevant permissions are currently set. This issue has been resolved thanks a lot!
Thank you very much for your support and help!

**Comment by yuhongwei380** [comment]
> Hi @yuhongwei380, Could you pls confirm if your app manifest has the right device permission set: "media"? More information is available on this page: [Integrate QR or barcode scanner capability - Teams | Microsoft Learn](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/qr-barcode-scanner-capability#update-manifest).

After your tips, the three-party engineers modified the code, and the problem has been solved, thank you very much!

**Comment by Nivedipa-MSFT** [comment]
@yuhongwei380 - Glad to hear that your issue is resolved. We are closing this issue for now. Please free to reopen if required.
