### ISSUE TITLE
`context.page.frameContext` returns empty in Task Module on IOS

### ISSUE THREAD

**Issue by KennethBWSong** [OfficeDev/microsoft-teams-library-js#1707]
Related issue: https://github.com/OfficeDev/TeamsFx/issues/8284

We found that we will get empty with following code in Task Module on IOS, but get `Task` on Desktop:
```
app.getContext().then((context) => {
  alert(`${context.page.frameContext}`);
});
```

**Comment by sayali-MSFT** [comment]
@KennethBWSong - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by kmhigashioka** [comment]
@sayali-MSFT thanks for looking into it! Do you have an ETA on when this will be fixed? I'm afraid our app heavily relies on this and will be totally unusable on ios platform.

**Comment by sayali-MSFT** [comment]
@kmhigashioka - Currently we don’t have ETA or Update on this thread. We will let you know once we have any updates on it. Thanks.

**Comment by ali-ms** [comment]
Hi @KennethBWSong and @kmhigashioka , can we know which iOS and Teams version did your team see the issue on?

**Comment by kmhigashioka** [comment]
Hello @ali-ms , 
iOS version: 16.3.1
Teams client: Version 5.5.2

**Comment by ali-ms** [comment]
Thanks @kmhigashioka. Will look into it.

**Comment by karlrez** [comment]
Hi, I am as well running into the same issue, look forward to hear of any updates

**Comment by sayali-MSFT** [comment]
Sorry for delay in response!!
We are actively checking the status of bug with engineering team and let you know the updates, if we have any.

**Comment by ChetanSharma-msft** [comment]
Linking similar issue: https://github.com/OfficeDev/microsoft-teams-library-js/issues/1639

**Comment by sayali-MSFT** [comment]
@[lts-1234567890](https://github.com/lts-1234567890)- Engineering team is working on the bug fix. We will keep you posted if there are any updates.

**Comment by sayali-MSFT** [comment]
This bug has been fixed now. We have tested this on Microsoft Teams version 5.13.0 and IOS version 16.5.1(c)
Could you please update the Teams version and confirm this?

**Comment by ThomasPe** [comment]
all the issues pointing to this are still open :-(

**Comment by ChetanSharma-msft** [comment]
Hello Everyone - We are actively checking the status of bug fixes with engineering team and let you know the updates.

**Comment by Dinesh-MSFT** [comment]
This issue has been fixed. I tested this in iOS 17.4.1 and Teams Version 6.6.0. Could you please check and confirm.
