### ISSUE TITLE
SDK doesn't work on the server side

### ISSUE THREAD

**Issue by otyunin** [OfficeDev/microsoft-teams-library-js#1708]
Hi Team! 

I'm trying to run this code:

```
await app.initialize();
const context = await app.getContext();
```

However, I see the error `The library has not yet been initialized`.

Do you support running the SDK with Node.js? I had thrown an error that the window was not defined before version 2.10 was released.

**Comment by TrevorJoelHarris** [comment]
Hi @otyunin, I'm sorry you are running into a problem here. Could you try surrounding the call to app.getContext in a try/catch and see if that fixes your problem? getContext can't possibly return a real value in Node (since your app isn't hosted in one of the app hosts). I'll see if we can make this a smoother experience for developers, but in the shorter term please let us know if the try/catch unblocks you.

**Comment by sayali-MSFT** [comment]
@otyunin - Could you please confirm if your issue has resolved with above suggestion or still looking for any help?

**Comment by noahdarveau-MSFT** [comment]
Hi @otyunin, can you tell us a bit more about what you're trying to accomplish? Are you expecting those calls to actually run or just compile for rendering purposes?

**Comment by erinha** [comment]
Hi @otyunin, thanks for the reply! 

Let me try to address your comments in two parts. 

First, the teams-js library is not designed to run on a server and won't _run_ in Node.js. We do allow server side rendering of apps that reference teams-js on a server, but that is only for rendering, not for running them. The teams-js library requires that it be running within the Teams client as the APIs require communication with the Teams client to function. 

Second, I'd like to revisit the problems you encountered trying to run teams-js in the front-end app. Can you please share more info about the teams-js API calls you're making in the two scenarios you mentioned - task modules and authentication? When you say you make a call to `getAuthToken`, are you referring to the `authentication.getAuthToken` teams-js API? Can you also please share which version of teams-js you're using? I think I saw you mention getting an error prior to 2.10.

Thanks.

**Comment by otyunin** [comment]
Hi @erinha,

Yes, I've used `authentication.getAuthToken`.

Do you have a piece of advice on how I can ensure that the auth link is opened from within Microsoft Teams by the same person who generated this link? Using teams-js on the client side isn't secure

**Comment by erinha** [comment]
Hi @otyunin,

There are several documentation articles about how to securely use authentication with teams-js on the client side, depending on your scenario (e.g., if you're authenticating a user signed into Teams client or if you're authenticating the user using third-party OAuth Identity Providers). 

Overview: [Authenticating app users - Teams | Microsoft Learn](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/authentication)

The single sign-on (SSO) flow of authenticating a user signed into Teams uses `authentication.getAuthToken()` API in teams-js and this article explains how to do this in your app, including best practices to keep it secure: [Overview to authentication for tabs using SSO in Teams with Azure AD - Teams | Microsoft Learn](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-overview)

Does this help address your concerns? If not, can you please share more details about the specific scenario you're trying to enable?

Thanks.
