### ISSUE TITLE
Microsoft Teams task modules can't be closed on iOS

### ISSUE THREAD

**Issue by LukasNespor** [OfficeDev/microsoft-teams-library-js#1710]
We have upgraded the ``@microsoft/teams-js`` library to version 2.10.0 and experiencing an issue with closing dialogs on iOS mobile devices. Calling ``dialog.url.submit()`` does not close the dialog. It works correctly on the web and desktop clients.

Teams client: 5.6.77.2023062801/0403
I have created simple app to reproduce the issue https://github.com/LukasNespor/TeamsDialogTest

**Comment by sayali-MSFT** [comment]
@LukasNespor -Previously, we have tested this issue with the TeamsJS Version 2.8.0 and it is working fine from our end.

iOS Teams app build: 5.2.77.2023023901/0210 (General)
@microsoft/teams-js 2.8.0
IOS version - 16.3
Issue Link- https://github.com/OfficeDev/microsoft-teams-library-js/issues/1494#issuecomment-1434566876

Meanwhile, we are checking with the latest 2.10.0 version with the given repo and get back to you.

**Comment by sayali-MSFT** [comment]
@LukasNespor - We are able to repro that issue, we have raised bug for the same. We will inform you once we get any update.
iOS Teams app build: 5.5.77.2023052302/0315 (General)
@microsoft/teams-js 2.8.0 and 2.10.0
IOS version - 16.4.1

**Comment by AE-MS** [comment]
A fix has been checked into Teams iOS for this issue. A full public rollout of the build of Teams iOS with the fix should be available by May 25th. I will report back here around that time to confirm the full rollout and the version number of Teams iOS with the fix.

**Comment by sayali-MSFT** [comment]
@LukasNespor -Issue is resolved.
@microsoft/teams-js 2.8.0 and 2.10.0
IOS Version-16.5
Teams version-5.9.1
Could you please check it once and confirm the same?

https://github.com/OfficeDev/microsoft-teams-library-js/assets/93527375/a0e30b95-2b76-4a93-b6a4-13da0d8f40aa

**Comment by LukasNespor** [comment]
It is working fine. Thanks for the fix!

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
