### ISSUE TITLE
Websites embedded as Teams tabs do not apply the :visited attribute to visited links

### ISSUE THREAD

**Issue by catmanjan** [OfficeDev/microsoft-teams-library-js#1721]
We have a Teams tab which is basically an embedded website.

When accessing the website through the browser, links that the user has already visited appear as purple (this is a standard feature of browsers and I shouldn't need to explain further)

However, it seems that the Teams tab has no knowledge of which links the user has clicked.

This really sucks for usability because users can't tell what they've already seen.

**Comment by Nivedipa-MSFT** [comment]
@catmanjan - Thanks for reporting your issue. 
Currently this feature is not supported. Could you please raise a feature request here:[Microsoft Teams Community](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472)

**Comment by Nivedipa-MSFT** [comment]
@catmanjan - We are closing this issue now. Please feel free to reopen if required.
