### ISSUE TITLE
authenticate.notifySuccess does not trigger successCallback

### ISSUE THREAD

**Issue by JSteunou** [OfficeDev/microsoft-teams-library-js#173]
I'm within a certain use case #171 

The user is in a Teams channel, clicking on a link shared by a tab app. It opens the app for the user and the user needs to do one action before starting. That action uses `authenticate` to open a popup to another domain. At the end of the action the user is redirect to a page that just does 

```js
microsoftTeams.initialize()
// wait a little because initialize is async #172
await new Promise(resolve => setTimeout(resolve, 50))
microsoftTeams.authentication.notifySuccess({some: 'data'})
```

but the parent `successCallback` is never called.

I had to use `window.close()` on the popup  + `failureCallback` but that is hackish and feels bad :( 

Any advice?

**Comment by Wajeed-msft** [comment]
Is your start page ( `authenticate` call) and end page (`notifySuccess` call) in the same domain?

**Comment by JSteunou** [comment]
Aaah you are right they are not on the same subdomain. We splitted some services per subdomain

**Comment by JSteunou** [comment]
In fact no, it could have been, but after it is the same domain entirely

**Comment by Wajeed-msft** [comment]
@JSteunou - Could you please have a look at [authentication sample code](https://github.com/OfficeDev/microsoft-teams-sample-complete-node/tree/master/src/views/tab-auth)? 
In this sample, authentication starts on [simple-start](https://github.com/OfficeDev/microsoft-teams-sample-complete-node/blob/master/src/views/tab-auth/simple-start.hbs) which redirects user to AAD login and returns back on [simple-end](https://github.com/OfficeDev/microsoft-teams-sample-complete-node/blob/master/src/views/tab-auth/simple-end.hbs) page. Instead of AAD login page, you could redirect to your custom login page on different domain.

**Comment by JSteunou** [comment]
I understand what you mean but from my point of view and context that would mean creating and deploying a new project on subdomain B just because subdomain A starts the flow and this flow will end with subdomain B. So instead of having A --> B you are saying I need A --> B --> B just to put my all my ms-teams code on the same side. But that's is not that easy because those separation exists for a reason here, and I cannot go over it.

**Comment by ydogandjiev** [comment]
Actually what’s needed is for the auth flow to start and end on the same domain so A —> B —> A or B —> A —> B. This is pretty typical since you generally have an endpoint that starts the auth flow and another on the same domain that acts as the callback. The reason this is required is because most browsers null out window.opener which is the only method the popup has for communicating back with the window that opened it.

**Comment by billbliss** [comment]
It is a pain, but it's not something we can control unfortunately.

**Comment by JSteunou** [comment]
Yep. Again thank you for your feedbacks, really appreciate

**Comment by spjpgrd** [comment]
I know this is closed, but I'm working through something similar to this right now, and we use auth0 for our user management. If our team uncovers some other fun discoveries, I'll be posting findings here 🙃

**Comment by MicroAsif** [comment]
in the web/desktop client, auth flow works fine, but when trying with mobile client. notify success called then never return the result. so it keeps redirecting on the same login page . 

using 1.4.2

**Comment by ricokahler** [comment]
> Is your start page ( authenticate call) and end page (notifySuccess call) in the same domain?

@Wajeed-msft  I'm fine with this constraint, however, I think an improvement would be to make the `notifySuccess` call throw if the domains don't match. Right now it just silently fails :(

Or possibly some mention of this in the docs would be nice too.

Thanks a bunch for any help!

**Comment by RukaiYu** [comment]
It seems this happens again?

**Comment by synth** [comment]
Yes, this is occurring for me as well. Any tips for debugging?

**Comment by Wajeed-msft** [comment]
What is the error code?

**Comment by synth** [comment]
cancelledByUser

**Comment by synth** [comment]
I tested several devices and am getting mixed results: 
```
OSX Chrome: Calls failure callback incorrectly
OSX Firefox: Calls failure callback incorrectly
OSX Desktop: Works
Windows10 Edge (Chromium): Works
Windows10 Chrome: Calls failure callback incorrectly
Windows10 Firefox: Calls failure callback incorrectly
Windows10 Desktop: Works
```

**Comment by Wajeed-msft** [comment]
@synth - Could you please try this [Sample Auth Manifest](https://github.com/OfficeDev/microsoft-teams-sample-auth-node/blob/master/manifest/AuthBot.zip) and see if you are still getting the same error?
![image](https://user-images.githubusercontent.com/31851992/72604649-5af6c280-3941-11ea-96d5-9a7f105d05ce.png)

**Comment by synth** [comment]
That didn't work for me at all. I tried on OSX in Chrome and Desktop. I click "Setup bot" and get:
<img width="600" alt="Screen Shot 2020-01-17 at 9 44 19 AM" src="https://user-images.githubusercontent.com/10546/72633783-0e45c400-390e-11ea-8822-1f888bcd8701.png">

Does this manifest need configuration or is it connected to a working backend as is?
