### ISSUE TITLE
Existing api openPurchaseExperience() T2 migration

### ISSUE THREAD

**Issue by JulianDeng** [OfficeDev/microsoft-teams-library-js#1742]
Our API was created 2 years ago and it's already deployed and in production for a while.
PR: https://github.com/OfficeDev/microsoft-teams-library-js/pull/613
Support doc: https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow?tabs=jsonV11#purchase-experience-api

Now we need to migrate our API implementation from T1 to T2, with the expectation to keep the interface & codes in teams JS SDK unchanged.

**Comment by Meghana-MSFT** [comment]
We will check this and get back to you, thanks!

**Comment by nwojod-MSFT** [comment]
Closing this request as the feature is already implemented and was addressed internally with the developer.
