### ISSUE TITLE
Teams bot "Learn more" button doesn't work

### ISSUE THREAD

**Issue by catmanjan** [OfficeDev/microsoft-teams-library-js#1754]
We have a bot that is showing a card with a Learn more button, this is meant to link to our website but when a user clicks it they get this behavior

![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/137350/c2bf4e74-56b0-4df0-851c-a8044ff72a56)

**Comment by ChetanSharma-msft** [comment]
Hello @catmanjan - Please confirm whether you have added a button with action "OpenUrl" and this button exists on Adaptive card?

Could you please share the repro steps?

**Comment by catmanjan** [comment]
@ChetanSharma-msft here is the function we are using with the sensitive parts blanked

![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/137350/1e03e5d1-5478-45b1-a536-8aa9724c798f)

**Comment by Nivedipa-MSFT** [comment]
@catmanjan - Could you please confirm if your URL contains the Machine names with numbers or any external deeplink you are using? Could you please share your URL which you are using in OpenURLAction to try at our end?
