### ISSUE TITLE
[Bugs] getTabInstances returns nothing and currentApp.navigateTo does nothing

### ISSUE THREAD

**Issue by wrharper-AASP** [OfficeDev/microsoft-teams-library-js#1758]
Hello,
I was referred here from: https://github.com/OfficeDev/TeamsFx/issues/8616

The overall issue at this point is the way you have to navigate to tabs has quite a few issues and isn't very fluid. It is possible for it to break quite easily with the ways people are working around it.

The 2 possible solutions to get this fixed:

1, fix getTabInstances so it returns what it should per docs.
Reference: https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/pages.tabs?view=msteams-client-js-latest#@microsoft-teams-js-pages-tabs-gettabinstances
2. fix currentApp so you can use navigateTo per docs.
Reference: https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/pages.currentapp?view=msteams-client-js-latest

#2 would be better for overall performance. We wouldn't need an entire class of params returned just to switch to a tab.

See GitHub link for a lot of details, this one has been going on for a while in the other link.

**Comment by nwojod-MSFT** [comment]
@wrharper-AASP thank you for bringing this to our attention. We understand how frustrating this must be and we would investigate these issues as soon as possible. We apologize for any inconvenience this may have caused.

**Comment by wrharper-AASP** [comment]
commented out since they don't work. microsoftTeams should be first like everything else in TeamsJsBlazorInterop.js. please see the previous post, these questions have already been answered.

does not work
//export function navigateToTab(tabInstance) {
    //return microsoftTeams.pages.tabs.navigateToTab(tabInstance);
//}

works but appids can change
export function navigateToApp(appId, pageId) {
    return microsoftTeams.pages.navigateToApp({ appId, pageId });
}

does not work
//export function navigateToPage(pageId) {
    //microsoftTeams.pages.currentApp.navigateTo(pageId)
//}

**Comment by noahdarveau-MSFT** [comment]
Hi @wrharper-AASP I was able to confirm in a blazor app that `pages.tabs.getTabInstances` is properly returning the TabInformation and the teams-js SDK is properly handling `pages.tabs.navigateToTab(tabInstance)` and `pages.currentApp.navigateTo(pageId)`. I noticed in the TeamsFX thread you mentioned that `getTabInstances` is coming back empty. My guess as to why you're experince this is `pages.tabs.getTabInstances` returns an array of TabInstance objects, so similar to your `TeamsContext` class, you will need not only a TabInstance class but also a class for the array (i.e. TabInstanceArray).
Here is some example code that should work in this regard:
```
public class TabInstanceArray {

  public TabInstance[] TeamTabs { get; set; }

}

public class TabInstance {

  public string ChannelId { get; set; }

  public bool? ChannelIsFavorite { get; set; }

  public string ChannelName { get; set; }

  public string EntityId { get; set; }

  public string GroupId { get; set; }

  public string LastViewUnixEpochTime { get; set; }

  public string TabName { get; set; }

  public string TeamId { get; set; }

  public bool? TeamIsFavorite { get; set; }

  public string TeamName { get; set; }

  public string Url { get; set; }

  public string WebsiteUrl { get; set; }

};
```

Also in your `MicrosoftTeams.cs` file, ensure to change the return type of `GetTabInstances` to `Task<TabInstanceArray>` (or whatever you decide to call it).

Please give this approach a let us know if it still isn't working.

**Comment by wrharper-AASP** [comment]
Blazor is not working for everyone right now: https://github.com/dotnet/razor/issues/8718
You must be using an older version or a preview version.

**Comment by nwojod-MSFT** [comment]
Closing this as issue was on Blazor and nor teams-js issue.
