### ISSUE TITLE
Is there a way to easily deploy an app that is just an external website?

### ISSUE THREAD

**Issue by catmanjan** [OfficeDev/microsoft-teams-library-js#1763]
Teams has the ability to add a tab app that is an external website, this works great but we have been asked to change the icon that appears

![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/137350/b76aa112-e06f-4322-9b65-494358c37bd2)

1. Is it possible to change this icon?
2. If not, is there a way to make an app that is just pointing to some other website that isn't Teams aware in any way?

**Comment by Prasad-MSFT** [comment]
@catmanjan - Do you mean to say while adding any external website as static tab in MS Teams channel, you want to change the icon of that?
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/62237649/247435f3-0d69-4d3b-8758-5fc806f7e700)

**Comment by catmanjan** [comment]
@Prasad-MSFT yes

**Comment by Prasad-MSFT** [comment]
@catmanjan - if that's the case, then I am afraid, this doesn't seem to be feasible.
To achieve your requirements, we recommend you give your feedback in [Teams Feedback Portal](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472).

**Comment by Prasad-MSFT** [comment]
Yes, if you want to add website as personal tab, then you can achieve so.
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/62237649/511fa7a5-635d-427d-8ffe-ac4348b0c017)

The manifest JSON is as follows:
```
{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.12/MicrosoftTeams.schema.json",
  "manifestVersion": "1.12",
  "id": "7xxxx6-c3e5-xx1a-bcx3-xxx78d3e09a9",
  "version": "1.0.0",
  "packageName": "com.custom.tab",
  "developer": {
    "name": "Contoso",
    "websiteUrl": "https://6c97-121-241-55-74.ngrok-free.app",
    "privacyUrl": "https://6c97-121-241-55-74.ngrok-free.app/privacy",
    "termsOfUseUrl": "https://6c97-121-241-55-74.ngrok-free.app/tou",
    "mpnId": ""
  },
  "name": {
    "short": "Tab",
    "full": "personalTab"
  },
  "description": {
    "short": "short description here",
    "full": "full description here"
  },
  "icons": {
    "outline": "outline.png",
    "color": "color.png"
  },
  "accentColor": "#D85028",
  "configurableTabs": [],
  "staticTabs": [
    {
      "entityId": "index",
      "name": "Personal Tab",
      "contentUrl": "https://make.powerautomate.com/",
      "websiteUrl": "https://make.powerautomate.com/",
      "scopes": [
        "personal"
      ]
    }
  ],
  "bots": [],
  "connectors": [],
  "composeExtensions": [],
  "permissions": [
    "identity",
    "messageTeamMembers"
  ],
  "validDomains": [
    "*.ngrok-free.app"
  ]
}
```
