### ISSUE TITLE
getAuthToken fails with renewalTimeout in desktop app

### ISSUE THREAD

**Issue by stabacco** [OfficeDev/microsoft-teams-library-js#1778]
Hello everyone,
we have setup a tab sso tab that loads our pre-existing app in a teams tab.

Everything works as expected in the when running teams in a browser tab, as well as when i 'pop up tab' from teams desktop.

However, when running inside of teams desktop ( windows 11, 1.6.00.12455 (64-bit).  ) . the `microsoftTeams.authentication.getAuthToken` times out with a `renewalTimeout` error. 

These are some of the logs i was able to dump out: 
```
Created a request with the following properties: {"LoginHint":"email---","msafed":"1","correlationId":"{3B20BFD6-DD27-46D2-ACDB-91F9CE6C2C48}","resource":"api://origin/app-id","claims":"User.Read"} 
Mon Jun 05 2023 16:41:05 GMT+1000 (Australian Eastern Standard Time) <304> -- info -- Fetching silent token with a web account 
Mon Jun 05 2023 16:41:05 GMT+1000 (Australian Eastern Standard Time) <304> -- info -- Getting silent token. 
Mon Jun 05 2023 16:41:06 GMT+1000 (Australian Eastern Standard Time) <304> -- info -- WAM: Silent token fetch complete. 
Mon Jun 05 2023 16:41:06 GMT+1000 (Australian Eastern Standard Time) <304> -- info --   token fetch responded withs:5;e:caa20002;aadStsErr:AADSTS901001;; 
Mon Jun 05 2023 16:41:06 GMT+1000 (Australian Eastern Standard Time) <304> -- info -- resource[:api://origin/app-id]
 ssorenew data:newPromise;gtia:ggt;ght;gp:cached;cr:s;cp1Off;addCCNonLlt:true-s;gst:wa:s:5;e:caa20002;s;atsPrePQ:5; 

```
I'm not sure what else to do at this point, any help would be greatly appreciated.

teams-js: 2.11.0

Cheers,
Stefano

**Comment by Nivedipa-MSFT** [comment]
@stabacco - Thanks for reporting your issue. Are you facing this issue intermittently or consistently

**Comment by stabacco** [comment]
thanks @Nivedipa-MSFT for looking into this: consistently. 
I can never access through the teams desktop tab and I can always access via web. 
I can also always access when I click 'pop out app'  and try to get an authToken from the popped out window, in case this helps.

**Comment by Nivedipa-MSFT** [comment]
@stabacco - We will test this using teams-js: 2.11.0 and update you soon.

**Comment by stabacco** [comment]
Thanks @Nivedipa-MSFT, it looks like your code is working for me, which is great! The one I'm using is quite similar, but still exibits that problem, I'll try to figure out what the difference is there. I'll keep you posted, thanks for now.

**Comment by Nivedipa-MSFT** [comment]
@stabacco - Please let us know if you have any further queries here, or should we close this issue?

**Comment by stabacco** [comment]
Closing, thanks

**Comment by Nivedipa-MSFT** [comment]
@stabacco - Thanks for confirmation. Could you please share your valuable feedback via [Microsoft Teams Developer Feedback](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u) link.
