### ISSUE TITLE
notifySuccess returns CancelledByUser in teams Web client

### ISSUE THREAD

**Issue by muiruri** [OfficeDev/microsoft-teams-library-js#1779]
I am using `microsoftTeams.authentication.authenticate` to open pop up window which displayed a login screen and after login invoke `microsoftTeams.authentication.notifySuccess` or `microsoftTeams.authentication.notifyFailure`

This works on desktop client (Mac) and also mobile app (iOS). However on teams web it fails.

It returns `CancelledByUser` error. Upon checking, the error comes from [here](https://github.com/OfficeDev/microsoft-teams-library-js/blob/8fb19af5c7b2a701df6b3695e03fe8330b4f703b/packages/teams-js/src/public/authentication.ts#LL368C7-L368C76) `if (!Communication.childWindow || Communication.childWindow.closed)` in authentication.ts

`Communication.childWindow` is `null`
This has been working okay then at some point started encountering the issue

using :
teams-js 2.11.0

Thanks

**Comment by Prasad-MSFT** [comment]
@muiruri - Could you please check if you are getting any error on console? 

Here's how you can do that : [DevTools for Microsoft Teams tabs](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/developer-tools)

**Comment by muiruri** [comment]
@Prasad-MSFT This is the error on the console

![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/1300851/10b1e7b3-af88-4343-99ad-19fc7c01d1ce)

It is not an intermittent issue. Only happens on Teams Web App. This is how we open the pop up

```
<Button
          primary={true}
          content={"Connect"}
          onClick={async () => {
            try {
              const authResult = await microsoftTeams.authentication.authenticate({
                url: `${url}/auth-start.html`,
                width: 600,
                height: 535,
              });
              if (authResult) {
                if (typeof authResult === 'object') {
                  dispatch(setAuth(authResult));
                } else {
                  dispatch(setAuth(JSON.parse(authResult)));
                }
              }
            } catch (e) {
              console.log(e);
              setError('Could not connect account.');
            }
          }}
```

in the pop-up code, even if I just do 

```
microsoftTeams.app.initialize().then(() => {
        console.log(('App initialized'));
        microsoftTeams.authentication.notifySuccess(JSON.stringify({ id: 10}));
      })
```

We get `CancelledByUser` error.

**Comment by muiruri** [comment]
I have managed to resolve the issue. I had duplicate `teams-js` in `index.html` & `node_modules`.
