### ISSUE TITLE
Issue with openPurchaseExperience

### ISSUE THREAD

**Issue by dieonar** [OfficeDev/microsoft-teams-library-js#1788]
Hello,

I have an issue with the implementation of in app purchase, I did the configuration inside the manifest by adding the following :

`"subscriptionOffer": {
    "offerId": "XXX.yyy"  
    },
    "authorization": {
      "permissions": {
        "resourceSpecific": [
          {
            "name": "InAppPurchase.Allow.User",
            "type": "Delegated"
          }
        ]
      }
    }`

And use the following code to open the in-app purchase popup 

`    var planInfo = {
      planId: "", // Plan Id of the published SAAS Offer
      term: "", // Term of the plan.
    };
    monetization.openPurchaseExperience(planInfo).then((result) => {
      alert(result);
    });`

And most of the time I get this error : 
`"Manifest does not contain the RSC permission to allow in-app purchases. Please contact app developer to add required RSC permission to their app manifest to enable"`

I did the configuration on two different app, on test tenant, for one of the application it works perfectly, but it show the above error on a normal tenant (the one of my company).
For the second application I have the error directly.

I did a test with a live SaaS offer and a preview.

Did I miss something somewhere ?

**Comment by dieonar** [comment]
For the manifest schema version I use this :
`  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.12/MicrosoftTeams.schema.json",
  "manifestVersion": "1.12",`

**Comment by dieonar** [comment]
@JulianDeng I just tried, the problem remains the same. 

In the meantime, I conducted several tests and ended up installing the application on my company's tenant and deploying the final offer on the marketplace. 

Here are the things I noticed: 
On the company's tenant with my account, I can make purchases correctly through the application using the popup. 

However, on a second account, the popup does not appear, and the error message "Manifest does not contain the RSC permission to allow in-app purchases. Please contact the app developer to add the required RSC permission to their app manifest to enable" occurs


I also upgrade the schema version to 1.15 and same behavior.

**Comment by dieonar** [comment]
The manifest package has been shared through Team, Istay at your disposal for any additional information

**Comment by Prasad-MSFT** [comment]
@dieonar - As informed by engineering team "In-app purchase is currently not supported in channel scope. It is only supported in personnel scope". There is a work item created to update the document to highlight this and engineering team will consider this request to implement in near future. Thanks for understanding.
