### ISSUE TITLE
Deep link to "Manage Team" page

### ISSUE THREAD

**Issue by AnthonyPhan** [OfficeDev/microsoft-teams-library-js#1791]
Hi,

Is there a way using teams-js have a button in our tab app which will deep link to the tab used to manage a team?

The tab I'm referring to is shown below:

![Kapture 2023-06-09 at 17 12 52](https://github.com/OfficeDev/microsoft-teams-library-js/assets/12785492/d9001c85-f722-40cf-87bb-0a9213bcdcca)

**Comment by Nivedipa-MSFT** [comment]
@AnthonyPhan - You can generate deeplink to tab using following format:
`https://teams.microsoft.com/l/entity/<appId>/<entityId>?webUrl=<entityWebUrl>&label=<entityLabel>&context=<context>&openInMeeting=false`

Ref Doc: https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-application?tabs=teamsjs-v2#generate-a-deep-link-to-your-tab

Could you please refer below sample:
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-deeplink/csharp

**Comment by AnthonyPhan** [comment]
Hi @Nivedipa-MSFT,

Thank you for your response, however, it does not actually address the question at hand. The deep links you provided and in the docs refer to a deep link to your own custom application. I'm looking for a deep link to the teams app settings for a specific team id.

**Comment by Nivedipa-MSFT** [comment]
@AnthonyPhan - We have copied the link of manage team from Teams web client. And we have open this link using app.openLink on button inTab application. We are able to navigate to the manage team tab of Team.

We have used below code in Tab form.

```
  microsoftTeams.app.initialize().then(() => {
          
                microsoftTeams.app.openLink("URL");
            });
```
Please refer below video:
[Deeplink_Issue.webm](https://github.com/OfficeDev/microsoft-teams-library-js/assets/92150070/05f0d734-90ee-4ff6-8987-7c166e038291)

**Comment by AnthonyPhan** [comment]
Hi @Nivedipa-MSFT,

The link to the mange team tab that appears in the browser makes no reference to the team Id, so there's no way for us to direct users of this tab from a channel app.

![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/12785492/1f4a2e11-e0de-440c-b389-fbcf741d5146)

How can we generate this link from a team id?

**Comment by AnthonyPhan** [comment]
actually looks like Team uses the internalId which is available via the Microsoft graph, so this should be possible. I think this can now be considered closed. The URL to use is:

```
https://teams.microsoft.com/_#/teamDashboard/${encodeURI(name)}/${internalId}/td.members
```

**Comment by Nivedipa-MSFT** [comment]
@AnthonyPhan - Thanks for the confirmation. We appreciate your feedback. To provide your valuable feedback, please use the [Microsoft Teams Developer Feedback](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u) link.
