### ISSUE TITLE
"Works in Teams, Outlook and Microsoft 365 app" message

### ISSUE THREAD

**Issue by catmanjan** [OfficeDev/microsoft-teams-library-js#1795]
We recently noticed this message appearing next to our app info

The problem is, we also have a SharePoint integration, how can we get it to mention SharePoint as well? Otherwise is there a way to disable this message?

![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/137350/b569d653-31e0-41e0-b82e-167269678638)

**Comment by ChetanSharma-msft** [comment]
Hello @catmanjan- Thanks for raising your query.
We will look into it and let you know the updates.

**Comment by ChetanSharma-msft** [comment]
Hello @catmanjan - Thanks for your patience.
We are checking your issue with engineering team and will let you know the updates.

**Comment by Meghana-MSFT** [comment]
@catmanjan - Could you please confirm if your app works in Sharepoint as well?

**Comment by catmanjan** [comment]
@Meghana-MSFT  yes, we have a web part integration too- what does teams use to identify the fact that these are all the same apps? Are the guids meant to be identical or just the app name and publisher?

**Comment by Meghana-MSFT** [comment]
Is it just a Sharepoint integration which runs in Teams or your app runs in Sharepoint as well? 

It uses the guid - Please check this doc which talks about to enabling your Teams personal tab to run in Outlook and Microsoft 365 app - https://learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/extend-m365-teams-personal-tab?tabs=manifest-teams-toolkit#update-the-app-manifest

**Comment by Meghana-MSFT** [comment]
Could you please let us know if this solves your query?

**Comment by catmanjan** [comment]
@Meghana-MSFT no I am confused still - as you can see in our screenshot it shows "Works in Teams, Outlook and the Microsoft 365 app" but I can't work out how it is doing this.

The GUIDs for all of our integrations are different, and the teams manifest doesn't even have a GUID

So how does this feature work?

Here is our SPfX package-solution.json - what do we need to add or change here to get it to also mention SharePoint in this list?

![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/137350/9e868308-b7bc-4e49-9770-ff609fb43a90)

**Comment by catmanjan** [comment]
@Meghana-MSFT thanks, so how do I use my teams app in outlook and m365?

**Comment by Meghana-MSFT** [comment]
Please check this doc https://learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/overview?tabs=Android, using which you can build and update Teams apps to run in other Microsoft 365 products.

**Comment by catmanjan** [comment]
@Meghana-MSFT I think according to that document we should be able to use our Teams bot in the New Outlook today, and it has some screenshots showing how it might look, but I can't tell from the interface how to actually trigger our Teams bot - can you confirm this should be working today or is it only in developer preview?

**Comment by Meghana-MSFT** [comment]
Please note that only [Teams app features mentioned in this table](https://learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/overview?tabs=Android#:~:text=Teams%20app%20features,Notes) are currently supported to extend across Microsoft 365 products.

**Comment by Meghana-MSFT** [comment]
First you need to Set up your dev environment for extending Teams apps across Microsoft 365 by following this doc https://learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/prerequisites.

After the tenant is made ready, when you upload an ME app in Teams it will be available in Outlook as well. 

You can see/add those apps using Apps option in nav bar
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/81138249/15be47ad-1f85-47d9-97af-1d66ad828058)

Compose a new mail and click on popout. Now click on More option in top right corner. It gives Apps option where you can invoke the ME app that you have added.
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/81138249/0ab8e1cf-1dba-4386-b14c-62c2a36ae4b1)


Please refer these samples which run in Outlook as well

1. https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-stage-view/nodejs#outlook-on-the-web
2. https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/msgext-link-unfurling/csharp#outlook-on-the-web
3. https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/msgext-search-quickstart/js#outlook-on-the-web

**Comment by catmanjan** [comment]
@Meghana-MSFT I've followed those instructions and it still doenst appear

Also, why is the non beta version of Teams showing the "Works in Teams, Outlook and Microsoft 365 app" if you need to be using the beta version of Office for that to be true?

![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/137350/3b1fb972-7403-4d14-8fa1-a9100b1b7ca5)

**Comment by catmanjan** [comment]
@Meghana-MSFT okay I worked it out, I can do it in browser Outlook only...

Okay we now have our Teams app running in Outlook - but because we also have an Outlook add in it now looks like there is 2 apps - is Microsoft planning on doing something to address this, as it will apply to most software vendors I would think?

![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/137350/732b2c7b-3f66-4d7a-ae5a-bc3bb7803bc2)

**Comment by Meghana-MSFT** [comment]
We will share this feedback with the engineering team.

**Comment by Meghana-MSFT** [comment]
@catmanjan - Since this issue is being tracked in another thread - https://github.com/OfficeDev/microsoft-teams-library-js/issues/1854

We are closing this issue, please feel free to reach out to us if you have any queries.

We would like your [feedback on your experience with our support team and Platform](https://aka.ms/DevSupportFeedback). Click here to [escalate](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUN0dNSTA4WVo2S05JQ1M4TVlYMjROSjhURS4u).
