### ISSUE TITLE
teams.authenticate throwing FailedToOpenWindow on MS Edge browser

### ISSUE THREAD

**Issue by didair** [OfficeDev/microsoft-teams-library-js#180]
Hi

I've been looking at an error i got reported to me that the login functionality isn't working in Edge browser. Apparently the authentication.authenticate throws an error with the reason `FailedToOpenWIndow` in the `failureCallback`. It's very odd and I haven't seen it before. Could you point me in the right direction or is there something up with the SDK?

Currently on @microsoft/teams-js version `1.3.7`. Also been trying builds on the `1.4.0-beta.16` version with the same results..

Here's a snippet of the code:
```
microsoftTeams.authentication.authenticate({
	url: window.location.origin + "/teams/authenticate",
	width: 600,
	height: 535,
	successCallback: token => {
		if ( this.props.onLogin ) {
			this.props.onLogin();
		}

		this.setState({ done: true });
	},
	failureCallback: function (reason) {
		console.error( 'login error', reason );
	}
});
```

**Comment by benpolinsky** [comment]
That error _can_ mean that the browser has blocked the popup window. I ran into a couple issues getting Edge to open the popup. The 'easier' of the issues to diagnose is to ensure that an explicit user action is triggering the code to authenticate -- for instance, a button click. 

In my case, when a user clicked our authenticate button, it redirected to a different React route which opened the popup. Even that amount of indirection will be enough for Edge to block the popup. 

I'd set up a minimal example: one button with an `onClick` handler that runs the above code - perhaps outside of React.

There was also a more esoteric case which related to our company's verified sites (accessible from Internet Options in control panel), but I'd definitely ensure there's direct explicit user interaction that triggers the popup first.

**Comment by didair** [comment]
Update: Yes, it does seem like the Teams SDK didn't "know" an user action was made due to a re-render in the component "accidentally" caused by ADAL trying to perform (and sucessfully) making a silent authentication..
To solve this I guess we could disable the `onClick` event on the button until we know for sure a silent login isn't successfully made, but I don't think we'll make the effort as of now to fix that.

For anyone else coming across here I would suggest you check out what @benpolinsky wrote in the comment above.
