### ISSUE TITLE
SSO: GetAuthToken shows popup with missing verification

### ISSUE THREAD

**Issue by jkerst** [OfficeDev/microsoft-teams-library-js#1801]
We have developed an app for mutli tenants. We are using following libraries relevant for authentication:

        "@azure/msal-browser": "^2.37.1",
        "@microsoft/teams-js": "^2.12.0",
        "@microsoft/teamsfx": "^2.2.1",

We call the teams-js library to get the ID token like this (simpified):

    if(teamsApp.isInitialized()===false) {await teamsApp.initialize();}
    token = await authentication.getAuthToken({ claims: [], silent: askSilent });

As expected, the teams-js will show a consent popup dialog. **Unfortunately, the popup dialog says that our app is not verified. Verification badge is missing. URL to privacy terms etc. is also missing.**

Here is the dialog with some basic information. URL also looks fine. Please note that some information is marked due to security reasons.

![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/130495478/8fdb1634-3324-4be7-bc0e-c80d665f3645)

**Troubleshooting details**
Request Id: c78d2e62-c03e-4cbf-aad8-05508ff31a00
Correlation Id: d80e9460-69ec-4474-a080-51b7ac3fbcf4
Timestamp: 2023-06-15T07:17:47.140Z

Later on, we try to get an access token for graph api calls from teamsfx library. We get the token like this (simplified):

    await credential.login(scope);
    const cred_token = await credential.getToken(scope);

This actually works pretty well. As expected a consent popup dialog appears and this time all the information is correct. We have a verification badge etc. Also our privacy URL and terms are correctly linked.

Here is the dialog with some basic information. URL looks also fine. Please note that some information is marked due to security reasons.

![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/130495478/8e5731b3-4266-4c56-b006-16811fbb24b2)

**Troubleshoot details**

Request Id: 229eb678-2504-4347-a8e5-802e5ade1900
Correlation Id: 6cdb53d3-6d62-4130-9e82-8b1514842b1b
Timestamp: 2023-06-15T07:20:24.334Z

Do you have any idea why this is happening? We checked AAD app configuration, but this also looks fine (second dialog is a proof to this).

Thank you for your help!

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this issue, we will check this and get back to you.

**Comment by sayali-MSFT** [comment]
@jkerst -When we mark our app as publisher verified then this blue badge is coming before publisher name.
Could you please refer below doc for more details.
https://learn.microsoft.com/en-us/azure/active-directory/develop/mark-app-as-publisher-verified

Also Refer the below document-https://learn.microsoft.com/en-us/azure/active-directory/develop/application-consent-experience

**Comment by jkerst** [comment]
Hi @sayali-MSFT, thank you for the documentation! Unfortunately, the documentation won't help as our app is already verified. The problem is that the verified bade is not shown.

If you look at the second consent screen, you will see a verification badge and also the links to the privacy statement and terms is correctly shown. The second consent screen is shown when our app is asking for access token.

However, if you look at the first consent screen, you will see that for the same app, the verification badge is missing. Also the screen states that there are no privacy statements and terms. The first consent screen is shown when our app is asking for ID token / launch the app for the first time. Can you please check why the first consent screen for ID token is behaving so much differently than the second consent screen for access token? 

Thanks!

**Comment by jkerst** [comment]
@sayali-MSFT : Thank you for the information. Unfortunately, we don't have access to both links. How can we get access?

**Comment by sayali-MSFT** [comment]
@jkerst -Could you please share the error screenshot?

**Comment by jkerst** [comment]
@sayali-MSFT : Sure:

![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/130495478/545071e4-ffac-4c3f-8740-112472d2b6d4)

**Comment by jkerst** [comment]
@tomagendium: Thank you for sharing this! We will check that. We recently moved from azurefd.net to a custom domain and I was hoping that this will solve it. According to what you just said, we now try the following:

We add to validDomains in manifest: [app.domain.com, domain.com]. We also add both domains (subdomain & domain) to custom domain names on Azure. Before, we had a mix here. Maybe this solves it for us.

**Comment by tomagendium** [comment]
@jkerst Note that it's not so much about the domain the app is actually using in the tabs etc. but specifically the "publisher domain" value for the app registration, under the "branding and properties" section. I suspect it might have been the 2nd thing that solved it (making sure that it's added as a verified domain) but hopefully it solves it for you!

**Comment by jkerst** [comment]
@tomagendium: Thank you, but so far we do not see any effect. Publisher Domain is identical to validURL is identical to custom domain names.

@sayali-MSFT : Any update on the "access denied" issue? I think now is a good time that someone from Identity org checks our case. We can not access this link:
https://identitydocs.azurewebsites.net/static/v2/get_help.html

**Comment by tomagendium** [comment]
@jkerst And to confirm, the domain is marked as "verified" under custom domains?

**Comment by jkerst** [comment]
@tomagendium : Yep, everything looks good here:

![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/130495478/1056def6-fb11-4f41-8851-48907a2af131)

**Comment by sayali-MSFT** [comment]
> @tomagendium: Thank you, but so far we do not see any effect. Publisher Domain is identical to validURL is identical to custom domain names.
> 
> @sayali-MSFT : Any update on the "access denied" issue? I think now is a good time that someone from Identity org checks our case. We can not access this link: https://identitydocs.azurewebsites.net/static/v2/get_help.html

Sure, we are checking with the internal team regarding Identity org team contact and let you know the update here.

**Comment by AE-MS** [comment]
FYI this is a known gap in the consent experience for which the Identity team does not currently have a timeline for a fix.

**Comment by jkerst** [comment]
@AE-MS : Thank you very much! Do you know any workaround? We did notice that this does not happend to every app. Actually, for a lot of apps, the consent dialog for ID token is rendered fine.

**Comment by AE-MS** [comment]
I'm not super familiar with this area since I work in the teams-js side of things and not on the identity side of things, so I don't really have a ton of details, I just did some digging to see that there was an acknowledged issue when a Microsoft app like Teams is showing a consent dialog on behalf of a non-Microsoft app like in the scenario you describe.

Using the StackOverflow links above are the best way to interact with the Identity team to get more details, I believe.

Can you give me an example of an app in Teams where the consent dialog for the ID token doesn't have this issue? This might help the Identity team further locate the source of the gap. Thanks!

**Comment by jkerst** [comment]
We have changed a lot of things in the last days. The consent popup for ID token is finally rendered correctly and shows the verification badge. We have no idea what the root cause was, but here is a list of things we have done in the last days:

- Changing the endpoint from "bla.azurefd.net" to a verified subdomain of our domain (app.our-domain.com) in our manifest.

- Created a new teams react example from teams toolkit 5.0.1. and combined this example with our app code.
- Therefore, we have started fresh with a new package configuration:
        "@fluentui/react-components": "^9.18.0",
        "@microsoft/mgt-element": "^2.8.0",
        "@microsoft/mgt-react": "^2.8.0",
        "@microsoft/mgt-teamsfx-provider": "^2.8.0",
        "@microsoft/microsoft-graph-client": "^3.0.1",
        "@microsoft/teams-js": "^2.7.1",
        "@microsoft/teamsfx": "^2.2.0",
        "@microsoft/teamsfx-react": "^3.0.0",
        "axios": "^0.21.1",
        "react": "^18.2.0",
        "react-dom": "^18.2.0",
        "react-router-dom": "^6.8.0",
        "react-scripts": "^5.0.1",
        "@fluentui/react-northstar": "^0.64.0",
        "@fluentui/react-teams": "^6.0.0",
        "react-device-detect": "^2.2.3"

I hope this helps to anyone with the same problem. Issue can be closed.

**Comment by jkerst** [comment]
Fixed, see comment above.
