### ISSUE TITLE
Cannot pass localhost URL to 

### ISSUE THREAD

**Issue by mscherotter** [OfficeDev/microsoft-teams-library-js#1805]
During testing and development, I need to use a localhost URL passed to the dialog.url.open() function, but that does not work.   The Dialog opens with a blank page.  I am using ngrok to tunnel to https://localhost:8000 Any suggestions?
 
```
const urlDialogInfo:UrlDialogInfo = {
            url: "https://localhost:8000/dialog",
            size: {
                width:DialogDimension.Large,
                height:DialogDimension.Large
            }
        };

        dialog.url.open(urlDialogInfo, async (result: dialog.ISdkResponse)=>{
            
        }, (message: any)=>{
            
        } );
```
### validDomains in manifest

```
"validDomains": [
        "localhost",
        "localhost:8000"
    ],
```

**Comment by mscherotter** [comment]
passing the full ngrok URl works.

**Comment by AE-MS** [comment]
FWIW I just tested this and was able to get a dialog to load a page from localhost without any issue. I'm not sure why it worked for me and not for you -- I'm glad you were able to find a workaround.

If you run into this issue again or need help troubleshooting why localhost wasn't working, please feel free to report back so we can help troubleshoot.
