### ISSUE TITLE
Support for Office (Agave) Addins within a Teams app

### ISSUE THREAD

**Issue by josephmastersonwork** [OfficeDev/microsoft-teams-library-js#1808]
This feature request is to create a way to preserve the M365 Calendar apps to be able to run their own Addins from within the app. This feature already exists today in Outlook Web (both consumer and commmercial) as well as Monarch

Added an ADO workitem: Feature 8032268: Support for Office Addins within Calendar App

**Comment by Prasad-MSFT** [comment]
Thanks, joseph, for raising this feature request. We will pass this to concerned team to have a look.

**Comment by Prasad-MSFT** [comment]
Hi @josephmastersonwork - FYI, we have discussed this with concerned team and this feature is in our backlog currently. We don't have any ETA to share at the moment. We will inform you once we get further information, Thanks!

**Comment by nwojod-MSFT** [comment]
We have added this to our backlog. However, we do not have an ETA. Once this feature is in place, we will notify the community.
