### ISSUE TITLE
Calling Notification from a Teams Tab App

### ISSUE THREAD

**Issue by jorgecolon413** [OfficeDev/microsoft-teams-library-js#1815]
We have two React.js TypeScript apps that work as a chat/calling platform for certain users, utilizing the Azure Communication Services library. One of the apps resides as a Tab App, where the user is part of the organization's tenant. The other web app is used for users outside of the organization.

Is there a way for an external user to send a continuous calling-like notification to an internal user using the Teams JavaScript SDK through the Tab App?

For example, if an external user initiates a call to one of the internal users, and the internal user is not logged into the Tab App to receive the incoming call notification, can the notification be sent to the Teams shell of the user they are trying to reach? This way, the user will be alerted that someone is trying to reach them.

**Comment by Nivedipa-MSFT** [comment]
@jorgecolon413 - Thanks for reporting your issue. We are checking this with engineering team, we will update you soon.

**Comment by jorgecolon413** [comment]
Thanks @Nivedipa-MSFT, we are currently testing the Graph API to accomplish this functionality with our use case. It may be a workaround for our need.

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
