### ISSUE TITLE
requestStopLiveStreaming method is not working

### ISSUE THREAD

**Issue by Wojciech-Florczak** [OfficeDev/microsoft-teams-library-js#1824]
I'm using `2.0.0-experimental.1` version of this library and I can't use `requestStopLiveStreaming` 
```js
import * as microsoftTeams from '@microsoft/teams-js';

// Stream starts when this method is used
microsoftTeams.meeting.shareAppContentToStage((error) => {
  if(error) {
    console.error(error);
  }
} 

// Stream won't stop when this method is used
microsoftTeams.meeting.requestStopLiveStreaming((error) => {
  if(error) {
    console.error(error);
  }
} 
```
Is there any other way to stop live stream? I would like to avoid bumping packages because it will require a lot changes in the app

**Comment by Nivedipa-MSFT** [comment]
@Wojciech-Florczak - Thanks for reporting your issue. Could you please share the error you are encountering in the console?

Are you testing on a specific platform (web, desktop, Android, or iOS)?

Before proceeding, could you please check if it is supported on the platform by using the isSupported() function?

**Comment by Wojciech-Florczak** [comment]
@Nivedipa-MSFT I'm testing it on the web. I've checked `isSupported()` method and the device is supported (Edge browser).  I'm getting an internal `500` error.

<img width="611" alt="image" src="https://github.com/OfficeDev/microsoft-teams-library-js/assets/53352540/e70ec79e-c5b7-4711-b55e-193469f2320e">

**Comment by Nivedipa-MSFT** [comment]
@Wojciech-Florczak - We will test this and update you soon.

**Comment by wpietrak** [comment]
@Nivedipa-MSFT could you share information about the progress of work and, possibly, when we can expect feedback :) Thanks a lot.

**Comment by Nivedipa-MSFT** [comment]
@wpietrak - The engineering team is actively working on the fix. At the moment, we do not have any ETA to provide. However, we will keep you updated and provide further information as soon as it becomes available.

**Comment by Wojciech-Florczak** [comment]
@Nivedipa-MSFT any updates on this?

**Comment by wpietrak** [comment]
Hi, any update in our issue :D

**Comment by Nivedipa-MSFT** [comment]
@Wojciech-Florczak, @wpietrak - We are checking the status of the bug with engineering team, we will let you know once we get any updates from them.

**Comment by Nivedipa-MSFT** [comment]
@Wojciech-Florczak , @wpietrak - Currently, we don't have any ETA to share. Engineering team is actively working on the fix, we will let you know once we get any updates on it.

**Comment by wpietrak** [comment]
Any news? :)

**Comment by Nivedipa-MSFT** [comment]
@wpietrak - We received an update from the engineering team, stating that the error is triggered due to either no Teams call ID or no app ID. Please check the input from your end to ensure that neither ID is empty.

**Comment by wpietrak** [comment]
Thank you for your feedback. We will check as quickly as possible.
