### ISSUE TITLE
Handler of `pages.config.registerOnRemoveHandler` not called on app removal

### ISSUE THREAD

**Issue by marekcis** [OfficeDev/microsoft-teams-library-js#1825]
Hi
I am using `pages.config.setConfig` to set `removeUrl` of my application.
The URL is loaded correctly, but once I click Remove button of the Teams app dialog, nothing happens and after cca 15 sec dialog with unsuccessful message appears that it was impossible to remove my app.

I am registering `pages.config.registerOnRemoveHandler` AFTER the SDK is fully initialised. 
The whole thing was working 2 weeks ago (mid jun), today I've did smoke test and it is not working at all.
We are using Teams SDK `2.9.1`

![Screenshot 2023-07-04 at 14 27 59](https://github.com/OfficeDev/microsoft-teams-library-js/assets/91459425/5f07f0b2-b4e8-4334-acff-db68d2b5e2bd)

**Comment by Nivedipa-MSFT** [comment]
@marekcis - Thank you for reporting your issue. We will test this and provide you with an update soon.

**Comment by marekcis** [comment]
My code looks like:
```
pages.config.registerOnRemoveHandler((evt: RemoveEvent) => {
      console.log('remove ok');
      evt.notifySuccess();
    });
```
The SDK is initialized and the remove route exists and loads normally in popup.

**Comment by Nivedipa-MSFT** [comment]
@marekcis - 
We have tested the code below:
```
 <button onclick="onClick()">Delete this tab and all underlying data?</button>
    <script>
        await microsoftTeams.app.initialize();
        pages.config.registerOnRemoveHandler((removeEvent) => {
            // Here you can designate the tab content to be removed and/or archived.
            console.log('remove ok');
            alert('remove ok');
            const configPromise = pages.getConfig();
            configPromise.
                then((configuration) => {
                    configuration.contentUrl = "...";
                    removeEvent.notifySuccess()
                }).
                catch((error) => { removeEvent.notifyFailure("failure message") });
        });

        const onClick() => {
            pages.config.setValidityState(true);
        }
    </script>
```
We have also encountered the following popup:
    
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/92150070/183dd571-6479-4613-8bd7-05eb8b873dd1)
However, the pages.config.registerOnRemoveHandler is not being called.

Please refer to the video provided below:
[registerOnRemoveHandler.webm](https://github.com/OfficeDev/microsoft-teams-library-js/assets/92150070/36d51b1e-2cdf-41f9-9eff-257ef74862bb)

We have raised a bug for the same. We will let you know once we get any updates on it.

**Comment by marekcis** [comment]
Please any update or ETA? Thanks

**Comment by Nivedipa-MSFT** [comment]
@marekcis - We are currently checking the status of the bug fix with our engineering team. We will provide you with an update as soon as possible. Thank you for your patience.

**Comment by Nivedipa-MSFT** [comment]
@marekcis - Engineering team is working on the bug fix. Currently we don't have any ETA to share. We will let you know once we get any updates from them.

**Comment by marekcis** [comment]
@Nivedipa-MSFT please any update after a month? Production is still broken.

**Comment by Nivedipa-MSFT** [comment]
@marekcis - We are checking the status of the bug with engineering team, we will let you know once we get any updates on it.

**Comment by ramsivaramsiva** [comment]
I am also faced this same issue since last 2 months, To resolve the issue added the code "pages.config.setValidityState(true);" 
For Example:
pages.config.registerOnRemoveHandler(removeEvent=>{
     //do your stuff
});
pages.config.setValidityState(true);

**Comment by ydogandjiev** [comment]
Calling `setValidityState(true)` is how your app tells Teams that you're ready for the deletion to be completed. If you do not call this API, then Teams takes the user through a forced delete flow (which is a fallback option in place to ensure users can always delete a tab). There is documentation on all this here:
https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page

**Comment by marekcis** [comment]
Thanks @ramsivaramsiva - you helped me to fix the bug 👍 

However @ydogandjiev I do not see the described behaviour in the documentation link you've provided.
The page states that: "By default, Teams enables the Remove button after five seconds even if you don't call setValidityState(true)."
So there is no need from devs to call `setValidityState(true)` by themselves. It just happen to fix the issue. 
But as also @ramsivaramsiva he happened to face the problem 2 months back, prior to that time removal flow worked fine.
So it is still a bug inside of Teams. The workaround is fine, but I'd appreciate if the problem was solved inside of Teams platform, not forcing 3rd party devs to apply workarounds.

**Comment by Nivedipa-MSFT** [comment]
@marekcis - Currently, we don't have any ETA to share. Engineering team is working on the bug fix. We will let you know once we get any updates on it.
