### ISSUE TITLE
ThumbnailCard Text does not wrap

### ISSUE THREAD

**Issue by catmanjan** [OfficeDev/microsoft-teams-library-js#1832]
We are supplying a Title, Subtitle and Text, but if the Text is long and has a line break it does not wrap as expected

![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/137350/a7a84bcd-5767-485d-bfae-56ce35285557)

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this issue, we will check this and get back to you.

**Comment by Meghana-MSFT** [comment]
@catmanjan - We checked this at our end using line breaks and its rendering as below. 

```
{
                            "type": "message",
                            "attachments": [
                                {
                                    "contentType": "application/vnd.microsoft.card.thumbnail",
                                    "content": {
                                        "title": "Bender",
                                        "subtitle": "tale of a robot who dared to love",
                                        "text": "Bender Bending Rodríguez <br /> is a main character in the animated television <br /><br /> series Futurama. He was created by series creators Matt Groening and David X. Cohen, and is voiced by John DiMaggio",
                                        "images": [
                                            {
                                                "url": "https://upload.wikimedia.org/wikipedia/en/a/a6/Bender_Rodriguez.png",
                                                "alt": "Bender Rodríguez"
                                            }
                                        ]
                                    }
                                }
                            ]
                        }
```

![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/81138249/44919427-3c28-48ca-b7c0-00f7541ce531)

Could you please share your card JSON and card rendering screenshots?

**Comment by catmanjan** [comment]
@Meghana-MSFT  my screenshot is a search result in chat when you click the app icon and perform a search

**Comment by Meghana-MSFT** [comment]
We checked by hard coding the title, subtitle and text mentioned in above JSON. Line breaks are rendering properly. Could you please confirm if this is what you mentioned?

 

https://github.com/OfficeDev/microsoft-teams-library-js/assets/81138249/1f49fd31-c47d-465a-8b6f-5f6793f9ca34

**Comment by catmanjan** [comment]
@Meghana-MSFT no here's a video showing the issue
[asdf.webm](https://github.com/OfficeDev/microsoft-teams-library-js/assets/137350/45fabf1d-33cd-469f-9ca8-dfd018f46365)

**Comment by Meghana-MSFT** [comment]
@catmanjan - We checked this at our end again by giving a lengthy Text with line break. Thumbnail card is rendering fine. 
Text goes to next line at `<br/>` and it shows ... at the end. Hovering on ... shows the entire text.

![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/81138249/f5da4d1d-a5a0-41a4-8d7a-0baf981a35d0)

```
var previewCard = new ThumbnailCard
                {
                    Title = "thumbnail card test",
                    Subtitle = "test",
                    Text = "Teams platform supports <br /> v1.5 or earlier of Adaptive Card features for bot sent cards and action based message extensions Teams platform supports v1.5 or earlier of Adaptive Card features for bot sent cards and action based message extensions",
                    Images = new List<CardImage> { new CardImage { Url = "https://fastly.picsum.photos/id/650/200/300.jpg?hmac=iNg9Umek-SwBR_yU0igvABZSTcRJFdhp1zyaqp0PdIw" } },
                    
                };
```

Could you please share your card, it might help us in having the repro. Thank you.

**Comment by catmanjan** [comment]
This is production so I'm not really sure what I can share with you, I showed you a video so surely thats enough to go back to developers with?

**Comment by Meghana-MSFT** [comment]
We have raised a bug for the same, we will keep you posted on the updates.

**Comment by heyitsaamir** [comment]
@catmanjan Are you building your thumbnail card using Adaptive Cards or traditional thumbnail cards? 
If you are using adaptive cards to build your thumbnail card, note that there is a `wrap` property which defaults to `false` ([spec](https://adaptivecards.io/explorer/TextBlock.html)).

It would be helpful to see the json you are using (feel free to obscure any details that might not be helpful).

**Comment by heyitsaamir** [comment]
@catmanjan Can you give more detail on the contents of the `text` field so we can better assist you? In your example, is it supposed to say `Relevant Protected Ingress Record` or `Relevant <more text> <br />Protected Ingress Record` or `Relevant <more text> \n Protected Ingress Record`? Were there multiple breaks in the value?

Additionally, it would be helpful to get more details such as:
1. Browser that you tested on / If you tested on the client itself
2. OS that you tested on
3. Have you tested on different browsers?

Feel free to obscure details on the text.

**Comment by catmanjan** [comment]
@heyitsaamir my video from July was in Firefox, but it looks like this bug has been fixed in the interm
