### ISSUE TITLE
MicrosoftTeams.js SDK initialization Timed out

### ISSUE THREAD

**Issue by camillehayot** [OfficeDev/microsoft-teams-library-js#1834]
Hi everyone,

I am building a tab application for MS Teams. I am trying to implement authentication from angular application to get access to API like this (https://localhost:4200)
`
const msalConfig = {
      auth: {
        clientId: 'myclientid',
        redirectUri: 'https://localhost:53000/auth-end'
      }
    };

    const msalInstance = new msal.PublicClientApplication(msalConfig);
    console.log('MSAL INSTANCE', msalInstance);
    msalInstance.initialize().then(async (response) => {

      const authProvider = async (callback: any) => {
        console.log('auth provider triggered');
        msalInstance.acquireTokenPopup({ scopes: ['https://graph.microsoft.com/.default'] }).then(response => {
          console.log('AUTH RESPONSE', response);
          callback(null, response);
        }).catch(err => {
          console.log('AUTH ERROR', err);
          callback(err, null);
        });
      };

      const options: Options = {
        authProvider
      };

      this.client = Client.init(options);
      console.log('CLIENT INITIALIZED', this.client, options);

      this.client.api('/me').get().then(response => {
        console.log('GET CURRENT USER', response);
      });
`
`On https://localhost:53000/auth-end I call the following script provided in Microsfoft Samples

// The following is a helper to wrap the initialize call in a promise and to detect if we're not 
// running inside of Teams
const teamsPromise = Promise.race([
    new Promise(resolve => microsoftTeams.app.initialize().then(() => resolve())),
    new Promise((resolve, reject) => setTimeout(() => reject('Failed to initialize connection with Microsoft Teams'), 250))]);

// Entrypoint of the script
async function main() {
    try {
        await teamsPromise;
        console.log("auth end started");
        const currentUri = new URL(window.location.href);
        var state = currentUri.searchParams.get('state');
        var code = currentUri.searchParams.get('code');
        // We need to send back the 'state' and the 'code' so that the caller can claim the token(s)
        microsoftTeams.authentication.notifySuccess(JSON.stringify({state, code}));
    } catch (ex) {
        console.error('Error happened while trying to end auth', ex);
        console.log("Attempting to close window");
        window.close();
    }
}
  
// Execute the entrypoint and log any errors
main().catch(err => console.error(err));

`
I expect microsoftTeams.app.initialize() to work but I always get the following message "MicrosoftTeams.js SDK initialization Timed out" . Am I missing something ?

Thanks all

**Comment by nwojod-MSFT** [comment]
@camillehayot thank you for reporting the issue. To help us investigate, please provide the teams-js version you are using and the platform you are encountering this error (desktop, web or mobile). We will investigate on our end and get back to you. Thanks
