### ISSUE TITLE
"No parent window found" when calling authentication.authenticate() inside MS Teams tab.

### ISSUE THREAD

**Issue by andrewfrankcare** [OfficeDev/microsoft-teams-library-js#1837]
Hello,

I'm developing an MS Teams App and am trying to get SSO working. 

However, when I call @microsoft/teams-js:authentication.authenticate() from my tab in my MS Teams App it opens the page in a browser, rather than as a pop-up window in MS Teams. This means when I call @microsoft/teams-js:app.initialize() in the new page, it fails with "No parent window found" - because it's not running in MS Teams.

My code looks like this:

```
import { app, authentication } from "@microsoft/teams-js";
...
const token = await authentication.authenticate({
                        url: window.location.origin + "/teams/start-authorisation",
                        width: 600,
                        height: 535,
                    });
...
```

Which then launches https://.../teams/start-authorisation which calls:

```
import { app } from "@microsoft/teams-js";
...
// This fails with "No parent window found".
await app.initialize();
```

I'm using React.js (Next.js) on the front-end running a newly installed MS Teams App on Mac OS X. The library for the front-end is:

 "@microsoft/teams-js": "^2.12.0",

Thanks in advance,
Andrew

**Comment by sayali-MSFT** [comment]
@andrewfrankcare - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by andrewfrankcare** [comment]
I'm using ngrok to connect the MS Teams App to my front-end.

**Comment by andrewfrankcare** [comment]
A related ticket:

https://github.com/OfficeDev/microsoft-teams-library-js/issues/1314

The fix there was related to the SameSite attribute for a cookie. However, it's not clear to me how that is related to this bug (and I'm not yet using any cookies in the flow).

**Comment by sayali-MSFT** [comment]
@andrewfrankcare -We have tested the above scenario on MAC device. It is working fine from our end.
Microsoft Teams Version 1.6.00.17554.
macOS Ventura 13.4.1
@microsoft/teams-js: "^2.12.0"

Code-
```
    microsoftTeams.authentication.authenticate({
                url: window.location.origin + "/auth-start",
                width: 600,
                height: 535
            })
```

Referred Sample Link-https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-sso/nodejs

![MicrosoftTeams-image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/93527375/f2cb3aa0-21fe-40d4-bceb-19880d539726)

**Comment by andrewfrankcare** [comment]
It's working now. I found an issue which I think might have been the problem. I was using the wrong App Id in the "Application ID URI" in Azure -> Expose an API -> Application ID URI and in the manifest.json's webApplicationInfo fields. It should have looked like this:

```
{
    "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.16/MicrosoftTeams.schema.json",
    "manifestVersion": "1.16",
    "id": "${{TEAMS_APP_ID}}",
    ...
     "webApplicationInfo": {
        "id": "${{TEAMS_APP_ID}}",
        "resource": "api://${{TAB_DOMAIN}}/${{TEAMS_APP_ID}}"
    }
}
```

It looks like there are multiple bugs in the Teams/Azure code where it doesn't validate input data leading to weird behaviour or "unknown errors" being returned.
