### ISSUE TITLE
Teams search results layout issue in Outlook

### ISSUE THREAD

**Issue by catmanjan** [OfficeDev/microsoft-teams-library-js#1841]
Not sure if/where I'm meant to log this one, but we have a Teams app that is returning search results in the pre-release Outlook as an add in

The layout looks bad

![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/137350/18228ccc-0b87-4e77-8d0c-38b76d237fe8)

**Comment by Meghana-MSFT** [comment]
Thanks for reporting this issue, we will check this and get back to you.

**Comment by Meghana-MSFT** [comment]
@catmanjan - We are also able to repro this issue if the subtitle is lengthy, we will check this internally and get back to you.

![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/81138249/5b089c3b-3524-406e-b008-f1aa6d815465)

**Comment by nwojod-MSFT** [comment]
Hi @catmanjan apologies for the delayed update. The team is still looking into this, and I will update the thread once I have additional information. Thanks

**Comment by nwojod-MSFT** [comment]
@catmanjan thank you for your patience. The fix is going through validation and would be released to PROD September 30th.

**Comment by catmanjan** [comment]
Looks like this is still happening 
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/137350/69d74181-2cda-47d7-a0c1-3f926312d6eb)

**Comment by nwojod-MSFT** [comment]
Hi @catmanjan, this issue has been fixed and available in the latest Outlook release. Please let us know if you still encounter this issue. Thanks
