### ISSUE TITLE
Deep Link for Join Teams Meeting link is not working

### ISSUE THREAD

**Issue by ceroles** [OfficeDev/microsoft-teams-library-js#1843]
We are currently using deeplinking in our Teams custom app for users to be able to join a Teams meeting directly.

We create the Teams meeting using Graph API and save the `joinWebUrl` property from the `onlineMeeting` resource. Then we replace the `https://` with `msteams://` so that the link clicked from inside the custom app in the Teams app will launch Teams' audio-video conferencing window for that meeting directly. We want to avoid the user having to go through the web browser to launch from there. This used to be working until recently. We have temporarily reverted to the default `https://` due to this.

Replicated on Windows 10, Teams version 1.6.00.16472.

May you please help check on the issue? Thank you.

**Comment by Nivedipa-MSFT** [comment]
@ceroles - Thanks for reporting your issue. We will check this and update you soon.

**Comment by ceroles** [comment]
We have tested it again on the latest version of Teams app and confirmed it is now working. Thank you

**Comment by Nivedipa-MSFT** [comment]
@ceroles - Glad to hear that it's working for you. We greatly appreciate your feedback. 
Could you please take a moment to share your valuable feedback through the [Microsoft Teams Developer Feedback](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u) link? 
Thank you!

**Comment by Nivedipa-MSFT** [comment]
@ceroles - We are closing this issue for now. Please feel free to reopen it if required.
