### ISSUE TITLE
Second dialog from messaging extension not updating content

### ISSUE THREAD

**Issue by NuxXDev** [OfficeDev/microsoft-teams-library-js#1849]
I have a Teams bot with a messaging extension that will show a dialog, and once that dialog is submitted will show a different dialog. On June 29th I noticed this stopped working correctly. Now after the first dialog is submitted, the second dialog shows up with the new title and size, _but the content does not update to the new content from the URL we specified_. 

I simplified the code to reproduce the issue and this is how it looks in Teams:
The first dialog shows up correctly:
![1](https://github.com/OfficeDev/microsoft-teams-library-js/assets/32570858/add9d6f5-a8fa-4e11-a85b-0cb8f993161b)

After “Submit” is clicked, the second dialog window shows up with the correct title and size, but the content is still from the first dialog:
![2023-07-18 09_01_33-2 png ‎- Photos](https://github.com/OfficeDev/microsoft-teams-library-js/assets/32570858/cfa60427-3edd-4c31-8618-2d44cea13c4c)

A few days after we noticed this problem started, we checked the Teams Tech Community forum and saw the last two comments (from jocsh and HARIBABU_PA) on this post seem like the same issue we are seeing. We are not using the new channel experience and have not had the issue in the original post. https://techcommunity.microsoft.com/t5/teams-developer/new-channel-experience-breaks-task-module-from-3rd-party-app/m-p/3856791/highlight/true#M7949

Below is a code sample from our bot and two test html pages. This issue is occurring in Teams in Edge, Chrome, and Firefox, Windows Teams (1.6.00.16472), and Windows Teams 2.0.

**Bot Code:**
```
protected override async Task<MessagingExtensionActionResponse> OnTeamsMessagingExtensionFetchTaskAsync(ITurnContext<IInvokeActivity> turnContext, MessagingExtensionAction action, CancellationToken cancellationToken)
{
	return new MessagingExtensionActionResponse()
	{
		Task = new TaskModuleContinueResponse()
		{
			Value = new TaskModuleTaskInfo
			{
				Height = 200,
				Width = 500,
				Title = "Test 1",
				Url = $"{_configuration["BaseUrl"]}/test1.html"
			}
		}
	};
}

protected override async Task<MessagingExtensionActionResponse> OnTeamsMessagingExtensionSubmitActionAsync(ITurnContext<IInvokeActivity> turnContext, MessagingExtensionAction action, CancellationToken cancellationToken)
{
	return new MessagingExtensionActionResponse()
	{
		Task = new TaskModuleContinueResponse()
		{
			Value = new TaskModuleTaskInfo
			{
				Height = 600,
				Width = 500,
				Title = "Test 2",
				Url = $"{_configuration["BaseUrl"]}/test2.html"
			}
		}
	};
}
```

**test1.html**
```
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
    <script src="https://res.cdn.office.net/teams-js/2.1.0/js/MicrosoftTeams.min.js" integrity="sha384-OEWKU/EjpwI1kJsgIcTi+paZNbXiqihK8zg6Dg2cbyjoEaC674oCQMy00ie4caKi" crossorigin="anonymous"></script>
</head>
<body>
<script>
    microsoftTeams.app.initialize();

    function closeWindow() {
        microsoftTeams.dialog.submit("test1", "OUR_BOT_ID");
    }
</script>
test 1
<button onclick="closeWindow()">Submit</button>
</body>
</html>
```
**test2.html**
```
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    test 2
</body>
</html>
```

**Comment by ChetanSharma-msft** [comment]
Hello @NuxXDev - Thanks for raising your query.
We will look into it and let you know the updates.

**Comment by Nivedipa-MSFT** [comment]
@NuxXDev - We are currently testing this out and facing some issues. We will provide an update soon.

**Comment by Nivedipa-MSFT** [comment]
@NuxXDev - Engineering team is actively working on the bug fix. We will let you know once we get any updates from them.

**Comment by Nivedipa-MSFT** [comment]
@NuxXDev - The bug has been fixed now. We have tested this on the Teams web client. Could you please test this and confirm once?

**Comment by Nivedipa-MSFT** [comment]
@NuxXDev - We are closing this issue for now. Please feel free to reopen if required.
