### ISSUE TITLE
Microsoft Teams Apps Not Working in SharePointOnline

### ISSUE THREAD

**Issue by twgolds** [OfficeDev/microsoft-teams-library-js#1851]
Hi,

Not sure this is the appropriate team.   

We have a number of Teams Applications and have them hosted in Microsoft SharePoint Online.

The Teams apps have been loaded into the SPO and then we've created Pages based on these applications.

The apps have been running successfully for the past 18 months.  We have not made any changes within the last 3 weeks.

Since around 9:00am today all the applications have stopped functioning within SharePoint.   This is across three different M365 tenants and two entirely unrelated applications.   The Teams Apps continue to function as expected within Teams, Outlook & Office.Com.

When opening a page that has been created using the Teams App, we simply get a blank page, in the console is an error message:
"Uncaught (in promise) SharePoint context is not initialized" -this is occurring within Microsoft code.

Looking into it, I cannot see any attempt by SPO to load the application.  No network requests go from SPO to the Teams App.  It looks very much as if SPO has broken the Teams App loading/hosting functionality.

Have there been any breaking changes deployed to SharePoint that would affect Microsoft Teams apps?  Or are there any new requirements within the Teams Application manifest to support SharePointOnline.  

Thanks for your help.

**Comment by Nivedipa-MSFT** [comment]
@twgolds -Thanks for reporting your issue. To help us investigate further, could you please share the repro steps that lead to the problem? Additionally, it would be very helpful if you could provide the code snippets you are using, along with a screen recording demonstrating the issue. With this information, we can try to reproduce the problem at our end. Thank you for your cooperation.

**Comment by twgolds** [comment]
Hi,

The steps are quite simple, but many.

1.  Take any Teams App. Confirm that it runs within Teams.

2. Modify the manifest.json to ensure it contains the "supportedSharePointHosts" attribute, with values "sharePointFullPage"


```
"configurableTabs": [
        {
            "configurationUrl": "https://myhost.com/config",
            "canUpdateConfiguration": true,
            "scopes": [
                "team",
                "groupchat"
            ]
            , "supportedSharePointHosts": ["sharePointFullPage", "sharePointWebPart"],
            "sharePointPreviewImage": "https://myhost.com/img/sharepoint-teams-app.png"
        }
```

3. Go to SharePointOnline admin center.
4. Go to the "App Section"
5. Upload your Teams Manifest ( the .zip file, not just the manifest.json )
6. Deploy the app ( SharePoint should prompt you automatically to do so )
7. Go to a SharePoint Site within your SharePoint tenant
8. Open a "Site Page"
9. Click the "Gear" on the top right near your profile picture
10. Select "Add a Page"
11. On the "Pages" window that opens up, select the "Apps" tab.  Your new App should be listed.
12. Select your App to create a new "Full Paged App" page within SharePoint.

It should load and display your Teams application, and indeed, this was the behavior until yesterday.

However, now it simply crashes initializing the SharePoint and does not get close to attempting to load the Teams App.

**Comment by Nivedipa-MSFT** [comment]
@twgolds - ICM has been created for this issue and the issue is being investigated. We will keep you informed on this thread once we receive any updates on its progress.

**Comment by twgolds** [comment]
Thanks.  An update would be appreciated, as this is causing severe problems for us and our customers.

Yesterday I created a simple "Hello World" Teams App from scratch.  Works in Teams but fails in an identical fashion when hosted in SharePointOnline.

The SharePoint "App Page" just fails to run properly because of a Javascript error.

**Comment by Nivedipa-MSFT** [comment]
@twgolds - We are checking the status of the ICM and update you soon.

**Comment by twgolds** [comment]
Is there an update on this issue?

**Comment by twgolds** [comment]
So, still not updates on this issue?

**Comment by Nivedipa-MSFT** [comment]
@twgolds - At the moment, we don't have a specific ETA to share. The engineering team is actively working on the issue, and we will notify you as soon as we have any updates.

**Comment by kick-flip-code** [comment]
We're facing the exact same issue here, are there any further updates on the issue or work-arounds?

**Comment by ChetanSharma-msft** [comment]
Hello Everyone,
We have raised the bug and informed to engineering team.
We will inform you once we get any updates from engineering team.

**Comment by kpoimenidis** [comment]
Hello, are there any updates on this issue?

**Comment by ChetanSharma-msft** [comment]
Hello @twgolds - Sorry for delay in response.
We got an update from engineering team that this issue is more related to SharePoint side, so we recommend you to raise your issue here: https://github.com/SharePoint/sp-dev-docs/issues/new/choose
