### ISSUE TITLE
Teams apps inside Outlook appear as duplicates when your add in has the same name across all applications

### ISSUE THREAD

**Issue by catmanjan** [OfficeDev/microsoft-teams-library-js#1854]
I raised this on another ticket but I need a seperate ticket for our own internal tracker.

Okay we now have our Teams app running in Outlook - but because we also have an Outlook add in it now looks like there is 2 apps - is Microsoft planning on doing something to address this, as it will apply to most software vendors I would think?

![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/137350/23a91458-8841-44f0-9d8f-3d6c2ea87cad)

**Comment by Meghana-MSFT** [comment]
We have shared this feedback with engineering team, we will get back to you once we have an update. Thank you.

**Comment by nwojod-MSFT** [comment]
Hi @catmanjan apologies for the delayed reply. 

Yes, we expect that many partners who have built Teams apps have also built Outlook Add-ins. For these partners, we recommend unifying their Teams apps and Outlook Add-ins in a unified manifest; what this means specifically is that their Outlook Add-in can be included as part of their Teams app manifest/package. This is currently in public preview: https://learn.microsoft.com/en-us/office/dev/add-ins/develop/unified-manifest-overview

With the unified manifest, you would have 1 "Ingress Search" app package to maintain. Your users would have 1 "Ingress Search" app to install/deploy, it would install both the Teams app and​ the Outlook Add-in, and in the Apps UX, the commands would be grouped under a single app icon.

Please let us know if this resolves your issue. Thanks
