### ISSUE TITLE
Bug v2.5.0: dialog.open not working in Outlook web for Microsoft 365 / Outlook app

### ISSUE THREAD

**Issue by matthiasdilger** [OfficeDev/microsoft-teams-library-js#1856]
Using version 2.5.0 of the library, it was possible to use dialog.open() to open a HTML task in Teams and Outlook:

```
var taskInfo = {
            title: null,
            size: {},
            url: null,
            card: null,
            fallbackUrl: null,
            completionBotId: null,
        };

      taskInfo.url = 'https://....';
      taskInfo.title = "Title";
      taskInfo.size.height = 'medium';
      taskInfo.size.width = 'medium';
      submitHandler = (result) => {
          ...
      };
      microsoftTeams.dialog.open(taskInfo, submitHandler);

```

Starting around a week ago this does no longer work in Outlook web and fails silently. Still works fine in Teams. Updating to version 2.13.0 and using dialog.url.open() makes no difference.

**Comment by Nivedipa-MSFT** [comment]
@matthiasdilger - Thanks for reporting your issue. We will test this and update you soon.

**Comment by Nivedipa-MSFT** [comment]
@matthiasdilger - We have tested this on Outlook web client version 20230801002.02. And it was working fine here.
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/92150070/01aa01e2-df5e-42e7-8a68-2e3ba308cc88)

Could you please test this and confirm on this?

**Comment by matthiasdilger** [comment]
@Nivedipa-MSFT I have cleared the browser cache but the problem is still there when I use https://outlook.office.com

**Comment by Nivedipa-MSFT** [comment]
@matthiasdilger - We received updates from the engineering team, stating that the fix has not been rolled out publicly. We will update you once it is released to the public.

**Comment by matthiasdilger** [comment]
@Nivedipa-MSFT It seems the fix has been rolled out, closing this now. Thanks!
