### ISSUE TITLE
use getContext() The library has not yet been initialized

### ISSUE THREAD

**Issue by Seongjun2** [OfficeDev/microsoft-teams-library-js#1868]
//my code
const { app } = require("@microsoft/teams-js");

class TeamsBot extends TeamsActivityHandler {
  constructor() {
    super();

    this.likeCountObj = { likeCount: 0 };

    this.onMessage(async (context, next) => {
      console.log("Running with Message Activity.");
      let txt = context.activity.text;
      console.log("txt : " + txt);
      
      app.initialize();
      app.getContext().then((context) => {
        console.log("Test");
        console.log("context : " + context);
      }).catch((err) => {
        console.log("getContext error : " + err);
      });

....
   });
 }
}
this is my code. it appears that you are correctly initializing the library with app.initialize(), but still encountering the error 'The library has not yet been initialized' when using getContext(). help me, please.

**Comment by Nivedipa-MSFT** [comment]
@Seongjun2 - Thanks for reporting your issue.
Could you please try like below code and test once again.

```
microsoftTeams.app.initialize().then(() => {

            microsoftTeams.app.getContext().then((context) => {

           
            });
        });

```

**Comment by Seongjun2** [comment]
> @Seongjun2 - Thanks for reporting your issue. Could you please try like below code and test once again.
> 
> ```
> microsoftTeams.app.initialize().then(() => {
> 
>             microsoftTeams.app.getContext().then((context) => {
> 
>            
>             });
>         });
> ```

Thank you, sir. but when I run that code, I get a phrase like 'Waiting for the debugger to disconnect...' which seems to be a problem in nodejs...

**Comment by Seongjun2** [comment]
> Hi @Seongjun2! Based on the sample code you shared above (e.g., the reference to `TeamsActivityHandler`), are you building a Teams bot that runs as a service?

Thank you.
Yes, I'm running it in debugging mode, creating teams bot.

**Comment by Seongjun2** [comment]
> > > Hi @Seongjun2! Based on the sample code you shared above (e.g., the reference to `TeamsActivityHandler`), are you building a Teams bot that runs as a service?
> > 
> > 
> > Thank you. Yes, I'm running it in debugging mode, creating teams bot.
> 
> Thank you for the extra detail! The teams-js library can only be used on the client, like when creating a personal tab. The information it needs to run is only available when running directly inside a hosting application like Teams, Outlook, or the Microsoft 365 app. It cannot be used on a service or on a backend (like in a bot).
> 
> What information are you looking to use team-js for in your bot? There may be an alternate way to get that info.

Thank you for the explanation.
I need the team's login information. I want to get the id value of the logged in user, is it possible? Should I use the graph API?

**Comment by ChetanSharma-msft** [comment]
Hello @Seongjun2 - Yes, you can get the id/AadId of user using context/turncontext of bot like below:
turnContext.Activity.From.Id or turnContext.Activity.From.AadObjectId.
https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/bot-request-approval/csharp/BotRequestApproval/Bots/ActivityBot.cs#L105

Reference docs:
https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?tabs=dotnet#get-the-user-id-team-id-or-channel-id

Alternatively, you can call Graph API to get the user details.
https://learn.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0&tabs=http

**Comment by ChetanSharma-msft** [comment]
@Seongjun2 - Please let us know if you have any further query.
Also, please share your valuable feedback [here](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u).
