### ISSUE TITLE
setValidityStatus() not working on 1.4.0

### ISSUE THREAD

**Issue by kharenzze** [OfficeDev/microsoft-teams-library-js#187]
I just upgraded from 1.3.7. The main breaking change I had to do to make my code compile was changing the way I import microsoftTeams to:
`import * as microsoftTeams from '@microsoft/teams-js'`
The point is that now, the save button is never activated, even if I call `microsoftTeams.settings.setValidityState(true); `

Am I missing another breaking change, or it's just broken?

**Comment by sachingupta** [comment]
Hi @kharenzze, We found some issue in minification of sdk js file and release a v1.4.1 with fix. Can you please use this version of sdk https://www.npmjs.com/package/@microsoft/teams-js/v/1.4.1 
Please let us know if you still see any issue.

**Comment by kharenzze** [comment]
Hi @sachingupta, It looks great! Thanks 😃
