### ISSUE TITLE
Show Status of a contact(Available/Busy/Offline)

### ISSUE THREAD

**Issue by SuneetAgarwal** [OfficeDev/microsoft-teams-library-js#1880]
### Motivation
**As a** End user of an enterprise business application  
**I want to** be able to know the availability status of my team members or fellow co-workers 
**So that** I can reach out to them via Microsoft Teams and collaborate with them to get a work done faster

### Details
For a logged in user to know the availability status of another person a Graph API call to get the presence is needed. As providers of enterprise softwares take a lot of protective measures to protect the data of there customers, we want to avoid Client side calling of Graph API but instead make a more secure servers side call.

### Requirement
Currently server side data fetching of user's teams status is not allowed. In order to allow this we request that the [Get Presence](https://learn.microsoft.com/en-us/graph/api/presence-get?view=graph-rest-beta&tabs=http) API starts supporting Permission type : Application.
This topic is actively tracked in a thread in Microsoft Community as well : [Graph API Presence should support Application permissions](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/graph-api-presence-should-support-application-permissions/idi-p/2276109).
Can you please let us know if there are plans to provide this feature. If yes, would be the expected timeframe

### Benefits
Contacts been displayed in enterprise business application can see the important status information without the need to navigate out of their current application and can reach out to them directly based on the person's availability

**Comment by Prasad-MSFT** [comment]
@SuneetAgarwal - Thanks for raising the request. We will check this with engineering team and will update accordingly.

**Comment by Prasad-MSFT** [comment]
@SuneetAgarwal - Engineering team is tracking this requirement. This is going to take some time. We will inform you once we hear any update.  
Also, you can now get latest Teams platform updates by subscribing to the RSS feed. 
[What's new - Teams | Microsoft Docs ](https://learn.microsoft.com/en-us/microsoftteams/platform/whats-new?pivots=ga-feature)

Thanks!

**Comment by SuneetAgarwal** [comment]
@Prasad-MSFT : Is there any update on this topic. Do you have a tentative timelines by when this is expected?

**Comment by Prasad-MSFT** [comment]
Hi @SuneetAgarwal - Currently we don't have any timeline details to share. Once we get any update from engineering team, we will notify in this thread. Thanks for understanding.

**Comment by Prasad-MSFT** [comment]
@SuneetAgarwal - We recently got confirmation from engineering team that, this feature is live now.

Thanks!

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
