### ISSUE TITLE
auth.getAuthToken() revoke consent

### ISSUE THREAD

**Issue by LeonYasoon** [OfficeDev/microsoft-teams-library-js#1882]
When calling auth.getAuthToken() for the first time in a tab SSO environment, the user is presented with a consent screen where they have to pick an account. If they pick "the wrong account", there is no possiblity to present them with the consent screen again. They are stuck with this account and subsequent calls to auth.getAuthToken() will always silently return the token for the chosen account. auth.getAuthToken() has a parameter called "silent", which according to the comments in the source code "allow[s] a prompt to be shown" but this parameter has no effect whatsoever. 

In Azure AD, the auth.getAuthToken() does not add an entry to the "Users and groups" section of the enterprise registration of the app in which the tab SSO consent was given, which makes it impossible even for the admin to revoke that consent.

The only occurence of these getAuthToken calls is inside of the "Sign-in logs" of the enterprise application of the Microsoft Teams Web Client itself, referring to the app in which the tab SSO was performed in the "Resource" column. Also, no option to revoke consent here.

It would be great if there was either a programmatic or admin UI way of revoking that consent, so users can attempt the consent again and select the "correct" account.

**Comment by nwojod-MSFT** [comment]
Thanks @LeonYasoon for reporting this issue. We will investigate this and provide an update. Thanks

**Comment by LeonYasoon** [comment]
Hey @nwojod-MSFT the host platform is the Teams client, either native or mobile doesn't matter. This is happening in Teams, haven't tested in Outlook.

**Comment by nwojod-MSFT** [comment]
@LeonYasoon thanks for the clarification. We will investigate this further and update you.

**Comment by Prasad-MSFT** [comment]
@LeonYasoon - Could you please provide a repro video along with the steps and sample code which you are using? We tried with this [sample](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-sso) but were not able to repro this issue.
