### ISSUE TITLE
Deeplink target to a customized uploaded app doesn't work on iOS latest teams client. (Link not supported. You can't open this link on the mobile app)

### ISSUE THREAD

**Issue by kafka-yu** [OfficeDev/microsoft-teams-library-js#1883]
As title mentioned, it cannot jump back to the teams app via the deep-link url open on iOS, e.g.
> https://teams.microsoft.com/l/entity/app-Id/home

the `appId` is the id in the manifest, and the app is uploaded via a developer account.

Any ideas? We assume it is due to the AppId is not correct? Are we able to get the id from the context via the sdk?
Thanks.

In the older MS Teams mobile app, it works, but looks like it becomes not working in the recent days.

<img width="601" alt="image" src="https://github.com/OfficeDev/microsoft-teams-library-js/assets/3942409/4b1b6da6-6b54-4bcf-8569-5eca93f5b84c">

**Comment by nwojod-MSFT** [comment]
@kafka-yu thank you for reporting this issue. What function are you using for deeplink and are you getting any errors? If you are using the [shareDeepLink ](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/pages?view=msteams-client-js-latest#@microsoft-teams-js-pages-sharedeeplink) function, this function is not currently supported on mobile. 

The manifest's appID is not the actual one as the host masks it for uniqueness.

The appID cannot be generated via context and there is no way to retrieve it programmatically. We plan to add a feature to retrieve it, but we don't know when it will be implemented.

**Comment by kafka-yu** [comment]
@nwojod-MSFT In our app, we invoke this URL in the system's browser tab:
> https://teams.microsoft.com/l/entity/app-Id/home

We expect it can jump back to Teams and then go to the particular app of the `app-id` (which is uploaded via the "Upload custom app" menu. 

It works correctly before. but recently it won't work in some mobile devices, but some of the devices still work. 

And not only for the "Custom upload app", but we also tried the app-id which is published in the Teams store. Some devices work, some do not.  (As the doc mentioned [here](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-application?tabs=teamsjs-v2#app-id-used-for-different-apps) the app-id is same as the manifest id if it is published in store.

<img width="568" alt="image" src="https://github.com/OfficeDev/microsoft-teams-library-js/assets/3942409/2567a2fa-f5e1-4a11-a10a-a0230c34c857">

**Comment by nwojod-MSFT** [comment]
@kafka-yu thanks for the additional info. For the mobile devices that does not work, does it have the same version for the ones that works correctly? We tried to create a similar link on our end, and it worked fine. Please what version of teams-js are you using?

**Comment by kafka-yu** [comment]
@nwojod-MSFT The Teams app version is different, but I cannot remember which version is was that worked. 

For now, if the deep-link targets to the app (manifest-id) that is side-loaded via "Custom upload", it doesn't work, If the link targets to the app we published in app store, it works.

Can I share the test accounts and apps from our side to your for testing and debugging?

**Comment by kafka-yu** [comment]
any insights? @nwojod-MSFT

**Comment by Nivedipa-MSFT** [comment]
@kafka-yu -Could you please share the test accounts and the app with us so that we can test it on our end?

**Comment by kafka-yu** [comment]
@Nivedipa-MSFT Thanks for responding! Is there a way I can share the account with you? It contains credential info.

**Comment by Nivedipa-MSFT** [comment]
@kafka-yu - Could you please send an email to microsoftteamsdev@microsoft.com.

**Comment by kafka-yu** [comment]
@Nivedipa-MSFT Thanks, I sent an email to this addr. 
Subject:  Credentials for Issue https://github.com/OfficeDev/microsoft-teams-library-js/issues/1883

Pls help check again. Thanks.

**Comment by Nivedipa-MSFT** [comment]
@kafka-yu - Apologies for the delay, We will check and update you soon.
