### ISSUE TITLE
executeDeepLink to channel app not working in the new teams desktop client

### ISSUE THREAD

**Issue by nbelyh** [OfficeDev/microsoft-teams-library-js#1885]
In the "new" teams desktop client (see system info below) the navigation links to channel appears to be broken.

Client information:
```
You have Microsoft Teams version 23202.1509.2295.2283.
You've got the latest version. It was last updated on 8/16/2023.
The client version is 49/23072301051.
```

When you click a link that should bring you to a specific TAB (app) in a specific team/channel, it does not open the tab.
The "old" client works, the web client does it as well, the Android client works as well.

It is only "new" teams desktop client where it does not work.
The new client switches to the correct TEAM and CHANNEL, but does not switch to the correct TAB in that channel (see video below).
That means, the content (application) IS opened, but the active tab is not set. See video below.

[See documentation on application deep links here](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-application?tabs=teamsjs-v2#configure-deep-link-to-browse-within-your-app-manually)

The link I mean:
```
https://teams.microsoft.com/l/entity/<appId>/<entityid>?context={"channelId":"<channelid>"}
```
Example of such a link:
```
https://teams.microsoft.com/l/entity/04239e5b-bcbb-4548-8ead-780874cd8fbf/1a9684175f7c482db867f192b051f441?context=%7B%%22channelId%22:%2219:eRbzh3LV2QpWDe2cHwCrxt6EgMxE2ZQxVCPeds8LjZ41@thread.tacv2%22%7D
```

Video where I explain the problem:
[![IMAGE ALT TEXT](http://img.youtube.com/vi/-UXYOr6oV0o/0.jpg)](http://www.youtube.com/watch?v=-UXYOr6oV0o "Video Title")

**Comment by Nivedipa-MSFT** [comment]
@nbelyh - Thanks for reporting your issue. We will test this and update you soon.

**Comment by nbelyh** [comment]
No, for me, the link works but the teams tab is not selected. I do not experience this popup in the new teams.

**Comment by nbelyh** [comment]
Today the Teams client was updated and it started working. Works in build:
```
You have Microsoft Teams version 23217.803.2295.6624.
You've got the latest version. It was last updated on 8/18/2023.
The client version is 49/23080601411.
```

**Comment by nbelyh** [comment]
Closing as fixed.

**Comment by Nivedipa-MSFT** [comment]
@nbelyh - Glad to hear that your issue is resolved. Could you please share your valuable feedback via [Microsoft Teams Developer Community Response Feedback](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u).
