### ISSUE TITLE
How to allow users to sort when performing a search command?

### ISSUE THREAD

**Issue by catmanjan** [OfficeDev/microsoft-teams-library-js#1887]
We have a search command that is returning results in a "most relevant" sort order - but users may want to sort by date or alphabetically.

How do we support this from Teams? There doesn't seem to be any UI that allows sorting, so is this just a limitation?

**Comment by Prasad-MSFT** [comment]
@catmanjan - Teams does not provide a built-in UI for sorting while performing a search command. To achieve your requirements, we recommend you give your feedback in [Teams Feedback Portal](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472).

Thanks!
