### ISSUE TITLE
Microsoft Teams JS SDK initialization timed out when try to implement custom  tab in Teams 

### ISSUE THREAD

**Issue by teamreactwts** [OfficeDev/microsoft-teams-library-js#1894]
We are facing an issue in the SDK - 

Version - "@microsoft/teams-js": "2.9.1",
Issue - 
1. When I am running inside the team environment I am getting this error  **Error: SDK initialization timed out.**
2. When I am running the app in Chrome I am getting this error: **VM424:1 Error: Initialization Failed. No Parent window found.**

My dependencies are : 
  "dependencies": {
    "@azure/msal-browser": "^2.11.0",
    "@fluentui/react-components": "^9.0.0-rc.10",
    "@microsoft/teams-js": "^2.5.0",
    "crypto": "^1.0.1",
    "eslint": "^8.47.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "^6.4.3",
    "react-scripts": "5.0.1"
  },
  
  
  
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/121109383/574eba58-a564-4624-b7b7-1414face0e40)

**Comment by Nivedipa-MSFT** [comment]
@teamreactwts - Thank you for reporting your issue. Could you please share on which platform (web, desktop, mobile) you are facing this issue?

**Comment by Nivedipa-MSFT** [comment]
@teamreactwts - We tested this using Teams JS v2.9.1, and it worked in both the Edge and Chrome browsers. Could you please share detailed reproduction steps and a screen recording to facilitate further investigation?

**Comment by Nivedipa-MSFT** [comment]
@teamreactwts - We are checking this internally, we will update you soon.

**Comment by TrevorJoelHarris** [comment]
@teamreactwts I made a simple 2.9.1 Teams app using Teams Toolkit. You can see the app's code here: https://github.com/TrevorJoelHarris/TeamsAppExamples/tree/main/TeamsJsTwoNineOne

The README file has instructions on how to run it locally (just open it in VSCode and press F5). I've had 2 people verify that that app is initializing correctly in web Teams. Give that a try and see if it is working for you. If it is, you should compare what that app is doing to what your app is doing and see what the differences are.

**Comment by mathihalli** [comment]
@Nivedipa-MSFT Any updates on this? I'm also seeing it (on both Teams browser and App).

I've tried upgrading and downgrading the library - from 2.9.1 to 2.15.0 without any luck?

<img width="694" alt="Screenshot 2023-09-26 at 2 16 58 PM" src="https://github.com/OfficeDev/microsoft-teams-library-js/assets/18518769/1b33990e-de09-4783-844c-c4c3f07e8f96">

**Comment by Nivedipa-MSFT** [comment]
@mathihalli - Could you please let us know if you have tried this?
https://github.com/OfficeDev/microsoft-teams-library-js/issues/1894#issuecomment-1701511321

We have tried at our end and we are still not able to repro this.

**Comment by mathihalli** [comment]
@Nivedipa-MSFT - That did not work for us.

But, I found this API:  microsoftTeams.pages.navigateCrossDomain(url).
Turns out if you're migrating away (to a different domain), you'll have to
use this first.

After I changed that, the issue was resolved.

**Comment by vikramtha** [comment]
@mathihalli This is interesting, so to be clear, you weren't able to navigate to a different domain until you used pages.navigateCrossDomain? Did you try: "window.location.href." Also, was the new domain in the validDomains section of the manifest?

**Comment by mathihalli** [comment]
Yes - that's right. I tried whitelist-ing the domains in validDomains and
also tried window.location.href. The microsoftTeams.app.initialize() and
getContext would timeout consistently.

But when I navigated using the pages.navigateCrossDomain, both the
initialize() and getContext() works fine
