### ISSUE TITLE
Deep link does not work in new Teams

### ISSUE THREAD

**Issue by tjosepo** [OfficeDev/microsoft-teams-library-js#1900]
Hi 👋

Our custom Teams App is using deep links to navigate users to sub-pages inside the iframe of our application.

Our deep links look like this:

```
https://teams.microsoft.com/l/entity/<app_id>/home?context={"subEntityId": "url=/subpage?id=12345"}
```
<sup>The URL is shown in plaintext for clarity. The real one we use is URL encoded properly.</sup>

This works on web Teams and old Teams, but not on new Teams where we get this message:

![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/44372776/183a21e2-140f-4177-8cf0-944a2b94c235)

It's unclear when this feature will be supported in new Teams or if there's an existing alternative.

[As per the documentation](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-application?tabs=teamsjs-v2), I tried using this library to generate a deep link:

```
teams.pages.shareDeepLink({ subPageId: "url=/subpage?id=12345" })
```

Unfortunately, the generated link was completely broken. It didn't open the app. Instead, if just opened the "Chat" tab at the first conversation. 

The generated link looked like this:

```
https://teams.microsoft.com/l/entity/<app_id>/_djb2_msteams_prefix_2479942178?label=Home&context={
++"subEntityId":+"url=/approvals?id=12345",
++"chatId":+"<chat_id>",
++"contextType":+"chat"
}&tenantId=<tenant_id>
```

# Questions:

- When will deep links be supported in new Teams? Is there an alternative way to achieve this effect in the meantime?
- Am I using the `teams.pages.shareDeepLink()` function wrong or is this an actual issue with it?

Deep links are quite important for an upcoming feature of our apps, so we would like to find an alternative for new Teams.

<s>On a side note, the type definitions for the `teams.pages` module did not have any Intelliscene in VS Code. Do I need a specific setup for them to work properly?</s> **Edit:** Just needed to restart VS Code with fewer background processes.

Thank you for you time. 🙇

Let me know if you need more information.

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this, we will check this and get back to you.

**Comment by ChetanSharma-msft** [comment]
Hello @tjosepo - Sorry for delay in response.
We are actively checking this with engineering team and let you know the updates.

**Comment by Meghana-MSFT** [comment]
@tjosepo - Apologies for the delay, bug has been already raised for this issue. We are following up with the team. We will keep you posted on the updates. Thank you.

**Comment by Meghana-MSFT** [comment]
@tjosepo - Could you please share the exact URL with encoded parameters and test credentials where the issue is reproduced.  Engineering team needs these details to find the root cause of the issue. Please share these details at microsoftteamsdev@microsoft.com.

**Comment by tjosepo** [comment]
I just tried it again, and it seems like deep links are now being supported in new Teams. That resolves my issue, so I will close this ticket.

Thank you for your time 🙇
