### ISSUE TITLE
Deep link chat does not work in the new version of teams

### ISSUE THREAD

**Issue by Tryal1** [OfficeDev/microsoft-teams-library-js#1904]
Hello. 

Our custom teams application uses deep link chat.
In the old version of Teams it works perfectly, but in the new one it doesn't
The function we are using to make these links is chat.openChat()

This is how we use this deep link:
```
chat.openChat({
        user: email,
        message: `${messageUser}`,
      });
```

This function in the new version as an error returns an empty object.

Thanks for the help.

**Comment by Prasad-MSFT** [comment]
@Tryal1 - Thanks for raising the issue. We will check this from our end and respond back with our findings.

**Comment by Prasad-MSFT** [comment]
@Tryal1 - We tried to repro this issue using below code snippet
```
const chatPromise = chat.openChat({ user: ["adelev@M365x17798679.onmicrosoft.com"], message: "Hi Adele!" });
    chatPromise.
        then((result) => { console.log(result) }).
        catch((error) => { console.log(error) });   
```                     
following [this sample](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/d166d0193f4e6560718adda94c4c8ab946d7342a/samples/tab-deeplink/csharp) and it works fine at our end in new Teams T2.1.
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/62237649/afa077fd-608d-477b-b413-ef4fd9d5175c)

On clicking the deep link button 'Open', its redirecting to chat with specified user as shown in below images.
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/62237649/4b9915c7-7223-4bba-b977-6cc43aafd347)
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/62237649/dfde7f64-d11b-4288-b5c8-00b4cd70bc52)
