### ISSUE TITLE
Modal Submission on teams keeps loading on web version of teams

### ISSUE THREAD

**Issue by thisisbkm** [OfficeDev/microsoft-teams-library-js#1906]
The described issue pertains to the malfunctioning behavior of a modal submission button within our Microsoft Teams application. We are using the `microsoftTeams.submitTask()` method with the `@microsoft/teams-js` SDK version 1.12.1, and our manifest version is v1.12.
Importantly, this problem is occurring exclusively within the web version of Microsoft Teams, while the mobile and desktop versions are unaffected and perform as expected. Additionally, it's worth noting that this issue is limited to a specific subset of our team members.
Please provide guidance as it appears to be a platform-specific issue on Microsoft Teams' end.

**_The modal submission payload_**
`microsoftTeams.tasks.submitTask(
      { value: 'submitButton', formData },
      "appIdForTeams"
    );`
    
  Source: Web version of teams
![data](https://github.com/OfficeDev/microsoft-teams-library-js/assets/44224854/16546f9e-2aaa-48d4-ad2c-2ff8a4af44ce)

**Comment by nwojod-MSFT** [comment]
Hi @thisisbkm thank for reporting this issue. We were able to repro the same behavior when we add an incorrect appId. However, with a valid appId, the dialog closes and submits successfully. Note- we can't confirm if that is what's causing the issue. Can you try removing the app id from the submitTask call and see if that fixes the problem?

**Comment by thisisbkm** [comment]
Hey @nwojod-MSFT 
1. I can confirm that appId is being passed correctly
2. I also mentioned that modal is being submitted successfully with mobile & desktop version of teams & it's only occurring for subset of users.

**Comment by Nivedipa-MSFT** [comment]
@thisisbkm - We are checking this internally, we will update you soon.
