### ISSUE TITLE
Admin consent request not working on some tenants

### ISSUE THREAD

**Issue by CptTony** [OfficeDev/microsoft-teams-library-js#1909]
We are going through the app submission process for ms teams and ran into the following problem during the review process.

Our tab application requires certain azure  permissions that can only be granted by admins (ie: EduAssignments.ReadWriteBasic). To achieve this, we use the grant process described [here](https://learn.microsoft.com/en-us/graph/auth-v2-service?tabs=http#3-request-administrator-consent).

When the user is not an admin, the dialogue correctly notifies them they can't grant the permissions and must contact an administrator. When the user does happen to be an admin, the dialogue allows them to grant permissions for the whole tenant.

This is working on our own tenant but its failing in the tenant that the Teams App Submission Review team is using.

For our tenant, the flow works and successfully grants permissions for everyone unlocking the application.

On the review team's tenant, the grant flow seems to work and returns with a successful response to our redirect URI. However, the permissions are never actually granted for anyone in the tenant even though we receive the redirect with the admin_consent=True param as expected from reading the docs.

We get the following error when trying to use the APIs (Expected if the permissions have not been granted)

`{
    "status_code": 424,
    "errors": "invalid_grant",
    "message": "AADSTS65001: The user or administrator has not consented to use the application with ID 'XXXX-XXXX-XXXX-XXXX-XXXX' named 'X App'. Send an interactive authorization request for this user and resource.\r\nTrace ID: XXXX-XXXX-XXXX-XXXX-XXXX\r\nCorrelation ID: 2d863503-7787-4363-9ad9-6fbed7e46510\r\nTimestamp: 2023-08-31 15:03:09Z"
}`

Is this a bug? It seems like the redirect should receive some kind of error if the permissions have not actually been granted for any reason.

**Comment by sayali-MSFT** [comment]
@CptTony - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by sayali-MSFT** [comment]
@CptTony -A related thread is ongoing here -https://github.com/OfficeDev/microsoft-teams-library-js/issues/1770
Are you facing same issue?

**Comment by CptTony** [comment]
No, this is a different issue.

We have initiated and successfully gone through an admin grant request as described here: https://learn.microsoft.com/en-us/graph/auth-v2-service?tabs=http#3-request-administrator-consent

This method allows you to pass a redirect uri which is called with the result of the operation. We get a positive result according to the documentation (admin_consent=True).

However, in the tenant that Microsoft's app submission review team is using, the permissions never take effect.

In our tenant they do work.

**Comment by sayali-MSFT** [comment]
@CptTony -We will check this at our end and will get back to you.

**Comment by CptTony** [comment]
There are no errors. The grant process returns to our redirect uri with admin_consent=True and zero errors.

We do run into an error when you try to access the app without consent, but that is expected. Its mentioned above but I don't think its relevant.

The problem lies in the admin authorization flow. It behaves as if permissions were granted but they were not.

**Comment by sayali-MSFT** [comment]
@CptTony -Could you please provide information regarding the request below?
 1. Where is this error coming back from?
 2. Which auth flow is this app using?
 
  If an app needs Graph permissions but doesn't have admin consent then they need to take the user through an interactive login/consent flow on the client first as documented here:

https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-graph-api?tabs=dotnet#from-the-user

**Comment by CptTony** [comment]
1. As mentioned in previous posts, there is no error. The grant flow returns perfectly as if permissions were properly granted but they don't actually take effect in the Azure cloud. The return params are described in the first post.
2. We are using the admin consent link flow described here: https://learn.microsoft.com/en-us/graph/auth-v2-service?tabs=http#3-request-administrator-consent

I don't think that last suggestion applies in our case. We are asking the admin to grant tenant-wide permissions. The permissions we require cannot be granted by users. We are using the process documented here: https://learn.microsoft.com/en-us/graph/auth-v2-service?tabs=http#3-request-administrator-consent

Here is a video of the issue: https://drive.google.com/file/d/1s37GwvR-5gsSO_lA1FbezqjILUmmiOse/view

At the end, the application can't successfully talk to the graph API and gets the following error (which we dont show in the video but it can be seen in the debugger):

`{ "status_code": 424, "errors": "invalid_grant", "message": "AADSTS65001: The user or administrator has not consented to use the application with ID 'XXXX-XXXX-XXXX-XXXX-XXXX' named 'X App'. Send an interactive authorization request for this user and resource.\r\nTrace ID: XXXX-XXXX-XXXX-XXXX-XXXX\r\nCorrelation ID: 2d863503-7787-4363-9ad9-6fbed7e46510\r\nTimestamp: 2023-08-31 15:03:09Z" }`

But I want to emphasize that we have already done an interactive grant request in the video with an admin. The error should not happen if the grant process was actually taking effect. However the grant process is not returning any errors (as highlighted in the video)

The expected behavior would be that if there was a reason for the permissions to not work, azure should return an error in the callback but it doesn't.

**Comment by sayali-MSFT** [comment]
@CptTony - We got the reply through engineering team- 
what is the Client ID of the app that the developer has registered in the AAD portal? Has the developer followed all of the instructions here fore registering their app:
https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-register-aad
 
Especially this part:
<img width="790" alt="MicrosoftTeams-image (11)" src="https://github.com/OfficeDev/microsoft-teams-library-js/assets/93527375/8784bf15-066c-4819-b223-6a3bcaa89b2e">

 
Also, have they specified the EduAssignments.ReadWriteBasic scope in their app's API permissions as documented here:
https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-graph-api?tabs=dotnet#to-configure-api-permissions
 
If they've done all that and are still seeing issues, then I think you should reach out to the Identity Org for further assistance:
https://review.learn.microsoft.com/en-us/identity/microsoft-identity-platform/get-help?branch=main

**Comment by CptTony** [comment]
The client id for our app is: b2d5bd5a-3e56-4c90-8f2f-cf782bb95c17

This application is meant to be used in multiple tenants. We are currently in the application submission review process for the msteams app store. The review team is testing the application in their tenant and that is where the problem occurs.

We have indeed added the relevant API permissions according to (https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-graph-api?tabs=dotnet#to-configure-api-permissions)

This application and the admin permission grant process works in our tenant but fails in the tenant owned by the microsoft app submission review team.

I tried following the last link you provided (https://review.learn.microsoft.com/en-us/identity/microsoft-identity-platform/get-help?branch=main) but it gives me a 403 Forbidden error, can you please review?

Thanks

**Comment by sayali-MSFT** [comment]
@CptTony -Could you please try to open the link using this page as well-
https://identitydocs.azurewebsites.net/static/v2/getting_started.html

**Comment by sayali-MSFT** [comment]
@CptTony -Did you get a chance to raise the query using the given link?

**Comment by CptTony** [comment]
We're not able to access that link either. For some reason it gives us an azure security error saying the account is suspended. But it isnt, we're able to access the dashboard and use everything else just fine

**Comment by sayali-MSFT** [comment]
@CptTony -If possible, can you please share the app package for this app so we can try to set it up and debug the issue?

**Comment by ChetanSharma-msft** [comment]
Hello @CptTony - Please confirm whether your issue has resolved or still looking for further help?
If not resolved, please share the app package, so that we can try to test it?
