### ISSUE TITLE
Teams bot deployment is too complicated

### ISSUE THREAD

**Issue by catmanjan** [OfficeDev/microsoft-teams-library-js#1910]
I have just been working with a customer to deploy our Teams bot and the steps are too complicated

We have a bot that is using SSO to another app and there are so many things that need to be set up and barely any feedback whether its set up correctly

The whole process really needs to be streamlined, we are already providing a manifest, why isn't the bot stuff baked into it for example?

**Comment by Nivedipa-MSFT** [comment]
@catmanjan - Thanks for reporting your issue. We are checking this internally. We will update you soon.

**Comment by ChetanSharma-msft** [comment]
Hello @catmanjan - We have migrated NodeJS sample to use Teams toolkit: https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-teams-authentication/nodejs

Now, you can quickly provision and deploy your code without manually creating the azure resources.

Also, please confirm whether you are referring below documentation?
https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/add-authentication?tabs=dotnet%2Cdotnet-sample

If yes, could you please elaborate which section and steps are complicated in the documentation, so that we can look into that specific section?

Thanks!!

**Comment by catmanjan** [comment]
@ChetanSharma-msft yes that doco is pretty close to what we have to ask customers to do to set up our app - the whole thing is too complicated, there are so many steps and little validation occurs, so if the person who is setting up the bot (who is likely not a developer themselves) makes a mistake it takes hours to backtrack and resolve the issue...

What I don't understand is why uploading the manifest file doesn't automatically register the bot and configure the SSO URLs, given all the details are already provided in that

**Comment by catmanjan** [comment]
@ChetanSharma-msft something else I noticed, in your link above it says

`Token Exchange URL. Leave this blank.`

But in this link https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/bot-conversation-sso-quickstart/BotSSOSetup.md

It says `For the Token Exchange URL use the Application ID URL obtained in step 1.3`

**Comment by Prasad-MSFT** [comment]
@catmanjan - The purpose of the Token Exchange URL is to facilitate the exchange of tokens between the Teams client and the bot service. It allows the bot service to obtain the necessary access token for the user, which can then be used to authenticate and authorize the user's actions within the bot.
By setting up the Token Exchange URL correctly, you can enable SSO for your bot and allow users to seamlessly authenticate and interact with your bot

**Comment by catmanjan** [comment]
@Prasad-MSFT what should the Token Exchange URL be set to?

It is unclear because this set of documentation says to leave it blank: https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/add-authentication?tabs=dotnet%2Cdotnet-sample

This set says to set it too the app ID URI: https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/bot-conversation-sso-quickstart/BotSSOSetup.md

This set says to set it to the "URL associated with the OAuth connection" (whatever that means?): https://learn.microsoft.com/en-us/azure/bot-service/bot-builder-concept-identity-providers?view=azure-bot-service-4.0&tabs=adv2%2Cga2

**Comment by Prasad-MSFT** [comment]
@catmanjan - While doing SSO with Azure AD, Token Exchange URL need to set up as the Application ID URI.
The application ID URI format must be: `api://fully-qualified-domain-name.com/{AppID}`
If you're building an app with a bot, a messaging extension, and a tab, enter the application ID URI as `api://fully-qualified-domain-name.com/BotId-{YourClientId}`, where the BotID is your bot app ID.
Ref: https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-register-aad#to-expose-an-api
This URI we use as Token Exchange URL in OAuth Connection Settings
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/62237649/643f8787-3d12-46e9-8569-3d4dd0116527)

**Comment by catmanjan** [comment]
@Prasad-MSFT again that doco is very confusing "api://fully-qualified-domain-name.com/BotId-{YourClientId}, where the BotID is your bot app ID" does this mean replace {YourClientId} with BotID, or "BotId" with BotID?

**Comment by Prasad-MSFT** [comment]
Yes @catmanjan - The doc is bit confusing, it should be mentioned like: 
If you're building an app with a bot, a messaging extension, and a tab, enter the application ID URI as `api://fully-qualified-domain-name.com/BotId-{YourClientId}`, where {YourClientId} is your bot app ID.
That means replace {YourClientId} with BotID. 
We will raise a doc enhancement request for the same.

Regarding the Token Exchange URL, it is mentioned in the step-by-step guide whose reference is given [here](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-overview#step-by-step-guides).

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now. Please feel free to reopen if required. Thanks!

**Comment by catmanjan** [comment]
@ChetanSharma-msft I see the doco is updated now, but that doesn't fix the underlying issue that the whole process needs to be streamlined

As it is today, configuring an Azure Bot is not accessible or easy to do unless you're an Azure Bot developer

**Comment by Prasad-MSFT** [comment]
Thanks @catmanjan for informing. We will work with concerned team to make the whole process streamlined and will keep changing the documentation accordingly.
