### ISSUE TITLE
New Clipboard API (teamsJS v2.15) throws errorCode: 100 sourcing from geoLocation.ts

### ISSUE THREAD

**Issue by MichaMican** [OfficeDev/microsoft-teams-library-js#1921]
I was very happy when i saw that FINALLY clipboard functionality was added with [v2.15](https://github.com/OfficeDev/microsoft-teams-library-js/releases/tag/v2.15.0)

Unfortunately i have hit a few bumps right away
1. There is no documentation on https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/?view=msteams-client-js-latest
2. There is no example for clipboard on https://github.com/OfficeDev/Microsoft-Teams-Samples

So i was out for my own and tried to rewrite our `copyToClipboard` function as follows:
```ts
import { clipboard } from "@microsoft/teams-js";
// ...
function copyToClipboard(value: string) {
    var blob = new Blob([value], { type: "text/plain" });
    clipboard.write(blob);
}
```

Unfortunately when executing this (In my case through a on click on a Button) i got an error, seemingly sourcing from geoLocation.ts (WTF?) with 'errorCode: 100' - I wasn't able to find any details to this error - can you help?

<img width="575" alt="image" src="https://github.com/OfficeDev/microsoft-teams-library-js/assets/45571948/01d09c6d-3616-49b5-9ab9-32c499c9ccac">

Sidenote: When i make the copyToClipboard function async and i await the clipboard.write() function it throws the same error, but instead of pointing to geoLocation.ts it then points to the line where i call the clipboard.write() function

## App Context:
Teams App. Tested in Chrome Web browser (teams v1 not preview)

**Comment by ChetanSharma-msft** [comment]
Hello @MichaMican - Thanks for raising your query. We will look into it and let you know the updates.

**Comment by nwojod-MSFT** [comment]
@MichaMican apologies for the inconvenience. Currently, the clipboard API cannot be used as this is still in development and not yet available for public consumption. This was the initial check-in to prep the teamsjs for the upcoming API. The API is not yet supported across platforms and the errorCode:100 is expected and by design. We are just as excited as you are to have this capability and will update the documentation as soon as it's ready. Thanks for your patience.

**Comment by MichaMican** [comment]
@nwojod-MSFT 
Thanks for the update! That's a shame - how much work is left and is there maybe even an ETA for it?

And as a proposal for improvement/feedback: It should be made clearer in the change log (2.15 release) that thus is currently not working - it currently just states "add clipboard for programmatical access to the clipboard api" - which sounds as if it was added and up and running.

**Comment by nwojod-MSFT** [comment]
Hi @MichaMican apologies for the late reply. We are still planning on the release and thus do not have an ETA now. I will update this thread once we are able to lock on a set timeline. Thanks

**Comment by alicialu-MSFT** [comment]
@MichaMican can you try again? Functionality should be available now!

**Comment by MichaMican** [comment]
We are currently in a code freeze with the Project, as we are preparing our next release - however i will test and revert as soon as we are thorugh the release process and start the work on the next version ;)
