### ISSUE TITLE
shareAppContentToStage()   does not work in New Teams

### ISSUE THREAD

**Issue by sebiJo** [OfficeDev/microsoft-teams-library-js#1928]
When calling 

`microsoftTeams.meeting.shareAppContentToStage() `

in 'New Teams', it returns  `microsoftTeams.ErrorCode.NOT_SUPPORTED_IN_CURRENT_CONTEXT`

The call works correctly in Teams classic. This is problematic for us since many of our users have already switched to the new Teams.

In addition: This error code was usually returned when the user did not have presenter privileges, so it is even harder for us to show a good error message. Is it missing presenter privileges or the new Teams client? Both return the same errorCode.

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this, we will check it and get back to you.

**Comment by ChetanSharma-msft** [comment]
Hello @sebiJo - Sorry for delay in response. We will check on it and let you know the updates.

**Comment by Meghana-MSFT** [comment]
We raised a bug for this issue, we will keep you posted on the updates. Thank you.

**Comment by Meghana-MSFT** [comment]
@sebiJo - Could you please confirm if you tryied this in Teams Public Developer Preview ring (ring 3.6)?

A fix was made on Tuesday, so engineering team would like to confirm if this has been fixed.

**Comment by sebiJo** [comment]
Yes, it does work now, thanks a lot!!
