### ISSUE TITLE
Teams V2 - getContext API returns displayName in the userPrincipalName field.

### ISSUE THREAD

**Issue by boraunlu** [OfficeDev/microsoft-teams-library-js#1932]
In Teams V2, the getContext API returns displayName in the userPrincipalName field. Here is a screenshot of the context below;
<img width="528" alt="image" src="https://github.com/OfficeDev/microsoft-teams-library-js/assets/13998127/9d4ebe70-93a8-4d6d-bff3-fd5bc3a10a07">

When we switch back to V1, everything goes back to normal. The userPrincipalName switches back to normal, "MiriamG@teamblee.onmicrosoft.com".

Is this an expected behavior? 

Thank you

**Comment by Prasad-MSFT** [comment]
@boraunlu - We tried to repro this issue, but at our end in Teams V2, the `getContext` API returns correct `userPrincipalName` field
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/62237649/6253aa6d-ed45-4545-8a73-70d36e436365)

Tested in `Microsoft Teams Version 1.6.00.25871`
`teams-js/2.0.0`

**Comment by Prasad-MSFT** [comment]
@boraunlu - Glad to hear that it worked after upgrading. Could you please share your valuable feedback via [Microsoft Teams Developer Community Response Feedback ](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u)link?

**Comment by AE-MS** [comment]
> Thanks, updating the teams SDK version resolved the issue on our end as well. Sorry for taking your time.

Hi @boraunlu! Out of curiosity, what version of teams-js were you using before you upgraded, where you saw the problem?
