### ISSUE TITLE
External OAuth Provider questions

### ISSUE THREAD

**Issue by kafka-yu** [OfficeDev/microsoft-teams-library-js#1936]
Hi team,

Do you have any way to check if the Tab is running in the MS Teams new version?

Currently I saw it is like an Edge view?

Thanks.

**Comment by Meghana-MSFT** [comment]
Currently it is not possible to check if your Teams is working in new version or classic. You can only get the clientType from Tab context - 
https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context?tabs=Json-v2%2Cteamsjs-v2%2Cdefault#tabpanel_1_Json-v2

**Comment by AE-MS** [comment]
Hi @kafka-yu. Can you tell us more about why you'd use this information? We might be able to offer an alternative approach depending on what you're looking to do.

**Comment by kafka-yu** [comment]
We wanna to implement different login process on desktop client to resolve SSO login issue via Google account ext.  For classic version of Electron, we do external login process, but now in teams New version, looks like it is a browser window wrapped in client app? Not an electron window anymore, so we want to check if we can detect it.

**Comment by alicialu-MSFT** [comment]
Hey @kafka-yu , we have made some improvements to the external OAuth process where developers will not need to do client-specific implementations, i.e. you will not need to follow different approaches for Electron v. New Version of Teams. We are releasing documentation on this and I will keep you updated on ETAs.

**Comment by kafka-yu** [comment]
OK Thanks @AE-MS 
Pls kindly share me the ETA.

**Comment by alicialu-MSFT** [comment]
Hi @kafka-yu , new documentation is out and can be found here. The main takeaway is that you need to add a third placeholder in your authenticate call, {hostRedirectUrl}. https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/using-teams-client-library?tabs=javascript%2Cmanifest-teams-toolkit#authentication

**Comment by kafka-yu** [comment]
thanks @alicialu-MSFT 
Question, do I still need to implement the login flow in Tab via https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-oauth-provider?

**Comment by alicialu-MSFT** [comment]
@kafka-yu  Yes, across the board you should be using flagging isExternal = True in authentication.authenticate even for Google accounts. Any 3P auth will be completed through authentication.authenticate.

**Comment by kafka-yu** [comment]
thanks! @alicialu-MSFT One more question.

In this article, how can we do the redirect back to teams on the mobil device?
https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-oauth-provider#add-authentication-to-external-browsers

I saw it says: 
> You can add authentication to external browsers for tabs in mobile only.

But in the final it is jumping by redirecting to "msteams://teams.microsoft.com/l/auth-callback". While this link is not working on mobile device..

**Comment by kafka-yu** [comment]
One more question, for the `authId`, when will it become invalid (or gone)? or is there any timeout mechanism developer needs to be aware of?
 @alicialu-MSFT

**Comment by kafka-yu** [comment]
@AE-MS @alicialu-MSFT  Second question, I saw on the mobile device, when set the "isExternal: true", the authRedirectMethod is "deeplink", but when calling "msteams://xxx" that deep-link to redirect, it doesn't work..  Any idea?

Thanks.

**Comment by kafka-yu** [comment]
> Hi @kafka-yu , new documentation is out and can be found here. The main takeaway is that you need to add a third placeholder in your authenticate call, {hostRedirectUrl}. https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/using-teams-client-library?tabs=javascript%2Cmanifest-teams-toolkit#authentication

After added this parameter, the `authentication` cannot open the login window anymore on the mobile device..

**Comment by alicialu-MSFT** [comment]
@kafka-yu Which mobile client/platform are you trying to use?

**Comment by jekloudaMSFT** [comment]
> One more question, for the `authId`, when will it become invalid (or gone)? or is there any timeout mechanism developer needs to be aware of? @alicialu-MSFT

Hi @kafka-yu, the authId will timeout after 2 minutes if a result is not received. It also becomes invalid after a result is received for that authId, since the authId is unique per auth request

**Comment by kafka-yu** [comment]
> @kafka-yu Which mobile client/platform are you trying to use?


iPhone with iOS 16.

**Comment by kafka-yu** [comment]
> > One more question, for the `authId`, when will it become invalid (or gone)? or is there any timeout mechanism developer needs to be aware of? @alicialu-MSFT
> 
> Hi @kafka-yu, the authId will timeout after 2 minutes if a result is not received. It also becomes invalid after a result is received for that authId, since the authId is unique per auth request

Thanks @jekloudaMSFT 

Another question, for the desktop client, after external browser open, if I leave the Tab and go to another Tab/(or Teams page), the redirecting via the `authId` will be also not working right? Is it by design or are we able to make it to work?

**Comment by kafka-yu** [comment]
Any response to my questions? @jekloudaMSFT @alicialu-MSFT 

Appreciated.

**Comment by jekloudaMSFT** [comment]
> Thanks @jekloudaMSFT , 2 mins may be a little short for our case.. Are we able to extend it? like 10 mins?

There's no way to extend the timeout from the calling app. May I ask what scenario you have that requires a longer timeout?

> Another question, for the desktop client, after external browser open, if I leave the Tab and go to another Tab/(or Teams page), the redirecting via the `authId` will be also not working right? Is it by design or are we able to make it to work?

If I'm understanding this scenario correctly, the only limiting factor here is the timeout (i.e. the auth session will probably have timed out by the time you redirect). Is this something you're trying to do that requires the longer timeout?
