### ISSUE TITLE
Adaptive Card Issue in Microsoft Teams Tabs with teams-js and Angular

### ISSUE THREAD

**Issue by VinyP** [OfficeDev/microsoft-teams-library-js#1940]
### Description

We are currently facing an issue with adaptive cards within our Microsoft Teams tabs. This has been functioning correctly since the launch of our application, but we've recently encountered a problem.

### Steps to Reproduce

1. Navigate to the specific Teams tab.
2. Attempt to open the adaptive card using the following code:
```javascript
dialog.adaptiveCard.open(adaptiveCardDialogInfo, dialogResponse);
```

Expected Behavior
The adaptive card should open without any issues.

Actual Behavior
The application breaks. Additionally, when checking support for the adaptive card with:

```javascript
dialog.adaptiveCard.isSupported();
```
it returns **false**. We also receive an **errorCode: 100**, but no other explicit error message is displayed.

Environment Details
@microsoft/teams-js: 2.12.0
@angular/core: ^15.0.0

Any guidance or suggestions to resolve this issue would be greatly appreciated. Thank you!

Code:
```javascript

      card: JSON.stringify({
        type: "AdaptiveCard",
        body: [
         {
          type: "TextBlock",
          size: "Medium",
          weight: "Bolder",
          text: "Select user(s) in your organization."
         },
         {
          label: "1) Select user(s): ",
          isRequired: true,
          placeholder: "Search and select user(s)",
          type: "Input.ChoiceSet",
          choices: [],
          "choices.data": {
            type: "Data.Query",
            dataset: "graph.microsoft.com/users"
          },
          id: "selection",
          isMultiSelect: true,
          errorMessage: "Atleast one user must be selected."
         },
         {
          isRequired: true,
          label: "2) Message",
          type: "Input.Text",
          size:"Medium",
          placeholder: "Enter your message",
          id: 'message',
          errorMessage: "A message is required."
         },
         {
          type: "Input.Toggle",
          label: "3) Summary",
          title: "Include Summary?",
          valueOn: "1",
          valueOff: "2",
          value: "1",
          id: "sum_type"
         }
        ],
        actions: [
          {
            type: "Action.Submit",
            title: "Cancel",
            associatedInputs: "none"
          },
         {
          type: "Action.Submit",
          title: "Send"
         },
        ],
        $schema: "http://adaptivecards.io/schemas/adaptive-card.json",
        version: "1.4"
       })
    }
    // RUN 
    dialog.adaptiveCard.open(adaptiveCardDialogInfo, dialogResponse);
```

**Comment by nwojod-MSFT** [comment]
@VinyP thanks, we will investigate this issue and update you. Have there been any changes made on your end that may have caused the issue? Is the teamsjs version currently being used the same as the one that was working initially (v2.12.0)? We're trying to identify any potential breaking changes. Thank you.

**Comment by AE-MS** [comment]
Hello @VinyP. I investigated this today and it looks like there may be a bug in Teams here. We will investigate further and provide updates as we have them.

In the meantime, if you temporarily use the deprecated [tasks.startTask](https://learn.microsoft.com/en-us/javascript/api/%40microsoft/teams-js/tasks?view=msteams-client-js-latest#@microsoft-teams-js-tasks-starttask) method, does that workaround the issue for you?

**Comment by Nivedipa-MSFT** [comment]
@VinyP - Thanks for reporting your issue, we will test this and update you soon.

**Comment by VinyP** [comment]
from @industryintel.com

Any update? We have quite a few clients impacted by this.

Thank you.

________________________________

**Comment by VinyP** [comment]
> @VinyP - We have raised a bug for this. We will inform you once we receive any updates on it.

@Nivedipa-MSFT - Any update? We have quite a few clients impacted by this.

Thank you.

**Comment by AE-MS** [comment]
> > @VinyP - We have raised a bug for this. We will inform you once we receive any updates on it.
> 
> @Nivedipa-MSFT - Any update? We have quite a few clients impacted by this.
> 
> Thank you.

@VinyP did the workaround I suggested above work for you?

**Comment by Nivedipa-MSFT** [comment]
@VinyP - We are checking the status of the bug with engineering team, and we'll keep you informed as soon as we receive any updates.

**Comment by andrewconnell** [comment]
+1 on this... with slightly different scenario:

### Environment Details
- @microsoft/teams-js v2.15.0
- No Angular like OP, using React v18
- Project based on the Teams Toolkit for VSCode (v5.20) "Tab:React with Fluent UI" template

using the deprecated `startTask` works:

```typescript
const card = AdaptiveCards.declare(require('./selectorCard.json')).render({videoOptions: pickableVideos});

const dialogInfo: AdaptiveCardDialogInfo = {
  title: 'YouTube Video Selector',
  size: { width: DialogDimension.Large, height: DialogDimension.Large },
  card: JSON.stringify(card)
};

const submitHandler: microsoftTeams.dialog.DialogSubmitHandler = (dialogResult: any) => {
  console.log('dialog response', dialogResult);
};

// open dialog & handle response
// 🚨🚨🚨 known bug in TeamsJS SDK v2... reverting to deprecated v1 API
//  > https://github.com/OfficeDev/microsoft-teams-library-js/issues/1940
// microsoftTeams.dialog.adaptiveCard.open(dialogInfo, submitHandler);
microsoftTeams.tasks.startTask(dialogInfo as any, (err: string, dialogResult: any): void => {
  console.log('dialog response', dialogResult);
});
```

Error displayed in browser when I use the `dialog.adaptiveCard.open()` instead of `tasks.startTask()':

![Screenshot 2023-10-07 at 11 54 18 AM](https://github.com/OfficeDev/microsoft-teams-library-js/assets/2068657/61d5d9a9-5cdd-4bdd-b730-653c8999f426)

**Comment by VinyP** [comment]
@AE-MS.

Yes, we managed to implement this workaround successfully. 👍🏽

Thank you @andrewconnell

**Comment by madhavsharmaagra** [comment]
Any update on this issue. Is there any thing in the pipeline? Thank you in advance. @AE-MS @Nivedipa-MSFT

**Comment by Dinesh-MSFT** [comment]
We are checking the status of the bug with engineering team, and we'll keep you informed as soon as we receive any updates.

**Comment by QinshanSun** [comment]
@AE-MS @Dinesh-MSFT  any update on this issue?

**Comment by QinshanSun** [comment]
Per our test, we meet this issue in Firefox(firefox doesn't support new teams) or use old teams in chrome. When using new teams in chrome, dialog.adaptiveCard.isSupported() is true and dialog.adaptiveCard.open(adaptiveCardDialogInfo, dialogResponse) works.

**Comment by AE-MS** [comment]
@Dinesh-MSFT and/or @Nivedipa-MSFT are best suited to give the status updates. 👍

**Comment by Dinesh-MSFT** [comment]
We are actively checking the status of the bug with engineering team, and we'll keep you informed as soon as we receive any updates.

**Comment by Wajeed-msft** [comment]
@VinyP , @andrewconnell, @QinshanSun , @madhavsharmaagra  - Unfortunately, at this point, Teams Classic is locked down to further changes unless it's for critical security or accessibility issues. Developers can use the [task.startTask](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/tasks?view=msteams-client-js-latest#@microsoft-teams-js-tasks-starttask) APIs if they still need to target Teams Classic. For New Teams this functionality is working as expected. 

We've announced timelines for moving all customers off the Teams Classic client here: [Classic Teams users to be updated to new Teams after March 31, 2024](https://learn.microsoft.com/en-us/MicrosoftTeams/new-teams-automatic-upgrade-announced)
