### ISSUE TITLE
Cross-domain postMessage not working in iOS client

### ISSUE THREAD

**Issue by nbelyh** [OfficeDev/microsoft-teams-library-js#1941]
I am using a File Picker in a Teams tab application (from [FluentUI](https://pnp.github.io/sp-dev-fx-controls-react/controls/FilePicker/)).

The picker has a "stock images" tab, that is actually an iframe to:
https://hubblecontent.osi.office.net/contentsvc/m365contentpicker/index.html?p=3&app=1001&aud=prod&channel=devmain&setlang=${language}&msel=0&env=prod&premium=1${themesColor}

That iframe communicates with its parent (my tab) using a `postMessage`, reporting events such as "file selected" or "close".

The problem is, **on iOS**, the posted events **do not reach my tab** (i.e. the iframe host page). Most probably, the iframe policy settings in iOS app are not correct? (i.e. different from other clients), thus preventing cross-domain postMessage calls.

This works fine in:
- web browsers (also Safari on iOS)
- Android
- Desktop client

This does not work in:
- iPad and iPhone Teams apps

Microsoft Teams
Version: 5.17.0
Build: 5.17.77.2023172401/0914 (general)
Device: iPad 9th 

Any ideas of workaround or estimate for a fix?

**Comment by sayali-MSFT** [comment]
@nbelyh - Thanks for reporting your issue.
We will check this at our end and will get back to you.
