### ISSUE TITLE
Anonymous unfurling microsoftTeams.app requests hang

### ISSUE THREAD

**Issue by VolodymyrHensorskyi** [OfficeDev/microsoft-teams-library-js#1946]
There is an issue during sign-in from anonymous unfurl cards. Whenever a user clicks on the Sign in button a new screen appears and nothing happens. I debugged it and found that both essential requests for our app hang. 
`await microsoftTeams.authentication.getAuthToken({ silent: true })`
`await microsoftTeams.app.getContext()`
Microsoft Library returns neither success nor error. I tried upgrading the msteams-js library to the latest version (2.15) but it did not help. 
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/145112017/be8af42a-a711-4362-8a53-c4d4cd6e25e5)

**Comment by Nivedipa-MSFT** [comment]
@VolodymyrHensorskyi - Thanks for reporting your issue. We will check this and update you soon.

**Comment by VolodymyrHensorskyi** [comment]
Hi @Nivedipa-MSFT 
You may use the basic bot and initiate the functions I specified above. It's pretty straightforward.

**Comment by VolodymyrHensorskyi** [comment]
can you please reopen it?

**Comment by Nivedipa-MSFT** [comment]
@VolodymyrHensorskyi - We will test this and update you with our findings.
