### ISSUE TITLE
calendar.composeMeeting does not work correctly in Outlook.

### ISSUE THREAD

**Issue by twgolds** [OfficeDev/microsoft-teams-library-js#1950]
If I use the following URL

`https://teams.microsoft.com/l/meeting/new?subject=TOM MEETING &startTime=2023-0930T17:00:00&attendees=person@one.com`

And paste it into my browser, it will correctly open up the Teams meeting scheduler dialog, with the start date set to the correct time.

If I use the link from teams-js like this :

` microsoftTeams.executeDeepLink(' .... link ....');`

It will open the scheduler correctly in Teams.

However, if I use the following code and use **Outlook Desktop** as the host client, it will open the meeting scheduler dialog BUT not set the start date.

`microsoftTeams.calendar.composeMeeting({
                        attendees: ['person@one.com'],
                        startTime: '2023-0930T17:00:00',
                        subject: 'Meeting',
                        content: 'Discuss ..'
                    });`

It does set the attendees, subject and content, but does not set the startTime.

I have tried 'MM/DD/YYYY HH:MM:SS' as the date format, but that doesn't work either.

Any suggestions on how to make it work?

**Comment by ChetanSharma-msft** [comment]
Hello @twgolds - Thanks for raising your query.
We will look into it and let you know the updates.

**Comment by Meghana-MSFT** [comment]
Could you please make sure that start time of the meeting in MM/DD/YYYY HH:MM:SS format. - https://learn.microsoft.com/en-us/javascript/api/%40microsoft/teams-js/calendar.composemeetingparams?view=msteams-client-js-latest#@microsoft-teams-js-calendar-composemeetingparams-starttime

**Comment by twgolds** [comment]
Thanks.  As I said, I tried, the MM/DD/YYYY HH:MM:SS format and it doesn't work.

Correctly opens the meeting schedule for the person with subject & content but does not set the date/time correctly.

**Comment by Meghana-MSFT** [comment]
@twgolds - We already have a bug where if we pass tomorrow's date and time it's taking the current date and time. This issue was reported here - https://github.com/MicrosoftDocs/msteams-docs/issues/8969

**Comment by twgolds** [comment]
I've just tried it with the hard-coded times : 

`       startDateTime = '10/03/2023 20:00:00';
        endDateTime = '10/03/2023 20:30:00';`

And it still doesn't set the correct time ( for those of you reading in the future, today is 3rd October 2023 ).

So I'd say the bug is that it simply doesn't set the date/time within Outlook.

Maybe it's my version of Outlook Desktop ... I'll check for a later version.

Cheers

**Comment by Meghana-MSFT** [comment]
We got an update from engineering team saying, "This has been fixed and will be available in Outlook Desktop builds 16.0.17011 (or higher)."
