### ISSUE TITLE
Chat service types not aligned with the expected values downstream

### ISSUE THREAD

**Issue by dinoilic** [OfficeDev/microsoft-teams-library-js#1964]
# Issue

I was trying to work with chat openings from an app, and following the [docs](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/chat?view=msteams-client-js-latest#@microsoft-teams-js-chat-openchat) and the [interface](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/opensinglechatrequest?view=msteams-client-js-latest) for the open chat props I tried to do something simple as:

```ts
if (chat.isSupported()) {
  await chat.openChat({ user });
}
```

Where `user` is a single string containing a UPN. After this change has been deployed I noticed that there was an error, something along the lines "members.map is not a function". This led me to believe that somehow, somewhere downstream in `teams-js` code it's somehow expected that we pass in an array of people instead of a single UPN string. To test that I did the following:

```ts
if (chat.isSupported()) {
  await chat.openChat({ user: [user] as any });
}
```

Due to satisfying the interface, I had to do an explicit cast as `any`. Surprisingly, this worked well, so I looked a bit into the code.

The [interface](https://github.com/OfficeDev/microsoft-teams-library-js/blob/1a6f8c34275e605c6166b4fe9baa9b93c589008a/packages/teams-js/src/public/chat.ts#L26C3-L26C3) indeed expects a single UPN, however further down in the code we have two if branches:
1. If it's `runtime.isLegacyTeams` - the SDK invokes `createTeamsDeepLinkForChat()` with `user` in an array like `[openChatRequest.user]` as seen [here](https://github.com/OfficeDev/microsoft-teams-library-js/blob/1a6f8c34275e605c6166b4fe9baa9b93c589008a/packages/teams-js/src/public/chat.ts#L77C19-L77C19) however
2. If it's not `isLegacyTeams` then SDK invokes `sendAndHandleStatusAndReason` and sends and object where `members` is set to a single user: `members: openChatRequest.user`

Since the `args` that go into `sendAndHandleStatusAndReason` aren't typed, I can't figure out what's actually expected, however I believe this `members` is the same `members` that breaks on non existent `map` function, which makes sense as I pass in a single UPN.

Same issue would appear in `openGroupChat` as well where we have this block

```ts
if (openChatRequest.users.length === 1) {
  const chatRequest: OpenSingleChatRequest = {
    user: openChatRequest.users[0],
    message: openChatRequest.message,
  };
  openChat(chatRequest);
}
```
and all of this seems proven in this function where the SDK does this:

```ts
const sendPromise = sendAndHandleStatusAndReason('chat.openChat', {
  members: openChatRequest.users,
  message: openChatRequest.message,
  topic: openChatRequest.topic,
});
resolve(sendPromise);
```

And as per interface, `openChatRequest.users` is an array of strings here.

# Solutions

I guess we would need to make sure that a single user is wrapped in an `[]` if `members` is expected to be an array.

**Comment by sayali-MSFT** [comment]
@dinoilic - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by maglims** [comment]
@dinoilic , we are able to repro and working on a potential fix. In the meanwhile, we understand that you are not blocked on this and have workaround(pass in array). Please feel free to correct me if it is not the case.

**Comment by dinoilic** [comment]
Thank you @maglims - I do have a workaround yes :)

**Comment by ChetanSharma-msft** [comment]
Hello @maglims - Looks like fixes are merged. Shall we close this issue?
