### ISSUE TITLE
Win OS + New Teams Desktop auth popup not working, redirecting to login in browser

### ISSUE THREAD

**Issue by Ununtuplicate** [OfficeDev/microsoft-teams-library-js#1968]
Hi all,

We're experiencing an issue with the `authentication.authenticate(AuthenticatePopUpParameters)` auth / login flow.

The auth code is written per the [non-deprecated](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/authentication.authenticatepopupparameters?view=msteams-client-js-latest) `authentication.AuthenticatePopupParameters` passed to the function params. The auth process is not able to complete via the browser.

We have an app running in the Teams Client that requires an additional authentication step.
When trying to log in, the `ms.authentication.authenticate(params)` function does not open an auth popup. Instead, the auth is opened in the browser.

Example params, where `data` is a 3000 char length base64 string:
- url: `auth-start?${data}`,
- width: 400,
- height: 600

This login / auth flow works for:
- macOS + New Teams desktop app
- macOS + New Teams browser / web app
- Win OS + New Teams browser / web app

This login / auth flow _**does not**_ work for:
- Win OS + New Teams desktop app

The auth flow works when using the _**Old**_ Teams app (am changing between new and old via the top-left toggle). 

In the logs, it is being reported that: 
`Error: browser is blocking the url to open at ...url: origin/node_modules/@microsoft_teams-js.js...` 

Supplying the `isExternal` param as `true` or `false`, or omitting this param does not change the behavior.

This is only affecting the New Teams Desktop App on Windows (am currently testing on Windows 10).
Has the New Teams Desktop App changed its behavior in terms of allowing the opening of the authentication popup?

Using the latest package version: `"@microsoft/teams-js": "^2.15.0"`

Thanks!  
-Chris

**Comment by sakov-ms** [comment]
Hi @Ununtuplicate, could you share the version number for the New Teams Desktop App on Windows?

**Comment by Ununtuplicate** [comment]
> Hi @Ununtuplicate, could you share the version number for the New Teams Desktop App on Windows?

```
You have Microsoft Teams version 23257.2618.2432.4374.
You've got the latest version. It was last updated on 10/10/2023.
The client version is 49/23091420225.
```

**Comment by sayali-MSFT** [comment]
@Ununtuplicate - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by Ununtuplicate** [comment]
> @Ununtuplicate - Thanks for reporting your issue. We will check this at our end and will get back to you.

@sayali-MSFT 

Hi, just letting you know that one of my colleagues has lost the ability to toggle back to the old version of the Teams Desktop App.

App version info:
```
You have Microsoft Teams version 23257.2618.2432.4374.
You've got the latest version. It was last updated on 11/10/2023.
The client version is 49/23091420217.
```

**Comment by Ununtuplicate** [comment]
Another colleague ran a fresh install of Win 10 Professional to test our Teams Desktop app and has the following version:
```
You have Microsoft Teams Version 1.6.00.27573 (64-bit). 
It was last updated on 2023-10-10.
```

No client version number is provided.

On macOS Old Teams:
```
You have Microsoft Teams Version 1.6.00.27656. 
It was last updated on 08/10/2023.
```

On macOS New Teams:
```
Version 23247.720.2421.8365 (23247.720.2421.8365)
```

The popup auth flow is working both on the old and new Teams Desktop app, but we're not sure what to make of the versioning going from `v1` to `v23427`.

**Comment by alicialu-MSFT** [comment]
Hi @Ununtuplicate , we have made some changes on New Teams that are still flighting. I can provide you with an update once these are available on all versions of New Teams. 

For the existing working login flows, are you setting isExternal = false?

**Comment by Ununtuplicate** [comment]
> Hi @Ununtuplicate , we have made some changes on New Teams that are still flighting. I can provide you with an update once the changes are available on all versions of New Teams. That is most likely the reason you see the mismatch in behavior across Teams clients.
> 
> For the existing working login flows, are you setting isExternal = false?

Hi @alicialu-MSFT 

We're currently not providing the `isExternal` param to the popup auth method.
I tested with `isExternal` : `true` , `false` , `omitted` , with the same results. The docs say that it should be omitted in our case, and so we are not including it.

New Teams Desktop App + Windows is still the only combination for which the popup does not work. 

Please let me know when you release a new version and would like me to test.
I can test all configurations with/without extra params, just let me know.

Tyvm,
-Chris

**Comment by alicialu-MSFT** [comment]
Hi! Could you try to validate again now, and if that doesn't work, try in a week? We expect the feature to be generally available in one more week. 

And yes, since you are in an embedded scenario, you should set isExternal=false.

**Comment by Aurora12** [comment]
This is still broken in the Windows desktop app.

"@microsoft/teams-js": "^**2.18.0"** (latest at the moment)

```typescript
import * as ms from "@microsoft/teams-js";

const params: ms.authentication.AuthenticatePopUpParameters = {
	url: `auth-start?${data}`,
	width: 400,
	height: 600,
	isExternal: false,
};
```

This opens an external page in the browser instead of a popup inside the desktop app, and the auth flow is broken because of that. 

_Works fine in the classic Teams on Windows and Mac, works in Chrome with both kinds of Teams, works in macOS desktop app._

Teams app:
```
You have Microsoft Teams version 23320.3021.2567.4799.
You've got the latest version. It was last updated on 21/12/2023.
The client version is 49/23111630012.
```

OS:
```
Microsoft Windows 11 Pro
Version 10.0.22631 Build 22631
```

**Comment by Aurora12** [comment]
@sayali-MSFT @ChetanSharma-msft @alicialu-MSFT Do you want me to open a new issue?

**Comment by ChetanSharma-msft** [comment]
> This is still broken in the Windows desktop app.
> 
> "@microsoft/teams-js": "^**2.18.0"** (latest at the moment)
> 
> ```ts
> import * as ms from "@microsoft/teams-js";
> 
> const params: ms.authentication.AuthenticatePopUpParameters = {
> 	url: `auth-start?${data}`,
> 	width: 400,
> 	height: 600,
> 	isExternal: false,
> };
> 
> ms.authentication.authenticate(params).then(......).catch(......);
> ```
> 
> This opens an external page in the browser instead of a popup inside the desktop app, and the auth flow is broken because of that.
> 
> _Works fine in the classic Teams on Windows and Mac, works in Chrome with both kinds of Teams, works in macOS desktop app._
> 
> Teams app:
> 
> ```
> You have Microsoft Teams version 23320.3021.2567.4799.
> You've got the latest version. It was last updated on 21/12/2023.
> The client version is 49/23111630012.
> ```
> 
> OS:
> 
> ```
> Microsoft Windows 11 Pro
> Version 10.0.22631 Build 22631
> ```

Hello @alicialu-MSFT - Could you please share your inputs?

**Comment by alicialu-MSFT** [comment]
We currently have an open issue on Google Auth for embedded pop-ups in new Teams. I am working on getting an ETA for the resolution. In the meantime, if this issue is occurring on a different type of external auth, please let us know so we can flag it as a separate issue.

**Comment by Aurora12** [comment]
Thank you, brilliant! We are not using Google auth though, it's a custom tab app for Microsoft Teams with the popup authentication flow. I'm speaking on behalf of the OP because we work for the same company.

Perhaps, you can suggest a different auth mechanism we can use that definitely works?
This one seems very fragile — we had many issues with it in the past with every other release of Teams.

**Comment by ChetanSharma-msft** [comment]
Hello @Aurora12 - Could you please refer this sample: https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/app-complete-auth/csharp

Reference doc: https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-flow-tab

Please test and let us know if you are still facing any issue.
