### ISSUE TITLE
Authentication.authenticate doesn't work on mobile(iPhone 7)

### ISSUE THREAD

**Issue by Tyrcheg** [OfficeDev/microsoft-teams-library-js#197]
Hi
I have an integration app which is now available for mobile devices. After clicking on Sign in button, which invokes Authentication.authenticate method nothing happens. I've tried to debug but 
 exceptions or logs doesn't appear. In the link below the line of code, where interaction with msteams-js library  is finished and nothing is happening.
After getting of a messageId I get no errors and nothing is performing in terms of opening of a browser, authentication etc.

https://github.com/OfficeDev/microsoft-teams-library-js/blob/master/src/public/authentication.ts#L39

**Comment by JSteunou** [comment]
I think this is related to https://github.com/OfficeDev/microsoft-teams-library-js/issues/188

**Comment by Tyrcheg** [comment]
Hi @JSteunou 
We had an issue with 1.3.7 where after calling authenticate method Safari browser starts to open and after that we cannot perform any logic, coz of msteams auth flow

After upgrading to 1.4.1 when we call authenticate method nothing is happen at all. 
#199 issue nicely describes that issue

Look forward to hear any updates on this issue in #199 .
