### ISSUE TITLE
microsoftTeams.conversations.openConversation does not trigger onStartConversation

### ISSUE THREAD

**Issue by LeonardoZivieri** [OfficeDev/microsoft-teams-library-js#1971]
I've downloaded the [tab-conversations nodejs example](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-conversations/nodejs) sample from Microsoft-Teams-Samples, but can't run

Using the conversations.openConversation api, the tab open, but the onStartConversation function didn't triggered to recieve the conversation reference.

I've tried to change the sdk version 2.0.0 and 2.15, but no one was triggered the event.

I've created an simple message listener to debug if has some message sent by the Microsoft, but no message recieved.

The image above, you can see the getContext call from starConversation function, and a "true" data, no message informations recieved

![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/16085171/43a73565-b673-4cf8-9f7f-20cc0bc36207)

```html
        window.addEventListener(
            "message",
            function (e) {
                console.log(new Date().toJSON(), ...e.data.args);
            },
            false
        );

        // Method to start a new conversation.
        function startConversation() {
            microsoftTeams.app.getContext().then((context) => {
                microsoftTeams.conversations.openConversation(
                    {
                        "subEntityId": Date.now(),
                        "entityId": context.page.id,
                        "channelId": context.channel.id,
                        "title": "Task Title",
                        "onStartConversation": (conversationResponse) => {
                            console.log('onStartConversation', { conversationResponse })
                            onStartConversation(conversationResponse)
                        },
                        "onCloseConversation": (conversationResponse) => {
                            console.log('onCloseConversation', { conversationResponse })
                            onStartConversation(conversationResponse)
                        },
                    }
                );
            });
        }
```

This seems to be a sdk problem. What can I do to resolve?

**Comment by Prasad-MSFT** [comment]
@LeonardoZivieri - Thanks for raising the issue. We will check this from our end and will update you accordingly.

**Comment by maglims** [comment]
Hi, @LeonardoZivieri , conversations related apis including onStartConversation are limited to Microsoft-internal use as of today. I am not sure how you are running the sample but that may contribute the issues you are seeing.

**Comment by Prasad-MSFT** [comment]
Hi @LeonardoZivieri - We are also able to repro this issue. We are checking this internally with concerned team. Once we get any further info, we will share on this thread.
Thanks!

**Comment by Prasad-MSFT** [comment]
@LeonardoZivieri - we have raised a bug for this issue and engineering team is looking into it. We will update this thread once we have further information.
Thanks!

**Comment by ydogandjiev** [comment]
Hi @LeonardoZivieri, did you send a message in the conversation pane after it opened? Teams doesn't create the conversation until the first message is posted by the user. Once that happens, the function you specified in the onStartConversation parameter of the OpenConversationRequest will be invoked with information about the conversation thread that was created.

I verified that this functionality works as expected in both the New and Classic Teams Clients:
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/3357245/689dac2b-b1e9-48df-818c-f56905a16c7c)
