### ISSUE TITLE
registerOnLoadHandler Not Triggering in New Version of Microsoft Teams

### ISSUE THREAD

**Issue by TahaKeles** [OfficeDev/microsoft-teams-library-js#1979]
We have implemented app caching in our Microsoft Teams Tab application according to the [official Microsoft documentation](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/app-caching). While the caching works as expected on the older Teams version (Teams v1), it seems that the registerOnLoadHandler is not being triggered in the newer version of Teams. This causes issues in the functioning of our application.

Steps to Reproduce:

Implement app caching in a Microsoft Teams Tab application as per the official documentation.
Test the caching functionality in Teams v1.
Update to the newer version of Microsoft Teams.
Observe that the registerOnLoadHandler method is not being triggered.

Expected Behavior:

The registerOnLoadHandler should trigger in both older and newer versions of Microsoft Teams, enabling the caching mechanism to work as intended.

Actual Behavior:

The registerOnLoadHandler is not triggering in the newer version of Microsoft Teams, causing the caching mechanism to fail.

Programming Language: TypeScript
Platform: Microsoft Teams
Affected Version: New Microsoft Teams

Additional Context:

This is a critical issue for us as it affects the user experience and functionality of our application. Any help or guidance to resolve this issue would be highly appreciated.

**Comment by sayali-MSFT** [comment]
@TahaKeles - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by ChetanSharma-msft** [comment]
Hello @TahaKeles - Sorry for delay in response.
We are looking into it and let you know the updates.

**Comment by sayali-MSFT** [comment]
@TahaKeles -We are trying to repro the issue but not able to repro the same, we are checking this with the engineering team and let you know once we have any update.

**Comment by sayali-MSFT** [comment]
@TahaKeles - Document has been updated - https://learn.microsoft.com/en-us/microsoftteams/platform/resources/teams-updates#known-issues
