### ISSUE TITLE
On iPad Teams app reopen defaults to Activity tab

### ISSUE THREAD

**Issue by ceroles** [OfficeDev/microsoft-teams-library-js#1980]
While checking #1842, we have noticed a new issue wherein when switching back to the Teams app (previously running in background), it always opens on the Activity tab. Isn't the expected behavior now that it should open on the last app opened?

Please see the following recording for issue replication:
https://github.com/OfficeDev/microsoft-teams-library-js/assets/118153014/5707a0b0-126e-41cd-b28a-f9fbba6f6597

Replicated on iPad iOS version 16.6, Teams versions 5.17.1

Thank you.

**Comment by ChetanSharma-msft** [comment]
Hello @ceroles - Thanks for raising your query.
Could you please confirm whether this is working in Teams Web/Desktop/Mobile clients in Windows/Mac?
Please share version details.

**Comment by ceroles** [comment]
Hi @ChetanSharma-msft , yes working fine on Teams web, desktop, and mobile. No access to Mac.
So far encountered only on iPad device (iOS version 16.6, Teams versions 5.17.1).
Thank you.

**Comment by Prasad-MSFT** [comment]
As this issue is more related to Teams product side, we have added appropriate tag, so that concerned team can have a look.

**Comment by Prasad-MSFT** [comment]
For Microsoft Teams product issues/failures your tenant Admin can reach out to [Microsoft 365 Product Support](https://docs.microsoft.com/en-us/microsoft-365/admin/contact-support-for-business-products?view=o365-worldwide&tabs=online).
