### ISSUE TITLE
Is there a way to get the version of Teams you are running inside of?

### ISSUE THREAD

**Issue by AnthonyPhan** [OfficeDev/microsoft-teams-library-js#1983]
Is there a way to determine the exact version of teams your user is running

**Comment by AE-MS** [comment]
Hi @AnthonyPhan! There's no way to do this today. Can you say more about what you'd use this information for? We might be able to help you find alternate way to do what you want.

**Comment by AnthonyPhan** [comment]
We are trying to investigate an issue in our application relating to the authentication flow which affects some users. We believe it is due to the specific version of Teams they are running. It would be useful for us to be able to determine the version of Teams in order to aid in this and future investigations.

**Comment by AE-MS** [comment]
Thanks for the extra detail. Unfortunately I don't know of a way to get the Teams version by using teams-js. A user could manually check the version, but it depends on whether they are running Teams on Windows, Mac, web, iOS, Android, etc. Is it correct that you are looking for a way to get the version programatically? Or would asking the user to manually look at the version be sufficient?

Is the authentication flow problem you are investigating related to calling one of the authentication functions in teams-js? If so, can you say a little more about it and perhaps we could help troubleshoot?

**Comment by AnthonyPhan** [comment]
> Thanks for the extra detail. Unfortunately I don't know of a way to get the Teams version by using teams-js. A user could manually check the version, but it depends on whether they are running Teams on Windows, Mac, web, iOS, Android, etc. Is it correct that you are looking for a way to get the version programatically? Or would asking the user to manually look at the version be sufficient?
> 
> Is the authentication flow problem you are investigating related to calling one of the authentication functions in teams-js? If so, can you say a little more about it and perhaps we could help troubleshoot?

Yes, we are looking for a way to get the version programatically as we have hundreds of users affected by the issue daily and it would not really work to request they send us the Team version number. The authentication flow issue i mentioned is outlined in the issue below. 

https://github.com/OfficeDev/microsoft-teams-library-js/issues/1715?fbclid=IwAR19prU_iVKTDBxg2-ESkH7huD5iYNtclibsxG_SIyPTkHQ9QjuhPkYjyWY

**Comment by Prasad-MSFT** [comment]
@AnthonyPhan - There is no way to get the version of Teams programmatically.
