### ISSUE TITLE
Authentification flow is broken on iOS

### ISSUE THREAD

**Issue by JSteunou** [OfficeDev/microsoft-teams-library-js#199]
(also tests with android are still in progress but android might have the same issue)

Tested with our app (Klaxoon) and Trello (others might have the same issue)

Tested with 1.3.7 because 1.4.1 does nothing when calling `authenticate` (#188 #197) 

1. authenticate open Safari instead of a webview popup / window like for the tab parameters action. This is very different from desktop behaviour and this is the main issue that induce the other ones IMHO
2. at the end of user login, notifying for success does not close the login window (because it was open in browser, not in integrated webview)
3. the app seems to get notified but as it does not share the same cookie jar the user is not logged in in the app, only in the browser opened. Again, this is a total different behaviour from the desktop app. This behaviour is also not documented.

**Comment by sharmajnu** [comment]
The auth flow does not work on Android it does not open the popup/page.

**Comment by ydogandjiev** [comment]
Hi @JSteunou, @sharmajnu, are you still encountering this issue with the latest Teams Client SDK and latest version of our Teams iOS Client? If so, could you please clarify the exact repro steps and experience you're seeing?

**Comment by JSteunou** [comment]
Sorry I could not tell you, I'm not on it anymore

**Comment by ChetanSharma-msft** [comment]
Hello @sharmajnu - Hope you are doing well!!
Sorry for delay in responses.

Could you please confirm if you are still facing this issue or need any help here.

**Comment by Wajeed-msft** [comment]
We are closing this issue from this tracking list. Please feel free to re-open if you are still experiencing the issue.
