### ISSUE TITLE
[Teams New Version] Cannot open Google login page, always redirect to Support page

### ISSUE THREAD

**Issue by kafka-yu** [OfficeDev/microsoft-teams-library-js#1998]
Hi Team,

Not sure if this is a correct place to ask questions about the problem we meet on New Teams client (Mac/Windows)

Steps:
1. When open our app RingCentral in New Teams client
2. Then click "Sign In"
3. Then fill one account email addr.
4. Then Click "Google"
5. It will go to the Google support page, and ask me to clear the cache.

<img width="935" alt="image" src="https://github.com/OfficeDev/microsoft-teams-library-js/assets/3942409/26fba997-f000-45c0-b25b-03871a823e72">
<img width="898" alt="image" src="https://github.com/OfficeDev/microsoft-teams-library-js/assets/3942409/f0194fe8-aefb-4284-8c24-825c1d871fea">

Anyone knows how to resolve this? I've tried:
 - Clear cache in this window
 - Clear cache for entire teams
 - Reinstall the New Teams client

All are not working.

Thanks.

**Comment by SaiPratap-MSFT** [comment]
@kafka-yu  - We have tested this scenario in new teams on Windows . it is redirecting to the google page on clicking google. Here i am attaching the video 

https://github.com/OfficeDev/microsoft-teams-library-js/assets/146196379/7c133512-dc56-494f-b27a-ca45dd726036

**Comment by kafka-yu** [comment]
@SaiPratap-MSFT 
Could you pls continue to log in with your Google account credential on the Google sign-in page? and then it will notify you it has no account matched, then go back to step 1 and do the login flow again. 

Thank you

**Comment by SaiPratap-MSFT** [comment]
@kafka-yu  - We are able to repro this issue, we have raised bug for the same. We will inform you once we get any update.

**Comment by kafka-yu** [comment]
Thank you! @SaiPratap-MSFT

**Comment by kafka-yu** [comment]
hello @SaiPratap-MSFT Is there any update?

**Comment by SaiPratap-MSFT** [comment]
@kafka-yu - We are checking your query with engineering team and let you know once we get any updates from them. Thanks.

**Comment by ChetanSharma-msft** [comment]
Hello @kafka-yu - Could you please share the error logs, if any? so that we can investigate it further accordingly.
Also, please share the code how you have implemented the google auth including the steps.

**Comment by kafka-yu** [comment]
no errors, in the DevTool, it just goes to the support page. @ChetanSharma-msft

**Comment by kafka-yu** [comment]
> @kafka-yu - We are able to repro this issue, we have raised bug for the same. We will inform you once we get any update.

hi @SaiPratap-MSFT do you have any ETA it can be fixed? Or it is already fixed?

**Comment by ChetanSharma-msft** [comment]
Hello @kafka-yu - Sorry for delay in response.
We are actively checking the updates with engineering team and let you know if we have any.
Apologize for the inconvenience.

**Comment by Prasad-MSFT** [comment]
Hi @kafka-yu - This issue seems to be fixed. Could you please let us know if you are still facing the issue or not?
