### ISSUE TITLE
http://statics.teams.microsoft.com/ is not responding so all dependecies using MicrosoftTeams.min.js are failing

### ISSUE THREAD

**Issue by vbatr** [OfficeDev/microsoft-teams-library-js#2000]
Hi 

I am using the older version of MicrosoftTeams.min.js that is hosted on https://statics.teams.microsoft.com/sdk/v1.x.x/js/MicrosoftTeams.min.js. 
http://statics.teams.microsoft.com/  is not responding and SSL certificate for that domain has been expired as well
As a result our bot application and the resources we are using as a dependency (i.e. https://token.botframework.com/) are failing
![Screenshot 2023-10-19 at 13 25 23](https://github.com/OfficeDev/microsoft-teams-library-js/assets/20244602/f3a24316-7784-4f68-9422-a966afc6cc28)

![Screenshot 2023-10-19 at 13 31 39](https://github.com/OfficeDev/microsoft-teams-library-js/assets/20244602/ab1d641a-440a-4f5a-99cd-2168fb14e2b0)

![Screenshot 2023-10-19 at 13 32 12](https://github.com/OfficeDev/microsoft-teams-library-js/assets/20244602/17f28ec0-3e73-4f12-9db9-dbef11255e6a)

**Comment by SaiPratap-MSFT** [comment]
@vbatr  -  Thanks for reporting your issue. We will test this and update you soon.

**Comment by vbatr** [comment]
UPD: looks like certificate issue was resolved
![Screenshot 2023-10-20 at 11 09 20](https://github.com/OfficeDev/microsoft-teams-library-js/assets/20244602/3a567a71-dc9b-4d9c-a108-18927cce6b24)

**Comment by vbatr** [comment]
Closing the issue as it was fixed and we had down time for the resource only between October, 18th and October, 19th
