### ISSUE TITLE
authentication.notifySuccess not working on ios

### ISSUE THREAD

**Issue by 86driver** [OfficeDev/microsoft-teams-library-js#2002]
i used the js sdk version is v1.10.0 (https://statics.teams.cdn.office.net/sdk/v1.10.0/js/MicrosoftTeams.min.js'),
it works well on pc, but when i use the sdk in teams app, it not works.

when i use ngrok, it works well.

signin url:  xx.dev-xx.site/ouath2/login
success callbackurl:  xx.dev-xx.site/ouath2/oauth2/callback

or you can tell me how to close the built-in browser in App,   then i can domyself to avoid the problem.

@Nivedipa-MSFT 

#### more info: 
device: IOS 16
plantform: Teams App

**Comment by 86driver** [comment]
below is my code


`<script>
        const tag = document.createElement('script');
        tag.async = true;
        tag.src = 'https://statics.teams.cdn.office.net/sdk/v1.10.0/js/MicrosoftTeams.min.js';
        tag.integrity = 'sha384-6oUzHUqESdbT3hNPDDZUa/OunUj5SoxuMXNek1Dwe6AmChzqc6EJhjVrJ93DY/Bv';
        tag.crossOrigin = 'anonymous';

        document.body.appendChild(tag);

        tag.addEventListener('load', function () {
            window.microsoftTeams?.initialize({
                successCallback: function (result) {
                    alert('success');
                    alert(result);
                },
                failureCallback: function (error) {
                    alert('failureCallback error');
                    alert(error);
                }
            });
            setTimeout(() => {
                window.microsoftTeams?.authentication?.notifySuccess('authed successfully');
            }, 5000);
        });

        tag.addEventListener('error', function (err) {
            alert('error');
            alert(err);
        });
    </script>`

**Comment by sayali-MSFT** [comment]
@86driver -Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by 86driver** [comment]
the mobile app seems can not find the window.opener @sayali-MSFT

**Comment by 86driver** [comment]
In the source code I saw this code： 
<img width="461" alt="image" src="https://github.com/OfficeDev/microsoft-teams-library-js/assets/38236070/9c9c5e3f-7655-4fd7-88bc-22fe66d8e585">
nativeInterface.framelessPostMessage is the bridge？   maybe the bug is around it.

I am very eager to fix this bug. Can you fix it as soon as possible？
@sayali-MSFT

**Comment by sayali-MSFT** [comment]
@86driver -Sure, we are checking with this internal team and let you know the update.

**Comment by sayali-MSFT** [comment]
@86driver - Also issue is occurred due to you were not implementing the auth flow as per our documentation which was resulting in the window.opener not being set correctly.

**Comment by 86driver** [comment]
> @86driver - Also issue is occurred due to you were not implementing the auth flow as per our documentation which was resulting in the window.opener not being set correctly.

 it is caused by window.open.     thanks a lot.

**Comment by sayali-MSFT** [comment]
@86driver - Glad to hear that your issue is resolved.
Could you please share your valuable feedback via [Microsoft Teams Developer Feedback](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u) link.
