### ISSUE TITLE
In new teams - page.id is empty string for frameContext- `settings`

### ISSUE THREAD

**Issue by sonam-serchan** [OfficeDev/microsoft-teams-library-js#2018]
This issue is happening only in new teams, but I can see it's not an issue for old teams.

When I am on in new teams:
Once I have added my app in the tab, then

- I open settings from the tab of my app
![Screenshot 2023-11-02 at 15 52 39](https://github.com/OfficeDev/microsoft-teams-library-js/assets/23254380/f014bb31-6cee-412f-ac00-aca8219c0f45)
- The page.id is not being retained:
![Screenshot 2023-11-02 at 15 47 26](https://github.com/OfficeDev/microsoft-teams-library-js/assets/23254380/6b300d61-2081-43a2-9dc8-38a899362da3)
- However, the id is there when I open the tab. Here the frameContext is `content`
![Screenshot 2023-11-02 at 16 30 37](https://github.com/OfficeDev/microsoft-teams-library-js/assets/23254380/73aaae39-3dee-47e2-ae45-5a4a519db774)

Now, when I open the same settings in old classic teams,
the page.id is retained and I can see it's value even in frameContext -`settings` as you can see below:
![Screenshot 2023-11-02 at 16 53 06](https://github.com/OfficeDev/microsoft-teams-library-js/assets/23254380/4b6f42fe-e5e8-4002-b2c0-322a9f6e76e7)

**Comment by Prasad-MSFT** [comment]
Hi @sonam-serchan - As explained by engineering team in [this](https://techcommunity.microsoft.com/t5/teams-developer/new-channel-experience-breaks-tab-settings-popup/m-p/3873343/highlight/true#M8083) thread, "the getContext API was never meant to retrieve information about the tab content page inside of the tab configuration page. If you need to read the existing tab instance settings in the configuration page, you should use the [settings.getSettings](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/settings?view=msteams-client-js-latest#@microsoft-teams-js-settings-getsettings) or [pages.getConfig](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/pages?view=msteams-client-js-latest#@microsoft-teams-js-pages-getconfig) API. That will give you the entityId, contentUrl, and all other metadata that you previously provided when the tab was initially setup.

**Comment by sonam-serchan** [comment]
Oh, right!
Thanks for that @Prasad-MSFT. Working now!
