### ISSUE TITLE
Deeplink doesn't work as expected in new teams client for custom apps

### ISSUE THREAD

**Issue by kavin-happyfox** [OfficeDev/microsoft-teams-library-js#2028]
We have a custom Teams app created for testing purposes contains a deeplink and the purpose is to redirect to chat tab.  
As instructed [here](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-application?tabs=teamsjs-v2#deep-link-to-a-chat-with-the-application), we have constructed it, where `<your-app-id>` is replaced with the manifest ID as mentioned [here](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-application?tabs=teamsjs-v2#app-id-used-for-different-apps). 

For this setup, the deeplink is working in classic client but not in the new client. I am getting a popup with message `This app cannot be found.`

When we checked the deeplink for a published Teams app, it is working in both the clients.

Also, we have observed that the ID of the custom app in the browser URL(as in the attached image) and the manifest ID are different. But it is same for the app which is published. When we use the ID in the browser URL for deeplink for custom app, it is working in the new client.

So, is this the reason for the issue? If so, how to retrieve that ID for the above use case?

Related issue: https://github.com/OfficeDev/microsoft-teams-library-js/issues/1883

<img width="1163" alt="Screenshot 2023-11-06 at 3 44 37 PM" src="https://github.com/OfficeDev/microsoft-teams-library-js/assets/112480281/16e9aa75-edfc-4070-b945-67d41b0dc58a">

**Comment by xnivaxhzne** [comment]
<img width="647" alt="Screenshot 2023-11-06 at 3 47 47 PM" src="https://github.com/OfficeDev/microsoft-teams-library-js/assets/112480281/0f00b090-14c4-4e69-89ae-0e9598703c58">

**Comment by sayali-MSFT** [comment]
@xnivaxhzne - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by sayali-MSFT** [comment]
@xnivaxhzne -We are not able to repro the scenario, as it is open an app install dialog properly for custom Teams app.
You have Microsoft Teams version 23285.3604.2469.4152.
You've got the latest version. It was last updated on 9/11/2023.
The client version is 49/23101227708.

![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/93527375/7a34dec4-bbf7-4910-b205-99b615d8edc5)

**Comment by xnivaxhzne** [comment]
@sayali-MSFT Thanks for replying back. 

Sorry, if the issue hasn't conveyed properly and this is not our expectation. 

### Expectation:
In a custom app, when this deeplink (`https://teams.microsoft.com/l/entity/<appId>/conversations` - where `<appId>` is the manifest ID of the custom app) is accessed from new Teams client's home tab, it is expected to get redirected to chat tab.

### Actual:
At the time when I logged this issue here, the client show the modal as attached [here](https://github.com/OfficeDev/microsoft-teams-library-js/issues/2028#issuecomment-1794495396), but today home tab is getting refreshed without the expected redirection.

**Comment by sayali-MSFT** [comment]
@xnivaxhzne -Thank you for the clarification. We will test this from our end. If it is a bug, we will raise it accordingly and keep you updated.

**Comment by sayali-MSFT** [comment]
@xnivaxhzne -We are able to repro the scenario, we have raised bug for the same. We will let you know once we have any update.
You have Microsoft Teams version 23306.3306.2510.9721.
You've got the latest version. It was last updated on 13/11/2023.
The client version is 49/23101227711.

![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/93527375/af663db7-d4fd-44fd-aa33-0b27de1bdacd)

**Comment by ChetanSharma-msft** [comment]
Hello @kavin-happyfox - Sorry for delay in response.
This bug is fixed.

Could you please reverify and let us know if you are still facing this issue.
