### ISSUE TITLE
Unable to send Adaptive Card as message to MS Teams using MS Graph Send Messages API

### ISSUE THREAD

**Issue by aoneahsan** [OfficeDev/microsoft-teams-library-js#2031]
I tried to send adaptive card as message body to MS Teams channel using MS Graph API
[https://graph.microsoft.com/v1.0/teams/{team-id}/channels/{channel-id}/messages](https://graph.microsoft.com/v1.0/teams/%7Bteam-id%7D/channels/%7Bchannel-id%7D/messages)

I changed the respective values with teamid, and channelid and provided a valid access token as well.

but i'm getting error and an un able to send adaptive card as message to MS Teams us MS Graph API.

Please assist.

<img width="1324" alt="Screenshot 2023-11-07 at 7 16 17 PM" src="https://github.com/OfficeDev/microsoft-teams-library-js/assets/37369204/89ee7eba-848b-41b0-b715-00b983089201">
<img width="932" alt="Screenshot 2023-11-07 at 7 16 30 PM" src="https://github.com/OfficeDev/microsoft-teams-library-js/assets/37369204/cda52a91-2115-45ca-9cdc-3e7fdeee349a">

**Comment by ChetanSharma-msft** [comment]
Hello @aoneahsan - Thanks for raising your query.
Could you please confirm whether the Graph API is working for you from postman or Graph Explorer or there also you are getting same error?

Looks like your token is having some issues. Please verify if you token is having required permissions to call the API using https://jwt.io/

**Comment by sayali-MSFT** [comment]
Hello @aoneahsan -Could you please confirm if your issue has resolved with provided suggestions or still looking for any help?
