### ISSUE TITLE
Chat deep link with one recipient throwing error in new Teams

### ISSUE THREAD

**Issue by aliblack89** [OfficeDev/microsoft-teams-library-js#2035]
When creating a chat deep link with one recipient an error is thrown in the new Teams desktop client. If there is more than one recipient it works correctly. I have used both the `chat.openChat({...})` and `chat.openGroupChat({...})` methods, both producing the same error.

Here is an example of the function I am calling to start a chat:

```javascript
// For openChat
async function startChat() {
    await app.initialize();

    if (chat.isSupported()) {
      try {
        const result = await chat.openChat({
          user: "adelev@xyz.onmicrosoft.com",
          message: "Hello",
        });
        console.log(result);
      } catch (error) {
        console.log(error);
      }
    } else {
      console.log("openChat is not supported");
    }
  }
```

```javascript
// For openGroupChat
async function startChat() {
    await app.initialize();

    if (chat.isSupported()) {
      try {
        const result = await chat.openGroupChat({
          users: ["adelev@xyz.onmicrosoft.com"],
          message: "Hello",
        });
        console.log(result);
      } catch (error) {
        console.log(error);
      }
    } else {
      console.log("openGroupChat is not supported");
    }
  }
```

The error displayed in the console is:
<img width="513" alt="Screenshot 2023-11-08 at 10 29 51" src="https://github.com/OfficeDev/microsoft-teams-library-js/assets/592673/f1a93a48-fca9-47a2-8b44-4af07bd57929">

I am using teams-js version 2.17.0 and Teams desktop is version 23285.3804.2469.4861.

**Comment by Meghana-MSFT** [comment]
Based on Teams version it seems you are on the new Teams T2.1. Could you please confirm if you are facing this issue on Teams classic as well. We will also check this at our end and get back to you.

**Comment by aliblack89** [comment]
Yeah, it works on Teams classic and also the web client. It just seems to be the new Teams that I'm getting this issue.

**Comment by nwojod-MSFT** [comment]
Closing issue as duplicate [#1964](https://github.com/OfficeDev/microsoft-teams-library-js/issues/1964)
