### ISSUE TITLE
Question/Feature Request: Updating  tabs website url from tab it self

### ISSUE THREAD

**Issue by abdulkareemnalband** [OfficeDev/microsoft-teams-library-js#204]
#### How can I update `websiteUrl` url from tab itself? 

we are setting a `websiteUrl` in [microsoftTeams.settings.setSettings](https://docs.microsoft.com/en-us/javascript/api/%40microsoft/teams-js/settings?view=msteams-client-js-latest#setsettings-settings-) so that clicking **go to website**  ![image](https://user-images.githubusercontent.com/3139353/55326132-a6201180-54a4-11e9-89dc-8fc86387df7d.png)  opens same view in browser  

After doing some operations view inside tab , we need to update `websiteUrl`.

I tried following code snippets in **tab** 

```ts
microsoftTeams.settings.getSettings(s => 
    microsoftTeams.settings.setSettings({...s,websiteUrl: 'new-website-url' })
);
```
and

```ts
    microsoftTeams.settings.setSettings({websiteUrl: 'new-website-url' })
``` 

in both cases tab crashed and went into reload loop

Is this operation supported?

**Comment by benpolinsky** [comment]
You should be able to use `microsoftTeams.settings.setSettings({websiteUrl: 'new-website-url'})` [source](https://docs.microsoft.com/en-us/javascript/api/%40microsoft/teams-js/settings?view=msteams-client-js-latest#setsettings-settings-)

I'm able to update and persist a tab's settings from within a content tab using the above method.

**Comment by abdulkareemnalband** [comment]
previously I did following 

```ts
microsoftTeams.settings.getSettings(s => 
    microsoftTeams.settings.setSettings({...s,websiteUrl: 'new-website-url' })
);
```

And it crashed the tab.
I will try setting minimal properties

**Comment by sachingupta** [comment]
@abdulkareemnalband As @benpolinsky you can update any setting property 
![image](https://user-images.githubusercontent.com/1689428/55356963-c938ca00-5480-11e9-8926-e2c78b5029be.png)

by calling microsoftTeams.settings.setSettings({websiteUrl: 'new-website-url'}).
Please use latest teams-js npm package https://www.npmjs.com/package/@microsoft/teams-js 
Please let us know if you still face any issue.

**Comment by billbliss** [comment]
It definitely shouldn't crash the tab or Teams. If you have a repro case for that, we'd like to know about it so we can fix it.

**Comment by abdulkareemnalband** [comment]
@sachingupta @billbliss 
My bad I forgot to mention that we need to update `websiteUrl` from **Tab** itself
When I do this tab crashes.

I will update original report to reflect this

**Comment by benpolinsky** [comment]
I can actually confirm this:

In a content tab:
- calling `setSettings` **from within the `getSettings` callback** causes the tab to reload infinitely. 
- calling `setSettings` from outside of the `getSettings` callback does not cause any unwanted behavior

Version 1.4.1.

**Comment by abdulkareemnalband** [comment]
@benpolinsky For me it went into reload loop for both cases

May be because i'm using angular to develop this???

**Comment by ydogandjiev** [comment]
@abdulkareemnalband, how does your tab decide when to call setSettings? Do you first check whether the settings have been updated and skip the setSettings call if so? If you call setSettings on every load then your tab will keep infinitely refreshing.

**Comment by abdulkareemnalband** [comment]
@ydogandjiev 
I was doing onload (actully ngOnInit lifecycle hook of after login componant) for testing perposes,
but after login happens (microsoftTeams.authenticate )(we use office365 as identity provider)

**Comment by abdulkareemnalband** [comment]
@sachingupta @billbliss 
is calling `microsoftTeams.settings.setSettings` from tab is even legal
calling this reloads the tab

**Comment by ydogandjiev** [comment]
Yes, you can call `microsoftTeams.settings.setSettings` from your tab's content page; however, you should generally only do so after giving a heads-up to the user since the tab does refresh after you update its settings - e.g. a notice banner with an "Update" button or an inline configuration page with a "Save" button.

**Comment by abdulkareemnalband** [comment]
@ydogandjiev can I do this without triggering reload?

**Comment by ydogandjiev** [comment]
Not currently, calling saveSettings from your tab’s content page always triggers a reload of the tab.

**Comment by abdulkareemnalband** [comment]
@ydogandjiev 
is there any plan to implement session specific `websitUrl` update
I.E.
user does some work in tab and tab website navigates to some different url, when he clicks on external  browser  link he should be taken to page specific to current view in tab

**Comment by ydogandjiev** [comment]
That’s an interesting scenario and definitely one we haven’t yet considered. Can you please better describe the functionality of your tab and why you need to change the URL that “Go to website” launches in this kind of dynamic fashion?

The tab settings (i.e. contentUrl, websiteUrl, entityId, etc.) are meant to be set only once at tab configuration time and should rarely be changed after that. User navigation within the tab should most definitely not change these settings. A tab is a window into some content that the user selects at configuration time. Users can re-open your tab’s configuration flow if they want to change where the tab points to.

We provided the setSettings API to some of our partners as a way to upgrade old instances of their tab (i.e. in case they want to update any of the settings they previously gave us). This API is meant to be called in the way that I described in one of my previous posts above. While we’ve considered eliminating the refresh triggered by the setSettings call; I actually think leaving it in might be better based on this discussion. This is an expensive call on our end that makes a network call to persist the updated settings in our backend store which in turn fans out the changes to everyone else in that team. If tabs started calling this API frequently to achieve the scenario you described we might end up causing a performance degradation in Teams itself.

**Comment by abdulkareemnalband** [comment]
@ydogandjiev 
Thanks for prompt response
Our required scenario is

1. Initial tab page is a list of resources
2. User clicks on a resource to view/edit that
3. tab navigates to particular resource page
4. If user clicks on `Go to website` he is taken to list view in browser instead of resource page

hope this clarifies the use case for that particular scenario

**Comment by billbliss** [comment]
The "go to website" button is not particularly discoverable by end users. Would you prefer a UI (button/link) within the tab itself that does this? Currently hyperlinks navigate within the tab, as you know, unless it's navigation outside `validDomains`. (Actually I haven't tried a hyperlink with "target=_blank" inside a tab - maybe that works.)

**Comment by abdulkareemnalband** [comment]
@billbliss 
`target="_blank"` actually  works(we use that for different scenario) 

As content inside tab changes **Go to website** becomes wrong destination.
may be we could update that temporary for particular session, so that **Go to website** links to what is currently shown in tab

**Comment by ydogandjiev** [comment]
@abdulkareemnalband, this functionality is now available. If you want to update the `contentUrl` and/or `websiteUrl` that your tab points to just for the current session you can now call:
```
microsoftTeams.setFrameContext({
  contetUrl: "https://tempContentUrl",
  websiteUrl: "https://tempWebsiteUrl"
});
```

These will be used if the user clicks on the "Reload tab" or "Go to website" actions:
![image](https://user-images.githubusercontent.com/3357245/76985500-883dfd80-68fd-11ea-8936-58ea02240ffe.png)
