### ISSUE TITLE
Detect when a user closes a tab app

### ISSUE THREAD

**Issue by AnthonyPhan** [OfficeDev/microsoft-teams-library-js#2040]
Is there a way to detect if a user closes/navigates away from a teams tab app? i'm looking for something similar to the beforeUnload event that you get in the browser environment. 

The use case is to let the user know if there are un-synced changes to ask if they are sure they want to close/navigate away form the tab.

**Comment by sayali-MSFT** [comment]
Hello @AnthonyPhan - Thanks for raising your query.
 
I think, you can use microsoftTeams.teamsCore.registerBeforeUnloadHandler whenever we want to handle the event, if we are moving out from the tab.
 
Reference docs: 
https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/app-caching#code-example
https://learn.microsoft.com/en-us/javascript/api/%40microsoft/teams-js/teamscore.registerbeforeunloadhandlerfunctiontype?view=msteams-client-js-latest
 
Sample link: 
https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/app-cache-meetings/nodejs/src/components/app-cache-tab.tsx#L103
 
Please let us know if it helps.
