### ISSUE TITLE
Clipboard API throws errorCode: 100 (teams-js v2.17) 

### ISSUE THREAD

**Issue by alexchaaan** [OfficeDev/microsoft-teams-library-js#2044]
Hi Team,

From this issue it looks like the Clipboard API should be available and working now:
https://github.com/OfficeDev/microsoft-teams-library-js/issues/1921

But I'm still getting errorCode: 100 when running clipboard.write().

I noticed clipboard.isSupported() is returning false within a personal app but if this returns false then when would it return true?

Happy to provide more information

**Comment by shrshindeMSFT** [comment]
Hi @alexchaaan,

Can you please provide us with a minimum repro code and which host are you targeting (like Teams v1)?

**Comment by alexchaaan** [comment]
const blob = new Blob([shareUrl]);
			try {
				await clipboard.write(blob);
			} catch (error) {
				console.log(error)
			}
				if(clipboard.isSupported()) {
				await clipboard.write(blob);
			}```

**Comment by alexchaaan** [comment]
this is in Teams, not sure where to find the version

**Comment by ChetanSharma-msft** [comment]
Hello @alexchaaan - Thanks for raising your query.

clipboard.write only supports Text, HTML, PNG, and JPEG data format. MIME type for Text -> text/plain, HTML -> text/html, PNG/JPEG -> image/(png | jpeg) Also, JPEG will be converted to PNG image when copying to clipboard.

Looks like you are trying it for blob content. Could you please try it with Text, HTML etc. and let you know if you still face the issue.

Reference doc link: https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/clipboard?view=msteams-client-js-latest

**Comment by sayali-MSFT** [comment]
Hello @alexchaaan - Thanks for raising your query.
 
clipboard.write only supports Text, HTML, PNG, and JPEG data format. MIME type for Text -> text/plain, HTML -> text/html, PNG/JPEG -> image/(png | jpeg) Also, JPEG will be converted to PNG image when copying to clipboard.
 
Looks like you are trying it for blob content. Could you please try it with Text, HTML etc. and let you know if you still face the issue.
 
Reference doc link: https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/clipboard?view=msteams-client-js-latest

**Comment by alexchaaan** [comment]
Same issue.

```		if(shareUrl) {
			console.log('clipboard is supported?')
			console.log(clipboard.isSupported())
			const blob = new Blob([shareUrl], {type: 'text/plain'});
			console.log(blob)
			console.log('THE BLOB')
			try {
				await clipboard.write(blob);
			} catch (error) {
				console.log(error)
			}
				if(clipboard.isSupported()) {
					await clipboard.write(blob);
			}
		}```

Again, the clipboard.isSupported() is returning false so I can't use that.
And clipboard.write is returning a error 100, `{errorCode: 100}`

**Comment by alicialu-MSFT** [comment]
Can you confirm which part of the Teams client you are trying to run this on? Is this when your app is loaded in the meeting pane or fully initialized in the sidebar or in a Teams channel/chat, etc? 

https://support.microsoft.com/en-us/office/switch-to-the-new-microsoft-teams-2d4a0c96-fa52-43f8-a006-4bfbc62cf6c5#:~:text=To%20use%20the%20new%20Teams%3A%201%20Open%20the,will%20reboot%20to%20open%20the%20new%20Teams.%20 For the Teams version, you can check Teams version and try the new Teams version by following the steps in this article. Please try running your personal app in the new Teams client and let us know if you're still getting those errors!

**Comment by alexchaaan** [comment]
Fully initialized in the sidebar. From the manifest, it's a static tab with personal scope

Looks like it works in the new version! Is it expected to break in the old version though?

**Comment by ChetanSharma-msft** [comment]
Hello @alexchaaan - We are checking this with engineering team and let you know the updates.
