### ISSUE TITLE
No way to access teams command bar extension in new Teams anymore

### ISSUE THREAD

**Issue by catmanjan** [OfficeDev/microsoft-teams-library-js#2046]
We used be able to do @appname in the command bar at the top and return search results, but in the new team it no longer works

![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/137350/34388b7a-bd83-4563-a6ba-04ff8e15cd04)

If we just type ingress we get this app result, but when you click it you are taken to the bot, not search results

![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/137350/0b8a65d3-f53d-42e0-8504-b615513d4aa0)

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this, we will check this and get back to you.

**Comment by Meghana-MSFT** [comment]
@catmanjan - Message extensions in command bar are not supported in T2.1 right now. This has been considered as a feature request. But we do not have any ETA on when this feature would become available. Thank you.

**Comment by catmanjan** [comment]
@Meghana-MSFT weird, but okay - is there a list of breaking changes between the old teams and new teams?

**Comment by Meghana-MSFT** [comment]
@catmanjan - Please refer these docs

1. https://learn.microsoft.com/en-us/microsoftteams/platform/resources/teams-updates?branch=main
2. https://learn.microsoft.com/en-us/microsoftteams/new-teams-desktop-admin
