### ISSUE TITLE
App Caching on iOS

### ISSUE THREAD

**Issue by LeonYasoon** [OfficeDev/microsoft-teams-library-js#2063]
According to the docs here: https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/app-caching app caching is supported on iOS only for personal tabs. But when enabling app caching according to the guide, it works for channel tabs aswell. Is this intended? (aka are the docs out of date?)

Also, in all scenarios where app caching works, when returning to the tab, it is overlayed with a loading spinner, even when calling notifySuccess and notifyAppLoaded:

![Image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/71631027/f4358846-5ef4-4b07-b6a7-93e8d5846f5e)

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this issue, we will check this and get back to you.

**Comment by Meghana-MSFT** [comment]
@LeonYasoon - App caching is supported in chat, channel and meeting scopes in iOS.  PR has been raised to update the docs.

**Comment by LeonYasoon** [comment]
Hi @Meghana-MSFT what about the loading spinner?

**Comment by Meghana-MSFT** [comment]
@LeonYasoon - Apologies for the delay, could you please let us know if you are still facing this issue? We are not able to repro this issue. Request you to please share a video recording of the issue.

**Comment by LeonYasoon** [comment]
Loading spinner seems to not be reproducible anymore
