### ISSUE TITLE
Context interface appears to be incorrect

### ISSUE THREAD

**Issue by RobPethick** [OfficeDev/microsoft-teams-library-js#207]
The interface for Context as defined in src/public/interfaces.ts does not seem to match with the return actually given when I call getContext

For example the interface declares property 'sharepoint' which I don't have but misses teamSiteDomain, which I do have. I assume this just needs to be updated. 
FYI I am using a teams for education client

**Comment by ydogandjiev** [comment]
@RobPethick, the `sharepoint` field will only be set when your page is hosted in SharePoint:
https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/tabs/tabs-in-sharepoint

As for the other fields that were missing from the Context type; I've opened a PR to add those:
#209

Thank you for reporting the issue!

**Comment by ydogandjiev** [comment]
Missing fields have now been added. Closing issue.

**Comment by RobPethick** [comment]
Hi - this doesn't seem to be sorted in v1.4.3 - is this going to be included soon?

**Comment by ydogandjiev** [comment]
@RobPethick, we only back port critical fixes to our older versions of the SDK. Most new changes will go out with the v1.5 release. Until we officially release the next version of the SDK you are welcome to use the latest beta version:
`yarn add @microsoft/teams-js@beta`
