### ISSUE TITLE
Bug: microsoftTeams.people.selectPeople results returning "UPN" in "email" field

### ISSUE THREAD

**Issue by LeonYasoon** [OfficeDev/microsoft-teams-library-js#2086]
Using `microsoftTeams.people.selectPeople` to open the people picker inside MS Teams shows a modal:

![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/71631027/ff51e2d3-15ad-4dd4-b623-09276f8e7e84)

Searching for users fires an HTTP request to this endpoint: `https://teams.microsoft.com/api/mt/part/emea-03/beta/users/searchV2` returning an array of matching user objects:

![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/71631027/3c16c4ce-c811-4a31-8f2d-58476f238dca)

The `email` field of the response is actually the `UPN` of that user. That is a bug which is critical to our operations. 
Please investigate :)

**Comment by SaiPratap-MSFT** [comment]
@LeonYasoon - Thanks for reporting your issue. We will check and update you soon.

**Comment by ChetanSharma-msft** [comment]
Hello @LeonYasoon - Could you please confirm what should be the correct email id for that particular person?

**Microsoft's recommended best practices are to match UPN to primary SMTP address.**

Please refer this documentation: https://learn.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configuring-alternate-login-id#what-is-alternate-login-id

You can refer this sample as well: https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/tab-device-permissions/nodejs/src/components/PeoplePicker.tsx

If you still have any issue, please let us know the below details:
1) Are you testing it in Classic or New Desktop or Web Teams client and please confirm if it is working in any.
2) Specific version of library used to call the `microsoftTeams.people.selectPeople`.

Thanks!!

**Comment by LeonYasoon** [comment]
Hi @ChetanSharma-msft 

1. This is not working in New Desktop, Classic Desktop and Web.
2. We first started seeing this bug in Teams JS SDK version 2.0.0 and we are now on 2.16.0 and it is still happening.

**Comment by ChetanSharma-msft** [comment]
Hello @LeonYasoon - Sorry for delay in response.
We have considered this as a feature request and engineering team will review it, the level of work required, and prioritize accordingly.

Currently we don't have exact ETA to share with you.
We are checking with engineering team and let you know.

Reference issue link: https://github.com/OfficeDev/microsoft-teams-library-js/issues/1526
