### ISSUE TITLE
authentication.getAuthToken is redirecting when using New Teams on a browser 

### ISSUE THREAD

**Issue by jwccit** [OfficeDev/microsoft-teams-library-js#2088]
When using the New Teams web client, calling the `authentication.getAuthToken` function is causing the page to navigate away from Teams and to a MS log in page. 

The flow works correctly, but using classic Teams or the desktop client, the user is presented with a new window to carry out the authentication.

The redirect is not ideal as it causes the user to be navigated away from the app they are trying to use.

**Comment by ChetanSharma-msft** [comment]
Hello @jwccit - Thanks for raising your query.
We will look into it and let you know the updates.

**Comment by Prasad-MSFT** [comment]
@jwccit - We tried to repro this issue following this sample, however we are observing same behaviour in both Teams Classic and New Teams in browser.
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/app-sso

Could you please share a video of your issues differentiating the behaviour?

**Comment by jwccit** [comment]
@Prasad-MSFT - Thanks for getting back to my and trying to reproduce the behavior. I've attached a video of the issue, both will be calling the same part of the code which is simply: 

![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/74728196/a2157c50-3837-44aa-97c4-481b4065aa53)

There is no code to redirect the user. Here is the console log 
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/74728196/e8c2a74d-9f1c-4cf3-a61b-8fff9833ef94)

Using the old teams, the logs are the same, except the navigation message

https://github.com/OfficeDev/microsoft-teams-library-js/assets/74728196/ae50617c-25ab-4ffb-88cb-f9049d6400c2



I've looked through the repo you linked and the token seems to be fetched the same way.

Appreciate the help.

**Comment by Prasad-MSFT** [comment]
@jwccit - Are you observing the same behaviour using this sample as well (https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/app-sso)?

Do you have this `authentication.authenticate()` function implemented in your code? This function launches a pop-up window for authentication, allowing the user to sign in without leaving the Teams client.

```
import { authentication } from "@microsoft/teams-js";
authentication.authenticate({
  url: window.location.origin + "/tab-auth/simple-start",
  width: 600,
  height: 535
})
.then((result) => {
  console.log("Login succeeded: " + result);
  // Handle the authentication result
})
.catch((reason) => {
  console.log("Login failed: " + reason);
  // Handle the authentication error
});
```

**Comment by jwccit** [comment]
Not had a chance to test the sample code, I will try and put some time aside this morning to have a look. 

I do have the `authenticate` function added, but I use it as a fallback if the user cancels or the first authentication fails. The app doesn't require any additional permissions, the default ones provided with the initial consent are enough (openId profile...).

![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/74728196/6d7782a4-1748-4cb0-9f54-43ab39790ca5)
 
As this line of code isn't getting hit and only the `getAuthToken` is, I can't work out why the behavior is different?

**Comment by jwccit** [comment]
@Prasad-MSFT - I am no longer having this issue with either the local or the live version. 

Not sure what was causing the issue, but after a complete Teams cache clear, the problem seems to have resolved. Apologies for having you look, but appreciate the  support

**Comment by Prasad-MSFT** [comment]
Thanks for informing @jwccit . Glad that its working now. We are closing this issue for now. Please feel free to reopen if required.

**Comment by wfseng** [comment]
The problem in new Teams in a web browser still exists:

`await microsoftTeams.app.initialize();
await microsoftTeams.authentication.getAuthToken();`

This does not generate a popup, but instead redirects the current browser tab/window. 
If the user either rejects or accepts consent, they are redirected back to Teams default home url away from the Teams app.

The popup is generated ok in Teams desktop.
To reproduce this the user must never have provided basic consent to the app.
