### ISSUE TITLE
microsoftTeams.executeDeepLink is not working as expected in desktop version

### ISSUE THREAD

**Issue by ppkedar** [OfficeDev/microsoft-teams-library-js#2092]
I am using microsoftTeams.executeDeepLink in a custom app to open a different desktop application. It's working in web version of Teams, but it's not working for desktop version.

**Comment by SaiPratap-MSFT** [comment]
@ppkedar -  Could you please provide more details of the issue

**Comment by ChetanSharma-msft** [comment]
Hello @ppkedar - Could you please share the details of your deep-link that you are trying so that we can try to repro it?
Also, please let us know if you are trying it in Classic or New Teams (Desktop/Web) clients.

**Comment by ppkedar** [comment]
> @ppkedar - Could you please provide more details of the issue

Hi @SaiPratap-MSFT, we are using it to open one of our external app. We use it like like microsoftTeams.executeDeepLink(ourapp://call?123456). It is working on browser but when we try to open it in new teams app it is not working.

**Comment by ppkedar** [comment]
> Hello @ppkedar - Could you please share the details of your deep-link that you are trying so that we can try to repro it? Also, please let us know if you are trying it in Classic or New Teams (Desktop/Web) clients and Teams JS library version details.
> 
> For any other external deep linking scenarios, you can use [app.openLink](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/app#@microsoft-teams-js-app-openlink), which provides similar functionality to the now **deprecated** (starting in TeamsJS v.2.0) **executeDeepLink** API.
> 
> Please refer this documentation: https://learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/teamsjs-support-m365#pages

@ChetanSharma-msft , I have tried to use app.openLink as you suggested but it's still not working for our application.

**Comment by ChetanSharma-msft** [comment]
Hello @ppkedar - Could you please share the complete URL of the deep link and also let us know if you are trying to open a Teams app or any other kind of application?

If it is a team's app, you can use like below:
microsoftTeams.executeDeepLink(https://teams.microsoft.com/l/app/<your-app-id>?tenantId=<tenantId>);

Could you please also share the official documentation that you have followed to open Desktop Application using microsoftTeams.executeDeepLink ?

**Comment by ppkedar** [comment]
> Hello @ppkedar - Could you please share the complete URL of the deep link and also let us know if you are trying to open a Teams app or any other kind of application?
> 
> If it is a team's app, you can use like below: microsoftTeams.executeDeepLink(https://teams.microsoft.com/l/app/?tenantId=);
> 
> Could you please also share the official documentation that you have followed to open Desktop Application using microsoftTeams.executeDeepLink ?



> Hello @ppkedar - Could you please share the complete URL of the deep link and also let us know if you are trying to open a Teams app or any other kind of application?
> 
> If it is a team's app, you can use like below: microsoftTeams.executeDeepLink(https://teams.microsoft.com/l/app/?tenantId=);
> 
> Could you please also share the official documentation that you have followed to open Desktop Application using microsoftTeams.executeDeepLink ?

Hi @ChetanSharma-msft  we are using 'avaya://call?1122' this URL to open other kind of application. It is an existing implication so, I need to check the documentation. It is implemented around 3 years back.

**Comment by ChetanSharma-msft** [comment]
Hello @ppkedar - Please refer below official documentation for supported deep-links:
https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-application?tabs=teamsjs-v2

Looks like you are trying to open the Desktop application, so please share the documentation you have followed.

Also, please share a shore video where it's working including the code snippets.

**Comment by ppkedar** [comment]
Hello @ChetanSharma-msft - Yes, we are trying to open another desktop application. As it was developed 3 years ago so, I don't have the documentation which is referred by earlier developers. But, It is working with Classic Teams Desktop app and New Teams Web version. 

Adding video for working case of new Teams web and not working case for new Teams Desktop. PFA.
[Teams-Issue.zip](https://github.com/OfficeDev/microsoft-teams-library-js/files/13714496/Teams-Issue.zip)


Here is code snippets :-

`function invokeVoiceCall (phone) {
    microsoftTeams.executeDeepLink(`avaya://call?${phone}`);
  }`

**Comment by ppkedar** [comment]
Hi @ChetanSharma-msft, above implementation is working with Classic teams, adding video of that. PFA.

[Classic Teams Recording 2023-12-19 194142.zip](https://github.com/OfficeDev/microsoft-teams-library-js/files/13717129/Classic.Teams.Recording.2023-12-19.194142.zip)

**Comment by ChetanSharma-msft** [comment]
Hello @ppkedar - Thanks for sharing the information.
We will check this custom protocol related issue with engineering team and let you know the updates.

**Comment by ppkedar** [comment]
Hi @ChetanSharma-msft , what will be the farther steps for this issue. Also, is there any other way we can use this functionality without using microsoftTeams.executeDeepLink ?

**Comment by SaiPratap-MSFT** [comment]
@ppkedar  - We have informed our engineering team if there is any alternative for this. let you know once we get any updates from them. 

Thanks.

**Comment by ppkedar** [comment]
@SaiPratap-MSFT - any update from engineering team for alternative solution.

**Comment by ppkedar** [comment]
Hi @Wajeed-msft, can you please let me know update on this.

**Comment by ChetanSharma-msft** [comment]
Hello @ppkedar - Sorry for delay in response.
Could you please confirm whether it is working for you in Classic Teams desktop/Web client?

**Comment by ChetanSharma-msft** [comment]
Hello @ppkedar - Sorry for delay in response.
Could you please confirm whether your deep link with protocol is working in Classic Teams Web/Desktop client?

Also, could you please share the actual protocol name use rather than "ourapp:" ?
Deep link: microsoftTeams.executeDeepLink(ourapp://call?123456)

**Comment by ppkedar** [comment]
Hi @ChetanSharma-msft - yes, deep link with protocol is working in Classic Teams Web on Desktop client but not on New Teams Desktop client.

 actual protocol name is "avaya:".
Deep link: microsoftTeams.executeDeepLink(avaya://call?123456);

**Comment by ppkedar** [comment]
Hi @ChetanSharma-msft , @Wajeed-msft , can you please give the update on this.
