### ISSUE TITLE
Share action in secondary bowser redirects to wrong page. 

### ISSUE THREAD

**Issue by Ujwalmanandhar** [OfficeDev/microsoft-teams-library-js#2098]
Repro steps: 
1. Open article in second browser with link: https://www.msn.com/en-us/travel/tripideas/20-most-walkable-cities-in-europe-have-you-tried-these-routes/ss-AA1k8cSq?ocid=channel&prodReqSrc=manual&mosat=default#image=9 

2. Click on share icon : reference image 

![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/5673199/7a030504-6659-41c4-965f-969e2bfe07b0)

4. Copy link and inspect 
5. it is https://www.loveexploring.com/galleries/136553/europes-top-20-cities-with-the-best-walking-routes?page=1 instead of original url 
https://www.msn.com/en-us/travel/tripideas/20-most-walkable-cities-in-europe-have-you-tried-these-routes/ss-AA1k8cSq?ocid=channel&prodReqSrc=manual&mosat=default#image=9

**Comment by nwojod-MSFT** [comment]
Hi @Ujwalmanandhar thank you for reporting this issue. We have investigated and found that we do not have control over the URL redirects. We suggest trying a different link to see if the same issue occurs. If the issue persists, you may want to report it as a bug to Apple or Android
