### ISSUE TITLE
Chatbot disappears when navigating to app via deep link

### ISSUE THREAD

**Issue by yoohyojun** [OfficeDev/microsoft-teams-library-js#2102]
When accessed through the installed app, the chatbot is displayed normally as shown in the image.
![1](https://github.com/OfficeDev/microsoft-teams-library-js/assets/80876813/04e6ec58-81a9-484a-840c-e2abc49ee25b)

However, if access through deep link, the chatbot menu disappears.
and the current app is not displayed in the apps section on the left either.
![2](https://github.com/OfficeDev/microsoft-teams-library-js/assets/80876813/ce9242cd-786c-4013-a008-c713f180bb03)

manifest.json
![3'](https://github.com/OfficeDev/microsoft-teams-library-js/assets/80876813/7f91fb43-3026-43bf-a32a-d460da0f585e)

deeplink pattern
https://teams.microsoft.com/l/entity/<app-id>/<entitiyId>?context={"subEntityId": "<subEntityId>"}

+
When move the screen through a deep link and change the tab, the app installation screen is displayed as shown below.
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/80876813/74d870ca-6422-4887-a555-db49de4b2883)

Deep links are created normally and are working as desired. However, the chatbot menu disappears. I don't know what the problem is. How can I fix it?

**Comment by Meghana-MSFT** [comment]
Would it be possible for you to share the above screenshots in English language? Does your app include tabs as well?

**Comment by yoohyojun** [comment]
> 위의 스크린 샷을 영어로 공유 할 수 있습니까? 앱에 탭도 포함되어 있나요?

English text was added to the screenshot, and some of the manifest.json contents were also captured and updated.

**Comment by Meghana-MSFT** [comment]
Thank you for the additional details, we are checking this. We will get back to you.

**Comment by Meghana-MSFT** [comment]
Please use deeplink of this format https://teams.microsoft.com/l/entity/appId. appId is the App ID from Microsoft Teams admin center. 

https://github.com/OfficeDev/microsoft-teams-library-js/assets/81138249/ef963548-9246-441e-9f50-b8d8a2c902eb

**Comment by yoohyojun** [comment]
> https://teams.microsoft.com/l/entity/appId 이 형식의 딥링크를 이용해주세요. appId 는 Microsoft Teams 관리 센터의 앱 ID입니다.
> 
>  딥링크탭(deeplinktab).mp4



> Microsoft Teams 관리 센터의


I tried creating a deep link using the app ID of Microsoft Teams admin center, but an error occurred.

If you configure deep linking using External app ID, there is no problem moving the app, but the chat tab disappears.

I have no idea what the problem is. What information can I provide that might help?


-video
https://github.com/OfficeDev/microsoft-teams-library-js/assets/80876813/2803d694-7a73-4974-897c-0eb510a8cc3b


-admin center
![5](https://github.com/OfficeDev/microsoft-teams-library-js/assets/80876813/42c9ce9f-4384-4e75-ba52-86bb204eb490)

- app file
[appPackage.prod_20231220_1.zip](https://github.com/OfficeDev/microsoft-teams-library-js/files/13747242/appPackage.prod_20231220_1.zip)

**Comment by Meghana-MSFT** [comment]
We will check and update you.

**Comment by yoohyojun** [comment]
> We will check and update you.

I'm wondering when it is going to be update

**Comment by Meghana-MSFT** [comment]
We checked this with the manifest you have shared. We created 2 deeplinks both with app Id & external App Id. As mentioned in the doc, deeplink with App Id is working fine. 
Could you please let us know what error you are facing while creating a deep link using the app ID of Microsoft Teams admin center.

https://github.com/OfficeDev/microsoft-teams-library-js/assets/81138249/8cf9209b-edc3-4b37-ba10-64311b45e905

![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/81138249/1a53c058-2f07-4260-967e-9ef35405b69d)

**Comment by yoohyojun** [comment]
It seems that a typo or space was included while creating the deep link. I tested it again and it works normally. Thank you so much.
