### ISSUE TITLE
microsoftteams.app.initialize with env variables

### ISSUE THREAD

**Issue by christopher5106** [OfficeDev/microsoft-teams-library-js#2104]
The documentation forces us to create .env file that will be used by microsoftteams.app.initialize method.

For our deployments, our preferred method is to use docker environement variables or process.env variables otherwise.

Is there a way to specify the parameters (APP ID, TENANT, RETURN_URI) directly to the initialization method ?

Thanks a lot in advance

**Comment by jekloudaMSFT** [comment]
Hi @christopher5106, can you please link the documentation referring to the .env file? Are you using Teams Toolkit to configure your app?

**Comment by christopher5106** [comment]
[Here ](https://microsoft.github.io/app-camp/aad/A02-after-teams-sso/#step-3-add-the-teams-app-id-to-the-env-file)

we created a manifest.json following your teams samples to create a sso tab

**Comment by jekloudaMSFT** [comment]
Ok thank you. `microsoftteams.app.initialize` does not take these values as arguments or use them from the .env file. They are used to generate the manifest, and if you are using the "A02-after-teams-sso" template, they are used in client code via `env.js`. If you are using that template then you can modify `server.js` to set the variables in question without using the local `.env`, and you can modify the `makePackage.js` script to generate the manifest without using `.env`. If you're not using the template, then I may need some more details to help, but you may just need to modify the script that generates your manifest.

**Comment by christopher5106** [comment]
Thanks !
