### ISSUE TITLE
Popup auth flow for custom tab app is broken on Windows in new Teams

### ISSUE THREAD

**Issue by Aurora12** [OfficeDev/microsoft-teams-library-js#2105]
This is still broken in the Windows desktop app.

"@microsoft/teams-js": "^**2.18.0"** (latest at the moment)

```typescript
import * as ms from "@microsoft/teams-js";

const params: ms.authentication.AuthenticatePopUpParameters = {
	url: `auth-start?${data}`,
	width: 400,
	height: 600,
	isExternal: false,
};

ms.authentication.authenticate(params).then(......).catch(......);
```

This opens an external page in the browser instead of a popup inside the desktop app, and the auth flow is broken because of that. 

_Works fine in the classic Teams on Windows and Mac, works in Chrome with both kinds of Teams, works in macOS desktop app._

Teams app:
```
You have Microsoft Teams version 23320.3021.2567.4799.
You've got the latest version. It was last updated on 21/12/2023.
The client version is 49/23111630012.
```

OS:
```
Microsoft Windows 11 Pro
Version 10.0.22631 Build 22631
```

_Originally posted by @Aurora12 in https://github.com/OfficeDev/microsoft-teams-library-js/issues/1968#issuecomment-1866653071_

**Comment by ChetanSharma-msft** [comment]
Hello @Aurora12 - Thanks for raising your query.
We will look into it and let you know the updates.

**Comment by alicialu-MSFT** [comment]
Hi @Aurora12 ! Are you trying to do Google Auth specifically in the embedded popup, or another type of external auth?

**Comment by Aurora12** [comment]
We are not doing Google auth, it's a Microsoft auth flow. 
https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-flow-tab

**Comment by ChetanSharma-msft** [comment]
Hello @Aurora12 - Could you please refer this sample: https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/app-complete-auth/csharp

Please test and let us know if you are still facing any issue.

**Comment by tsirkey** [comment]
I'm encountering a similar issue in one of our apps which uses MS auth.
I noted the following line in the logs:

> 2024-01-11T00:20:15.734014+10:30 0x000048d0 <INFO> TeamsCloud::HandleNewWindow: Blocking internal window open requests

@Aurora12  does the popup open in the browser if you change:

> isExternal: true

?
