### ISSUE TITLE
microsoftTeams.app.getContext() doesn't resolve when using multiple tabs for Outlook and Microsoft 365

### ISSUE THREAD

**Issue by akanjimm** [OfficeDev/microsoft-teams-library-js#2106]
We came across this issue when we implemented multiple tabs for our Teams application. We noticed the microsoftTeams.app.getContext() method never gets resolved when there is a tab switch in Outlook and Microsoft 365 (works perfectly in the Teams client), unless the app is refreshed.

With the "showLoadingIndicator" property set to true in the manifest file, when there is a tab switch, the loading indicator never stops until there is a timeout error with a prompt to reload.

The non-stop loading indicator issue goes away when the "showLoadingIndicator" property is set to false, but it's still not possible to get the app context object.

**Package versions**
- teamsjs versions 2.2.0 and 2.5.0
- teams toolkit (vscode) version 5.4.0

**Steps to reproduce:**
- Scaffold a new tab app (Teams, Outlook, Microsoft 365)

- Update manifest with an extra tab
Example:
`
"staticTabs": [

        {
            "entityId": "index",
            "name": "Tab 1",
            "contentUrl": "${{TAB_ENDPOINT}}/index.html#/tab",
            "websiteUrl": "${{TAB_ENDPOINT}}/index.html#/tab",
            "scopes": [
                "personal"
            ]
        },
        {
            "entityId": "index2",
            "name": "Tab 2",
            "contentUrl": "${{TAB_ENDPOINT}}/index.html#/tab2",
            "websiteUrl": "${{TAB_ENDPOINT}}/index.html#/tab2",
            "scopes": [
                "personal"
            ]
        }

    ]
`

- Create an extra component (add logic to get context within) and update app route
Example:
`<Route path="/tab" element={<Tab />} />`
`<Route path="/tab2" element={<Tab2 />} />`

**Result**
- Microsoft Teams
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/81008428/d0bdd79d-99f1-4feb-aa9c-47bd015c8839)

- Outlook
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/81008428/cef4722b-1ee9-46c8-a221-c65378d2e079)

- Microsoft 365
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/81008428/3feda007-cfd2-41b2-a89c-e1372a35a209)

**Comment by ChetanSharma-msft** [comment]
Hello @akanjimm - Thanks for raising your query.
Engineering team will look into it and let you know the updates.

**Comment by lakhveerk** [comment]
Hello @akanjimm

Do APIs other than getContetx work fine when the `showLoadingIndicator` is set to false?

**Comment by akanjimm** [comment]
Hello @lakhveerk

Tested two APIs. The microsoftTeams.chat.isSupported() API worked but the microsoftTeams.authentication.getAuthToken() API didn't work.

Both APIs worked when app is accessed via Microsoft Teams after tabs are switched.

**Comment by lakhveerk** [comment]
Thank you for checking! We are working on a fix and will let you know when it will be released.

**Comment by akanjimm** [comment]
Hi @lakhveerk 

Thanks for the feedback. We'll check and confirm at our end.
