### ISSUE TITLE
SelectMedia returning 500 when invoked inside taskmodule

### ISSUE THREAD

**Issue by rishabhj007** [OfficeDev/microsoft-teams-library-js#2111]
I've created a webpage that will be displayed inside the task module. I'm aiming for file upload flow within the task module. The code is working in teams mobile and the older desktop client. But on the new teams, i'm running into "500" internal error. Attaching the webpage code. 
Not sure what is going wrong. Is the selectMedia API not supported within the new client?

``` 
  <html>
  <head>
  <title>Teams Task Module</title>
  <script src="https://res.cdn.office.net/teams-js/2.18.0/js/MicrosoftTeams.min.js"
              integrity="sha384-g8DoRkiR0ECQ9rwKIgY8GjQ5h0d2jp1347CmU/IRlyUHPjJZiFWEOYc+hFtT9MGL"
              crossorigin="anonymous"></script>
  <style id="theme"></style>
  </head>
  <body>
  <button id="selectFile">Select File</button>
  <button id="sendFile">Send File</button>
  <script>
          microsoftTeams.initialize();
  
          // Declare global variable
          file_var = null;
  
          microsoftTeams.getContext(function (context) {
              if (context) {
                  var theme = context.theme;
                  document.getElementById('theme').innerHTML = 'body { background-color: ' + (theme === 'dark' ? '#2b2b2b' : theme === 'contrast' ? '#ffffff' : '#eeeeee') + '; }';
              }
              else {
                  console.error('Error getting context');
              }
          });
  
          document.getElementById('selectFile').addEventListener('click', function () {
              let imageProp = {
                  sources: [microsoftTeams.media.Source.Camera, microsoftTeams.media.Source.Gallery],
                  startMode: microsoftTeams.media.CameraStartMode.Photo,
                  ink: false,
                  cameraSwitcher: false,
                  textSticker: false,
                  enableFilter: true,
              };
              let mediaInput = {
                  mediaType: microsoftTeams.media.MediaType.Image,
                  maxMediaCount: 1,
                  imageProps: imageProp
              };
              microsoftTeams.media.selectMedia(mediaInput, (error, attachments) => {
                  if (error) {
                      if (error.message) {
                          alert(" ErrorCode: " + error.errorCode + error.message);
                      } else {
                          alert(" ErrorCode: " + error.errorCode);
                      }
                  }
                  if (attachments) {
                      var file = attachments[0];
                      if (file.mimeType === 'image/png' || file.mimeType === 'image/jpeg') {
                          if (file.size <= 1048576) {
                              var reader = new FileReader();
                              reader.onload = function () {
                                  file_var = reader.result;
                              };
                              reader.onerror = function (error) {
                                  console.error('Error reading file:', error);
                              };
                              reader.readAsDataURL(file);
                          } else {
                              alert('File size must be less than 1MB.');
                          }
                      } else {
                          alert('Only PNG and JPG files are allowed.');
                      }
                  }
              });
          });
          document.getElementById('sendFile').addEventListener('click', function () {
              if (file_var) {
                  microsoftTeams.tasks.submitTask(file_var, function (error) {
                      if (error) {
                          console.error('Error submitting task:', error);
                      }
                  });
              } else {
                  alert('No file selected.');
              }
          });</script>
  </body>
  </html>

**Comment by Vaibhav-MSFT** [comment]
Hi @rishabhj007 Thanks for reporting your issue. We will test this and update you soon

**Comment by ChetanSharma-msft** [comment]
Hello @rishabhj007 - Sorry for delay in response.
We have tested the selectMedia API in Classic & New Teams web client and functionality is working at both the places.
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/59052547/1d3bbe99-a206-4b0c-8095-a25b11f6b6df)

Please make sure that you have added proper permissions in it:
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/59052547/8ca62c89-cd57-4a83-abf0-ec66e3e7b053)

We have tried below sample with Tab app:
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-device-permissions/nodejs

We have tried with npm package: `"@microsoft/teams-js": "^2.5.0",`

**Comment by rishabhj007** [comment]
Hey @ChetanSharma-msft, I've tried the sample, it still doesn't work.
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/32224970/3f2d1d70-d392-4ab7-9e15-1cdb8c99f04c)
So, going into a bit more detail. I was testing the following sample - 
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-task-module/csharp.
Here, on click of custom form, we get a new taskmodule which was supposed to run the above flow. I ran the Tab app sample and simply rendered that webapp inside the taskmodule.
In the teams desktop client, I'm seeing the webpage 
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/32224970/1cfdb1de-b8a5-4fea-851e-cb2e3eede76e)
In teams web  
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/32224970/b8a82249-d40b-47af-9b37-78f8bc4de9b5)

I think it might be a task module issue where, the from within the task module the teamsJS media API calls are failing

**Comment by rishabhj007** [comment]
Is the media API not supposed to be supported inside the task modules. If yes, then how can a message extension enable file upload from users?

**Comment by ChetanSharma-msft** [comment]
Hello @rishabhj007 - Sorry for delay in response.
Please find our investigation result here.

Followed below steps:
**1) Setup the bot-task-module sample:** https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-task-module/nodejs

2) Added a new .html file with your provided HTML code.

3) Tested the functionality in Teams Web/Desktop (Classic, New):

4) **Classic Web Client:** We are getting this error message: **"ErrorCode: 1000Please grant media permissions for the app"**
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/59052547/8e29c083-6da9-4564-8791-907ffe308581)

**Investigation Result:** This is actually a byDesign behavior means we do not have any provision to grant the media permissions from the **"task module"** but if try it from Teams Tab, we have an option to give the media related permissions.

4) **Classic Teams Web Client:** We are getting this error message: **"ErrorCode: 1000Please grant media permissions for the app"**
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/59052547/8e29c083-6da9-4564-8791-907ffe308581)

**Investigation Result:** This is actually a byDesign behavior means we do not have any provision to grant the media permissions from the **"task module"** but if try it from Teams Tab, we have an option to give the media related permissions.

5) **New Teams Web Client:** We are getting this error message: **"ErrorCode: 500An internal error occurred"**
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/59052547/6d04d649-8dd7-4b7a-b4fe-0294e98bd94f)

**Investigation Result:** Error message is misleading, but this is actually a byDesign behavior means we do not have any provision to grant the media permissions from the **"task module"** but if try it from Teams Tab, we have an option to give the media related permissions.

Regarding misleading error message, we will inform engineering team to fix the error message issue.

6) **Classic Teams Desktop client:** 

7) **New Teams Desktop client: ** We are not getting any error message.
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/59052547/1e819065-d8c5-4b2e-a685-1975aed8268d)

**Investigation Result:** There is no error message, or any response coming after clicking on the button, but this is actually a byDesign behavior means we do not have any provision to grant the media permissions from the **"task module"** but if try it from Teams Tab, we have an option to give the media related permissions.

Regarding no error message or response, we will inform engineering team to fix the issue.

So, ultimately MediaAPI permissions are not supported on Task module.
For a better experience please try it directly in the Teams Tab application.

**Comment by ChetanSharma-msft** [comment]
Update: We have raised the bug to Update the proper error message and other issue where we are not seeing any error message or response using Teams 2.1.

We will let you know if we have any update from engineering team.

**Comment by rishabhj007** [comment]
Hey @ChetanSharma-msft 
Can you post the behavior in new teams after providing the media permission to the app from settings. For me, even after providing the permissions manually, the behavior is unchanged. The newer teams is not able to invoke the camera or gallery, for adding media. It works for both old teams desktop and teams mobile.

**Comment by ChetanSharma-msft** [comment]
Hello @rishabhj007 - I tried to check but did not find any option to enable camera/device permissions from New Teams Web/Desktop client.
Could you please share the steps you have followed to enable media permissions from Teams settings in New Teams client?

**Comment by ChetanSharma-msft** [comment]
Just an update: [Location](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability#location-apis) and [Media](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/media-capabilities#media-capability-apis) APIs aren't supported in the new Teams client. We recommend using HTML5 Geolocation, and Media.

Reference doc: https://learn.microsoft.com/en-us/microsoftteams/platform/resources/teams-updates#known-issues

**Comment by rishabhj007** [comment]
@ChetanSharma-msft Makes sense. Is this feature dropped or do you plan to support it in future? Also does HTML5 media API work in teams Mobile?
Another question while we are at it - There seems to be a payload limit of around 1MB in the taskModule [submit](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/dialog.url?view=msteams-client-js-latest#@microsoft-teams-js-dialog-url-submit) functionality.
Couldn't find any documentation related to there being a payload limit. Can you shed some light on this too.

**Comment by alicialu-MSFT** [comment]
The html5 media API does not work in Teams mobile today, we're working on getting that support. 
@ChetanSharma-msft  I would actually suggest that the developer tries the geolocation API instead, that API is also supported across Outlook and Office. Please see documentation here for what's supported: https://learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/teamsjs-support-m365 
You should be able to use selectMedia in Teams mobile. 
Apologies for the cross platform inconsistencies here -- we are actively working to reconcile all of these things so you only need to call one API at once.

**Comment by rishabhj007** [comment]
Hey @alicialu-MSFT,
Do we have plans to support the teams-JS media API in the newer teams? I wanted to have a future-proof implementation, so it would be great if you can confirm this.

Also, the other question - "_There seems to be a payload limit of around 1MB in the taskModule [submit](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/dialog.url?view=msteams-client-js-latest#@microsoft-teams-js-dialog-url-submit) functionality._"
Can we have some light on this too?

Thanks a lot!!

**Comment by rishabhj007** [comment]
> Just an update: [Location](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability#location-apis) and [Media](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/media-capabilities#media-capability-apis) APIs aren't supported in the new Teams client. We recommend using HTML5 Geolocation, and Media.
> 
> Reference doc: https://learn.microsoft.com/en-us/microsoftteams/platform/resources/teams-updates#known-issues
> 
> Also, raised one doc update: [MicrosoftDocs/msteams-docs#10228](https://github.com/MicrosoftDocs/msteams-docs/issues/10228)

@ChetanSharma-msft Just wondering, how was the tab app working in new teams if the media APIs are not supported?

**Comment by Dinesh-MSFT** [comment]
Hi @rishabhj007 We can give permissions from Teams settings or from tab app. But we do not have option to provide permission from Task module.

**Comment by Dinesh-MSFT** [comment]
Hi @rishabhj007 Could please confirm whether your issue is resolved?
