### ISSUE TITLE
When receiving chatbot messages, they are not displayed in the app menu.

### ISSUE THREAD

**Issue by yoohyojun** [OfficeDev/microsoft-teams-library-js#2116]
The message is received normally and the notification badge is displayed normally on the left side.
But Notifications do not appear in the menu area within the app. How can I display it?

![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/80876813/5cf4e7a7-a6b9-482e-9688-6b026369eb9f)

**Comment by ChetanSharma-msft** [comment]
Hello @yoohyojun - Could you please confirm whether you are facing this issue in Classic or New Teams Client?

**Comment by Vikram-MSFT** [comment]
Hello @yoohyojun When receiving chatbot messages, they are not displayed in the app menu.
The app menu in Microsoft Teams is used to display apps and tabs that are installed in a team or a channel. By default, chatbot messages are not displayed in the app menu. Instead, chatbot messages are displayed in the chat or channel where the bot is installed.

**Comment by yoohyojun** [comment]
> 안녕하세요 - 클래식 또는 새 Teams 클라이언트에서 이 문제가 발생하는지 확인해 주시겠습니까?

Neither new Teams nor classic Teams appear

**Comment by yoohyojun** [comment]
> 안녕하세요 챗봇 메시지 수신 시 앱 메뉴에 노출되지 않습니다. Microsoft Teams의 앱 메뉴는 팀 또는 채널에 설치된 앱과 탭을 표시하는 데 사용됩니다. 기본적으로 챗봇 메시지는 앱 메뉴에 표시되지 않습니다. 대신 봇이 설치된 채팅 또는 채널에 챗봇 메시지가 표시됩니다.

So, is there no way to display it?

**Comment by yoohyojun** [comment]
> Hello @yoohyojun - Could you please confirm whether you are facing this issue in Classic or New Teams Client?

Neither new Teams nor classic Teams appear

**Comment by yoohyojun** [comment]
> Hello @yoohyojun When receiving chatbot messages, they are not displayed in the app menu. The app menu in Microsoft Teams is used to display apps and tabs that are installed in a team or a channel. By default, chatbot messages are not displayed in the app menu. Instead, chatbot messages are displayed in the chat or channel where the bot is installed.

So, is there no way to display it?

**Comment by ChetanSharma-msft** [comment]
Hello @yoohyojun - We will check if it's possible or now and let you know.

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
