### ISSUE TITLE
notifyFailure() called in registerOnRemoveHandler() doesn't works

### ISSUE THREAD

**Issue by adrianlachowicz** [OfficeDev/microsoft-teams-library-js#2129]
Hi, I want to add support for deleting my connector from Teams.
To the useEffect in my configuration page, I add: `microsoftTeams.pages.config.registerOnRemoveHandler`.
My problem is that despite calling the `notifyFailure` function, my connector is still deleted without any notification about failure.

The code where notifyFailure must be called:
```
      microsoftTeams.pages.config.registerOnRemoveHandler(async (removeEvent) => {
        const config = await microsoftTeams.pages.getConfig()
        console.log(`Config: \n${JSON.stringify(config)}`)
        removeEvent.notifyFailure('Test')
      })
```

What is wrong

Environment:
 - @microsoft/teams-js: 2.18.0
 - Teams in the Chrome browser (Windows)

**Comment by ChetanSharma-msft** [comment]
Hello @adrianlachowicz - Thanks for raising your query.
We will look into it and let you know the updates.

**Comment by adrianlachowicz** [comment]
@ChetanSharma-msft this is the full code in my useEffect hook:
```
useEffect(() => {
    const teams = async () => {
      await microsoftTeams.app.initialize()
      await microsoftTeams.pages.getConfig()
      const config = await microsoftTeams.pages.getConfig()

      microsoftTeams.pages.config.registerOnSaveHandler(async (saveEvent) => {
        try {
          const data: any = {
            contentUrl: window.location.origin
          }
  
          await microsoftTeams.pages.config.setConfig(data)
          

          const config = await microsoftTeams.pages.getConfig()

          mutation.mutate({
            webhookUrl: config.webhookUrl
          }, {
            onSuccess: () => {
              saveEvent.notifySuccess()
            }
          })
        } catch (error) {
          saveEvent.notifyFailure()
        }
      })

      microsoftTeams.pages.config.registerOnRemoveHandler(async (removeEvent) => {
        console.log(`Config: \n${JSON.stringify(config)}`)
        console.log("Before")
        removeEvent.notifyFailure('Test')
        console.log("After")
      })
    }

    teams()
  }, [mutation])
```

In the `registerOnRemoveHandler` I will add a code for HTTP requests to my backend server which will delete old webhooks.
I haven't done it yet, because `notifyFailure` is not working.
I think that is not the problem. The `notifyFailure` function should work without it.

**Comment by Prasad-MSFT** [comment]
@adrianlachowicz - There is a bug raised for this issue. We are following up with engineering team regarding the update. 
We will inform in this thread once we hear from them. Thanks!

**Comment by Prasad-MSFT** [comment]
@adrianlachowicz - Could you please try the suggestion mentioned [here](https://github.com/OfficeDev/microsoft-teams-library-js/issues/1825#issuecomment-1710382884) & let us know if that helps?
