### ISSUE TITLE
iconPositionVertical property is showing as 0 in Teams 2.1(Web and desktop) but showing correct value in Classic Teams

### ISSUE THREAD

**Issue by SubbaReddi** [OfficeDev/microsoft-teams-library-js#2130]
Partner is using iconPositionVertical property from teams getcontext. But observed "0" is returning in Teams 2.1
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/69682598/3d479574-e1ee-47be-b773-96006cc1034b)

Below is the screenshot from Classic teams:
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/69682598/20471368-f366-4997-baa4-5492b7d23181)

**Comment by Meghana-MSFT** [comment]
Engineering team informed that this is a known gap in T2.1. The functionality will be implemented but we do not have an ETA regarding the same. 

Same issue is reported here - https://github.com/OfficeDev/microsoft-teams-library-js/issues/2005

**Comment by SubbaReddi** [comment]
As it is duplicate request, closing
