### ISSUE TITLE
Unable to position authentication.authenticate popup

### ISSUE THREAD

**Issue by ricardasjak** [OfficeDev/microsoft-teams-library-js#2139]
Hello,

I am using Teams SDK (v2.19) to start auth flow with 3rd party auth provider. I am using `isExternal=false` flag and the popup opens at very top left edge of the screen. This is not a good UX, I would much prefer to center auth popup inside the Teams. I am Mac OS and Teams v2 user.

```
authentication.authenticate({
  url: '/teams-sign-in',
  width: 600,
  height: 600,
  isExternal: false,
})
```

Two problems:
1) Is there anything I can do to fix popup position on the screen?
2) This is even worse in multi monitor setup, the popup always appears on the main screen top left corner, despite Teams app located on the secondary screen.

**Comment by jekloudaMSFT** [comment]
Hi @ricardasjak, there is currently no way to change the position of the popup on the screen. I've added this to our backlog as a feature request, but we cannot provide an ETA for implementation due to the high volume of requests we get. We will update this thread accordingly.

**Comment by TrevorJoelHarris** [comment]
Closing this issue now that we've opened a backlog feature request
