### ISSUE TITLE
microsoftTeams.media.viewImages didn't work on new Teams

### ISSUE THREAD

**Issue by MozzaikJD** [OfficeDev/microsoft-teams-library-js#2145]
Hello, 

I'm encountering an issue with the media.viewImages API. It's working on the web app and the old desktop app.
But it's not working on the new Teams desktop app.
Version : 
- teams-js : 2.19
- MS Teams : 23335.232.2637.4844
- 49/23113028724

I search alternatives to the deeplink issue #2051 
I also explore a way to open a file in the teams desktop app with microsoftTeams.files.openFilePreview but it's an internal API.

Thanks for your help.

**Comment by ChetanSharma-msft** [comment]
Hello @MozzaikJD - Thanks for raising your query.
Could you please share the repro steps including the code snippets and reference doc so that we can try to repro it?

**Comment by MozzaikJD** [comment]
Hello @ChetanSharma-msft,
Below are the snippet of code to reproduce the problem

```
export const openImage = async (url = 'https://randomuser.me/api/portraits/women/75.jpg') => {
  if (!microsoftTeams.app.isInitialized()) {
    try {
      await microsoftTeams.app.initialize();
    } catch (error) {
      console.error('error initializing teams');
      return;
    }
  }

  microsoftTeams.media.viewImages([{ value: url, type: 1 }], (error) => {
    console.log('media.viewImages : ', url);
    console.log('media.viewImages.errorCode', error?.errorCode);
    console.log('media.viewImages.message', error?.message);
  });
};
```

This code is working on the legacy desktop app and the legacy web app but not on the new desktop app or the new web app.
On new Teams, the error is : 
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/153134711/55a47b2b-9536-443b-927a-be1992d27d70)

Regards,

**Comment by MozzaikJD** [comment]
Thanks for your reponse. I will follow the fix of this issue.
I will close the ticket

**Comment by hussain-s6** [comment]
> Hello @MozzaikJD - Sorry for delay in response. We are checking on it and let you know the updates.
> 
> Update: @MozzaikJD - Currently [Location](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability#location-apis) and [Media](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/media-capabilities#media-capability-apis) APIs aren't supported in the new Teams client.
> 
> Reference doc link: https://learn.microsoft.com/en-us/microsoftteams/platform/resources/teams-updates#known-issues

Hi, the documentation mentions:
> The Media API isn't supported in the [new Teams client](https://learn.microsoft.com/en-us/microsoftteams/platform/resources/teams-updates). We recommend you to use HTML5 media.

What does this mean exactly? Is there an example code?

**Comment by Vaibhav-MSFT** [comment]
Hello @hussain-s6 ,
Location and Media API will now not work in New Teams Client since it provides subpar user experience. And it is recommended to use HTML5 Geolocation, and Media.

**Comment by hussain-s6** [comment]
> HTML5 Geolocation, and Media

I understand this, I searched online and couldn't find another similar to an image viewer for HTML5 Media. It's more about playing video and audio files.

Can you confirm that there are no plans for new Teams to implement an image viewer similar to old Teams?

**Comment by Vaibhav-MSFT** [comment]
@hussain-s6 We will confirm it and let you know the updates.
