### ISSUE TITLE
microsoftTeams.pages.navigateToApp didn't work on "legacy" Teams

### ISSUE THREAD

**Issue by MozzaikJD** [OfficeDev/microsoft-teams-library-js#2146]
Hello, 

I am trying to use the microsoftTeams.pages.navigateToApp method to navigate to the oneDrive app. I am using the following code:

```
const appId = '5af6a76b-40fc-4ba1-af29-8f49b08e44fd';
cont pageId = '7211f19f-262a-42eb-a02e-289956491741';

microsoftTeams.pages.navigateToApp({ appId, pageId })
```

This works fine for
- new Teams Desktop client
- new Teams Web Client

but it's KO for
- old Teams Desktop client
- old Teams Web Client

In these platforms, I get an infinite loading screen.
![chrome_i4PRlvXHig](https://github.com/OfficeDev/microsoft-teams-library-js/assets/153134711/6d9267ea-d6e8-4dff-9fb1-105fe3f3131b)

An equivalent code in the old Teams Desktop and Web Client is:
```
microsoftTeams.app.openLink('https://teams.microsoft.com/_#/apps/5af6a76b-40fc-4ba1-af29-8f49b08e44fd/sections/7211f19f-262a-42eb-a02e-289956491741');
```

I am using the latest version of the Teams JS SDK (2.19.0).
For the moment I search an robust way to detect if the user is using the old or the new Teams client to adapt the code.

Can we expect a fix for this issue in the near future? Or with the deadline of the old Teams client, is it not worth it?
Thanks in advance for your help.

**Comment by TrevorJoelHarris** [comment]
Hi @MozzaikJD, sorry you are running into this problem. Can you share the version of Teams desktop and Teams web you encountered this on with me?

**Comment by MozzaikJD** [comment]
Off course :
Desktop :Microsoft Teams : 1.6.00.30616 (64 bits) -E.
For Web: How do I find this information?

**Comment by ChetanSharma-msft** [comment]
Hello @MozzaikJD - Could you please confirm whether below deep link is working for you in Classic Teams Client with Teams JS SDK v2.19.0?
`microsoftTeams.app.openLink('https://teams.microsoft.com/_#/apps/5af6a76b-40fc-4ba1-af29-8f49b08e44fd/sections/7211f19f-262a-42eb-a02e-289956491741');`

As per documentation, the tab app navigation is supported only in [new Teams client](https://learn.microsoft.com/en-us/microsoftteams/platform/resources/teams-updates).

Reference doc: https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tab-navigation#navigate-between-tabs

**Comment by MozzaikJD** [comment]
Hi @ChetanSharma-msft,

I can confirm that it works on the classic Teams client (Desktop and Web).

But it's KO on newTeams (New Teams Desktop: Open browser => New Teams Web => with a popup to go to classic teams).
(screenshot below)
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/153134711/67b53ad3-73d0-42c3-a1f2-362ff8487f25)

I'll make a fork where I will check the context to choose the right method to call. Thanks for your help
