### ISSUE TITLE
Teams js  sharing.shareWebContent method creates Draft Chat on teams , and we have to manually delete these chats

### ISSUE THREAD

**Issue by xeroOrex** [OfficeDev/microsoft-teams-library-js#2155]
Teams js  sharing.shareWebContent method creates Draft Chat on teams , and we have to manually delete these chats. PFB the screenshot 
<img width="256" alt="Capture" src="https://github.com/OfficeDev/microsoft-teams-library-js/assets/53090923/fabdbe81-9722-4a1b-8ab8-88628d3329e8">
Whenever some one is typing the user name in the people picker component of Share To Teams feature , its creating a draft version of chat with the user... So User has to manually delete all those draft version

We are using Teams JS version ^2.10.1

Can you please look into this on priority?

**Comment by Vikram-MSFT** [comment]
Hello @xeroOrex, we will investigate the issue and get back to you soon.

**Comment by Vikram-MSFT** [comment]
Hello @xeroOrex we have repro the steps from our end using Teams JS version ^2.10.1 but when we select username in the people picker component of Share to Teams feature, its not creating a draft version of chat with the user.

https://github.com/OfficeDev/microsoft-teams-library-js/assets/152395416/eebbbc87-2936-4e84-9c42-f86e664d1715

**Comment by xeroOrex** [comment]
I think you are using different functionality . I am using  Share To Teams functionality. I am using this  sharing.shareWebConten({..params})

and this is the import

import { sharing } from "@microsoft/teams-js";

**Comment by Vikram-MSFT** [comment]
Hello @xeroOrex we have repro the steps from our end using the functionality sharing.shareWebConten({..params}) but when we select username in the people picker component of Share to Teams feature, its not creating any draft version of chat with the user.

**Comment by ChetanSharma-msft** [comment]
Hello @xeroOrex - Could you please share the code sample created by you so that we can try to repro it from our end?
