### ISSUE TITLE
MS allows team names that are prone to injections

### ISSUE THREAD

**Issue by jagman-Kaur** [OfficeDev/microsoft-teams-library-js#2159]
Right now MS allows invalid teams names which can lead to injection attacks like:
`<img src="x" onerror=alert(document.domain)>`

I see there is a validation being done for channels names. Could something similar be also added for team names?

<img width="577" alt="Screenshot 2024-02-05 at 2 04 42 pm" src="https://github.com/OfficeDev/microsoft-teams-library-js/assets/96811112/9270a1aa-593e-4706-8f56-721f051fffaf">

**Comment by Meghana-MSFT** [comment]
This issue is related to Teams product. We are adding appropriate label to this question. Thank you.
