### ISSUE TITLE
authentication.authenticate() not showing pop up in desktop client.

### ISSUE THREAD

**Issue by Aliksalot** [OfficeDev/microsoft-teams-library-js#2163]
I am trying to prompt authentication using url provided from the azure/msal-node library.
My workflow goes like this:
Authenticate page gets loaded in meetingSidePanel view. From there a request to the server is made to fetch the url on which authentication will be done. After that I execute microsoftTeams.authentication.authenticate with params as shown in the code snippet below: 
<img width="424" alt="image" src="https://github.com/OfficeDev/microsoft-teams-library-js/assets/117526291/5423e0c4-893f-4aab-9b69-3215a0de2e37">

On all web browsers I have tested so far (Chrome, Edge) This has worked, pop up has been shown and authentication has been completed successfully, but that is not the case for Desktop Client.

I would be happy if you could help me with this issue, since I have been browsing old issues, reports and documentations for a few days and haven't been able to come up with a solution.
Thank you in advance.

**Comment by ChetanSharma-msft** [comment]
Hello @Aliksalot - Thanks for raising your query.
Please confirm whether you are facing this issue in Teams new client or classic Teams?

**Comment by jekloudaMSFT** [comment]
Hi @Aliksalot, can I also know if you are receiving any error response from the authentication API?

**Comment by Aliksalot** [comment]
Hello,
I was facing this issue in new Teams. It is now fixed.
Adding 
"devicePermissions": [
    "openExternal"
  ],

**Comment by ChetanSharma-msft** [comment]
Hello @Aliksalot - Thanks for the confirmation.
Shall we close this issue now?

**Comment by Aliksalot** [comment]
Yes, thank you for feedback. 

Regards, Alexander
