### ISSUE TITLE
External Login API not working on the pop out window of the Teams app on Classic Teams client

### ISSUE THREAD

**Issue by kafka-yu** [OfficeDev/microsoft-teams-library-js#2179]
Hi team,

We meet an issue after introduced the OAuth External Provider API (with isExternal=true), when pop out our Teams app, and click to login, it can jump to the system's default browser to do authencation, but after that when clicks the Open prompt, it opens the Teams client app, but the Pop out app is not able to handle the login result. Looks like still the main window is handling it.

<img width="493" alt="image" src="https://github.com/OfficeDev/microsoft-teams-library-js/assets/3942409/8dd465c2-62a2-4138-b57a-34d3ef09ee04">

<img width="674" alt="image" src="https://github.com/OfficeDev/microsoft-teams-library-js/assets/3942409/c1a52ce6-d952-43cd-9e52-0a249d7eb8d6">

{authId} is generated, no problem.

**Comment by ChetanSharma-msft** [comment]
Hello @kafka-yu - Thanks for raising your query.
Could you please share the repro setups including code snippets, so that we can check it from our end.

Also, could you please confirm whether you are facing the same issue in New Teams client and on Web/Desktop?

**Comment by kafka-yu** [comment]
hi @ChetanSharma-msft thanks for the reply, 

> in New Teams client and on Web/Desktop

No, these clients work fine. As per the API spec doc, when passing "isExternal: true" to the `authencation.authorize({...})`, it will only open the external browser on the Classic Teams desktop client.


```

import { authentication } from '@microsoft/teams-js';

    const authWinParams = {
      url: `https://abc.sample.com/auth/login.html?isExternal=true&oauthRedirectMethod={oauthRedirectMethod}&authId={authId}`,
      width: 740,
      height: 530,
      isExternal: true
    };

const result =  await authentication.authenticate(authWinParams);
//... handle the result 


```

and in the `/auth/login.html`, we pass the authId and oauthRedirecMethod etc. params to our backend to get login url, after login, we get the authId etc. info back, then call the "msteams://teams.microsoft.com/l/auth-callback?authId=xxxxx" to jump back to the teams.

Almost everything is following with https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-oauth-provider

**Comment by kafka-yu** [comment]
I got the error message now, it said:

```
Error: Authorization code contains unexpected characters. Allowed characters are a-z, A-Z, 0-9
```

Any insights where this error came from? I searched the source code of JS SDK, don't find this one.

**Comment by ChetanSharma-msft** [comment]
Hello @kafka-yu - Thanks for sharing the information.
We will look into it and let you know the updates.

**Comment by jekloudaMSFT** [comment]
Hi @kafka-yu, it looks like the authorization code in your link (the "result" parameter) does include characters outside the allowed range. You can see the decoded result by passing it through a URL decoder. The allowed values here align with those allowed by the RFC OAuth standard ([RFC 6749](https://www.rfc-editor.org/rfc/rfc6749.html)). Is this a value that your app is forming, or are you receiving it from an external OAuth provider?
