### ISSUE TITLE
Custom uploaded apps with configurableTab cannot be added to groupChat

### ISSUE THREAD

**Issue by sebiJo** [OfficeDev/microsoft-teams-library-js#2184]
New Teams native client, Version 24033.808.2706.9945 (24033.808.2706.9945)
Environments: Mac, Windows, Web
(Works fine in old Teams client)

Steps to reproduce:
1) Go to a chat with another person
2) Add a tab
3) Manage your apps
4) Upload an app
5) Upload any app package with a configurable tab for groupChat
6) "Error Message: Something went wrong when loading tab configuration dialog, please try again later."

The same seems to appear if you try add an app to a channel without adding it to the team first.

**Comment by Prasad-MSFT** [comment]
@sebiJo - We are able to repro this issue. We have raised a bug for the same. We will inform you once we get any further update from engineering team. Thanks!

**Comment by CodeABao** [comment]
same issue, please @me when have a good news

**Comment by Seenko** [comment]
any updates on this?

**Comment by CYLin-PWT** [comment]
Looking for update as well.

**Comment by Prasad-MSFT** [comment]
We got confirmation from engineering team that, the fix has been rolled out publicly. Please do verify.
