### ISSUE TITLE
Deeplink webUrl from Graph API works in Teams classic but not in Teams V2

### ISSUE THREAD

**Issue by ayoubqrt** [OfficeDev/microsoft-teams-library-js#2186]
Hello 👋 ,

I have developed a Microsoft Teams application that can open links and redirect to the good page in Teams native interface. I'm using the function `app.openLink`.

To achieve this, I use the GraphAPI that returns the `webUrl` of a teamTab for example. [Here's the official doc](https://learn.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-1.0)

So my problem is that this redirection by cliking on this link (by using `app.openLink`) works good in Teams Classic but not in Teams V2 version. In Teams V2, either it redirects me to the default tab of the channel or it says that I have to open Teams in classic version to open the link.

I saw that the links are constructed differently between the 2 versions.

So what's the solution for this ? Is there any workaround to construct the URL by any chance ? Or maybe the request to Graph API has to be different in order to have workings URL in both version.

I'm not sure if it's Graph or Teams related.

**Comment by Prasad-MSFT** [comment]
Thanks @ayoubqrt for raising your issue. We will check this from our end and will get back to you soon.

**Comment by Prasad-MSFT** [comment]
Hi @ayoubqrt - We are able to repro this issue. The deep link works in classic Teams; however, it throws error in New Teams client. We have raised a bug for the same. We will inform you once we get any further update from engineering team. 


Thanks!

**Comment by ayoubqrt** [comment]
Hi @Prasad-MSFT, thanks for the quick reply. Hope it will be fixed soon ! 
In the meantime, is there a way to construct the news urls constructed by the new Teams client ? I looked a little bit but the problem is that I don't know where to find the `_djb2_msteams_prefix_123456`

**Comment by Prasad-MSFT** [comment]
@ayoubqrt - We should only follow the deep link formats mentioned in official document.
https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-application?tabs=teamsjs-v2

**Comment by ayoubqrt** [comment]
@Prasad-MSFT But where it's mentioned in this documentation how to navigate outside the app.
For example I want to be redirect in a tab in a channel in a team

**Comment by Prasad-MSFT** [comment]
@ayoubqrt - Link to a configurable tab: https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-application?tabs=teamsjs-v2#deep-link-to-open-application-install-dialog:~:text=Link%20to%20a%20configurable%20tab%20itself%3A

**Comment by ayoubqrt** [comment]
@Prasad-MSFT 
I have this kind of error: 
The translation of the message is: `Your link points to a tab that no longer exists
We directed you to the conversation where the tab was originally located, but the tab no longer exists`

<img width="576" alt="image" src="https://github.com/OfficeDev/microsoft-teams-library-js/assets/57446997/95ea702a-7959-4e33-a8b4-15f7d13cca48">

The link: (I use all the informations from Microsoft Graph API)
const context = {
     channelId: "19:.......",
};
https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.wiki/<entityId>?webUrl=<webUrlFromGraph>&context=encodeURIComponent(JSON.stringify(context))

**Comment by Prasad-MSFT** [comment]
@ayoubqrt - The same error also we were getting which has been conveyed to engineering team as well.

**Comment by ChetanSharma-msft** [comment]
Hello @ayoubqrt - Sorry for delay in response.
We are actively checking the status of bug fixes and let you know the updates.

**Comment by Prasad-MSFT** [comment]
Hi @ayoubqrt - We tested the functionality using New Teams and observed that the issue has been fixed. 
Please do verify and confirm.

Tested with `Microsoft Teams version 24096.2100.2802.2509.`
`The client version is 49/24040701700.`

**Comment by markdon** [comment]
@Prasad-MSFT @ayoubqrt I've been using the `webUrl` of a `TeamsTab` from the GraphAPI as the `topic.webUrl` of an Activity Stream notification. Opening these notifications in Teams v2 was resulting in the same behaviour described in this issue.

My Activity Stream notifications that use these deep link urls are now working correctly in Teams v2.

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
