### ISSUE TITLE
notifySuccess working on Teams iOS but not work on Teams Android

### ISSUE THREAD

**Issue by tiennguyen1293** [OfficeDev/microsoft-teams-library-js#2189]
use methods from Teams SDK
```
  const response = await microsoftTeams.authentication.authenticate({
        url,
        width: 600,
        height: 535,
})
```

```
const response = {
          token,
          userId,
}

microsoftTeams.authentication.notifySuccess(response)
```

response after `notifySuccess`
```
response.ssoToken = undefined
```

Expected: 
- `response.ssoToken` should be `token`

Old Issue:
https://github.com/OfficeDev/microsoft-teams-library-js/issues/942
https://github.com/OfficeDev/microsoft-teams-library-js/issues/528

**Comment by Vaibhav-MSFT** [comment]
Hello @tiennguyen1293 ,
Thanks for reporting your issue. We will test this and update you soon.
