### ISSUE TITLE
registerBeforeUnloadHandler has no effect

### ISSUE THREAD

**Issue by felipc** [OfficeDev/microsoft-teams-library-js#219]
I'm trying to use the registerBeforeUnloadHandler API on my tab (configurable tab in a new channel) to warn about unsaved changes to the user, but it doesn't work.  Even though the microsoftTeams.registerBeforeUnloadHandler function exists, calling it has no effect: my callback function is never called, and it doesn't prevent the tab from being switched way.

**Comment by asnow003** [comment]
Sorry this method is currently only available to a select few for beta testing.  It's a feature that might be coming to the SDK soon.  We are testing it out and will hopefully be available very soon.
