### ISSUE TITLE
Teams China do not work with @microsoft/teams-js

### ISSUE THREAD

**Issue by tiennguyen1293** [OfficeDev/microsoft-teams-library-js#2191]
URL: https://teams.microsoftonline.cn
Version: `"@microsoft/teams-js": "^2.14.0"`

Code
```
await microsoftTeams.app.initialize()
```

I can not init Teams SDK in Teams China.

Error message
```
Error: SDK initialization timed out.
```

![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/26110369/ef53bbd8-5f77-4fb2-b181-fee84056ca6f)

**Comment by Prasad-MSFT** [comment]
Thanks @tiennguyen1293 - For raising your issue. Could you please let us know if it is happening in Classic Teams or New Teams? And also, if its specific to Desktop Client or Web Client or both?

**Comment by tiennguyen1293** [comment]
Hi @Prasad-MSFT , it is happening on both Web and Desktop App.

please me to help investigate, thanks

**Comment by Prasad-MSFT** [comment]
Thanks for informing. We will investigate this at our end.
Could you please let us know if it is happening in Classic Teams or New Teams?

**Comment by lakhveerk** [comment]
Hi @tiennguyen1293, You need to explicitly specify the url in initialization call using `validMessageOrigin` parameter. Please see this link: https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/app?view=msteams-client-js-latest#@microsoft-teams-js-app-initialize

Please do let us know if it does not resolve your issue.

**Comment by TimRowe** [comment]
@tiennguyen1293 Did you solve it? I had the same problem

**Comment by tiennguyen1293** [comment]
@TimRowe Yes, i set the url in `microsoftTeams.app.initialize(['https://teams.microsoftonline.cn'])`
