### ISSUE TITLE
Allow the use of local images in Adaptive Cards in Bot-framework

### ISSUE THREAD

**Issue by IAM5K** [OfficeDev/microsoft-teams-library-js#2195]
**Description:**

**Issue:**
Currently, Adaptive Cards do not support the use of local images. This means that developers are unable to include images from their local file system in Adaptive Cards, which limits the flexibility and customisation of the cards. If there is already such implementation please share the source.

**Feature Request:**
We would like to request the ability to use local images in Adaptive Cards. This would allow developers to include images from their local file system in Adaptive Cards, providing more customisation options and improving the user experience.

**Proposed Solution:**
One possible solution to this issue is to allow developers to pass image data as a base64-encoded data URI when rendering the card. This would involve converting the image to a base64-encoded data URI and passing it as a parameter when rendering the card.

Here is an example of how this could be implemented:

```typescript

// Pass the data URI to the Adaptive Card

    // Read the image from a local file
    const image = fs.readFileSync('path/to/image.png');
    const base64Image = Buffer.from(image).toString('base64');
    const dataUri = `data:image/png;base64,${base64Image}`;

    // Render your adaptive card for reply message
    const cardData: CardData = {
      title: "Test card",
      body: "Congratulations! Your Hello World App is running. Open the documentation below to learn more about how to build applications with the Teams Toolkit.",
      image: dataUri, // Add the image as a base64-encoded data URI
    };

    const cardJson = AdaptiveCards.declare(testCard).render(cardData);
    return MessageFactory.attachment(CardFactory.adaptiveCard(cardJson));

```

// card.json
```json
//card.json
{
  "type": "AdaptiveCard",
  "body": [
    {
      "type": "Image",
      "url": "${image}",
      "altText": "Image"
    },
    {
      "type": "TextBlock",
      "text": "Name:",
      "weight": "bolder"
    },
    {
      "type": "TextBlock",
      "text": "${title}",
      "wrap": true
    },
    {
      "type": "TextBlock",
      "text": "Message:",
      "weight": "bolder"
    },
    {
      "type": "TextBlock",
      "text": "${body}",
      "wrap": true
    }
  ]
}

```

**Additional Information:**
- This feature would provide developers with more flexibility and customisation options when creating Adaptive Cards.
- It would also improve the user experience by allowing developers to include images from their local file system in Adaptive Cards.

**References:**
- [Adaptive Cards Documentation](https://adaptivecards.io/)

**Labels:**
- enhancement
- feature-request
- help-wanted

**Comment by Prasad-MSFT** [comment]
@IAM5K - Thanks for your feedback. We have updated engineering team about this feature.
To achieve your requirements, we recommend you suggest this feature in [Teams Feedback Portal](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472).

Also, you can now get latest Teams platform updates by subscribing to the RSS feed
[What's new - Teams | Microsoft Docs](https://docs.microsoft.com/en-us/microsoftteams/platform/whats-new)

**Comment by IAM5K** [comment]
Thanks for your acknowledgement,
We are currently facing issues with URL based icons and avatars.
On research found that this feature works in SharePoint or VPA based adaptive cards, if it is already there why not here 💡.
