### ISSUE TITLE
Location API not supported in new Teams client

### ISSUE THREAD

**Issue by Nerconer** [OfficeDev/microsoft-teams-library-js#2200]
As the title says, it is not supported and therefore, it is recommended to use HTML `geolocation`.
https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?tabs=mobile%2Cteamsjs-v2#update-manifest

<img width="687" alt="image" src="https://github.com/OfficeDev/microsoft-teams-library-js/assets/7198106/fe7b9ccb-63bc-4035-9696-fbdcb1c66b59">

Is it planned to make this API work again for new Teams client in the future?

Using HTML `geolocation` is a downgrade because we can't open a map to set a custom location.

**Comment by ChetanSharma-msft** [comment]
Hello @Nerconer - Thanks for raising your query.
Yes, we have planned to support it but we don't have exact ETA to share with you.

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
