### ISSUE TITLE
iOS M365 App: chat.openChat, call.startCall, mail.composeMail not working

### ISSUE THREAD

**Issue by StefanH114** [OfficeDev/microsoft-teams-library-js#2209]
When trying to run 
`
import {
  call,
  chat,
  mail,
} from "@microsoft/teams-js";

chat.openChat({ user: target })`

`call.startCall({
        targets: [target],
        requestedModalities: [call.CallModalities.Video],
      })`
or
`mail
      .composeMail({
        toRecipients: [target],
        type: mail.ComposeMailType.New,
      })`

in the iOS M365 App it returns an error.  No teamsJS action seems to work.

Everything works fine in Outlook Desktop/Android/iOS, Teams Desktop/Android/iOS, M365 Desktop/Android.
Are there any known limitations for the M365 iOS App?

**Comment by maglims** [comment]
Hi @StefanH114 , thanks for reporting the issue. Could you help to confirm the below questions in order for us to look into further? 

Do you mean, all three call chat.openChat/call.startCall/mail.composeMail are all working fine in Outlook and Team's three platform Desktop/android/iOS, and they also work fine in M365 Desktop and android, but just not in M365 iOS, is the understanding correct?

**Comment by StefanH114** [comment]
> Hi @StefanH114 , thanks for reporting the issue. Could you help to confirm the below questions in order for us to look into further?
> 
> Do you mean, all three call chat.openChat/call.startCall/mail.composeMail are all working fine in Outlook and Team's three platform Desktop/android/iOS, and they also work fine in M365 Desktop and android, but just not in M365 iOS, is the understanding correct?

Hi, 
yes that's the situation for us.

**Comment by ChetanSharma-msft** [comment]
Hello Everyone,
Thanks for raising your query.

Mail module is currently not supported in M365 app.
Kindly refer this documentation for all supported/non-supported modules:
https://learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/teamsjs-support-m365#mail
