### ISSUE TITLE
teamSiteDomain not set when inside a personal tab

### ISSUE THREAD

**Issue by RobPethick** [OfficeDev/microsoft-teams-library-js#221]
I am part of a team developing an application that integrates closely with teams and the underlying sharepoint files

When I develop in a channel tab then I get values for teamSiteDomain, teamSitePath and teamSiteUrl. For example: 
​
teamSiteDomain: "testdomain.sharepoint.com"​
teamSitePath: "/sites/TeamName"​
teamSiteUrl: "https://testdomain.sharepoint.com/sites/TeamName"

I am trying to develop an experience within the personal tab where the user can see their data for all their teams, this requires knowing the teamSiteDomain. But when accessing the context from a personal tab I get the following:

teamSiteDomain: ""​
teamSitePath: ""​
teamSiteUrl: ""

I appreciate why teamSitePath and teamSiteUrl are empty, but I don't see why teamSiteDomain is as it was never specific to a team or channel. Could this be included?

**Comment by ydogandjiev** [comment]
Hey @RobPethick, the teamSite* properties in the SDK context point to the SharePoint site associated with the existing team where your tab is loaded. In the personal context it's expected for these to be empty. We currently don't have an SDK API that can be used to enumeration of all the user's teams and believe that's a scenario that should be handled via our Graph APIs.

Specifically, you can first enumerate all of the user's teams by calling:
`https://graph.microsoft.com/v1.0/me/joinedTeams`

And then fetch the SharePoint site for each team by calling:
`https://graph.microsoft.com/v1.0/groups/<group_id>/sites/root/weburl`

In the future there will be a more optimized way to do this but for now I believe this is your best option.

**Comment by RobPethick** [comment]
Ah, thanks for the advice 👍
