### ISSUE TITLE
clipboard write error in personal tab

### ISSUE THREAD

**Issue by CodeABao** [OfficeDev/microsoft-teams-library-js#2220]
when i use clipboard.write, even the isSupported is return true, i staill got an error like below:
{errorCode: 500, message: "Failed to copy to clipboard. NotAllowedError: Fail… 'write' on 'Clipboard': Document is not focused."}

"Failed to copy to clipboard. NotAllowedError: Failed to execute 'write' on 'Clipboard': Document is not focused."

sdk version:
@microsoft/teams-js": "^2.21.0
teams version:
24046.2807.2738.2540

**Comment by Prasad-MSFT** [comment]
Hi @CodeABao, thanks for reporting. We will check this with engineering team and will provide you the update.

Thanks!

**Comment by ZimnitskiYury** [comment]
issue #2196 

pr #2201

**Comment by CodeABao** [comment]
> HI @CodeABao, sorry you ran into this. The PR @ZimnitskiYury linked ([#2196](https://github.com/OfficeDev/microsoft-teams-library-js/issues/2196)) is a WIP to fix this issue, so please follow that PR for tracking when the fix is available!

thanks

**Comment by shrshindeMSFT** [comment]
@ZimnitskiYury @CodeABao 
Thank you for reporting this issue. We've deployed the fix, and it will soon be rolling out. I'll update this thread once the official fix has been released. 😊

**Comment by shrshindeMSFT** [comment]
Thank you for your patience. The fix for this issue is deployed and is available for everyone to use.
