### ISSUE TITLE
Custom protocol not getting triggered inside custom app using location.assign() on New Teams App (Windows). 

### ISSUE THREAD

**Issue by Stephen-Neel** [OfficeDev/microsoft-teams-library-js#2224]
- Microsoft Teams version 24033.811.2738.2546.
- The client version is 49/24020205516.
- OS: Windows 11 Pro
**location.assign()** not getting triggered, if using **http://** it is working well. 
Note : It is working well on mac.

**Comment by ChetanSharma-msft** [comment]
Hello @Stephen-Neel - Thanks for raising your query.
Could you please share the repro steps & Code snippets so that we can try to repro it from our end?

**Comment by Stephen-Neel** [comment]
> Hello @Stephen-Neel - Thanks for raising your query. Could you please share the repro steps & Code snippets so that we can try to repro it from our end?

I'm simply trying to open an app from link using location.assign()

`<a href="#" class="button" id="open-in-app">Open in app</a>


document.getElementById('open-in-app').addEventListener('click', function(evt) {

        evt.preventDefault();
        evt.stopPropagation();

        window.location.assign('ms-excel:ofv') // for example ms-excel:ofv I already have the custom protocol setup on registry editor and it is working well when using the link directly on browser.
})
`

**Comment by ChetanSharma-msft** [comment]
Hello @Stephen-Neel - Could you please confirm whether it is working in Older Teams Desktop/web clients?

**Comment by Dinesh-MSFT** [comment]
Hi @Stephen-Neel,
Could please let us whether it is working for you in older Teams web/desktop client.

**Comment by Stephen-Neel** [comment]
@ChetanSharma-msft @Dinesh-MSFT Thank you for your response. Found the issue. On old teams we've checked **userAgent includes Electron** to load a **https** page which contains custom protocol link. If it doesn't contain  **Electron** we were rendering it inside iframe ( for web app). In new teams we don't have **Electron in userAgents** so the page get loaded inside iframe and the custom url got blocked. Now we are using **clientType** from **context** and it worked well
