### ISSUE TITLE
Mobile/desktop functionality discrepancy when opening stage viewer.

### ISSUE THREAD

**Issue by gosvig123** [OfficeDev/microsoft-teams-library-js#2227]
This issue relates to a discrepancy when opening a stage viewer tab from an Iphone in an adaptive card.

In this case the functionality will work just fine on desktop and the stage viewer will open, but on mobile it will not.

If adding personal scope the app will open on mobile as well and on desktop.
To reproduce the issue create an adaptive card linking to a stage viewer and make sure the app does not require personal scope, but does have configurable tab scope.

 Below i have attached a video from desktop showing the expected behavior and a video from an iphone displaying the error.

https://github.com/OfficeDev/microsoft-teams-library-js/assets/109414278/c6d2fca3-7bc7-4099-837b-4a37511fac31

https://share.vidyard.com/watch/YgksvCNgRRcnxJAXnqqjBN

**Comment by Meghana-MSFT** [comment]
@gosvig123 - According to the doc https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/tabs-link-unfurling, when users invoke Stage View from Adaptive Cards, Stage View opens in a new Teams window along with the originating chat or channel thread in the side panel. But the UI in the video you shared is different. Could you please share your JSON with us and also could you please clarify on below point?

> make sure the app does not require personal scope, but does have configurable tab scope.

**Comment by gosvig123** [comment]
@Meghana-MSFT , thanks for the input, i pasted the json of our card below, let me know if you have any thoughts?

For the point about scope - it relates to being able to replicate the issue. We have a working version but it uses personal scope, which should not be needed to open the stage viewer. If we remove the scope it works just fine on laptop as displayed, hope that clarifies it, otherwise please ask!

our adaptive card.

`card_data={
                "$schema":"http://adaptivecards.io/schemas/adaptive-card.json",
                "type":"AdaptiveCard",
                "version":"1.2",
                "body":[
                    {
                        "type": "TextBlock",
                        "text": img_identifier,
                        "size": "Large"
                    },
                    {
                        "type": "ColumnSet",
                        "columns": [
                            {
                                "type": "Column",
                                "width": "80",
                                "items": [                    
                                    {
                                        "type": "Image",
                                        "url": 'data:image/png;base64,'+thumbnails,
                                        "width": "150px",
                                        "altText":"altText"
                                    },
                                ]
                            },
                            {
                                "type": "Column",
                                "horizontalAlignment": "Right",
                                "width": "20",
                                "items": [
                                    {
                                        "type": "ActionSet",
                                        "id": "open_viewer",
                                        "actions":[
                                            {
                                                "type": "Action.OpenUrl",
                                                "iconUrl": "https://stroke-assets.s3.eu-west-1.amazonaws.com/assets/view.png",
                                                "url": self._create_deeplink(diagnostic.id),
                                            }
                                        ]
                                    }  
                                ] 
                            }
                        ]
                    },
                    {
                        "type": "ColumnSet",
                        "separator": True,
                        "columns": [
                            {
                                "type": "Column",
                                "items": [   
                                    {
                                        "type": "TextBlock",
                                        "text": desc,
                                        "wrap": True,
                                        "style": "Default",
                                        "fontType": "Default",
                                        "isSubtle": False,
                                        "weight": "Lighter" if "complete" in desc.lower() else "Bolder",
                                        "color": "Default",
                                    } for desc in analysis_desc_list
                                ]
                            }
                        ]
                    },
                ]
            }`

**Comment by Meghana-MSFT** [comment]
As per the https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/tabs-link-unfurling#invoke-collaborative-stage-view-from-adaptive-card, below JSON is used to create a Collaborative Stage View button in an Adaptive Card. But the JSON you shared is different, could you please let us know which doc you are following.

It is also mentioned that Collaborative Stage View isn't supported in Teams web and mobile clients.

```
{
  "type": "Action.Submit",
  "title": "Open",
  "data": {
    "msteams": {
      "type": "invoke",
      "value": {
        "type": "tab/tabInfoAction",
        "tabInfo": {
          "contentUrl": "contentUrl",
          "websiteUrl": "websiteUrl",
          "name": "Sales Report",
          "entityId": "entityId"
        }
      }
    }
  }
}
```

**Comment by albagarrey** [comment]
This works but opens a Collaborative Stage View. It takes a few more seconds to load than the normal stage view in mobile. So we are using the normal stage view though deep link (`https://github.com/OfficeDev/microsoft-teams-library-js/issues/2227`). Any ideas why we get that behavior?

**Comment by Meghana-MSFT** [comment]
We will check this and get back to you.

**Comment by Meghana-MSFT** [comment]
@gosvig123 - We are not able to repro this, would you please share deployed app with us at microsoftteamsdev@microsoft.com. So that we can check and raise bug.
