### ISSUE TITLE
Regression: PeoplePicker does not search guest users in New Teams

### ISSUE THREAD

**Issue by matthiasdilger** [OfficeDev/microsoft-teams-library-js#2231]
Launching `people.selectPeople()` with `openOrgWideSearchInChatOrChannel:true`
Guest users do not show up in the search result in New Teams. It still works fine in Classic Teams.

**Comment by Prasad-MSFT** [comment]
@matthiasdilger - Thanks for raising your issue. We will check this at our end and will update you accordingly.

**Comment by Prasad-MSFT** [comment]
@matthiasdilger - We are able to repro this issue. We have raised a bug for the same. We will inform you once we get any further update from engineering team. 

Thanks!

**Comment by matthiasdilger** [comment]
This issue has been fixed in the latest dev preview of Teams. I assume the fix will make it into production at some point, so closing this issue. Thank you!
