### ISSUE TITLE
microsoftTeams.authentication.getAuthToken is not working properly in v2

### ISSUE THREAD

**Issue by kartik1225** [OfficeDev/microsoft-teams-library-js#2245]
In tab app in teams I am trying to login with below code and nothing complicated going on but still I app is getting refreshed each time I give admin consent.

```
microsoftTeams.app.initialize().then(() => {

      microsoftTeams.authentication.getAuthToken({
        successCallback: (token) => {
          console.log("Token: ", token);
          document.getElementById("token").textContent = "Token: " + token;
        },
        failureCallback: (error) => {
          console.error("Error getting token: ", error);
        }
      });
    });
```

Error response

```
{
    "error": "invalid_grant",
    "error_description": "AADSTS65001: The user or administrator has not consented to use the application with ID '5e3ce6c0-2b1f-4285-8d4b-75ee78787346' named 'Microsoft Teams Web Client'. Send an interactive authorization request for this user and resource. Trace ID: a0e3da79-4e5d-49bb-a4e4-6e41b44a9000 Correlation ID: 3a67212f-366b-4ae1-98cc-9bee273834a0 Timestamp: 2024-04-01 18:17:27Z",
    "error_codes": [
        65001
    ],
    "timestamp": "2024-04-01 18:17:27Z",
    "trace_id": "a0e3da79-4e5d-49bb-a4e4-6e41b44a9000",
    "correlation_id": "3a67212f-366b-4ae1-98cc-9bee273834a0",
    "suberror": "consent_required"
}
```

How prevent this?

https://github.com/OfficeDev/microsoft-teams-library-js/assets/21341192/64c1798f-9b3e-4db6-9981-e7f32225aa64

**Comment by Prasad-MSFT** [comment]
@kartik1225 - Thanks for reporting this. We will check this at our end and will update you accordingly.

**Comment by kartik1225** [comment]
I have only tested for the webclient so I am not sure about the desktop client. 

But I just created the fresh project simple tab > Typescript ( with basic restify server template)
and then I initialized it and tried to get the token but that popup is not working properly.

App was working fine before in previous version but from past 3-4 days I am facing this issue.

**Comment by Prasad-MSFT** [comment]
Hi @kartik1225 - We tried to repro this issue at our end, however it is working fine at our end in both MS Teams web and desktop client.
```
You have Microsoft Teams version 24091.200.2790.8949.
The client version is 49/24032122305.
```
From the error it seems line the admin of the tenant has not approved the app. You need to check in the portal to see if everything is configured correctly.
Please go through this [doc](https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/grant-admin-consent#:%7E:text=Select%20Azure%20Active%20Directory%20then%20App%20registrations.,the%20permissions%20the%20application%20requires.) to learn about admin consent experience.

If everything is configured properly, we recommend sharing the repro video and/or the deployed manifest with tenant credentials, so that we can directly raise a bug.

Thanks!

**Comment by kartik1225** [comment]
Hey, thanks for the update. I will take a look into this and I will get back to you as soon as possible.

**Comment by rahul-chanana** [comment]
We are facing the same issue with our app.

microsoftTeams.authentication.getAuthToken() seems to be broken when we switch to new teams (v2) in web browser. It works fine in deskop clients though.

Additional info: as a result of above mentioned bug ("Invalid authResponse received from msal for resource api") the consent window is not opening up as a pop up but as a redirect in same browser tab as https://teams.microsoft.com/v2

Please provide an update about status of this bug.

**Comment by kartik1225** [comment]
I am also facing the same issue in V2 web.

**Comment by kartik1225** [comment]
I have exposed the api correctly and this is simple basic app but when I try to get the token it is giving me this.

Here is the auth code.

```
microsoftTeams.app.initialize().then(() => {
    getClientSideToken()
        .then((token) => {
            console.log("2. Send token to server "+ token);
            return axios.post(`${apiBaseUrl}/api/authenticate/ms-teams`, { token });
        })
        .catch((error) => {
            console.log(error);
        });
});

    function getClientSideToken() {

        return new Promise((resolve, reject) => {
            console.log("1. Get auth token from Microsoft Teams");
            
            microsoftTeams.authentication.getAuthToken().then((result) => {
                resolve(result);
            }).catch((error) => {
                reject("Error getting token: " + error);
            });
        });
    }
```

Above code was taken from the official documentation [here](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-code#add-code-for-getauthtoken).'

And this is how it is behaving right now.


https://github.com/OfficeDev/microsoft-teams-library-js/assets/21341192/f1825668-72e3-42e7-a72c-307fb6cbf680

Here how I am exposing the api in the azure side.

<img width="1728" alt="Screenshot 2024-04-17 at 16 38 44" src="https://github.com/OfficeDev/microsoft-teams-library-js/assets/21341192/1e0b359a-4fc5-4a97-b5fa-8f46e1e01783">
<img width="824" alt="Screenshot 2024-04-17 at 16 42 23" src="https://github.com/OfficeDev/microsoft-teams-library-js/assets/21341192/56810eeb-78fb-4fd0-b757-ef154c7c5af0">

Response
```
{
    "error": "invalid_grant",
    "error_description": "AADSTS65001: The user or administrator has not consented to use the application with ID '5e3ce6c0-2b1f-4285-8d4b-75ee78787346' named 'Microsoft Teams Web Client'. Send an interactive authorization request for this user and resource. Trace ID: d76976d3-56e8-4a53-bc73-01451b7b6d00 Correlation ID: 47885f4a-95a4-4645-baf9-d247372b2dcf Timestamp: 2024-04-17 11:11:23Z",
    "error_codes": [
        65001
    ],
    "timestamp": "2024-04-17 11:11:23Z",
    "trace_id": "d76976d3-56e8-4a53-bc73-01451b7b6d00",
    "correlation_id": "47885f4a-95a4-4645-baf9-d247372b2dcf",
    "suberror": "consent_required"
}
```

When I give consent It is keep giving me this token error and automatically refreshes the browser. Please help me I am stuck from past 2 months.

**Comment by Prasad-MSFT** [comment]
Thanks for sharing these. We will check this at our end and will update you.

**Comment by dmcweeney** [comment]
Any update on this - we also are having similar problems upgrading from V1 to V2 sdk!

**Comment by ksdaniel** [comment]
Could it be you still need to authorize the client application (under Exponse an API in the App registration settings)?

![image](https://github.com/user-attachments/assets/398f64a9-bab7-4491-97f9-0aef58fb7aae)
