### ISSUE TITLE
configName is missing for Settings interface

### ISSUE THREAD

**Issue by VKAlwaysWin** [OfficeDev/microsoft-teams-library-js#225]
For connector page that would be great to have configName property for src/public/settings.ts 

configName should be part of setSettings and provided by Settings interface.
https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/connectors/connectors-creating#getsettings-response-properties

**Comment by asnow003** [comment]
Let me get this in our backlog and see if we can work this change in.
