### ISSUE TITLE
Teams JS throws error "resourceRequiresConsent" even after consent

### ISSUE THREAD

**Issue by alexisconia** [OfficeDev/microsoft-teams-library-js#2252]
Hi,

We are encountering an error with teams-js and the new version of Teams.
We have some users that got the error "resourceRequiresConsent" even if they did the consent before.

After some investigations, I can reproduce by removing the consent and restarting the process. I always get the error.
It's working with the previous Teams Version

@microsoft/teams-js : v2.21.0
Teams client version: 1415/24022924517

This problem also impact some of our customers.

**Comment by Dinesh-MSFT** [comment]
Hi @alexisconia - Thanks for raising the query.
We will look into it and let you know the updates.

**Comment by alexisconia** [comment]
Hi @Dinesh-MSFT 
I did a test on a Dev tenant with Jira Cloud app and I get the same result
![Uploading Screenshot 2024-04-09 at 06.17.40.png…]()

**Comment by alexisconia** [comment]
Hi @Dinesh-MSFT, please find the screenshot about the same problem with another app. It seems that the problem is only happening when the app uses the silent parameter to true
![Screenshot 2024-04-10 162953](https://github.com/OfficeDev/microsoft-teams-library-js/assets/6534961/7ecdc3f2-fe95-4752-bd51-e25d18ed90bd)

**Comment by Dinesh-MSFT** [comment]
Hi @alexisconia, 
We tried to install the Jira cloud application, we couldn't find any error. Could you please share the exact repro step. So, we will look into it and let you know the update.

**Comment by alexisconia** [comment]
Hi @Dinesh-MSFT 
I'm using a dev tenant, and the Teams Web Client V2. 
You need to use a tenant where you have never consented to the app (or remove the app from Entra ID Portal). Try to add the app to a channel and get the dialog to authenticate, validate the consent and you get the message "resourceRequiresConsent".

**Comment by alexisconia** [comment]
I have a video that I can send you if needed

**Comment by Dinesh-MSFT** [comment]
Hi @alexisconia,
please share the video.

**Comment by alexisconia** [comment]
Hi, Sorry for the delay. With the last client update it seems to be ok now.
