### ISSUE TITLE
TeamsSDK to provide information about customer desktop forced theme information (e.g., whether it is Aqua OR Desert)

### ISSUE THREAD

**Issue by dalyap** [OfficeDev/microsoft-teams-library-js#2253]
Devs from Teams implemented forced color mode. Unfortunately this method doesn't appear to apply for 3p apps built with Unity. We'd love to see if there's some help as we move forward to solve for high contrast accessibility. I'm forwarding some notes from our dev lead Tyler Libey. Wondering if there's a hook from SDK that could be shared, Tyler's thought at the end! Please let us know.
Since avatars in teams is a 3p app, all the exposed pieces need to exist here: https://github.com/OfficeDev/microsoft-teams-library-js/blob/fb98b73cb18bd49112993398f4a412fc3c2240f3/packages/teams-js/src/public/app.ts#L149C4-L149C4
Currently that SDK only supports outputs for "default", "dark", "contrast". Note - it does output "light" with teams 2.1, but I couldn't get it to output anything specific to desert.
The version of fluent northstar we are on does not support a "desert" theme. But it does support a forced colors theme. The original plan for other reasons anyways was to upgrade to fluent components v9, but I'm having a hard time finding whether or not desert (or forced colors) exists there already.
So - since we don't know "desert" or event a difference between "contrast" and "forced", we could treat all contrast modes as "forced".
 
In some initial testing this appears to work fairly well for the sidepanel (desert, aquatic as forced)
 
There are two issues here:
The icons for "desert" vs "aquatic" need to be different. Since we use png images (not fluent icons) I do need a way to determine the theme from the SDK. All of the examples around "forced" theme that are linked don't provide that two way readability - its only one way (read/apply from system). This is for the emote icons, the none icon, the mood slider, and a few others.
The themeing isn't quite right in the forced mode. For example - the hover state doesn't go dark orange (desert)  or neon blue (aquatic) when hovered. This might just be an issue with the version of fluent northstar we are on and could be fixed with fluent V9.
Last bit - this is only for the sidepanel. For something like the Customizer UI - the ability to apply the "forcedColors" theme doesn't seem viable. For that we'd need a specific theme for desert mode, which would 100% require a hook from the teams sdk to read that. BUT since it appears that teams has gone away from labeling specific themes and is instead going for "windows theme", that may not be possible to have.

**Comment by Prasad-MSFT** [comment]
@dalyap - Thanks for your feedback. We will inform engineering team about this and will update this thread once we hear from them. Thanks!

**Comment by Prasad-MSFT** [comment]
@dalyap - We got update from engineering team that, "Currently exposing the forced color themes via the App SDK is not supported. We only support three themes - light, dark, and contrast."
Engineering team is aware of this feature ask and internal discussion is going on. Also, to achieve your requirements, we recommend you give your feedback in [Teams Feedback Portal](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472).

**Comment by dalyap** [comment]
Thank you @Prasad-MSFT

**Comment by vikramtha** [comment]
Hi @dalyap  I am the PM on theming and just to make sure I understand your scenario. You want a way for the SDK to tell the app if the user has selected "desert" or "aquatic" as a theme correct? I will add this to the ongoing spec on including more parameters to theme and let the PM's know on Avatars once this is available.

**Comment by vikramtha** [comment]
No longer a TeamsJS SDK relevant issue - There was an internal chat where this seemed to be the expected design from Windows theming and Edge
