### ISSUE TITLE
Teams context on iOS has invalid teamsSiteUrl with 2024-MarT2 update

### ISSUE THREAD

**Issue by nbelyh** [OfficeDev/microsoft-teams-library-js#2266]
The problem started with Teams 2024 March T2 update.
**On iOS**, now it turned out to be NOT THE TEAMS SITE URL passed in context, but a URL to a web page on the root site.

Was (correct, also correct on all other Teams client versions, i.e. Android/Desktop/Web):
https://something.sharepoint.com/sites/TeamSite

Now (iOS, after March 2024 update):
https://something.sharepoint.com/_layout/15/sharepoint.aspx 

This is causing a problem in our application, because it assumes that `teamsSiteUrl` contains a URL of teams site, not a page.
Would appreciate some ideas for workarounds (how do I get the team site).

In the documentation, it is also stated that the old way is correct:
https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/microsoftteams.context?view=msteams-client-js-1.13.1#@microsoft-teams-js-microsoftteams-context-teamsiteurl

![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/528366/3c1d0a36-3c0f-4454-b326-0d3c9326794c)

This property should not be some a page on a root site, this should be a team site url.

**Comment by nbelyh** [comment]
I've investigated a bit, the problem is the `teamSiteUrl` that is passed in the teams context:

On iOS, it turned out to be NOT THE TEAMS SITE URL, but a URL to a web page on the root site. 

Was (correct, also correct on all other Teams client versions):
`https://something.sharepoint.com/sites/TeamSite`

Now (iOS, March 2024 update):
`https://smething.sharepoint.com/_layout/15/sharepoint.aspx `

What the hell, honestly 😭

**Comment by Prasad-MSFT** [comment]
@nbelyh - Thanks for raising your issue. We will check this at our end and will update you accordingly.

**Comment by Prasad-MSFT** [comment]
@nbelyh - Just to be sure, are you testing using @microsoft/teams-js": "^1.13.1 or Teams JSv2?

In Teams JSv2 it is referred as `sharepointSite.url`

**Comment by nbelyh** [comment]
1.13.1 (our app is still on 1.x version). But I don't think there is difference, as it's only on iOS.

**Comment by Prasad-MSFT** [comment]
@nbelyh - We have raised a bug for the same. We will inform you once we get any further update from engineering team. 

Thanks!

**Comment by otahi** [comment]
@Prasad-MSFT 
Hi, 
At this stage, it seems that the issue occurs inconsistently, with some users experiencing it while others do not.

I have a few questions regarding this issue:

1. Although there might already be some measures in place, is there any information you can share about the current status or actions taken?
2. Is there an estimated timeline for when all the measures will be fully implemented and the issue resolved?

Thank you for your support.

**Comment by Prasad-MSFT** [comment]
@otahi - Apologies. Engineering team is currently working on the fix, however there is no ETA to share at the moment. We will inform you once we have any update. Thanks!

**Comment by otahi** [comment]
@Prasad-MSFT Thank you for the reply. I appreciate your efforts and will await further updates.

**Comment by Prasad-MSFT** [comment]
@nbelyh , @otahi - We got update from engineering team that the issue has been fixed.

Thanks!
