### ISSUE TITLE
Stage view in personal tab with sideloaded app 

### ISSUE THREAD

**Issue by robhavlicek** [OfficeDev/microsoft-teams-library-js#2268]
Hi,
I have a problem with the stage view in the personal tab. If the app is sideloaded, the stage view does not work. By trial and error I have come to the conclusion that it is due to a different appId. When sideloaded, the appId (from manifest) is shown as externalId and a different Id is used for the app.

If I use this Id, stage view works as expected. Is this the expected behavior?
How can I find out this Id from the context of Teams? Graph api, for this purpose, requires permissions that I don't want to ask our users.

![image_2024-04-12_110624498](https://github.com/OfficeDev/microsoft-teams-library-js/assets/21018677/23d327e9-a4ec-456a-87cc-136ab455f56a)
 
![image_2024-04-12_110540166](https://github.com/OfficeDev/microsoft-teams-library-js/assets/21018677/e5303215-45c0-46fa-9395-c1f50123e3f5)

**Comment by Prasad-MSFT** [comment]
According to this [documentation](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-application?tabs=teamsjs-v2#app-id-for-different-types-of-apps), for **side-loaded apps**, we should use Manifest ID.

**Apps submitted to org catalog:** Org catalog ID
**Apps submitted to Teams app store:** Store ID

**Comment by robhavlicek** [comment]
Oh, I see. I've read this [documentation ](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/open-content-in-stageview?tabs=withchat#invoke-from-deep-link) and there's no mention of it. So I'll modify my backend to work with all IDs, since we're using one instance of the application for multiple deployments. 
Thank you,

**Comment by AE-MS** [comment]
> Oh, I see. I've read this [documentation ](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/open-content-in-stageview?tabs=withchat#invoke-from-deep-link) and there's no mention of it. So I'll modify my backend to work with all IDs, since we're using one instance of the application for multiple deployments. Thank you,

FYI I filed a doc bug to clarify the documentation to which you linked:
https://github.com/MicrosoftDocs/msteams-docs/issues/10762
