### ISSUE TITLE
Deeplink to file using /viewer/teams does not work in New Teams

### ISSUE THREAD

**Issue by pheidler** [OfficeDev/microsoft-teams-library-js#2269]
Deeplinking to a file not stored in a Channel/Shared Documents folder no longer works in New Teams. This previously worked in Classic Teams using the /viewer/teams API. See here: https://techcommunity.microsoft.com/t5/teams-developer/how-to-open-a-file-in-the-custom-spfx-teams-tab-in-ms-teams/m-p/1786898/highlight/true#M2003

**Comment by Prasad-MSFT** [comment]
Hi @pheidler - Could you please let us know which deep link format you have used to navigate to file?

**Comment by pheidler** [comment]
@Prasad-MSFT Yes, like this:
https://teams.microsoft.com/_#/${document.FileType}/viewer/teams/${document.Url}?threadId=${channelId}&baseUrl=${siteUrl}&fileId=${document.FileUniqueId}&ctx=files&viewerAction=view

**Comment by pheidler** [comment]
@Prasad-MSFT This was advised by someone with MSFT support in this thread: https://techcommunity.microsoft.com/t5/teams-developer/how-to-open-a-file-in-the-custom-spfx-teams-tab-in-ms-teams/m-p/1786898/highlight/true#M2003

The official documentation refers to opening links to files in a channel, but doesn't mention files stored in other SharePoint folders. 

This is the complete deep link: https://teams.microsoft.com/_#/pdf/viewer/teams/https:~2F~2F[tenant_name].sharepoint.com~2Fsites~2FMark8ProjectTeam2~2FMeetingPack_4~2FAgendaDocuments~2F[file_name].pdf?threadId=19:082b34f4abf84eacbcef8ac5d0a923db@thread.tacv2&baseUrl=https:~2F~2F[tenant_name].sharepoint.com~2Fsites~2FMark8ProjectTeam2~2FMeetingPack_4&fileId=b3eaa820-75ee-4f2b-8b44-5fa60c848789&ctx=files&viewerAction=view

Thanks!

**Comment by Prasad-MSFT** [comment]
> @Prasad-MSFT Yes, like this: [https://teams.microsoft.com/_#/${document.FileType}/viewer/teams/${document.Url}?threadId=${channelId}&baseUrl=${siteUrl}&fileId=${document.FileUniqueId}&ctx=files&viewerAction=view](https://teams.microsoft.com/_#/$%7Bdocument.FileType%7D/viewer/teams/$%7Bdocument.Url%7D?threadId=$%7BchannelId%7D&baseUrl=$%7BsiteUrl%7D&fileId=$%7Bdocument.FileUniqueId%7D&ctx=files&viewerAction=view)

@pheidler If your file is not stored in any channel, where is it stored in SharePoint? and which thread/channel id are you using in the deeplink Url which you shared?

This is the only supported deep link format for configuring a deep link to connect to a file in a channel:
`https://teams.microsoft.com/l/file/<fileId>?tenantId=<tenantId>&fileType=<fileType>&objectUrl=<objectUrl>&baseUrl=<baseUrl>&serviceName=<Name>&threadId=<threadId>&groupId=<groupId>`
https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-teams#generate-deep-links-to-a-file-in-a-channel

There is no deep link format available for files stored outside team's channel.

**Comment by pheidler** [comment]
@Prasad-MSFT It's stored in the team site. We use this feature to display documents that are managed through our SPFx app and stored in a separate folder than Shared Documents. If this is not currently supported, can we expect this feature to be added at some point?  This is a key feature for us that the switch to New Teams has removed.

**Comment by Prasad-MSFT** [comment]
@pheidler- To achieve your requirements, we recommend you give your feedback in [Teams Feedback Portal](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472).

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
