### ISSUE TITLE
Regression: dialog.url.open() does not work in configurable tabs in group chats in New Teams (reloading the tab works)

### ISSUE THREAD

**Issue by matthiasdilger** [OfficeDev/microsoft-teams-library-js#2288]
Teams JS lib 2.20.0
Only group chats in New Teams are affected, channels work fine. Both work fine in Classic Teams.

To reproduce:
Create a Teams app with bot and configurable tab in groupchat scope
In the tab add a button that executes `dialog.url.open({url:'https://someUrlFromTheManifest.com', size: {height:'medium',width:'medium'}})`
Add the tab to a group chat (`configurationUrl` from manifest gets called, you need to execute `pages.config.setConfig()` with your tab url)
After configuration is done and your tab has loaded, navigate to the 'chat' tab of the group chat and navigate back to your tab
Press the button and nothing happens.

The web dev console shows the following error which implies that channel logic is called, although we are in a group chat:
![Screenshot 2024-04-24 at 09 59 45](https://github.com/OfficeDev/microsoft-teams-library-js/assets/5625718/ff433bb2-1cd0-4616-973e-09dde76d9d48)

Reloading the tab fixes the problem, but navigating to the group chat 'chat' and back to your group chat tab makes the problem re-appear. It seems that this navigation path has its own logic, which fails.
![Screenshot 2024-04-24 at 10 02 31](https://github.com/OfficeDev/microsoft-teams-library-js/assets/5625718/fe7a0526-555e-48a7-9a16-ea447df2fd6e)

This problem has been present in the dev preview for some time and seems to now have made its way into the production ring.

**Comment by Vaibhav-MSFT** [comment]
Hello @matthiasdilger ,
Thanks for reporting your issue. We will test this and update you soon.

**Comment by matthiasdilger** [comment]
Hi @Vaibhav-MSFT, do you have an update?

**Comment by Vaibhav-MSFT** [comment]
@matthiasdilger , we are still not able to repro the issue, but will share the updates asap.

**Comment by matthiasdilger** [comment]
@Vaibhav-MSFT I have just reproduced the issue on https://teams.microsoft.com/v2/, no dev preview. If you follow the steps there, you should be able to see the issue.

**Comment by Vaibhav-MSFT** [comment]
@matthiasdilger , we tried with the code snippet and steps shared but are we are not exactly able to repro the exact issue you are facing. Can you provide us with some more snapshots of the code snippets?

**Comment by matthiasdilger** [comment]
Hi @Vaibhav-MSFT the other bits are all standard code, your configuration page (that gets called when you try to add the tab to the group chat) has to set up the tab [like this](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page?tabs=teamsjs-v2):

```
microsoftTeams.app.initialize().then(() => {
microsoftTeams.pages.config.registerOnSaveHandler((saveEvent) => {
                const configPromise = microsoftTeams.pages.config.setConfig({
                    websiteUrl: "https://myUrl.com",
                    contentUrl: "https://myUrl.com",
                    removeUrl: "https://myUrl.com/remove",
                    entityId: "test",
                    suggestedDisplayName: "Test"
                });
                configPromise.
                        then((result) => {saveEvent.notifySuccess()}).
                        catch((error) => {saveEvent.notifyFailure("failure message")});
            });
microsoftTeams.pages.config.setValidityState(true);
});
```

And once the tab has been loaded, the button pressed event needs to execute:

```
const taskInfo = {
          title: "Do something",
          size: {
              height: 'medium',
              width: 'medium'  
          },
          url: 'https://myUrl.com'
      };

        submitHandler = (result) => {
           console.log(result);
        };
        microsoftTeams.dialog.url.open(taskInfo, submitHandler);
```

You can reproduce this issue on https://teams.microsoft.com/v2, I'm getting quite a few reports from users already.

**Comment by matthiasdilger** [comment]
This has finally been fixed in the current Teams dev preview, closing
