### ISSUE TITLE
Generate a deep link to share content to stage in meetings does not work in new Teams

### ISSUE THREAD

**Issue by viclarsson** [OfficeDev/microsoft-teams-library-js#2297]
The deep linking feature to meeting stage explained in this documentation does not seem to work in the new teams client: https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-in-meeting?tabs=method-1#generate-a-deep-link-to-share-content-to-stage-in-meetings

Nothing really happens and users are left confused.

Anything known?

**Comment by Prasad-MSFT** [comment]
Hi @viclarsson - Could you please make sure you are using the correct ID?
The following table lists the different types of app IDs used for different types of apps for deep links:

Custom app uploaded in Teams : Manifest ID
Apps submitted to org catalog : Org catalog ID
Apps submitted to Teams Store : Store ID

Ref: https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-application?tabs=teamsjs-v2#app-id-for-different-types-of-apps

**Comment by viclarsson** [comment]
> Hi @viclarsson - Could you please make sure you are using the correct ID? The following table lists the different types of app IDs used for different types of apps for deep links:
> 
> Custom app uploaded in Teams : Manifest ID Apps submitted to org catalog : Org catalog ID Apps submitted to Teams Store : Store ID
> 
> Ref: https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-application?tabs=teamsjs-v2#app-id-for-different-types-of-apps

Will do!
Just to understand, is this a recent change or a change with the new Teams? As we have had it working up until recently.
Thanks for the quick reply!
