### ISSUE TITLE
SDK initialization timed out

### ISSUE THREAD

**Issue by sschoeb** [OfficeDev/microsoft-teams-library-js#2298]
We are using the version 2.20.0 of the teams-js library.

We see more and more the following error reported in our app:
`SDK initialization timed out.`

There were already two of this issues in this repo:
https://github.com/OfficeDev/microsoft-teams-library-js/issues/1894
https://github.com/OfficeDev/microsoft-teams-library-js/issues/1681

Both of these are closed. But this is definitely not fixed. We currently even implemented a retry, but does not help either. 

What does microsoft expect from us to do if we get this error from the framework? Should we show an error to the user? 

here the callstack:
```
Error Stack: at formatArgs (webpack:///node_modules/@microsoft/teams-js/dist/MicrosoftTeams.min.js:1:49345)
at formatArgs (webpack:///node_modules/@microsoft/teams-js/dist/MicrosoftTeams.min.js:1:54162)
```

Do you need any additional information?

**Comment by TrevorJoelHarris** [comment]
Hi @sschoeb , I'm sorry that you've run into this problem. Would you mind sharing an example from your code of the `app.initialize` call that you are making and what arguments (if any) you are passing to it?

**Comment by sschoeb** [comment]
Thanks for your reply @TrevorJoelHarris 

Sure, this is what we do:
```
import {app} from '@microsoft/teams-js';

await app.initialize();
```

As this is an angular app, we call initialize() within the ngOnInit method. 
Please let me know if you need any additional information.

**Comment by TrevorJoelHarris** [comment]
@sschoeb Can you try 2 things for me when you have time:

Follow the instructions [here](https://github.com/OfficeDev/microsoft-teams-library-js/wiki/TeamsJS-Logging#enabling-logging) to enable client side logging and then reply to this with the client logs you see during a failed app initialization.

**Comment by TrevorJoelHarris** [comment]
Oh, one other quick question. I am assuming you are seeing this in Teams on a desktop browser, but if that's not the case please let me know!

**Comment by ChetanSharma-msft** [comment]
Hello @sschoeb - Please confirm the above details and let us know if you are facing this issue in New Teams client?

**Comment by sschoeb** [comment]
@TrevorJoelHarris Thanks for the feedback. I'll enable the client side logging and will come back here as soon as I've detailed logs.

Yes, looks like all reports are on Desktop (not yet sure about the version, but I try to figure that out as well)

**Comment by sschoeb** [comment]
@TrevorJoelHarris Takes a while till I have that stuff deployed properly to get the logs. Will reopen the task as soon as I've proper logs. Thank you very much for your help up to now!

**Comment by TrevorJoelHarris** [comment]
@MajaEffenberg I don't have a lot of Angular experience, but I imagine that you could override the console.log function and send the log statements somewhere else before writing them to the console? Something like this:

```typescript
let actualLog = console.log;

console.log = function(message){
    alert(message); // Have this redirect log messages to wherever you want
    actualLog(message);
};

console.log('hi');
```
