### ISSUE TITLE
openLink API to support windowing preference

### ISSUE THREAD

**Issue by ikangalia** [OfficeDev/microsoft-teams-library-js#2300]
Can we add a new parameter to the `openLink` API to support opening links in a new host instance? 

Currently, we can use the API to open links within the same window instance of the host. But it would be great to support functionality similar to:

```javascript
window.open("<parsed url>", "_blank", ...)
```

**Comment by vikramtha** [comment]
Hey, We can create this and I will ping you separately on how to properly request this feature!
