### ISSUE TITLE
On click of adpative cards, Teams is asking for a app update

### ISSUE THREAD

**Issue by Balaji-Gopal** [OfficeDev/microsoft-teams-library-js#2312]
With the click of an adaptive card, Teams is asking to update the app after upgrading to the New Teams Version.

Is this something avoidable or is it mandatory?

For security/privacy reasons I am unable to attach any screenshots or videos

**Comment by Vikram-MSFT** [comment]
Hello @Balaji-Gopal 
It seems that the prompt to update the app after clicking an adaptive card in Teams following an upgrade to the new Teams version is related to the adaptive card schema version used by the app. The Teams platform requires apps to use the latest schema version of the official SDK, which includes Teams-specific properties for adaptive cards. If the app's adaptive cards are not using the latest schema, Teams may prompt for an update to ensure compatibility with the new client. This update prompt is likely not avoidable.

**Comment by Balaji-Gopal** [comment]
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/16814811/ff6f1cbc-767a-4071-b7d4-afeb78713234)

I am using version 1.3 and 1.4, Will upgrading this to 1.5 solve my issue?

**Comment by Vikram-MSFT** [comment]
Hello @Balaji-Gopal 
Yes you can go with the upgradation of your version.
