### ISSUE TITLE
MS Teams Post Adaptive Card and Wait for Response stops in Power Automate flows

### ISSUE THREAD

**Issue by claudiu-mera** [OfficeDev/microsoft-teams-library-js#2313]
I am using MS Teams Post Adaptive Card and Wait for Response action in a Power Automate flow. 

Each time user input is provided, a banner with message "Your response was sent to the app" is displayed below the adaptive card. The flow remains in Running state, as it is still waiting for user input.

Example of Adaptive card body:
```
{
    "type": "AdaptiveCard",
    "body": [

      {
        "type": "Input.ChoiceSet",
        "id": "selector",
        "style": "expanded",
        "label": "Please choose an option:"
        "isMultiSelect": false,
        "choices": [
          {
            "title": "Red,
            "value": "1"
          },
          {
            "title": "Green",
            "value": "2"
          },
          {
            "title": "Blue",
            "value": "3"
          }
        ]
      }
    ],
    "msteams": {
      "width": "Full"
    },
    "actions": [
      {
        "type": "Action.Submit",
        "title": "Submit"
      }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.3"
  }
```

Notes:
1. The flow was working fine until a couple of days ago, when it suddenly stopped working. 
2. The issue is encountered only on some environments, while on others not.

**Comment by Prasad-MSFT** [comment]
Hi @claudiu-mera - Could you please let us know what issue you are facing here? Is the Power Automate flow not sending the adaptive card?

**Comment by claudiu-mera** [comment]
@Prasad-MSFT , below you can find a couple of screenshots that describe the issue:

Expected behavior:
After pressing submit
- confimation message (defined in Post adaptive card and wait for reponse) displayed 
- flow continues execution
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/19303385/4ef7fb26-576c-4f7a-a8d1-cdbc637f0359)

Actual behavior:
After pressing submit
- banner with message "Your response was sent to the app" is displayed below adaptive card
- no data submitted
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/19303385/85b0bfc6-7858-4482-a016-b73bef57874b)

**Comment by Prasad-MSFT** [comment]
@claudiu-mera - We tried to repro this issue sending below adaptive card by Power Automate flow
```
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.3",
    "body": [
	{
      "type": "Input.ChoiceSet",
      "id": "myColor",
      "style": "expanded",
      "label": "What color do you want?",
      "isMultiSelect": false,
      "choices": [
        {
          "title": "Red",
          "value": "1"
        },
        {
          "title": "Green",
          "value": "2"
        },
        {
          "title": "Blue",
          "value": "3"
        }
      ]
    }
    ],
    "msteams": {
      "width": "Full"
    },
    "actions": [
      {
        "type": "Action.Submit",
        "title": "Submit"
      }
    ]
  }
```

![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/62237649/369d8b0b-55f1-4f5b-b8d1-81de1df67bbb)

then on submitting after choosing any option got expected result.
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/62237649/1f449756-e54e-45e6-942c-523f798e7e6d)

Power Automate Flow:
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/62237649/b391c0f0-61d1-4f89-a243-82f8c8822d49)

**Comment by Prasad-MSFT** [comment]
**Update:**

We observed that this works fine in Teams web client, while in Teams Desktop client its not working as expected (nothing happens after we click the Submit button in the adaptive card)
![image](https://github.com/OfficeDev/microsoft-teams-library-js/assets/62237649/399e9d84-5b30-4b68-8cbf-1f337b09d01b)


Tested in:
```
You have Microsoft Teams version 24128.3300.2862.7357.
The client version is 49/24050722600.
```

We have raised a bug for the same. We will inform you once we get any further update from engineering team. 

Thanks!

**Comment by claudiu-mera** [comment]
@Prasad-MSFT, thank you. Unfortunately, the issue reproduces both on web client **and** desktop app.

web client version: v2

desktop client: 
teams version 24102.2219.2860.2337
client version 49/24041122313

**Comment by DerekCFI** [comment]
I'm having the same issue.

**Comment by Prasad-MSFT** [comment]
We are following up with engineering team about this issue. We will update this thread once we hear from them. Thanks!

**Comment by Prasad-MSFT** [comment]
Hi @claudiu-mera , @DerekCFI - this issue seems to be fixed now.
![image](https://github.com/user-attachments/assets/e5b59550-84be-4899-8ec1-5926aa393545)

We checked both in MS Teams Desktop `(Microsoft Teams version 24215.1005.3072.3011. The client version is 49/24080212008.) `and Web client and it works.
