### ISSUE TITLE
Documentation ThirdPartyCloudStorage

### ISSUE THREAD

**Issue by usselite** [OfficeDev/microsoft-teams-library-js#2325]
Hi, 

We have interest in integrating deeper within MS Teams, the ThirdPartyCloudStorage API seems applicable, however, it is kind of unclear what the requirements are in order to use it. Is this part of the Cloud Storage Partner Program? If so, or if it's not, could it be clarrified? 

Referring to this:
https://github.com/OfficeDev/microsoft-teams-library-js/blob/3d3f2cc82ec1b2df5562bbad9d7a68242c8fbcf7/packages/teams-js/src/public/thirdPartyCloudStorage.ts

Thanks,

**Comment by jekloudaMSFT** [comment]
Hi @usselite, thanks for reporting this; I'll look into improving the documentation around ThirdPartyCloudStorage. Could you tell me more about the scenario you're looking to implement with the ThirdPartyCloudStorage APIs?

**Comment by usselite** [comment]
Hi @jekloudaMSFT, I was mostly interested in the drag and drop scenario (https://github.com/OfficeDev/microsoft-teams-library-js/pull/1903), so we can implement our own cloud solution other than Onedrive for example. 

What makes it confusing, for being able to use functionalities, is it required to be enroled in the CSP program (https://developer.microsoft.com/en-us/office/cloud-storage-partner-program)? Because right now, the only information that can be found about 'third party cloud' providers, is the list here: https://techcommunity.microsoft.com/t5/microsoft-teams-blog/microsoft-teams-adds-third-party-file-integration/ba-p/80880 and it looks as these are enroled into the CSP program, but it's not clearly stated on the site that Teams is also part of the program.

Thanks,

**Comment by jekloudaMSFT** [comment]
Hey @usselite, it looks like this API is unrelated to the Cloud Storage Partner Program. I asked the dev who worked on this for more information, and this is what they said:

When a user drags and drops files in the compose box, the files are stored in OneDrive. We can also enable the user to send files to other third-party storage providers.

---

##Prerequisites
Admins must configure the third-party cloud storage provider's App ID
[Admin settings for file drag-drop to third-party storage - Microsoft Teams | Microsoft Learn](https://review.learn.microsoft.com/en-us/MicrosoftTeams/admin-settings-for-file-drag-drop-to-third-party-storage?branch=pr-en-us-14488)
Note to use this "NativeFileEntryPoints" should be disabled" : [Turn off Teams Native File Upload policy - Microsoft Teams | Microsoft Learn](https://review.learn.microsoft.com/en-us/microsoftteams/turn-off-teams-native-file-upload-policy?branch=pr-en-us-14488)
 
##For Cloud Storage Providers
If you are a cloud storage provider and want to support this feature, you will use the API to handle files dragged and dropped by users so that they are uploaded to your cloud storage.
 
From applicationContext they will get the value of Thread id and ReplyToId.
 
They need to concatenate above two values to get unique id / cache id like below:
`const uniqueIdForChats = replyChainIdforChats + inputthreadId;`
 
Send this id along with the callback, and they will receive the files which were drageddroped in compose.
<img width="1357" alt="drag_and_drop" src="https://github.com/OfficeDev/microsoft-teams-library-js/assets/93734408/87a97235-3eea-4653-9f9e-9672dd1aaf7e">

 
Note: "commandContext":"thirdParty" This will help the Third Party App to identify that their app was opened programmatically and they have to call the Teams SDK API for the dropped files.

---

Does this help?

**Comment by usselite** [comment]
Hi @jekloudaMSFT thanks for asking the dev! 

The both links you provided redirect to "review.learn.microsoft.com", I don't think I can access those pages?

There's no public versions:  https://review.learn.microsoft.com/en-us/MicrosoftTeams/admin-settings-for-file-drag-drop-to-third-party-storage?branch=pr-en-us-14488

There does seem to be a public article about turn off teams native upload policy, is it alike: https://learn.microsoft.com/en-us/microsoftteams/turn-off-teams-native-file-upload-policy?branch=pr-en-us-14488, but not sure if the articles are alike?

**Comment by jekloudaMSFT** [comment]
My apologies, it looks like those sites are only accessible internally at the moment. I've followed up asking for public documentation and will report here when I hear back

**Comment by jekloudaMSFT** [comment]
Thank you for your patience! The docs should be available now here:
https://learn.microsoft.com/en-us/microsoftteams/admin-settings-for-file-drag-drop-to-third-party-storage
https://learn.microsoft.com/en-us/microsoftteams/turn-off-teams-native-file-upload-policy

**Comment by mahimaMSFT** [comment]
I was oof for some time, is there anything I can help with?

**Comment by usselite** [comment]
Hi @jekloudaMSFT  and @mahimaMSFT,

I could use some support with how to determine the right manifest usage for this.
```
 "composeExtensions": [
        {
            "botId": "xxx",
            "canUpdateConfiguration": false,
            "commands": [
                {
                    "id": "Upload",
                    "description": "Drag and drop",
                    "title": "Drag and drop",
                    "type": "action",
                    "fetchTask": true,
                    "context": [
                        "thirdParty"
                    ]
                },
                {
                    "id": "settings",
                    "description": "Modify the plugin settings",
                    "title": "Settings",
                    "type": "action",
                    "fetchTask": true,
                    "context": [
                        "compose"
                    ]
                }
            ]
        }
    ],
```

or more like 
```
....
{
                    "id": "Upload",
                    "description": "Drag and drop",
                    "title": "Drag and drop",
                    "type": "action",
                    "fetchTask": true,
                    "commandContext": [
                        "thirdParty"
                    ]
                }
```

Thanks,

**Comment by usselite** [comment]
Hi @jekloudaMSFT , @mahimaMSFT, 

Provided with the answer from @Prasad-MSFT, we're not getting the manifest to validate. The manifest we used would be as summed above: 

```
 "composeExtensions": [
        {
            "botId": "xxx",
            "canUpdateConfiguration": false,
            "commands": [
                {
                    "id": "Upload",
                    "description": "Drag and drop",
                    "title": "Drag and drop",
                    "type": "action",
                    "fetchTask": true,
                    "context": [
                        "thirdParty"
                    ]
                },
                {
                    "id": "settings",
                    "description": "Modify the plugin settings",
                    "title": "Settings",
                    "type": "action",
                    "fetchTask": true,
                    "context": [
                        "compose"
                    ]
                }
            ]
        }
    ],
```

Would it be possible to get the manifest example from you instead and possibly small code snippets to integrate it within the code?

Thanks,

**Comment by Prasad-MSFT** [comment]
Hi @usselite - Apologies! We are checking this with engineering team. We will update this thread once we get any further info. Thanks!

**Comment by usselite** [comment]
@Prasad-MSFT @mahimaMSFT any update?

**Comment by Prasad-MSFT** [comment]
@usselite - We got below response from engineering team:
"Manifest file is specific to the app. We only require that upload action should be the first action on it.
Suppose if there are 2 actions that an app supports (View and Upload). It this case upload should be confirmed before View in Manifest."
 
This API is used for below requirement:
When a user drags and drops files in the compose box, the files are stored in OneDrive. We can also enable the user to send files to other third-party storage providers.
If you are a cloud storage provider and want to support this feature, you will use the API to handle files dragged and dropped by users so that they are uploaded to your cloud storage.

**Comment by usselite** [comment]
Hi @Prasad-MSFT please provide a sample of the manifest file that we should use in order to trigger this.

**Comment by Prasad-MSFT** [comment]
Attaching a sample manifest file:

[manifest 1.json](https://github.com/user-attachments/files/16159697/manifest.1.json)

**Comment by usselite** [comment]
@Prasad-MSFT for my own understanding, there's no mention of `"commandContext":"thirdParty" ` is this correct? Your colleague @jekloudaMSFT mentioned it's needed?

**Comment by Prasad-MSFT** [comment]
Hi @usselite, apologies. We understand the concern. We are checking this with engineering team internally and will get back to you.

**Comment by usselite** [comment]
@Prasad-MSFT any update?

**Comment by Wajeed-msft** [comment]
@usselite - [ThirdPartyCloudStorage](https://github.com/OfficeDev/microsoft-teams-library-js/blob/3d3f2cc82ec1b2df5562bbad9d7a68242c8fbcf7/packages/teams-js/src/public/thirdPartyCloudStorage.ts#L19) is beta API which is not yet documented, we will share the details steps for you to follow in order implement this functionality soon. We will also work on updating Dev Docs to include same steps for other developers to follow.

**Comment by usselite** [comment]
@Wajeed-msft Do you have a timeline for this? Because there is limited documentation right now, looks like we're missing a part only at this moment.  https://learn.microsoft.com/en-us/microsoftteams/admin-settings-for-file-drag-drop-to-third-party-storage#documentation-for-developers-third-party-storage-apps

**Comment by Prasad-MSFT** [comment]
> @Prasad-MSFT for my own understanding, there's no mention of `"commandContext":"thirdParty" ` is this correct? Your colleague @jekloudaMSFT mentioned it's needed?

Regarding doubts on: `"commandContext":"thirdParty"`
 
This value will be present in the payload of application context:
![image](https://github.com/user-attachments/assets/07f01325-81d6-4bea-b143-d489ec9fccda)

This will help the Third-Party App to identify that their app was opened programmatically, and they have to call the Teams SDK API for the dropped files.

**Comment by usselite** [comment]
@Prasad-MSFT, thanks will take a look at it.

**Comment by Prasad-MSFT** [comment]
User drags and drops the file in teams compose box ---> it will auto open the app 
(Refer prerequisites to configure your app to open programmatically)
https://learn.microsoft.com/en-us/microsoftteams/admin-settings-for-file-drag-drop-to-third-party-storage#documentation-for-developers-third-party-storage-apps

When you click on submit, in network tab (dev tools) we can see we are sending a payload with some information.
![image](https://github.com/user-attachments/assets/5958c38d-646b-47a5-bd06-84462026f4d3)
This payload we are getting in our app's application context (refer below code)
![image](https://github.com/user-attachments/assets/23db4b79-2484-435d-a8f3-47f3fb6ed11f)
![image](https://github.com/user-attachments/assets/f408b846-eb6f-43fb-b935-64835a7ce62d)

From above payload we will need 2 values:

- Thread id
- ReplyToId

We need to concatenate above two values to get unique id / cache id like below:
`const uniqueIdForChats = replyChainIdforChats + inputthreadId;`
 
Send this id along with the callback as defined in below code reference.
![image](https://github.com/user-attachments/assets/1b98838d-05c5-4c30-9b2f-0e60763fe42b)

**Comment by usselite** [comment]
Hi @Prasad-MSFT the 1st image is not read-able (low-res).

**Comment by Prasad-MSFT** [comment]
> Hi @Prasad-MSFT the 1st image is not read-able (low-res).

Updated images.

**Comment by usselite** [comment]
@Prasad-MSFT would it be possible to show us the manifest you use?

**Comment by Prasad-MSFT** [comment]
> Attaching a sample manifest file:
> 
> [manifest 1.json](https://github.com/user-attachments/files/16159697/manifest.1.json)

FYI @usselite

**Comment by Prasad-MSFT** [comment]
Hi @usselite, could you please share the Teams app name you own?

**Comment by usselite** [comment]
Hi @Prasad-MSFT we haven't had the time to dive deeper into it so far. But it looks like the manifest you shared (31st july) is the same one from the 10th of july. With that manifest we we're not able to get the trigger going, so we're not entirely sure what we're doing wrong. 

Do we need something specific in the manifest at all? 

Our app name is 'Sendent', however, it's not available in the app-source due the way how our solution run by customers.

**Comment by mahimaMSFT** [comment]
Hi,
Could you please help me to understand how is your app integrated with teams?
Are you able to open your app using the "+" icon in the compose box, and upload files from there?
I am happy to connect over a call and discuss all the doubts.

**Comment by usselite** [comment]
Hi @mahimaMSFT what is the best way to connect with you to schedule a call? We're situated in the Amsterdam Timezone.

We tried the '+' icon for a manual upload, but it didn't work unfortunately.

**Comment by Prasad-MSFT** [comment]
@usselite , could you please send email to microsoftteamsdev@microsoft.com ?

**Comment by usselite** [comment]
Hi @Prasad-MSFT the issue is still being investigated

**Comment by usselite** [comment]
The issue has been solved. The problem was we'd have to use the literal app-id. This is not the ID from the manifest (or external app id). It's the id you get after your app has been uploaded to teams admin center.
