### ISSUE TITLE
microsoftTeams.authentication.getAuthToken() doesn't work for task modules in teams v2

### ISSUE THREAD

**Issue by vhensorskyi** [OfficeDev/microsoft-teams-library-js#2340]
Hi folks,

Whenever I try to execute `microsoftTeams.authentication.getAuthToken()` for task modules when consent isn't approved the function doesn't throw a consent error, like resourceRequiresConsent. It constantly fails with `Get Auth token error`. Moreover, the function doesn't refresh a token once the consent gets approved. A user needs to sign out from MS Teams Client and login again to populate a new valid token. Both issues started happening on the v2 MS Teams, anything was working fine on the v1. Could you please investigate this, since many users are affected by this?

Best regards,
Volodymyr

**Comment by Nivedipa-MSFT** [comment]
@vhensorskyi - Thanks for reporting your issue. We will test this and update you soon.

**Comment by Nivedipa-MSFT** [comment]
@vhensorskyi - We are still checking this with the engineering team, we will let you know once we get any updates from them.

**Comment by Nivedipa-MSFT** [comment]
@vhensorskyi - There is an already bug raised for this issue. We will let you know once we get any updates on it.

**Comment by vbatr** [comment]
Hi @Nivedipa-MSFT 

I there any ETA for resolving this issue? 
We have the same problem while calling microsoftTeams.authentication.getAuthToken({ silent: true }) in our app. Without silent parameter SSO consent popup is not shown on within task module. 

Regards, 
Volodymyr B.

**Comment by mparfianowicz** [comment]
Hi!

This is a blocker for implementing Tab SSO for the official [Microsoft Teams - Atlassian Jira Data Center](https://marketplace.atlassian.com/apps/1217836/microsoft-teams-for-jira-data-center) integration. It would be really great to have this bug resolve as soon as possible.

Kind regards
Marek Parfianowicz
Principal Engineer
Atlassian

**Comment by tanimcseku** [comment]
Hi @Nivedipa-MSFT , any update on this?

**Comment by Nivedipa-MSFT** [comment]
@tanimcseku - We are checking the status of the bug with the engineering team, we will let you know once we get any updates from them.

**Comment by tanimcseku** [comment]
Hi @Nivedipa-MSFT , any updates?

**Comment by Nivedipa-MSFT** [comment]
@vhensorskyi, @vbatr, @tanimcseku, @mparfianowicz - We received an update from the engineering team stating that the bug has been fixed. Could you please check and let us know if it is working for you? 
If you are still experiencing this issue, please provide a minimal app that can reproduce the problem along with the Teams Client logs:
https://learn.microsoft.com/en-us/microsoftteams/log-files#log-collection

**Comment by dmcweeney** [comment]
Is this fix related to #2445 ?
