### ISSUE TITLE
RSC Teams app starts to throw error for Graph calls

### ISSUE THREAD

**Issue by tobiasviehweger** [OfficeDev/microsoft-teams-library-js#2341]
While not directly related to the Javscript SDK, we are using RSC permissions in our Teams app and started to have issues with it in the last few weeks. For no reason we can see, Graph started throwing the following

`Missing role permissions on the request. API requires one of 'TeamMember.Read.All, TeamMember.ReadWrite.All, Group.Read.All, Group.ReadWrite.All, TeamMember.Read.Group, Member.Read.Group'. Roles on the request 'Group.Selected'`

This was fixed for one of our customers by just re-installing the Teams app, but it's not clear why this suddenly starts to fail - might this be related to the migration from group owner consent to team owner consent on MS side?

Example request ids:

2024-05-27T13:57:34    request-id: 05b95254-9e7c-46d3-a7a1-a0c05108e714
2024-05-27T08:59:50     request-id: d315b5a6-60e8-45a3-8753-53e6c9d8e0fe
2024-05-27T10:54:36     request-id: 70dff19c-02fa-4680-9243-0bb69dc3b906

(we have a lot more in case this is required)

Any idea why this might start happening?

**Comment by Meghana-MSFT** [comment]
Thank you for reporting this, we will check this and get back to you.

**Comment by tobiasviehweger** [comment]
Hi @Meghana-MSFT,
no unfortunately we have observed this in different tenants.. By service principal you are referring to the Enterprise application located in the webApplication part of the manifest correct? We are using the same enterprise application also for delegated authorization and these seem to be still working - so my understanding would be that the service principal has not been deleted...

**Comment by Meghana-MSFT** [comment]
@tobiasviehweger - Engineering team has looked into logs and said that User with object ID 3c8ef21a-XXXX-XXXX-XXXX-XXXXXXXXXXXX revoked resource specific consents at 2:35 PM UTC on May 28. A different user granted RSC permissions a few minutes later.

**Comment by tobiasviehweger** [comment]
Hi @Meghana-MSFT thanks for checking, though that sounds like when the customer tried uninstalling/re-installing to fix the issue. Let me cross check out logs I'll get back soon

**Comment by Meghana-MSFT** [comment]
@LeonYasoon - Engineering team has looked into the logs and said that the two traces provided above are in different tenants:
GET teams/id/members was invoked for tenant 7eb71b7c-ca4b-470d-XXXX-XXXXXXXXXXXX
 
while GET permissions grants was invoked for tenant c1a5a59d-592c-49a2-XXXX-XXXXXXXXXXXX.

**Comment by LeonYasoon** [comment]
@Meghana-MSFT 
Thanks for the investigation. We were able to find out that the affected customer had done a tenant migration, leaving behind ambigous traces in our systems. Feel free to close this issue.

**Comment by Meghana-MSFT** [comment]
Thank you for confirming. We are closing this issue, please feel free to reach out to us if you have further queries. kindly share your valuable feedback on [feedback on your experience with our support team and Platform](https://aka.ms/DevSupportFeedback).

**Comment by LeonYasoon** [comment]
Hi @Meghana-MSFT sorry for reopening this issue, but we have found another case that results in the same symptoms as before.

In tenant with id 19963573-6f6f-4cd6-9837-XXXXXXXXXXXX the app 89d5ca9f-d63b-4885-bd30-6e7433c1540c in team 543c85fe-3889-44af-94a9-XXXXXXXXXXXX was revoked RSC permissions on 6/11/2024, 4:51:40 PM. 

The correlation id for this revoke transaction is cd0fda2d-1ff0-402c-9462-a87186a533b4 and from the azure portal audit log it looks like this:

![Screenshot 2024-06-26 at 15 53 25](https://github.com/OfficeDev/microsoft-teams-library-js/assets/71631027/6949cd94-9865-46d2-aab2-417daf2f5ba9)

There is another transaction with the exact same timestamp which was "Update group" for that same team with the same correlation id which changed the group type to "Unified".

The "Display Name" of the actor is "Microsoft Teams Graph Service". Could it be possible that this was some kind of migration which didnt complete successfully leaving the app without RSC permissions?

**Comment by Meghana-MSFT** [comment]
Hi @LeonYasoon - We will check this internally and get back to you.
