### ISSUE TITLE
GetContext: Error: SDK initialization timed out.

### ISSUE THREAD

**Issue by RichieMcCaff** [OfficeDev/microsoft-teams-library-js#2348]
Since the last msTeams update on May 20th our app has started timing out on the GetContext call with the error `Error: SDK initialization timed out.`. This is only occurring on mobile devices (both iOS and Android). 

The app we have is using teamsJs to interact with msTeams from an iFrame and in this particular failure we are using context to get  the theme and the current subpageId to use in a deeplink as part of the redirect when logging the user in.

We initially thought there was an issue with `app.initialize()` but it's actually timing out when trying to retrieve the context.
Weirdly if we refresh the page on it's first attempt at accessing the context the next time it tries it will access it successfully.

I haven't discovered any way to programmatically retry get the context, I've tried a retry loop that tries accessing it a few times on an interval of 2 seconds with no luck.

The only solution I have to workaround this is to refresh the entire page with `window.location.reload()`.

I've tried pulling as much information out of the error it drops but it doesn't give me anything past `Error: SDK initialization timed out.`, most of the time the getContext function will not return the promise at all and just sits there.

Is this something youse are aware of? I see a couple recent posts that seem similar but only mention the initialize failing.

**Comment by Dinesh-MSFT** [comment]
Hi @RichieMcCaff - Thanks for raising the query.
We will look into it and let you know the updates.

**Comment by AE-MS** [comment]
I believe @KangxuanYe replied to you on the other issue but he is helping look into the problem.

**Comment by KangxuanYe** [comment]
Hi @RichieMcCaff, just here for letting you know that we are still investigating this issue internally and we have some problems on setting environment for devices (both virtual and real). We will get back to you soon and thanks for your patience.

**Comment by RichieMcCaff** [comment]
@KangxuanYe
