### ISSUE TITLE
`microsoftTeams.app.openLink` redirects to the wrong chat conversation after correctly redirecting to the chat conversation.

### ISSUE THREAD

**Issue by tiennguyen1293** [OfficeDev/microsoft-teams-library-js#2362]
It seems that the Teams App Desktop has recently updated something causing the Chat Tab to redirect to the previously selected chat conversation. 

However, with the microsoftTeams.app.openLink function, the behavior is incorrect. After I trigger openLink, I am redirected to the chat conversation I want, but then it redirects back to the previously selected chat room.

Expected:

- Redirect to the chat conversation specified when openLink is triggered.

P/s: Working on Teams Android And Teams iOS.

Versions:

`"@microsoft/teams-js": "^2.21.0"`

```
Teams Desktop App: 
You have Microsoft Teams version 24091.212.2846.1453.
You've got the latest version. It was last checked on 5/13/2024.
The client version is 50/24050307617.
```

**Comment by Dinesh-MSFT** [comment]
Hi @tiennguyen1293 - Thanks for raising the query.
We will look into it and let you know the updates.

**Comment by Dinesh-MSFT** [comment]
Hi @tiennguyen1293,
We have tried to repro this issue with 'https://teams.microsoft.com/l/chat/19:26531ed8-42bb-4bd0-a14f-0290df84650d_7d0ecdd8-82dd-44bd-9b10-043545eb1aae@unq.gbl.spaces/conversations' deep link. It is working fine. To help you better could please provide more details for further assistance. So, we will look into it and let you know the updates.

**Comment by Dinesh-MSFT** [comment]
Hi @tiennguyen1293,
Could please try to update your Teams and check once. if you still face the issue, we will raise the bug.
