### ISSUE TITLE
Perform action before user change tabs from custom app

### ISSUE THREAD

**Issue by ojuliocode** [OfficeDev/microsoft-teams-library-js#2378]
Issue description: the application I'm working on is an app tab. Every time the user tries to leave this app tab, I want to execute a function calld unload(), which is the callback function for `msTeams.teamsCore.registerBeforeUnloadHandler()`. 

The action I want to perform is to Undock the application, aka, the action that is performed when user clicks this button 

![undock](https://github.com/OfficeDev/microsoft-teams-library-js/assets/149907954/75269fa5-8690-4e14-8cca-206f76aea24a)

But I have no idea which function to use. I took a look at msTeams.stageView.open(), but I don't think that is the solution. Is there an API way to open the tab in a new window? 

If that's not possible, is it possible to notify the user he needs do undock before the tab unload? Like: if user goes away, then notify him he needs to undock?

At last, I used msTeams.authentication.authenticate() to the url of the app. But the thing is: the newly opened window does not share the devices permissions i have in the normal app tab. I need to use microphone, but the permissions kind of reset. How to overcome this?

Thanks in advance

(Edit: if stageView.open() is the solution, how do I get the threadId? in your documentation it is saying that threadId is optional, but it is actually needed in the sdk)

**Comment by erinha** [comment]
Thanks for your post @ojuliocode! 

I'd love to get more info about the scenario you're trying to enable. It sounds like you're trying to have the app open itself in a new host (e.g., Teams) window when the user starts to navigate away from it. We'd want to make sure we weren't overriding the user's action to leave or quit an application, but more info would be super helpful. I presume that opening your app in a new browser window (via `window.open`) does not achieve your goal?

Additionally, what platform and host (i.e., Teams, Outlook, microsoft365.com, etc.) are involved in your scenario? 

Regarding your question about `threadId` for `stageView.open()`, I have opened a documentation bug to get [this article](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/open-content-in-stageview?tabs=withchat#invoke-from-stageview-api) updated and reflect that `threadId` is required.

**Comment by vikramtha** [comment]
Hey @ojuliocode,

It seems like this scenario you would like to enable goes against what the user's intention would be. If I am understanding correctly, having the app pop-out and remain open even if the user tries to navigate away wouldn't be in line with how we allow apps to function in Teams. However, yes you could use the stageView API to pop-out the application by specifying the[ stageView open param to popout.](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/stageview.stageviewopenmode?view=msteams-client-js-latest)

**Comment by vikramtha** [comment]
@ojuliocode Unfortunately no that is also not possible at the moment.
