### ISSUE TITLE
Open Teams from WebUrl

### ISSUE THREAD

**Issue by andreatosato** [OfficeDev/microsoft-teams-library-js#241]
I would like to open an existing Teams with the WebURL.
Is there a method?
I tried redirecting, but it doesn't work, it shows me the web page asking me if I want to use Teams via Web or App.

**Comment by Wajeed-msft** [comment]
If you want to open any deeplink from a tab then you can use `microsoftTeams.executeDeepLink(/*deepLink*/);`

Here is are the docs for [Deep linking from your tab](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deep-links#deep-linking-from-your-tab)

**Comment by andreatosato** [comment]
I change my code with microsoftTeams.executeDeepLink(/*deepLink*/) but this is result:
![image](https://user-images.githubusercontent.com/24985956/60729182-6143c500-9f42-11e9-97aa-f38bcc7c9246.png)
I want to open Team, not redirect to.

**Comment by andreatosato** [comment]
I didn't see any response to the issue, maybe I was unclear about the request. I explain to you better what I would like to do.
I have an application that creates a new Teams (Static Tab application). Once the new Teams have been created, I would like the user to view the team. In a nutshell, I would like your application to be redirected to the team automatically, without going through the page that asks you if you want to use the application or browser.
When a new Teams is created, its WebUrl is also returned, so I would like that starting from this URL, the application would go into "Team" mode and select the "General" channel of the Team, all inside the application itself.

**Comment by Wajeed-msft** [comment]
@andreatosato: This should work fine. Could you please try this sample code?

```
<p>
    <button onclick="navigate();">Navigate To Team</button>
</p>

<script src="https://statics.teams.microsoft.com/sdk/v1.4.2/js/MicrosoftTeams.min.js" crossorigin="anonymous"></script>

<script>
    microsoftTeams.initialize();
    function navigate() {
        microsoftTeams.executeDeepLink("https://teams.microsoft.com/l/team/19:#ab5aef94bcf49#0a93c6eeaee3d59df%40thread.skype/conversations?groupId=63d#7b6e-ff#4-4579-88d2-4067156afad1&tenantId=#d9b645f-597b-41f#-a2a3-ef1#3fbd91bb");
    }

</script>
```

**Comment by andreatosato** [comment]
I used "@microsoft/teams-js": "^1.4.3" with same result.
After click in Teams, they redirect to Webpages e not in Teams Sections

**Comment by Wajeed-msft** [comment]
Could you please share your app to repro this or just the tab code?

**Comment by andreatosato** [comment]
url is read by Graph API for Teams

```js
redirectToTeam(url) {
    microsoftTeams.executeDeepLink(url);
}
```

**Comment by Wajeed-msft** [comment]
Could you please share you App Manifest which can be used to repro this?

**Comment by Gousia-MSFT** [comment]
@andreatosato Please reopen with your manifest if you are still facing any issues.

**Comment by andreatosato** [comment]
[CreatorTeam.zip](https://github.com/OfficeDev/microsoft-teams-library-js/files/4153660/CreatorTeam.zip)

This is my manifest, not work in 1.6.0 version.

**Comment by ydogandjiev** [comment]
Hey @andreatosato, I am having some trouble getting your app to run consistently in my test tenant. Can you help me understand how you are getting the team deep links? Have you tried just copying a deep link via the Teams UI and calling `microsoftTeams.executeDeepLink` with that? Do you see the same behavior?
![image](https://user-images.githubusercontent.com/3357245/73800170-c7105d80-476c-11ea-9120-a3f93e55ec03.png)

When I get a deep link to a Team from the Teams UI it looks something like this:
https://teams.microsoft.com/l/team/19%3a990cec08724643319ca61f397c02d752%40thread.skype/conversations?groupId=8020da73-87d8-4946-920f-94c326a23e1c&tenantId=378323fe-8860-4713-bdca-d3996d11b589

I have a test app which I typically use to exercise the Teams Client SDK:
https://github.com/ydogandjiev/microsoft-teams-test-tab/raw/master/package/test-tab.zip

When I call `executeDeepLink` using the URL mentioned above I see my client navigating without any issue (both web and desktop):
![image](https://user-images.githubusercontent.com/3357245/73800376-4d2ca400-476d-11ea-9b63-bd0849cbcae1.png)

Can you please give this a shot and let me know if you see any issues?

**Comment by andreatosato** [comment]
Thanks for reply @ydogandjiev 
Your app works but not fine.
DeepLink open Teams sections but not correct Teams selected.

My link:
Team with Paolo (simple name)
https://teams.microsoft.com/l/team/19:65213f8813a541f390d0b13b2c914831%40thread.skype/conversations?groupId=5054cead-8ee3-4fef-b0cb-39039f8eadcf&tenantId=97877fab-d3d2-4424-bbb9-2423276e5f58

Team with Daniele (simple name)
https://teams.microsoft.com/l/team/19:e7c57160eaff4a618cdbfae6bf455677%40thread.skype/conversations?groupId=8c6205e7-a32e-484a-9275-3ffacac56f57&tenantId=97877fab-d3d2-4424-bbb9-2423276e5f58


Teams links arrive from Microsoft Graph

**Comment by andreatosato** [comment]
Same behaviour. Open Teams tab but not correct Team!

```JS
import React, { Component } from 'react';
import ReactDOM from 'react-dom';
import App from './App';
import * as serviceWorker from './serviceWorker';
import { Provider, themes, Header } from '@stardust-ui/react'
import * as microsoftTeams from "@microsoft/teams-js";
import 'semantic-ui-css/semantic.min.css'
import './index.css';
import { Button} from '@stardust-ui/react';

class TestParent extends Component {
    constructor(props) {
        super(props);
    }

    componentDidMount() {
        try {
            microsoftTeams.initialize();
            microsoftTeams.appInitialization.notifyAppLoaded();
            microsoftTeams.getContext(async context => {
                microsoftTeams.appInitialization.notifySuccess();
            });
        } catch (err) {
            microsoftTeams.appInitialization.notifyFailure({ reason: microsoftTeams.appInitialization.FailedReason.Other, message: err.message });
        }
    }

    redirectToTeam() {
        var url = 'https://teams.microsoft.com/l/team/19:e7c57160eaff4a618cdbfae6bf455677%40thread.skype/conversations?groupId=8c6205e7-a32e-484a-9275-3ffacac56f57&tenantId=97877fab-d3d2-4424-bbb9-2423276e5f58';
        console.log(url);
        microsoftTeams.executeDeepLink(url);
        // WHY NOT THIS?
        //microsoftTeams.navigateToTab(new { tabName = "Teams", teamId =)
    }

    render() {
        return (
            <Provider theme={this.state.theme}>
                <Button primary content="Vai al Team" onClick={() => this.redirectToTeam()} />
            </Provider>
        );
    }
}
export default TestParent

ReactDOM.render(<TestParent></TestParent>, document.getElementById('root'));
```

**Comment by ydogandjiev** [comment]
Thanks @andreatosato, this definitely looks like a bug on our end. We've previously only validated that our `executeDeepLink` API works with the deep links listed in our public documentation here:
https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links

However, I think it's reasonable to expect that the API also work with other deep links like the ones you are trying to use. We will look into this issue on our end and get it fixed.

**Comment by Subhasish-msft** [comment]
@ydogandjiev, Is there any bug created for this? There is a similar issue [here](https://github.com/OfficeDev/microsoft-teams-library-js/issues/300)

**Comment by mdanielcristian** [comment]
This is still a bug on 1.10, any progress? Is there a bug opened for this? @ydogandjiev

**Comment by petecuttriss** [comment]
Hi, I've found the same issue... if we try and link through to the default Team link URL it doesn't work.  If we link through to the General channel it's fine.  Currently we are having to code around this issue when we hit a team link e.g. /l/team.

e.g. This doesn't work : https://teams.microsoft.com/l/team/19%3a6c5be939bb2c46aea593f81fdea36447%40thread.skype/conversations?groupId=9850f4dc-5db1-468e-b64f-f4f744fce1ee&tenantId=4d738f76-0c95-4304-b624-98fe0217f850

This does:
https://teams.microsoft.com/l/channel/19%3a6c5be939bb2c46aea593f81fdea36447%40thread.skype/General?groupId=9850f4dc-5db1-468e-b64f-f4f744fce1ee&tenantId=4d738f76-0c95-4304-b624-98fe0217f850

**Comment by jeryjpk** [comment]
> This is still a bug on 1.10, any progress? Is there a bug opened for this? @ydogandjiev

Is it resolved , If yes can you walk me through the new way of implementing it ?
Thanks in advance

**Comment by ChetanSharma-msft** [comment]
Hello Everyone,
Hope you are doing well!!

Sorry for delay in responses.
We will check on the updates on this issue with engineering team and get back to you.
