### ISSUE TITLE
Deep Link to conversations tab not working in Teams v2

### ISSUE THREAD

**Issue by xSaNta123** [OfficeDev/microsoft-teams-library-js#2422]
I have a problem with deep links redirecting the user to the "Chat" tab of our application.
I'm using the 2.25.0 version of the [@microsoft/teams-js](https://www.npmjs.com/package/@microsoft/teams-js).

on Teams v1 this deep link (https://teams.microsoft.com/l/entity/<app_id>/conversations) worked without any issues
on Teams v2 it changes to the specified "Chat" tab, but the editor is not working. When accessing the "Chat" via the tab in the app, the editor works.

I'm getting this in the console after making the deep link call 
`either targetOrigin or target is invalid`

Tried using:
import { app, pages } from "@microsoft/teams-js";
pages.currentApp.navigateTo({ pageId: "conversations" });
pages.navigateToApp({ appId: <app_id>, pageId: "conversations" });
and also
app.openLink("https://teams.microsoft.com/l/entity/<app_id>/conversations");

all with the same results.
![Screenshot 2024-07-24 at 09 19 57](https://github.com/user-attachments/assets/12d70ce3-4d96-4f09-a14e-f90f6824d661)
![Screenshot 2024-07-24 at 09 32 20](https://github.com/user-attachments/assets/125a85ff-4ffd-45d0-b266-bcbcb854ef9d)

Tested in multiple browsers 
- Chrome (Client version: 1415/24061318413) 
- Firefox (Client version: 1415/24061318413)

And in Teams 
- 24165.1406.2974.9471
- Client version: 50/24061318413)

**Comment by Prasad-MSFT** [comment]
Thanks for raising your issue. We will check this at our end and will update you accordingly.

**Comment by Prasad-MSFT** [comment]
@xSaNta123 , thanks for confirming. We will check this at our end and will update you.

**Comment by Prasad-MSFT** [comment]
@xSaNta123, we tried to repro this issue by uploading an app to org catalog and observed that using below deep link it is navigating us to that particular app chat tab.
`microsoftTeams.app.openLink("https://teams.microsoft.com/l/entity/<appId>/conversations?tenantId=<tenantId>");`
or 
`microsoftTeams.app.openLink("https://teams.microsoft.com/l/entity/<appId>/conversations");`


Also, by manually copy/pasting the deep link url and clicking on that it redirects to appropriate chat tab.

Tested in Teams web client and Teams desktop client both.
`We have Microsoft Teams version 24165.1414.2987.41. The client version is 49/24053101421.`

**Comment by SwenRanj** [comment]
We are having the exact same issue with @microsoft/teams-js v2.23.0. Both in the client, browser and on multiple devices.
Also tried all of the methods that @xSaNta123 mentions. A few weeks ago we didn't have this problem.

**Comment by xSaNta123** [comment]
@Prasad-MSFT ok, so this just confirms that on the older version of the client `49/24053101421` the deep link works. Tested it again now on my setup `50/24061318413`, still with the same outcome. Can you perhaps try to update your client to this version and try again ?

**Comment by SwenRanj** [comment]
@xSaNta123 @Prasad-MSFT 
I am getting this issue on:
* MS Teams version: 24180.205.2980.1757
* Client version: 49/24062724814.
* Last update check: 26-7-2024.

**Comment by SwenRanj** [comment]
> @SwenRanj , we tried to repro this using both @microsoft/teams-js v2.23.0 and @microsoft/teams-js v2.25.0, however it works with both. We are able to navigate to proper app chat tab using the deep link.

@Prasad-MSFT  Just to clarify, we also get directed properly to the chat tab. However the inputfield for the user message is showing an error ("Oops, something happened with the editor"). Our users cannot response in the chat because of this.

**Comment by Prasad-MSFT** [comment]
This is right repo to post your queries. It  is within the scope of the JS library.
FYI, the input field is not showing any error in our case.
![image](https://github.com/user-attachments/assets/2ddbfada-908c-4cbe-a2ca-9e0a56589c05)

Lets wait for @xSaNta123's response and if it is the same issue, then we can raise a bug from our end and assign to engineering team for further investigation. Thanks!

**Comment by xSaNta123** [comment]
Hey @Prasad-MSFT, sorry for a late reply I was out of office on vacation. The issue here is with the input field not working when redirected via deep link. Redirection to the "Chat" tab is working without a problem, but it is "unusable" as the editor is showing 
"Oops, something happened with the editor"
![Screenshot 2024-08-05 at 11 03 04](https://github.com/user-attachments/assets/484eeac2-5450-4884-9d38-f083ffeb5fcb)

**Comment by Nivedipa-MSFT** [comment]
@xSaNta123 - There is an already bug raised for this. Engineering team is working on it. We will let you know once we get any updates on it.
