### ISSUE TITLE
Tab provisioned via API is missing key context fields. 

### ISSUE THREAD

**Issue by AmonHouston** [OfficeDev/microsoft-teams-library-js#243]
I've created a Microsoft Team with a custom tab using the `https://graph.microsoft.com/beta/teamsTemplates('standard')` api call. 

When I go to that tab, and console.log out the context it's missing values in the following variables:

- channelRelativeUrl
- chatId
- entityId
- teamSiteDomain
- teamSitePath

And it's completely missing the teamSiteUrl field. 

I also have this custom Teams tab app installed manually via the App Studio, and the console.log context that provides gives all the above fields with the correct information. 

Below is my JSON package i'm sending to the API.

```
{
            "template@odata.bind": "https://graph.microsoft.com/beta/teamsTemplates('standard')",
            "displayName": teamName
            "description": description,
            "owners@odata.bind": [
                `https://graph.microsoft.com/beta/users('${ownerID}')`
            ],
            "installedApps": [
                {
                    "teamsApp@odata.bind": `https://graph.microsoft.com/v1.0/appCatalogs/teamsApps('${appID}')`
                }
            ],
            "channels":[
                {
                    "displayName":"Custom channel",
                    "isFavoriteByDefault":true,
                    "tabs":[
                        {
                            "teamsApp@odata.bind": `https://graph.microsoft.com/v1.0/appCatalogs/teamsApps('${appID}')`,
                            "name": "Custom app",
                            "configuration": {
                                "contentUrl": `https://${Constants.hostname}/auth/end.html`
                            }
                        }
                    ]
                }
            ]
        }
```

**Comment by AmonHouston** [comment]
Updating to 1.4.3 has gotten the teamSiteUrl field to show on the provisioned tab now. However it is still empty. 

Here is a screenshot of what is logged 
![image](https://user-images.githubusercontent.com/34081746/60853577-c7855c00-a250-11e9-9322-1a9e0bdb1da3.png)

**Comment by AmonHouston** [comment]
After a bit further research, it seems that the the teamSiteUrl in the context object is only available **after** the user navigates to the file (SharePoint) tab and back.  If the navigate directly to the custom tab first, it throws an error message which makes this field less than ideal and somewhat unreliable.

**Comment by Abhijit-MSFT** [comment]
Currently, there is no way to know when SharePoint provisioning is completed. We have raised request to update documentation for this on https://github.com/microsoftgraph/microsoft-graph-docs/issues/4970.

Ref: - https://github.com/MicrosoftDocs/msteams-docs/issues/752
