### ISSUE TITLE
Unappealing frame is shown around all channel/chat apps since July 28th 2024

### ISSUE THREAD

**Issue by sebiJo** [OfficeDev/microsoft-teams-library-js#2434]
Since July 28th, an ugly frame is shown around all apps in channels and chats. The frame even appears clickable but clicking it doesn't do anything. Has this frame been introduced by intention or is this a bug?

This seems to appear on all platforms (Mac, Windows, Web). Is there any way to avoid the frame or assign a custom color to the frame? It really doesn't look nice and it consumes valuable pixels on small screens.

![Bildschirmfoto 2024-07-29 um 15 27 01](https://github.com/user-attachments/assets/cf636f78-4465-4082-80b2-370ba7c73608)

**Comment by jker-org** [comment]
Same here. We are using the standard fluent ui grey as background for our static app and chat / group app. For static app, everything is fine. For chat / group app, we have this clickable white border. In our opinion this does break with the design patterns of all the apps. Please provide the possibility to deactivate this border for our apps.

**Comment by supermarkd** [comment]
Noticed the same. Please disable this ugly frame since it distracts users from the main content. The frame is also clickable. What is the intention? Probably a bug?!

**Comment by sebiJo** [comment]
The entire App-iFrame is now placed within a huge clickable button, which causes the white frame:
![iframe in button](https://github.com/user-attachments/assets/2c6de3d2-d7e7-4df2-8616-1b203730c332)

**Comment by sayali-MSFT** [comment]
Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by sebiJo** [comment]
Update:
The issue seems to be (almost) fixed in "Public Preview" (Client Version 50/24071128815) while the issue is reproducible in the main version (Client version 50/24062724814).

Minor bug: Even in the public preview version, all apps are displayed within a huge button which causes rounded corners and an additional solid border around the app frame. Since this bug was introduced, the apps do not appear as perfectly integrated anymore, so I would suggest to remove the button or at least remove the border style of the button.

**Comment by sayali-MSFT** [comment]
@sebiJo -We are able to repro the scenario, we will inform the engineering team and let you know the update once we have any.

**Comment by sayali-MSFT** [comment]
@sebiJo - The issue has been fixed internally. We will let you know once it is publicly released.

**Comment by sebiJo** [comment]
I can confirm that the frame has gone in version  24231.507.3099.9636
Thanks a lot!

**Comment by sayali-MSFT** [comment]
@sebiJo -Could you please share your valuable feedback via [Microsoft Teams Developer Feedback link.](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u)
