### ISSUE TITLE
Authenticate popup is throwing SDK not initialised error

### ISSUE THREAD

**Issue by aniketrai** [OfficeDev/microsoft-teams-library-js#2440]
Hi,
I am doing the authentication based on documentation. 
The authenticate method opens a popup, we have a our custom login. Upon successful login, when triggered the notifysuccess is throwing SDK not initialised error. 

The js file from where we are calling authenticate is different that from where we are doing notifysuccess.

This works on Desktop app. but not on Web. We are facing this issue in Web version. 
While publishing our App, we also asked MS validation team, that if they faced this issue. They said never faced this.

**Comment by KangxuanYe** [comment]
Hi @aniketrai , thanks for reporting this issue for us. Before I ask some questions, I would like to repeat and summarize some of your info to make sure I fully get your situation.

It is to say that you have an app published (I think I might be wrong here) with everything working fine before and now you are having initialization timed out issue on your authentication flow inside of popup. And your app only has issue on web version.

Could you please say more about 

- what host you are running on? For example, Teams.
- What browser you are using for the app? For example, Edge, Chrome.
- What version of Teams-Js library are you using for your app? (What's the version before if you have made any change?)
- And sorry I do not understand what you said 'The js file from where we are calling authenticate is different that from where we are doing notifysuccess.' 

Also, to help us debugging, could you please send us logs with client debugging enabled. You can simply follow [instruction here](https://github.com/OfficeDev/microsoft-teams-library-js/wiki/TeamsJS-Logging#enabling-logging).

Thank you.

**Comment by aniketrai** [comment]
We have a script, config.js where we are calling` microsoftTeams.authentication.authenticate` and the URL which we are passing here loads a different script called Login.js. 
We are doing Third party authentication (via our own website). 
When login succeeds, the callback URL loads a new URL called OAuthCallBack.js, in which we are validating the claims and if pass, we are calling `microsoftTeams.authentication.notifySuccess `. Here we are getting the the error : SDK initialization timed out. 
I am also passing the valid domains and checking `microsoftTeams.app.isInitialized` before calling `microsoftTeams.app.initialize` in OAuthCallback.js.

**Comment by KangxuanYe** [comment]
> Thanks, I found this log interesting `teamsJs:app teamsjs is being used from https://res.cdn.office.net/teams-js/2.25.0/js/MicrosoftTeams.min.js. Today, teamsjs can only be used from a single script or you may see undefined behavior. This log line is used to help detect cases where teamsjs is loaded multiple times -- it is always written. The presence of the log itself does not indicate a multi-load situation, but multiples of these log lines will. If you would like to use teamjs from more than one script at the same time, please open an issue at https://github.com/OfficeDev/microsoft-teams-library-js/issues`
> 
> host - Windows Teams web browser - Edge Version - 2.25.0

Thank you for this reply. The piece of log you posted here doesn't indicate a multiple-load situation. I didn't see all logs from your side, but if you see that logs for multiple time, then it does indicate you are having Teams-JS library be loaded for multiple time. If so, please let us know if Teams-Js libraries are loaded multiple time by accident or you have a request for multiple load.

**Comment by KangxuanYe** [comment]
@aniketrai , based on your description, it seems like app is initialized. Would you mind providing your app's appID so that I can go to our telemetry database for double check? Thank you so much.
