### ISSUE TITLE
Sharing Sound with shareAppContentToStage

### ISSUE THREAD

**Issue by markitosha** [OfficeDev/microsoft-teams-library-js#2444]
Hi Team,

Is it possible to share presenters sound along with shareAppContentToStage? We use this method to show a tab with a video, and if participants are not muted, it might cause an echo. Our idea is to share the sound from the presenter along with the content and mute the video for other participants on their side so that everyone hears only the presenter’s video. Is it possible to achieve in Microsoft Teams?

Thank you!

**Comment by Nivedipa-MSFT** [comment]
@markitosha - Thanks for reporting your issue. We will check this and update you soon.

**Comment by Nivedipa-MSFT** [comment]
@markitosha - Currently, Microsoft Teams does not support sharing the presenter's audio directly along with the content when using shareAppContentToStage. 
To achieve your requirements, we recommend you give your feedback in [Teams Feedback Portal](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472).

**Comment by Nivedipa-MSFT** [comment]
@markitosha - Could you please share your valuable feedback via [Microsoft Teams Developer Community Response Feedback](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u)
link?
