### ISSUE TITLE
Context on Mobile

### ISSUE THREAD

**Issue by HeinA** [OfficeDev/microsoft-teams-library-js#245]
'ello

When opening a teams tab on a mobile device, I do not get the context.  This works correctly in the Desktop App.  Is this a known issue? Is there a workaround?

Any help would be appreciated
Regards
Hein

------------------------------
```typescript
import { Component, OnInit } from '@angular/core';
import { NavbarService } from './../nav-menu/nav-menu.service';
import * as microsoftTeams from '@microsoft/teams-js';

@Component({
  selector: 'app-config-component',
  templateUrl: './config.component.html'
})
export class ConfigComponent implements OnInit {
  constructor(public nav: NavbarService) {
    nav.hide();
  }

  public Context: microsoftTeams.Context;
  
  public OnGetContext = (context: microsoftTeams.Context) => {
    this.Context = context;
  }

  public OnSaveEvent = (saveEvent) => {
    microsoftTeams.settings.setSettings({
      entityId: "production-plan",
      contentUrl: "https://nmpp.ngrok.io",
      suggestedDisplayName: "Production Plan",
      websiteUrl: "https://nmpp.ngrok.io/website",
      removeUrl: "https://nmpp.ngrok.io/remove",
    });
    microsoftTeams.settings.setValidityState(true);
    saveEvent.notifySuccess();
  }

  ngOnInit() {
    microsoftTeams.initialize();
    microsoftTeams.getContext(this.OnGetContext);
    microsoftTeams.settings.registerOnSaveHandler(this.OnSaveEvent);
  }
}
```
-----------------------
```html
<h1>Configuration</h1>

<p>Team Name: <strong>{{ Context.teamName }}</strong></p>
```

![TeamsConfig](https://user-images.githubusercontent.com/1184125/61956868-4a7f1400-afbe-11e9-9cd2-2cacf7f20a0c.png)

**Comment by Wajeed-msft** [comment]
Could you please confirm if following code is working fine for you on mobile?

**Script:**
 ```
var app = angular.module('DemoApp', [])
        app.controller('myController', function ($scope) {
            $scope.load = function () {
                microsoftTeams.initialize();
                microsoftTeams.getContext(context => {
                    alert(JSON.stringify(context));
                });
                
            }
        });
```
**HTML:**
```
<body ng-app="DemoApp" ng-controller="myController">
    <div ng-init="load()">
        This is a sample code.
    </div>
</body>
```

**Comment by HeinA** [comment]
Thank you for the response Wajeed

Your example does work...

My example is an Angular App created from a Visual Studio 2019 Core 2.2 Angular template.
Do you have any idea why it is not working there?

I'm new to both Angular development as well as Teams development :)

Regards
Hein

**Comment by HeinA** [comment]
OK...

It works on an ordinary tab.  
![Screenshot_2019-07-31-12-33-38](https://user-images.githubusercontent.com/1184125/62205378-9bf91b80-b38f-11e9-9ada-13997d601340.png)


On a config tab it returns no results
![Screenshot_2019-07-31-12-33-13](https://user-images.githubusercontent.com/1184125/62205398-a4515680-b38f-11e9-93ee-616816187283.png)


Cheerz
Hein

**Comment by Wajeed-msft** [comment]
> It works on an ordinary tab.

What do you mena by ordinary tab? Are you referring to [static tabs](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/tabs/tabs-static)?

**Comment by HeinA** [comment]
‘ello

No, I mean it works on a configurable tab’s content page.  Just not on the configuration Page.

**Comment by Wajeed-msft** [comment]
There is a bug that not all the values are populated in context object on mobile. We are tracking this internally.

**Comment by HeinA** [comment]
Thank you very much :)

**Comment by HeinA** [comment]
‘ello

No, I mean it works on a configurable tab’s content page.  Just not on the configuration Page.

Sent from Mail for Windows 10
