### ISSUE TITLE
Deep Link from Adaptive Card to Static (Personal) App is not working

### ISSUE THREAD

**Issue by jker-org** [OfficeDev/microsoft-teams-library-js#2471]
Hi there,

we have a problem catching the information from a deep link with our app.

We have an adaptive card that uses Action.OpenURL to open the following link (our app id is replaced with <app_id>):
`https://teams.microsoft.com/l/entity/<app_id>/index?label=Upgrade&context={'subEntityId':'upgrade'}`

The app opens, but we can not receive the sub entity id.

Our code:
```typescript
                if (!microsoftTeams.isInitialized()){
                    await microsoftTeams.initialize();
                    hyDebug("Teams-JS initialized.");
                }
                const inner_context = await microsoftTeams.getContext();
                // [...]
               console.log(inner_context.page);
``` 

Console output:
`
{
    "id": "index",
    "frameContext": "content",
    "subPageId": "",
    "isFullScreen": false,
    "isMultiWindow": false,
    "sourceOrigin": ""
}
`

We use:
`@microsoft/teams-js": "^2.26.0"`

**Is there anything we miss?** 

We use a React app, but context is read before any routing happens.

Experienced in Teams Web (Windows; Edge and Google Chrome). Teams Desktop not tested due to inability to read console log.

**Comment by sayali-MSFT** [comment]
Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by jker-org** [comment]
@sayali-MSFT : Thank you for the link. However, the example is not relevant for my case. The example shows on how to use deeplink in conversations. Again, I have a URL with a deeplink to my static app. In the app, the page information is completely empty as if the deeplink did not conatin any information.

According to our opinion, this is a bug.

**Comment by jker-org** [comment]
@ChetanSharma-msft , @sayali-MSFT : We found the issue. Please decide for yourself if you consider this as a bug or not. Solution: It is **absolutely** necessary to encode the context.

With this link, it works:

`https://teams.microsoft.com/l/entity/<app_id>/index?&context=%7B%22subEntityId%22:%20%22upgrade%22%7D`

If someone comes across this, use this js code to generate a static link for yourself:

```javascript
const encodedContext = encodeURI('{"subEntityId": "upgrade"}');
const deeplink = 'https://teams.microsoft.com/l/entity/<app_id>/index?&context=' + encodedContext;

// Log to console
console.log(deeplink)
```

**Comment by sayali-MSFT** [comment]
@jker-org -We will check this from our end, and if it is a bug, we will raise it accordingly and let you know the update

**Comment by sayali-MSFT** [comment]
All the query parameters and the white spaces are properly URI encoded. which is already [documented here](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-application?tabs=teamsjs-v1#configure-deep-link-to-browse-within-your-app-manually).
![image](https://github.com/user-attachments/assets/7f3ff21d-77eb-4e1a-8b22-7ff9e318a47f)
