### ISSUE TITLE
There seems to be a typo in the base HTML on the Home tab of the Workflows.

### ISSUE THREAD

**Issue by seoheehahn** [OfficeDev/microsoft-teams-library-js#2472]
![스크린샷 2024-08-20 오후 2 38 50](https://github.com/user-attachments/assets/6d1dfb82-28ae-4744-ac31-4c670bf65682)
![스크린샷 2024-08-20 오후 2 42 56](https://github.com/user-attachments/assets/1f886bac-0483-4b9a-baad-423f953d0bad)

Is this a typo?

**Comment by Prasad-MSFT** [comment]
We checked this at our end and are able to repro. We are checking this internally with engineering team. 
We will update you once we hear from them. Thanks!

![image](https://github.com/user-attachments/assets/96b85f87-42d1-4a59-8ce4-6622c67af318)

**Comment by Prasad-MSFT** [comment]
Hi @seoheehahn, the issue seems to be fixed now. Please do verify.
![image](https://github.com/user-attachments/assets/67a903f6-5729-40d6-8add-3a341382d7d1)

**Comment by Prasad-MSFT** [comment]
@seoheehahn, Could you please share your valuable feedback via [Microsoft Teams Developer Community Response Feedback](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u) link?
