### ISSUE TITLE
microsoftTeams is not defined when upgrading to version 2.26.0

### ISSUE THREAD

**Issue by maurelio1234** [OfficeDev/microsoft-teams-library-js#2478]
We were using version 2.3.0 directly from the cdn: https://res.cdn.office.net/teams-js/2.3.0/js/MicrosoftTeams.min.js

We updated to version 2.26.0 by changing the script src to the new version https://res.cdn.office.net/teams-js/2.26.0/js/MicrosoftTeams.min.js

We initialise the SDK via:

```js
        microsoftTeams.initialize(() => {
           ...
        });
```

Now we get an `microsoftTeams is not defined` error.

**Comment by Nivedipa-MSFT** [comment]
@maurelio1234 - Thanks for reporting your issue. We will check this and update you soon.

**Comment by maurelio1234** [comment]
@Nivedipa-MSFT 

Hi,

I get the same error, it's the first `microsoftTeams` that is undefined.

**Comment by jadahiya-MSFT** [comment]
Hi @maurelio1234, I'm sorry that you are running into this issue. I'll be looking into this error for you. 

Something that would be helpful for me are how you are importing 2.26.0 and a screenshot of the error in question. In the meantime, I will be trying to reproduce the issue on my end.

**Comment by maurelio1234** [comment]
@jadahiya-MSFT 

I import it via the CDN on an HTML page with a sign in button that also imports my code:

```html
<script
  src="https://res.cdn.office.net/teams-js/2.26.0/js/MicrosoftTeams.min.js"
  integrity="sha384-gqPg5qCjdUgTGRZ/stLskrnJllL5h5+f4kTqvxVqtl2FdT7PVRa9Q7zq4gFlZ7bO"
  crossorigin="anonymous"
></script>
...
<script type="text/javascript" src="{{staticBaseHost}}/static/mycode.js?{{timestamp}}" defer></script>
...
<button id='sign-in'>SIGN IN</button>

```

In my code I do

```js
const signInButton = document.getElementById("sign-in");

signInButton.addEventListener("click", function () {
        microsoftTeams.app.initialize().then(() => {
            microsoftTeams.authentication.authenticate({
                ...
            });
        });
    });

```

When I click on the button I have the error:

```
2microsoftTeamsStaticTabAuthentication.js:13 Uncaught ReferenceError: microsoftTeams is not defined
    at HTMLButtonElement.<anonymous> (microsoftTeamsStaticTabAuthentication.js:13:9)
```

**Comment by jadahiya-MSFT** [comment]
@maurelio1234 Can you confirm if the CDN call to acquire the 2.26.0 version is succeeding? Do you see that `microsoftTeams` is in the sources list?

It appears to me that it should because the integrity hash and cdn links are correct. Do you know if this also affects other versions that are <2.26.0?

**Comment by maurelio1234** [comment]
@jadahiya-MSFT 

Hi, 

>  Do you see that microsoftTeams is in the sources list?

Indeed it is not there ❗ 
And I just noticed this error message:

```
Failed to find a valid digest in the 'integrity' attribute for resource '<URL>' with computed SHA-384 integrity 'gqPg5qCjdUgTGRZ/stLskrnJllL5h5+f4kTqvxVqtl2FdT7PVRa9Q7zq4gFlZ7bO'. The resource has been blocked.
```

this matches the sha on your [doc](https://learn.microsoft.com/en-us/javascript/api/overview/msteams-client?view=msteams-client-js-latest&tabs=npm#cdn), that I copied on my sources:

```
<script
  src="https://res.cdn.office.net/teams-js/2.26.0/js/MicrosoftTeams.min.js"
  integrity="sha384-gqPg5qCjdUgTGRZ/stLskrnJllL5h5+f4kTqvxVqtl2FdT7PVRa9Q7zq4gFlZ7bO"
  crossorigin="anonymous"
></script>
```

Maybe the doc is just wrong ❓ 

<details>
<summary>Other responses</summary>

> Can you confirm if the CDN call to acquire the 2.26.0 version is succeeding? 

Yes, I see it in dev tools

<img width="1508" alt="Screenshot 2024-08-22 at 19 19 43" src="https://github.com/user-attachments/assets/6770d0f8-a760-4764-96e9-a222d577fe8f">

> Do you know if this also affects other versions that are <2.26.0?

It was working fine in v2.3.0.


</details>

**Comment by jadahiya-MSFT** [comment]
@maurelio1234
> ```
> Failed to find a valid digest in the 'integrity' attribute for resource '<URL>' with computed SHA-384 integrity 'gqPg5qCjdUgTGRZ/stLskrnJllL5h5+f4kTqvxVqtl2FdT7PVRa9Q7zq4gFlZ7bO'. The resource has been blocked.
> ```

The above is very curious because I don't see a reference to URL when I purposely break the integrity hash with the following:

```html
    <script
      src="https://res.cdn.office.net/teams-js/2.26.0/js/MicrosoftTeams.min.js"
      integrity="sha384-tester"
      crossorigin="anonymous"
    ></script>
```

I get the following:

`Failed to find a valid digest in the 'integrity' attribute for resource 'https://res.cdn.office.net/teams-js/2.26.0/js/MicrosoftTeams.min.js' with computed SHA-384 integrity 'gqPg5qCjdUgTGRZ/stLskrnJllL5h5+f4kTqvxVqtl2FdT7PVRa9Q7zq4gFlZ7bO'. The resource has been blocked.`
 
 Can you verify that the integrity hash and CDN url is only used in that one location?

**Comment by maurelio1234** [comment]
@jadahiya-MSFT 

I just did the test again and I indeed got the url of my tab:

```
[THE URL OF MY TAB]:1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://res.cdn.office.net/teams-js/2.26.0/js/MicrosoftTeams.min.js' with computed SHA-384 integrity 'gqPg5qCjdUgTGRZ/stLskrnJllL5h5+f4kTqvxVqtl2FdT7PVRa9Q7zq4gFlZ7bO'. The resource has been blocked.
```

> Can you verify that the integrity hash and CDN url is only used in that one location?

yes, this is the only page that has been charged on the embed at this point.

> If you tried to remove importing your script and instead call your code directly from the HTML as I did in my above message do you see the same error?

I will test and tell you

**Comment by maurelio1234** [comment]
@jadahiya-MSFT 

>> If you tried to remove importing your script and instead call your code directly from the HTML as I did in my above message do you see the same error?

> I will test and tell you

Just tested it and I get the same error.

**Comment by maurelio1234** [comment]
@jadahiya-MSFT 

Just another bit: I downgraded to 2.25.0 (and removed the integrity attribute) and it works.
The problem here seems to be either on the `integrity` bit or on more generally on v2.26.0.

**Comment by maurelio1234** [comment]
@jadahiya-MSFT 

I confirm that if I remove the `integrity` attribute everywhere, v2.26.0 works without problems.

**Comment by jadahiya-MSFT** [comment]
@maurelio1234 

Thanks for testing, I don't recommend removing the `integrity` attribute, since that could expose you to a security risk. 

I'm going to run through some of my own tests to confirm whether the issue is with the `integrity` bit. 

>I confirm that if I remove the integrity attribute everywhere, v2.26.0 works without problems.

Just for clarification, does "everywhere" just mean the one location? 

>Just another bit: I downgraded to 2.25.0 (and removed the integrity attribute) and it works.
The problem here seems to be either on the integrity bit or on more generally on v2.26.0.

Can you try the following for testing with v2.25.0 to see if the `integrity` hash works there for you.

```html
<script
  src="https://res.cdn.office.net/teams-js/2.25.0/js/MicrosoftTeams.min.js"
  integrity="sha384-6royw0i5cEmf/8pzbTX9dVy1pjjJA8PQOaQbGvoL/m39OdjrlcWluhQZxqy5KbJA"
  crossorigin="anonymous"
></script>
```

Also I wanted to say thanks for being responsive and helping us track down the root of this issue.

**Comment by maurelio1234** [comment]
@jadahiya-MSFT 

Hi!

> Just for clarification, does "everywhere" just mean the one location?

In this page I am doing a SSO authentication flow, so there's this page where I call `microsoftTeams.authentication.authenticate` and another one where I call `microsoftTeams.authentication.notifySuccess`

They both work fine on 2.26.0 without the `integrity` attribute

> Can you try the following for testing with v2.25.0 to see if the integrity hash works there for you.

I just tested it and it works fine.

**Comment by TrevorJoelHarris** [comment]
@maurelio1234 I just tried to put together a really simple webpage that matched the sample that you shared [here](https://github.com/OfficeDev/microsoft-teams-library-js/issues/2478#issuecomment-2305166839).

```html
<html>
<head></head>
<body>
	<script src="https://res.cdn.office.net/teams-js/2.26.0/js/MicrosoftTeams.min.js" integrity="sha384-gqPg5qCjdUgTGRZ/stLskrnJllL5h5+f4kTqvxVqtl2FdT7PVRa9Q7zq4gFlZ7bO"crossorigin="anonymous"></script>
	<button id='sign-in'>SIGN IN</button>
	<script>
		const signInButton = document.getElementById("sign-in");
		signInButton.addEventListener("click", function () {
			console.log(`TeamsJS is initialized is a ${microsoftTeams.app.isInitialized()} statement`);
		});
	</script>
</body>
</html>
```

When I run this page locally it seems to work correctly:

![image](https://github.com/user-attachments/assets/4e8689a3-f234-45e1-843e-20e537e40e43)

Does the above simple web page work for you?

**Comment by maurelio1234** [comment]
@TrevorJoelHarris 

Yes, I confirm it works, if I just open it on a browser like via `file:///tmp/test.html`.

**Comment by TrevorJoelHarris** [comment]
Okay, great! This means that the problem isn't with the 2.26 SHA hash. When I take that sample and change the SHA hash value it breaks.

The error that you are running into: 

"microsoftTeams is not defined"

Suggests to me that your app's script is executing before you have finished downloading the 2.26 package from the CDN. 2.26 is larger than 2.3 (and SHA hash checks add extra time to the download). I noticed that you have the `defer` attribute on your app's script tag:

![image](https://github.com/user-attachments/assets/c1fda6bd-6ded-4244-b2dc-78e68121052f)

I'm curious: if you remove the `defer` tag what happens? Does everything work? I wonder if using defer for that tag but not the CDN script is causing your script to get executed after the page finishes rendering but *ahead* of when the CDN package finishes downloading.

**Comment by maurelio1234** [comment]
@TrevorJoelHarris 

> I'm curious: if you remove the defer tag what happens? Does everything work? I wonder if using defer for that tag but not the CDN script is causing your script to get executed after the page finishes rendering but ahead of when the CDN package finishes downloading.

Hi,

yes I confirm removing the the `defer` keywork fixed the problem! 
Thanks, this unblocks me!
I guess we can close this ticket.

**Comment by TrevorJoelHarris** [comment]
@maurelio1234 Glad that worked!
