### ISSUE TITLE
Teams SDK timeout - only on the Microsoft 365 Android app

### ISSUE THREAD

**Issue by FedWiebe** [OfficeDev/microsoft-teams-library-js#2482]
Our Teams (Office) app is running nicely everywhere. We are also already published in AppSource.

Suddenly, however, the Teams SDK starts timing out in the Microsoft 365 app on Android. It still works in the Outlook and Teams Apps on Android.

I enabled debug logging and attached the results.

[www.federated.directory-1724507869813.log](https://github.com/user-attachments/files/16736844/www.federated.directory-1724507869813.log)

**Comment by FedWiebe** [comment]
I'm using version 2.21 of the TeamsJS package.

This is the code in which it is initialized:

`// Initialize the Microsoft Teams SDK only once
  async initialize (): Promise<void> {
    try {
      await microsoftTeams.app.initialize();
    } catch (error) {
      console.log(
        `MicrosoftTeamService: Error initializing Teams SDK`,
        error
      );
      throw error;
    }
    return;
  }`

**Comment by Nivedipa-MSFT** [comment]
@FedWiebe - Thanks for reporting your issue. Could you please share your repro video along with the deployed application zip so we can test it on our end?

**Comment by FedWiebe** [comment]
Hi @Nivedipa-MSFT 

Thanks for spending the time 👍

Attached the movie and the manifest.

But we are also in the Marketplace: https://appsource.microsoft.com/nl-nl/product/office/wa200007331?tab=overview

https://github.com/user-attachments/assets/7d89d188-bb49-42c0-b88e-13db01550082
[manifest.zip](https://github.com/user-attachments/files/16745551/manifest.zip)

**Comment by FedWiebe** [comment]
Updating the SDK to 2.26.0 solved this issue, it seems. I haven't tested all the scenario's yet, but I can log in now again in the Microsoft 365 app in our DEV environment.

The Microsoft team that helped us get onboarded on the AppSource marketplace, however advised us to stick to 2.21 for now. 
Is it OK to switch to 2.26.0?

**Comment by AE-MS** [comment]
> Updating the SDK to 2.26.0 solved this issue, it seems. I haven't tested all the scenario's yet, but I can log in now again in the Microsoft 365 app in our DEV environment.
> 
> The Microsoft team that helped us get onboarded on the AppSource marketplace, however advised us to stick to 2.21 for now. Is it OK to switch to 2.26.0?

I don't understand why anyone from Microsoft would have advised you to stay on a lower version but I will ask the app validation team about ensuring these recommendations get corrected. You absolutely should able to switch to the latest version of the teamsjs library.

Thanks!
