### ISSUE TITLE
[Question] Is it possible to unset subEntityId after executing deeplink

### ISSUE THREAD

**Issue by raimi6** [OfficeDev/microsoft-teams-library-js#250]
Hey, my app has internal navigation inside configurable tab and after navigating to my tabs content  by DeepLink I want to somehow unset subEntityId from app.
As I understand from docs deeplink just takes me to tab and all internal tab navigation has to me manual.
`microsoftTeams.getContext((context) => {
      if (context.subEntityId) {
            this.props.history.push('/client/items/' + context.subEntityId);
      }
 });`

**Comment by asnow003** [comment]
Hello there, just trying to understand your flow.  So after navigating by deep link to your tab the context is set with the subEntityId that was in the deep link.  Are you wanting to change the value of the context?

**Comment by raimi6** [comment]
Yes, I want to change the value of context in this case remove deep link parameters  from it inside app.

**Comment by ChetanSharma-msft** [comment]
Hello @raimi6 - Hope you are doing well!!
Looks like these changes are rolled out.

Could you please check and confirm here?
