### ISSUE TITLE
calendar.composeMeeting is not working on Outlook desktop app on Windows

### ISSUE THREAD

**Issue by RichieMcCaff** [OfficeDev/microsoft-teams-library-js#2500]
When using the calendar module in the Outlook desktop app we get the following error when trying to compose a meeting:

<img width="396" alt="Screenshot 2024-09-05 at 12 06 57" src="https://github.com/user-attachments/assets/a270a416-c601-4c8b-939b-4d6153672bf5">

This is after confirming the module is supported and confirmed working on outlook web and mobile apps.

**Comment by AE-MS** [comment]
@RichieMcCaff This seems to be a problem in Outlook itself. Let me reach out to the Outlook team and get back to you.

**Comment by krubenok** [comment]
Hi @RichieMcCaff - my team and I are responsible for these APIs in Outlook. We're looking into it and as @AE-MS mentioned we do have a repro. Please give us a few days into next week and i'll see if I can share any details then. 

Thanks.

**Comment by krubenok** [comment]
Update from our end, Classic Outlook for Windows was incorrectly expecting that startTime and endTime were required while the TeamsJS API lists them as optional. We have a PR out to fix this and with all things rolling out smoothly, the fix should be available in Insiders Beta channel in a few weeks. 

Given that slower forks of Classic Outlook can take several months to receive updates, I would suggest adding some placeholder startTime and endTimes in composeMeeting to ensure CC, MEC, and SAC users don't face this error in the mean time.

**Comment by RichieMcCaff** [comment]
Probably would have helped if I included the parameters I was using in the issue!
Thanks for the workaround, I'll add it and close this out.
