### ISSUE TITLE
Can't enable media permissions for anonymous users

### ISSUE THREAD

**Issue by Tryptophan** [OfficeDev/microsoft-teams-library-js#2509]
Hi dev team,

When using an app in a teams meeting that requires media as an anonymous user in the web client, there is no way for the user to enable those permissions.

For example for a logged in user, they can do the following:
![Screenshot from 2024-09-11 16-31-35](https://github.com/user-attachments/assets/ab0d4a0b-832c-42b0-a01b-cdc997510a76)
![Screenshot from 2024-09-11 16-31-48](https://github.com/user-attachments/assets/58904b91-9f5b-42da-b5d5-d4f331e905de)
![Screenshot from 2024-09-11 16-32-04](https://github.com/user-attachments/assets/b2b9d341-30c2-4d09-af1b-b480112f6673)
to enable media permissions for an app added to the meeting.

For anonymous users these settings don't exist. Is there any way to programmatically show the user the permissions dialog (similar to the native app) for that user to enable the permission when they don't have access to these settings?

**Comment by Nivedipa-MSFT** [comment]
@Tryptophan - Thanks for reporting your issue. We will check this and update you soon.

**Comment by Prasad-MSFT** [comment]
Hi @Tryptophan, thanks for raising your issue. We will check this with engineering team and will get back to you.

**Comment by Prasad-MSFT** [comment]
@Tryptophan, currently there is no way available to programmatically show the user the permissions dialog (similar to the native app) to enable the permission when they don't have access to these settings. To better achieve your requirements, we recommend submitting this feature request through the [Teams Feedback Portal](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472). This is the best way to ensure your idea is considered for future updates.
