### ISSUE TITLE
OAuthPrompt is not showing button on Team app v2

### ISSUE THREAD

**Issue by vbatr** [OfficeDev/microsoft-teams-library-js#2510]
Hi,

Our application is using OAuthPrompt in order to get Bot Framework Token:

            AddDialog(new OAuthPrompt(
                nameof(OAuthPrompt),
                new OAuthPromptSettings
                {
                    ConnectionName = ConnectionName,
                    Text = "Sign in with Microsoft account",
                    Title = "Sign In",
                    Timeout = 300000, // User has 5 minutes to login (1000 * 60 * 5)
                    EndOnInvalidMessage = true
                }));
                
             
With some of the latest Teams app update the prompt **is not showing the button** on Team web/desktop/mobile:

![Screenshot 2024-09-13 at 12 54 55](https://github.com/user-attachments/assets/ad9f81d6-aa31-47dd-9db0-b09518c822cc)

But the button is displayed correctly in test WebChat in portal.azure.com, so it seems it just Teams issue.
Is there any workaround for that?

Regards,
Volodymyr B.

**Comment by sayali-MSFT** [comment]
@vbatr -Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by vbatr** [comment]
Thanks @sayali-MSFT. The issue is related to Teams client and/or Bot Framework/Bot Builder, but I could not find proper repository to report it there....

**Comment by sc3446** [comment]
One more issue: https://github.com/microsoft/BotBuilder-Samples/issues/4013

**Comment by sayali-MSFT** [comment]
@@vbatr -We have tested this issue on the updated Teams client, and it looks like the issue is resolved with this new version. Could you please check and confirm?
![image](https://github.com/user-attachments/assets/33a61888-5ac1-4fbc-a1e3-1076c4aa6edf)


![image](https://github.com/user-attachments/assets/0a58b723-2b9e-4cd8-8e28-950d2cbdf378)

**Comment by vbatr** [comment]
Hi @sayali-MSFT 

The issue is not reproducible on the latest version of Teams client. Seems it was fixed.
Closing the ticket.

**Comment by sayali-MSFT** [comment]
@vbatr - Could you please share your valuable feedback via[ Microsoft Teams Developer Feedback link.](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u)
