### ISSUE TITLE
Login adminconsent redirect_uri

### ISSUE THREAD

**Issue by LeonYasoon** [OfficeDev/microsoft-teams-library-js#2515]
Hi Teams.
Not sure where to correct place to raise this issue would be, so please feel free to point me in the right direction.

When creating an adminconsent URL like `https://login.microsoftonline.com/organizations/v2.0/adminconsent?client_id={{CLIENTID}}&scope={{SCOPES}}&redirect_uri={{REDIRECTURI}}&state={{STATE}}` and confirming the admin consent, the user is sometimes redirect to a URI that is shaped like `{{REDIRECTURI}}?admin_consent=True&tenant={{TENANTID}}&state={{state}}Sign+in+to+your+account` which leads to the state being corrupted by the string "Sign in to your account" beeing appended.

**Comment by Prasad-MSFT** [comment]
Hi @LeonYasoon, thanks for raising your issue. Could you please provide more details on your issue? Any repro video would be really helpful.

**Comment by LeonYasoon** [comment]
Sure, here is what the flow looks like:

Open a Microsoft adminconsent login URL that is shaped like `https://login.microsoftonline.com/organizations/v2.0/adminconsent?client_id={{CLIENTID}}&scope={{SCOPES}}&redirect_uri={{REDIRECTURI}}&state={{STATE}}`
![Screenshot 2024-09-18 at 08 55 53](https://github.com/user-attachments/assets/9055c28b-a4cc-436b-9739-24fd4aaaf4f8)

Select an admin account
![Screenshot 2024-09-18 at 08 56 03](https://github.com/user-attachments/assets/23a4fa6d-bddb-49a1-a0fc-9948ff3fe2a8)

Approve the request
<img width="1393" alt="Screenshot 2024-09-18 at 08 58 12" src="https://github.com/user-attachments/assets/7bb62704-5e73-4c55-904a-bbf3c53af6f6">

Sometimes, the redirect uri that is provided with the adminconsent URL is called with the provided state but also with the string "Sign+in+to+your+account" appended to the state query, which can be seen here in our access logs:
![Screenshot 2024-09-18 at 09 09 12](https://github.com/user-attachments/assets/f5cb22de-ad04-4736-9ee9-96183f3840d3)

**Comment by LeonYasoon** [comment]
Also, please excuse me if this is not the right place to raise this request and feel free to point me in the right direction.

**Comment by Prasad-MSFT** [comment]
Thanks for providing the details. We are checking this with engineering team. We will inform you once we have any update.

**Comment by Prasad-MSFT** [comment]
We have raised an ICM for this issue and engineering team is looking into it. We will inform you once we have further update. Thanks!

**Comment by Prasad-MSFT** [comment]
Hi @LeonYasoon, could you please provide additional details about the failure?
We would need either fiddler trace, or traceId/CorrelationId from the failed request, or har file with network requests from the browser dev tools. If you can provide these, engineering team can take a look.

**Comment by LeonYasoon** [comment]
Hi @Prasad-MSFT, the `X-Request-Id` on the response of `searchV2` is `42d54e1e-6e2b-4cac-bc24-da11b67b7093` and the `x-serverrequestid` is `704CB68132EF4928B29B595694B95245`. I can provide a har file aswell but since the network logs contain sensitive data i would rather not post it here in this public thread.

**Comment by LeonYasoon** [comment]
Hi @Prasad-MSFT, going through our access logs, i cannot find an occurence of this issue in the past weeks. Seems like the queryState providing entity has fixed this already. Feel free to close the issue.
