### ISSUE TITLE
Getting empty SSO token from mobile outlook app  

### ISSUE THREAD

**Issue by chandraarora** [OfficeDev/microsoft-teams-library-js#2537]
Hi 

We have developed a teams app which takes the sso token from the app and get the onbehalf of token from entra (Azure AD). We are using the teams SDK teamsUserCredential.getToken(''). This is working on Teams apps (dekstop, mobile , web) , outlook web but on outlook on mobile we get empty SSO token. What could be wrong? Please see the code below. 

I would appriciate any help, we do not find any reason whey it does not work on outlook of android and ios but it works on rest the platform. 

```

async (teamsUserCredential, { dispatch, rejectWithValue, getState }) => {
    const { auth } = getState()
    try {
      **var tokenRes = await teamsUserCredential.getToken('')**
      const teamsContext = await app.getContext()
      const res = await getRecentOneDriveFiles(
        tokenRes.token,
        '',
        teamsContext.user.tenant.id
      )
```
 
Best regards
Chandra

**Comment by Nivedipa-MSFT** [comment]
@chandraarora - Thanks for reporting your issue. We will check this and update you soon.

**Comment by Nivedipa-MSFT** [comment]
@chandraarora - Have you tested with the [GetTokenAsync()](https://learn.microsoft.com/en-us/dotnet/api/microsoft.teamsfx.teamsusercredential.gettokenasync?view=msteams-client-dotnet-latest#microsoft-teamsfx-teamsusercredential-gettokenasync(azure-core-tokenrequestcontext-system-threading-cancellationtoken)) method? Is it working for you? Please let us know if you have any further queries

**Comment by chandraarora** [comment]
Hi

I came to know from Teams approval team that this is a platform limitation, and it does not work at the moment. Does Teams app supported on office 365 anroid/ios mobile?

Thanks
Chandra

**Comment by Nivedipa-MSFT** [comment]
@chandraarora - Yes, the Microsoft Teams app is supported on both Android and iOS mobile devices.

**Comment by erinha** [comment]
Hi @chandraarora, thanks for reporting this issue. The `teamsUserCredential` is a class in the teams-toolkit library (for what it's worth, I noticed that the [documentation](https://github.com/OfficeDev/teams-toolkit/blob/ef1e05412294f363eeac0ea7c7223c23882637fe/packages/sdk/src/credential/teamsUserCredential.ts#L13C1-L19C62) on the class indicates it only works in Teams). 

I suggest that you open your issue in the teams-toolkit repo: https://github.com/OfficeDev/teams-toolkit/issues. 

It may be that this is a feature request to have the `teamsUserCredential` work in other hosts aside from Teams, but it would be best to have the teams-toolkit team confirm. Either way, they should be able to help with this.

Hope this helps!

**Comment by chandraarora** [comment]
Thank you Erin, will do this.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mr-github-user** [comment]
I was encountering this same issue and found a solution here: 
https://github.com/OfficeDev/teams-toolkit/issues/10987

I had to add outlook mobile as a client app registration in my app's app registration.

**Comment by jekloudaMSFT** [comment]
Closing this since it's on teams-toolkit. Thanks for providing the solution, @mr-github-user!
