### ISSUE TITLE
Uncaught (in promise) Error: SDK initialization timed out.

### ISSUE THREAD

**Issue by JE-Development** [OfficeDev/microsoft-teams-library-js#2545]
Hello, I get this error message:
![Screenshot 2024-10-07 154642](https://github.com/user-attachments/assets/2d9d4dad-4198-4f81-af22-cc0cf4e952c7)
I am developing a website for Teams (Desktop) and I am using "Personal App" in "App Features". There I am using "https://localhost:5173". The website runs locally on my PC and the app is made with Vue.js + Vite. In the SSO Tab I am using this URL "api://localhost:5173/[client-id]"
The error message says that something is wrong in line 59.
Line 59 is: 
`microsoftTeams.app.initialize`
The full function is:
`created() {
  microsoftTeams.app.initialize({
    clientId: '<client-id>'
  })
},`
I use Teams version: 24257.204.3155.53
Client version: 49/24090101421
The strane party for me is that since beginning of development it worked normally but a day after (without changing anything) it stopped working and this error appear. Now my team members have the same issue.

**Comment by KangxuanYe** [comment]
Hi @JE-Development , thank you for providing your question with great detail so that we know what you and your team were doing. There are a few things we would still like to learn more about so that we can fully understand your situation and help you.

when you said that `I am developing a website for Teams (Desktop) and I am using "Personal App" in "App Features". `, is there any document or wiki you are following? I am not sure I understand what `Personal App` and `App Features` you were referring to. Could you please say more about those or you can have a screenshot to show me what are they look like?

Also, could you please try to follow this [document](https://github.com/OfficeDev/microsoft-teams-library-js/wiki/TeamsJS-Logging) in our GitHub to turn on client logging and send all of logs to us if there is any?

Please feel free to let us know if anything doesn't work or you don't know how to do it. Thank you.

**Comment by JE-Development** [comment]
Hello @KangxuanYe 
Here ypu can see what I mean with "Personal App" (Teams is on german language):
![s1](https://github.com/user-attachments/assets/630f4e03-1113-47ef-b22d-18803e0ffaa5)
![s2](https://github.com/user-attachments/assets/ff8e4f24-e8b2-4877-a378-7b6f9b3e98b7)
 
 In my log there are only 2 messages:
 1. (a warning) `An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.`
 2. the error message I showed you
 
 We use Vue.js + Vite with JavaScript. The teams-js version is 2.28.0

**Comment by KangxuanYe** [comment]
@JE-Development, thank you for explaining the detail to me with screenshots. I think now I understand what you / your team are working on. The only thing I am concerned about are logs you sent me. It looks like those are logs be thrown to browser by default.

Could you please follow this link (https://github.com/OfficeDev/microsoft-teams-library-js/wiki/TeamsJS-Logging) to turn on the client logging and send logs whose namespace starts with `teamsJs` to us? If you didn't see any logs like screenshots I shown below after turning on client logging, I think I'll have more questions.

![image](https://github.com/user-attachments/assets/b1c62a00-6dd6-4a4e-a6ec-712492f58bf6)

**Comment by JE-Development** [comment]
@KangxuanYe I followed these steps and in the 'Teams desktop console' nothing changed, but the logs in 'Teams web browser console' are different:
This are the logs by Teams Web (Firefox):
![s1](https://github.com/user-attachments/assets/95ca1902-e841-4baf-aeb3-250f5f65fd0b)
![s2](https://github.com/user-attachments/assets/c43bd2dc-e61b-45f3-a84e-d21f7ffd53fc)

**Comment by jadahiya-MSFT** [comment]
@JE-Development there is a known issue with Firefox, I am currently working on a fix to unblock testing using that browser, but for now could you run the log testing on a Chromium based browser to make sure you don't run into the known issue as a red herring. Additionally, can you try using `app.initialize` without supplying the `clientId` and see if you still run into a SDK initialization error.

**Comment by KangxuanYe** [comment]
Hi @JE-Development, thank you for providing the extra data. I can see your code goes into our Teams-Js library and hit one line in `app.ts` file. I think your code is doing something for initialization but generally speaking, if the initialization flow goes into Teams-Js library, there WILL be some logs printed out to console even if the initialization process hasn't been started yet. Could you please double check if you set the JavaScript context to match the domain your app is on, that you used the exact casing in the doc link (localStorage.debug = 'teamsJs.*';)? I have seen you turned on all of logLevels, including `verbose` which is great. And also did you refresh the app after completing these setup steps? I'd like to help understand why the client logs aren't showing up in your console.

It would also be helpful if you can provide your app's `appId` (you can set it as a special one for testing purpose) and I can take a look in our telemetry database to see what's going on with this initialize call.

**Comment by JE-Development** [comment]
@jadahiya-MSFT Thanks for your reply. Using `app.initialize` without `clientId` worked for me. It works in the Browser (tested in Chrome and Firefox) and in the Windows app. Thank you very much :D
