### ISSUE TITLE
[Bug] Compose calendar event URLs do not open the compose dialog on mobile

### ISSUE THREAD

**Issue by RichieMcCaff** [OfficeDev/microsoft-teams-library-js#2550]
So taking the following link: https://outlook.cloud.microsoft/owa?path=calendar/action/compose&rru=addevent&subject=test&body=test

On mobile devices it will open outlook and the the compose dialog will not open.

We used to use the deeplink url but had to switch to the above as it has a bug where it ends with a blank screen as described [here](https://techcommunity.microsoft.com/t5/microsoft-365/outlook-deeplink-calendar-compose-ends-with-a-blank-screen-on/m-p/4212741#M53563)

I understand this may not be the right place to raise this bug as I don't see the connection with teams-js but I've raised it in a few other places and some of our internal contacts in MS said to raise it here.

**Comment by sayali-MSFT** [comment]
@RichieMcCaff - Could you clarify what document you're referring to get the link?

**Comment by RichieMcCaff** [comment]
The action/compose link?

I've pulled this from the threads where it's been provided as a solution to the deeplink url blank screen issue

- https://techcommunity.microsoft.com/t5/outlook/https-outlook-office-com-calendar-0-deeplink-compose-fails-to/m-p/3816442
- https://github.com/InteractionDesignFoundation/add-event-to-calendar-docs/discussions/47
- https://github.com/OfficeDev/office-js/issues/3345

**Comment by AE-MS** [comment]
Even though this isn't the right forum for this, I reached out to the mobile OWA team and they have fixed this issue and will start rolling out the change worldwide next week. I'll report back here when it is fully available and you can verify it.

**Comment by AE-MS** [comment]
@RichieMcCaff can you verify that this works now? Everything should be rolled out.

**Comment by RichieMcCaff** [comment]
@AE-MS Sorry for the delay, I was doing that getting married thing.

Everything looks good with the owa link on mobile now, thank you for the swift response on all this.

**Comment by AE-MS** [comment]
Awesome; thanks for reporting the issue!
