### ISSUE TITLE
App sometimes completely gone without a trace after 5 seconds

### ISSUE THREAD

**Issue by justim** [OfficeDev/microsoft-teams-library-js#2552]
Our production app is running into a weird issue, every couple of refreshes our app goes blank without any error message. This only happens sometimes.

The app is fully functional for 5 seconds and then crashes — the entire `iframe` is gone from the Teams app, making it practically impossible to see what goes wrong _inside_ the `iframe`, if anything. The 5 seconds could be an indication of some kind of timeout, but there aren't any logs in the console to corroborate that.

Logging with `localStorage.debug = 'teamsJs.*';` for both cases:
![Screenshot 2024-10-09 at 17 23 48](https://github.com/user-attachments/assets/c8ca2c4b-2e79-45d0-8b1a-f1c0e7782388)
(did not fail)

![Screenshot 2024-10-09 at 17 24 15](https://github.com/user-attachments/assets/f3e5f56e-e841-44d3-8269-8cffef54cec9)
(did fail)

The logging is the same for both cases.

This happens in the desktop app, on different computers, and in the browser.

Environment:
- `@microsoft/teams-js`: `2.29.0` — latest version
- Microsoft Teams browser: 1415/24090101421
- Microsoft Teams (macOS): 24231.507.3099.9636

Is there any way to solve this from our end, or are we running in some weird bug?

**Comment by sayali-MSFT** [comment]
@justim-Thanks for reporting issue.
Could you please share more insight like code snippets and repro steps so that we can try it from our end.

**Comment by jekloudaMSFT** [comment]
Hi @justim, do you see any error UI in Teams when this occurs, or is it just a blank app page? And are you using the "Reload app" button in Teams to refresh the app?

**Comment by justim** [comment]
It goes completely blank without any indication of what happened; The logs from the initial comment are complete, there was nothing further.

I have removed the app and all development versions of the app — which had been there for months (maybe years), and re-installed the app from the store. The problem still occurs.

> Hi @justim, do you see any error UI in Teams when this occurs, or is it just a blank app page? And are you using the "Reload app" button in Teams to refresh the app?

I have only seen the problem when switching to the app, from "Chat" (or any other) to our pinned app, it then opens a `contentUrl` of our manifest. Have not seen it happen with the "Reload app" button.

> @justim Thanks for reporting issue. Could you please share more insight like code snippets and repro steps so that we can try it from our end.

I'm having a hard time coming up with a reproduction, it only happens sometimes without any errors, making it hard to pinpoint the problem.

I'll keep trying to get a reproduction, if you have any suggestions, I'm all ears.

**Comment by Jim-Bar** [comment]
Hi,

We have the exact same issue since we added Microsoft authentication in our personal app. Sometimes the iframe completely disappears, sometimes everything works just fine.

It only occurs when using authentication with Microsoft. When it occurs, we have a single error in the console: `either targetOrigin or target is invalid`. We stopped having the problem after uninstalling / reinstalling the personal app, but we are concerned that our customers may stumble on it.

**Comment by jekloudaMSFT** [comment]
Hi @Jim-Bar, can you please share which authentication API the app uses that introduces this issue?

**Comment by jekloudaMSFT** [comment]
Thanks @Jim-Bar, which part of the flow did you see the iframe disappear? When opening the dialog, calling `getAuthToken`, calling the backend, before any of that?

@justim, had you recently pushed any changes to the app?

**Comment by Jim-Bar** [comment]
I am not sure when, and now that the app has been uninstalled then reinstalled on my end, the issue no more occurs.

**Comment by justim** [comment]
We released a whole bunch of changes over the last week, including updated dependencies.

The problem does not seem to show up anymore, no idea what could have changed that.

And because the problem also seems to be gone for @Jim-Bar, I'm closing this issue.

Will report back if anything changes.

Thanks!
