### ISSUE TITLE
The published app disappeared on iOS "Add App"

### ISSUE THREAD

**Issue by nbelyh** [OfficeDev/microsoft-teams-library-js#2555]
We have a published teams application in the Microsoft marketplace, here
https://appsource.microsoft.com/sv-se/product/office/wa200003175

The problem is, the app stopped appearing in the "Add App" **on iOS devices** (add configurable tab)
If you use "Search" and try to look up "VisPlan", it comes up on desktop, Android, web, but not on iOS.

Are there some recent policy changes for iOS?

Manifest
```
{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.16/MicrosoftTeams.schema.json",
  "manifestVersion": "1.16",
  "id": "{{APPLICATION_ID}}",
  "version": "{{VERSION}}",
  "packageName": "{{PACKAGE_NAME}}",
  "developer": {
    "name": "VisPlan",
    "websiteUrl": "https://visplan.com",
    "privacyUrl": "https://visplan.com/support/privacy-policy-for-visplan",
    "termsOfUseUrl": "https://visplan.com/support/terms-of-service",
    "mpnId": "..."
  },
  "name": {
    "short": "{{APPLICATION_NAME}}",
    "full": "{{APPLICATION_NAME}}"
  },
  "description": {
    "short": "Visual Planning",
    "full": "....."
  },
  "icons": {
    "outline": "{{ICON_OUTLINE}}",
    "color": "{{ICON_COLOR}}"
  },
  "accentColor": "#f0f0f0",
  "configurableTabs": [
    {
      "configurationUrl": "https://{{HOSTNAME}}/tab/config?name={loginHint}&tenant={tid}&group={groupId}&theme={theme}",
      "canUpdateConfiguration": true,
      "scopes": [
        "team"
      ]
    }
  ],
  "staticTabs": [
    {
      "entityId": ".....",
      "scopes": [
        "personal"
      ],
      "context": [
        "personalTab"
      ],
      "name": "VisPlan",
      "contentUrl": "https://{{HOSTNAME}}/tab/personal?name={loginHint}&tenant={tid}&theme={theme}"
    }
  ],
  "permissions": [
    "identity",
    "messageTeamMembers"
  ],
  "validDomains": [
    "{{HOSTNAME}}"
  ],
  "defaultInstallScope": "team",
  "showLoadingIndicator": false,
  "publisherDocsUrl": "https://visplan.com/knowledge-base",
  "webApplicationInfo": {
    "id": "{{APPLICATION_ID}}",
    "resource": "api://{{HOSTNAME}}/{{APPLICATION_ID}}"
  },
  "localizationInfo": {
    "defaultLanguageTag": "en-us",
    "additionalLanguages": [
      {
        "languageTag": "sv-se",
        "file": "sv-se.json"
      }]
  }
}
```

**Comment by jekloudaMSFT** [comment]
Hi @nbelyh, thanks for reporting this. Can you confirm that you're seeing this on the Teams iOS app (as opposed to Outlook or Office)?

**Comment by nbelyh** [comment]
@jekloudaMSFT thank you for swift response!
Yes, correct, iOS Teams app, both iPhone and iPad.

**Comment by jekloudaMSFT** [comment]
Thanks @nbelyh, I'm still working on getting this issue routed to our Teams iOS team

**Comment by Meghana-MSFT** [comment]
@nbelyh - We tested this at our end by adding the app from Teams web client first. We were able to see the app in Teams iOS. Could you please let us know how you are searching for app in iOS as the app is made available in iOS only after it is added from Teams web/desktop. 

![visplan](https://github.com/user-attachments/assets/9f6a1b49-2898-456c-a33f-4c5e33d4a5e6)

**Comment by nbelyh** [comment]
The problem appears when you try to add a TAB, i.e. "Add an App" in a tab. Please check the video:

https://unmanagedvisio.com/upload/missing-visplan-tab.mp4

**Comment by Meghana-MSFT** [comment]
@nbelyh - We are able to repro this issue. We raised a bug for this, we will keep you posted on the updates. Thank you.
