### ISSUE TITLE
chat module is sending the message twice

### ISSUE THREAD

**Issue by RichieMcCaff** [OfficeDev/microsoft-teams-library-js#2559]
When using the functions from the chat module `openChat`/`openGroupChat` it will more often then not send the message input twice.

Something as simple as a button triggering this function:

```
chat.openChat({
      user: "test@test.com",
      message: "test
  })
```

Will result in the chat `testtest`

**Comment by sayali-MSFT** [comment]
@RichieMcCaff- Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by erinha** [comment]
Hi @RichieMcCaff I'm sorry you're running into this issue. On which client and platform are you running into this issue (e.g., Teams web or Outlook desktop, etc.)?

Additionally, if you can grab teams-js client logs for your app when you run into this problem, that would be helpful in investigating your issue. 

Please follow the directions here to turn on logging: https://github.com/OfficeDev/microsoft-teams-library-js/wiki/TeamsJS-Logging

Thanks!

**Comment by sayali-MSFT** [comment]
Hello @RichieMcCaff- Could you please provide the details mentioned by @erinha.
