### ISSUE TITLE
registerOnRemoveHandler cannot be called from Config/Settings page/iframeContext

### ISSUE THREAD

**Issue by miketeix** [OfficeDev/microsoft-teams-library-js#256]
The registerOnRemoveHandler cannot be called from Config/Settings page or iframeContext, I get an error when I try to do so.

I've created a second page for the removal experience where I call registerOnRemoveHandler (basically a call to our backend to clean up), and register the url for that page when I call setSettings under the `removeUrl` prop - though, the app doesn't redirect there, so what's the point of the `removeUrl` anyhow?

Any help is much appreciated.
@arawlins

**Comment by ydogandjiev** [comment]
Hi @miketeix, the `registerOnRemoveHandler` and `removeUrl` are meant to be used by app developers to provide a custom remove experience for their tabs and/or clean up resource associated with tabs if necessary. The `removeUrl` you provide as part of your tab configuration flow will be loaded by Teams in the remove dialog whenever user tries to delete your tab (red rectangle demarcates the area under your control):
![image](https://user-images.githubusercontent.com/3357245/62405586-0e1a5d80-b554-11e9-9167-3ba843cd3b3f.png)

You can read more about this in our documentation here:
https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/tabs/tabs-update-remove#removing-a-tab

**Comment by miketeix** [comment]
Hi Yuri @ydogandjiev, I forgot to mention that I'm trying to do all this from a `Connector` configuration and not from a tab (I originally created this issue from this page https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/connectors/connectors-creating?view=msteams-client-js-latest) . When I click on 'Remove' from the configure frame, there is no 'remove' dialog - point #6 from this page seems to suggested that I can... https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/connectors/connectors-creating?view=msteams-client-js-latest#integrating-the-configuration-experience
