### ISSUE TITLE
microsoftTeams.authentication open the auth.index page twice

### ISSUE THREAD

**Issue by RukaiYu** [OfficeDev/microsoft-teams-library-js#257]
Hi there,
I'm new to Teams SDK, while I'm doing the stuff as below:
```js
microsoftTeams.authentication.authenticate({
        url: `${window.location.origin}/assets/auth-start.html?env=${env}`,
        width: 600,
        height: 535,
...}) 
```
In Teams desktop version (macOS client), it will open the authorization popup, and then open the Url twice (two windows).

I dig into the example document, all things are the same.
Could anyone give some help?

Thanks!

**Comment by Gousia-MSFT** [comment]
@RukaiYu Have you looked at this [sample ](https://github.com/OfficeDev/microsoft-teams-sample-auth-node/tree/master/src/views/tab/simple)for Authentication? Could you please share a screenshot along with your manifest?

**Comment by RukaiYu** [comment]
![image](https://user-images.githubusercontent.com/3942409/63320454-6624d280-c350-11e9-9601-ff3694efa38c.png)
![image](https://user-images.githubusercontent.com/3942409/63320468-76d54880-c350-11e9-8fde-6a133ea9e5e7.png)
![image](https://user-images.githubusercontent.com/3942409/63320499-8e143600-c350-11e9-979b-f1fa5ccef2d3.png)
Hi @Gousia-MSFT  Thanks. I've looket that sample, and have same code setup.

**Comment by Gousia-MSFT** [comment]
@RukaiYu Could you please share a screenshot of the issue you are facing. Also please share the manifest file which we could upload to Teams and check on our side. Please share the manifest to Microsoft Teams developer support alias mentioned on [Feedback page](https://docs.microsoft.com/en-us/microsoftteams/platform/feedback) if you do not want to share it publicly.

**Comment by RukaiYu** [comment]
Hi @Gousia-MSFT I've sent an email to microsoftteamsdev@microsoft.com. Please kindly follow up that email with title: "Github Issue #257 follow up - The authorization window can't open while open two authentication windows".

Pls contact me if there have any problems.

Thanks!
