### ISSUE TITLE
[Question]: How to (or is it possible to) show an alert message notification in Teams?

### ISSUE THREAD

**Issue by RukaiYu** [OfficeDev/microsoft-teams-library-js#263]
[Question]: How to (or is it possible to) show an alert message notification in Teams?

I want to show some error message when the user clicks the action in my card and error happened in the backend.

**Comment by Gousia-MSFT** [comment]
@RukaiYu Could you please try [updating the card](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bot-conversations/bots-conversations#updating-messages) on error and see if that helps?
