### ISSUE TITLE
getContext() - non-async

### ISSUE THREAD

**Issue by craigwillis85** [OfficeDev/microsoft-teams-library-js#264]
Hi all

I've been using the TeamsJS SDK for a while and I've always used the `microsoftTeams.getContext()` way of determining if my app is currently in Teams.

My main issue is though, I need to display conditional data, based on whether or my app is inside teams.

I'm using VueJS and I'm checking in the `created()` function, that is called just before the DOM is created. Because of this, calling `microsoftTeams.getContext()` takes maybe 0.5 seconds. This is enough time to display some of the conditional data. Once the callback had completed and we are in Teams, it will display the teams specific conditional data, causing a slight flicker, whilst the data is shown/hidden

Is there a way to get the context in a non-async way? So, that i can call run display the conditional data if I know I'm teams?

Thanks

**Comment by Trinetra-MSFT** [comment]
Thanks for reporting this. We are looking into it.

**Comment by Gousia-MSFT** [comment]
@craigwillis85 Thanks for reaching out!! We have raised a feature request for adding async method for getContext in teams client SDK.
