### ISSUE TITLE
Duplicate Attendees Addition Issue via app.openLink URL on PC and Tablet

### ISSUE THREAD

**Issue by jrkgus413** [OfficeDev/microsoft-teams-library-js#2645]
The following issues are occurring with attendee data passed via app.openLink:

Attendees are occasionally duplicated on PC and some users are added multiple times.

A specific issue is occurring on tablets where users are adding themselves as duplicate entries.

We are requesting investigation into these device-specific issues and recommendations to effectively address the duplication issue.

**Comment by Prasad-MSFT** [comment]
Thank you for your inquiry! Could you please provide more details about your issue? Specifically, it would be helpful to know: 

- **Reproduction Steps:** What steps did you take leading up to the problem? 
- **Documentation Links**: Are there any specific guides or documentation you followed? 
- **Teams Client Version**: What version of the Teams client are you using? 
- **Code Snippets**: If applicable, please share any relevant code snippets. 

Providing this information will help us better understand your situation and assist you more effectively.
