### ISSUE TITLE
How to get the teams client version?

### ISSUE THREAD

**Issue by nbelyh** [OfficeDev/microsoft-teams-library-js#2648]
Is there a way I can get teams app version info programmatically?

There is "hostClientType" in the context, but it's very basic, like "desktop", "web" or "android".
I want exact version number. Is it possible to get it?

I want to get the numbers from the "About".

The reason is that I want to change behavior of the app depending on the version. New version of teams introduced a new UI to add app, that is very confusing for the users (before the default was to "add to a team" as a button, but in the latest version there is no such option. So I would like a hint to our application that is specific to the latest teams client version, and is shown only there.

**Comment by Meghana-MSFT** [comment]
@nbelyh - Currently it is not possible to retrieve the Microsoft Teams version using microsoft/teams-js. You can suggest this feature at [Microsoft Teams feedback Portal](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472).

**Comment by nbelyh** [comment]
Thank you, clear.
