### ISSUE TITLE
[Question] Is it possible to add additional navigation parameter to navigateToTab?

### ISSUE THREAD

**Issue by bajzat** [OfficeDev/microsoft-teams-library-js#265]
Hi!

I'd like to ask about the navigateToTab function. I have a personal app and a tab registered in MS Teams as a custom app. The tab app is an angular app and had multiple routes e.g: /welcome, /configuration, /summary, etc. .In the manifest file, the entry point of the tab is the /welcome. 

I would like to navigate from the personal app to the tab app, but not to the default entry point (/welcome) I want to navigate the user to the /configuration path. 

Is there any way to achieve it? Because the navigateToTab function only accept a TabInstance no additional parameter for navigation.

Thanks

Tamas

**Comment by Trinetra-MSFT** [comment]
Yes, You can deep link your tab to an entity. Please take a look at [Create deep links to content and features in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deep-links#deep-linking-to-your-tab) and let us know if you face any issue.

**Comment by bajzat** [comment]
Thanks! It worked.
