### ISSUE TITLE
The window.open will open that url twice in desktop client

### ISSUE THREAD

**Issue by RukaiYu** [OfficeDev/microsoft-teams-library-js#266]
Hi Team,

I added the settings page, which has a button to open a link via window.open. While it will open the page in the system browser twice.
```javascript
window.open('<page link>', '_blank');
```

This button's click event handler is binded to the teams PrimaryButton component library for React.

Does anyone know the reason?
Thanks.

**Comment by Trinetra-MSFT** [comment]
Could you please check if any external library is being used?

**Comment by RukaiYu** [comment]
> Could you please check if any external library is being used?

@Trinetra-MSFT 
We checked again, no other external libraries are used. This on happens in the desktop version of Teams. It works fine in the web browser.

**Comment by Gousia-MSFT** [comment]
@RukaiYu Are you still working on it? Looks like there is an issue with the UX Library which is being used. This has nothing to do with Teams client SDK library.

**Comment by Gousia-MSFT** [comment]
Please re-open if you still need any help.
