### ISSUE TITLE
Ambient const enums are not allowed when the '--isolatedModules' flag is provided

### ISSUE THREAD

**Issue by bansalrachita** [OfficeDev/microsoft-teams-library-js#267]
Trying to import enums throws an error when  '--isolatedModules' flag is provided for ts-lint config.

```
Error:(21, 52) TS2748: Cannot access ambient const enums when the '--isolatedModules' flag is provided.
```
/**
 * Indicates the various types of roles of a user in a team.
 */
export declare const enum UserTeamRole {
    Admin = 0,
    User = 1,
    Guest = 2
}

**Comment by bansalrachita** [comment]
The use case is utilizing the above roles from teams context in the app to validate that a user is an admin, user or a guest. And if nothing is provided passing on as a guest user. So, I'm trying to utilize the same enum defined in the teams client SDK to do the same but I'm not able to use it since I get the above error.

**Comment by sachingupta** [comment]
@bansalrachita, I am interested to know what are benefit you are getting using --isolatedModules true flag in your project? Can you use disabling this flag?

**Comment by bansalrachita** [comment]
@sachingupta Our project is using create-react-app that uses Babel for transpiling Typescript code into JS. During transpilation it strips off the types and doesn't do type-checking during transpilation. The flag provided by Typescript does a  pre-emptive check to make sure that the code transpiles correctly. Disabling the flag would surely disable these errors but the code will not be transpiled correctly through Babel during build.

**Comment by brycepolly** [comment]
+1 on this, so this can be used in react apps.

**Comment by anandvnath** [comment]
Useful references on why `const enum` does not work in some scenarios. 

I do not see an issue if we just import `enum` rather than `const enum`

https://ncjamieson.com/dont-export-const-enums/
https://github.com/microsoft/TypeScript/issues/5243
