### ISSUE TITLE
Proposal: Reject/avoid initialization in case you're out of Teams context

### ISSUE THREAD

**Issue by kharenzze** [OfficeDev/microsoft-teams-library-js#272]
### What I want

When `initialize` method is called and your app is not embedded in Teams, I would like to get notified that there's no way to initialize.

### Current behavior

There's no way to detect this situation, since `initialize` returns `undefined` and the callback passed as first arg is never called.

### Proposal

1.  Provide a public method `embeddedInTeams()`, so that we can easily detect we should initialize.
2. Modify `initialize` so that it returns a promise that's rejected in these circumstances.

I would go for #1, since IMO it's cleaner and reusable

### Context info

Our web app works both inside/outside Teams, and right now we detect the context in a tricky way. For sure you can provide us a more resilient method to handle this situation. 

Thanks,

prioritymatrix.com
Appfluence Inc

**Comment by Gousia-MSFT** [comment]
@kharenzze Thanks for reaching out. We have a feature request for this and we are working on it. But we do not have a firm timeline to share as of now.

**Comment by kharenzze** [comment]
Thank you. We'll keep an eye on the following releases. 
Is that feature tracked in another Github issue? I couldn't find it. It would be nice to follow it up and receive notifications.

[prioritymatrix.com](https://prioritymatrix.com)
[Appfluence Inc](https://appfluence.com)

**Comment by Gousia-MSFT** [comment]
We have raised a feature request for this and we are tracking it internally.

**Comment by wictorwilen** [comment]
@Gousia-MSFT  any updates on this? Six months has passed since you started to track it...

**Comment by ydogandjiev** [comment]
Hey @wictorwilen, do you have a suggestion on how this can be technically implemented? As you probably know Teams Apps are hosted by the Teams Clients using an iframe and the only communication mechanism available between them is [Window.postMessage()](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage). The `microsoftTeams.initialize` method sends a message from the hosted iframe to the parent window and waits for a response. Given that we recently added a callback to this API it is now possible to create your own simplistic `isInTeams` method:
```
function isInTeams() {
  return new Promise((resolve, reject) => {
    microsoftTeams.initialize(() => {
      resolve(true);
    });
    setTimeout(() => {
      resolve(false);
    }, 1000);
  });
}
```

Of course the problem with this approach is that when not hosted within Teams the `isInTeams` method will always take 1 second to return which is not an acceptable option in a lot of use cases. Therefore, the best option is for you to simply pass an explicit QSP to your pages when they are hosted within Teams. Whether creating a static tab, configurable tab, or a task module you are in control of the URL(s) that Teams uses to point to your website. Therefore, you can add an extra parameter to them (e.g. `&inTeams=true`) and check that to determine whether to enable Teams-specific functionality or not.

**Comment by kharenzze** [comment]
Those are exactly the workarounds we're using. We saw that office.js shows a message "Warning: Office.js is loaded outside of Office client", but I don't know exactly what they do to detect it. If you could do something similar, it would be really helpful.

I check https://github.com/OfficeDev/office-js/blob/release/dist/office.debug.js and it looks like they do the platform checking in 'getAppContext', but I can't see exactly what they do.

[prioritymatrix.com](https://prioritymatrix.com)
[Appfluence Inc](https://appfluence.com)
