### ISSUE TITLE
Teams desktop app crashes when using webcam stream

### ISSUE THREAD

**Issue by Titaye** [OfficeDev/microsoft-teams-library-js#273]
Desktop apps is randomly crashing when a tab is using webcam stream.
Here is a sample manifest adding a sample staticTab : https://gist.githubusercontent.com/Titaye/5abbc73e78414f7cdf8f24c3b7c509cc. 
The html page take the mediastream from getUserMedia browser API and displays it in a video tag.
Launch teams, stay on the static tab for 5 to 10 minutes and desktop app should kill itself.

**Comment by Wajeed-msft** [comment]
@Titaye - Thanks for reporting this. We have fixed this issue. We are working on rolling this to public builds.

**Comment by Titaye** [comment]
Perfect !
Any ideas of the time it will takes before the update ? We are waiting for this before sending an app for review.
And also is there an electron upgrade in the roadmap to have more controls on the video constraints ? 

Thanks

**Comment by ChetanSharma-msft** [comment]
Hello @Titaye - Hope you are doing well!!
Looks like these changes are rolled out.

Could you please check and confirm here?
