### ISSUE TITLE
refreshToken

### ISSUE THREAD

**Issue by viperfx** [OfficeDev/microsoft-teams-library-js#274]
The tokens we acquire from this library seems to be a single token that expires.

Is there a way to obtain a refresh token? 

Use case: Access user's calendar after SSO, and keep access to calendar via Graph API to be able to keep up to date with holidays

**Comment by ydogandjiev** [comment]
For security reasons all tokens generated client side via Implicit Grant are short-lived. To get a refresh token you can send the short-lived token you got from Teams to your backend and exchange it via AAD's OBO flow which will also provide you with a long-lived refresh token:
https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-oauth2-on-behalf-of-flow

Please make sure to transmit and cache these refresh tokens securely and never send them down to the client. You can read more about this here:
https://docs.microsoft.com/en-us/machine-learning-server/operationalize/how-to-manage-access-tokens#security-concerns
