### ISSUE TITLE
This call is not allowed in the 'authentication' context

### ISSUE THREAD

**Issue by shane99a** [OfficeDev/microsoft-teams-library-js#275]
What does this error mean? Our error tracking software keeps randomly logging this error for our application running in MS teams. No idea how to reproduce it. And the source code is not clear on what it means either.

```
Error: This call is not allowed in the 'authentication' context (Most recent call first)
File https://unpkg.com/@microsoft/teams-js@1.5.0/dist/MicrosoftTeams.min.js  line 1 col 5114 in Object.n.ensureInitialized
File https://unpkg.com/@microsoft/teams-js@1.5.0/dist/MicrosoftTeams.min.js  line 1 col 25290 in Object.e.authenticate
```

**Comment by Trinetra-MSFT** [comment]
Could you please tell us the scenario for which you are getting this error?

**Comment by shane99a** [comment]
It's happening with this app: https://appsource.microsoft.com/en-us/product/office/WA200000150?src=wnblogmar2018&tab=Overview, when you try to login in one of the tabs, like Dashboard.

**Comment by Trinetra-MSFT** [comment]
Could you please update your Teams client library to new version? Please take a look [Microsoft Teams JavaScript client SDK](https://docs.microsoft.com/en-us/javascript/api/overview/msteams-client?view=msteams-client-js-latest#installing-the-sdk).

**Comment by aosolis** [comment]
It means you're calling authenticate() to open an auth popup, but the page calling it is already in an auth popup.

**Comment by shane99a** [comment]
> It means you're calling authenticate() to open an auth popup, but the page calling it is already in an auth popup.

Ah I see, just wondering how do you determine a page is already in an auth popup.

**Comment by ydogandjiev** [comment]
@shane99a, you can typically determine if you are running in the auth popup simply based on your routes. For example, your auth flow would typically start at something like https://myapp.com/auth/begin and then end at https://myapp.com/auth/end. You would want to make sure that the code running on these begin and end pages wouldn't try to trigger a secondary auth flow itself.

Additionally, we recently exposed the `frameContext` parameter in the SDK context which will tell you if you are running in the auth popup. Here are all the possible frame contexts that your app could be loaded into:
```
// Ensure these declarations stay in sync with the framework.
export enum FrameContexts {
  settings = 'settings',
  content = 'content',
  authentication = 'authentication',
  remove = 'remove',
  task = 'task',
  sidePanel = 'sidePanel',
  stage = 'stage',
}
```

You could do something like:
```
microsoftTeams.initialize(() => {
  microsoftTeams.getContext(context => {
    if (context.frameContext === microsoftTeams.FrameContexts.authentication) {
      // In auth popup so show Authenticating... message with spinner
    } else {
      // Start loading content
     }
  });
});
```
