### ISSUE TITLE
[Question]/[Feature Request] Trigger shortcuts from client library

### ISSUE THREAD

**Issue by bajzat** [OfficeDev/microsoft-teams-library-js#276]
Hi!

I'd like to inquiry about shortcuts. Is it possible to trigger a shortcut (e.g Accept Call) from the JS library using a keyboard shortcut (alt + shift + A)? 

If not I'd like to you to consider it as a feature request. As a developer, I'd like to provide a user interface for my customer where the user can see data from my application and accept/decline the incoming call.

Thanks,

Tamas

**Comment by Trinetra-MSFT** [comment]
@bajzat , Teams do not support shortcuts for accept/decline call. We do not have any ETA to share as of now.

**Comment by bajzat** [comment]
Thank you for the quick answer.
