### ISSUE TITLE
authentication.notifySuccess does not trigger successCallback in Desktop app

### ISSUE THREAD

**Issue by Blackbaud-ChristiSchneider** [OfficeDev/microsoft-teams-library-js#277]
I am creating a Teams app with a tab that has a configuration page. My configuration page uses the `microsoftTeams.authentication.authenticate` function to open a sign in popup and set a `successCallback`. Everything works perfectly in the web app:

1. Choose to add the tab app to a channel
1. The config modal appears
1. Click the sign in button in the config, which opens a pop up
1. Sign in in the pop up, which closes the pop up and calls `successCallback` in the config modal
1. The config modal is authenticated and I can configure my app

When I run it in the desktop app, `notifySuccess` never triggers the `successCallback`. I am using a Mac and asked my coworker to test on a Windows computer.

What happens on Mac desktop app:

1. Choose to add the tab app to a channel
1. The config modal appears
1. Click the sign in button in the config, which opens a pop up
1. Sign in in the pop up, which redirects back to the page that calls `notifySuccess` and stays on that page (confirmed with dev tools), never closes pop up, never calls `successCallback` in the config modal

**Comment by Gousia-MSFT** [comment]
@Blackbaud-ChristiSchneider Are you seeing the issue only on Mac? Does that work fine on Windows?Could you please share your app manifest with us?

**Comment by Blackbaud-ChristiSchneider** [comment]
I only have a Mac so I could not test. I asked my coworker to test but he hasn't been able to do so yet.

Manifest:
```
{
    "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.5/MicrosoftTeams.schema.json",
    "manifestVersion": "1.5",
    "version": "1.0.0",
    "id": "c6a5d790-9097-4789-a1b6-1432a5504b70",
    "packageName": "com.microsoft.teams.library.js.277",
    "developer": {
        "name": "Blackbaud",
        "websiteUrl": "https://www.blackbaud.com",
        "privacyUrl": "https://www.blackbaud.com",
        "termsOfUseUrl": "https://www.blackbaud.com"
    },
    "icons": {
        "color": "favicon.png",
        "outline": "favicon.png"
    },
    "name": {
        "short": "microsoft-teams-library-js #277",
        "full": "microsoft-teams-library-js #277"
    },
    "description": {
        "short": "description",
        "full": "description"
    },
    "accentColor": "#FFFFFF",
    "configurableTabs": [
        {
            "configurationUrl": "https://host.nxt.blackbaud.com/ms-teams/config",
            "canUpdateConfiguration": true,
            "scopes": [
                "team"
            ]
        }
    ],
    "permissions": [
        "identity",
        "messageTeamMembers"
    ],
    "validDomains": [
        "host.nxt.blackbaud.com",
        "signin.blackbaud.com",
        "*.blackbaud.com"
    ]
}
```

**Comment by Blackbaud-ChristiSchneider** [comment]
If you watch the dev tools console with that configuration url, there's a log statement that will show when `notifySuccess` is called.

**Comment by Blackbaud-ChristiSchneider** [comment]
This also happens on Windows.

**Comment by Gousia-MSFT** [comment]
@Blackbaud-ChristiSchneider For [Authentication in tabs](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/auth-flow-tab) the login start page must be on the same domain as the post-login redirect page. Could you please confirm if that's the case for you?

**Comment by Blackbaud-ChristiSchneider** [comment]
Yes, they're on the same domain. You can use that `configurationUrl` from my manifest to test it and view the current url in the dev console.

**Comment by Gousia-MSFT** [comment]
@Blackbaud-ChristiSchneider  The Sign In start and end page are on a different sub domain. Could you please try adding redirecting back to same domain and then call notifySuccess()?
SignIn start:
![image](https://user-images.githubusercontent.com/45553518/66122778-33802200-e5fe-11e9-9729-20554c6dd254.png)
Signin end:
![image](https://user-images.githubusercontent.com/45553518/66122788-3ed34d80-e5fe-11e9-8d14-0bcce22a7ac1.png)

**Comment by Blackbaud-ChristiSchneider** [comment]
They're not - the start page is what is defined in the `configurationUrl` - https://host.nxt.blackbaud.com/ms-teams/config. That page has a button with a click action to call `microsoftTeams.authentication.authenticate` with a url of `https://signin.blackbaud.com/signin/`. Or does "start page" mean the `microsoftTeams.authentication.authenticate` `url` property?

**Comment by Gousia-MSFT** [comment]
Yes the start page is the url defined in `microsoftteams.authentication.authenticate`.

**Comment by Blackbaud-ChristiSchneider** [comment]
Alright, I can change that. Why does it work properly in the web app but not the desktop app?

**Comment by Gousia-MSFT** [comment]
In our Web Client (i.e. the browser), the authenticate call opens the popup window directly from within the iframe whereas in our Desktop Client the iframe just sends a message to the top-level Teams window which in turn handles the opening of the popup window. That changes both the way window.opener gets set within the popup window and the way messages posted back from the popup get validated. If the popup can't access its parent via window.opener or the messages sent back come from an unexpected origin then the notifySuccess/notifyFailure calls will essentially do nothing.

**Comment by Blackbaud-ChristiSchneider** [comment]
Is there no way to detect this and print a console error? I imagine this behavior leads to desktop-only issues in many cases - if someone is doing most of their development on web, which I imagine is quite common considering you can't log into multiple tenants in the desktop Teams app, they won't notice this issue until they test with desktop, if they even test. Then, if the issue is noticed prior to app submission, they may not know what the problem is (like me) and file a duplicate issue to this.

**Comment by Gousia-MSFT** [comment]
@Blackbaud-ChristiSchneider Currently we do not have any such method that checks for the platform and raise a console error. Thanks for sharing your thoughts. We will consider this.
