### ISSUE TITLE
Remove websiteUrl from inside tab itself

### ISSUE THREAD

**Issue by praneshrv96** [OfficeDev/microsoft-teams-library-js#279]
We need to remove the websiteUrl of the pinned tabs. So when the tab is accessed we called 
```
microsoftTeams.settings.getSettings(function(settings) {
	if(settings.websiteUrl) {
		microsoftTeams.settings.setSettings({
			websiteUrl: undefined
		});
	}
});
```
and
```
microsoftTeams.settings.getSettings(function(settings) {
	if(settings.websiteUrl) {
		settings.websiteUrl = undefined;
		microsoftTeams.settings.setSettings(settings);
	}
});
```

In both the cases, the tab is reloaded but the websiteUrl is not updated. Is removing the websiteUrl is supported?

**Comment by Trinetra-MSFT** [comment]
Could you please tell us what you are trying to do? Are you trying to update the existing `websiteUrl `to new one? If it is the scenario, you can set `canUpdateConfiguration `to `true `in your app manifest for configrableTabs. Please take a lake at [Updating an existing tab instance](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/tabs/tabs-update-remove#updating-an-existing-tab-instance).

**Comment by praneshrv96** [comment]
We need to hide our tab in the mobile client. Removing websiteUrl in the tab configuration hides it in mobile clients. So we are trying to update the tab configuration whenever the tab is visited (Trying to remove the websiteUrl from the content window itself).
Yes, it can be updated by updating the tab configuration in the config window but the users need to update every single tab they have saved earlier. So trying to update(remove the websiteUrl) from inside the content window.

**Comment by Trinetra-MSFT** [comment]
@praneshrv96 , Did you tried this [removal page example](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/tabs/tabs-update-remove#removal-page-example)?

**Comment by Trinetra-MSFT** [comment]
Please reopen, if you still facing issue..

**Comment by praneshrv96** [comment]
@Trinetra-MSFT , Sorry for the late response. I did try the removal page example. It works from config screen. What I am trying to achieve is **Remove websiteUrl of the tab from the content window**. Is there a way to do this?
