### ISSUE TITLE
Hide configurable tabs on mobile clients

### ISSUE THREAD

**Issue by praneshrv96** [OfficeDev/microsoft-teams-library-js#280]
According to this [doc](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/tabs/tabs-requirements#mobile-client-behavior), if we don't provide the 'websiteUrl' to the tabs, it won't be displayed in mobile clients. But my app is still getting displayed in mobile clients. I am using js sdk version 1.5.2.

Mobile client behavior mentioned in the doc:

> For group and channel (configurable) tabs, the mobile clients only show tabs that have a value for websiteUrl. If you want your tab to appear on the Teams mobile clients, you must set the value of websiteUrl.

**Comment by Josverl** [comment]
are you aware of the recommendation for [Tabs on mobile](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/design/tabs-mobile)

    When full support for tabs is released:  All tabs will always be available on mobile

To prepare for the update, you should follow the guidance for tabs on mobile when creating your tabs.

If your application cannot render a mobile tab, then you could use header sniffing to detect mobile , and display a message informing your users about that limitation.
