### ISSUE TITLE
Returns undefined passed value via event type signin/verifyState

### ISSUE THREAD

**Issue by tmhao2005** [OfficeDev/microsoft-teams-library-js#283]
After having called `notifySuccess` with specific values, I received nothing then which covers in event `signin/verifyState` in BOT. 

This problem is just happened on MSTeams app on **Android** device only (OS v8.0). 

Can anyone have a look?

**Comment by Trinetra-MSFT** [comment]
Could you please share some more information or some piece of code?

**Comment by tmhao2005** [comment]
hey @Trinetra-MSFT 

I figured out the value was `string` transferred instead of `object` as set earlier (happened only on Android).

```typescript
if (context.activity.name === "signin/verifyState") {
  const value = await this.authStateAccessor.get(context);
  const { state } = context.activity.value;

  // Unlike others, On Android `state` is string
}
```

**Comment by Gousia-MSFT** [comment]
@tmhao2005 Were you able to solve the issue? Is there anything else you need help on?

**Comment by Gousia-MSFT** [comment]
Please re-open if you still face any issues.
