### ISSUE TITLE
[Feature request] Onedrive file picker

### ISSUE THREAD

**Issue by abdulkareemnalband** [OfficeDev/microsoft-teams-library-js#284]
Provide API to pick onedrive file in tab addin. like https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/?view=odsp-graph-online
Possible API could be

```ts
interface PickOptions{

}
interface PickResult{
  status:success|failed|cancelled;
  value:{
    id:string;
    driveId:string;
    name:string;
    webUrl:string;
 }
 name:string;
 error:any;
}

function pickOnedrive(options:PickOptions , callback:(result:PickerResult) => void);
```

### Rationale
In our addin we need to store references to user picked files from onedrive/sharepoint

**Comment by Trinetra-MSFT** [comment]
@abdulkareemnalband, Thanks for your valuable suggestion. Please feel free to reopen this.
