### ISSUE TITLE
authentication.notifySuccess does not trigger successCallback on mobile

### ISSUE THREAD

**Issue by Noja13it** [OfficeDev/microsoft-teams-library-js#287]
We are implementing the tab authentication flow in our application. Web, and Desktop work as expected.

On mobile, `authenticaton.authenticate` triggers the Microsoft sign in 'popup' to open in what I assume is a webview. After the user signs in with their microsoft account, the 'popup' closes, but `successCallback` is not triggered. As a result the login flow can not be completed, and the user is stuck on the login screen.

We are using version 1.5.2

EDIT: put the wrong version number.

**Comment by Trinetra-MSFT** [comment]
Is you start page `authenticate `url and end page `notifySuccess `call url is in the same domain?

**Comment by Noja13it** [comment]
@Trinetra-MSFT

Yes. They are both on the same domain.

**Comment by Trinetra-MSFT** [comment]
Which version you are using for Teams mobile client, is it above than 1.4?

**Comment by Noja13it** [comment]
@Trinetra-MSFT 

We are using the latest version available on the Google Play Store.
Version: 1416/1.0.0.2019101801

**Comment by Gousia-MSFT** [comment]
@Noja13it Thanks for reaching out. This is a known issue. We have a bug on this and we are working on fixing this.

**Comment by arpitgupta19** [comment]
@Noja13it Please confirm if this issue is happening on both android and iOS ?

**Comment by Noja13it** [comment]
@arpitgupta19 

After having done some tests, there appear to be a separate issue on iOS.

On iOS, `successCalllback` is triggered, however, there appear to be an issue in the parsing of the result sent from `notifySuccess`. Unlike in the desktop client where we receive the result as an object:
```
{
     accessToken: '<token>',
     expiresIn: '3599',
     tokenType: 'Bearer'
}
```
On iOS we receive a string: 
`'{\n    accessToken = "<token>";\n    expiresIn = 3599;\n    tokenType = Bearer;\n}'`

I am assuming this is not intended behaviour?

**Comment by kevin-brouder** [comment]
I can confirm this is an issue with Android using the latest sdk (1.5.2) and latest Teams app from Google Play store. It appears the successCallBack never fires, however, it seems to get past that point as the "auth window" that is calling it does close.

**Comment by Trinetra-MSFT** [comment]
We have a bug for this, we are tracking this internally, once it is fixed we will let you know. Closing this issue feel free to reopen it.

**Comment by arpitgupta19** [comment]
@Noja13it 
Do you need the full dictionary object or just the accessToken string is enough ?
