### ISSUE TITLE
Debug WebView in android

### ISSUE THREAD

**Issue by abdulkareemnalband** [OfficeDev/microsoft-teams-library-js#289]
We are developing an addin for Microsoft Teams, and we want debug our addin from android devices.
Please enable Web view debugging<sup>[1]</sup> by calling `WebView.setWebContentsDebuggingEnabled(true)`

you can do this in stock android app with **developer preview** mode as desktop application or provide separate app for developers

[1]: https://developers.google.com/web/tools/chrome-devtools/remote-debugging/webviews#configure_webviews_for_debugging

**Comment by Gousia-MSFT** [comment]
@abdulkareemnalband Could you please try [Accessing DevTools from an Android client](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/developer-tools#accessing-devtools-from-an-android-client) to allow WebView debugging for android.

**Comment by abdulkareemnalband** [comment]
@Gousia-MSFT thanks
 I didn't kew that
All I needed to do was enable developer preview

1. goto menu ☰ 
2. settings
3. select About
4. switch Developer Preview
