### ISSUE TITLE
Bug: Spelling checker is not working in teams tab

### ISSUE THREAD

**Issue by abdulkareemnalband** [OfficeDev/microsoft-teams-library-js#293]
[Spell check] is not working in Windows Microsoft Teams App teams tab

It work fine when tab is open in web version of teams app

## Steps to reproduce
1. Add `textarea`/`contenteditable` to tab 
2. set attribute `spellcheck="true"` on `textarea`/`contenteditable`
3. Type some word spelled wrong in `textarea`/`contenteditable` (i.e. adn instead of and)
4. Red squiggle is not shown

[Spell check]:https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/spellcheck

**Comment by Abhijit-MSFT** [comment]
@abdulkareemnalband - We have filed a bug and tracking it internally.

**Comment by ShadowXVII** [comment]
Where is this bug tracking @Abhijit-MSFT ?

The bug has been reported here also:
https://microsoftteams.uservoice.com/forums/908686-bug-reports/suggestions/40333423-bug-spell-check-does-not-work-on-app-or-personal
