### ISSUE TITLE
Authentication dialog cookie is not sent on login flow callback

### ISSUE THREAD

**Issue by abdulkareemnalband** [OfficeDev/microsoft-teams-library-js#296]
We are using azure ad open Id connect to authenticate users,
In Microsoft teams windows app,When our login callback (POST request) is called from login flow, request is missing open Id nounce cookie.
when cookie has `samesite` policy set in it.

following cookie does not work
```
Set-Cookie: .AspNetCore.Correlation.OpenIdConnect.T41tbNDInNzFy0doamyj0aiBTdTTE5M4dnguI0_ZsuY=N; expires=Tue, 10 Dec 2019 09:48:00 GMT; path=/signin-oidc; secure; samesite=none; httponly
```

following cookie works
```
Set-Cookie: .AspNetCore.Correlation.OpenIdConnect.T41tbNDInNzFy0doamyj0aiBTdTTE5M4dnguI0_ZsuY=N; expires=Tue, 10 Dec 2019 09:48:00 GMT; path=/signin-oidc; secure;  httponly
```

But When same login flow is done in web app for teams, It works

**Comment by Trinetra-MSFT** [comment]
@abdulkareemnalband , Could you please share some piece of code what you are trying or error logs so we can see the issue?

**Comment by abdulkareemnalband** [comment]
Fixed issue,
It was because of chrome 66 of teams application  not implementing `samesite:none`
Now we set those properties based on incoming request user agent
