### ISSUE TITLE
Run app in background

### ISSUE THREAD

**Issue by shaharmor** [OfficeDev/microsoft-teams-library-js#298]
Hi,

Is it possible to run a Teams app in the background without forcing users to interact with it?

**Comment by code0007** [comment]
@shaharmor , Are you trying to run Teams in background without any user interaction or is it about any custom teams app? Could you please clarify?

**Comment by Trinetra-MSFT** [comment]
@shaharmor , Are you trying to set Microsoft Teams application to run in background without any user interaction or is it about any custom teams app? Could you please clarify?

**Comment by shaharmor** [comment]
I want an admin to be able to run a custom app in the background (as a
hidden iframe for example) for its users.

The Teams app itself will be in the foreground, but the custom app will be
in the background.

If possible to trigger such an app remotely it would be best

**Comment by Trinetra-MSFT** [comment]
@shaharmor , When you sideload any custom teams app within Teams, the tab (HTML) will be shown only but the actual service will be running in background on your server where the app is hosted (example Azure/Sharepoint). Could you please clarify what you want to achieve? Are you looking for updating the Tab data without user interaction while service is running in background?

**Comment by shaharmor** [comment]
Hey @Trinetra-MSFT ,

I understand the separation between the service (Which is hosted on my servers), and the Teams app (Which is running on end-users devices).

My goal is to be able to have either a:

1. Constantly running hidden `iframe` in every end-user Teams app (Only desktop is fine)

1. An way for an administrator to remotely trigger end-users Teams apps to open a specific `iframe` (Preferably hidden).

We would like to use end-users already-open Teams app to run background tests of some of our internal apps (Websites).

**Comment by ydogandjiev** [comment]
Hi @shaharmor, we don't currently have support for what you are describing but it's something that's on our radar and we might look at implementing in the future. I will pass your feedback on to our PMs.

In the meantime, you could try using push notifications to trigger a service worker to run on the device though this will require users to open the app at least once and grant it permissions to push notifications. There is a detailed guide on how to implement push notifications in JavaScript here:
https://blog.sessionstack.com/how-javascript-works-the-mechanics-of-web-push-notifications-290176c5c55d

**Comment by shaharmor** [comment]
Hey @ydogandjiev 

Thanks for the feedback, however it is not helpful as we need access to some Web APIs that don't exist on Service Workers.

Is there any way I can track progress on that feature that you mentioned?

**Comment by mwerghemmi** [comment]
Hi @shaharmor , @Trinetra-MSFT , 

I am  having a very similar need: My tab app need to execute a deep link when an event accures in the Backend.  
this works fine when the tab is open tab receive the event fron backend) and executes the deeplink. 
The issue is, when usr let say is catting, meaning the tab is not open, the notification from backend is not received and the deppl link is not executed. 
Any hints here ?  
As general question, when a tab is not active (user is ussing another Teans service, lets say calling) can the tab javsscipt code executed? 
Many th

**Comment by Trinetra-MSFT** [comment]
This is not supported yet. Please feel free to reopen if you any query

**Comment by guypaskar** [comment]
@Trinetra-MSFT , @ydogandjiev  said in the past " it's something that's on our radar". Has anything progressed with that over the past year?
