### ISSUE TITLE
Initialize tab config form with saved app specific settings

### ISSUE THREAD

**Issue by synth** [OfficeDev/microsoft-teams-library-js#302]
Given: A user is configuring a tab and the application has several application specific settings to configure the presentation and data shown on the tab. 
Expected: Anytime the user visits the tab config form, all of those app specific settings are preselected. 

What is the best practice for persisting those app specific settings? It seems the settings and context interfaces (As described here: https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context) only persist or allow a predefined teams specific list of attributes. 

We are implementing this by issuing an ajax request to our servers in the `saveHandler` that is registered via `microsoftTeams.settings.registerOnSaveHandler(saveHandler)`. It is in the success callback of this ajax request that we call `notifySuccess`. 

Is this the correct practice? I couldn't find examples of more involved tab config pages that involve additional app specific settings.  If there is a way to use the Microsoft SDK, please let me know.

**Comment by synth** [comment]
@Trinetra-MSFT Yes, I have followed this page. However, there is no mention of application specific settings. What we have done is implement an AJAX handler to first save those settings to our database, and if there are no errors or validation issues, then we call the notifySuccess handler in the success callback of the AJAX request. 

This seems to work, but just wanted to make sure that's the best practice. It would be good to perhaps add that into the example as I'm sure saving app specific settings is a common case.

**Comment by Trinetra-MSFT** [comment]
@synth Currently there is no other way to specify settings as a common base.

**Comment by ydogandjiev** [comment]
@synth, the approach you have pursued is the correct one. Teams only allows you to save pointers into your service (e.g. `entityId`, `contentUrl`, etc.). Your own application's data should be stored in your database of choice and referenced via the tab's `entityId` and/or QSPs you add to the `contentUrl`.

**Comment by synth** [comment]
@Trinetra-MSFT @ydogandjiev Thank you! Yes, makes sense for you to give us pointer and we save in our db. I just wanted to confirm this since the documentation doesn't specify. Cheers.
