### ISSUE TITLE
setValidityState doesn't work correctly on tab removal page

### ISSUE THREAD

**Issue by synth** [OfficeDev/microsoft-teams-library-js#303]
Given: a removeUrl is set with `setSettings` and the user clicks "Remove" from the tab menu
Expected: The Remove form button is not activated until `setValidityState(true)` is called
Actual: The Remove form button is activated after a timeout no matter what. Subsequent calls to `setValidityState(false)` do not deactivate the form button

I tested using the example code here: https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page

My specific code, I am using older js, not es6, but that shouldn't affect anything: 

```html
<html>
<head>
  <script src= 'https://statics.teams.cdn.office.net/sdk/v1.5.2/js/MicrosoftTeams.min.js'></script>
</head>
<body>
  <button onclick="onClick()">Delete this tab and all underlying data?</button>
  <script>
    microsoftTeams.initialize();
    microsoftTeams.settings.registerOnRemoveHandler(function(removeEvent) {
      // Here you can designate the tab content to be removed and/or archived.
        microsoftTeams.settings.getSettings(function(settings) {
        });
        removeEvent.notifySuccess();
    });

    function onClick() {
        microsoftTeams.settings.setValidityState(true);
    }
  </script>
</body>
</html>
```

**Comment by Trinetra-MSFT** [comment]
@synth , When a user selects Remove from the tab's drop-down menu, Teams will load the optional removeUrl page (designated in your configuration page) into an IFrame. Here, the user is presented with a button loaded with the onClick() function that calls microsoftTeams.settings.setValidityState(true) and enables the Remove button located near the bottom of the removal page IFrame. Please try to set contentUrl within setSettings.

**Comment by synth** [comment]
Hi @Trinetra-MSFT Thx for response.  

> Teams enables the Remove button after 5 seconds, even if your tab hasn't called setValidityState().

This is very strange. 5 seconds is a very short time. What's the point of having app's call setValidityState if it will have no effect after 5 seconds?

I get that you probably want to allow end users to remove Tab regardless of app logic (like in case of app error). However, I feel either: 
1. That there should be an alternative mechanism for end user to hard remove tab
2. Or, the documentation should not recommend app developers to call `setValidityState` as its confusing and has no ultimate effect. 
3. Or, There should be a longer timeout to enable the remove button. 

Thx for your consideration

**Comment by Trinetra-MSFT** [comment]
@synth , What do you mean by removal of app logic? Below piece of code helps to remove the entire tab and all data which is configured in a channel.

   ```
 microsoftTeams.settings.registerOnRemoveHandler((removeEvent) => {
      // Here you can designate the tab content to be removed and/or archived.
        microsoftTeams.settings.getSettings((settings) => {
        settings.contentUrl = "..."
        });
        removeEvent.notifySuccess();
    });
```
Btw Teams will load the optional removeUrl page (designated in your configuration page) into an IFrame. when setValidityState is set to true it will enable remove button as configuration page loads. but if you have not enabled the setValidityState it will take some time for sure as mentioned in the document.  

Currently this is the only way to remove a tab from channel.

**Comment by synth** [comment]
@Trinetra-MSFT I'm referring to this: 
<img width="1425" alt="Screen Shot 2020-01-22 at 11 56 15 AM" src="https://user-images.githubusercontent.com/10546/72929186-3a968180-3d0e-11ea-986c-0d2a7f63b099.png">

A user clicks "Manage Team", then clicks "Apps", then deletes the App. This causes (correctly) all the tabs to be removed from the team. However, the tab removal logic is not called during this flow.

**Comment by ydogandjiev** [comment]
@synth, removing an app doesn’t actually cause all the tabs to be removed. They are simply hidden and get re-shown if/when the app is installed into the team again.

**Comment by synth** [comment]
Thanks for letting us know this. Is there documentation on this? Seems problematic. Companies will expect that uninstalling an app hard deletes all data. Imagine one user adds the app and installs several tabs. That user ends up leaving the org and the app is subsequently uninstalled. Then another user later installs the app...then all of the previous tabs are restored unbeknownst to the current user. In a team with a lot of channels, it would be near impossible to manage - let alone the compliance issues with the 3rd party app holding onto data it shouldn't (if the app is uninstalled).

There should be a full app uninstall hook that notifies the app to clean up all of its component references and data.

**Comment by ydogandjiev** [comment]
@synth, thank you for the feedback. We are aware of the asks for an app/tab removal hook and is something we will be looking into. It’s important to keep in mind that tabs in and of themselves do not store any data; they are just pointers to external sites which store the data (not that different from contextually relevant bookmarks). Data access, compliance, and retention policies need to be handled by the external site. You should not be relying on Teams to do that for you.

**Comment by synth** [comment]
Thanks @ydogandjiev. It's good to know an app removal hook is on your radar. It's true the tab itself doesn't store any data, and it's us, as third parties, that are storing data. This is precisely the reason for a need for an app removal hook. In other words, the app removal hook can help 3rd parties to clean out data that should no longer be stored which follows international compliance guidelines (eu, au, us, etc).

**Comment by Meghana-MSFT** [comment]
Can you please help by suggesting this feature on [Microsoft Feedback portal](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472).

**Comment by synth** [comment]
@Meghana-MSFT This seems like a bug not a feature request, which is why I posted here.

**Comment by Meghana-MSFT** [comment]
Engineering team has considered this as a feature request.

**Comment by synth** [comment]
Hmm, the issue described here follows Microsoft's own documentation which does not work as described. I'm unclear how that is a feature request - the documentation itself describes it as an existing feature...

**Comment by ydogandjiev** [comment]
The behavior described in this issue is currently by design. We do not want to allow app developers to intentionally or accidentally block users from being able to delete their tabs. That is why we automatically enable the "Remove" button after 5 seconds and allow the user to force delete the tab.

**Comment by synth** [comment]
@ydogandjiev If this is true, then the purpose of `setValidityState` should be clarified in the documentation. 

1. The button is activated regardless of calling the function, so its optional 
2. There is no utility to the argument (`true`) to the function, as false doesn't do anything.
