### ISSUE TITLE
Desktop Notifications do not display until user clicks into Teams App

### ISSUE THREAD

**Issue by SnazzySnail8** [OfficeDev/microsoft-teams-library-js#308]
I have not been receiving desktop notifications until I click into the Teams app; then they appear to pop up all at once.

**Comment by Abhijit-MSFT** [comment]
There is a possibility that you have dismiss the notifications. You receive below (image) notification when you sing in to Teams. Can you try turning on the notifications by signing out and signing back in.

![image](https://user-images.githubusercontent.com/48427340/73242283-978cae80-41ca-11ea-954c-c48eab3fa7dd.png)
