### ISSUE TITLE
The close flow is broken when opening Calendar invite DeepLink in a task module in adaptive card.

### ISSUE THREAD

**Issue by kafka-yu** [OfficeDev/microsoft-teams-library-js#309]
Hi Team,

We found an issue that:
1. I have a customized html page, and have a button to open a calendar deeplink: e.g. 
```javascript
 microsoftTeams.executeDeepLink('https://teams.microsoft.com/l/meeting/new?subject=test%20subject&attendees=joe@contoso.com,bob@contoso.com&startTime=10%2F24%2F2018%2010%3A30%3A00&endTime=10%2F24%2F2018%2010%3A30%3A00&content=test%3Acontent', (s , r) => {
      alert(s + '\r\n' + r);
    });
```
2. Then I open this page via the task module from message extension.
```json
{
      task: {
        "type": "continue",
        "value": {
          "title": "Task module title",
          "height": 500,
          "width": "medium",
          "url": "<my page url of the form>/index.html",
        }
      }
   }
```
3. I can see this page open in a dialog box. And I can open the deeplink to see the Teams calendar invite window.
4. When I click the "Close" button, it lets me to choose "Discard changes" or not.
![image](https://user-images.githubusercontent.com/3942409/74104275-0df7bc00-4b8e-11ea-9940-0669dcb76695.png)

I choose "Discard Changes".

5. Nothing happens.

Seems a bug there? I open the page in Tab, and open the calendar invite, I can see "Discard Changes" working.

Thanks.

**Comment by Subhasish-msft** [comment]
@kafka-yu , How are you executing the calendar deeplink in the html page? Is there a button in html page on click of which you are executing deeplink Or On page render it self you are executing deeplink. 
I tried out the way you have mentioned above and it is working fine for me. So just need some conformation.

**Comment by Gousia-MSFT** [comment]
Please re-open if you are still facing the issue.
