### ISSUE TITLE
is there any API to detect running in Teams or not?

### ISSUE THREAD

**Issue by NewFuture** [OfficeDev/microsoft-teams-library-js#310]
When an APP can be run in both teams Tab and pure Browser (without web teams), but display different tips.
How to detect that it is running in Teams or not?

**Comment by Gousia-MSFT** [comment]
@NewFuture You can use the [Teams javascript client SDK](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/using-teams-client-sdk) to determine whether a particular web page is running inside Teams or pure browser. Please try [getting context](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context) for tab in Teams.

**Comment by NewFuture** [comment]
@Gousia-MSFT  thank you,
```js
teams.getContext(callback)
```
It will never call the callback in the pure browser.
it means the status is `pending`. How to confirm its status?

**Comment by Gousia-MSFT** [comment]
@NewFuture microsoftTeams.getContext() works only inside teams tab and returns null on a pure browser. Could you please try this out and see the experience in the browser?

**Comment by NewFuture** [comment]
@Gousia-MSFT 
No, It will not call the callback in the pure browser. (it's always waiting without any return )

**Comment by NewFuture** [comment]
#156

**Comment by Gousia-MSFT** [comment]
@NewFuture Do you find the solution feasible? Is there anything else you need help on?

**Comment by NewFuture** [comment]
@Gousia-MSFT not yet.
It's better to provide this feature in Teams client SDK.

**Comment by Gousia-MSFT** [comment]
@NewFuture Thanks for your feedback. We will definitely consider this.

**Comment by amrlafi** [comment]
Hacky solution for now:

    var teamsInitialized = false;
    microsoftTeams.initialize(() => {
      teamsInitialized = true;
    });

    setTimeout(() => {
       if(teamsInitialized) {
        // teams running
       } else {
        // otherwise
       }
    }, 1000);'
