### ISSUE TITLE
Bug:Scheduling dialog does not close when used from tab and channel is selected

### ISSUE THREAD

**Issue by abdulkareemnalband** [OfficeDev/microsoft-teams-library-js#311]
[Scheduling dialog](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links#linking-to-the-scheduling-dialog) does not close when opened from tab

```ts
teams.executeDeepLink('https://teams.microsoft.com/l/meeting/new');
```

Also when After click on `schedule ` button teams opens `posts` tab instead of staying in same tab

**Comment by Gousia-MSFT** [comment]
@abdulkareemnalband - I could not repro the issue you have mentioned. When opened from tab, the deeplink to scheduling dialog closes as expected on close and on schedule opens up the same tab. Could you please share some piece of code you are trying?

**Comment by abdulkareemnalband** [comment]
@Gousia-MSFT The repro steps are
Environment : Windows 10 teams client
1. Open scheduling dialog from a tab by executing `teams.executeDeepLink('https://teams.microsoft.com/l/meeting/new');`
1. In Schedule dialog select a channel
1. Click on `Schedule`
1. Now meeting is scheduled but dialog does not close

**Comment by Gousia-MSFT** [comment]
@abdulkareemnalband We could not repro the issue you have mentioned. Could you please share a video recording of the issue?

**Comment by abdulkareemnalband** [comment]
@Gousia-MSFT now it is working
But there is new issue,that is after meeting is scheduled tab gets reloaded
I will open new issue for that

**Comment by abdulkareemnalband** [comment]
#312 is created for other issue
