### ISSUE TITLE
Bug: Tab gets reloaded after Scheduling dialog is closed

### ISSUE THREAD

**Issue by abdulkareemnalband** [OfficeDev/microsoft-teams-library-js#312]
After closing [Scheduling dialog](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links#linking-to-the-scheduling-dialog) tab from which it was opened gets reloaded

```ts
teams.executeDeepLink('https://teams.microsoft.com/l/meeting/new');
```

**Comment by Gousia-MSFT** [comment]
@abdulkareemnalband When you switch back after creating the meeting the tab gets reloaded. This is the expected behaviour. Are you facing any issues here?

**Comment by abdulkareemnalband** [comment]
@Gousia-MSFT The main issue is that we loose all state when we get back to tab.
My expectation was that it will work same as a [task module](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/what-are-task-modules), that when closed it keeps tab as it is

If you thing it not valid scenario please close this task

**Comment by Gousia-MSFT** [comment]
@abdulkareemnalband Currently when you switch back to a tab after clicking somewhere else, it does not store any state. Teams does not keep the state of the tab when you click on something else. It actually refreshes the tab when you re-visit it.
