### ISSUE TITLE
popup blocked, app submission failed

### ISSUE THREAD

**Issue by Venipa** [OfficeDev/microsoft-teams-library-js#314]
our team tried to submit a app which got denied due to the popup which gets created upon authentication.
the support for the app submission still denies the app after explaining this issue, tho' it works on other users.
is there any solution for this?

regards

**Comment by Wajeed-msft** [comment]
Are you opening login prompt without user clicking on Login Button? Most of the browsers block such pop-ups. Solution would be to create show Sign In button and let user initiate the pop-up. Please take a look at [teams-sample-auth-node](https://github.com/OfficeDev/microsoft-teams-sample-auth-node/tree/master/src/views/tab/silent) code and [Auth Bot](https://github.com/OfficeDev/microsoft-teams-sample-auth-node/blob/master/manifest/AuthBot.zip) manifest to see the experience.

**Comment by Venipa** [comment]
yes according to the docs we did not include any user interaction before opening the popup since it was not stated there.
i guess adding that to the docs may help or referencing a issue about that.

we'll be implementing such manual authentication,
thanks tho :)
