### ISSUE TITLE
Task Module window is not able to close when using tasks.submitTask();

### ISSUE THREAD

**Issue by kafka-yu** [OfficeDev/microsoft-teams-library-js#315]
Hi There,

We load a custome task module dialog box from message extension, sample code:
```json
{
   url: 'https://our-teams-app-domain.com',
...
}
```

And now the popup loaded. We have a button in the page, clicks it, which will call:
```javascript
microsoftTeams.tasks.submitTask();
```
We want to use this way to close the popup as the docs suggested. https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/task-modules-bots#submitting-the-result-of-a-task-module

But seems sometimes it won't close the popup?

JS SDK Version: 1.4.3
We would try the latest version 1.6.0 next.

**Comment by Trinetra-MSFT** [comment]
@kafka-yu , Could you please try to close the task module pop up in submit Handler? 
```
`microsoftTeams.initialize();
    submitHandler = (err, result) => {
        if (result.action == "some_text") {
            microsoftTeams.tasks.submitTask();
        }
        };`
```

**Comment by Trinetra-MSFT** [comment]
@kafka-yu , Are you still having this issue?

**Comment by Gousia-MSFT** [comment]
Please re-open if you are still facing any issues.

**Comment by sgsmittal226** [comment]
Hi @Gousia-MSFT I am getting similar issue.

I tried even to close using dom.

let element: HTMLElement =  window.parent.document.getElementsByClassName("ngdialog-close")[0] as HTMLElement;
element.click();

but then I am facing domexception to 

DOMException: Blocked a frame with origin "https://demo.xyz.io" from accessing a cross-origin frame.
    at https://demo.xyz.io/team/web/scripts/client.js

**Comment by ydogandjiev** [comment]
@kafka-yu, if you are opening the task module from bot or messaging extension then you must ensure that your backend service handles and responds to the task/submit message. Ultimately, it's your bot that drives the lifetime of the task module in this case. You can read more about that here:
https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/task-modules-bots

@sgsmittal226, the `microsoftTeams.tasks.submitTask()` API needs to be called from the page loaded within the task module (i.e. the one loaded from the `url` in your `taskModuleInfo` object). In your example it looks like you are trying to call it from within the page that opens the task module it which is not supported.
