### ISSUE TITLE
Can't save a connector.. (from dev environment OK from production KO)

### ISSUE THREAD

**Issue by vbarrier** [OfficeDev/microsoft-teams-library-js#317]
I made a custom connector for teams that display notifications on channels and add Tab on teams.

For the tab parts -> Everything is working well

But I have a problem for the connector parts, I get an error when I try to save my settings in the developer console:

```angular.min.js:113 2020-03-25T20:35:25.953Z Received error from connectors {"seq":1585168484680,"timestamp":1585168525943,"flightSettings":{"Name":"ConnectorFrontEndSettings","AriaSDKToken":"d127f72a3abd41c9b9dd94faca947689-d58285e6-3a68-4cab-a458-37b9d9761d35-7033","SPAEnabled":true,"ClassificationFilterEnabled":true,"ClientRoutingEnabled":true,"EnableYammerGroupOption":true,"EnableFadeMessage":false,"EnableDomainBasedOwaConnectorList":false,"EnableDomainBasedTeamsConnectorList":false,"DevPortalSPAEnabled":true,"ShowHomeNavigationButtonOnConfigurationPage":false,"DisableConnectToO365InlineDeleteFeedbackPage":true},"status":500,"clientType":"SkypeSpaces","connectorType":"f00d8890-daa8-4c87-89f5-83cbab0bccd4","name":"handleMessageError"}```

-> registerOnSaveHandler is called -> setSettings is correctly set with entityId, contentUrl (same configurationUrl as the connector configuration) and the configName. getSettings -> is called to save to my app the webhook url -> it works -> notifySuccess is then called and

I checked on the connector dashboard everything seems fine, on the App Studio everything is green also!

I don't know what is happening..

My code: 

```microsoftTeams.settings.registerOnSaveHandler(function(saveEvent) {
        microsoftTeams.settings.setSettings({
            entityId: 'icescrum-pkey-' + $scope.settings.project.pkey,
            contentUrl: isSettings.serverUrl + '/msTeams/setup/',
            configName: $scope.settings.project.name
        });
        microsoftTeams.settings.getSettings(function(settings) {
            $scope.settings.webhookUrl = settings.webhookUrl;
            return FormService.httpPost('msTeams/save', $scope.settings, true).then(function() {
                saveEvent.notifySuccess(); //wait that the settings are really saved on iceScrum side
            });
        });
    });
    microsoftTeams.settings.getSettings(function(settings) {
        $scope.setup = !settings.configName;
        var tokenData = JSON.parse(localStorage.getItem("msTeams-oauth"));
        var userData = JSON.parse(localStorage.getItem("msTeams-user"));
        if (tokenData) {
            FormService.httpGet('ws/project/user/' + userData.id + '?light=true', {headers: {'Authorization': 'Bearer ' + tokenData['accessToken']}}, true).then(function(projects) {
                $scope.projects = projects;
                if (settings.entityId) {
                    $scope.settings.project = _.find($scope.projects, {pkey: settings.entityId.split('icescrum-pkey-')[1]});
                }
                $scope.ready = true;
            });
        }
    });
```

My manifest: 

```{
"$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.5/MicrosoftTeams.schema.json",
"manifestVersion": "1.5",
"version": "1.0.0",
"id": "ca153ede-92f2-46e7-8695-3726b5343bf4",
"packageName": "com.kagilum.icescrum",
"developer": {
    "name": "Kagilum SAS",
    "websiteUrl": "https://www.icescrum.com",
    "privacyUrl": "https://www.icescrum.com/privacy",
    "termsOfUseUrl": "https://www.icescrum.com/termsofuser"
},
"icons": {
    "color": "color.png",
    "outline": "outline.png"
},
"name": {
    "short": "iceScrum",
    "full": "Connect with iceScrum"
},
"description": {
    "short": "A true Agile project management tool",
    "full": "iceScrum is a web application for using Scrum while keeping the spirit of a collaborative workspace. It also offers virtual boards with post-its for sprint backlog, product backlog and others."
},
"accentColor": "#FFFFFF",
"configurableTabs": [
    {
        "configurationUrl": "https://preview.icescrum.com/msTeams/setupTab/",
        "canUpdateConfiguration": true,
        "scopes": [
            "team",
            "groupchat"
        ],
        "supportedSharePointHosts": [
            "sharePointFullPage",
            "sharePointWebPart"
        ]
    }
],
"connectors": [
    {
        "connectorId": "f00d8890-daa8-4c87-89f5-83cbab0bccd4",
        "configurationUrl": "https://preview.icescrum.com/msTeams/setup/",
        "scopes": [
            "team"
        ]
    }
],
"permissions": [
    "identity",
    "messageTeamMembers"
],
"validDomains": [
    "preview.icescrum.com"
]```

**Comment by Trinetra-MSFT** [comment]
@vbarrier, Could you please confirm  getSetting and setSettings is implemented within registerOnSaveHandler and you have implemented registerOnremoveHandler() correctly?
```
microsoftTeams.settings.registerOnRemoveHandler(function (removeEvent) {
    var removeCalled = true;
removeEvent.notifySuccess();
});
```

**Comment by vbarrier** [comment]
Hello thank you for your reply. getSettings & SetSettings are well implemented : it works using dev environment and ngrok. 

I don't have the microsoftTeams.settings.registerOnRemoveHandler is it mandatory?

**Comment by Trinetra-MSFT** [comment]
@vbarrier , If your issue persist on production meanwhile could you please check your connector status in connector developer dashboard? No it's not mandatory but you need to implement when you want to [modify or remove](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/removal-page).

**Comment by vbarrier** [comment]
I have added removeEvent management: 

On the dashboard connector status I have: 

```Registered
Pending Approval```

**Comment by vbarrier** [comment]
It still doesn't work

**Comment by ydogandjiev** [comment]
@pradeepananth, any idea what might be causing the Connector issue @vbarrier's running into?

**Comment by pradeepananth** [comment]
@vbarrier  - I used the manifest provided and tried setting up the connector and got the following error when debugging: _Url domain is not present in the valid domain list_
Valid domain retrieved has *.icescrum.com, but looks like Connectors service do not support wildcards. Please add the full domain preview.icescrum.com to the valid domains in the Connectors dashboard and let us know how that goes.

**Comment by vbarrier** [comment]
Thank it helps also I don't why but if I create a new team I don't have the connectors menu to manage its connectors and test mine. 

What are the rules to see / don't see the connectors menu ? (checkbox to manage connectors is checked on the team settings)

**Comment by pradeepananth** [comment]
@vbarrier - When a new team is created, there is a propagation delay for the Team to be provisioned on Exchange for Connectors to work. Most of the times, it takes less than a minute, but sometimes it may take up to 24 hours. 
Please let us know if you are not seeing the menu option even after 24 hours from Team creation.

**Comment by Trinetra-MSFT** [comment]
Please feel free reopen if you have any further query.
