### ISSUE TITLE
there is no logout

### ISSUE THREAD

**Issue by Venipa** [OfficeDev/microsoft-teams-library-js#319]
recently we received from the partner center a issue we must fix.
we implemented a logout button which logs out of office with the msadal js library.

since thats the only way we found to "logout" we got declined again because the user got logged out of office.

can someone share an exmaple, could not find any example with a logout button

**Comment by Wajeed-msft** [comment]
@Venipa - Could you please take a look at this [Auth sample](https://github.com/OfficeDev/microsoft-teams-sample-auth-node/blob/master/src/views/tab/silent/silent.hbs#L58) with logout option?

**Comment by Venipa** [comment]
@Wajeed-msft  we are using azure functions & angular as frontend, there is no such thing on the client sdk
we do logout with msadal but i also logs out users from teams.

**Comment by Wajeed-msft** [comment]
Are you building Microsoft Teams integration? This repo is only for Microsoft Teams apps.

**Comment by Venipa** [comment]
we are building a tab for teams, its hard to tell which is which in the documentation.
even so there is no logout option for the tab.
also the naming of the "libraries"/"sdk" is kinda misleading

**Comment by Wajeed-msft** [comment]
@Venipa - Did the LogOut code from [Teams Auth Bot Sample](https://github.com/OfficeDev/microsoft-teams-sample-auth-node/blob/master/src/views/tab/silent/silent.hbs#L301) help?

**Comment by Venipa** [comment]
no, tho we still dont know if there is any logout to tabs 😅
there is literally no docs

**Comment by Wajeed-msft** [comment]
Could you please share your app manifest to check the experience at our end?
