### ISSUE TITLE
[Question] Alternative to navigateCrossDomain

### ISSUE THREAD

**Issue by diabhoil** [OfficeDev/microsoft-teams-library-js#323]
Hey,

it is not really an issue, but I do not know where to ask else (posted on stackoverflow but no answer yet). Actually I am thinking about using navigateCrossDomain on my static/personal tab to navigate from my html page to linked sharepoint pages (which are generated "dynamically" and depending on the users tenant). 
But since it is deprecated and the link [https://aka.ms/navigateCrossDomain](https://aka.ms/navigateCrossDomain) is not really helping here: are there any alternatives or is there a new/better way on opening a spo page from a private tab? 

Direct links wont work since it is blocked because of X-Frame-Options/sameorigin. Also we do not want to open the sharepoint pages in the browser since the user should no leave the teams client. An alternative would be tasks.startTask (??) but only if there is no better way :(

best regards

**Comment by Wajeed-msft** [comment]
You could load SharePoint page in static tab. Could you please try [solution suggested here](https://stackoverflow.com/questions/57593508/sharepoint-page-not-loading-in-personal-tab-of-static-app-ms-teams-desktop-clie/57770834#57770834)? Also, could you please share the link to your Stackoverflow question as well?

**Comment by diabhoil** [comment]
This solution will work with a single url but I can't define the SharePoint Page URL in the manifest file of the teams app because a) its not one url, there can be many urls which will be defined by the end users and b) they will be totally dynamic.

[StackOverflow](https://stackoverflow.com/questions/61253236/alternative-to-navigatecrossdomain-microsoft-teams-js)

**Comment by Wajeed-msft** [comment]
@diabhoil - Do you want to navigate from one **teamSiteDomain** to another? You can navigate with-in the same site domain as you could specify only one webApplicationInfo in the manifest. Opening other tenant would need Sign In.
![image](https://user-images.githubusercontent.com/31851992/80369666-4618bc00-88ac-11ea-9d86-202dbd9bc04c.png)

You could use hyperlinks to navigate within the same site domain.
![image](https://user-images.githubusercontent.com/31851992/80369795-79f3e180-88ac-11ea-9415-3a19d754cbd4.png)

**Comment by diabhoil** [comment]
@Wajeed-msft No its a multi tenant application in a static tab. We want to switch the users from our custom domain (custom web site - no SharePoint) to the customer tenant SharePoint site. 

So we list, for the particular customer, a bunch of SharePoint URLs and they can click on it and are navigated to the specific site on their own SharePoint tenant. This would be possible with navigateCrossDomain, but not any more in the future when the function is deprecated.

**Comment by Nikitha-MSFT** [comment]
Could you please go through the documentation [navigateCrossDomain](https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/microsoftteams?view=msteams-client-js-latest#navigatecrossdomain-string---status--boolean--reason---string-----void-) If that helps?
