### ISSUE TITLE
CancelledByUser when execute Auth

### ISSUE THREAD

**Issue by andreatosato** [OfficeDev/microsoft-teams-library-js#324]
Hi all,
I follow [this tutorial](https://github.com/OfficeDev/microsoft-teams-sample-complete-node/blob/c101826ac17ebf8fc70209ceacad15e338201f3a/src/views/tab-auth/simple.hbs#L84-L96), but work only on Teams web.
On Teams Desktop fail with error: **CancelledByUser**
I suspect that [this method](https://github.com/OfficeDev/microsoft-teams-library-js/blob/f579aa62e422fadc34908059395eba6320b153cb/src/public/authentication.ts#L140) not work properly but I don't know why.

### Teams Web
Open popup, log on AAD and return correct Access Token.

### Teams Desktop
1. First attempt
Open web window and then not callback to Teams
2. Second attemp
Open Teams popup and then call fail callback with message **CancelledByUser**.

### Version
1.6

**Comment by andreatosato** [comment]
I resolve this issue after move teams initialization on index.

**Comment by lqdreaming** [comment]
Hello, I also have the problem now when I debugged with chrome browser of mac:
microsoftTeams.authentication.notifySuccess (tooken)
Login failed: CancelledByUser
May I ask how to solve it?
version:1.6

**Comment by andreatosato** [comment]
@lqdreaming do you call Teams initialization?
Once in app load
