### ISSUE TITLE
apps authentication popup issue

### ISSUE THREAD

**Issue by xhb1987** [OfficeDev/microsoft-teams-library-js#328]
HI, we have a very weird issue when we try to use `authentication.authenticate()` function.

when user click on a button (which will call this authenticate function) the first time, the app will open a new browser, but it will open a popup iframe window in second time.

Everything is working on web.

I am using lib `1.6.0`, and my app version is `1.3.00.8663`

**Comment by ydogandjiev** [comment]
@xhb1987, this can typically happen when the `authenticate()` API is called before the `initailize()` completes. Can you please try structuring your code as follows:
```
microsoftTeams.initialize(() => {
  microsoftTeams.authentication.authenticate(...);
});
```

Or better yet, don't even show the "Login" button on your page until initialization has completed.

**Comment by xhb1987** [comment]
@ydogandjiev thank you for your help, I will try this. Basically I just try put it inside `getContext`, and it works, will try to put it inside initialize, will close this issue.
