### ISSUE TITLE
getContext api returns wrong channel's context

### ISSUE THREAD

**Issue by vksuthar** [OfficeDev/microsoft-teams-library-js#329]
### Issue
The `microsoftTeams.getContext` js sdk api returns the context of wrong channel.

### Steps to reproduce
- Launch Microsoft Teams (https://teams.microsoft.com)
- Select a conversation channel (let's assume General in Team A)
- Now without selecting the other channel (let's assume General channel in Team B), directly click on extended menu (...) present on another conversation channel (let's assume General channel in Team B)
- Click on Connectors
- Click on configure button for any connector
- Now, try to run microsoftTeams.getContext(() => { console.log(arguments[0]); }); expression on console for popup iframe window in developer tools
- The context is of previous channel (General in Team A) and not of the current channel (General in Team B) where the connector was supposed to get added

**Comment by Trinetra-MSFT** [comment]
@vksuthar , getContext method returns the context of tab in which channel it is added. Did you configured the connector in Team A(General channel) first  than Team B(General channel)?

**Comment by vksuthar** [comment]
@Trinetra-MSFT This issue is with Connectors only. It doesn't matter if the connector is already added with Team A / B or not. As mentioned in the steps, if you select a channel (any channel) and then without selecting another channel if you try to launch Connectors dialog with extended menu, the context provided is of former selected channel.

**Comment by Trinetra-MSFT** [comment]
@vksuthar , We have filed a bug for this & tracking this internally. We will let you know once it is fixed.

**Comment by Trinetra-MSFT** [comment]
Please feel free to reopen if you still face this issue as bug is resolved
