### ISSUE TITLE
Authentication pop up not getting open on team window desktop application

### ISSUE THREAD

**Issue by sgsmittal** [OfficeDev/microsoft-teams-library-js#330]
it is working fine with web browser but not in teams desktop application.
I even tried with enabling dev tools but don't see any error

**Comment by ydogandjiev** [comment]
Hi @sgsmittal, are you using the `microsoftTeams.authentication.authenticate` API to open the popup? Also, did you take a look at #328?

**Comment by sgsmittal** [comment]
yes @ydogandjiev I tried the same but it doesn't worked

microsoftTeams.initialize(() => {
        microsoftTeams.authentication.authenticate({
          url: url,
          width: 600,
          height: 535,
          successCallback: (accessToken: string) => {
            window.location.href = window.location.protocol + "//"+ window.location.host + "/mattersTab";
          },
          failureCallback: (reason) => {
          }
        });
      });

**Comment by sgsmittal** [comment]
desktop app version: - Microsoft Teams Version 1.3.00.9267
microsoft js sdk :-  "1.6.0"

**Comment by aosolis** [comment]
@sgsmittal What's the domain of your tab, and what's the domain of the page you're opening in the auth popup? Is the domain in your manifest's validDomains list?

**Comment by sgsmittal226** [comment]
@aosolis I am using ngrok for local development
so
Domain of tab is the one generated by ngrok (https://fe752d34.ngrok.io)
Domain of the pop up :-   amazoncognito.com

and yes that is under manifest valid domain

![image](https://user-images.githubusercontent.com/40248398/80819076-ee26d180-8b99-11ea-8104-e0d9c865b2b9.png)

**Comment by Wajeed-msft** [comment]
@sgsmittal226 - Could you please add **fe752d34.ngrok.io** to validDomains section and try?

**Comment by ydogandjiev** [comment]
@sgsmittal226, what's the exact URL that you are passing to the `authenticate` API call? If it's something like `https://example.auth.us-east-1.amazoncognito.com` then it will not be covered by the `*.amazoncognito.com` entry. The entry needs to be `*.*.*.amazoncognito.com` or preferably something more specific.

**Comment by sgsmittal226** [comment]
Thank you guys it worked :)
