### ISSUE TITLE
[Question] Library Support regarding the Phone System

### ISSUE THREAD

**Issue by nullptr023** [OfficeDev/microsoft-teams-library-js#332]
Hi Microsoft Teams, 

It is not actually an issue but a question. I watched the demos of Microsoft Teams on how the bots, message extension is implemented but didn't see any implementation about the Phone System. So my question is, does the Microsoft Teams Library supports intercepting the call from the Teams Phone System? Like for instance, we want to make a connection to the Microsoft Teams's Phone System through the SDK and create an app that handles call flow through the SDK. Is that supported? If not, do you have plans in the future to implement it? 

I hope I was able to explain my question properly.

Thank you!

**Comment by Subhasish-msft** [comment]
@nullptr023 , Yes, Microsoft Teams apps can now interact with users in rich ways using voice and video. These APIs allow you to add new features such as interactive voice response (IVR), call control, and access to real-time audio and/or video streams for calls and meetings, including desktop and app sharing. Please have a look into [calling and meeting API](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/calls-meetings-bots-overview).

You can also refer to [communication API](https://docs.microsoft.com/en-us/graph/api/resources/communications-api-overview?view=graph-rest-beta)

**Comment by nullptr023** [comment]
@Subhasish-msft , thanks for the information. I'll take a look at it.
