### ISSUE TITLE
Privacy: Sending personal information unencrypted over HTTP to errors.angularjs.org

### ISSUE THREAD

**Issue by kevinrobinson** [OfficeDev/microsoft-teams-library-js#333]
I'm not sure if this is the right place to report, but figured it was close enough to be worth a shot.  If this is not the right place to report these kinds of issues, feel free to say that and close the issue, but I suspect folks on this team will be better able to route the issue than I would be :)

I was using MS teams, and opening a videocall in Safari showed a whitescreen.  I opened the console, and was surprised to see that there were HTTP requests to errors.angularjs.org that included personally identifiable information from my MS account.  Perhaps this issue impacts this library as well.

Here's what I saw; the redacted part is an email address:
![image](https://user-images.githubusercontent.com/1056957/81323854-0ef09a80-9064-11ea-9ffe-7b7b3b502fc5.png)

I tried once to reproduce this after the call, but couldn't.  It seems that this might have been happening because a series of other errors before that I didn't capture in the moment.  Regardless, I was surprised to see there were any circumstances where Teams would transmit email addresses unencrypted over HTTP to the angularjs.org domain.

Thanks for listening!

**Comment by Trinetra-MSFT** [comment]
@kevinrobinson , We have filed a bug for this. we will update you once it is fixed.

**Comment by kevinrobinson** [comment]
@Trinetra-MSFT thanks for your help! 👍

**Comment by kevinrobinson** [comment]
hi @Trinetra-MSFT!  You had said "we will update you once it is fixed," is there an update?  Thanks!
