### ISSUE TITLE
Broken link in Github https://dev.office.com/microsoft-teams

### ISSUE THREAD

**Issue by robations** [OfficeDev/microsoft-teams-library-js#334]
https://dev.office.com/microsoft-teams ?

Not sure if this is a temporary glitch, but this subdomain is giving me an NXDOMAIN.

Web search gives a couple of possible alternatives:

https://developer.microsoft.com/en-us/microsoft-teams/docs
https://docs.microsoft.com/en-us/microsoftteams/platform/

Or maybe the API doc link from the readme:

https://docs.microsoft.com/en-us/javascript/api/overview/msteams-client?view=msteams-client-js-latest

**Comment by lindalu-MSFT** [comment]
@robations @laujan Where was this link? There is no such domain as dev.office.com. It is EITHER:
developer.microsoft.com/microsoft-teams OR
docs.microsoft.com/microsoftteams

Closing not actionable. Please reopen if you find "dev.office.com/microsoft-teams" URL mentioned on one of our sites or docs. Thanks, linda

**Comment by robations** [comment]
If you go to the root page if this repo here in GitHub:

> OfficeDev /
> microsoft-teams-library-js

> Javascript library for use by Microsoft Teams apps
> **dev.office.com/microsoft-teams**
> View license 

Emphasis added.

**Comment by robations** [comment]
@lindalu-MSFT see above

**Comment by ydogandjiev** [comment]
Thanks @robations! I've updated the repo description so that it points to:
https://docs.microsoft.com/microsoftteams/platform/
