### ISSUE TITLE
Not able to see videos of majority of members in Desktop application.

### ISSUE THREAD

**Issue by jit4peace** [OfficeDev/microsoft-teams-library-js#336]
Not able to see video of many members after pinning them. They are visible in mobile application.

I can observe that new feature of 9 video at a time is added. But with same the videos even if they are on, are not visible.
I have attached screenshot with names hidden.
![VideoNotVisibleOnTeams](https://user-images.githubusercontent.com/9901058/82001263-69978100-9678-11ea-81a8-4e5e910f7337.png)

**Comment by Trinetra-MSFT** [comment]
@jit4peace , Could you please use `Report a Problem` feature in teams and send the logs?
![image](https://user-images.githubusercontent.com/50989436/82042397-6a0b3880-96c7-11ea-8e94-883ac16438ab.png)
