### ISSUE TITLE
Message extn custom form won't close form on submitTask - Android

### ISSUE THREAD

**Issue by rjesh-git** [OfficeDev/microsoft-teams-library-js#337]
Message extension with custom form won't close the form after `microsoftTeams.tasks.submitTask `instead shows the message "An error occurred retry" in the webform in the Android device.

Teams version - 1416/1.0
Android version - 10

No issues with desktop or web client occur only in the mobile devices, associated bot receives the payload and the response card is also posted in the channel.

**Comment by Gousia-MSFT** [comment]
@rjesh-git What version of Teams app are you using? Could you please provide a screenshot of the teams client version you are on?

**Comment by rjesh-git** [comment]
@Gousia-MSFT thanks for looking into this, here are the screenshots as requested. Taken from Samsung S9.

<img width="396" alt="image1" src="https://user-images.githubusercontent.com/9443767/82216853-68f82800-98ce-11ea-8aea-f97c7bd652eb.png">
<img width="399" alt="image2" src="https://user-images.githubusercontent.com/9443767/82216870-6b5a8200-98ce-11ea-8f7e-981edf7f662f.png">

**Comment by Gousia-MSFT** [comment]
@rjesh-git Could you please try enabling [Dev tools for Android](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/developer-tools#accessing-devtools-from-an-android-client) and see if you are seeing any console errors?

**Comment by rjesh-git** [comment]
@Gousia-MSFT No console errors from the remote device, I assume an error occurs outside the context of IFrame on receipt of empty object for the request event "composeExtension/submitAction".

**Comment by Gousia-MSFT** [comment]
@rjesh-git Could you please share your app manifest and repro steps with us?

**Comment by rjesh-git** [comment]
I'm sharing the project source code with you - [https://github.com/rjesh-git/customform-msgext/blob/master/README-conveyBot.md](https://github.com/rjesh-git/customform-msgext/blob/master/README-conveyBot.md)

1. Create bot registration and add teams channel
2. Update .env with Microsoft App Id and Password
3. Run `gulp ngrok-serve`
4. Copy the new ngrok URL from the terminal and update bot registration messaging endpoint - ex - https://5f62df55.ngrok.io/api/messages
5. Upload customform-msgext.zip from package folder as custom app to teams
6. Install app to any Team
7. Open Teams app in Android device, and go to Team where the app is installed
8. Invoke the message extension action `customform-msgex` while posting new post in a channel
9. The custom form opens with a button, just hit the button it should post a message to the channel message, but won't close the form instead show the "error occurred" as mentioned in this issue.

**Comment by Gousia-MSFT** [comment]
@rjesh-git Could you please share a working manifest that i can directly upload and check in my Teams? Please share it on `microsoftteamsdevATmicrosoft.com` if you do not want to share it publicly.

**Comment by Gousia-MSFT** [comment]
Please re-open with requested information
