### ISSUE TITLE
microsoft Teams：ms cannot communicate with each other beacause the function of microsoftTeams.authentication.authenticate will jump to the external browser link 

### ISSUE THREAD

**Issue by lqdreaming** [OfficeDev/microsoft-teams-library-js#338]
`microsoftTeams.authentication.authenticate({
                    url: `https://login.microsoftonline.com/common/oauth2/authorize??response_type=code&client_id=f34575e3-c476-4fe9-9396-922f57ba1f32&resource=https%3A%2F%2Fgraph.microsoft.com&redirect_uri=https%3A%2F%2F${src}&state=teams`,
                    width: 600,
                    height: 535,
                    successCallback: function (result) {
                        console.log("Login succeeded: " + result)
                        const accessCode = result.code
                        localStorage.setItem('accessCode', accessCode)
                        window.location.assign(`${url}?code=${accessCode}&state=microsoft`)
                    },
                    failureCallback: function (reason) {
                        console.log("Login failed: " + reason)
                        // handleAuthError(reason)
                    }`
the microsoftTeams jump to the external browser link, then Jump to the redirected page after third-party login verification. the microsoftTeams can't receive message when the redirected page send a message. 
I would like to ask why it will jump to the external link of the browser instead of opening it as an iframe in ms, thank you very much!

**Comment by Trinetra-MSFT** [comment]
@lqdreaming , The URL you pass to` microsoftTeams.authentication.authenticate()` is the start page of the authentication flow. Authentication flow must start on a page that's on your domain. This domain should also be listed in the `validDomains `section of the manifest. Could you please look at [initiate auth flow ](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-tab-aad#initiate-authentication-flow)in teams tab?

**Comment by lqdreaming** [comment]
> @lqdreaming , The URL you pass to` microsoftTeams.authentication.authenticate()` is the start page of the authentication flow. Authentication flow must start on a page that's on your domain. This domain should also be listed in the `validDomains `section of the manifest. Could you please look at [initiate auth flow ](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-tab-aad#initiate-authentication-flow)in teams tab?

nowadays, starting the authentication will jump to the chrome browser, this is not the result we want, we want to verify the identity in the popup of team box.
microsoftTeams.authentication.authenticate() is the start page of xxx.com/login.html,
the page of authentication flow is xxx.com/auth.html,
the page of end flow is xxx.com,
xxx is on behalf of our primary domain name.

**Comment by lqdreaming** [comment]
@Trinetra-MSFT nowadays, starting the authentication will jump to the chrome browser, this is not the result we want, we want to verify the identity in the popup of team box.
microsoftTeams.authentication.authenticate() is the start page of xxx.com/login.html,
the page of authentication flow is xxx.com/auth.html,
the page of end flow is xxx.com,
xxx is on behalf of our primary domain name.

**Comment by Trinetra-MSFT** [comment]
@lqdreaming Could you please look at [Teams Auth](https://github.com/ydogandjiev/taskmeow) sample code?

**Comment by lqdreaming** [comment]
login.html---the start page
` <script type="text/javascript">
        const accessToken = localStorage.getItem('AB_microsoft_token')
        const url = window.location.protocol + "//" + window.location.host

        if (accessToken) {
            window.location.assign(`${url}`)
        } 
        function login() {
            // hideProfileAndError()
            microsoftTeams.initialize()
            microsoftTeams.authentication.authenticate({
                url: url + '/auth.html',
 response_type=code&client_id=f34575e3-c476-4fe9-9396-922f57ba1f32&resource=https%3A%2F%2Fgraph.microsoft.com&redirect_uri=https%3A%2F%2F${src}&state=teams`,
                width: 600,
                height: 535,
                successCallback: function (result) {
                    const accessCode = result.code
                    window.location.assign(`${url}?code=${accessCode}&state=microsoft`)
                },
                failureCallback: function (reason) {
                    localStorage.removeItem('microsoft')
                    console.log("Login failed: " + reason)
                    // handleAuthError(reason)
                }
            })
        }
    </script>`
auth.html---the page of authentication flow
`<script type="text/javascript">
microsoftTeams.initialize()
            microsoftTeams.getContext(function (context) {
                let state = _guid()
                const url = window.location.protocol + "//" + window.location.host
                localStorage.setItem("simple.state", state)
                localStorage.removeItem("simple.error")
                let queryParams = {
                    client_id: appId,
                    response_type: "code", // "id_token token",
                    // response_mode: "fragment",
                    resource: "https://graph.microsoft.com/",
                    redirect_uri: url,
                    nonce: _guid(),
                    state: 'teams',
                    login_hint: context ? context.loginHint || context.userPrincipalName || context.upn : ''
                }

                // Go to the AzureAD authorization endpoint
                let authorizeEndpoint = "https://login.microsoftonline.com/common/oauth2/authorize?" + toQueryString(queryParams)
                window.location.assign(authorizeEndpoint)
            }())
</script>`
The above is the js code of two pages. Thank you for helping me!

**Comment by lqdreaming** [comment]
@Trinetra-MSFT 
login.html---the start page

` <script type="text/javascript">
const accessToken = localStorage.getItem('AB_microsoft_token')
const url = window.location.protocol + "//" + window.location.host

    if (accessToken) {
        window.location.assign(`${url}`)
    } 
    function login() {
        // hideProfileAndError()
        microsoftTeams.initialize()
        microsoftTeams.authentication.authenticate({
            url: url + '/auth.html',
response_type=code&client_id=f34575e3-c476-4fe9-9396-922f57ba1f32&resource=https%3A%2F%2Fgraph.microsoft.com&redirect_uri=https%3A%2F%2F${src}&state=teams, width: 600, height: 535, successCallback: function (result) { const accessCode = result.code window.location.assign(${url}?code=${accessCode}&state=microsoft) }, failureCallback: function (reason) { localStorage.removeItem('microsoft') console.log("Login failed: " + reason) // handleAuthError(reason) } }) } </script>`



auth.html---the page of authentication flow
`<script type="text/javascript">
microsoftTeams.initialize()
microsoftTeams.getContext(function (context) {
let state = _guid()
const url = window.location.protocol + "//" + window.location.host
localStorage.setItem("simple.state", state)
localStorage.removeItem("simple.error")
let queryParams = {
client_id: appId,
response_type: "code", // "id_token token",
// response_mode: "fragment",
resource: "https://graph.microsoft.com/",
redirect_uri: url,
nonce: _guid(),
state: 'teams',
login_hint: context ? context.loginHint || context.userPrincipalName || context.upn : ''
}

            // Go to the AzureAD authorization endpoint
            let authorizeEndpoint = "https://login.microsoftonline.com/common/oauth2/authorize?" + toQueryString(queryParams)
            window.location.assign(authorizeEndpoint)
        }())
</script>`

The above is the js code of two pages. Thank you for helping me!

**Comment by lqdreaming** [comment]
login.html---the start page
`<script type="text/javascript">
const accessToken = localStorage.getItem('AB_microsoft_token')
const url = window.location.protocol + "//" + window.location.host

if (accessToken) {
    window.location.assign(`${url}`)
} 
function login() {
    // hideProfileAndError()
    microsoftTeams.initialize()
    microsoftTeams.authentication.authenticate({
        url: url + '/auth.html',
        width: 600, 
       height: 535,    
      successCallback: function (result) { 
           const accessCode = result.code 
          window.location.assign(${url}?code=${accessCode}&state=microsoft) },      
     failureCallback: function (reason) {
        console.log("Login failed: " + reason) 
     } 
  }) 
} 
</script>`

**Comment by lqdreaming** [comment]
auth.html---the page of authentication flow
`<script type="text/javascript">
     microsoftTeams.initialize()
     microsoftTeams.getContext(function (context) {
         let state = _guid()
          const url = window.location.protocol + "//" + window.location.host
          localStorage.setItem("simple.state", state)
           localStorage.removeItem("simple.error")
          let queryParams = {
              client_id: appId,
              response_type: "code", // "id_token token",
             resource: "https://graph.microsoft.com/",
             redirect_uri: url,
             nonce: _guid(),
             state: 'teams',
            login_hint: context.loginHint || context.userPrincipalName
         }

        // Go to the AzureAD authorization endpoint
        let authorizeEndpoint = "https://login.microsoftonline.com/common/oauth2/authorize?" + toQueryString(queryParams)
        window.location.assign(authorizeEndpoint)
    }())
</script>`

**Comment by lqdreaming** [comment]
@Trinetra-MSFT the function of microsoftTeams.authentication.authenticate in login page will open the page of auth.html in chrome external browser. the login and auth pages are in a domain.

**Comment by ydogandjiev** [comment]
@lqdreaming, please ensure that initialization has completed before starting the auth flow:
```
microsoftTeams.initialize(() => {
  microsoftTeams.authentication.authenticate({
    url: url + '/auth.html',
    width: 600,
    height: 535,
    successCallback: result => {
      const accessCode = result.code;
      window.location.assign(`${url}?code=${accessCode}&state=microsoft`);
    },
    failureCallback: reason => {
      console.log("Login failed: " + reason);
    }
  });
});
```

**Comment by lqdreaming** [comment]
@ydogandjiev thank you very much, it is ok after adoptting your suggestion.
