### ISSUE TITLE
Need for API versioning and standardizing the error format in SDK APIs

### ISSUE THREAD

**Issue by pankajmi2** [OfficeDev/microsoft-teams-library-js#341]
Consider the scenario where a developer fetches latest Teams JS SDK and uses its latest APIs to build a webapp. The webapp is being used by an android user who is using an old android build which doesn’t has knowledge of the new API. At present, this scenario will break for this user since the API call wouldn’t return from the android platform.

Currently Teams JS SDK doesn’t have any knowledge on whether the underlying platform (Android/ iOS/ Web) provides implementation of an API or not and ends up always calling the API. If underlying platform has knowledge of the API then the call gets handled properly, else if the underlying platform is old (that means it doesn’t know about that API), then there is no graceful handling of the API call.

So, we need a way in the SDK to figure out whether underlying platform has knowledge of the API before actually invoking the API. Also, there is a need of standardizing the error format and codes which all SDK APIs will use.

**Comment by pankajmi2** [comment]
Consider the scenario where a developer fetches latest Teams JS SDK and uses its latest APIs to build a webapp. The webapp is being used by an android user who is using an old android build which doesn’t has knowledge of the new API. At present, this scenario will break for this user since the API call wouldn’t return from the android platform. 

Currently Teams JS SDK doesn’t have any knowledge on whether the underlying platform (Android/ iOS/ Web) provides implementation of an API or not and ends up always calling the API. If underlying platform has knowledge of the API then the call gets handled properly, else if the underlying platform is old (that means it doesn’t know about that API), then there is no graceful handling of the API call. 

So, we need a way in the SDK to figure out whether underlying platform has knowledge of the API before actually invoking the API. Also, there is a need of standardizing the error format and codes which all SDK APIs will use.

**Comment by Gousia-MSFT** [comment]
@pankajmi2 Thanks for sharing your feedback with us! We have forwarded it to the right team.
