### ISSUE TITLE
callback of microsoftTeams.settings.registerOnRemoveHandler is not executed

### ISSUE THREAD

**Issue by kostyaVyrodov** [OfficeDev/microsoft-teams-library-js#342]
Hello,

I try to subscribe on `microsoftTeams.settings.registerOnRemoveHandler`, but unfortunately, my **callback of registerOnRemoveHandler is not executed**.

Here's my code:
```
<html>
<head>
  <script src='https://statics.teams.cdn.office.net/sdk/v1.6.0/js/MicrosoftTeams.min.js'></script>
</head>

<body>
  <p>Deleting tab...</p>
  <script>
    microsoftTeams.initialize();
    microsoftTeams.settings.registerOnRemoveHandler(function (removeEvent) {
      console.log('registerOnRemoveHandler');
      removeEvent.notifySuccess();
    });
  </script>
</body>

</html>
```

**Steps to reproduce:** 
1. Open Teams in Google Chrome
2. Add a tab to a group channel
3. Try to remove it
<img width="1439" alt="Screenshot 2020-05-25 at 18 04 54" src="https://user-images.githubusercontent.com/15310397/82824918-e7e2f700-9eb2-11ea-9e48-f2ebf2e2ad8b.png">

**Expected result:** 
```
function (removeEvent) {
      console.log('registerOnRemoveHandler');
      removeEvent.notifySuccess();
});
```
should be executed

**Actual result:** I see errors in the console and they don't look related to registerOnRemoveHandler

<img width="511" alt="Screenshot 2020-05-25 at 18 05 31" src="https://user-images.githubusercontent.com/15310397/82825032-24aeee00-9eb3-11ea-81ac-ef31c301b85d.png">

**Comment by ydogandjiev** [comment]
@kostyaVyrodov, did you provide a `removeUrl` during your tab's configuration flow? This is documented here:
https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page#modify-or-remove-a-tab

**Comment by kostyaVyrodov** [comment]
@ydogandjiev , no... 
It started working after providing a `removeUrl`

Thank you!
