### ISSUE TITLE
[Question] create notification similar to Activity Feed

### ISSUE THREAD

**Issue by nullptr023** [OfficeDev/microsoft-teams-library-js#344]
Hi Microsoft Teams,

Is there a way to implement an app that has notification similar to Activity Feed? Like I want to show to the user that there is a notification in a custom app in the left side bar of Microsoft Teams. Also, when the app is selected in the side bar, does the app always refresh or it keep its state? Please let me know.

Thank you.

**Comment by Trinetra-MSFT** [comment]
@nullptr023 , You can integrate [send proactive notification](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-proactive-message?view=azure-bot-service-4.0&tabs=csharp) in your custom app. You can also [@mention](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-and-group-conversations?tabs=dotnet#working-with-mentions) a user to notify in the Teams activity feed from your custom app. Apart from that there are [change notification API](https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0) which notify users in Activity feed form any custom app

**Comment by nullptr023** [comment]
Hi @Trinetra-MSFT ,

Thanks for the update. If understand correctly, all the options you mentioned **notifies** the activity feed instead of the custom app. Is that correct? If that so, what we wanted to achieve is to have a notification in the app itself like there is a notification icon in the custom app. Is it not possible at the moment? 
Also, I wonder if the custom app reloads itself when switching between apps. For instance, I open my custom app from the left side navigation and do some operation, then switch with Chat, then go back to the app again to continue what I'm doing. Does it reload/refresh the page of the app or it keeps the state of the app? Please let me know. 

Thank you.

**Comment by nullptr023** [comment]
Hi @Trinetra-MSFT ,
I just tried doing the sample of the personal tab and it looks like it keeps reloading when switching between tabs or apps. Is there a way to prevent it from reloading? cause it doesn't make sense. It should not refresh the page cause the user is using it. Also, please see my other question above regarding the notification for specific custom app not notification pass to the Activity Feed. 
The idea is the custom have will have the icon notification and not reload the app each time it is visited. For instance, we did some operation in the app, then switch for a moment in other apps. then if something happen to app depending on the operation the custom app will notify the user by having the custom app a notification icon. Please let me know if the two are possible or work around. 

Thank you.

Thank you.
