### ISSUE TITLE
microsoftTeams.authentication.getAuthToken() does not work for Tab within MSTeams in latest Android version

### ISSUE THREAD

**Issue by icatchx22i** [OfficeDev/microsoft-teams-library-js#345]
While testing authentication on different devices I noticed that calling getAuthToken() fails on tabs running in Android without calling the failureCallback function.  This causes our application to hang on splash screen waiting for next steps. 

Not sure if related / maybe is a clue, but calling getContext when running in Android also seems to not call its' callback. I have tested and debugged this using the remote debuging in chrome.  (I also think that changing getContext to return a promise would be better, but that's for a different ticket.) 

Thanks

**Comment by Nikitha-MSFT** [comment]
could you please share which Teams client SDK are you using? Also could you please Teams version and android version

**Comment by icatchx22i** [comment]
Gladly :) 
SDK version 1.6.0
Android Teams Version: 1416, Build #1.0.0.2020050805, CAlling version: 2020.10.01.1
Android Version: 10 build # 10.0.0.222, Kernel version: 4.14.116

Thank you

**Comment by Nikitha-MSFT** [comment]
We are checking it internally.

**Comment by Nikitha-MSFT** [comment]
@icatchx22i - Can you kindly check this on latest Teams iOS Alpha ?

**Comment by icatchx22i** [comment]
@Nikitha-MSFT Could you please send me a guide how to get the IOS Alpha? Also, just a note that this ticket was opened for the Android version. I do not have this issue with iOS Developers version

**Comment by Nikitha-MSFT** [comment]
@icatchx22i  - we have created a bug, tracking it internally.

**Comment by icatchx22i** [comment]
@Nikitha-MSFT Hi, any updates on this issue? thanks

**Comment by Nikitha-MSFT** [comment]
Are you trying to call getAuthToken for tab SSO? If yes tab SSO is not yet supported on mobile.
