### ISSUE TITLE
Download Not Supported from iFramed app in Chrome 83

### ISSUE THREAD

**Issue by HaveSpacesuit** [OfficeDev/microsoft-teams-library-js#346]
I'm running a custom tab from Microsoft Teams in an iFrame. Part of my app allows the user to download files, but Chrome 83 is [not allowing users](https://www.chromestatus.com/feature/5706745674465280) to download files inside an iFrame anymore unless it has the `sandbox="allow-downloads"` attribute on it.

![image](https://user-images.githubusercontent.com/15036346/83675167-31f86680-a59e-11ea-9471-e89e798aafb1.png)
![image](https://user-images.githubusercontent.com/15036346/83675208-48062700-a59e-11ea-901c-f2d1881751e6.png)

How soon can we update the MS Teams web app to provide this?

**Comment by ydogandjiev** [comment]
Thanks for the reporting the problem, @HaveSpacesuit! We are aware of this issue and in the process of releasing a fix for it.

**Comment by HaveSpacesuit** [comment]
It looks like this is fixed on the web now. Now I'm having a related problem on the desktop app. When running my tab plugin via localhost, it won't open up a configured tab or the configure new tab page. I get this error in the dev console:
![image](https://user-images.githubusercontent.com/15036346/87092079-6b0ca200-c200-11ea-8164-d4c767c6fb4f.png)

Localhost works fine on a web browser, and a published app works fine in the desktop app. It is only running localhost in the desktop app that causes the problem.

Is this related to the allow-downloads fix, and can we expect a fix in the desktop app for this?

**Comment by ydogandjiev** [comment]
@HaveSpacesuit, this console error is a red herring. Is your localhost page being hosted over https? Are you seeing your page's JavaScript code running? Are you sure that it's not hitting any errors on load?

**Comment by HaveSpacesuit** [comment]
Thank you, you are correct. There is no issue other than I forgot an old configuration step on my end. 😳
