### ISSUE TITLE
Question/Feature Request: Navigating back to tab's contentUrl set by setFrameContext

### ISSUE THREAD

**Issue by EdGuest** [OfficeDev/microsoft-teams-library-js#347]
We have a similar type of app as described in #204, where operations within our app result in the need to update the contentUrl and websiteUrl to reflect that view configuration.

setFrameContext implemented for #204 is solving that for reloads (and opening in a browser), however we also allow linking to other Teams content within our view which we navigate to using executeDeepLink.

Users need to be able to go back and forth between our tab and these links, but currently back navigating in Teams is reloading the tab based on it's settings rather than going back to the contentUrl set in setFrameContext, so they are not going back the the same view they left.

Is this operation supported another way or if not something that can be added as a new feature?

**Comment by Trinetra-MSFT** [comment]
@EdGuest , Did you tried `microsoftTeams.navigateToTab(tabInstance: TabInstance, onComplete?: (status: boolean, reason?: string))` to navigate to specific tab content URL?

**Comment by EdGuest** [comment]
> @EdGuest , Did you tried `microsoftTeams.navigateToTab(tabInstance: TabInstance, onComplete?: (status: boolean, reason?: string))` to navigate to specific tab content URL?

To give a bit more background - our app allows creating of diagrams where symbols can be linked to external content by hyperlinks. Our users can copy & paste in links to Teams content (documents, tabs, etc.), which when we are in Teams navigates to the content within Teams.

My understanding is microsoftTeams.excecuteDeepLink() is the only way to navigate to a Teams deeplink? Can we open a Teams deeplink (to e.g. a PowerPoint file in the channel files) with microsoftTeams.navigateToTab()?

The main thing it that we need a back navigation after this to take us back to our tab with the contentUrl as it was before the user linked on the link to open the file.

**Comment by Trinetra-MSFT** [comment]
@EdGuest , If you have a Tab which contains power point files you can still use the deep link to configurable tab but you can't directly able to open the file from deep linking you can navigate to tab. Here is the deep link to configurable tab:
[https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links#generating-a-deep-link-to-your-tab](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links#generating-a-deep-link-to-your-tab).

**Comment by Trinetra-MSFT** [comment]
Please feel free to reopen this issue if you have further query
