### ISSUE TITLE
Deeplink callback is not called

### ISSUE THREAD

**Issue by huyayuan** [OfficeDev/microsoft-teams-library-js#348]
I use the following code to execute deeplink:
``` javascript
  MSTeams.executeDeepLink(deepLink, (status, reason) => {
    console.log("Pls call me");
  });
```
But the callback is not executed. Is it a bug or anything I did is not correct?

I have a quick look about deeplink of the source code, I assume that when the teams iframe receive the deeplink url, it directly handles and jumps to the corresponding url and ignore to execute the deeplink callback in the child iframe, am I right?

**Comment by Abhijit-MSFT** [comment]
Checking it internally.

**Comment by ydogandjiev** [comment]
This behavior is expected. When you use the `executeDeepLink` API it typically triggers a navigation away from your app/tab which means that the iframe hosting your page is torn down and your code stops executing before it can process the callback. Are you just looking to use this callback to determine the success of the `executeDeepLink` call?

**Comment by mwerghemmi** [comment]
Hi @ydogandjiev, 
I am having this same issue too.  
in my case i need to do some other processing after the Deeplink is executed. 
what would be the best approach ? 
if i understand well, when the Tab page is not active (after navigation) nothink can be executed right ?

**Comment by huyayuan** [comment]
@ydogandjiev That's right. We are looking for a way to determine whether a deeplink is valid or not, if not, for example, maybe the end user didn't install some specific 3rd party app, we need to know that redirection is failed and give user better experience such as show the user a webpage to download that app. So base on our scenario, do you have some better solutions?

Your explanation meets my assumption, it seems that this callback will never be executed, then what's the purpose to pass the callback as second param into the executeDeepLink function? Should we delete this param in next teamsjs version and introduce some ways to detect the result of deeplink execution.

**Comment by ChetanSharma-msft** [comment]
Hello @huyayuan,
Hope you are doing well!!

Sorry for delay in response.
We will check on it with engineering team and let you know the updates.

**Comment by Meghana-MSFT** [comment]
Engineering team has given the following suggestion - 
The purpose of the callback is to notify the developer of failures with the executeDeepLink API. In the case of a successful navigation, the developer can still get a callback if they have called registerBeforeUnloadHandler and done the work to delay their app from getting unloaded immediately.

**Comment by Wajeed-msft** [comment]
https://github.com/OfficeDev/microsoft-teams-library-js/issues/348#issuecomment-1318282350

Please feel free to re-open if you have any further questions.
