### ISSUE TITLE
CancelledByUser when execute Auth

### ISSUE THREAD

**Issue by prashant-nigam** [OfficeDev/microsoft-teams-library-js#349]
Authenticate Fails on teams Desktop app with message : '**CancelledbyUser**' . Works fine on Teams Web App.

Teams authentication popup never opens in desktop app. On debugging found below condition being executed from teams SDK: 
if (!s.GlobalVars.childWindow || s.GlobalVars.childWindow.closed)
                        c("CancelledByUser");

**SDK Version : 1.6.0**

**Comment by Trinetra-MSFT** [comment]
@prashant-nigam , `CancelledByUser `executed within `NotifyFailure ` when the user closed the popup window before completing the authentication flow. Can you please check login pop is getting blocked for teams desktop? Can you please also help with the error screenshot you are getting in console for Teams desktop app?

**Comment by prashant-nigam** [comment]
I was able to resolve this by calling code from callback of initialize function. It seems just calling initialize does not work some times as Teams SDK is not initialized properly
