### ISSUE TITLE
authentication.authenticate() bug in IE11 (v0.4)

### ISSUE THREAD

**Issue by davidye** [OfficeDev/microsoft-teams-library-js#35]
We're running into an IE11 bug in authentication.authenticate() with this setup:

1) Parent window calls authentication.authenticate({url: <oauth_endpoint>, ... })
2) Child popup window loads <oauth_endpoint>
3) User authenticates in child popup window
4) Child popup window is redirected to callback url with same origin as parent window
5) Child popup window remains open and notifySuccess / notifyFailure messages are never returned to the parent window

It appears that postMessage() in IE11 breaks when the redirect happens. A few threads that document this bug:

http://stackoverflow.com/questions/21070553/postmessage-still-broken-on-ie11
https://github.com/Vestorly/torii/issues/63

**Comment by ydogandjiev** [comment]
@davidye, thank you for reporting this issue. Unfortunately I am unable to reproduce the bug you've described on my end. I built a simple test tab for myself that allows the user to authenticate with their Facebook, LinkedIn, or AAD account and verified that the tab works great in all browsers that Microsoft Teams supports including IE 11 You can download a package for this tab that's ready to sideload here:
https://teams-todolist.azurewebsites.net/tabs/todolist_0.4.zip

Can you tell me how this tab's authentication flow is different from what you are doing?

**Comment by DoctorGester** [comment]
@ydogandjiev Windows 8.1 Pro, Internet Explorer 11.0.9600.18161

I was able to reproduce the issue using todolist_0.4.zip you have provided earlier. After authorizing with facebook the popup window never closes and no authorization happens. I had to alter the manifest.json and provide a correct logo.png file. We are also having the same issue in our company app.

I was able to craft 2 small HTML files and seemingly reproduce the issue using the same setup. You will have to change the local file path inside the top_page.html file in order for popup to work. The attached example uses postMessage and appears to work in Chrome fine, but does not work in IE11.
[gxnrxf.zip](https://github.com/OfficeDev/microsoft-teams-library-js/files/1521472/gxnrxf.zip)

**Comment by srinivasnaidu-msft** [comment]
@DoctorGester  Attached zip contains a video of authentication pop up closing properly after the . A video or image of your issue can help us.

[ieissuewithpopup.zip](https://github.com/OfficeDev/microsoft-teams-library-js/files/1531070/ieissuewithpopup.zip)
