### ISSUE TITLE
[Question/Feature] Controlling task module's close event.

### ISSUE THREAD

**Issue by dbajpeyi** [OfficeDev/microsoft-teams-library-js#352]
**Context**
We have an app/website which is embedded in a task module in Microsoft Teams. The app is pretty complex and users are supposed to make many interactions - choose templates, add custom content, etc. 
This content is kept on our servers as a `draft` that users could access anytime if they went to our website. 

**Problem**
When our app runs outside the Microsoft Teams environment, we attach a `beforeunload` event handler to the `window` object which prevents user from closing the tab when there are unsaved changes:

```
function beforeUnloadHandler(state) {
    return (event) => {
        if (state.userHasUnsavedChanges) {
            event.preventDefault();
            event.returnValue = '';
        }
    };
}

window.addEventListener('beforeunload', beforeUnloadHandler(state));
```
However now that we embed the site in the task module, this part of the code loses relevance.

**Question**
Is there some way for our application to control the decision of if the dialog should be closed?

Example:
```
Msteams.tasks.onBeforeClose = (event) => event.preventDefault(); event.returnValue="";
```

The [submitHandler](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/task-modules-tabs#submitting-the-result-of-a-task-module) is the closest I got to, however it doesn't give access to the event that can be prevented.

Thank you in advance!

**Comment by Abhijit-MSFT** [comment]
@dbajpeyi, Unfortunately there is nothing for this. The moment you click on some button - "OnTeamsTaskModuleSubmitAsync" method will get called and taskModule will be closed.

**Comment by dbajpeyi** [comment]
@Abhijit-MSFT Thanks for the response!
