### ISSUE TITLE
[REQUEST] Update Electron version of the desktop app (tab bugs with current Chromium version)

### ISSUE THREAD

**Issue by nikbora** [OfficeDev/microsoft-teams-library-js#354]
👋🏻

We have an app with a tab that has two bugs related to an old version of Chromium inside of Electron desktop app (Electron version 4.2.12 vs. current stable of 9.x). As an example, one is related to a rich text React component we use that gets double key events (https://github.com/ianstormtaylor/slate/issues/3406). We don't have these bugs when running Teams in current or even recent versions of Chrome, Firefox, Edge, Safari etc. Even a small upgrade to Electron 5.x would do the trick as it has newer Chromium.

I am posting this here as am not sure how to request this from whoever maintains the desktop app.

**Comment by Nikitha-MSFT** [comment]
We are looking into this

**Comment by Nikitha-MSFT** [comment]
Our Team is actively working on upgrading our Electron version away from v4.2, That should help fix this issue. But currently we don't have any ETA to share when it will be fixed.

**Comment by nikbora** [comment]
Great, thanks for the update.
