### ISSUE TITLE
configName is always null when retrieved via getSettings

### ISSUE THREAD

**Issue by natwallbank** [OfficeDev/microsoft-teams-library-js#355]
Hi, I've been experimenting with creating a Teams connector and have mostly resolved the issues I've been having.  However, I notice that I can supply `configName` to `setSettings` and this is used by Teams and displayed:

![image](https://user-images.githubusercontent.com/1752093/85619987-0592b000-b65b-11ea-8eda-9aff6f32ba0f.png)

I can specify this on creation or on edit of configuration. However, what makes it a little awkward is that I don't appear to be able to retrieve it. Whenever I call `getSettings` it comes back as null. The other properties are populated correctly.

Is this a known issue?

**To clarify (as I realise I wasn't totally clear about this): this relates to editing an existing configuration.  The first step I'm trying to achieve in the iFrame is to load the configuration (via getSettings) so that I can retrieve the entityId and configName.  I can retrieve the entityId no problem, but configName is always null.**

**Comment by Subhasish-msft** [comment]
@natwallbank , I could able to reproduce it. I have created a bug for this.

**Comment by natwallbank** [comment]
@Subhasish-msft Great, thanks for taking the time to take a look 👍

**Comment by ydogandjiev** [comment]
The `setSettings` API only accepts objects that implement the `Settings` interface which is defined as follows:
```
  export interface Settings {
    /**
     * A suggested display name for the new content.
     * In the settings for an existing instance being updated, this call has no effect.
     */
    suggestedDisplayName?: string;
    /**
     * Sets the URL to use for the content of this instance.
     */
    contentUrl: string;
    /**
     * Sets the URL for the removal configuration experience.
     */
    removeUrl?: string;
    /**
     * Sets the URL to use for the external link to view the underlying resource in a browser.
     */
    websiteUrl?: string;
    /**
     * The developer-defined unique ID for the entity to which this content points.
     */
    entityId: string;
  }
```

You cannot store arbitrary data in the tab settings. Any customer data should optimally be stored in your own backend/database and fetched dynamically at runtime. Any tab instance metadata can be serialized in the `contentUrl` or stored in your own service indexed by the `entityId` (or some other key you put in the `contentUrl`).

**Comment by natwallbank** [comment]
@ydogandjiev That's incorrect. I found that same documentation, and assumed what you say to be correct - but it appears to be different at runtime for connectors, which is rather frustrating - as it's not possible to rely on the Typescript definition file.

It is perfectly valid to set `configName` and that is what is displayed as the name of configuration when you look at configured connectors for a channel.

**Comment by Trinetra-MSFT** [comment]
Bug is Resolved now, We set a new field FriendlyName for it, Let us know if you still face this issue. Closing this please feel free to reopen if you have further query. Thanks
