### ISSUE TITLE
Teams context channel name and ID is wrong on IOS tab

### ISSUE THREAD

**Issue by FormMachines** [OfficeDev/microsoft-teams-library-js#357]
We are testing a custom tab on an IOS device, the channel name and ID provided in JS Context object seems wrong, its always returns the default channel name and ID, even if the tab is launched from a different channel, not the default channel. 

This error is noted on an iPhone 8 device, other versions of Teams (desktop, web and Android) seems correct. Teams JS tested was version 1.6. 

```
MSTeams.getContext((ctx: MSTeams.Context) => 
{
/*
ctx.channelId and ctx.channelName always returns the default channel ID and name, even if the tab is launched from a different channel (not the default channel of the team). This error only happens on the IOS version of MS Teams
*/
}); 
```

**Comment by Trinetra-MSFT** [comment]
@FormMachines , Could you please try to upgrade your teams to latest build for iphone and let me if you still face this issue.

**Comment by FormMachines** [comment]
We are using version 1.6, which is the latest production version. Unless you mean the latest beta-version? Can you please clarify?

**Comment by FormMachines** [comment]
Any updates on this @Trinetra-MSFT , thank you very much!

**Comment by Trinetra-MSFT** [comment]
@FormMachines , We have a Bug for this in pipeline for returning general channel ID for tab. We will let you once this got resolved
