### ISSUE TITLE
Teams on Android, "userTeamRole" is always "user", even for admins

### ISSUE THREAD

**Issue by FormMachines** [OfficeDev/microsoft-teams-library-js#358]
We are testing a custom tab on Android devices, the MSTeams context object returned always has "userTeamRole" set to "User", even for admin users, expecting "Admin" to be returned. 

On other version of Teams, desktop, web and IOS, this is correct. Only seems to happen on the Android version of Teams. 

Teams.js version tested was 1.6, our app was side-loaded into Teams.

**Comment by Gousia-MSFT** [comment]
@FormMachines Thanks for reaching out to us! This is a known issue. We have a bug on this and we are working on fixing it.

**Comment by olafur164** [comment]
@Gousia-MSFT This seems also to be happening on iPadOS 13.6.1
