### ISSUE TITLE
How to handle SSO authentication in server side Node JS

### ISSUE THREAD

**Issue by Vigneshramkumar** [OfficeDev/microsoft-teams-library-js#359]
Hello Team,

I am working on a Teams tab application using React JS as UI and serving the same as static content to a Node JS application. We are planning to use the SSO authentication part mentioned in below MS documentation.

[MS SSO for Teams Tab app](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso)

Here they are using MS Teams library for JS and asked to do setup in Azure and in manifest file. I have done with azure and manifest part. But is there any way to write the authentication part in node JS server side.

`var authTokenRequest = {
  successCallback: function(result) { console.log("Success: " + result); },
  failureCallback: function(error) { console.log("Failure: " + error); },
};
microsoftTeams.authentication.getAuthToken(authTokenRequest);`

When i try to write the same in node JS side I am getting window is not defined error. Kindly help me on solving the issue.

![image](https://user-images.githubusercontent.com/17233137/86019819-b8d91b80-ba44-11ea-836e-0a767271aa21.png)

**Comment by Vigneshramkumar** [comment]
Below is the code written for SSO authentication.

![image](https://user-images.githubusercontent.com/17233137/86022966-aa8cfe80-ba48-11ea-81c9-6268662e0bc8.png)

**Comment by Abhijit-MSFT** [comment]
Check this [sample](https://github.com/ydogandjiev/taskmeow). This will help you.
