### ISSUE TITLE
API for setting user presence?

### ISSUE THREAD

**Issue by eddieparker** [OfficeDev/microsoft-teams-library-js#368]
I see that this issue: https://github.com/OfficeDev/microsoft-teams-library-js/issues/343 was closed as you don't have permission to *get* a users presence, but what about setting it?

I ask as it would be nice for users to set people to away/do-not-disturb/etc based on what their own applications may or may not be doing.  Is there a mechanism for doing this in the API?

**Comment by Gousia-MSFT** [comment]
@eddieparker Currently we do not have any API to set the presence of the user. You can only get the user's presence using [Get Presence API](https://docs.microsoft.com/en-us/graph/api/presence-get?view=graph-rest-beta&tabs=http).
