### ISSUE TITLE
Teams SSO in a SharePoint Hosted Tab using SPFX

### ISSUE THREAD

**Issue by philip-young** [OfficeDev/microsoft-teams-library-js#370]
Hello,

We are attempting to implement the newly released Teams Single Sign-On (SSO) API found [here](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso) but are having difficulties when opening our SPFX built tab in Teams desktop. Are there any foreseeable problems with using Teams SSO and an SPFX built tab? 

We have followed the guide exactly and have noticed the the Tab does not load in desktop Teams but no error messages appear. I have checked the Teams logs and have found a few AUTHSSO entries as seen below:
`AUTHSSO: Return cached token for resource: api://oursite.sharepoint.com/our-app-reg-client-id-here`
`AUTHSSO: Start acquiring Adal tokens -- resources: api://oursite.sharepoint.com/our-app-reg-client-id-here`

These two entries appear one after another and I can't see anything else. However, in the Teams Desktop DevTools we have seen this error:
`AUTHSSO:Token Cache: Token for resource api://oursite.sharepoint.com/our-app-reg-client-id-here is not valid, cannot get it in cache`

Can you please advise? Or maybe have some other ways to debug/see what is wrong? I believe the Teams Web App is working with this configuration.

**Comment by Trinetra-MSFT** [comment]
@philip-young , Could you please look at the sample code for [SSO](https://github.com/OfficeDev/msteams-tabs-sso-sample-nodejs)? SSO works for SPFx as well. Could you please also share the repro steps you have tried?

**Comment by DFAndyChau** [comment]
@Trinetra-MSFT I'm Phil's colleague.  Just to isolate the issue, we scaffolded an new hello world webpart in SPFX 1.11 and can still replicate the error.

After installing the webpart in SP and adding the app package to teams.  It works fine in both Teams Web App and Teams Mobile, but we get a blank screen in Teams Desktop.

We followed this guide to create the app registration https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso.

Below is the Teams app manifest:

{
    "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.7/MicrosoftTeams.schema.json",
    "manifestVersion": "1.7",
    "version": "1.0.0",
    "id": "53f45514-0c69-476c-9ef2-5140a632283c",
    "packageName": "contoso.teams.spfxsso",
    "developer": {
        "name": "SPFX",
        "websiteUrl": "https://www.google.ca",
        "privacyUrl": "https://www.google.ca",
        "termsOfUseUrl": "https://www.google.ca"
    },
    "icons": {
        "color": "color.png",
        "outline": "outline.png"
    },
    "name": {
        "short": "SSO Sample",
        "full": "SSO Sample"
    },
    "description": {
        "short": "SSO Sample for SPFX",
        "full": "SSO Sample for SPFX"
    },
    "accentColor": "#FFFFFF",
    "configurableTabs": [
        {
            "configurationUrl": "https://contoso.sharepoint.com/sites/GoArctic/_layouts/15/TeamsLogon.aspx?SPFX=true&dest={teamSitePath}/_layouts/15/teamshostedapp.aspx%3FopenPropertyPane=true%26teams%26componentId=50ac93ac-677b-420b-840d-3a9b8e804bb1%26forceLocale={locale}",
            "canUpdateConfiguration": true,
            "scopes": [
                "team"
            ]
        }
    ],
    "permissions": [
        "identity",
        "messageTeamMembers"
    ],
    "validDomains": [
        "contoso.sharepoint.com"
    ],
    "webApplicationInfo": {
        "id": "e76e3253-f3aa-49b0-a5e0-44859936d4a1",
        "resource": "api://contoso.sharepoint.com/e76e3253-f3aa-49b0-a5e0-44859936d4a1"
    }
}

**Comment by philip-young** [comment]
Hello, we haven't heard back yet and just wanted to follow up.

**Comment by Wajeed-msft** [comment]
Hi @philip-young - If you're using SPFx then you will get a ready-made AAD id and resource (and then get SSO for free out-of-the-box). You shouldn't have to do extra work to use SSO (like using our getAuthToken API). That's all handled for you via SPFx in Teams.

Could you please update your app manifest with following webApplicationInfo? 
```
 "webApplicationInfo": {
    "resource": "https://contoso.sharepoint.com",
    "id": "00000003-0000-0ff1-ce00-000000000000"
  }
```
Please let us know if you are still facing the issue after this change.
