### ISSUE TITLE
Feature Request: Implement retrieval of  marketing campaign id from AppSource same as Office.js

### ISSUE THREAD

**Issue by abdulkareemnalband** [OfficeDev/microsoft-teams-library-js#374]
We want track from where our leads are coming from. In Office.js we can read campaignId from store ([link](https://docs.microsoft.com/en-us/office/dev/store/promote-your-office-store-solution)).  Can you implement somewhat similar API from teams also.

**Comment by Gousia-MSFT** [comment]
@abdulkareemnalband Thanks for reaching out to us! We are looking into it.

**Comment by Gousia-MSFT** [comment]
@abdulkareemnalband Thanks for your patience here! We had a discussion on this internally and this isn't currently available. Please feel free to raise a [Uservoice ](https://microsoftteams.uservoice.com/)for the same.

**Comment by abdulkareemnalband** [comment]
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/41347900-feature-request-implement-retrieval-of-marketing
