### ISSUE TITLE
Getting all details of an incoming call

### ISSUE THREAD

**Issue by vipulw2011** [OfficeDev/microsoft-teams-library-js#377]
Hi, I am implementing a thing where what I am doing is when a user calls to a number that call is redirected to teams and when it comes in teams, I need to take all the available details and search for the user in my web app running inside MS Teams Tabs. I could't find anything on this. If someone can just guide me here.

Thanks

**Comment by phr0st** [comment]
Hi @vipulw2011, I also have the same requirement. Could not find anything related to this. Would be nice if you can give me an update on any progress.

**Comment by vipulw2011** [comment]
@phr0st Hi, I didn't make any progress on this. Still on it and I am seeing anything in their documentation. Any update from you ?

**Comment by phr0st** [comment]
@vipulw2011 : no, same here...

**Comment by unckleg** [comment]
Same here. Msoft team should be shamed.

**Comment by ydogandjiev** [comment]
From the description above it's not clear what exactly you are trying to achieve. Can you please better explain the scenario you're trying to implement? Do you have any comps/mocks showing the end-to-end experience you are using to deliver to the customer?

**Comment by vipulw2011** [comment]
@ydogandjiev Any update on this issue. This is the key feature I am trying to implement. I don't have mocks to share with you but I can explain you the flow. 
I have built a personal tab in MS Teams which includes by web application embedded there. What I want is whenever a particular user receives a call, I need the details of that call in my personal tab application so that I can do some data processing there for my business needs. Any help or guidance from you will be appreciated.

**Comment by vipulw2011** [comment]
@Wajeed-msft Is there any update on this previous issue you closed ?
https://github.com/MicrosoftDocs/msteams-docs/issues/807

**Comment by Subhasish-msft** [comment]
@vipulw2011 , You could create a [subscription ](https://docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&tabs=http)for the callRecord API. It Subscribes a listener application to receive change notifications when changes occurs in Microsoft Graph.

**Comment by vipulw2011** [comment]
@Subhasish-msft I will try and let you know

**Comment by vipulw2011** [comment]
@bijaykush Any update on the issue you created.
https://github.com/microsoftgraph/microsoft-graph-docs/issues/8191

**Comment by bijaykush** [comment]
@vipulw2011 
No update on this. I am still waiting for this. 

@Subhasish-msft 
I think subscribing callRecords API will give change notifications at the end of the call not when the call is started.

**Comment by sayali-MSFT** [comment]
@vipulw2011 - Could you please confirm if your issue has resolved or still looking for any help?
