### ISSUE TITLE
Getting application id in tab context

### ISSUE THREAD

**Issue by praneshrv96** [OfficeDev/microsoft-teams-library-js#381]
How to get the application id in tab context? I need to pass the appid in microsoftTeams.executeDeepLink call. Where can I get the appid? I know it is in manifest. But I don't want to hard code it since we have multiple packages for our app and id differs for all.

**Comment by VaraPrasad-MSFT** [comment]
[Tab Context](https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/microsoftteams.context?view=msteams-client-js-latest) does not have a property called appId , hence you can't get appid from tab context.

How did you installed the app ? could you please confirm.

**Comment by praneshrv96** [comment]
I meant the id of the application. For deeplink I want the id "https://teams.microsoft.com/l/entity/<appId>/<entityId>?webUrl=<entityWebUrl>&label=<entityLabel>&context=<context>". But I don't want to hardcode it. Is there any way to fetch it using SDK?

**Comment by Wajeed-msft** [comment]
Currently Tab context do not provide App ID.
Could you please try passing App ID as query string parameter in your Tab's content URL? That way, you don't need to hard code it.

**Comment by praneshrv96** [comment]
Passing in URL is also similar to hardcoding right? When the apps are sideloaded the App ID is different from the one in manifest. In that case even if I set the App ID which is in manifest in the URL, the after installation ID will be different. How can we fetch the App ID properly in those cases?

**Comment by Wajeed-msft** [comment]
> When the apps are sideloaded the App ID is different from the one in manifest. 

The Id which you pass in [deeplink](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links#generating-a-deep-link-to-your-tab) should be the same as manifest App ID. 
![image](https://user-images.githubusercontent.com/31851992/90522001-d430ef00-e188-11ea-8d67-9e811ff23c72.png)


Are you facing any issue while creating deep link using this ID specified in manifest?
