### ISSUE TITLE
Is there a way to pop-up 1:1 chat through the sdk?

### ISSUE THREAD

**Issue by JinkaiZhang1989** [OfficeDev/microsoft-teams-library-js#382]
Hi Teams,

Is there a way to pop up a 1:1 chat into a multi-window, just like using 
![Pop-up the 1:1 chat into a multi-window](https://user-images.githubusercontent.com/52779957/90405581-89ef3580-e0d6-11ea-8621-90e1a36dd992.png)

I find a way by deep link that works for webapp, and it could open a new page with the link:
https://teams.microsoft.com/multi-window/chats/<chatId>

However, when clicking into the deep link inside Teams desktop, it would open a new webpage but not a popped-up window.
I used the microsoftTeams.executeDeepLink(url) for a test as well, but no window is popped up.

Do you know if it is doable that, we could pop up a 1:1 chat in a app via Teams SDK. So that the user could see the 1:1 chat but not leaving the Teams App.

Thanks,
Jinkai

**Comment by VaraPrasad-MSFT** [comment]
Currently it is not possible.

**Comment by loksayi** [comment]
Is there any update for it ?

**Comment by VaraPrasad-MSFT** [comment]
No, Currently we do not have any ETA to share.

**Comment by kolysg** [comment]
Is there any update on this? @VaraPrasad-MSFT

**Comment by ChetanSharma-msft** [comment]
Hello @kolysg, @loksayi, @JinkaiZhang1989,
Thanks for reporting this issue.

We will check it internally with engineering team and get back to you.

**Comment by Prasad-MSFT** [comment]
There doesn't seem to be any way to do so. To achieve your requirements, we recommend you give your feedback in Teams [UserVoice](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472). 

Microsoft will always focus on customer’s feedback and experience. Some new features would be added to the services based on customers' feedback in the future, and your good ideas will be very helpful for them to improve the service.
