### ISSUE TITLE
saveEvent.notifyFailure not working on Android and IOS

### ISSUE THREAD

**Issue by fsxin** [OfficeDev/microsoft-teams-library-js#383]
No error message is displayed when use saveEvent.notifyFailure function on Android and IOS, and setting page will be closed

**Comment by VaraPrasad-MSFT** [comment]
Could you please give us more information regarding the problem you are facing.

**Comment by fsxin** [comment]
Open setting page for custom app and enter relevant information, click save button and it does information validation , the error message will displayed on setting page  when validation fails . Register the callback function by registerOnSaveHandler((evt: SaveEvent) => void), display error message by SaveEvent.notifyFailure(string). It works fine on PC, but it not working on Android and IOS, the expected result is setting page not close and display error message when validation fails, the actual result is setting page close and no error message is displayed when use SaveEvent.notifyFailure(string).
Thanks

**Comment by fsxin** [comment]
> Could you please give us more information regarding the problem you are facing.

Open setting page for custom app and enter relevant information, click save button and it does information validation , the error message will displayed on setting page  when validation fails . Register the callback function by registerOnSaveHandler((evt: SaveEvent) => void), display error message by SaveEvent.notifyFailure(string). It works fine on PC, but it not working on Android and IOS, the expected result is setting page not close and display error message when validation fails, the actual result is setting page close and no error message is displayed when use SaveEvent.notifyFailure(string).
Thanks

**Comment by VaraPrasad-MSFT** [comment]
Are you doing authentication ? can you share some screenshots.
