### ISSUE TITLE
chatId is never being populated.

### ISSUE THREAD

**Issue by unckleg** [OfficeDev/microsoft-teams-library-js#386]
- chatId is never being populated.

**Comment by Nikitha-MSFT** [comment]
Which chat id you are referring to? Could you please share your scenario in more detail?

**Comment by unckleg** [comment]
@Nikitha-MSFT 

```javascript
microsoftTeams.getContext(context => {
  console.log(context.chatId);
}); // This function is being invoked in task module in the meeting chat.
```

One more thing, is there any way for getting chat members from the task module with microsoft-teams lib ?

**Comment by unckleg** [comment]
@ydogandjiev Thanks 🙏

**Comment by Nikitha-MSFT** [comment]
We are not able to reproduce the issue at our end. Could you please try this code?

```
microsoftTeams.getContext(function (context) {
            alert(JSON.stringify(context.chatId));
            console.log(context)
        });
```

try if that helps.

**Comment by vman** [comment]
I have seen that the chatId is only populated if you are in the context of a personal chat (1:1) or a group chat. If you are in the context of a teams channel, the chatId will be empty.

**Comment by Nikitha-MSFT** [comment]
Could you please share the screen shots of personal chat, group chat and in teams channel?

**Comment by vman** [comment]
@Nikitha-MSFT I didn't mean to report that as a bug. Was trying to add more details to maybe explain the behaviour OP was seeing. I think the chatId being empty in a teams channel is by design as we are not in the context of a chat then.

**Comment by Nikitha-MSFT** [comment]
@vman - Yes, You will get a chat Id only in the tabs in a group chat context, Chatid in teams channel is empty that is by design.
