### ISSUE TITLE
Cryptic “handleMessageError” when trying to install a Microsoft Teams app

### ISSUE THREAD

**Issue by brandonweiss** [OfficeDev/microsoft-teams-library-js#388]
Hey! Alright, so I’ve been working on building a Microsoft Teams app for a little while now and although I’ve been able to figure out most things, I’ve completely hit a wall on this error. Here’s what I’ve done.

I created a Connector in the connector portal. The configuration URL is `https://216a8c7c0af5.ngrok.io/microsoft-teams`, which is a tunnel that points to my development environment locally. The connector’s ID is `f5dbf883-8cd3-4b15-b5c7-63047806e143`.

I made a manifest that looks like this:

```json
{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.7/MicrosoftTeams.schema.json",
  "manifestVersion": "1.7",
  "id": "f5dbf883-8cd3-4b15-b5c7-63047806e143",
  "version": "1.0.0",
  "packageName": "com.ghostinspector.app",
  "name": {
    "short": "Ghost Inspector"
  },
  "description": {
    "full": "Ghost Inspector makes it simple to ensure your website is working properly — with no programming or testing experience required. Whether your team is made up of engineers, manual testers, or people who are brand new to testing, our intuitive tools will help you accomplish your goals.",
    "short": "Automated website testing made easy"
  },
  "developer": {
    "name": "Ghost Inspector",
    "websiteUrl": "https://ghostinspector.com",
    "privacyUrl": "https://ghostinspector.com/privacy",
    "termsOfUseUrl": "https://ghostinspector.com/terms"
  },
  "accentColor": "#6dc372",
  "connectors": [
    {
      "connectorId": "f5dbf883-8cd3-4b15-b5c7-63047806e143",
      "scopes": [
        "team"
      ],
      "configurationUrl": "https://216a8c7c0af5.ngrok.io/microsoft-teams"
    }
  ],
  "icons": {
    "outline": "outline.png",
    "color": "color.png"
  },
  "permissions": [
    "identity",
    "messageTeamMembers"
  ],
  "showLoadingIndicator": true
}
```

The IDs match and the configuration URL matches. I zipped it up and sideloaded it into Microsoft Teams. When I try to install it on a channel, the modal pops up and while it’s loading I see my first confusing error in the console.

```
2020-08-19T22:14:57.292Z AppsService: getInstalledAppForTeam - Invalid teamId and/or appId specified
```

What does that mean and how do I fix it?

When my application loads in the iframe, I configure what I need to configure, the “Save” button is enabled, I click “Save”, and see the next error in the console.

```
2020-08-19T22:16:58.592Z Received error from connectors {"seq":1597867821123,"timestamp":1597875418575,"flightSettings":{"Name":"ConnectorFrontEndSettings","AriaSDKToken":"d127f72a3abd41c9b9dd94faca947689-d58285e6-3a68-4cab-a458-37b9d9761d35-7033","SPAEnabled":true,"ClassificationFilterEnabled":true,"ClientRoutingEnabled":true,"EnableYammerGroupOption":true,"EnableFadeMessage":false,"EnableDomainBasedOwaConnectorList":false,"EnableDomainBasedTeamsConnectorList":false,"DevPortalSPAEnabled":true,"ShowHomeNavigationButtonOnConfigurationPage":false,"DisableConnectToO365InlineDeleteFeedbackPage":true},"status":500,"clientType":"SkypeSpaces","connectorType":"f5dbf883-8cd3-4b15-b5c7-63047806e143","name":"handleMessageError"} 0-angular-jquery.min-eee9041.js:114:37
```

The logic inside my `registerOnSaveHandler` hook does fire. I can see data being created in my database. But after some number of seconds the save times out and I see this error message in the modal `Unable to save "Ghost Inspector" connector configuration. Please try again.`

I have no absolutely no idea what’s going wrong or how to fix it. The error message contains no useful information that I can see.

Here is the relevant code from my app if you’d like to see it.

```js
import * as microsoftTeams from '@microsoft/teams-js'

const initializeMicrosoftTeamsApp = () => {
  return new Promise((resolve) => microsoftTeams.initialize(resolve))
}

const getMicrosoftTeamsContext = () => {
  return new Promise((resolve) => microsoftTeams.getContext(resolve))
}

const getMicrosoftTeamsSettings = () => {
  return new Promise((resolve) => microsoftTeams.settings.getSettings(resolve))
}

initializeMicrosoftTeamsApp().then(() => {
  getMicrosoftTeamsContext().then(({ channelName }) => {
    $scope.channelName = channelName
  })

  getMicrosoftTeamsSettings().then(({ webhookUrl }) => {
    $scope.channelUrl = webhookUrl
  })

  microsoftTeams.settings.registerOnSaveHandler((saveEvent) => {
    // save some data

    const settings = {
      contentUrl: window.location.toString(),
      entityId: 'entityId',
    }

    microsoftTeams.settings.setSettings(settings, (data) => {
      // this callback does not seem to be getting called
    })

    saveEvent.notifySuccess()
  })
})
```

Am I doing something wrong? Is this a bug? Thanks for your help!

**Comment by Gousia-MSFT** [comment]
@brandonweiss Could you please verify few things here?
1.  Could you please confirm if you have added contentUrl in valid domains of your connector in connector dashboard? 
2. Please confirm if all the URL's you are trying to load are https url's.
3. Please check if you have set actions in connector dashboard properly.
4. Please confirm if you have added microsoftTeams.setValidityState(true) before registering save handler.

**Comment by brandonweiss** [comment]
@Gousia-MSFT Thanks for getting back to me so quickly!

1. I do not have the domain of the content URL defined as a valid domain in either the connector portal or the manifest. The content URL is the same as the configuration URL, and the [`validDomains` documentation](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#validdomains) says “If your tab configuration or content UI needs to navigate to any other domain besides the one use for tab configuration, that domain must be specified here”. That seems to imply that the domain of the configuration URL doesn’t need to be added as a valid domain. Is that correct or incorrect?
2. I’m only loading one URL (the configuration URL) and it is HTTPs.
3. I’m not entirely sure what that means… do you mean for the question “Do you want to enable actions on your Connector cards?” I have to choose “Yes”? If “No” is not a valid option, why am I even given a choice?
4. I’m registering the save handler when the page loads and then calling `setValidityState(true)` afterwards in response to user input. Does the save handler have to be defined _after_ the save button is enabled? 🙀 I can’t find anywhere in the documentation that says that. Also, I’m confused about how that would work if I have to call `setValidityState(false)` in response to user input. When I re-enable the save button for a second time, do I just call `registerOnSaveHandler` again? Or do I have to be careful to only call it once, the very first time `setValidityState(true)` is called?

Thanks again for your help!

**Comment by brandonweiss** [comment]
Also, one more thing about the fourth thing you suggested. The Node.js sample app you provide seems to call `registerOnSaveHandler` _before_ `setValidityState(true)`, similar to what I am doing.

https://github.com/OfficeDev/msteams-samples-hello-world-nodejs/blob/220474191703added9fd257b21761da209eb555e/src/static/scripts/teamsapp.js#L20-L48

Am I misunderstanding what is happening in the sample app?

**Comment by Gousia-MSFT** [comment]
@brandonweiss Could you please try this in the browser and see if you get any console errors? Could you please check the valid domains list at Connectors developer portal? It does not support wild card characters like (*.ngrok), It should be the same domain name as used for configuration URL and all lower case. Please check a similar issue [here ](https://github.com/MicrosoftDocs/msteams-docs/issues/1628#issuecomment-667209625)and see if this solution helps you.
