### ISSUE TITLE
[Question] On which devices does geolocation actually work?

### ISSUE THREAD

**Issue by benji24290** [OfficeDev/microsoft-teams-library-js#389]
In the [Request Permission - How-to Guide](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/native-device-permissions?tabs=desktop) ther is a important note "The geolocation API is currently not fully supported on all desktop clients."

On which devices does geolocation work? I am currently trying to get the location in a grouptab, in the web version of teams I get the location. In the mobile version (Android) and in the desktop version (Windows) I can query the permissions which are also "granted" but I don't get the location, I assume that the timeout is reached.
```javascript 

navigator.permissions.query({ name: 'geolocation' }).then((result) => {
      if (result.state === 'granted') {
        // Access granted
        this.setState({
          granted: `yes`
        })
      } else if (result.state === 'prompt') {
        this.setState({
          granted: `prompt`
        })
      } else {
        this.setState({
          granted: `granted?:${result}`
        })
      }
    }).catch(err => {
      this.setState({
        granted: `err: ${err.message}`
      })
});
if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition((pos) => {
        this.setState({
          location: { lat: pos.coords.latitude, lon: pos.coords.longitude }
        })
      }, (err) => {
        this.setState({
          location: `not: ${err.message}`
        })
      }, { timeout: 60000 })
} else {
      console.log('Geolocation is not supported by this browser.')
      this.setState({
        location: 'no loc allowed'
      })
}

```

`granted` is set to "granted" on all devices but `location` only in the browser version of teams or outside of the teams context (directly in the browser)

**Comment by VaraPrasad-MSFT** [comment]
@benji24290 , There is a feature request on this but currently we cannot give you an ETA on when this will be available

**Comment by benji24290** [comment]
@VaraPrasad-MSFT thank you very much for your feedback.
I understand that you can't give me a time frame for this, but I'm sure that many other developers would appreciate a summary of the available native features on the different platforms. This would make it easier to evaluate whether a team is suitable for an application.

**Comment by ffarguelles** [comment]
Mobile is now supported as I make it work. What about desktop? I'm getting error code 9000 (old platform) when trying to access the location or some media capabilities

**Comment by Sridevi-MSFT** [comment]
The getLocation API is in works on desktop/web clients and is not released yet.
