### ISSUE TITLE
Spell check unavailable in Custom Tabs on Desktop clients

### ISSUE THREAD

**Issue by ShadowXVII** [OfficeDev/microsoft-teams-library-js#393]
#293 is still an issue. 

Core issue posted here on UserVoice.
https://microsoftteams.uservoice.com/forums/908686-bug-reports/suggestions/40333423-bug-spell-check-proofing-tools-do-not-work-on-a

Affects all apps, such as Planner, Forms, Assignments, Education, Yammer, etc.

**Comment by Trinetra-MSFT** [comment]
@ShadowXVII This is a limitation of our Electron-based Desktop Client. Most browsers seem to provide built-in spell checking capabilities but it doesn't seem like that's been implemented/enabled in our Desktop Client.

Please look at articles discussing options for enabling spell checking in Electron, e.g.:
https://ourcodeworld.com/articles/read/485/how-to-implement-and-enable-the-grammar-and-spellchecker-in-electron-framework](https://ourcodeworld.com/articles/read/485/how-to-implement-and-enable-the-grammar-and-spellchecker-in-electron-framework)

**Comment by ShadowXVII** [comment]
Have you used teams?

The spellcheck exists in the electron desktop client everywhere except tabs. I.e chats work fine, but there's an issue with spell check flowing to other tabs.

**Comment by Trinetra-MSFT** [comment]
@ShadowXVII , Yes, above comment about the tabs only, Let me update it

**Comment by ShadowXVII** [comment]
But it should follow to IFrames?
https://github.com/electron/electron/issues/13514

It works fine on web (using non browser spellcheck)

**Comment by Trinetra-MSFT** [comment]
@ShadowXVII: We have an Feature raised for this.
	
As part of Electron 8+ rollouts, we have modified our spellchecker dictionaries implementation.  Going forward, we will be using native platform spellchecker (where available). i.e. just like Edge, on Windows 10, we will be relying on Windows 10 dictionaries. This improves overall spellchecking experience and will recognize terms - such as acronyms, URLs, etc. This feature is going through ERP reviews at the moment and will be rolled out to R1+ soon.
For Tab apps, we do not invoke spellchecker as the original requirement (AFAIK) is that the Apps provide their own. For example: OneNote, etc. I do realize that this is not entirely true for all of the apps so I believe we need some sort of flag for app devs to use Teams spellchecker or bypass it.  

Spellchecker v3 (future):

Future plans is to align with Office Editor Integration and use all the goodness from it (Proofing tools such as Synonyms...) - this is a long lead item and remains in backlog atm.

**Comment by ShadowXVII** [comment]
Thanks for the info. I use the proofing tools so would be good to see them in teams one day.

It's odd to assume tabs will do their own spellcheck. Especially with so many Microsoft apps like planner, yammer etc that would benefit from it and haven't provided their own.

Also, it's inconsistent because it works in web based versions but seems to have been turned off in desktop.

Anyway, hope we see some progress soon. We're delaying our adoption of tabs because we need spellcheck.

**Comment by Trinetra-MSFT** [comment]
Please feel free to reopen if you further query on this. This feature is in our backlog, we are working on it. once it is rolled out we will let you know.
