### ISSUE TITLE
parentMessageId contains the id of the top level message. But the id of the reply message seems to be missing.

### ISSUE THREAD

**Issue by vman** [OfficeDev/microsoft-teams-library-js#398]
Hello

When `teams-js` is loaded in a task module invoked from a message action and I have a look at the context object:

1) If the message action was invoked in a Teams channel top level message, the `parentMessageId` property contains the correct id of the top level message
2) However, if the message action is invoked on a reply to a top level message, I am not able to find a property which contains the id of the reply message (The `parentMessageId` property still contains the id of the top level message to which the reply was posted)

I am also not able to find a relevant property to look for in the docs: https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/microsoftteams.context?view=msteams-client-js-latest

Is there something I am might be doing wrong? Happy to provide more information if you need.

**Comment by Nikitha-MSFT** [comment]
That is by design. Are you facing any issue? could you please explain your scenario in more detail?

**Comment by vman** [comment]
When we invoke a message action on a reply in a teams channel, we want to open a task module. 

Inside that task module, we want to use teams js to know on which reply the message action was invoked. 

This is easy to do if the message action was invoked on a top level message in the thread as the parentMessageId propety contains the id of the top level message. 

But using teams js in the task module, how to get the id of the reply on which the message action was invoked?

**Comment by Nikitha-MSFT** [comment]
Bot will not receive the Reply id. That is by design. You need to get the reply id using [Get reply AP](https://docs.microsoft.com/en-us/graph/api/channel-get-messagereply?view=graph-rest-beta&tabs=http)I and pass it to task module.

**Comment by vman** [comment]
Hi @Nikitha-MSFT , the API you mention:
beta/teams/{teamId}/channels/{channelId}/messages/{messageId}/replies/**{replyId}**

needs a **replyId** to get the replies. From where do I get this? Also, do you have any examples of passing parameters to a task module?

**Comment by Nikitha-MSFT** [comment]
@vman -Yes, You can get reply id by using [list channel message replies](https://docs.microsoft.com/en-us/graph/api/channel-list-messagereplies?view=graph-rest-beta&tabs=http) Also you can pass parameter to task module along with your URL, if the URL accept parameter then you would be able to pass it. Could you please check this [code snippet](https://github.com/Abhijit-MSFT/TaskManagement/blob/master/TaskManagement/Bots/MessageExtension.cs#L233).
