### ISSUE TITLE
Bug: Cannot add our app tab to private channel.

### ISSUE THREAD

**Issue by abdulkareemnalband** [OfficeDev/microsoft-teams-library-js#399]
Cannot Add our application tab to private channel. No errors in settings page, but we get "we couldn't save your tab settings. please try again" In UI .
![image](https://user-images.githubusercontent.com/3139353/91703798-61684080-eb98-11ea-986b-91fc55ba9bab.png)

Adding tab to non private channels works great.

**Comment by VaraPrasad-MSFT** [comment]
Can you please share the manifest.

**Comment by abdulkareemnalband** [comment]
@VaraPrasad-MSFT 
here you go


[TeamsLocalhost.zip](https://github.com/OfficeDev/microsoft-teams-library-js/files/5154071/TeamsLocalhost.zip)

**Comment by VaraPrasad-MSFT** [comment]
Could you please change the loclhost urls to [ngrok ](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/debug#locally-hosted)and try.

**Comment by abdulkareemnalband** [comment]
@VaraPrasad-MSFT  it works fine when used with regular (I mean non private channels)
It only fails on private channel

Same thing happens with our hosted sites,

**Comment by abdulkareemnalband** [comment]
[DecisionsMaster2.zip](https://github.com/OfficeDev/microsoft-teams-library-js/files/5166118/DecisionsMaster2.zip)
Here is hosted one

**Comment by VaraPrasad-MSFT** [comment]
Thanks for reaching out to us ! We are checking this internally.

**Comment by abdulkareemnalband** [comment]
created #409
