### ISSUE TITLE
Teams authenticate doesn't work from add-in from Word within Teams client

### ISSUE THREAD

**Issue by avaneerd** [OfficeDev/microsoft-teams-library-js#404]
We have an Office web add-in that requires authentication, this add-in can be used in the majority of the office online suite (Word, Excel, etc.). 
When opening a Office document in Teams it opens that document in Office online embedded (iframe) in Teams. 
We can open our add-in from that view, but using `microsoftTeams.authentication.authenticate` will open a new window in an external browser.

We also have our own custom Teams tab, which uses the same authentication code and that works.
![image](https://user-images.githubusercontent.com/19610888/92375424-5b76e000-f101-11ea-932e-19b9c47c633c.png)

To me it seems that the authentication request is send to `window.parent` or `window.opener`. From an add-in in Office online that would be Word/Excel and not Teams.

**Comment by Manish-MSFT** [comment]
hi @avaneerd , We are investigating issue internally.

**Comment by Manish-MSFT** [comment]
hi @avaneerd , We are aware of this missing feature and have started discussions on ways to fix within the next few quarters. As of now, there is no clear timeline yet.

**Comment by nwojod-MSFT** [comment]
Hello @avaneerd. Apologies for the delayed response on this issue. We have raised this as a feature request on the Microsoft Teams portal for consideration. The product team will review this request against other requests on their backlog and prioritize accordingly. We cannot guarantee if or when this feature will be implemented. However, you can follow up on the request via this link https://feedbackportal.microsoft.com/feedback/idea/aa6f289b-ce92-ed11-a81b-000d3ae32cd0. Thanks for your patience.

**Comment by Wajeed-msft** [comment]
Closing this from the issues list. Please upvote if you have same feature request: https://feedbackportal.microsoft.com/feedback/idea/aa6f289b-ce92-ed11-a81b-000d3ae32cd0.
