### ISSUE TITLE
microsoftTeams.tasks.submitTask does not send task/submit message to bot from mobile Teams app (iOS)

### ISSUE THREAD

**Issue by sergeyv-creware** [OfficeDev/microsoft-teams-library-js#405]
1. Have bot replied to a user with following Hero card
```
    {
      "contentType": "application/vnd.microsoft.card.hero",
      "contentUrl": null,
      "content": {
        "title": "Title",
        "text": "description",
        "buttons": [
          {
            "type": "invoke",
            "title": "Edit",
            "value": {
              "id": "configuration",
              "type": "task/fetch"
            }
          }
        ]
      },
      "name": null,
      "thumbnailUrl": null
    }
```
2. User press Edit in bot reply
3. Bot receives task/fetch message and replies with
```
{
  "task": {
    "value": {
      "title": "Task",
      "height": 300,
      "width": "small",
      "url": "https://0123456789abcdef.ngrok.io/taskModule.html"
    },
    "type": "continue"
  }
}
```
4. Page loads fine in Teams App
5. Behind the page there is a script, that is supposed to submit data back to bot upon user clicks a button, see snippet below
```
microsoftTeams.initialize();

...

var cmdSave = document.getElementById('save');
cmdSave.addEventListener('click', function (ev) {
  ev.preventDefault();
  ev.stopPropagation();

  microsoftTeams.getContext(function (context) {
    microsoftTeams.tasks.submitTask({id: 'saveTest'}, 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb');
  });
})

```
6. Clicking Save button in task module page on mobile (iOS) leads to task module close, but does not perform data submission to the bot.
7. Clicking Save button in task module page on desktop (web or electron app) works as expected

this was tried with iOS app version 2.0.20 (1.077.2020082103) both public channel & Developer preview.
also following teams SDK versions were tried
https://statics.teams.cdn.office.net/sdk/v1.7.0/js/MicrosoftTeams.min.js
https://statics.teams.cdn.office.net/sdk/v1.5.2/js/MicrosoftTeams.min.js

This behavior is not observed on Teams app on Android version 1416 (1.0.0.2019112202)
This behavior is not observed on Teams app on Android version 1416 (1.0.0.2020081801)

**Comment by VaraPrasad-MSFT** [comment]
@sergeyv-creware , Thanks for reaching out. We are able to reproduce the issue at our end and raised a bug.

**Comment by Gousia-MSFT** [comment]
We are tracking this internally
