### ISSUE TITLE
Bug: Group Id is missing in context for settings  in private channel

### ISSUE THREAD

**Issue by abdulkareemnalband** [OfficeDev/microsoft-teams-library-js#409]
`groupId` is missing in teams context for private channel

**Comment by Gousia-MSFT** [comment]
@abdulkareemnalband Group id is undefined for private channels. The data you receive from the getContext call will be obfuscated to protect the privacy of the channel. Please check the document [here](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context#retrieving-context-in-private-channels)
