### ISSUE TITLE
openFilePreview returns "App does not have the required permissions for this operation"

### ISSUE THREAD

**Issue by andylwelch** [OfficeDev/microsoft-teams-library-js#410]
Hi,

My application uses the `openFilePreview()` function to navigate my application's Teams Tab to a file uploaded into that team.  This works perfectly in my private application instances, but when installed via the App Store I receive the following error result "App does not have the required permissions for this operation"

I managed to capture this error by passing a callback function as per [this commit](https://github.com/OfficeDev/microsoft-teams-library-js/commit/ceaa6bb649c5a4cbfde4cd2e090ec5f024d5a5d5)

An extract of my code:
```
function openFilePreview(filePreviewParameters, callback) {
  sendCustomMessage(
    'openFilePreview',
    [
      filePreviewParameters.entityId,
      filePreviewParameters.title,
      filePreviewParameters.description,
      filePreviewParameters.type,
      filePreviewParameters.objectUrl,
      filePreviewParameters.downloadUrl,
      filePreviewParameters.webPreviewUrl,
      filePreviewParameters.webEditUrl,
      filePreviewParameters.baseUrl,
      filePreviewParameters.editFile,
      filePreviewParameters.subEntityId,
    ],
    (success, result) =>
      console.log('openFilePreview', { success, result }) ||
      callback(success ? undefined : new Error({ message: result }))
  );
}

const file = {
   entityId,
   objectUrl,
   type,
   title,
};
openFilePreview(file, err => {
    if (err) {
      console.warn('openFilePreview: unable, using fallback', err);
    }
});
```

Output:
![image](https://user-images.githubusercontent.com/7505965/93175701-64a42480-f773-11ea-981c-f48312781800.png)

How should our application request this permission? Why is it working perfectly in our apps which have not been uploaded to the app store even though the `manifest.json` is functionally identical?

Thanks

**Comment by Nikitha-MSFT** [comment]
openFilePreview api is not available for 3P apps.

**Comment by andylwelch** [comment]
Oh, why not? It's a great feature! It works perfectly in my private apps too, just not the app from Teams store. Can this be reviewed please?

**Comment by Nikitha-MSFT** [comment]
We don't currently have plans to expose this API to 3P apps.
