### ISSUE TITLE
Teams SDK would throw error when call initialize multiple times

### ISSUE THREAD

**Issue by SLdragon** [OfficeDev/microsoft-teams-library-js#413]
Here is an simple example:

```html

<html>

<head>
  <title>Sample</title>
</head>

<body>
  <script src="https://statics.teams.cdn.office.net/sdk/v1.6.0/js/MicrosoftTeams.min.js"></script>

  <script type="text/javascript">
    microsoftTeams.initialize(window);

    microsoftTeams.getContext((context, error) => {
      console.log(context);
    });

    microsoftTeams.initialize(() => {
      microsoftTeams.authentication.getAuthToken({
        successCallback: (token) => {
          console.log(token);
        },
        failureCallback: (err) => {
          console.log(err);
        },
        resources: []
      });
    });
  </script>
</body>

</html>
```

And it would throw error:
![image](https://user-images.githubusercontent.com/5545529/93284060-baa3b700-f7c9-11ea-8e38-9b4c4a3659b0.png)

In our scenario, we have a SDK wrapper, which would call the init function to get SSO token:
```
    microsoftTeams.initialize(() => {
      microsoftTeams.authentication.getAuthToken({
        successCallback: (token) => {
          console.log(token);
        },
        failureCallback: (err) => {
          console.log(err);
        },
        resources: []
      });
    });
```

Outside the SDK wrapper, user may call Teams SDK initialize function himself like below:
```
    microsoftTeams.initialize(window);
```

Then this error would throw.

Any ideas about how to solve the problem?

**Comment by ydogandjiev** [comment]
@SLdragon, it appears that your are calling the `microsoftTeams.initialize()` API incorrectly. This API only takes an optional callback function as the first parameter and an optional list of supported parent/child origins as the second parameter. Can you help me understand why you are trying to pass the `window` object to this API? That is not correct and will not work.

**Comment by SLdragon** [comment]
@ydogandjiev , we are using teams toolkit 1.0.4, in this version, the generated template would contains this code:
```
 microsoftTeams.initialize(window);
```

But in the version 1.0.5, there is no window object:
```
 microsoftTeams.initialize();
```

Not sure whether it is a typo from Teams Toolkit VSCode extension
