### ISSUE TITLE
problem with setValidityState and ngrok

### ISSUE THREAD

**Issue by piekenpuil** [OfficeDev/microsoft-teams-library-js#418]
When running my app on localhost, and tunneling through ngrok, the code microsoftTeams.settings.setValidityState(true); doesn't seem to work. 
It does work when I have my app running in e.g. azure. 
Is this on purpose ? Makes it hard to debug.

**Comment by Trinetra-MSFT** [comment]
@piekenpuil , Did you mean you are not able to hit the `setValidityState `method on ngrok but when code is deployed over Azure it is working? You can try this code for the [configurationpage ](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page) here,

**Comment by piekenpuil** [comment]
@Trinetra-MSFT The code you're referring to is known to me. 
The setValidityState method is being hit, both when I run my app on localhost through ngrok, or when deployed in azure. But in the  ngrok scenario the code doesn't make the save button enabled. 
I get the same phenomenon when running [this](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page). 
No idea what is causing it. This type of code used to work in the past without any problems ! Bug in the new version of teams-js ? Bug in ngrok ? Problem with my pc ?

**Comment by Trinetra-MSFT** [comment]
@piekenpuil , Can you check your ngrok URL once for the configuration page, and provide code snippet that you are trying to we can check this at our end?

**Comment by KEMiCZA** [comment]
@piekenpuil in your WebApp make sure that SSL is disabled. I had the same issue, and after debugging without SSL ngrok will take care of the SSL tunneling.

**Comment by Wajeed-msft** [comment]
We are closing this issue from this tracking list. Please feel free to re-open if you are still experiencing the issue.
