### ISSUE TITLE
Yet another problem with notifySuccess and successCallback

### ISSUE THREAD

**Issue by GryaznovGI** [OfficeDev/microsoft-teams-library-js#419]
Hi all!

I know that this question has been asked many times. But I am stuck and need some help anyway. I have a tab app, and I am trying to authorize inside the third-party site (Trello) inside my app to get an access token.

I have the auth start-page with the address `https://dev95.planyway.com/standalone/html/standalone.html`. There is the page that I am calling the `authentication.authenticate(...)` method from.

I am passing the URL like `https://trello.com/1/authorize?callback_method=fragment&...` to authorize with Trello. It leads to the opening of a pop-up with the Trello auth page. I can pass through the auth process inside this pop-up and the auth end-page is opened inside the pop-up with the valid token. The auth end-page has the address `https://dev95.planyway.com/standalone/html/token.html`. As you see, the start and end auth pages are inside the same domain.

I am calling the `authentication.notifySuccess()` method inside the auth end-page, but the pop-up window still stays opened and  the successCallback method that I registered in the `authentication.authenticate(...)` method is not triggered.

There is the app manifest:

```
{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.7/MicrosoftTeams.schema.json",
  "manifestVersion": "1.7",
  "version": "1.0.0",
  "id": "<app id>",
  "packageName": "com.planyway.dev",
  "developer": {
    "name": "Planyway",
    "websiteUrl": "https://planyway.com",
    "privacyUrl": "https://planyway.com/legal/privacy-policy",
    "termsOfUseUrl": "https://planyway.com/legal/terms-of-use"
  },
  "icons": {
    "color": "color.png",
    "outline": "outline.png"
  },
  "name": {
    "short": "PlanywayDev",
    "full": "Planyway Team Planner and Calendar"
  },
  "description": {
    "short": "Planyway",
    "full": "Team Planner and Calendar for Trello"
  },
  "accentColor": "#FFFFFF",
  "staticTabs": [
    {
      "entityId": "planywayTab",
      "name": "Planyway",
      "contentUrl": "https://dev95.planyway.com/standalone/html/standalone.html",
      "websiteUrl": "https://planyway.com/",
      "scopes": [
        "personal"
      ]
    }
  ],
  "permissions": [
    "identity",
    "messageTeamMembers"
  ],
  "validDomains": [
    "planyway.com",
    "dev95.planyway.com",
    "*.planyway.com",
    "*.trello.com",
    "trello.com"
  ]
}
```

There is the "authenticate" code and "notifySuccess" code:

```
microsoftTeams.initialize(() => {
    microsoftTeams.authentication.authenticate({
        height: 720,
        width: 650,
        url: authUrl,
        successCallback: () => {
            alert('SUCCESS CALLBACK');
        },
        failureCallback: error => {
            alert('FAILURE CALLBACK');
        }
    });
});
```

```
microsoftTeams.initialize();
microsoftTeams.authentication.notifySuccess();
```

The SDK package version is 1.7.0

Hope for your help!
Thank you!

**Comment by Trinetra-MSFT** [comment]
@GryaznovGI , I tried to sideload your manifest within Teams, I was able to login through trello
![image](https://user-images.githubusercontent.com/50989436/93967329-983f0a00-fd84-11ea-84f0-eedf7e581803.png)

**Comment by GryaznovGI** [comment]
@Trinetra-MSFT , thank you for looking into it!

It is strange a lot. I've tried it just now, and the issue still exists.
I still see the empty authorization pop up after redirecting from the Trello auth page. And the successCallback is not triggered.

![image](https://user-images.githubusercontent.com/2621625/93970234-e1e52000-fd97-11ea-8bf7-956818b72f8c.png)

I can close it manually, and the failure callback is triggered in this case.

Your successful login is connected with the implementation details. The token is saving to local storage in end-auth page. And after app page reloading you are logged in.

There is a full code of the `token.html` page:

```
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Planyway</title>

    <script src="https://statics.teams.cdn.office.net/sdk/v1.7.0/js/MicrosoftTeams.min.js" crossorigin="anonymous"></script>
    <script type="text/javascript">
        if (window.location.hash) {
            microsoftTeams.initialize();

            let token = window.location.hash.substring(7);
            localStorage.planywayTrelloToken = token;

            try {
                microsoftTeams.authentication.notifySuccess();
            }
            catch (e) {
                localStorage.setItem('token', token);
            }
        }
    </script>
</head>
</html>
```

I've debugged it with dev tools and noticed the following. The token is successfully saved to local storage in line 13. But the call of `microsoftTeams.authentication.notifySuccess()` in line 16 is not leading to the closing of authorization pop up and the triggering of success callback. The catch block is not used too because there are no explicit errors.

Also, I've noticed that if I put the token page code to the initialization callback, this callback is never triggered.
I mean the following code example:
```
microsoftTeams.initialize(() => {
    let token = window.location.hash.substring(7);
    localStorage.planywayTrelloToken = token;

    try {
        microsoftTeams.authentication.notifySuccess();
    }
    catch (e) {
        localStorage.setItem('token', token);
    }
});
```

I assume the success callback is not triggered because the SDK is not initialized. But I don't know why.

I've changed the manifest to allow you to reproduce the issue. Please, check it again!

```
{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.7/MicrosoftTeams.schema.json",
  "manifestVersion": "1.7",
  "version": "1.0.0",
  "id": "861228c3-eefd-462f-9b13-24dae6530ac3",
  "packageName": "com.planyway.dev",
  "developer": {
    "name": "Rubius",
    "websiteUrl": "https://planyway.com",
    "privacyUrl": "https://planyway.com/legal/privacy-policy",
    "termsOfUseUrl": "https://planyway.com/legal/terms-of-use"
  },
  "icons": {
    "color": "color.png",
    "outline": "outline.png"
  },
  "name": {
    "short": "PlanywayDev",
    "full": "Planyway Team Planner and Calendar"
  },
  "description": {
    "short": "Planyway",
    "full": "Team Planner and Calendar for Trello"
  },
  "accentColor": "#FFFFFF",
  "staticTabs": [
    {
      "entityId": "planywayTab",
      "name": "Planyway",
      "contentUrl": "https://dev95.planyway.com/standalone1/html/standalone.html",
      "websiteUrl": "https://planyway.com/",
      "scopes": [
        "personal"
      ]
    }
  ],
  "permissions": [
    "identity",
    "messageTeamMembers"
  ],
  "validDomains": [
    "planyway.com",
    "dev95.planyway.com",
    "*.planyway.com",
    "*.trello.com",
    "trello.com"
  ]
}
```

Thank you a lot in advance!

**Comment by Trinetra-MSFT** [comment]
@GryaznovGI , No luck to repro this at my end, After following the complete login process, pop was getting closed and i was able to see the dashboard. Could you try to clear you cache and try?
![image](https://user-images.githubusercontent.com/50989436/94154113-31604480-fe9b-11ea-803c-f44fa5918d95.png)

**Comment by GryaznovGI** [comment]
@Trinetra-MSFT , thank you again!

I cleared the cache, but it didn't help.

I dug into your library code, and, as I noticed, the issue appears in the following calls chain.

In `authentication.notifySuccess` method after the call of `sendMessageRequestToParent('authentication.authenticate.success', [result]);` I fall into the branch:
```
const targetOrigin = getTargetOrigin(targetWindow);

// If the target window isn't closed and we already know its origin, send the message right away; otherwise,
// queue the message and send it after the origin is established
if (targetWindow && targetOrigin) {
  targetWindow.postMessage(request, targetOrigin);
} else {
  getTargetMessageQueue(targetWindow).push(request);
}
```

This branch starts with calling of `getTargetOrigin(targetWindow)`. And as a result, I am getting `null` because `parentOrigin` is null. And instead of calling `targetWindow.postMessage` I am getting `getTargetMessageQueue(targetWindow).push(request);`. It puts `authentication.authenticate.success` callback to the queue and it stucks there and prevents successive pop-up window closing. I assume it is because the origin is never established.

I tried to check why parentOrigin is null. There is the following code in `publicApi.initialize`:
```
try {
  // Send the initialized message to any origin, because at this point we most likely don't know the origin
  // of the parent window, and this message contains no data that could pose a security risk.
  GlobalVars.parentOrigin = '*';
  const messageId = sendMessageRequestToParent('initialize', [version]);
  GlobalVars.callbacks[messageId] = (
    context: FrameContexts,
    clientType: string,
    clientSupportedSDKVersion: string = defaultSDKVersionForCompatCheck,
  ) => {
    GlobalVars.frameContext = context;
    GlobalVars.hostClientType = clientType;
    GlobalVars.clientSupportedSDKVersion = clientSupportedSDKVersion;

    // Notify all waiting callers that the initialization has completed
    GlobalVars.initializeCallbacks.forEach(initCallback => initCallback());
    GlobalVars.initializeCallbacks = [];
    GlobalVars.initializeCompleted = true;
  };
} finally {
  GlobalVars.parentOrigin = null;
}
```

In the `finally` block `parentOrigin` is setting to the `null` value. And I assume it is the reason for the `getTargetOrigin(...)` fail in my case. But I don't know how it should work in this case and when the `parentOrigin` should be set. The only place where parentOrigin is setting up yet is `interbalApi.updateRelationships`. But looks like I never have this called and `getTargetOrigin(...)` is returning the origin only for the `initialize` method and never again.

But this SDK code is two years old and I sure it is completely tested and should work. Therefore it is my fault only. But I really stuck on it :)

I'll be glad for any insights!

**Comment by Trinetra-MSFT** [comment]
@GryaznovGI , Please take a look at this [sample code](https://github.com/ydogandjiev/taskmeow/tree/master/manifest/prod) and working manifest?

**Comment by Trinetra-MSFT** [comment]
Please feel free to reopen if you have further query on this.
