### ISSUE TITLE
microsoftTeams.authentication.getAuthToken within Tab Configuration, refresh the whole page after successful consent (First time usage only)

### ISSUE THREAD

**Issue by ministainer** [OfficeDev/microsoft-teams-library-js#420]
Hi, 

I have a complex configuration scenario that requires my tab configuration to be SSO enabled. I'm using microsoftTeams.authentication.getAuthToken to perform the SSO and it works fine with one simple glitch.  When I try to configure the tab for the first time, the authentication flow prompt the user to consent to the permission required. 
After user consent is successfully done the whole teams window is been refreshed and the user have to restart add tab scenario all over again.

I suspect that sendMessageRequestToParent is causing the Microsoft teams window to completely refresh is there any work around or parameter can stop the "parent" from refreshing?

How to reproduce, simply implement SSO within a Tab Configuration , video preview [here](https://insightme-my.sharepoint.com/:v:/g/personal/amr_365apps_com_au/EQrzYLqEsAZHsmrU_w6sXrYBrb4c4tT2mv8GPoqwOJjXOA?e=hJkk0d)

Thanks,
Amr

**Comment by Trinetra-MSFT** [comment]
@ministainer , Can you please look at this [SSO sample code](https://github.com/ydogandjiev/taskmeow/blob/master/manifest/prod/manifest.json) for configurable Tabs? You need to set SSO `?inTeams=true` in your configuration URL.

**Comment by Gousia-MSFT** [comment]
Please re-open if you still face any issues here
