### ISSUE TITLE
Doesn't work with Snowpack or Vite

### ISSUE THREAD

**Issue by niicojs** [OfficeDev/microsoft-teams-library-js#422]
This lib doesn't work with [Snowpack ](https://www.snowpack.dev/) or [Vite](https://github.com/vitejs/vite). I don't really know what's causing this but it's like there is no export when using those tools.
It seems they are the futur of dev tools so we should make this work.

**Comment by adityap31** [comment]
Hello, Is this issue addressed. As I too am trying msteamsjs with snowpack and vite.

**Comment by Prasad-MSFT** [comment]
@niicojs ,@adityap31- Could you please share console errors if you are getting any ? Is it working fine in iFrame?
