### ISSUE TITLE
Error when calling registerOnRemoveHandler on Connector

### ISSUE THREAD

**Issue by carlosvini** [OfficeDev/microsoft-teams-library-js#424]
When I try to register a remove handler on a connector it says:

> This call is not allowed in the 'settings' context

![image](https://user-images.githubusercontent.com/4670443/94933681-1bf1a880-04a1-11eb-8dbd-9385de425b1a.png)

I'm following the instructions from here https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-creating:

> Handling removals
> You can optionally execute an event handler when the user removes an existing connector configuration. You register this handler by calling microsoftTeams.settings.registerOnRemoveHandler(). This handler can be used to perform cleanup operations such as removing entries from a database.

Code:

```js
microsoftTeams.initialize()
microsoftTeams.settings.registerOnRemoveHandler((removeEvent) => {
   alert('removed')
})
```

What else should I do?

**Comment by Trinetra-MSFT** [comment]
@carlosvini , Could you please check this [sample code](https://github.com/OfficeDev/microsoft-teams-sample-connector-csharp/blob/master/TeamsToDoAppConnector/Views/Connector/Setup.cshtml) for connector setup page and handling remove Event?

**Comment by carlosvini** [comment]
Thanks @Trinetra-MSFT, I had already seen this sample code. Turns out I got it working by moving the registerOnRemoveHandler call immediately after initialize. This still doesn't make much sense to me, since the registerOnSaveHandler works just fine where it is, but I won't investigate any further.
