### ISSUE TITLE
Settings for Custom Tab in Teams

### ISSUE THREAD

**Issue by LaljiG** [OfficeDev/microsoft-teams-library-js#426]
If you go into amend Settings for a custom tab that you have created before, is there anyway to get the existing websiteUrl and contentUrl values in your configuration page?

The microsoftTeams.getContext method doesn't seem to make these Urls available (like it does entityId).

For a standard tab (e.g. Website, Word) when you go into amend the settings, Teams automatically pre-populates existing parameters like websiteUrl. So it has these values in it's own settings store. All these simply need to be made available via getcontext. It makes entityId available so why not the others.

**Comment by Trinetra-MSFT** [comment]
@LaljiG , [Tab context](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context#getting-context-by-using-the-microsoft-teams-javascript-library) doesn't return website URL and Content URL for custom tab, it return only teamsiteURL, What you can do to store the website URL/Content URL somewhere and reuse it. You can also check [get Tab](https://docs.microsoft.com/en-us/graph/api/teamstab-get?view=graph-rest-1.0) graph API if that helps

**Comment by aosolis** [comment]
Hello! In the configuration page you can call `microsoftTeams.settings.getSettings` to get the current configuration for the tab.
(https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/microsoftteams.settings?view=msteams-client-js-latest#getsettings--instancesettings--settings-----void-)

**Comment by Trinetra-MSFT** [comment]
Please feel free to reopen if you have further queries on this.
