### ISSUE TITLE
Wrong resource URL in manifest.json

### ISSUE THREAD

**Issue by maximo-calero** [OfficeDev/microsoft-teams-library-js#437]
Testing SSO, I found out when you build a Development.zip to test your Personal Tab the manifest.json has a wrong URL in the resource property.

In Visual Studio Code I assigned this value:

![image](https://user-images.githubusercontent.com/35887433/95942879-9c3ed480-0de4-11eb-9f93-a31a3cbf0895.png)

But in the manifest.json, inside Development.zip, I have this value:

![image](https://user-images.githubusercontent.com/35887433/95942759-53871b80-0de4-11eb-84b9-ffca2fd4e155.png)

**Comment by Abhijit-MSFT** [comment]
You need to provide your resource url. It will change for every application. Check [here ](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso#2-update-your-microsoft-teams-application-manifest)on how to build this url. Let me know if this is not what you are looking for

**Comment by maximo-calero** [comment]
I provided it, :
`    "webApplicationInfo": {
      "id": "37b95c2a-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
      "resource": "api://devmcalero.ngrok.io/37b95c2a-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
    }
`
But once you save the manifest.json in Visual Studio Code, the manifest.jsonof the development.zip, has the following content:
`    "webApplicationInfo": {
        "id": "37b95c2a-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
        "resource": "api://undefined/undefined"
    }
`

**Comment by Trinetra-MSFT** [comment]
@maximo-calero , Can you try to save your `webApplicationInfo `
 ```
"webApplicationInfo": {
    "id": "4xxxxx58xxxxxxxxxxxxxxxx57b6xxx",
    "resource": "api://yourNgrok.com/botid-4xxxxx58xxxxxxxxxxxxxxxx57b6xxx"
  }
```

**Comment by maximo-calero** [comment]
This issue is related with Microsoft Teams Toolkit as I saw today:
https://github.com/OfficeDev/microsoft-teams-app-quickstarts/issues/17
I think this issue can be closed.
Sorry, for the inconveniences
