### ISSUE TITLE
First 2 links in readme.md are broken

### ISSUE THREAD

**Issue by nmishr** [OfficeDev/microsoft-teams-library-js#438]
Clicking on the readme.me file in github leads to 404's

https://msdn.microsoft.com/en-us/microsoft-teams/
https://msdn.microsoft.com/en-us/microsoft-teams/jslibrary

**Comment by sbtron** [comment]
Cleaning out old bug, the first two links now point to -  https://developer.microsoft.com/microsoft-teams and https://docs.microsoft.com/en-us/javascript/api/overview/msteams-client which work.
Lets resolve this bug.

**Comment by sayali-MSFT** [comment]
@nmishr - We are closing this issue for now, Please feel free to reopen it, if required.

**Comment by v-chetsh** [comment]
@nmishr - We are closing this issue for now.
Please feel free to open it, if required.
