### ISSUE TITLE
When is registerOnRemoveHandler called?

### ISSUE THREAD

**Issue by quesurifn** [OfficeDev/microsoft-teams-library-js#439]
Hello, 

I'm developing an Office 365 connector for my company. 

It looks like clicking the garbage can doesn't call the registerOnRemoveHandler. (see attached)

In what scenarios does the handler get called? 

<img width="1246" alt="Screen Shot 2020-10-21 at 9 00 24 AM" src="https://user-images.githubusercontent.com/21092055/96730958-581b7900-137c-11eb-968e-7ec0426111cf.png">

**Comment by quesurifn** [comment]
Any update on this?

**Comment by quesurifn** [comment]
@shashishailaj @aosolis2

**Comment by Manish-MSFT** [comment]
Hi @quesurifn, microsoftTeams.settings.registerOnRemoveHandler() is called whenever remove button is clicked. You can perform your cleanup operations on registerOnRemoveHandler() event and be sure that Connector has been removed.

**Comment by quesurifn** [comment]
@Manish-MSFT Great. At the moment we add the removeUrl into the settings however the remove button doesn't load our remove page. I posted an example here: https://github.com/OfficeDev/microsoft-teams-library-js/issues/439

Do you mind helping me with this?

**Comment by Manish-MSFT** [comment]
@quesurifn could you please post your handler code here? and also is remove button triggering your handler?

**Comment by quesurifn** [comment]
@Manish-MSFT No. I don't think it's loading the page at all. Much less the javascript on the page. 

`class App extends TeamsBaseComponent {
  constructor() {
    super()
    this.state = {
      insideTeams: null,
      channelName: null,
      channelId: null,
      teamName: null,
      teamId: null,
      webhookUrl: null,
      authCode: null,
      flowStep: 'pre-authentication',
      error: false,
      isAlreadyAuthed: false,
      needsGraphAuth: false,
 
    }

    this.onCode = this.onCode.bind(this)
    this.startAuthentication = this.startAuthentication.bind(this)
  }

  startAuthentication() {
    window.location.href = getAuthUrl()
  }

  onClose() {
    if(process.env.NODE_ENV === 'development') {
      console.error("Modal Closed")
    }
  }

  debug(msg) {
    if(process.env.NODE_ENV === 'development') {
      console.debug(msg)
    }
  }

  async onCode(authCode, _params) {
    this.debug('On Code')
    try {
      const {data} = await service.getAuthCode(authCode)
      localStorage.setItem('token_state', JSON.stringify(data))
      this.setState({token: data})
      const responseObject = await service.finishChannelSetup(data.access_token, this.state)
      if (responseObject.success) {
        microsoftTeams.settings.setValidityState(true)
        this.setState({channel: responseObject.channel, connector: responseObject.connector ,flowStep: 'authenticated'})
      } else {
        this.setState({needsGraphAuth: true, flowStep: false})
      }
    } catch(e) {
      this.debug(e)
      this.debug('Catching')
      this.setState({error: e.message, flowStep: false})
    }
  }

  async componentWillMount() {
    const { error } = this.state

    const urlParams = new URLSearchParams(window.location.search);
    const inRemovalState = urlParams.get('removal')
    const inTokenState = urlParams.get('code')
    const insideTeams = await this.inTeams()

    if(insideTeams) {
      microsoftTeams.initialize()
      microsoftTeams.getContext((context) => {
        const entity = `teams-${context.teamId}-${context.channelId}`;
        this.setState({
            teamName: context.teamName,
            channelName: context.channelName,
            channelId: context.channelId,
            teamId: context.teamId,
            isAlreadyAuthed: localStorage.getItem(entity) ? true : false,
            flowStep: inRemovalState ? 'removal' : 'pre-authentication'
        });

        microsoftTeams.appInitialization.notifySuccess();
      });

      if(inTokenState) {
        await this.onCode(inTokenState, "")
      }

      microsoftTeams.settings.registerOnSaveHandler((saveEvent) => {
        const {channelId, channelName, teamId} = this.state
        const contentUrl = `https://${window.location.href}?name={loginHint}&tenant={tid}&group={groupId}&theme={theme}`
        const entity = `teams-${teamId}-${channelId}`;
        microsoftTeams.settings.setSettings({
            entityId: entity,
            contentUrl,
            configName: `Integration with ${channelName}`,
            removeUrl: `${window.location.origin}?removal=true`
        });

        console.log('Remove URL')
        console.log(`${window.location.origin}?removal=true`)

        microsoftTeams.settings.getSettings(async (settings) => {
          try {
            const channel_update_data =  {...channel, webhook_url: settings.webhookUrl};
            delete channel_update_data.created_at
            delete channel_update_data.updated_at

            await service.updateChannel(token.access_token, connector.id, channel.id, channel_update_data)
            localStorage.setItem(entity, true)
            saveEvent.notifySuccess()
          } catch(e) {
            console.error("ERROR THROWN")
            console.log(e)
            saveEvent.notifyFailure(e.message)
          }
        })
      })
    }
  }`

**Comment by quesurifn** [comment]
If there are syntax errors I apologize. I edited out all of our companies proprietary data

**Comment by quesurifn** [comment]
@Manish-MSFT Any update on this?

**Comment by Trinetra-MSFT** [comment]
@quesurifn , Closing this thread as Duplicate of #435 will be addressing issue there.
