### ISSUE TITLE
Trying to open task module. Using the HTML Sdk.

### ISSUE THREAD

**Issue by harshitagar** [OfficeDev/microsoft-teams-library-js#440]
I am trying to open the task module using the HTML sdk, It is working fine in WEB client of Teams but not in Desktop client. In desktop client it is trying to open my browsers tab.
Please give a solution fr it.
let taskInfo = {
    title: null,
    height: null,
    width: null,
    url: null,
    card: null,
    fallbackUrl: null,
    completionBotId: null,
};

taskInfo.url = "some url";
taskInfo.title = "Login Form";
taskInfo.height = 600
taskInfo.width = 900
submitHandler = (err, result) => {
    console.log(`Submit handler - err: ${err}`);
    console.log(`Submit handler - result\rName: ${result.name}\rEmail: ${result.email}\rFavorite book: ${result.favoriteBook}`);
};
microsoftTeams.tasks.startTask(taskInfo, submitHandler);

**Comment by Nikitha-MSFT** [comment]
We are not able to repro the issue at our end. Could you please check this [sample](https://github.com/OfficeDev/microsoft-teams-sample-task-module-csharp/blob/master/Microsoft.Teams.Samples.TaskModule.Web/Views/Home/Tasks.cshtml)?

**Comment by ChetanSharma-msft** [comment]
Hello @harshitagar - Sorry for delay in response.

Please let us know if your issue has resolved or need any help here ?

**Comment by harshitagar** [comment]
This is resolved. Thanks for the help here.
