### ISSUE TITLE
Personal tab does not carry over entity_id query parameter on iOS devices

### ISSUE THREAD

**Issue by synth** [OfficeDev/microsoft-teams-library-js#441]
Given: A Microsoft Teams app that implements Personal/Static tab and specifies entityID in the manifest and is viewed on an iOS device such as an iPad.
Expected: It loads the personal tab by passing along an entity id. 
Actual: The personal tab doesn't load on iOS because the entity_id query parameter is not passed along. The entity_id is passed along on all other platforms: Android, web and desktop. 

Here is the relevant portion of our manifest (note `myapp` is used in place of real values). 
```
    "staticTabs": [
        {
            "entityId": "myapp-personal",
            "name": "Profile",
            "contentUrl": "https://myapp.com/ms_teams/start?viewer=ms_teams",
            "websiteUrl": "https://myapp.com/ms_teams/start",
            "scopes": [
                "personal"
            ]
        }
    ],
```
Please let me know if you need more information.

**Comment by Nikitha-MSFT** [comment]
We are not able to repro it at our end. Could you please check this [example](https://github.com/ydogandjiev/taskmeow/blob/master/manifest/prod/manifest.json). Also could you please confirm , are you trying to getContext for iOS device? Are you not getting the entity id in context for iOS?

**Comment by synth** [comment]
@Nikitha-MSFT While I can install that example and pin the app into my desktop and web teams, it doesn't show up in android or ios teams. Further, I tried testing with other 3rd party apps and have the same issue where they don't appear in teams. I tried with: Polly, Zoom, and LucidChart. 

In my testing on ios and android, I deleted the databases, uninstalled the apps, logged out multiple times - but couldn't get these apps to appear on my android or ios devices despite being pinned in the desktop and web Teams apps. 

This is a separate issue, but its preventing me from testing the actual issue with TaskMeow. Thanks for your help.

**Comment by Nikitha-MSFT** [comment]
We are not able to repro the issue at our end. Did you install the app in the right Tenant? Could you please check and update?

**Comment by synth** [comment]
Yes, its definitely the correct tenant because as made sure to log out of all my devices and re-login using the exact same O365 credentials.

**Comment by Nikitha-MSFT** [comment]
Could you please share Your manifest and repro steps?

**Comment by synth** [comment]
@Nikitha-MSFT So, the issue above is not particular to our manifest - just to be clear. Are you able to see Zoom or TaskMeow pinned in your mobile app drawer in either iOS or Android?

That said, I'm still happy to send your our manifest. We'd like to send it to you privately. Can you tell us a recommended way to do that?

**Comment by Nikitha-MSFT** [comment]
Could you please drop a mail at microsoftteamsdev@microsoft.com.

**Comment by synth** [comment]
Hello. Do you kindly have an update for us on this? We have several customers who have brought this to our attention now.

**Comment by synth** [comment]
Hello. Is there any update on this? @Nikitha-MSFT  We have many customers now experiencing this.

**Comment by Nikitha-MSFT** [comment]
Did you drop mail to microsoftteamsdev@microsoft.com? Could you please send a mail again?

**Comment by synth** [comment]
@Nikitha-MSFT We had a call on December 22nd with Trinetra and we were able to reproduce the issue on your end. We left the call with an action for Microsoft to resolve the issue.

**Comment by synth** [comment]
Hello. We are having more and more customers report this issue. @Nikitha-MSFT I see you are assigned recently. Will there be progress soon on this? I am happy to help work with you to resolve this any time. Really appreciate your help! Otherwise, can you recommend a workaround for personal tabs in iOS? Thank you!

**Comment by Nikitha-MSFT** [comment]
Bug is Resolved now, we have tested this at our end, could you please also check and confirm?

**Comment by synth** [comment]
@Nikitha-MSFT thank you for following up. I have tested, but unfortunately the issue remains.

I got latest from the app and even fully uninstalled and reinstalled to be sure. But the same behavior shows the entity_id is passed back.

The MsTeams app shows:
Version 3.4.1
Build: 3.4.77.2021042303/48
Release branch: releasetrain-2021Mar15-T1

**Comment by devina10192** [comment]
Hi, @synth I am getting the same issues with an app submission that we are trying to publish on Microsoft. Did the issue get resolved for you? It's only coming for ios devices, static tabs are loading fine for android and web.

**Comment by synth** [comment]
This is still an issue for us as well :(

**Comment by Meghana-MSFT** [comment]
We see that the tab is loading properly in IOS, attaching a screenshot for your reference. 
![iosstatictab](https://user-images.githubusercontent.com/81138249/147762242-4c196626-4930-45e0-9743-73a98f7089a6.png)

**Comment by Meghana-MSFT** [comment]
@synth - Could you please confirm if its resolved or not?

**Comment by synth** [comment]
@Meghana-MSFT Yes, I believe it is fixed now! Thank you!
