### ISSUE TITLE
For an single tab APP, how to remove tabs to enhance user experience

### ISSUE THREAD

**Issue by lubobill1990** [OfficeDev/microsoft-teams-library-js#445]
I find several Apps in App market, like Planer, don't show any tab on the top of iframe.

I have already set "isFullScreen" to true, but there are still tabs shown. I can't find any document about how to hide tabs.

I find there's a function, enterFullscreen, but it doesn't work.

**Comment by ydogandjiev** [comment]
Hi @lubobill1990, the `isFullScreen` field in the app manifest is currently reserved for Microsoft-built apps as well as those deployed by tenant admins to the organizational catalog:
https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/overview#publish-to-your-organizations-app-catalog

For apps that are globally distributed via our Store we are obligated to show attribution to our customers making it clear that the experiences they are interacting within our apps are owned by different companies/developers and therefore adhere to different Privacy Policy and Terms of Use. The header & about tab we render on your behalf satisfies this requirement. We did recently reduce the vertical height consumed by our header and in the future we will look for further ways to make it even less intrusive; however, it's unlikely that we will be able to completely eliminate it.

**Comment by lubobill1990** [comment]
Thanks Yuri! @ydogandjiev
