### ISSUE TITLE
microsoft teams- user experience using the chats and looking at shared files.

### ISSUE THREAD

**Issue by baelan** [OfficeDev/microsoft-teams-library-js#450]
Currently when you go to view files on the chats, say chat for group 1, you can only view the documents and pics,... as list view. It is time consuming to check through these to find what you're looking for mentioned before on the chat. My team uses the chat option to collaborate instead of the teams part as we find it easier. It would be great if in all parts where you can share documents that they can be seen as lists as well as tiles.

![image](https://user-images.githubusercontent.com/74314328/98835565-7edb4580-2438-11eb-903b-f6465a8e7edb.png)
-- Here you do have the option

![image](https://user-images.githubusercontent.com/74314328/98835661-9b777d80-2438-11eb-995d-780078dfc8c4.png)
--- Here unfortunately you dont

It is a small thing but it could improve the user experience very much.

Many thanks

**Comment by Trinetra-MSFT** [comment]
@baelan , This is by Design as of now for group chat, You can raise a [Microsoft Teams UserVoice](https://microsoftteams.uservoice.com/forums/555103-public/filters/new) for the same.
