### ISSUE TITLE
If there is no message in the channel for a period of time, then notify. How to achieve it?

### ISSUE THREAD

**Issue by real-liyongsheng** [OfficeDev/microsoft-teams-library-js#452]
If there is no message in the channel for a period of time, then notify. How to achieve it?
In addition, how to implement the archive team button in the notification message?

**Comment by VaraPrasad-MSFT** [comment]
@real-liyongsheng : There is no direct way to implement this. Every interval you need to check channel messages using [API ](https://docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&tabs=http)and look for if any update is there. If there is no update, notify it.

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
