### ISSUE TITLE
Url with portnumber in Content URL not working on ios

### ISSUE THREAD

**Issue by ernie76** [OfficeDev/microsoft-teams-library-js#453]
I have a Manifest for a Personal tab with this example URL for the "Content URL" 
https://example:8443/tab
This is not loading on the iphone teams app.
If I change the URL to 
https://example/tab
its working.

Sven 
 Scholz

**Comment by Trinetra-MSFT** [comment]
@ernie76 , is this issue with the iPhone only or other platform? Did you tried to add your URL in app manifest validDomain[] array? Please share your manifest so we can check it at our end. you can share it directly to `microsoftteamsdev@microsoft.com `

**Comment by ernie76** [comment]
the issue is only on the iphone. i have test on android, there is it working

@Trinetra-MSFT i have send a mail with the test Manifest to you

**Comment by ernie76** [comment]
I think i found the error
Under validDomains there is missing the domain with the portnumber
With the App Studio in Teams, the port number is not accepting.
with a texteditor and uploading its working

**Comment by Trinetra-MSFT** [comment]
@ernie76 , Yes, App Studio is not accepting the URL with Port Number, it can be a Bug need to confirm this with engineering team. but I believe by putting it manually in validDomain[] array it is working. Are you still seeing this issue over iPhone device?

**Comment by ernie76** [comment]
its working with the iphone, if I put it manually in validDomain[].

**Comment by Trinetra-MSFT** [comment]
@ernie76 , Great! As of now I'm closing this thread. I will check about App Studio validDomain[] port number URL issue internally.
