### ISSUE TITLE
authenticate: Cannot read property 'width' of null

### ISSUE THREAD

**Issue by DaleyKD** [OfficeDev/microsoft-teams-library-js#454]
# Description
When attempting to use the `registerAuthenticationHandlers` function to "pre-set" the AuthenticateParameters for later use, it works great the first time.  However, if an error occurs, when you click the Login button again (which invokes `authenticate`), it fails, and you get the error `MicrosoftTeams.min.js:1 Uncaught TypeError: Cannot read property 'width' of null`.

# Reproduction Steps
1. Use the following code snippets to setup a sample page.  The `url` doesn't need to be valid for this to work.
``` html
<div>
    <button onclick="testClick()">Login</button>
</div>
```

``` javascript
    <script src="https://statics.teams.cdn.office.net/sdk/v1.7.0/js/MicrosoftTeams.min.js" integrity="sha384-00JbifySIlPvW32u9rSurgu8PujfL6XFdV9iNn4ZWyurJJ33MFvpwPqmCHDq9ADv" crossorigin="anonymous"></script>

    <script>
        microsoftTeams.initialize();
        microsoftTeams.appInitialization.notifyAppLoaded();
        microsoftTeams.authentication.registerAuthenticationHandlers({
            url: "/authentication/authstart",
            width: 1024,
            height: 768,
            successCallback: function (result) {
                console.log("Success: " + result);
            },
            failureCallback: function (reason) {
                console.error(reason);
            }
        });

        microsoftTeams.appInitialization.notifySuccess();

        function testClick() {
            microsoftTeams.authentication.authenticate();
        }
    </script>
```
2. Click Login.
3. QUICKLY (super fast... like Lightning McQueen fast!) close the dialog popup (your dev tools console should have an error "CancelledByUser")
4. Click Login again.
5. Note the error in your dev tools console.

**Comment by Manish-MSFT** [comment]
We are investigating this issue internally.

**Comment by DaleyKD** [comment]
> We are investigating this issue internally.

Thanks, @Manish-MSFT . While minor, it'll be a bug our QA team will find.

**Comment by Manish-MSFT** [comment]
@DaleyKD, We have raised a bug for this.

**Comment by Manish-MSFT** [comment]
@DaleyKD  I think you would be calling calling the authenticate API with no parameters.Also, there is no API call registerAuthenticationHandlers.

**Comment by DaleyKD** [comment]
@Manish-MSFT : I'm not sure what you're trying to say.

There is absolutely a function called `registerAuthenticationHandlers`, and it's even documented in your code:
https://github.com/OfficeDev/microsoft-teams-library-js/blob/34c3e77d780a1fdbefb823830b1da4e9e97d5bd2/src/public/authentication.ts#L20-L26

Then when you call `authenticate`, line 31 shows that the `authenticateParameters` can be `undefined` (it's marked with a `?`).  On line 32, it checks if it is `undefined`, and if it is, it uses the one that you registered in `registerAuthenticationHandlers`.
https://github.com/OfficeDev/microsoft-teams-library-js/blob/34c3e77d780a1fdbefb823830b1da4e9e97d5bd2/src/public/authentication.ts#L28-L33

**Comment by ydogandjiev** [comment]
@DaleyKD, please do not use the `registerAuthenticationHandlers` API. This API was added by mistake and creates broken flows and incorrect expectations. The authParams passed to authenticate are used to return the status of the operation back to you, the caller. Once the authenticate call succeeds or fails the authParams are cleared and are no longer relevant. The `registerAuthenticationHandlers` API creates the incorrect expectation that these auth handlers can somehow persist and be re-used across multiple `authenticate` calls which is not the case. Apologies for the confusion. I will look into updating our documentation to make this clear.

**Comment by DaleyKD** [comment]
That really sucks. This is going to set us back a few days of development work because of how we designed our auth flow.

**Comment by DaleyKD** [comment]
If you can find ANY way to keep it or something similar to let us "globally" register the success/fail callbacks, that'd be helpful.

I don't like the idea of having to do an `authenticate({})` call all the way down at my `<LoginButton onClick={} />` and find a way to bubble up the error message so that I can display it.

**Comment by ydogandjiev** [comment]
@DaleyKD, have you take a look at my sample app here:
https://github.com/ydogandjiev/taskmeow

Specifically, the authentication service found here:
https://github.com/ydogandjiev/taskmeow/blob/ce434b102527a2ec7d26a08f42772426f882394f/src/services/teams.auth.service.js#L38

And the authentication UI logic here:
https://github.com/ydogandjiev/taskmeow/blob/ce434b102527a2ec7d26a08f42772426f882394f/src/App.js#L60

I tried to abstract most of the SDK authentication calls out of the actual components and simplify the error handling via promises.

**Comment by DaleyKD** [comment]
Welp, I was greatly mistaken on the amount of time it was going to take!!  I think I found my fix for at least now.  While the future may make it hard for me to bubble certain objects up from a lowly `<LoginButton />` control up to our main `<App />` for use in its state (mind you, this is my very first React/SPA app), for the time being, we should be good.  You can close this if you'd like.
