### ISSUE TITLE
microsoftTeams.authentication.authenticate method open popup windows in random locations when in desktop app

### ISSUE THREAD

**Issue by baileyg2016** [OfficeDev/microsoft-teams-library-js#461]
SDK version: 1.5.2
React version: 16.9.0

microsoftTeams.authentication.authenticate method open popup windows in random locations when in desktop app. This can make it hard for a user to find the popup and should be found in the center of the screen. In the teams web client, the popup opens in the center of the screen and would expect the same in the desktop client.

**Comment by lokimeyburg** [comment]
Thanks for submitting this @baileyg2016. Yeah, I can see how that would be frustrating. This is probably something to do with our Electron client. Will get back to once we know more about what's going on and how we can address it.
