### ISSUE TITLE
Allow Paste and Match Style to be set to Ctrl-V / ⌘-V

### ISSUE THREAD

**Issue by phillyc** [OfficeDev/microsoft-teams-library-js#463]
I'm opening this issue here, as it's the closest thing I could find to directly influence the Teams application as a whole. No offense intended, if this isn't he appropriate forum.

In the Teams app, you can Ctrl-V to paste from clipboard. This frequently carries formatting information like font style, size, and weight. There is also an option to Paste and Match Style, which just pastes plaintext and allows Teams to match it to the current style setting of the conversation box.

It would be wonderful to invert these, so that the default is Paste and Match Style. It's very rare that I want to paste with the formatting option from my other text sources.

**Comment by RamaMohanaChary** [comment]
Hi @phillyc,

Could you please reach out to [Product Support Channels](https://docs.microsoft.com/en-us/microsoftteams/platform/feedback#product-support-channels) on this question.

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
