### ISSUE TITLE
Request: Obtain version of app in context

### ISSUE THREAD

**Issue by DaleyKD** [OfficeDev/microsoft-teams-library-js#465]
Is there any way for us to obtain the version of our app (the one that's in the app manifest .json) via JavaScript?  It would be extremely helpful for us to be able to get that via the context object (`getContext()`) so that we could ensure that our client is using the latest version of our app, since it'll be sideloaded into an organization.

**Comment by DaleyKD** [comment]
Bump.

**Comment by Wajeed-msft** [comment]
@DaleyKD - Apologies for the delay in response. Currently Teams SDK doesn't allow you to get the app version information. However, you could pass query string parameter in your Tab URL set in your App Manifest:
>Ex: https://myapp.com?ver=1.2

You can read this parameter in your code and match it against server version.

Let me know if this works for you.

**Comment by DaleyKD** [comment]
Totally understand the workaround.  Is this something you can possibly put on a roadmap as an enhancement request to include in the context object? It seems like it might be helpful for some of the app manifest to be readable in the context object (or some other API call).

**Comment by Wajeed-msft** [comment]
Graph APIs to get installed app details are already available. Could you please take a look at [Get Installed App Details](https://docs.microsoft.com/en-us/graph/api/team-get-installedapps?view=graph-rest-1.0&tabs=http#example-2-get-the-names-and-other-details-of-the-installed-app) documentation? Let me know if that works for you.

**Comment by DaleyKD** [comment]
@Wajeed-msft : That's a GREAT Graph API endpoint. I didn't even realize that particular one existed. My only question on that is: is there any **easy** way for the current app to authenticate itself to use a bearer token?  Seems like a lot of work to setup a client ID/secret so that your Teams App can get a bearer token just to get info about itself.

**Comment by Wajeed-msft** [comment]
For getting just the version number of app, query string is simplest option. 

@ydogandjiev - Do we have any plans to include app information as part of tab context?

**Comment by wictorwilen** [comment]
@Wajeed-msft 

> For getting just the version number of app, query string is simplest option.

This will not work for channel tab as the URL is set upon configuration. What if you want to find out if the customer upgraded to a newer version of your app/manifest?

**Comment by Wajeed-msft** [comment]
This is accepted as feature request:  https://github.com/OfficeDev/microsoft-teams-library-js/issues/1196
