### ISSUE TITLE
Add ipynb rendering support to file preview tab.

### ISSUE THREAD

**Issue by ddsmit** [OfficeDev/microsoft-teams-library-js#468]
If you click a HTML in the "Files" tab of a channel, it will show a preview of the HTML file in Teams. Adding the ability to preview a ipynb file (ie Jupyter notebook) would be very helpful for a lot of the work that I do. 

Github has a nice implementation of a ipynb preview that could be used as a reference (although I cannot speak to whether plotly charts will render).

If this is not the correct repo to put in this issue, please guide me to the correct repo. I'd be willing to try and add the capability myself too with some guidance. I have another issue I wanted to address about Plotly charts not rendering in the HTML preview (although it works in Chrome and Edge), but I wanted to make sure I was looking at the correct repo first.

**Comment by Manish-MSFT** [comment]
Hi @ddsmit, This is an upcoming feature in MS Teams and I don't have ETA as of now, but this feature has already been noted down by Teams Engineering Team. I think in future releases will address this issue soon. Thanks.

**Comment by Trinetra-MSFT** [comment]
Please feel free to reopen if you have further query on this
