### ISSUE TITLE
how to detect that your embedded tab is in teams

### ISSUE THREAD

**Issue by Venipa** [OfficeDev/microsoft-teams-library-js#469]
is there any way to have a variable which declares that the app is in a teams environment?
Need such flag to enable additional UI changes for teams only.

**Comment by VaraPrasad-MSFT** [comment]
Currently this is not possible.

**Comment by wictorwilen** [comment]
See https://github.com/wictorwilen/msteams-react-base-component/blob/3a4f3c076a8092864d050376edfb76d9a19ad1f2/src/useTeams.ts#L9 for a reference implementation

**Comment by ydogandjiev** [comment]
Thanks for chiming in @wictorwilen. The code in your project will work today; however, it does make assumptions about the iframe name which are not officially documented and could change in the future. The only safe way to do this is to add an explicit QSP to the URLs your app loads in Teams that your code can then use as a signal. For example, when specifying the `contentUrl` in your app manifest or passing it to the `setSettings` API during tab configuration you can add the `&inTeams=true` parameter (the exact name is up to you) which your page can then check for when determining if it's being loaded in Teams or not. Of course, if you are redirecting to other pages you will need to make sure the `inTeams` parameter is correctly passed along.

**Comment by wictorwilen** [comment]
@ydogandjiev - I know, but this as it is right now this is the best method (and also this same method is used throughout many of the Microsoft published code samples). Using the SDK is not a good approach as you have to try to get the context and have a timeout to see if it does not return (see this previous implementation I used: https://github.com/wictorwilen/msteams-react-base-component/blob/9cf224a9e69894f51a88f9b5c694b0be1b55603c/src/index.tsx#L40).

This is not a new request and I do think the SDK should have it natively; either through a native SDK method or if you stopped using old style callbacks and used promises - then the `getContext` could reject if not in Teams.

**Comment by olafur164** [comment]
We use:
```
const userAgent = window.navigator.userAgent.toLowerCase();
const isTeamsUserAgent = userAgent.includes('teamsmobile');

export const isInTeams = () => isTeamsUserAgent || window.parent !== window;
```

**Comment by marekcis** [comment]
We use:
```
const getEmbeddedBy = (): string => {
  return (window.location !== window.parent.location) ? document.referrer : document.location.href;
};

const isEmbeddedByMsTeams = (): boolean => {
  return (window !== window.top) && getEmbeddedBy().startsWith('https://teams.microsoft.com');
};

const isEmbeddedByMsTeamsNative = (): boolean => {
  return navigator.userAgent.toLocaleLowerCase().includes('electron') && isEmbeddedByMsTeams();
};
```

**Comment by v-chetsh** [comment]
@Venipa  - Could you please confirm if your issue has resolved with above suggestion or still looking for any help?

**Comment by Venipa** [comment]
setting a query parameter in the teams manifest indicating that the app IS running under teams, we successfully could distinguish between teams and non teams context without any problems so far.
