### ISSUE TITLE
Result parameter from successCallback is an object instead of a string on Android

### ISSUE THREAD

**Issue by guiconti** [OfficeDev/microsoft-teams-library-js#473]
I have a Microsoft Teams app that requires the user to authenticate to access its features. As part of the authentication flow, I call the `authenticate` function from Microsoft Teams javascript SDK. The `successCallback` for the `authenticate` function is called with a `result` parameter that should be a `string`. That is the case for the web, desktop, and iOS versions. However, on Android I am getting an `object` instead of a `string`. All the calls are exactly the same across all platforms on both my frontend and backend.

I have printed the `result` right after the `successCallback` function is called on Android to test this.

Here's the code

```
microsoftTeams.initialize(() => {
	microsoftTeams.authentication.authenticate({
		url,
		successCallback: result => {
			console.log('Success callback', result);
```

Log on Microsoft Teams running on Desktop
![image](https://user-images.githubusercontent.com/17715786/102513852-bce01080-4059-11eb-8a45-4993d8046552.png)

Log on Microsoft Teams running on Android
![image](https://user-images.githubusercontent.com/17715786/102512652-45f64800-4058-11eb-869b-856b213c27c5.png)

**Comment by RamaMohanaChary** [comment]
Hi @guiconti, we have raised a bug for this.

**Comment by formulahendry** [comment]
+1.
Our customer also meets with the similar issue: https://github.com/OfficeDev/TeamsFx/issues/4859
It only happens when it is Android device.

**Comment by Prasad-MSFT** [comment]
As mentioned [here](https://github.com/OfficeDev/TeamsFx/issues/4859#issuecomment-1120123609) this issue has been fixed. And this fix is available in the beta version of the @microsoft/teamsfx SDK: https://www.npmjs.com/package/@microsoft/teamsfx/v/0.7.1-beta.c23501411.0

You could try this beta version in you Teams app.
