### ISSUE TITLE
How create tabs inside search based extension messages?

### ISSUE THREAD

**Issue by brunokunace** [OfficeDev/microsoft-teams-library-js#474]
Hi, idk if this is the most place to call it, but i dont see it on documentation

how i make this tabs (Recents, Reports) inside a search extension message?

like this:
![image](https://user-images.githubusercontent.com/16597320/102690353-8b934c00-41e3-11eb-9b87-a39a9057a83a.png)

sorry if i cant put this issue here, but i not see it in any other place.

thanks

**Comment by Manish-MSFT** [comment]
Hi @brunokunace , These are actually called messaging extension search commands. Please try providing multiple commands by providing id's, title and other fields to render them as tabs.[This](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/search-commands/define-search-command#manually-create-a-command) documentation serves as best reference guide.
