### ISSUE TITLE
Background filters API

### ISSUE THREAD

**Issue by LeonardoZivieri** [OfficeDev/microsoft-teams-library-js#478]
Hi, I am creating an application that needs an API that changes camera filters in calls. I need to save an image in the filter list and select it, also list existing filters if possible.

**Comment by Manish-MSFT** [comment]
Thanks for reaching out to us. We are the developer support team for Microsoft teams focused on helping developers resolve their code issues. For issues related to teams product, please reach out to the [Product support channels](https://docs.microsoft.com/en-us/microsoftteams/platform/feedback#product-support-channels) for Microsoft Teams.

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
