### ISSUE TITLE
Consuming results from `getContext()`

### ISSUE THREAD

**Issue by marwalsch** [OfficeDev/microsoft-teams-library-js#480]
This might be a noob question to some but I just cannot get my head around how the result `getContext()` is intended to be used properly, as it appears to be an asynchronous callback. I need the context's `loginHint` to fetch some data, which would look like:

```
        microsoftTeams.getContext(async (context) =>
            this. user = await this.fetchUserDataByEmail(context.loginHint!)
        );
```

This works but I obviously want to consume the retrieved user data in some way. Such as:

```
        microsoftTeams.getContext(async (context) =>
            this. user = await this.fetchUserDataByEmail(context.loginHint!)
            this.foo = await this.fetchFooByUserID(this.user!.id); //I assumed user will not be  null by now
        );
```
But the user is undefined. What would be the correct way to do ensure waiting for results?
Would there any way to wrap the `microsoftTeams.getContext()` in an asynchronous method? For instance:

```
async getLoginHint(){
     microsoftTeams.getContext(async (context) =>
...
/*some magic*/
...
     return hint;
}

```

**Comment by Jagadeesh-MSFT** [comment]
Hi @marwalsch,
Thank you for reaching out to us, we will investigate and if we require further information we will reach out.
Thanks,
Jagadeesh
Teams Dev Community Response

**Comment by Jagadeesh-MSFT** [comment]
Hi @marwalsch, 
yes, we can wrap the  microsoftTeams.getContext() in any method. 
You will get the basic user details in getContext. 
Could please let us know what more details you want to fetch about user ?

**Comment by marwalsch** [comment]
@Jagadeesh-MSFT 
Thanks for the response. The fetched Data comes from an API secured through Teams-SSO-Tokens and returns basic user information in exchange for the Email. I'D use the Office-Guid through the context, but the database isn't aware of it.
I am primarily looking for a tangible solution on how exactly I can wrap getContext(9 in a more readable manner. I really just want to move all calls on `microsoftTeams`-calls out of my immediate app logic and achieve something similar to this:

```
interface IContextService {
    getLoginHintAsync(): Promise<String>;
}
```
And the app calls it like: `let hint = await contextService.getLoginHint();`.

I am curious about how I had to implement this method. It would look something like:

```
public getLoginHintAsync(): Promise<String>{
    //call getContext()
    //resolve with loginHint
    //or
    //reject with "" or similar when callback takes longer than n seconds (for example)
}
```

So my current Solution looks more like this:
` this. user = await this.fetchUserDataByEmail(await contextService.getLoginHint());` //ignore emtpystring

I can't quite understand how the callback works on this method and all implementations I've seen just call their methods from within the `getContext()`-Block, as I currently do.

Any suggestions are welcome.

**Comment by ydogandjiev** [comment]
Hey @marwalsch, you can implement your `getLoginHintAsync` API very easily as follows:
```
public getLoginHintAsync(): Promise<String> {
  return new Promise((resolve, reject) => {
    microsoftTeams.getContext(context => {
      resolve(context.loginHint);
    });
  });
}
```

However, I would like to emphasize that any of the user information in the context should **not be used for making authentication or authorization decisions** for data access. This is noted here:
https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context#user-context
![image](https://user-images.githubusercontent.com/3357245/104085415-2213c580-5204-11eb-942e-59a8bec777cd.png)

The only way to securely get the user's identity is by authenticating them using one of the methods documented here:
- Option A: https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso
- Option B: https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-flow-tab
