### ISSUE TITLE
How to use ts-check with script tag in html file

### ISSUE THREAD

**Issue by abdulkareemnalband** [OfficeDev/microsoft-teams-library-js#484]
I'm using teams client sdk from cdn aka

```html
<script src="https://statics.teams.microsoft.com/sdk/v1.8.0/js/MicrosoftTeams.min.js"
            crossorigin="anonymous"></script>
```

I have also installed `@microsoft/teams` package via `yarn install`

trying to use sdk as 
```html
<script>
// ts-check
microsoftTeams.initialize()
</script>
```

but it shows following error
![image](https://user-images.githubusercontent.com/3139353/104280651-460c2b00-54d2-11eb-85f4-54c2fcf9f569.png)

**Comment by Manish-MSFT** [comment]
@abdulkareemnalband : We are looking into this issue, and will update you soon.

**Comment by Manish-MSFT** [comment]
@abdulkareemnalband  : Can we get on call to discuss this issue. Please write to us at microsoftteamsdev@microsoft.com
