### ISSUE TITLE
AuthenticateParameters.failureCallback invoked with reason "CancelledByUser" even if notifySuccess(token) has been called

### ISSUE THREAD

**Issue by fume** [OfficeDev/microsoft-teams-library-js#49]
Hi,
sometimes the failureCallback got called even if the notifySuccess has been invoked from the authentication popup window. The reason is usually "CancelledByUser" but this is not the case because the popup got closed automatically after the call to notifySuccess.

This is really random, really hard to reproduce.

Thanks, regards

**Comment by kamilwylegala** [comment]
Hello,

I also use Teams JavaScript library and I get the same random errors described by @fume. So far it happens only in web app, on desktop app I don't get such errors. 

Any clues why is it happening? Thanks in advance for any advices.

Regards.

**Comment by ydogandjiev** [comment]
Thanks for raising this issue @fume and @kamilwylegala. We are aware of the problem and working on a fix for it. It will most likely become available with the next version of the SDK.

**Comment by naugtur** [comment]
Is there an action on our side we need to take after the new version gets released, or would it just stop happening?

**Comment by ydogandjiev** [comment]
@naugtur, you will most likely have to update to vNext (e.g. 1.1) of the SDK in order to get the fix. Since we don't plan to remove/change any existing functionality of the SDK updating to the next version should be as simple as changing the src path of our JavaScript library.

**Comment by naugtur** [comment]
@ydogandjiev good to know, thanks! Looking forward to more notifications from this thread ;)

**Comment by naugtur** [comment]
We've also observed a regression related to this. 
Our Compose Extension used to authorize successfully every time, but now (with no changes on our part), for some users it fails constantly in a manner similar to described in this thread. Seems like the same issue propagated there.

**Comment by naugtur** [comment]
@ydogandjiev the bug continues to affect our integrations. Do you have a date for a fix?

**Comment by synth** [comment]
I'm currently experiencing this issue fyi. It doesn't seem like its timeout related.

**Comment by ydogandjiev** [comment]
@synth, the original issue discussed here was resolved a while back. Can you please open a new issue regarding the problem you've encountered and provide some additional details:
1. What version of the SDK are you using?
2. Are you seeing the issue in our Web, Desktop, or Mobile clients (or all of them)?
3. Is the starting and terminating domain of your auth flow the same?
4. Are you able to share an app package or minimal repro of the issue?

**Comment by synth** [comment]
Thanks. I realized that there is a more current issue, #173 and posted there as well. I will also try to create a minimal reproducible case.
