### ISSUE TITLE
authentication.authenticate ignored in "sidePanel"

### ISSUE THREAD

**Issue by evgenyelyashevich** [OfficeDev/microsoft-teams-library-js#495]
Why is popup opening ignored for context.frameContext === "sidePanel"
This works if state.frameContext === "content"
I don't get failureCallback, or failureCallback. Just nothing
How do I do it then in sidePanel without other tabs (only on tab in meeting)?

At the moment I'm using a message on SidePanel ("Please log in on Tab of this meeting settings to enable the functionality.") After that, on sidePanel it will not be required again. But this is not the best option

```
microsoftTeams.authentication.authenticate({
    url: window.location.origin + "/#teamsauthpopup",
    width: 600,
    height: 535,
    successCallback: (response) => {
        const { username, accessToken, expiresOn, idToken } =
            JSON.parse(response);
        this.authState = { username, accessToken, expiresOn, idToken };
        resolve(this.authState);
    },
    failureCallback: (reason) => {
        reject(reason);
    }
});
```

**Comment by ydogandjiev** [comment]
@evgenyelyashevich, please make sure that you are using the latest version of the Client SDK. Support for the sidePanel frame context was first added in v1.8.0:
https://www.npmjs.com/package/@microsoft/teams-js/v/1.8.0

**Comment by evgenyelyashevich** [comment]
@ydogandjiev Thank you very much. That helped
![image](https://user-images.githubusercontent.com/54266063/106216405-16546700-61e4-11eb-9545-2d56309f44bf.png)
