### ISSUE TITLE
Q - Teams Tab App SSO for existing AAD protected Web App+Api 

### ISSUE THREAD

**Issue by dmcweeney** [OfficeDev/microsoft-teams-library-js#499]
Hi,

Question on the Teams Tab SSO implementation. 

We have an multi-tenant AAD web app+api implemented in Asp.Net Core and protected by AAD/OIDC. 
A couple of the controller actions spool the client app (which is a SPA) which then calls the backend apis using the normal cookie auth. We use MSAL.Net on the backend for making calls to the graph api. 

We want to surface this app as a Teams tab app that utilizes the Teams tab SSO - with **minimal** change.
However I cannot find any samples with this scenario. 

My assumption is that because the OIDC cookie auth is not supported within the Teams tab that I will have to convert my web apis to also support bearer token authentication, and obviously include the bearer token in all api calls to the app.

Is this correct?

One thing that is throwing me is the separate AAD App registration for the Teams Tab app - 
specifically the **Authentication - Platform - Web - Redirect Uri**

> "This will be the page where a successful implicit grant flow will redirect the user. This will be same fully qualified domain name that you entered in step 5 followed by the API route where a authentication response should be sent."

Is this solely for use by the AAD consent dialog or is there other events that Teams will call this?

Thanks

Donal

**Comment by Trinetra-MSFT** [comment]
@dmcweeney , While implementing the [SSO for teams tab](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso) you need to set up oAuth connection for your Azure app. You can look at following sample code which have [SSO for teams tab](https://github.com/Trinetra-MSFT/teams-tab-SSO-CSharp) implementation

**Comment by dmcweeney** [comment]
@Trinetra-MSFT thanks for the update and sample.
I've been through all of the SSO tab samples but have yet to find one with backend api configured as follows:

```
           services.AddAuthentication(sharedOptions =>
            {
                sharedOptions.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                sharedOptions.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
            } )
            .AddCookie()
            .AddOpenIdConnect( options =>
            {

```

I'm guessing only **bearer** token support is supported as that is what all the samples show.

Thanks, Donal

**Comment by Trinetra-MSFT** [comment]
@dmcweeney , Yes it uses jwt bearer token as of now, it request a Bot token using [TokenExchangehelper](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/auth-aad-sso-bots#add-the-code-to-request-and-receive-a-bot-token)
 
```
 services.AddAuthentication(options =>
                {
                    options.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
                })
                .AddJwtBearer(options =>
                {
                    var azureAdOptions = new AzureADOptions();
                    Configuration.Bind("AzureAd", azureAdOptions);
                    options.Authority = $"{azureAdOptions.Instance}{azureAdOptions.TenantId}/v2.0";
                    options.TokenValidationParameters = new TokenValidationParameters
                    {
                        ValidAudiences = SSOAuthHelper.GetValidAudiences(Configuration),
                        ValidIssuers = SSOAuthHelper.GetValidIssuers(Configuration),
                        AudienceValidator = SSOAuthHelper.AudienceValidator
                    };
                });
```

We don't have any sample yet using open id connect or other `AUTH `mechanism, but in future we will work on that part

**Comment by dmcweeney** [comment]
@Trinetra-MSFT thanks for the confirmation - I was worried that I had missed something obvious.
