### ISSUE TITLE
Missing successCallback from Teams auth popup in Desktop app 

### ISSUE THREAD

**Issue by cas--** [OfficeDev/microsoft-teams-library-js#502]
I having an issue with the auth popup in the Teams desktop app not calling successCallback when it is complete but it works fine in browser and mobile apps. From searching I can see this is a common issue (e.g.  #356 and #330 ) but I unable to resolve it with the suggestions provided in those issues. Anything else that can be suggested to fix the issue?

For the record the auth redirects are on the same domain and are listed are follows in manifest:
```
 "validDomains": [
    "jell.com",
    "*.jell.com"
  ],
```
(I see reference to adding token.botframework.com but I don't see the relevance here and testing shows no difference)

Our site is an AngularJS SPA and this is our bot app: https://appsource.microsoft.com/en-gb/product/office/WA104381619 

I recently fixed an issue with the auth popup not opening correctly (#458) by creating a AngularJS factory to initialize microsoftTeams. In case it is relevant to the auth popup missing successCallback, here is the code:
```
  module.factory('microsoftTeamsLoaded', [
    '$q',
    '$window',
    'angularLoad',
    function ($q, $window, angularLoad) {
      const deferred = $q.defer();
      angularLoad
        .loadScript(
          'https://statics.teams.cdn.office.net/sdk/v1.6.0/js/MicrosoftTeams.min.js'
        )
        .then(() => {
          $window.microsoftTeams.initialize(() => {
            deferred.resolve($window.microsoftTeams);
          });
        });
      return deferred.promise;
    },
  ]);
```

Controller snippet with button on-click authenticate function:
```
  ...
  microsoftTeamsLoaded.then((microsoftTeams) => {
    ctrl.microsoftTeams = microsoftTeams;
  });
  ...
  const onAuthSuccess = function (res) {
    $rootScope.$apply(() => {
        setUser(res.user);
    });
  };
  ...
  ctrl.authenticate = function () {
    ctrl.microsoftTeams.authentication.authenticate({
      url: $window.location.origin + '/app/microsoft-teams/tabs/auth',
      width: 600,
      height: 535,
      successCallback: onAuthSuccess,
      failureCallback: onAuthFailure,
    });
  };
```

Controller snippet for the redirect page:
```
    microsoftTeamsLoaded.then((microsoftTeams) => {
        ...
        whenLoggedIn.then((res) => {
          microsoftTeams.authentication.notifySuccess(res);
        });
        whenLoggedIn.catch(() => {
          microsoftTeams.authentication.notifyFailure();
        });
```

**Comment by cas--** [comment]
Thanks for setting up a chat but I spent time today investigating this further and seems I have resolved it by replacing $rootScope.apply() for $scope.apply() in the component onAuthSuccess method:
```diff
const onAuthSuccess = function (res) {
-    $rootScope.$apply(() => {
+    $scope.$apply(() => {
```
This makes sense since it was that component's scope that needed the digest update after the external javascript notifySuccess call. That it only occurred in the Desktop app is odd and the lack of debug console in the Teams App on Linux is very frustrating here. 

Perhaps you can point me to where I can raise an issue for the Linux app to show the dev console? It works on both Windows and MacOS so should be trivial to provide a keyboard shortcut or menu item.

**Comment by RamaMohanaChary** [comment]
Hi Calum,

Glad to hear from you that issue got resolved.

Regarding your issue for the Linux, could you please reach out to [Product Support Channel](https://docs.microsoft.com/en-us/microsoftteams/platform/feedback#product-support-channels).
