### ISSUE TITLE
Improve ability for developers to utilize SDK when writing unit tests

### ISSUE THREAD

**Issue by drub0y** [OfficeDev/microsoft-teams-library-js#508]
Currently it requires a lot of mocking of complicated, internal magic for an application that utilizes the SDK to actually be able to unit test it. I spent easily over 8hrs diving into the code and reverse engineering it just to get the `microsoftTeams.initialize(...)` call to even actually pass so that our application could even load.

It looks like the SDK itself has a `Utils` class and some "prublic" APIs that it uses to "cheat" and bypass actual DOM windowing by emulating a frameless window instance which it mocks out. This would be wonderful to actually ship as a companion package that developers could import into their unit tests.

I would highly suggest that some effort be put into improving the ability for developers to simply import a companion unit testing package that smooths out the difficulties surrounding working with the SDK. Additionally, some guidance around how best to work with the SDK in the context of a testing framework such as Jest would be wonderful. For example, would one initialization for an entire test run suffice (e.g. `beforeAll`) or should I be initializing it for each test (e.g. `beforeEach`)?

**Comment by Saonti-MSFT** [comment]
Hi @drub0y, You can raise an [User Voice](https://microsoftteams.uservoice.com/) for this. 
Microsoft will always focus on customer’s feedback and experience, some new features would be added to the services based on customers' feedback in the future.
