### ISSUE TITLE
Theme change-handler doesn't work when inside pop-out-app window

### ISSUE THREAD

**Issue by marwalsch** [OfficeDev/microsoft-teams-library-js#511]
I am having the following implementation for using the them change handler inside teams, using React Northstar for styling.

On app startup:
```
        microsoftTeams.getContext(context => {
            this.applyThemeHandler(context.theme!)
        });

        this.state = {
            theme: teamsTheme,
        }
```

Change-handler:

```
    private applyThemeHandler(themeName: string) {
        this.setState({
            theme: this.convertTheme(themeName)
        });
    }

    private convertTheme(themeName: string): ThemePrepared {
        switch (themeName) {
            case 'dark':
                return teamsDarkTheme;
            case 'contrast':
                return teamsHighContrastTheme;
            default:
                return teamsTheme;
        }
    }
```

It works as expected inside desktop and web client as well as the mobile client. However, when opening the app with the desktop-client's pop-out-app window, the dark theme won't be applied. It always switching to the light theme instead (while the pop-out window itself changes accordingly). This occurs when initially opening the window as well as when changing the client's them while having the pop-out window open.

This issue might also be related to the feature itself rather than the theme-handler(?)

**Comment by Mallipriya-MSFT** [comment]
Hi @marwalsch, 
Could you please debug and check the console logs for errors in desktop app by following the document - [DevTools for Microsoft Teams tabs - Teams | Microsoft Docs](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/developer-tools).

**Comment by marwalsch** [comment]
@Mallipriya-MSFT  Hello,

no errors, but logging the theme returned by teams actually revealed that it behaves as it should. So for some reason 
```
switch (themeName) {
            case 'dark':
                return teamsDarkTheme;
            case 'contrast':
                return teamsHighContrastTheme;
            default:
                return teamsTheme;
        }
```
returns 'teamsDarkTheme' but doesn't apply it in the Provider. Thus I assume the issue is actually on Northstar's side. Can you(should i re-open there?

**Comment by Mallipriya-MSFT** [comment]
@marwalsch, Taking this for internal discussion with team, I will update you with resolution

**Comment by marwalsch** [comment]
It appears this issue is patched as of Version 1.4.00.6073 (32-Bit).
@Mallipriya-MSFT Could you confirm to close?

**Comment by Nikitha-MSFT** [comment]
@marwalsch Is your issue resolved?

**Comment by marwalsch** [comment]
@Nikitha-MSFT 
I just re-checked
- my own app,
- App Studio,
- Polly
and it appears to be working properly now.
