### ISSUE TITLE
Unable to open task module from chat panel in new meeting experience

### ISSUE THREAD

**Issue by kasturi15** [OfficeDev/microsoft-teams-library-js#512]
We are posting a link to task module in meeting chat in form specified in https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/what-are-task-modules#task-module-deep-link-syntax
<details>
<summary>
The task module link is in this format 
</summary>
https://teams.microsoft.com/l/task/2a05d07c-d194-400e-8122-cad64cfe1cef?url=https%3A%2F%2Flocalhost%3A44349%2Fteams%2F%23%2Fdecision-vote%2F0c89e9be-b0dd-4851-b71a-62e48bb0081e%2Fitems%2F01JE2R3DFKGO3URGOZDBDKV33I2SW6I3SZ%2Fdecisions%2FAkTY6AAnIkmo8vYJZB0iAJYAIHGu%2Fpolls%2F6dcee631-507c-4c0e-b8b9-aaa7630b3433%3FdriveId%3Db!PWNtco7QNkqr0Y4bVDYuLIppTN4jCt1EhNuwtdC_eOaYbWEtwcw1T4Ms5nIz2ey4%26groupId%3Dce7be93e-af51-4682-8ba9-c906fe75c160%26channelId%3D19%3A76c92b8b760c46b5a06ef540e145f525%40thread.tacv2%26tenant%3Dc7105dda-a548-4def-8ee7-e992e0e6dcb0%26realm%3Dfigg.onmicrosoft.com&height=580&width=1024&title=Cast%20vote&fallbackUrl=https%3A%2F%2Flocalhost%3A44349%2FGenericRedirect%3Fngapp%3Dweb%26endpoint%3Ddecision-vote%2F0c89e9be-b0dd-4851-b71a-62e48bb0081e%2Fitems%2F01JE2R3DFKGO3URGOZDBDKV33I2SW6I3SZ%2Fdecisions%2FAkTY6AAnIkmo8vYJZB0iAJYAIHGu%2Fpolls%2F6dcee631-507c-4c0e-b8b9-aaa7630b3433%26driveId%3Db!PWNtco7QNkqr0Y4bVDYuLIppTN4jCt1EhNuwtdC_eOaYbWEtwcw1T4Ms5nIz2ey4%26groupId%3Dce7be93e-af51-4682-8ba9-c906fe75c160%26channelId%3D19%3A76c92b8b760c46b5a06ef540e145f525%40thread.tacv2%26tenant%3Dc7105dda-a548-4def-8ee7-e992e0e6dcb0%26realm%3Dfigg.onmicrosoft.com
</details>

The links always work from main teams window. 
Sometimes it also works from meeting window in new meeting experience. 
But sometimes it is not working from meeting window chat. 

Following are the error details
<details>
<summary>
Logs 
</summary>
<pre>
﻿
main-487659960afcfb39.js:1 CID[8b6086f5-433b-4a0b-96e8-fee5fc51a467] HostedWebContentWithAppIdInner: GraphQL query failed to get installed app id: 2a05d07c-d194-400e-8122-cad64cfe1cef
(anonymous)	@	main-487659960afcfb39.js:1
(anonymous)	@	main-487659960afcfb39.js:1
(anonymous)	@	calling-app-c2e2c75545bbc280.js:1
Promise.catch (async)		
V	@	calling-app-c2e2c75545bbc280.js:1
(anonymous)	@	content-bubble-conta…a4f150c0afe6ea.js:1
hu	@	vendors-9d3486e849faa02f.js:1
Cc	@	vendors-9d3486e849faa02f.js:1
(anonymous)	@	vendors-9d3486e849faa02f.js:1
Ji	@	vendors-9d3486e849faa02f.js:1
Ac	@	vendors-9d3486e849faa02f.js:1
vc	@	vendors-9d3486e849faa02f.js:1
(anonymous)	@	vendors-9d3486e849faa02f.js:1
(anonymous)	@	vendors-9d3486e849faa02f.js:1
Ji	@	vendors-9d3486e849faa02f.js:1
Xi	@	vendors-9d3486e849faa02f.js:1
Ki	@	vendors-9d3486e849faa02f.js:1
M	@	vendors-9d3486e849faa02f.js:1
Q	@	vendors-9d3486e849faa02f.js:1
en	@	vendors-9d3486e849faa02f.js:1
Zt	@	vendors-9d3486e849faa02f.js:1
(anonymous)	@	vendors-9d3486e849faa02f.js:1
$t	@	vendors-9d3486e849faa02f.js:1
vendors-9d3486e849faa02f.js:1 Error: Unable to fetch app definition
    at content-bubble-conta…a4f150c0afe6ea.js:1
    at ea (vendors-9d3486e849faa02f.js:1)
    at Ga (vendors-9d3486e849faa02f.js:1)
    at ku (vendors-9d3486e849faa02f.js:1)
    at Sc (vendors-9d3486e849faa02f.js:1)
    at jc (vendors-9d3486e849faa02f.js:1)
    at vc (vendors-9d3486e849faa02f.js:1)
    at vendors-9d3486e849faa02f.js:1
    at vendors-9d3486e849faa02f.js:1
    at Ji (vendors-9d3486e849faa02f.js:1)
lu	@	vendors-9d3486e849faa02f.js:1
Nu.n.payload	@	vendors-9d3486e849faa02f.js:1
bo	@	vendors-9d3486e849faa02f.js:1
Ja	@	vendors-9d3486e849faa02f.js:1
ku	@	vendors-9d3486e849faa02f.js:1
Sc	@	vendors-9d3486e849faa02f.js:1
jc	@	vendors-9d3486e849faa02f.js:1
vc	@	vendors-9d3486e849faa02f.js:1
(anonymous)	@	vendors-9d3486e849faa02f.js:1
(anonymous)	@	vendors-9d3486e849faa02f.js:1
Ji	@	vendors-9d3486e849faa02f.js:1
Xi	@	vendors-9d3486e849faa02f.js:1
Ki	@	vendors-9d3486e849faa02f.js:1
lc	@	vendors-9d3486e849faa02f.js:1
_a	@	vendors-9d3486e849faa02f.js:1
(anonymous)	@	content-bubble-conta…a4f150c0afe6ea.js:1
Promise.catch (async)		
(anonymous)	@	content-bubble-conta…a4f150c0afe6ea.js:1
hu	@	vendors-9d3486e849faa02f.js:1
Cc	@	vendors-9d3486e849faa02f.js:1
(anonymous)	@	vendors-9d3486e849faa02f.js:1
Ji	@	vendors-9d3486e849faa02f.js:1
Ac	@	vendors-9d3486e849faa02f.js:1
vc	@	vendors-9d3486e849faa02f.js:1
(anonymous)	@	vendors-9d3486e849faa02f.js:1
(anonymous)	@	vendors-9d3486e849faa02f.js:1
Ji	@	vendors-9d3486e849faa02f.js:1
Xi	@	vendors-9d3486e849faa02f.js:1
Ki	@	vendors-9d3486e849faa02f.js:1
M	@	vendors-9d3486e849faa02f.js:1
Q	@	vendors-9d3486e849faa02f.js:1
en	@	vendors-9d3486e849faa02f.js:1
Zt	@	vendors-9d3486e849faa02f.js:1
(anonymous)	@	vendors-9d3486e849faa02f.js:1
$t	@	vendors-9d3486e849faa02f.js:1
main-487659960afcfb39.js:1 CID[8b6086f5-433b-4a0b-96e8-fee5fc51a467] PlatformErrorBoundary: Error message: Unable to fetch app definition.
(anonymous)	@	main-487659960afcfb39.js:1
(anonymous)	@	main-487659960afcfb39.js:1
(anonymous)	@	content-bubble-conta…a4f150c0afe6ea.js:1
Nu.o.componentDidCatch.n.callback	@	vendors-9d3486e849faa02f.js:1
mo	@	vendors-9d3486e849faa02f.js:1
vu	@	vendors-9d3486e849faa02f.js:1
xc	@	vendors-9d3486e849faa02f.js:1
(anonymous)	@	vendors-9d3486e849faa02f.js:1
Ji	@	vendors-9d3486e849faa02f.js:1
Ic	@	vendors-9d3486e849faa02f.js:1
vc	@	vendors-9d3486e849faa02f.js:1
(anonymous)	@	vendors-9d3486e849faa02f.js:1
(anonymous)	@	vendors-9d3486e849faa02f.js:1
Ji	@	vendors-9d3486e849faa02f.js:1
Xi	@	vendors-9d3486e849faa02f.js:1
Ki	@	vendors-9d3486e849faa02f.js:1
lc	@	vendors-9d3486e849faa02f.js:1
_a	@	vendors-9d3486e849faa02f.js:1
(anonymous)	@	content-bubble-conta…a4f150c0afe6ea.js:1
Promise.catch (async)		
(anonymous)	@	content-bubble-conta…a4f150c0afe6ea.js:1
hu	@	vendors-9d3486e849faa02f.js:1
Cc	@	vendors-9d3486e849faa02f.js:1
(anonymous)	@	vendors-9d3486e849faa02f.js:1
Ji	@	vendors-9d3486e849faa02f.js:1
Ac	@	vendors-9d3486e849faa02f.js:1
vc	@	vendors-9d3486e849faa02f.js:1
(anonymous)	@	vendors-9d3486e849faa02f.js:1
(anonymous)	@	vendors-9d3486e849faa02f.js:1
Ji	@	vendors-9d3486e849faa02f.js:1
Xi	@	vendors-9d3486e849faa02f.js:1
Ki	@	vendors-9d3486e849faa02f.js:1
M	@	vendors-9d3486e849faa02f.js:1
Q	@	vendors-9d3486e849faa02f.js:1
en	@	vendors-9d3486e849faa02f.js:1
Zt	@	vendors-9d3486e849faa02f.js:1
(anonymous)	@	vendors-9d3486e849faa02f.js:1
$t	@	vendors-9d3486e849faa02f.js:1
</pre>
</details>

![image](https://user-images.githubusercontent.com/34769756/108992165-ffa80f80-76be-11eb-888f-66d426052cb8.png)

**Comment by Mamatha-MSFT** [comment]
Hi @kasturi15, Could you please send the code snippets so that I can repro at my end.

**Comment by abdulkareemnalband** [comment]
Hi @Mamatha-MSFT  
colleague of @kasturi15 here


1. Schedule a meeting
2. Install a teams APP
3. Join a meeting
4. Open chat panel
5. post a link with deeplink to a (STEP 2 APP's) task module 
6. click on link

sometime (not always) Task module fails load properly
And we see follwing error in teams developer console when that happens
```
HostedWebContentWithAppIdInner: GraphQL query failed to get installed app id: <APPID from step 2>
```

**Comment by abdulkareemnalband** [comment]
Both logs and link are hidden behind detials summary tag in original post

**Comment by Mamatha-MSFT** [comment]
@kasturi15, @abdulkareemnalband  I am able to reproduce the issue, Task module deep link will not work in Teams meeting window chat. You can use [Content Bubble](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?tabs=dotnet#notificationsignal-api) in meeting.

**Comment by abdulkareemnalband** [comment]
@Mamatha-MSFT  hi thanks for reply
We will defiantly try to implement content bubble

Is there a time like when this will be supported in meeting window caht

**Comment by Mamatha-MSFT** [comment]
@abdulkareemnalband You can use it any time when you are in meeting.

**Comment by abdulkareemnalband** [comment]
@Mamatha-MSFT 
We cannot use content bubble for all scenarios,
Is there a workaround for this other that content bubbles

**Comment by Mamatha-MSFT** [comment]
@abdulkareemnalband Currently there is no workaround other than content bubbles.

**Comment by mmjosund** [comment]
@Mamatha-MSFT Will the content bubble implementation (In-meeting dialog box) work for Teams Web and Teams Mobile apps? Or is this only supported for the Native Teams app?

If not, what is the recommendation to serve actions for users on Web and Mobile?

**Comment by figgsoftware** [comment]
@Mamatha-MSFT  We don't feel this is acceptable. Customers have been running key voting scenarioes with this functionality for a long time, and then suddenly it does not work for some users. It feels random. What are the criteria for when it works and when it does not work.

**Comment by Mamatha-MSFT** [comment]
@figgsoftware @mmjosund - Could you please specify are you getting any error in while using content bubble. Please go through the [sample for content bubble](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/meetings-content-bubble).

**Comment by abdulkareemnalband** [comment]
@Mamatha-MSFT  content bubble does not suite for our workflow
Thing is same links work when opened from main teams window chat page
but fails open when tried from meeting window chat sidepanel

**Comment by Mamatha-MSFT** [comment]
@abdulkareemnalband - See the highlighted text in below image that task module will not work in meeting. Please see the [documentation](https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?tabs=dotnet#in-meeting-dialog). 
![image](https://user-images.githubusercontent.com/78795357/118800286-5fc4e100-b8bd-11eb-9f79-d4fcf6bfc613.png)

**Comment by abdulkareemnalband** [comment]
@Mamatha-MSFT  Yes i have read that
Issue here is we have a link posted in chat , built using by following this [documentation](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links#generate-a-deep-link-to-your-tab)

Same link works in main teams window chat
but fails in in meeting chat sidepanel

**Comment by Mamatha-MSFT** [comment]
We have raised a bug for this issue and concerned team is working on it.

**Comment by ChetanSharma-msft** [comment]
Hello @kasturi15 - Hope you are doing well!!
This issue has resolved.

Could you please check and confirm?

**Comment by kasturi15** [comment]
Hello @ChetanSharma-msft, I tested today and it is still not working on my end. 

**Getting the following error**:
 
?agent=electron&version=22102807200:98 ["CDL: {\"errorCode\":\"Error\",\"requestId\":\"q-2124\",\"hostRendererId\":\"5e3ce6c0-2b1f-4285-8d4b-75ee78787346\",\"component\":\"RequestHandler\",\"requestWindowId\":\"d2e87178-cc3f-4da1-b718-cd2a0e52266e\",\"operationType\":\"query\",\"operationName\":\"appDefinition\",\"message\":\"error while processing q-2124: {\\\"name\\\":\\\"Error\\\",\\\"message\\\":\\\"Unexpected error value: { message: \\\\\\\"getGroupChatAppDefinition - No registeredApp found with appId (d17c0803-3247-48e8-8955-32142e85f3c0) for chat (19:meeting_NjRlOWRlYjMtMGFkMS00NDhlLWEyZWEtZmJiNjUyNzIzMTlm@thread.v2), callerContext: (cdl)\\\\\\\", status: \\\\\\\"NotFound\\\\\\\" }\\\",\\\"stack\\\":[]} (reason: undefined)\"}"]

["CID[d2e87178-cc3f-4da1-b718-cd2a0e52266e] TaskModuleForDeepLinkContainer: {\"name\":\"Error\",\"message\":\"Unexpected error value: { message: \\\"getGroupChatAppDefinition - No registeredApp found with appId (d17c0803-3247-48e8-8955-32142e85f3c0) for chat (19:meeting_NjRlOWRlYjMtMGFkMS00NDhlLWEyZWEtZmJiNjUyNzIzMTlm@thread.v2), callerContext: (cdl)\\\", status: \\\"NotFound\\\" }\",\"stack\":[]}"]

![image](https://user-images.githubusercontent.com/34769756/200854438-28667ac0-3b33-4c9e-bb12-c8af60053c18.png)

**Comment by Prasad-MSFT** [comment]
Hi @kasturi15 - We tried to repro this issue. However, its working fine at our end.
Checked in `Microsoft Teams Version 1.5.00.32474 (64-bit)`. 
We are checking with engineering team. We will inform you if there is any update. Thanks!
