### ISSUE TITLE
Enable deep-linking to private channels

### ISSUE THREAD

**Issue by dani-cl-madrid** [OfficeDev/microsoft-teams-library-js#516]
This is a feature request. It would be great if the private chats could also have links to them accessible by right clicking on the chat in the left panel. Having that feature, the link can be shared, or stored as a bookmark. If a user that don't have access to the chat and clicks the link, he should get an error. Or a dialog to request access, in the same way it appears when accessing a private channel. 
Thank you!

**Comment by Mallipriya-MSFT** [comment]
Hi @dani-cl-madrid, Yes, you can raise the user voice for the scenario [here](https://microsoftteams.uservoice.com/).

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
