### ISSUE TITLE
Teams authenticate doesn't work with CBA on iOS.

### ISSUE THREAD

**Issue by enumm** [OfficeDev/microsoft-teams-library-js#521]
When using  `microsoftTeams.authentication.authenticate` to authenticate to AAD with
[certificate-based authentication](https://docs.microsoft.com/en-us/azure/active-directory/authentication/active-directory-certificate-based-authentication-get-started) enabled it opens popup that does not have access to saved certificates.

![image](https://user-images.githubusercontent.com/7242996/109937811-f844bf80-7cd7-11eb-9020-0133f09fcc4b.png)

**Comment by Sridevi-MSFT** [comment]
Hi @enumm, Are you facing same issue in android as well and also can you confirm which teams version are you using.

**Comment by enumm** [comment]
Hello @Sridevi-MSFT , Unfortunately we cannot set this up and test on android,  Teams app version : 2.4.2 build 1.077.2021030207
Teams SDK 1.9.0.
The issue is that on iOS

only `Mozilla/5.0 (iPhone; CPU iPhone OS 14_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Mobile/15E148 **Safari**/604.1` view controller has access to certificates stored on phone.

and `microsoftTeams.authentication.authenticate` opens `Mozilla/5.0 (iPhone; CPU iPhone OS 14_4 like Mac OS X) **AppleWebKit**/605.1.15 (KHTML, like Gecko) Mobile/15E148` view controller which doesn't have access to certificates.

**Comment by Sridevi-MSFT** [comment]
Hi @enumm, Device-base CA policies only work in the Safari browser. They don't work in other browsers like Chrome or WebView's created by apps like Teams.
