### ISSUE TITLE
Runtime error when bundled with Rollup

### ISSUE THREAD

**Issue by tecton** [OfficeDev/microsoft-teams-library-js#522]
Hi,

I'm using a new package that depends on teams-js SDK and I use Rollup to bundle it.
I got the error that shows `Unhandled Rejection (TypeError): Cannot set property '_uninitialize' of undefined` in local debug.
The error message indicates that error happens in this [line](https://github.com/OfficeDev/microsoft-teams-library-js/blob/967ea096c6762086c0e1f1ebd3ae965e2850aa3b/src/public/publicAPIs.ts#L64).

I think `this.uninitialize = () => {...}` is trying to update the exported uninitialize function. But I'm not sure whether this is a bug because `this` value is undefined when the whole library is bundled with Rollup.

I changed this code to `exports.uninitialize = () => {...}` and it's working. Could you please help to verify whether my understanding is correct? I can create a PR if it's a bug, thanks!

library version: 1.9.0
Rollup: 1.16.3

**Comment by Mamatha-MSFT** [comment]
Hi @tecton, Can you please provide the code snippet and repro steps. It will help to repro at my end.

**Comment by tecton** [comment]
Hi @Mamatha-MSFT, thanks for the quick reply! I created a [project](https://github.com/tecton/teams-js-wrapper) that wraps teams-js library.

I also tried to upgrade Rollup to latest version and it's not an issue any more. So I think the named export in Rollup 1.x make `this` undefined.

Repro steps:
1. Clone the wrapper project and build it using `npm run build`.
2. Create a new project for Teams personal tab.
3. Add the wrapper lib as dependency.
4. In the Tab js file, use the getSSOToken function that is exported in that wrapper.
```
import { getSSOToken } from "wrapper-lib/dist/index";
...
async componentDidMount() {
  const ssoToken = await getSSOToken();
  console.log(ssoToken);
}
```

**Comment by Mamatha-MSFT** [comment]
Hi @tecton, I have reproduced the same code that you have provided. It is working completely fine at out end and so, I suggest you to retry once again at your end.

**Comment by tecton** [comment]
Hi @Mamatha-MSFT, I tried again and saw the same error. I removed the "module" field in [package.json](https://github.com/tecton/teams-js-wrapper/blob/master/package.json) of test lib to make sure it uses the Rollup bundled version. Here's the detailed steps that I used to reproduce the bug:
1. Clone the wrapper project and build it. It should have `dist\index.js` file that will be used by Tab app later.
2. Use "Microsoft Teams Toolkit" extension to create a new project. I chose "Personal app with single sign-on (SSO)" TypeScript version.
3. Locally run ngrok service using `ngrok http https://localhost:3000` and paste the ngrok address to "Domain name" for AAD registration.
4. In created project, run `npm install` and `npm start` in "api-server" folder.
5. Navigate to project folder and run `npm install` which is for tab app.
6. Use `npm install ..\teams-js-wrapper` to install the local package built in step 1.
7. Add code:
```typescript
import { getSSOToken } from "wrapper-lib";
...
async componentDidMount(){
    console.log(await getSSOToken());
    // Initialize the Microsoft Teams SDK
    microsoftTeams.initialize();
    ...
}
```
8. Use `npm start` to start webpack server.
9. Hit "F5" to start debugging.
10. I saw the error page as screenshot.
![Error](https://user-images.githubusercontent.com/886116/112119317-3ad32b00-8bf8-11eb-8f38-a9cf82a7540e.png)

Thanks

**Comment by Mamatha-MSFT** [comment]
@tecton - You need to add the required packages as mentioned in the [sample](https://github.com/OfficeDev/microsoft-teams-library-js/blob/967ea096c6762086c0e1f1ebd3ae965e2850aa3b/src/public/publicAPIs.ts#L2). and `this._uninitialize ` is an undocumented function used to clear state between unit tests
