### ISSUE TITLE
`mediaDevices.getUserMedia` returns "DOMException: Permission denied" when it is called in the pop-out-app window

### ISSUE THREAD

**Issue by kafka-yu** [OfficeDev/microsoft-teams-library-js#524]
Hi there,

Not sure if this is the correct repo to ask. But I still want to have a try.

Does anyone know why the below code won't return the MediaSteam in an MS Teams pop-out-app window in desktop client of the MS Teams app?
```js
await window.navigator.mediaDevices.getUserMedia({audio: true, video:false})
```
It returns "DOMException: Permission denied".

It works in the default app window.

```js
MediaStream {id: "vDPnWRVz0V4kVgwWOMITbBPeN3KXgN9pviDg", active: true, onaddtrack: null, onremovetrack: null, onactive: null, …}
```

Is it caused by the "audio" permission is not granted to the pop-out window?

NOTE:
I've enabled the device permissions in my app's manifest, and also the MS Teams app itself.

Thank you!

Reference:
- https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?tabs=desktop#use-teams-apis-to-get-device-permissions

**Comment by Jagadeesh-MSFT** [comment]
@kafka-yu, just to confirm , could you please check all the permissions are enabled in the settings tab as shown below image
![image](https://user-images.githubusercontent.com/73812940/110586938-f0ce5c00-8198-11eb-9ffa-1b2d7754aee2.png)

**Comment by Jagadeesh-MSFT** [comment]
@kafka-yu, are you still facing the issue.

**Comment by kafka-yu** [comment]
> @kafka-yu, are you still facing the issue.

Sorry for the delay in the reply. I'm still facing this issue. And I've also enabled all the permission as your screenshot.

I

> @kafka-yu, just to confirm , could you please check all the permissions are enabled in the settings tab as shown below image
> ![image](https://user-images.githubusercontent.com/73812940/110586938-f0ce5c00-8198-11eb-9ffa-1b2d7754aee2.png)


Would you please help check again? Thanks!

@Jagadeesh-MSFT

**Comment by kafka-yu** [comment]
@Wajeed-msft @Jagadeesh-MSFT Would you pls help check again?

**Comment by Jagadeesh-MSFT** [comment]
@kafka-yu, Sorry for the delayed response. We are working on it, will update you soon.

**Comment by Jagadeesh-MSFT** [comment]
@kafka-yu, Thanks for reaching out to us. We are the developer support team for Microsoft teams focused on helping developers resolve their code issues. For issues related to teams product, please reach out to the [Product support channels](https://docs.microsoft.com/en-us/microsoftteams/platform/feedback#product-support-channels) for Microsoft Teams.

**Comment by kafka-yu** [comment]
Oh, I thought it was a technical issue related to the teams' framework. 

Thanks for you help. @Jagadeesh-MSFT

**Comment by kafka-yu** [comment]
hi @Nikitha-MSFT would you pls help check? Thanks!

**Comment by Wajeed-msft** [comment]
@kafka-yu - this looks like a bug with pop-up window. @Trinetra-MSFT  - could you please repro and raise a bug for this?

**Comment by kafka-yu** [comment]
Hi @Wajeed-msft  thanks.

Hello @Trinetra-MSFT would you pls help check? A large number of our customers are been blocked using our MS Teams app due to this problem. We want to push this to be resolved more eailer. Appreciated and Thank you!

**Comment by kafka-yu** [comment]
Hi there, may I ask is there any update?

**Comment by Jagadeesh-MSFT** [comment]
Hi @kafka-yu, Apologies for the delayed response, we are working it practically , but we are unable to repro your issue from my end. we will taking this to our internal team and will post the timely updates.

**Comment by kafka-yu** [comment]
@Jagadeesh-MSFT Thank you very much.

**Comment by Jagadeesh-MSFT** [comment]
@kafka-yu , could you please share your availability and write it to microsoftteamsdev@microsoft.com.

**Comment by kafka-yu** [comment]
@Jagadeesh-MSFT Sure, thanks. I've sent an email to microsoftteamsdev@microsoft.com.

**Comment by Jagadeesh-MSFT** [comment]
@kafka-yu, we are able to repro your issue from our end , we will raise a bug and share the details with. 
Thank you

**Comment by kafka-yu** [comment]
Hi @Jagadeesh-MSFT @Trinetra-MSFT is there any update on the bug? May I ask any ETA of this issue when it is going to be fixed? 

Appreciated.

**Comment by Jagadeesh-MSFT** [comment]
@kafka-yu, our Engineering Team is working on it, currently we don't have any ETA to share with you.

**Comment by kafka-yu** [comment]
@Jagadeesh-MSFT Got it, thanks for your update.

**Comment by kafka-yu** [comment]
hi @Jagadeesh-MSFT Would you pls keep this thread updated when there has any progress? Very appreciated. Thank you!

**Comment by Jagadeesh-MSFT** [comment]
@kafka-yu, our Engineering Team is working on it, we will update you soon. Currently we don't have any ETA to share with you.

**Comment by kafka-yu** [comment]
@Jagadeesh-MSFT thank you!!!! ❤️

**Comment by kafka-yu** [comment]
Hi team,

May I know is there any update on this ticket?

We're still waiting for this to be resolved to deliver new features for our MS Teams app.

Thank you!

**Comment by kafka-yu** [comment]
hi @Jagadeesh-MSFT would you pls help check if there is any update for this one? Thank you!

**Comment by Wajeed-msft** [comment]
@kafka-yu- checking status on this with engineering team.

**Comment by Wajeed-msft** [comment]
@kafka-yu - got updates from engineering team on this. This is more of a feature request to support device permissions in the multiwindow. Unfortunately we do not have an ETA to share publicly.

**Comment by kafka-yu** [comment]
Ok, that would be a pity to hear that. Thank you @Wajeed-msft  for checking this.
