### ISSUE TITLE
Context object different in a pop-out window

### ISSUE THREAD

**Issue by FormMachines** [OfficeDev/microsoft-teams-library-js#525]
Version: desktop version of Teams. 

In a custom tab, the "getContext" method returns a full object (correct) when not popped out. Once popped out, the same call returns an object with some properties missing (not correct), for example, the user's team role property is missing. 

Using SDK version 1.9

**Comment by Mamatha-MSFT** [comment]
Hi @FormMachines, Thanks for bringing up this issue, I will repro at my end and will let you know.

**Comment by Mamatha-MSFT** [comment]
@FormMachines, I am able to repro the issue from my end. Seems like it's a bug, yet need to get confirmation from the internal team. Will be raising the same as bug.

**Comment by ChetanSharma-msft** [comment]
Hello @FormMachines - 
Sorry for delay in response.
Hope you are doing well!!

Could you please confirm whether you are still facing this issue with the latest SDK?
