### ISSUE TITLE
authentication.getUser response different in popout window.

### ISSUE THREAD

**Issue by mmzeeman** [OfficeDev/microsoft-teams-library-js#527]
When I call `microsoftTeams.authentication.getUser` in a popout window I get a response object with oid, tid and a upn, but when I call it inside a personal tab running in teams I get an error response `App does not have the required permissions for this operation`. The same personal tab on iOS also returns an object with oid, tid and upn.

What is the correct behaviour?

**Comment by enak** [comment]
[microsoftTeams.authentication.getUser](https://github.com/OfficeDev/microsoft-teams-library-js/blob/master/src/public/authentication.ts#L95) is marked as `@private`, so you probably shouldn't rely on that method to get user information. You can call microsoftTeams.getContext() for the [Context](https://github.com/OfficeDev/microsoft-teams-library-js/blob/967ea096c6762086c0e1f1ebd3ae965e2850aa3b/src/public/interfaces.ts#L170) which includes some user information.

----

Also, make sure you've got the `1fec...` code in your App Registration.

    12. In the Authorized client applications section, identify the applications that you want to authorize for your app’s web application. Select Add a client application. Enter each of the following client IDs and select the authorized scope you created in the previous step:
    
    1fec8e78-bce4-4aaf-ab1b-5451cc387264 for Teams mobile or desktop application.
    5e3ce6c0-2b1f-4285-8d4b-75ee78787346 for Teams web application.

Source: https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso#1-create-your-aad-application

**Comment by mmzeeman** [comment]
Thanks for clarifying. I totally missed the `@private` marker in the comment section.
