### ISSUE TITLE
microsoftTeams.authentication.notifySuccess()  sending string instead of JSON on ios devices

### ISSUE THREAD

**Issue by nisitk** [OfficeDev/microsoft-teams-library-js#528]
original value
'{\n accessToken = "<token>";\n expiresIn = 3599;\n tokenType = Bearer;\n}'

expected value 
{
accessToken: 'token',
expiresIn: 3599,
}

SDK version 1.7.0

**Comment by charliedavison** [comment]
@nisitk

I think I'm having a similar issue, but I expected notify success to be a string.

notifySuccess expects a string passed in for the result -

`(result?: string | undefined, callbackUrl?: string | undefined): void`

and looking at the SDK code it eventually calls the `successCallback` provided to `authenticate`.

The function signature of `successCallback` is:

`((result?: string | undefined) => void) | undefined`

This lead me to believe that for it to work I should stringify my JSON that I want to pass through the `successCallback` and then parse it once its over there. Felt a bit strange but it worked - until I tried it on Android, where for some reason even when I stringify the data passed into `notifySuccess` I get an Object passed into `successCallback` which then breaks when I try and JSON parse it.

**Comment by FlorianGrimm** [comment]
I'm currently working on the same? problem.

In the sample 
https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/tab-sso/csharp/TeamsTabSSO/Views/Auth/End.cshtml
line 24
                microsoftTeams.authentication.notifySuccess({
                    idToken: hashParams["id_token"],
                   ....
an object is given ... but the MicrosoftTeams.d.ts say it must be a string.

in node_modules\@microsoft\teams-js\dist\MicrosoftTeams.js from "@microsoft/teams-js@1.10.0
the function sendMessageToParent  (line 165 ) There is a stringify and a postMessage.

Is the sample correct or the d.ts? As of your issue I think the string is the save way.

**Comment by Nivedipa-MSFT** [comment]
@nisitk - Could you please confirm that this issue is still persist or resolved?

**Comment by Wajeed-msft** [comment]
Sharing updates from https://github.com/OfficeDev/microsoft-teams-library-js/issues/942:

[notifySuccess](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/authentication?view=msteams-client-js-latest#@microsoft-teams-js-authentication-notifysuccess) and [notifyFailure](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/authentication?view=msteams-client-js-latest#@microsoft-teams-js-authentication-notifyfailure) both return string. There is a bug for Android https://github.com/OfficeDev/microsoft-teams-library-js/issues/942 for which fix will be rolling out across the Android Teams app in March. Please use linked thread to get further updates.
