### ISSUE TITLE
When implementing a custom connector, microsoftTeams.settings.getSettings returns deprecated webhook URL format

### ISSUE THREAD

**Issue by chrisatkin** [OfficeDev/microsoft-teams-library-js#529]
I'm implementing a custom connector for my company. We have an iframe which loads our configuration URL as defined at both aka.ms/connectorsdashboard and in our app manifest. The frame in turn calls `microsoftTeams.settings.getSettings()` to determine the webhook URL for us to post messages to.

However, as described both [here](https://answers.microsoft.com/en-us/msteams/forum/all/microsoft-teams-important-your-connector-is/59452bf4-f87a-4503-9bfb-a8333724bee5) and [here](https://admin.microsoft.com/AdminPortal/Home?#/MessageCenter/:/messages/MC234048), Office 365 connector webhook URLs are changing formats to include the tenant name.

However, the API returns the old format, resulting in an error message being appended to the messages our app sends:

<img width="924" alt="teams1" src="https://user-images.githubusercontent.com/1859164/111520835-b7a46780-8715-11eb-97b8-7a6c833b3ef3.png">

(screenshot redacted as app is not publicly available yet)

There is also an alert in the connectors configuration UI:

<img width="815" alt="teams2" src="https://user-images.githubusercontent.com/1859164/111521307-3b5e5400-8716-11eb-935f-ee97d87dd3b1.png">

When I click through the "Manage" button, debugger indicates the old URL format is still being returned by `getSettings`.

We're using v1.9 of the SDK.

**Comment by chrisatkin** [comment]
@RamaMohanaChary we're seeing this issue on a custom app, not the Incoming Webhook app. Accordingly, we are unable to use an "Update URL" button as we cannot implement it on our app.

When I set up the webhook, I specified a page to load as the configuration page. When the Teams client loads our configuration page, we use the [Teams JS](https://www.npmjs.com/package/@microsoft/teams-js) library to interact with the Teams API/client. One of the pieces of information we retrieve from Teams is the webhook URL (using `microsoftTeams.settings.getSettings`), which is sent to our systems via API calls. The issue is that the webhook URL returned by `getSettings` uses the old format and not the new format. When sending messages through the old format, warnings appear as in my screenshot.

Webhook URLs in the old format follow the following format: `https://outlook.office.com/Webhook/[GroupExternalObjectGuid]...`, whereas new-style URLs use the format `https://[tenantName].webhook.office.com/...`.

Furthermore, when the Teams client displays the warning ("Attention required") for a connection, `getSettings` _still_ returns the old URL format. This is the bug. `getSettings` always returns the _old_ URL format, and not the new one. Custom apps implementing a inbound webhook have no way of determining a webhook URL that will not produce the warning.

**Comment by Wajeed-msft** [comment]
@Nikitha-MSFT - Could you please check this?

**Comment by Nikitha-MSFT** [comment]
When you are getting the web-hook URL from the get settings, it will return the URL which is configured for the channel. To get the Updated URL in get settings you need to update the web-hook URL in the UI as Rama mentioned and then get the web-hook URL using Get settings. Try if that helps.

**Comment by chrisatkin** [comment]
@Nikitha-MSFT I guess I’m just not understanding this. We have a _custom_ app; we aren’t using the incoming web hook app. I can’t see how to implement the “update URL” button in a custom app?

**Comment by Wajeed-msft** [comment]
Hi @chrisatkin - I checked this internally with engineering team. Only option for 3P connectors is to remove and add new configuration. Old webhook URLs will stop working in future, however I don't have an ETA to share.

**Comment by chrisatkin** [comment]
@Wajeed-msft thanks for checking, I appreciate it. Just to be clear then, the official solution to this is to keep reinstalling our app when the URL expires? Because we never seem to be given the new format through `getSettings`,  only the old one. And at some point in the future they’ll just stop working?

**Comment by Wajeed-msft** [comment]
@chrisatkin - For already configured Connectors you will still get existing configured webhook URL when you call `getSettings`. But when you configure a new Connector to a channel, you should receive new webhook format. Are you getting new format for new configurations?

**Comment by chrisatkin** [comment]
@Wajeed-msft as far as I can tell, we are always getting the old format. Our app is fairly new, and we caught this in testing starting around two weeks ago.

**Comment by chrisatkin** [comment]
@Wajeed-msft @Nikitha-MSFT just wondering if there any updates on this?

**Comment by RamaMohanaChary** [comment]
Hi @chrisatkin, 

Checking internally with the team, will get back to you soon.

**Comment by Wajeed-msft** [comment]
@chrisatkin - We tried on one of the demo tenant and we are getting new format. Checking with engineering team on what additional information is needed to debug this issue.

**Comment by Wajeed-msft** [comment]
@chrisatkin - could you please share the Connector Id so that we can check logs?

**Comment by chrisatkin** [comment]
@Wajeed-msft our QA team has been testing whether "remove and add it again" is a suitable fix, but I can share that the connector with ID `e975b41c-ae96-41fc-9a0b-e17d03ada11f` displays the behaviour.

Some additional IDs that may help you pinpoint this specific connector instance, pulled from calling `microsoftTeams.getContext` within the frame associated with this connector:
- `channelId`: `19:d2c63a2e59d648a6accaa066f57f0c4d@thread.tacv2`
- `groupId`: `209348a4-d178-4fa9-b027-fdacbac3bc14`
- `teamId`: `19:d2c63a2e59d648a6accaa066f57f0c4d@thread.tacv2`
- `sessionId`: `f2d588e7-8be0-aa5c-e7f8-8cf23d3e3dda`
- `tid`: `93499d0f-2776-4f2d-ba43-0bc475f4c8e1`
- `userObjectId`: `203ee8b5-94e6-4685-a765-e0a5ffb735d0`

For further info, I can also be reached at `catkin {at} guidespark {dot} com`. Thanks for looking into this.

**Comment by Wajeed-msft** [comment]
Hi @chrisatkin - This looks like a bug, checking more details. I'll keep you posted.

**Comment by chrisatkin** [comment]
@Wajeed-msft thanks, I appreciate it. FWIW, our release of Teams support is blocked until there's a resolution for this.

**Comment by Wajeed-msft** [comment]
@chrisatkin - meanwhile could you please try these two options for testing?

1. Try registering a new Connector through Connector dashboard and see if you are getting same issue.
2. Try your existing Connector on some other [demo tenant](https://developer.microsoft.com/en-us/microsoft-365/dev-program)

**Comment by chrisatkin** [comment]
@Wajeed-msft thanks for your suggestions - we'll look into it on our end too and get back to you

**Comment by chrisatkin** [comment]
@Wajeed-msft just checking in with you to see if you have any updates. My team isn't seeing this occur anymore, but it wasn't happening every time so we can't categorically rule it out.

**Comment by Wajeed-msft** [comment]
Are you getting new format webhook URL?

**Comment by chrisatkin** [comment]
We are getting the new format. I would say though, we were sometimes getting the new format before too, so we can’t say definitively that the bug is fixed. It could just be coincidence that we haven’t seen it happen recently as it did seem to be quite rare - we’re looking for guidance from you in that regard.

**Comment by Wajeed-msft** [comment]
All custom connectors using SDK should receive new webhook URL when newly created now. Could you please let me know if you face this issue anytime going forward? Please feel free to re-open if you face it again.
