### ISSUE TITLE
Not sending Accept Response from team calender.

### ISSUE THREAD

**Issue by sudoaccessdenied** [OfficeDev/microsoft-teams-library-js#535]
### I have create a meeting for channel in which User is  the member of the teams channel.But when the  Channel member accept the meeting invitation from the teams calender  it is not showing Accepted.
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/30634773/112447312-31240180-8d77-11eb-9b57-86a6f89b609d.png)

### The user accepted from teams calender as show in figure. However it is working fine if we accepting  after opening it.
![image](https://user-images.githubusercontent.com/30634773/112447082-e99d7580-8d76-11eb-9c75-5596f9d4e068.png)

**Comment by Mamatha-MSFT** [comment]
Thanks for reaching out us. We are the developer support team for Microsoft teams focused on helping developers resolve their issues. For issues related to teams product, please reach out to the [product support channels](https://docs.microsoft.com/en-us/microsoftteams/platform/feedback#product-support-channels) for Microsoft Teams.
