### ISSUE TITLE
Context is different on private channel

### ISSUE THREAD

**Issue by MonalisaBaltatescu** [OfficeDev/microsoft-teams-library-js#538]
![teams context private channel](https://user-images.githubusercontent.com/32879490/113307562-f4737f80-930d-11eb-8194-35d5062c0e7c.png)
![teams context public](https://user-images.githubusercontent.com/32879490/113307601-fd645100-930d-11eb-86de-33a3f66001f2.png)

The Teams context has a different definition between a private channel and a standard channel. See the attached pictures.

       On a private channel, the group Id (used to retrieve the team info) is missing.
       On a private channel, the channel id is equal to the team Id.
       On a private channel, the channel name is equal to the team name.

**Comment by Nikitha-MSFT** [comment]
we are looking into it get back to you soon

**Comment by Nikitha-MSFT** [comment]
Need to add channel id and channel name will be undefined for private channels in [Retrieving context in private channels](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context#retrieving-context-in-private-channels).

**Comment by MonalisaBaltatescu** [comment]
Thanks for answering! Although my problem is not fully soled because I am trying to retrieve the members of a private channel using graph api, but I don't have the channel id. What should I do next?

**Comment by Nikitha-MSFT** [comment]
You can get channel id using graph API. Please check [List Channels](https://docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&tabs=http)

**Comment by ChetanSharma-msft** [comment]
Hello @MonalisaBaltatescu - Hope you are doing well!!
Could you please confirm whether your issue has resolved or still looking for any help?

**Comment by BerndGewehr** [comment]
Only a few teams apps work in private channels, not even planner, Project or the channel calendar. A better API support could be the most important thing to bring improvement for many of those apps...
