### ISSUE TITLE
MeetingId is incorrect

### ISSUE THREAD

**Issue by lemonpowah** [OfficeDev/microsoft-teams-library-js#539]
Hi everyone,

I've been playing around with the InMeetings apps and I was trying to get the online meeting object through graph API. The problem is, the context object returned in the teams app contains a corrupted or shall I say completely different meetingId.

Thus, when trying to query graph for the online meeting in question the response is:
```
{
    "error": {
        "code": "BadRequest",
        "message": "Meeting Id is corrupted.",
        "innerError": {
            ...
        }
    }
}
```
You can check [this issue](https://github.com/microsoftgraph/microsoft-graph-docs/issues/11696) from the microsoft-graph docs repo for more info. It's essentially the same issue and I think it rather belongs here.

As per my [comment ](https://github.com/microsoftgraph/microsoft-graph-docs/issues/11696#issuecomment-813457028) there, I am able to obtain the actual meeting Id through the joinWebUrl and it's entirely different:

- Teams sdk returns: 
```
MCMxOTptZWV0aW5nX05USTRNakEzT0dVdFl6TTNZUzAwWVRCbUxUa3lPR010TmpOaFpUSmhPVGswTldReEB0aHJlYWQudjIjMA==
``` 
- The actual id is: 
```
MSpkYWY2MmNjOC1lZTJkLTQxN2ItODg4NC1iY2Y0MGM0MTI5YzMqMCoqMTk6bWVldGluZ19OVEk0TWpBM09HVXRZek0zWVMwMFlUQm1MVGt5T0dNdE5qTmhaVEpoT1RrME5XUXhAdGhyZWFkLnYy
```

**Comment by Nikitha-MSFT** [comment]
Currently the specific meeting metadata received from client sdk can not be used to interact with graph. This is by design.

**Comment by AJIXuMuK** [comment]
@Nikitha-MSFT if the provided metadata can't be used to interact with MS Graph then it's useless in many cases in scenarios.
What was the intention to block developers from accessing MS Graph based on provided metadata?

**Comment by Nikitha-MSFT** [comment]
We are checking internally, get back to you soon.

**Comment by Nikitha-MSFT** [comment]
We are working to provide more details. Currently the GetMeetingsDetail() API of BotSDK will return basic information for the meeting, such as the organizerId, the meetingResourceId, and the joinWebUrl of the meeting. 
 
You will be able to use this information to make the following calls to Graph in 'user context':
GET https://graph.microsoft.com/beta/users/{organizedId}/onlineMeetings/{meetingResourceId}

GET https://graph.microsoft.com/beta/users/{organizedId}/onlineMeetings/?$filter=joinWebUrl eq {joinWebUrl}
