### ISSUE TITLE
Feature Requests: Specify surrounding frame's background color in context

### ISSUE THREAD

**Issue by abdulkareemnalband** [OfficeDev/microsoft-teams-library-js#542]
Teams design team keeps on changing background color for frame surrounding task modules , tabs and such

Every time that is updated, we need to spend time to update our application style to match teams to make it look more integrated in teams,

It will help us if we can get color value directly in context, and we can use that color match our apps background color

**Comment by marwalsch** [comment]
Starting June Teams will [remove the margin](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/removing-tab-margins) for tabs, which might be a solution since you can define the margin's colour by yourself. Obviously this doesn't work for task modules though.

**Comment by Sridevi-MSFT** [comment]
@abdulkareemnalband, Please raise a UserVoice [here](https://microsoftteams.uservoice.com/), if this needs to be considered as a future request.

**Comment by abdulkareemnalband** [comment]
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/43172040-feature-request-specify-surrounding-frame-s-backg

**Comment by abdulkareemnalband** [comment]
Background color for task module is updated again in dark theme

**Comment by Nikitha-MSFT** [comment]
Could you please check Teams UI Toolkit should contain all the information, also please check this https://www.figma.com/community/file/916836509871353159 / [design toolkit](https://docs.microsoft.com/en-us/windows/uwp/design/downloads/) for more info.
