### ISSUE TITLE
Request documentation: how to create a new pop up window for third party auth

### ISSUE THREAD

**Issue by BustosAndrew** [OfficeDev/microsoft-teams-library-js#543]
I need documentation, in JS, regarding how we can create a temporary window to authenticate a user with an integrated web app. For context, I'm integrating a file/folder viewer using Box's api. Box requires access tokens for users to have access to their files and folders. It would be easier if there were docs on how to make external auth easier without the need to change the content page of the team tab. Edit: I was just informed that we can create task windows, but I believe third party auth should be addressed in documentation.

**Comment by ChetanSharma-msft** [comment]
Hello @BustosAndrew - Sorry for delay in response.
Could you please confirm whether you are still facing this issue or is it resolved?

**Comment by Wajeed-msft** [comment]
@BustosAndrew - This is covered as part of [Enable authentication using third-party OAuth provider](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-flow-tab) documentation. You can use authentication.authenticate() to [initiate authentication flow](https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-tab-aad?tabs=teamsjs-v2#initiate-authentication-flow) by passing URL of third party auth provider.  

Closing this issue from the tracking list of issues. Please feel free to re-open if you are still having issues.
