### ISSUE TITLE
`getTabInstances` never resolves on mobile.

### ISSUE THREAD

**Issue by ascott18** [OfficeDev/microsoft-teams-library-js#544]
1. Call the following code in a tab app in the Android version of Teams:
	  ```ts
	  microsoftTeams.initialize(() => {
		  console.log("Initialized")
		  microsoftTeams.getTabInstances((tabInfo) => {
			  console.log("Tabs", tabInfo)
		  }, {
	        favoriteChannelsOnly: false,
	        favoriteTeamsOnly: false,
	      });
	  });
	  ```
2. Observe that `"Initialize"` is printed, but `"Tabs"` nor the expected array of tab info is never printed. This is causing our app to hang because basic Teams SDK functionality is not implemented as documented. If the SDK is for some reason unable to fetch info about installed tabs, it should immediately throw rather than hanging and never resolving.

Edit: Just confirmed that this is broken in the same way on the IOS Teams mobile app.

**Comment by Jagadeesh-MSFT** [comment]
Hi @ascott18 , we are working on it , will update you soon.

**Comment by Jagadeesh-MSFT** [comment]
Hi @ascott18, we are able to repro this issue from our end , we will raise a bug and will share with you.

**Comment by Jagadeesh-MSFT** [comment]
Hi @ascott18, Thanks for the insights, we will update the same in bug , our team is working on it. Currently we don't have any ETA to share with you.

**Comment by mykyta-Koptsov** [comment]
hi, guys 
our team have the same issue. ` getTabInstances`  doesn't work on mobile application.
Any updates on this issue ? 
in Web and Desktop  application this approach works fine 
```
microsoftTeams.initialize();
microsoftTeams.getTabInstances((tabInfo) => {
  	  console.log("Tabs", tabInfo)
    }, {
      favoriteChannelsOnly: false,
      favoriteTeamsOnly: false,
   });
```
I tried to wrap code in Promise but it didn't work for me
```
new Promise((resolve, reject) => {
microsoftTeams.initialize(() => {
    console.log("Initialized")
    microsoftTeams.getTabInstances((tabInfo) => {
  	  console.log("Tabs", tabInfo)
    }, {
      favoriteChannelsOnly: false,
      favoriteTeamsOnly: false,
    });
});
});
```

**Comment by mykyta-Koptsov** [comment]
And the same isuue I have with `microsoftTeams.getMruTabInstances` function never resolves on mobile application.

**Comment by RobPethick** [comment]
@v-chetsh @Jagadeesh-MSFT - any time updates on this? This is a critical issue for us too

**Comment by ascott18** [comment]
@ydogandjiev Do you have any updates on this issue? This is still an absolutely major issue for us. @Jagadeesh-MSFT who was working this issue hasn't been active on GitHub in almost a year.

**Comment by Meghana-MSFT** [comment]
@ascott18 - This issue has been converted to requirement as this was not implemented on Mobile. We will check with engineering team.

**Comment by Meghana-MSFT** [comment]
Engineering team has confirmed this JS API is not implemented on Mobile. We will get the doc updated mentioning the same.

**Comment by teemukolehmainen-howspace** [comment]
How is it then possible to get the ID of the current tab in mobile SDK?

**Comment by Meghana-MSFT** [comment]
We are checking this internally; we will update you.

**Comment by Meghana-MSFT** [comment]
Can you please try [getSettings](https://github.com/OfficeDev/microsoft-teams-library-js/blob/972735033b80462c458dd28a0aa7e4b4735c99c9/packages/teams-js/src/public/settings.ts#L69)? it's implemented on Mobile.

**Comment by teemukolehmainen-howspace** [comment]
> Can you please try [getSettings](https://github.com/OfficeDev/microsoft-teams-library-js/blob/972735033b80462c458dd28a0aa7e4b4735c99c9/packages/teams-js/src/public/settings.ts#L69)? it's implemented on Mobile.

getSettings only returns the entityID, not the actual UUID of the tab which we need for activity notifications.

**Comment by Meghana-MSFT** [comment]
@teemukolehmainen-howspace - Engineering team has shared the below suggestions.

The getTabInstances API is not the right thing to use here. This API enumerates all tabs across all the user's teams & channels (and is therefore very slow). Also, it doesn't work in group chats or private scheduled meetings. Hence it is advised not to use this API for this purpose.

Here is an example of notification to tab. It requires tabId which can be retrieved by listing tabs in the channel. 

[team: sendActivityNotification - Microsoft Graph beta | Microsoft Learn](https://learn.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&tabs=http#example-2-notify-a-user-about-a-channel-tab)

**Comment by Wajeed-msft** [comment]
We have raised feature request for supporting getTabInstances on mobile. Currently we do not have an ETA when this would be implemented. Raised documentation update request here: https://github.com/MicrosoftDocs/msteams-docs/issues/8244

**Comment by Wajeed-msft** [comment]
@ascott18 - I have raised this with mobile engineering team once more.

**Comment by ChetanSharma-msft** [comment]
Hello @ascott18 - Sorry for delay in response.
We are actively checking with engineering team on your query and let you know the updates, if any.

**Comment by ChetanSharma-msft** [comment]
The getTabInstances API isn't implemented on Teams mobile.

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.

**Comment by AE-MS** [comment]
FYI I updated the teams-js library to now properly report `pages.tabs.isSupported() === false` on Teams mobile platforms in PR #2010
