### ISSUE TITLE
Missing image Exif/Metadata

### ISSUE THREAD

**Issue by joseph-passineau** [OfficeDev/microsoft-teams-library-js#547]
Hi,

I'm using microsoftTeams.media.selectMedia to retrieve images from the users phone. Then, for each attachments (microsoftTeams.media.Media), I call the media.getMedia method in order to retrieve the blob.

What I noticed is that pretty much all the Exif/Metadata of the images are gone.

Not sure if this is intended or not.

Thanks,
Joseph

**Comment by ChetanSharma-msft** [comment]
Hello @joseph-passineau - Sorry for delay in response.
Could you please confirm whether you are still facing this issue or is it resolved?

**Comment by joseph-passineau** [comment]
Hi @ChetanSharma-msft 
We decided not to go with Microsoft Teams in the end since one of the requirement for our application was to be able to read Exif/Metadata.

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.

**Comment by Wajeed-msft** [comment]
Raised this on [Microsoft Teams feedback portal](https://feedbackportal.microsoft.com/feedback/idea/13d84df4-41bc-ed11-a81b-000d3a0450e3). 
Closing this from issues page.
