### ISSUE TITLE
microsoftTeams.media.scanBarCode crashes MS Teams on iOS when in dark theme

### ISSUE THREAD

**Issue by martin1996-de** [OfficeDev/microsoft-teams-library-js#555]
Hi all,

I just figured out that using scanBarCode on an iOS device crashes the whole app when using the dark theme.

Can someone confirm?

Thanks
Dennis

**Comment by martin1996-de** [comment]
Hi @Wajeed-msft and @Nikitha-MSFT ,
with version 3.6.0 on iOS the issue has been fixed.
Can you confirm that the product team fixed this issue?

**Comment by ChetanSharma-msft** [comment]
@martin1996-de - Looks like your issue has resolved.

We are closing this issue for now, please feel free to reopen it, if required.
