### ISSUE TITLE
Force settings dialog to update my configurableTabs

### ISSUE THREAD

**Issue by nansou13** [OfficeDev/microsoft-teams-library-js#559]
Hello, 

First of all, thank you for this awesome librairy. I would like to share with you my problem on my configurableTabs. I modified the url of `contentUrl` in `microsoftTeams.settings.setSettings `but everyone who use my application before, use the old Url. Is it possible to force the opening of the settings dialog? Is there any other solution to modify without asking the customers to modify all their urls

Best regards ! 
Nans

**Comment by ydogandjiev** [comment]
@nansou13, you can actually call the `microsoftTeams.settings.setSettings` API within your tab's content page as well so you can implement a just-in-time migration flow that allows you to update your `contentUrl` when users visit your tab. For example, you could try doing something like this:
```
document.body.onload = () => {
  microsoftTeams.initialize();
  microsoftTeams.settings.getSettings(settings => {
    if (isOldUrl(settings.contentUrl)) {
      settings.contentUrl = updateUrl(settings.contentUrl);
      microsoftTeams.settings.setSettings(settings);
    }
  });
};
```

Alternatively, if you want to do this migration without waiting for users to visit your tabs then you can do that via the tabs Teams Graph APIs documented here:
https://docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta

**Comment by nansou13** [comment]
oh thank you @ydogandjiev !! it works well.
