### ISSUE TITLE
Sometimes getAuthToken hang without trigger callback function

### ISSUE THREAD

**Issue by SLdragon** [OfficeDev/microsoft-teams-library-js#562]
Hi, team, I am using teams sdk to get SSO token, however, sometimes I wait about 5 second, the  ```getAuthToken``` callback function still not trigger. 
I am wondering what's the best practice to handle this scenario, or are there some timeout inside the getAuthToken function so that I can reuse it？

```
microsoftTeams.initialize(() => {
        microsoftTeams.authentication.getAuthToken({
          successCallback: (token: string) => {
           console.log(token)
          },
          failureCallback: (errMessage: string) => {
            console.log(errMessage);
          },
          resources: []
        });
});
```

**Comment by Jagadeesh-MSFT** [comment]
Hi @SLdragon, we are working on it, will update you soon.

**Comment by Jagadeesh-MSFT** [comment]
Hi @SLdragon , we are unable to repro your issue from our end , could you please let us know if you are still facing the issue.

**Comment by SLdragon** [comment]
Thanks, I think this is related to this issue: https://github.com/OfficeDev/microsoft-teams-library-js/issues/580, we can use that one to track

**Comment by Jagadeesh-MSFT** [comment]
Hi @SLdragon, we are closing this issue here and will track from  [#580](https://github.com/OfficeDev/microsoft-teams-library-js/issues/580), feel free to reopen the issue if you have any further quires on this.
Thank you .
