### ISSUE TITLE
Compose message/card from a configurable tab

### ISSUE THREAD

**Issue by dylanvdbrink** [OfficeDev/microsoft-teams-library-js#565]
Hi,

I've also submitted [an issue on StackOverflow](https://stackoverflow.com/q/66602012/3021549) but someone with a MSFT suffixed username replied that my use case cannot be done with the latest version of the Teams library.

I've also explained it in the StackOverflow issue but what I am trying to do is the following:

I have created an Angular application which uses the Microsoft Teams Javascript library. A page/route from this Angular app is shown within a Microsoft Teams configurable tab. From this tab I would like to be able to click a button which will "pre-compose" a message in the chat of the channel/chat of where the configurable tab is installed. So when the button is clicked, Teams should navigate to the "Posts" tab of the channel/chat and fill in the text/url/string in the chat and let the user decide to press enter to send it.

I've read the documentation but I cannot conclude that this is possible. I've looked at creating a task module but for a configurable tab this only seems to be able to open dialogs to get the user to fill in data and call a service. The bot documentation also seems to mention filling the compose box of the chat but the documentation is not very clear in specifying how the bot should be called from a configurable tab.

We use this same functionality from a message extension, which opens a task module with a frame and from there a user can click on a button to compose a message, but the configurable tab shows a more advanced searching UI so we would like to have this functionality from there as well.

Thanks,
Dylan

**Comment by Mamatha-MSFT** [comment]
Hi @dylanvdbrink Taking this for internal discussion with team, I will update you with resolution.

**Comment by Mamatha-MSFT** [comment]
Hi @dylanvdbrink You can "pre-compose" a message in the chat using [deeplinking to the chat](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links#deep-linking-to-a-chat) but it doesn't support card to send.
 we recommend you to raise a Teams UserVoice [here](https://microsoftteams.uservoice.com/) if this needs to be consider as a future request.
