### ISSUE TITLE
registerBeforeUnloadHandler still not implemented 2+ years later.

### ISSUE THREAD

**Issue by ascott18** [OfficeDev/microsoft-teams-library-js#575]
Title in reference to https://github.com/OfficeDev/microsoft-teams-library-js/issues/219 from June 2019. There's still no way to perform any actions when your app is about to be unloaded (manual reload, navigate away, etc).

What is the timeline for this feature? If there are no plans to implement it, why does it still exist in current versions of the SDK?

**Comment by Sridevi-MSFT** [comment]
@ascott18 - Thanks for bringing up this issue, Let us investigate at our end.

**Comment by Sridevi-MSFT** [comment]
@ascott18 - This API has already been implemented and developers should be able to use it in their tab content pages.

**Comment by ascott18** [comment]
@Sridevi-MSFT this is not true. The callback we provide to the `registerBeforeUnloadHandler` function is never called for us. It is also still undocumented on https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/microsoftteams?view=msteams-client-js-latest.

**Comment by Trinetra-MSFT** [comment]
Hi @ascott18 , Could you please confirm if you are using the latest [teams client SDK](https://statics.teams.cdn.office.net/sdk/v1.10.0/js/MicrosoftTeams.min.js) in your Tab page?

**Comment by ascott18** [comment]
We're using 1.9.0, which per this very repository, is the latest version.
![image](https://user-images.githubusercontent.com/5017521/120866280-72d5e300-c544-11eb-8771-bc9709cf5306.png)

**Comment by Trinetra-MSFT** [comment]
@ascott18 , Yes v.1.10.0 is the latest one, but this method is also available in v1.9.0 as well, @Sridevi-MSFT , Could you please try to integrate this in an configuration page?

**Comment by Sridevi-MSFT** [comment]
@ascott18 - I have integrated the microsoftTeams.registerBeforeUnloadHandler() in configuration page and it's working fine.
Could you please check this with latest SDK version 1.10.0 

`<script src="https://statics.teams.cdn.office.net/sdk/v1.10.0/js/MicrosoftTeams.min.js" integrity="sha384-6oUzHUqESdbT3hNPDDZUa/OunUj5SoxuMXNek1Dwe6AmChzqc6EJhjVrJ93DY/Bv" crossorigin="anonymous"></script>`

**Comment by ascott18** [comment]
Thanks for enabling it, looks like its working now. 

However, I must reiterate that it is still entirely undocumented on https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/microsoftteams?view=msteams-client-js-latest

**Comment by Sridevi-MSFT** [comment]
Add microsoftTeams.registerBeforeUnloadHandler() function in this documentation https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/microsoftteams?view=msteams-client-js-latest

**Comment by kafka-yu** [comment]
team, just want to double confirm: `registerBeforeUnloadHandler` this handler won't stop the tab been navigated away right?

I saw the source code, it just tells the parent of the window that the tab is `readyToUnload`, no other blocking actions.

Are we able to do stop/interrupting against the navigating away action?

**Comment by erinha** [comment]
Hello @kafka-yu and @ascott18, I'm really sorry this is still not fully resolved! 

The `registerBeforeUnloadHandler` API has been implemented and @ascott18 you're correct, the handler won't stop navigation away from the tab.

We're working on adding the reference documentation for the handler and updating the docs to be more helpful. 

Apologies again for the delay!

**Comment by ChetanSharma-msft** [comment]
Hello @kafka-yu and @ascott18 - Sorry for delay in response.
Just wanted to let you know that engineering team is pro-actively working on it.
We will share you the updates, once it is fully resolved.

**Comment by MuhammadAli-208** [comment]
Any update on this? 
i need to open a confirmation popup when user click any other tab, so if he has any unsaved changings. He can save them before unloading tab.

**Comment by MuhammadAli-208** [comment]
[msftbot](https://github.com/apps/msftbot)

**Comment by ChetanSharma-msft** [comment]
Hello @MuhammadAli-208 - 

Just wanted to let you know that engineering team is pro-actively working on it and currently we don't have any exact ETA to share.
We are closely tracking it from our end and let you know the updates once it is fixed.

**Comment by alexneyman-MSFT** [comment]
Hey everyone, I'd like to clarify the current state of the handlers `registerOnBeforeUnloadHandler` and `registerOnLoadHandler`. As of right now, these handlers should have no functionality when called. These two handlers are currently marked as hidden and internal becaues we're currently working on enabling support for `onBeforeUnload` and full caching of apps in certain contexts. While we're still relatively uncertain on the timeline of these features, we are actively working on them and will keep everyone updated as progress is made.  We're also working on updating docs regarding these handlers and improving future documentation of experimental features so we can avoid confusion we may have caused in the past.

**Comment by alexneyman-MSFT** [comment]
Another quick update here: these handlers should be available anywhere that app caching is available in teams, i.e. personal apps, chat/channel/calendar tabs, meeting sidepanel apps. It will not work in any other surfaces (e.g. task module, stage view, meeting stage, etc.). Full docs for the current state of app caching can be [found here.](https://learn.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/build-tabs-for-meeting?tabs=desktop%2Cmeeting-chat-view-desktop%2Cmeeting-stage-view-desktop%2Cchannel-meeting-desktop#app-caching)

Please let me know if there are any issues.
