### ISSUE TITLE
Error: not_specified

### ISSUE THREAD

**Issue by ascott18** [OfficeDev/microsoft-teams-library-js#577]
We're seeing the following error in our production logs. Please advise on how we're meant to deal with the "not_specified" error from Teams. Perhaps Teams should generate better error messages?

@microsoft/team-js version: 1.9.0

```
Error: not_specified
    at webpack:///node_modules/@microsoft/teams-js/dist/MicrosoftTeams.min.js:1:8959
    at apply (webpack:///node_modules/@microsoft/teams-js/dist/MicrosoftTeams.min.js:1:2816)
    at u (webpack:///node_modules/@microsoft/teams-js/dist/MicrosoftTeams.min.js:1:6944)
    at processMessage (webpack:///node_modules/@microsoft/teams-js/dist/MicrosoftTeams.min.js:1:37798)
```

**Comment by Jagadeesh-MSFT** [comment]
Hi @ascott18, could you please share the repro steps o mitigate the issue.

**Comment by ascott18** [comment]
I have no explanation for this - we're just seeing this error happening for some users in our production logs. This isn't something that our code is doing - as you can see, the stack trace is entirely within Teams code. Teams is throwing useless, nondescriptive errors. We'd like for this issue to be fixed by Microsoft in the event that it is a symptom of something causing an adverse user experience.

**Comment by Nikitha-MSFT** [comment]
In production logs means are you using developer tools to capture log? Could you please share how you are capturing the logs? Also please specify when you are getting the "not_specified" errors? Are you receiving this on action performed? Could you please explain your scenario in more detail?

**Comment by ascott18** [comment]
- We're seeing this error in the Application Insights logging that we have running in our app. 
- Our end users are encountering this error. We do not have any information about what the users were doing, or even who the users are. 
- We're seeing this at all stages of page lifecycle (sometimes a second or two after page load, sometimes several minutes after page load). 
- So far, all instances of this error have happened in the Teams desktop app - never on mobile or in the browser.

**Comment by Jagadeesh-MSFT** [comment]
Hi @ascott18, we are taking this to our internal team, will update you soon.

**Comment by Ravindra-MSFT** [comment]
HI @ascott18, it seems like the developer might have a bug in integration with the ApplicationInsights-JS SDK which is resulting in these not_specified errors getting logged. Can you please take a look at this similar issue and double check that they are correctly passing the exception information to the App Insights SDK.

**Comment by Jagadeesh-MSFT** [comment]
Hi @ascott18, it seems like there might have a bug in your integration with the ApplicationInsights-JS SDK which is resulting in these not_specified errors getting logged. Could you please take a look at this similar issue and double check that you are correctly passing the exception information to the App Insights SDK:
Getting error messages of the format not_specified at e.sendExceptionInternal · Issue #1006 · microsoft/ApplicationInsights-JS (github.com)

**Comment by ascott18** [comment]
@Jagadeesh-MSFT We are not manually calling `trackException` - this is being caught by the passive error catching mechanisms of the AI JS SDK.

**Comment by Jagadeesh-MSFT** [comment]
Hi @ascott18, we are taking this to our internal team, will update you soon.

**Comment by Wajeed-msft** [comment]
@ydogandjiev - do you know what might be going wrong here?

**Comment by Wajeed-msft** [comment]
@ascott18 - we are unable to repro this at our end. Would it be possible for you to get repro steps?

**Comment by ascott18** [comment]
No. As I previously mentioned, 

> I have no explanation for this - we're just seeing this error happening for some users in our production logs.

and 

> Our end users are encountering this error. We do not have any information about what the users were doing, or even who the users are.

**Comment by v-chetsh** [comment]
@ascott18 - We have raised a internal bug for it and engineering team is looking into it

**Comment by ydogandjiev** [comment]
Spent some more time on this issue today. Pulling up v1.9.0 of the Client SDK in VS Code I looked for the code called out in the exception stack:
![image](https://user-images.githubusercontent.com/3357245/144342207-f159c87e-c367-4685-b8e6-c8e756c7930a.png)

And got this:
![image](https://user-images.githubusercontent.com/3357245/144342191-52ee4f52-075d-4c49-81de-d0ca198c484f.png)

Which appears to be this code:
https://github.com/OfficeDev/microsoft-teams-library-js/blob/fef94899bd1eec65670d82a84e5b1d752c590c54/src/internal/utils.ts#L22

So that means you are most likely calling one of these APIs without a callback:
- settings.setSettings
- executeDeepLink
- postMessage (to task module)

And when the API call fails the generic callback handler throws an exception. @ascott18, can you try passing your own callback function to these API calls and using it to log a more obvious error message to your traces?
