### ISSUE TITLE
Break point inside getAuthToken would make microsoftTeams.getContext callback hang

### ISSUE THREAD

**Issue by SLdragon** [OfficeDev/microsoft-teams-library-js#580]
Hi, team,
I have a react Teams Tab project, the code is as below:
```
import React from "react";
import * as microsoftTeams from "@microsoft/teams-js";

export interface IAppState {
  token1: string,
  locale: string
}

 export default class App extends React.Component<{}, IAppState> {

  constructor(props: any) {
    super(props);
    this.state = {
        token1: "",
        locale: ""
    }
  }

  async componentDidMount() {
    microsoftTeams.initialize();
    microsoftTeams.authentication.getAuthToken({
      successCallback: (token: string) => {
          this.setState({token1: "This is access token: " + token});
      },
      failureCallback: (errMessage: string) => {
          console.log(errMessage);
      },
      resources: []
    });

    microsoftTeams.getContext((context: microsoftTeams.Context) => {
      this.setState({locale: "This is locale: " +  context.locale!})
    });
  }

  public render(): JSX.Element {
    return (
      <div>
        <p>{this.state.token1}</p>
        <p>{this.state.locale}</p>
      </div>
    );
  }
}

```

It will show SSO token and current locale as below:
![image](https://user-images.githubusercontent.com/5545529/118578705-358cf980-b7bf-11eb-9975-c7295f6c78da.png)

However, if I add a break point inside ```successCallback``` as below, then continue run the Tab App, then the getContext call back would never fired, it will hang forever.

![image](https://user-images.githubusercontent.com/5545529/118578858-83a1fd00-b7bf-11eb-8c47-c6eda56f7a2c.png)

Other information:
If I clear all the cache from dev tool, then it will work for the first time if I added a breakpoint, next time it will hang
![image](https://user-images.githubusercontent.com/5545529/118579094-fad79100-b7bf-11eb-9a3a-c81d1d670cf0.png)

The version of the SDK is 1.9.0

**Comment by Jagadeesh-MSFT** [comment]
Hi @SLdragon, we are working on it, will update you soon.

**Comment by SLdragon** [comment]
Any update?

**Comment by Jagadeesh-MSFT** [comment]
Hi @SLdragon, Sorry for the delayed response. we will share the update by today EOD.

**Comment by Jagadeesh-MSFT** [comment]
Hi @SLdragon, we have tested this from our end, I am able to repro your scenario, we are taking this to internal discussion.

**Comment by SLdragon** [comment]
Thanks, if your team need some test samples, I can provide it

**Comment by Jagadeesh-MSFT** [comment]
Hi @SLdragon, yah, that will help more , please share some more samples as well.

**Comment by SLdragon** [comment]
Sure,
Here are the sample and steps:
1. Install VSCode Teams extension here: https://marketplace.visualstudio.com/items?itemName=TeamsDevApp.ms-teams-vscode-extension
2. Download this sample and open it in VSCode: 
[sample.zip](https://github.com/OfficeDev/microsoft-teams-library-js/files/6588546/sample.zip)

3. Add two break point and click F5 to debug
![image](https://user-images.githubusercontent.com/5545529/120578115-e2ba6f80-c457-11eb-803b-b90b64eaa5ea.png)

**Comment by Jagadeesh-MSFT** [comment]
Hi @SLdragon, we have raised bug for this , our engineering team is working on it. We don't have ETA to share for the fix.

**Comment by SLdragon** [comment]
Thank you @Jagadeesh-MSFT

**Comment by ChetanSharma-msft** [comment]
Hello @SLdragon - Engineering team was not able to repro this issue. Both getAuthToken and getContext completing successfully no matter what breakpoints we set.

If you are still seeing this issue with the latest version of the Teams SDK please provide a minimal repro app that we can use to recreate the problem.
