### ISSUE TITLE
microsoftTeams.generateGUID is not a function

### ISSUE THREAD

**Issue by creage** [OfficeDev/microsoft-teams-library-js#582]
I'm running `@microsoft/teams-js` `1.10.0`, and according to [documentation](https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/microsoftteams?view=msteams-client-js-latest#generateGUID__) there should be a `generateGUID` function available as exported one.

Type definitions coming with package **have** this function defined, but it somehow fails to import it.

Trying to consume it in my TS project:
```ts
import * as microsoftTeams from "@microsoft/teams-js";

console.log(microsoftTeams.generateGUID());
```
results into error:
```
TypeError: _microsoft_teams_js__WEBPACK_IMPORTED_MODULE_1__.generateGUID is not a function
```

**Comment by Jagadeesh-MSFT** [comment]
Hi @creage , we are able to repro your issue from our end, we will take it to our internal team and will let you know.

**Comment by Jagadeesh-MSFT** [comment]
Hi @creage , We have raised a bug on this. Our engineering team is working on it , we don't have any ETA to share about the fix.

**Comment by ChetanSharma-msft** [comment]
Hello @creage - Sorry for delay in response.
We have raised a bug for it and informed internally.

We will let you know once we have any update on it.

**Comment by AE-MS** [comment]
Hi @creage, thanks for reporting this. I know this post is very old but I wanted to ensure there was a clear answer. The teams-js `generateGUID` function was not intended to be used by app developers; it was an internal utility function. The fact that it showed up in the documentation and was exported from the type definition file was a bug on our part. I have looked at the [current documentation](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/?view=msteams-client-js-latest) and [typing file](https://res.cdn.office.net/teams-js/2.8.0/js/MicrosoftTeams.d.ts) (as of the time of this writing) and ensured that `generateGUID` is no longer exported and no longer appears in the documentation.

FWIW this function was just a tiny wrapper around the [v4](https://www.npmjs.com/package/uuid#uuidv4options-buffer-offset) function in the [uuid package](https://www.npmjs.com/package/uuid), so if you are somehow still blocked by this, you should be able to use that package.
