### ISSUE TITLE
local storage not setting in authentication success callback

### ISSUE THREAD

**Issue by BustosAndrew** [OfficeDev/microsoft-teams-library-js#583]
here is the js code inside a react component: 
```js
const SetCookies = () => {
        GetAuthUrl().then((authorizationUrl) => {
            microsoftTeams.authentication.authenticate({
                url:
                    "https://box-integration-tab.herokuapp.com/?url=" +
                    encodeURIComponent(authorizationUrl),
                width: 600,
                height: 900,
                successCallback: function (result: string) {
                    GetTokenObject(result).then(function (tokenObj) {
                        // document.cookie = `access_token=${tokenObj.access_token};max-age=${tokenObj.expires_in};path=/;samesite=lax`;
                        // document.cookie = `refresh_token=${
                        //     tokenObj.refresh_token
                        // };max-age=${60 * 60 * 24 * 60};path=/;samesite=lax`; //two months
                        ls.set("access_token", `${tokenObj.access_token}`, {
                            ttl: 3600
                        });
                        ls.set("refresh_token", `${tokenObj.refresh_token}`, {
                            ttl: 3600 * 24 * 60
                        });
                    });
                    setShowLogin(false);
                    location.reload();
                },
                failureCallback: (result) => {
                    console.log(result);
                    // try {
                    //     ls.set("failed", "uhoh", { ttl: 30 });
                    //     console.log(ls.get("failed"));
                    // } catch (error) {
                    //     console.log(error);
                    // }
                    setShowLogin(true);
                    console.log(showLogin);
                }
            });
        });
    };
```
Failure callback always works, but upon successful login it never sets local storage. ls is some node module for handling local storage. To confirm, the start and end page of the auth flow are on the same domain.

Here is a vid describing the issue: https://youtu.be/qdyLejGBdE8

**Comment by BustosAndrew** [comment]
Is some part of ms teams functionality down? The fluent ui elements aren't even rendering.

**Comment by Mamatha-MSFT** [comment]
Hi @BustosAndrew - I will repro at my end and will get back to you.

**Comment by Mamatha-MSFT** [comment]
Hi @BustosAndrew - I have reproduced the same scenario that has been provided above. I am able to repro the issue with local storage setting  in authentication success callback. Will check this issue with internal team and will get back to you. 

For fluent UI it's working as expected in teams desktop client.  I have provided the screenshot of fluent UI element getting rendered in teams desktop client please check. 
![image](https://user-images.githubusercontent.com/78795357/120214742-84706f80-c252-11eb-93b3-e30a16d54df4.png)

**Comment by ravibhusal** [comment]
@BustosAndrew does the successCallback actually get triggered in your case or the issue is just that the localStorage isn't getting set?

**Comment by BustosAndrew** [comment]
It does get triggered but local storage won't set in the success callback.

**Comment by BustosAndrew** [comment]
Any update on this issue? Is there any workaround besides the one shown in the code sample?

**Comment by Mamatha-MSFT** [comment]
@BustosAndrew -  `ls.set()` is working as expected in `successCallback()`. Could you please confirm are you getting any value in `tokenObj` while `successCallback` method get triggered?

**Comment by BustosAndrew** [comment]
I'll let you know in the coming days.

**Comment by BustosAndrew** [comment]
I am not getting any value in the tokenObj when passing it into console.log().

**Comment by Mamatha-MSFT** [comment]
@BustosAndrew - Is GetTokenObject() is an predefined function or your customized function?

**Comment by BustosAndrew** [comment]
@Mamatha-MSFT it is a function I created/customized. Async function.

**Comment by Mamatha-MSFT** [comment]
@BustosAndrew - I have tried with async function in successCallback(). It's working as expected. I think the issue is with your customized GetTokenObject() function.

**Comment by BustosAndrew** [comment]
Sorry for the prolonged wait I will get back to you within a day.

**Comment by BustosAndrew** [comment]
I looked over my custom function and it's still not working on my end.

Function code:
```js
const GetTokenObject = async (code: string) => {
    const authenticationUrl = "https://api.box.com/oauth2/token";
    const clientDetails: any = await axios.get("/client");
    const params = new URLSearchParams({
        grant_type: "authorization_code",
        code: code,
        client_id: `${clientDetails.data.id}`,
        client_secret: `${clientDetails.data.secret}`
    });

    const tokenObj = await axios.post(authenticationUrl, params, {
        headers: { "Access-Control-Allow-Origin": "*" }
    });
    return tokenObj.data;
};
```

**Comment by Wajeed-msft** [comment]
@BustosAndrew - just because I see some commented code in snippet which talks about cookies, I am wondering if cookies  worked for you or not.  Please take a look at [SameSite cookie attribute updates](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/samesite-cookie-update). 

Regarding the repro part, would it be possible for you to share manifest/ sample code which we could use to repro at our end?

**Comment by BustosAndrew** [comment]
> @BustosAndrew - just because I see some commented code in snippet which talks about cookies, I am wondering if cookies worked for you or not. Please take a look at [SameSite cookie attribute updates](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/samesite-cookie-update).
> 
Cookies I faced the same issue.
Also, you're asking for me to share my manifest on here? @Wajeed-msft

**Comment by Wajeed-msft** [comment]
@BustosAndrew - you could share it directly on [Microsoft Teams Community Help](https://docs.microsoft.com/en-us/microsoftteams/platform/feedback) alias mention on the doc page.

**Comment by BustosAndrew** [comment]
Actually I'll just put my manifest on here if that's fine.

**Comment by BustosAndrew** [comment]
```json
{
    "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.8/MicrosoftTeams.schema.json",
    "manifestVersion": "1.8",
    "id": "{{APPLICATION_ID}}",
    "version": "{{VERSION}}",
    "packageName": "{{PACKAGE_NAME}}",
    "developer": {
        "name": "Andrew Bustos",
        "websiteUrl": "https://{{HOSTNAME}}",
        "privacyUrl": "https://{{HOSTNAME}}/privacy.html",
        "termsOfUseUrl": "https://{{HOSTNAME}}/tou.html"
    },
    "name": {
        "short": "Box-Tab",
        "full": "Box-Tab"
    },
    "description": {
        "short": "TODO: add short description here",
        "full": "TODO: add full description here"
    },
    "icons": {
        "outline": "icon-outline.png",
        "color": "icon-color.png"
    },
    "accentColor": "#D85028",
    "configurableTabs": [
        {
            "configurationUrl": "https://{{HOSTNAME}}/boxTab/config.html?name={loginHint}&tenant={tid}&group={groupId}&theme={theme}",
            "canUpdateConfiguration": true,
            "scopes": ["team"]
        }
    ],
    "staticTabs": [],
    "bots": [],
    "connectors": [],
    "composeExtensions": [],
    "permissions": ["identity", "messageTeamMembers"],
    "validDomains": ["{{HOSTNAME}}"],
    "showLoadingIndicator": false
}
```

Sorry for the delay @Wajeed-msft. I probably didn't mention before, but this project was generated with a yeoman generator for teams. Let me know if you need anything else.

**Comment by v-chetsh** [comment]
@BustosAndrew - Hope you are doing well!!
Could you please confirm whether you are still facing this issue or is it resolved?

If it is still pending, could you please share the codebase URL if you are referring any sample or minimal code so that we can try it.
