### ISSUE TITLE
Geolocation not working on desktop app error code 9000. Is supported?

### ISSUE THREAD

**Issue by ffarguelles** [OfficeDev/microsoft-teams-library-js#584]
When trying to access the geolocation data using `microsoftTeams.location.getLocation()` on desktop, I receive and error with code `9000`. The docs states that this error means the following:
> User is on old platform build where implementation of the API is not present. Upgrading the build should resolve the issue.

I'm using Microsoft Teams Version 11.4.00.11161

In this [document](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?tabs=mobile#use-teams-apis-to-get-device-permissions) it is stated that *Support for location is enabled through getLocation API. You must use this getLocation API for location, as HTML5 geolocation API is currently not fully supported on Teams desktop client.*, so it seems supported.

[I've seen that](https://github.com/OfficeDev/microsoft-teams-library-js/blob/a165617d54c72f464cedf1d308364689a5dacafa/src/public/location.ts#L53) `getLocation()` calls `isApiSupportedByPlatform` with a `locationAPIsRequiredVersion` value that is compared with `GlobalVars.clientSupportedSDKVersion`, but all the posible values for `clientSupportedSDKVersion` are coming from [here in the constants file](https://github.com/OfficeDev/microsoft-teams-library-js/blob/684f44db37d32c596f3c8d396a4a00979f8ed1f1/src/internal/constants.ts), where they are hardcoded with values lesser than `locationAPIsRequiredVersion`

![image](https://user-images.githubusercontent.com/62290512/119836935-86e06b80-bed8-11eb-823e-e8cd672dab6a.png)
![image](https://user-images.githubusercontent.com/62290512/119837047-9c559580-bed8-11eb-9841-3d8debc6f433.png)
![image](https://user-images.githubusercontent.com/62290512/119843567-0de41280-bede-11eb-8155-98fbfed482e3.png)

**Comment by Sridevi-MSFT** [comment]
@ffarguelles - Thanks for bringing up this issue, I will repro at my end and will let you know.

**Comment by Sridevi-MSFT** [comment]
@ffarguelles - Thanks for bringing up this issue, I will repro at my end and will let you know.

**Comment by Sridevi-MSFT** [comment]
@ffarguelles - The getLocation API is in works on desktop/web clients and is not released yet.
