### ISSUE TITLE
Teams SSO getAuthToken Issue

### ISSUE THREAD

**Issue by ra700** [OfficeDev/microsoft-teams-library-js#586]
Hello, 

We are developing teams tab application with SSO and we use the following flow.
1. Call microsoftTeams.authentication.getAuthToken to get token.
2. This token is exchanged with access token using on-behalf-of flow.
3. If the exchange fails due to consent required we call microsoftTeams.authentication.authenticate with relevant parameters and after consent approval we get the access token.
4. we use the access token to get information we need.

Usually this works OK.

However when authentication process is done for the first time, for admin user for example,
teams popup the consent directly when we call the getAuthToken. 
After the consent approval we get token which we try to exchange for access token. But we receive a response of consent required, which cause us to request a consent for a second time.

How can we avoid this second consent?
Is it possible that in some cases getAuthToken will return an access token?

Thanks,
Ronny

**Comment by Nikitha-MSFT** [comment]
We are looking into the issue we will get back to you soon

**Comment by Nikitha-MSFT** [comment]
The getAuthToken() is only valid for consenting to a limited set of user-level APIs that is email, profile, offline_access and OpenId. It is not used for further Graph scopes such as User.Read or Mail.Read. For suggested workarounds, see [additional Graph scopes](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso#apps-that-require-additional-graph-scopes). Try if that helps
