### ISSUE TITLE
subEntityId value is empty

### ISSUE THREAD

**Issue by amansani15** [OfficeDev/microsoft-teams-library-js#588]
I have two **static tabs** (tab1 and tab2) in my app. I am launching the tab2 from tab1 using deeplinkurl which is perfectly working fine. **Below is the deeplinkurl**

msTeams.executeDeepLink("https://teams.microsoft.com/1/entity/appidvalue/entityid?webUrl=https://localhost:3000/index.html#/tab2)

Now, I have a situation where I want to load a file based on the value I am sending from the tab1 to tab2 using deeplinkurl. For example, I have three buttons a, b and c in tab 1 and when I click on these buttons, each button should load a different file in my tab2. So, I am using subentityid to pass some parameter value from tab1 and read that value from tab2 and load the file accordingly. **Below is the deeplink url with subentityid:**

**Code In tab1:**
msTeams.executeDeepLink("https://teams.microsoft.com/1/entity/appidvalue/entityid?webUrl=https://localhost:3000/index.html#/tab2&context='{"subEntityId":"testing"}'")

**Code In tab2:**
msTeams.initialize();
msTeams.getContext(context => { test(context.subEntityId)});
function test(value: string | undefined){
    console.log("Value is: " + value)
}

Note: I am able to see the output for context.entityid and context.theme. So, the getContext method is working, it's just the subEntityId value is empty. The language I am using is typescript (.tsx)

Please guide me how I can get the subEntityId value in tab2 or is there any way to **go to tab2** and **load the file** based on tab1 button clicks. Looking forward for some inputs.

Thanks in Advance

**Comment by Mamatha-MSFT** [comment]
Hi @amansani15 -  All query parameters should be properly URI encoded. You must follow the preceeding example
```
var encodedWebUrl = encodeURI('https://tasklist.example.com/123/456&label=Task 456');
var encodedContext = encodeURI('{"subEntityId": "task456"}');
var taskItemUrl = 'https://teams.microsoft.com/l/entity/fe4a8eba-2a31-4737-8e33-e5fae6fee194/tasklist123?webUrl=' + encodedWebUrl + '&context=' + encodedContext;
```

Please check this [doc ](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links) form more info.

**Comment by amansani15** [comment]
Hello @Mamatha-MSFT, I have already gone through the document before and I had tried encoding too, but the value was still empty even after encoding that is why I didn't put that info before. **Here is the one which I have tried before:**

var encodedWebUrl = encodeURI('https://localhost:3000/index.html#/tab2');
var encodedContext = encodeURI('{"subEntityId": "testParameter"}');
var taskItemUrl = 'https://teams.microsoft.com/l/entity/appid/entityid?webUrl=' + encodedWebUrl + '&context=' + encodedContext;
console.log("DeepLinkURL:" + taskItemUrl)
msTeams.executeDeepLink(taskItemUrl)

**------------in the log-----------------**
DeepLinkURL:https://teams.microsoft.com/l/entity/appid/entityid?webUrl=https://localhost:3000/index.html#/tab2&context=%7B%22subEntityId%22:%20%22testParameter%22%7D

**Comment by Mamatha-MSFT** [comment]
Hi @amansani15 - I am unable to repro the issue. I am able to get the value of `subEntityId`. FYI the `subEntityId `will be avaialable only when you deeplink from tab1 to tab2 and `subEntityId `will be empty when you directly open a tab2.

**Comment by amansani15** [comment]
Hello @Mamatha-MSFT. I am sharing the script files, console logs and screenshots for better understanding and might help to reproduce the issue at your end.

**---------console logs----------**
![consoleLog](https://user-images.githubusercontent.com/62998123/121903239-18801380-ccf6-11eb-9596-4bd4e0dec894.PNG)


**------Tab1 and Tab2--------**
![tab1](https://user-images.githubusercontent.com/62998123/121903281-25046c00-ccf6-11eb-8d96-5293b498eaf6.PNG)


![tab2](https://user-images.githubusercontent.com/62998123/121903296-2897f300-ccf6-11eb-8575-2aad4fd2ef60.PNG)

-------------------------------------------------------------------
**home.tsx --- typescript file**
`import * as msTeams from '@microsoft/teams-js';

function Index() {

    msTeams.initialize(); 
   
    function TabDeepLinks(){ 
      var encodedWebUrl = encodeURI('https://localhost:3000/index.html#/viewerPath');
      var encodedContext = encodeURI('{"subEntityId": "testParameter"}');
      var taskItemUrl = 'https://teams.microsoft.com/l/entity/appID/viewer?webUrl=' + encodedWebUrl + '&context=' + encodedContext;
      console.log("DeepLinkURL:" + taskItemUrl)
      msTeams.executeDeepLink(taskItemUrl)
    }

    return (              
      <button onClick={TabDeepLinks}>Launch Tab2</button>
    )
}

              
export default Index;`
---------------------------------------------------------------------------------------
**viewer.tsx ---typescript file**
`import * as msTeams from '@microsoft/teams-js';


function TestViewerTab() {
    msTeams.initialize()
    var testValues : string | undefined
    msTeams.getContext(context => {
        getContextValues(context.theme)
        getContextValues(context.subEntityId)
        getContextValues(context.entityId)
        console.log("Theme Value is: " + context.theme)
        console.log("SubEntityID Value is: " + context.subEntityId)    
        console.log("EntityID Value is: " + context.entityId)
    })

    function getContextValues(value: string | undefined){
        console.log("Value is: " + value)
        testValues = value
        return(
            <div>
                <h1>Value is {testValues}</h1>
            </div>
        )            
    }

    return(        
        <div>
            <h1>test Value is {testValues}</h1>
            <h2>Not able to print the context values too</h2>
        </div>
    )
}

export default TestViewerTab`

--------------------------------------------------------------------
**index.tsx**
`export { default as home } from './home';
export { default as viewer } from './Viewer';
`

Hope this helps to reproduce the issue. Also, I appreciate if you can share the working code at your end, would love to see and try it. TIA

**Comment by Mamatha-MSFT** [comment]
Hi @amansani15  - I have tried with the code which you have provided above. You are not getting `subEntityId `because of incorrect `webUrl`. I think it's the issue with "**#**" symbol in your `webUrl`.  Remove the "**#**" in your `webUrl `and you will get a subEntityId. 
var encodedWebUrl = encodeURI('https://localhost:3000/index.html');

**Comment by amansani15** [comment]
Hello @Mamatha-MSFT 

Thank you. Now I am able to see the subEntityID value after removing '#' from the url. 

I have assigned the context property values to a variable and the value is undefined when I am trying to access that variable value outside of the getContext method. May I know how to assign the context values  to some variable and access it outside of the getContext. I am unable to print/display any of the context values outside of the getContext. TIA

**Comment by Mamatha-MSFT** [comment]
@amansani15 - Please check below code to replace your **viewer.tsx** file

```
import React from 'react';
 import * as microsoftTeams from "@microsoft/teams-js";
 
class Tab extends React.Component<any, any> {
  constructor(props: any){
    super(props)
    this.state = {
      context: {},
    }
  }
  //React lifecycle method that gets called once a component has finished mounting
  //Learn more: https://reactjs.org/docs/react-component.html#componentdidmount
  componentDidMount(){
    // Get the user context from Teams and set it in the state
    microsoftTeams.getContext((context: microsoftTeams.Context) => {
      this.setState({
        context: context,
      });
      alert(JSON.stringify(context));
      
    });
    // Next steps: Error handling using the error object
  }

  render() {
      var contextvalue = this.state.context.subEntityId;
      console.log("test:  " + contextvalue)
      return (
      <div>
        <h3>subEntityId: {contextvalue}</h3>       
      </div>
      );
  }
}
export default Tab;
```

**Comment by amansani15** [comment]
Awesome, working like a charm. Just one thing, we need to initialize microsoftTeams library - msTeams.initialize().

Thank you so much for all the help.
