### ISSUE TITLE
getContext was hang in compose extension settings page (Teams Client Beta)

### ISSUE THREAD

**Issue by NewFuture** [OfficeDev/microsoft-teams-library-js#590]
SDK version 1.8 to 1.10

In the Teams desktop clients under Beta Version (R0 to R3), the `getContext` hang when open the `settings` page of  `compose extension`.
 
maybe related to #580

**Comment by Nikitha-MSFT** [comment]
We are checking internally get back to you.

**Comment by Nikitha-MSFT** [comment]
Tracking the issue : https://github.com/OfficeDev/microsoft-teams-library-js/issues/580. Closing the issue here.
