### ISSUE TITLE
Teams getLocation API doesn't work with sdk version 1.9.0 and 1.10.0

### ISSUE THREAD

**Issue by ishanisuchak** [OfficeDev/microsoft-teams-library-js#593]
**SDK Version**: 1.9.0 and 1.10.0

**Issue**:

According to MS documentation [here](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?tabs=desktop#use-teams-apis-to-get-device-permissions), HTML5 geolocation API is not fully supported in teams and we should be using the Teams getLocation API instead:
 
![image](https://user-images.githubusercontent.com/25173209/123077834-09a50980-d438-11eb-9676-c7d14ac2d7bf.png)

The getLocation API expects the SDK version to be minimum 1.9.0 but it doesn't work with both 1.9.0 and 1.10.0 versions. On debugging, found this variable to be undefined (for v1.9.0 and v1.10.0) which should be having the installed SDK version instead:

![image](https://user-images.githubusercontent.com/25173209/123078327-7b7d5300-d438-11eb-8756-34a1a95c0a8b.png)

So, get 9000 error code for the getLocation API:

![image](https://user-images.githubusercontent.com/25173209/123078480-a36cb680-d438-11eb-98ec-2c9ea5c971ae.png)

**Repro steps**:

Create a personal app in teams. In the tabWebpart.ts file, add:

```javascript
import * as microsoftTeams from '@microsoft/teams-js';
microsoftTeams.initialize();
let locationProps = { "allowChooseLocation": false, "showMap": false };
microsoftTeams.location.getLocation(locationProps, (err: microsoftTeams.SdkError, position: microsoftTeams.location.Location) => {
            if (err) {
              console.log("Error: " + err.errorCode + err.message);
              return;
            }
              console.log("Found location: " + JSON.stringify(position));
          });
```

**Comment by Sridevi-MSFT** [comment]
Hi @ishanisuchak -  The getLocation API is in works on desktop/web clients and is not released yet.

**Comment by ishanisuchak** [comment]
It is mentioned though that the getLocation API should be used in place of the HTML 5 geolocation API: https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/native-device-permissions?tabs=desktop#use-teams-apis-to-get-device-permissions

Anyway to use the HTML geolocation API in teams?

Right now it throws this error if used in Teams: **Network location provider at 'https://www.googleapis.com/' : No response received.**

Code: navigator.geolocation.getCurrentPosition (successCallback, errorCallback);

This code works in all browsers but gives this error on both Teams web and desktop client.

**Comment by Wajeed-msft** [comment]
> Anyway to use the HTML geolocation API in teams?

@ishanisuchak - currently there is no workaround to use getLocation API in Teams desktop client.

**Comment by Wajeed-msft** [comment]
Closing this feature ask as the location capability is available for the Teams web client, desktop, and mobile. 
Doc ref: [Integrate location capabilities](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/device-capabilities/location-capability?tabs=desktop%2Cteamsjs-v2).
