### ISSUE TITLE
support for back/forward in custom team app

### ISSUE THREAD

**Issue by mdissel** [OfficeDev/microsoft-teams-library-js#599]
In our single page app (that is loaded as a team app (full screen) or team tab) you can navigate to different parts. 
When we use executeDeeplink(..) to open a document and close the document, our team app is reloaded with the initial page. 

Is it possible to "register" the navigation in our app so that the back or close function doesn't reload the initial page.

**Comment by Prithvi-MSFT** [comment]
Hi, execute deep link will navigate you to a different link or trigger a client action so at teams scope whenever you close the document it will always redirect to initial URL. So if you want to maintain navigation you will need to add custom logic at code level.

**Comment by mdissel** [comment]
Thanks!
Is is possible to add entries to the back/forward history in Teams? so that if you navigatie in your app the user can use the back/forward buttons in Teams?

![image](https://user-images.githubusercontent.com/126084/128485493-7fcf0bc9-3e15-41d7-88eb-655857724ed2.png)

**Comment by Prithvi-MSFT** [comment]
Hi, this navigation is part of teams product and we cannot add custom entries for navigation.

Thanks

**Comment by mdissel** [comment]
ok, please add this as a feature request.

**Comment by Prithvi-MSFT** [comment]
Hi, You can raise feature request on https://microsoftteams.uservoice.com/

Tnanks

**Comment by MarcinJuraszek** [comment]
@mdissel This is partially possible already using [`registerBackButtonHandler`](https://github.com/OfficeDev/microsoft-teams-library-js/blob/e6d607978af2ef87a63754c020abaea409179880/src/public/publicAPIs.ts#L228) and [`navigateBack`](https://github.com/OfficeDev/microsoft-teams-library-js/blob/master/src/public/navigation.ts#L68).

The comment on `registerBackButtonHandler` explains a bit more on how to use it:

```
 * Registers a handler for user presses of the Team client's back button. Experiences that maintain an internal
 * navigation stack should use this handler to navigate the user back within their frame. If an app finds
 * that after running its back button handler it cannot handle the event it should call the navigateBack
 * method to ask the Teams client to handle it instead.
```

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
