### ISSUE TITLE
handle,  when user closes task module.

### ISSUE THREAD

**Issue by mykyta-Koptsov** [OfficeDev/microsoft-teams-library-js#604]
i founded method that handles this action. When user closes task module , clicl on X. This is callback `submitHandler` in method `microsoftTeams.tasks.startTask()`. But when i tried to implement this it's not works for me. 
```
  componentDidMount() {
    microsoftTeams.initialize();
    const submitHandler = (err: string, result: any): void => { 
      console.log(`Err: ${err}; Result:  + ${result}`); 
      microsoftTeams.tasks.submitTask();
    };
    microsoftTeams.tasks.startTask({
      title: "Custom Form",
      height: 510,
      width: 430,
    }, submitHandler );
}

```
Any suggestions or opinions on what I did wrong?

![Screenshot 2021-07-03 at 15 18 07](https://user-images.githubusercontent.com/57220090/127985808-399d3e44-4a1f-44cf-a2c5-2edd50c2769b.png)

**Comment by mykyta-Koptsov** [comment]
Hey guys, Can you help me with my question?

**Comment by Wajeed-msft** [comment]
Hi @mykyta-Koptsov - I am looking into this.

**Comment by Wajeed-msft** [comment]
@mykyta-Koptsov - could you please try [Demo Task Module app manifest](https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/app-task-module/csharp/Microsoft.Teams.Samples.TaskModule.Web/Manifest/TaskModuleCSharp.zip) and let me know if event is getting triggered for you?
![image](https://user-images.githubusercontent.com/31851992/125206269-0e751480-e2a4-11eb-812a-32fcf0533153.png)

**Comment by mykyta-Koptsov** [comment]
hey @Wajeed-msft , I tried to use your manifest. Your manifest works expected. And I sow this example code before and try to implement by this example.
I use `"botbuilder": "4.13.4" `, 
 And i attached my manifest 
 `{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.8/MicrosoftTeams.schema.json",
  "manifestVersion": "1.8",
  "version": "255.255.255",
  "id": "fa96d6c3-c376-4cc1-99ce-0ef7efe418a10",
  "packageName": "com.msteams-atlassian.trello-dev",
  "developer": {
    "name": "Atlassian",
    "websiteUrl": "https://atlassian.com/",
    "privacyUrl": "https://www.atlassian.com/legal/privacy-policy",
    "termsOfUseUrl": "https://www.atlassian.com/legal/cloud-terms-of-service"
  },
  "name": {
    "short": "Trello Dev",
    "full": "Trello Dev"
  },
  "description": {
    "short": "Trello lets you work more collaboratively and get more done.",
    "full": "Trello for Microsoft Teams"
  },
  "icons": {
    "outline": "outline.png",
    "color": "color.png"
  },
  "accentColor": "#a60747",
  "configurableTabs": [
    {
      "configurationUrl": "https://trello.com/integrations/teams/tab-config?iframeSource=msteams&theme={theme}",
      "canUpdateConfiguration": false,
      "scopes": [
        "team",
        "groupchat"
      ]
    }
  ],
  "staticTabs": [
    {
      "entityId": "AllMyCards",
      "name": "Cards Assigned to me",
      "contentUrl": "https://mkoptsov-msteams-trello.public.atlastunnel.com/silent?tabpage=mycards",
      "websiteUrl": "https://trello.com",
      "scopes": [
        "personal"
      ]
    },
    {
      "entityId": "CalenderCards",
      "name": "Cards Calendar",
      "contentUrl": "https://mkoptsov-msteams-trello.public.atlastunnel.com/silent?tabpage=mycardscalender",
      "websiteUrl": "https://trello.com",
      "scopes": [
        "personal"
      ]
    },
    {
      "entityId": "RecentBoards",
      "name": "Recent Boards",
      "contentUrl": "https://mkoptsov-msteams-trello.public.atlastunnel.com/silent?tabpage=recentboards",
      "websiteUrl": "https://trello.com",
      "scopes": [
        "personal"
      ]
    },
    {
      "entityId": "Boards",
      "name": "All Boards",
      "contentUrl": "https://mkoptsov-msteams-trello.public.atlastunnel.com/silent?tabpage=myboards",
      "websiteUrl": "https://trello.com",
      "scopes": [
        "personal"
      ]
    },
    {
      "entityId": "Help",
      "name": "Help",
      "contentUrl": "https://mkoptsov-msteams-trello.public.atlastunnel.com/help",
      "websiteUrl": "https://mkoptsov-msteams-trello.public.atlastunnel.com/help",
      "scopes": [
        "personal"
      ]
    }
  ],
  "bots": [
    {
      "botId": "055ecfc7-7c93-4699-b89d-923357b0e943",
      "needsChannelSelector": false,
      "isNotificationOnly": false,
      "supportsFiles": false,
      "scopes": [
        "personal"
      ],
      "commandLists": [
        {
          "scopes": [
            "personal"
          ],
          "commands": [
            {
              "title": "add ",
              "description": "Add a new card"
            },
            {
              "title": "set-due ",
              "description": "Change the due date of the active card"
            },
            {
              "title": "comment ",
              "description": "Add a comment to the active card"
            },
            {
              "title": "set-label ",
              "description": "Add or remove labels on the active card"
            },
            {
              "title": "move ",
              "description": "Move the active card to a different list"
            },
            {
              "title": "search ",
              "description": "Search for cards across all your boards"
            },
            {
              "title": "feedback",
              "description": "Leave a feedback about the Trello for Microsoft Teams"
            },
            {
              "title": "help",
              "description": "Get help using Trello for Microsoft Teams"
            },
            {
              "title": "tasks",
              "description": "Test the task module with an Adaptive & Thumbnail card"
            }
          ]
        },
        {
          "scopes": [
            "personal"
          ],
          "commands": [
            {
              "title": "setup",
              "description": "Link Trello account"
            },
            {
              "title": "reset",
              "description": "Reset Trello account"
            },
            {
              "title": "assign to me",
              "description": "Assign active Trello card"
            },
            {
              "title": "link",
              "description": "Link new Trello board"
            },
            {
              "title": "set-list",
              "description": "Set active Trello board list"
            },
            {
              "title": "show-list",
              "description": "Show active Trello board list"
            },
            {
              "title": "unlink",
              "description": "Unlink active Trello board"
            },
            {
              "title": "info",
              "description": "Shows info about active Trello board"
            },
            {
              "title": "board",
              "description": "Shows info about active Trello board"
            }
          ]
        }
      ]
    }
  ],
  "connectors": [
    {
      "connectorId": "b9cf8971-7d55-4b73-9ffa-a584611b600b",
      "scopes": [
        "team"
      ]
    }
  ],
  "composeExtensions": [
    {
      "botId": "055ecfc7-7c93-4699-b89d-923357b0e9410",
      "canUpdateConfiguration": false,
      "commands": [
        {
          "id": "search",
          "title": "Search",
          "description": "Find a card",
          "initialRun": true,
          "parameters": [
            {
              "name": "query",
              "title": "Query",
              "description": "Search string"
            }
          ]
        },
        {
          "id": "createCard",
          "title": "Create card",
          "description": "Create card",
          "type": "action",
          
          "fetchTask": true,
          "context": [
            "compose",
            "commandBox",
            "message"
          ]
        }
      ]
    }
  ],
  "permissions": [
    "identity",
    "messageTeamMembers"
  ],
  "webApplicationInfo": {
    "id": "055ecfc7-7c93-4699-b89d-923357b0e9410",
    "resource": "api://mkoptsov-msteams-trello.public.atlastunnel.com/055ecfc7-7c93-4699-b89d-923357b0e943"
  },
  "validDomains": [
    "trello.com",
    "*.trello.com",
    "trellochatbot.com",
    "*.msteams-atlassian.com",
    "*.ngrok.io"
  ]
}
`

**Comment by v-chetsh** [comment]
Hello @mykyta-Koptsov,
Looks like you are trying to invoke Task Module from Messaging Extension.
This event will be handled by Bot TeamsActivityHandler class method name: OnTeamsTaskModuleSubmitAsync().
https://docs.microsoft.com/en-us/microsoftteams/platform/bots/bot-basics?tabs=csharp#teams-invoke-activities

Invoking the method microsoftTeams.tasks.startTask() works if we are opening a Task Module from Client Component (Tab etc.)

Thanks!!
