### ISSUE TITLE
Messaging between bots of the same tenant

### ISSUE THREAD

**Issue by stefan2410** [OfficeDev/microsoft-teams-library-js#608]
As an idea probably
A calling bot registered to the tenant  join the calls.  If there is another bot - tabbed application in users, would be possible the first bot to send json messages to the user (via graph, it knows the user ID and/or UPN),   including in the message the AppId of the front-end bot, which could listen in events using the microsoft-teams-library-js,  to get the message?

**Comment by v-chetsh** [comment]
We are checking on it's possibility & get back to you.

**Comment by v-chetsh** [comment]
@stefan2410 -  Are you able to resolve this issue or still looking for any help?
If it is resolved, could you please close it.

**Comment by stefan2410** [comment]
@v-chetsh  I did not get any answer.  
You had written at Aug 5
` We are checking on it's possibility & get back to you.`

**Comment by Wajeed-msft** [comment]
@stefan2410 - Currently you can not use `microsoft-teams-library-js`  to fetch messages. 

If you are interested in getting notification for messages posted in a chat then it you can [subscribe](https://docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&tabs=http) to `/chats/{id}/messages`. 

For communicating between two bots you can expose APIs. See example where you can trigger message from bot based on external get request: [proactive-messages](https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/csharp_dotnetcore/16.proactive-messages/Controllers/NotifyController.cs#L33).

Please let me know if you need more details.

**Comment by v-chetsh** [comment]
@stefan2410 - We are closing this issue for now, Please feel free to reopen it, if required.
