### ISSUE TITLE
Download file in teams mobile app doesn`t work.

### ISSUE THREAD

**Issue by sergesama** [OfficeDev/microsoft-teams-library-js#611]
I am working on downloading pdf / docx files while developing TeamsApp . I have a problem when I am initiating download by click on the invisible link with attribute download(filename) and url.
Code example:

```
export const downloadScan = (doc_num) => (dispatch) => {
  dispatch(FileLoading())

  const email = 'email ' + localStorage.getItem('email');

  return fetch(baseUrl + 'statements/'+doc_num+'/download_handled_pdf/', {
      method: "GET",
      headers: {
        'Authorization': email
      },
      credentials: "same-origin"
  })
  .then(response => {
      if (response.ok) {
        return response;
      } else {
        dispatch(FileFailed())
        var error = new Error('Error ' + response.status + ': ' + response.statusText);
        error.response = response;
        throw error;
      }
    },
    error => {
          throw error;
    })
  .then(response => response.blob())
  .then(blob => { 
      var isbFilename ="statement"+doc_num+".docx";
      var objectUrl = URL.createObjectURL(blob);
      var a = document.createElement("a");
      document.body.appendChild(a);
      a.style = "display: none";
      a.href = objectUrl;
      a.download = isbFilename;
      a.click()
      window.URL.revokeObjectURL(objectUrl);
      dispatch(FileLoaded())

   })
  .catch(error => console.log(error));
```
  
  
  
In web browsers its working normal. In Teams desktop version file is saved in standart download folder without Teams notification.
But on iOS(v14.4.6) and Android(10 QKQ1.191215.002) my code doesn`t work at all.
On Android I recieve error notification "This action is not supported on mobile device". 
On iOS Teams open preview of file without a possibility to save it.
My question is if it even possible to do on mobile version of Teams? Maybe there is a library or something?

**Comment by v-chetsh** [comment]
Hello @sergesama,
We are looking into it.
We will let you know soon.

**Comment by v-chetsh** [comment]
Hello 
Looks like download functionality is not supported On Android device as of now.
We have verified with ReactJS code also but it's not supported for now.

Thanks!!

**Comment by sergesama** [comment]
@v-chetsh Its not supported on iOS device too?

**Comment by v-chetsh** [comment]
@sergesama, We have tested it in Android device & it's not supported.
We haven't verified for iOS device but we have a less functionality support on mobiles in comparison to Desktop/Web Teams client.
So it may not work on iOS device too.

**Comment by sergesama** [comment]
@v-chetsh, Hello, is file downloading supported on Android and iOS now? If not, when will it be supported?

**Comment by v-chetsh** [comment]
@sergesama - Could you please raise a user voice:  https://microsoftteams.uservoice.com/forums/555103-public/filters/new

**Comment by sergesama** [comment]
@v-chetsh  I can't follow the link you provided.(

**Comment by v-chetsh** [comment]
@sergesama - Have you tested it recently in iOS ?
If yes, could you please share the error logs if any?
Meanwhile we will also check it from our end and let you know.

**Comment by sergesama** [comment]
I am unable to test at the moment my app because download files in my app temporary depricated. For this reason, I also cannot send off the logs with this bugs. But this feature is very important such as download file in IOS/ANDROID. Have you got the information about fixed this bugs?

**Comment by Nivedipa-MSFT** [comment]
@sergesama - We are able to repro this issue and we have raised a bug for it. We will let you know once we get updates on it.

**Comment by Nivedipa-MSFT** [comment]
@sergesama -You have any compatible app installed in your device that opens Resume. The way it works today on Android is whenever a document link is clicked on the Teams Android App, it would redirect to any external app that supports viewing the  document..
 
This dialog shows up only when no third party app is present in the device that can open the file.. 
If you installs any Document reader app then the Teams app will redirect to that app and you can view the document.
