### ISSUE TITLE
I want to implement all team functionalities in my website and mobile app

### ISSUE THREAD

**Issue by adaptgurus** [OfficeDev/microsoft-teams-library-js#615]
Hi,

We want to implement Microsoft Teams in our Website and mobile app functionalities:
Start Meeting
End Meeting
Video Recoding
Screen Sharing 
Whiteboard

integration in our website we are using Nodejs and for frontend we are using bootstrap 

but this current code is not working and I am not able to find any tutorials 

Please help me

**Comment by Prithvi-MSFT** [comment]
Hi, you can create meeting using graph api
https://docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-1.0&tabs=http
Also you can include whiteboard in your meetings
https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/design/designing-apps-in-meetings?tabs=desktop#use-cases-2

However even when you create a meeting using graph api, to join the meeting you will be redirected to teams only.

Thanks
