### ISSUE TITLE
The "initialize" method is asynchronous, but not properly returning a promise

### ISSUE THREAD

**Issue by peterkappelt** [OfficeDev/microsoft-teams-library-js#616]
Hey folks, hope y'all are doing well.

This issue is basically a re-open of https://github.com/OfficeDev/microsoft-teams-library-js/issues/172

The initialize method of the teams sdk is asynchronous, but it takes a callback rather than properly returning a promise (which I consider a best-practice). In #172, a fix was announced in Release 1.5 - but nothing has happened yet since.

Could you take another look at it? 

https://github.com/OfficeDev/microsoft-teams-library-js/blob/619520aec9b64e00c93aace134fb7f62a76bc6c4/src/public/publicAPIs.ts#L26-L39

**Comment by v-chetsh** [comment]
We are looking into it and get back to you soon.

**Comment by MarcinJuraszek** [comment]
This is now available in the Public Preview of the new version of Teams JavaScript SDK, which we just announced as part of Ignite: [Ignite 2021: Building apps for collaboration in a hybrid world - Teams SDK updates in public preview](https://devblogs.microsoft.com/microsoft365dev/ignite-2021-building-apps-for-collaboration-in-a-hybrid-world/#teams-sdk-updates-in-public-preview).

See [2.0-preview](https://github.com/OfficeDev/microsoft-teams-library-js/tree/2.0-preview) branch for more information on how to use the new version, and [app.ts](https://github.com/OfficeDev/microsoft-teams-library-js/blob/2.0-preview/packages/teams-js/src/public/app.ts#L434 ) for the new `initialize` signature.

**Comment by ChetanSharma-msft** [comment]
@peterkappelt - Hope you are doing well !!
Please let us know if you need any input or shall we close this issue?
