### ISSUE TITLE
App within Microsoft Teams App Desktop unable to go fullscreen

### ISSUE THREAD

**Issue by AlexisGlez** [OfficeDev/microsoft-teams-library-js#618]
Hello :)

I am creating an app for Microsoft Teams and one of the features that it has is the ability for it to go into full screen mode. The way I implemented this was with the web API and it works great in teams Web, but it seems that the Microsoft Teams Desktop App is blocking/removing the fullscreen API from the DOM, which is not allowing the app to go into full screen mode.

My question is, is it possible to use this library to make my app go into full screen mode? I was taking a look into the documentation and I found that `sendMessageRequestToParent('enterFullScreen', [])` was the way to do it, but it seems that the `sendMessageRequestToParent` function is not being exported from the library (when I called that function an exception was thrown saying that the function did not exist)?

https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/microsoftteams?view=msteams-client-js-latest#sendMessageRequestToParent_string__any___

Any help regarding this topic will be much appreciated, thank you!

**Comment by Prithvi-MSFT** [comment]
Hi, I did not find any method to switch the tab in full screen using. Let me confirm with internal team and get back to you.

**Comment by Prithvi-MSFT** [comment]
Hi @AlexisGlez ,
The enterFullScreen API is just a programmatic way to expand the tab within the Teams Client
Currently this API is not available to 3P developers and that is why it's not covered anywhere in our public documentation.
 
Can you try code from below link to display full screen content
https://www.w3schools.com/howto/howto_js_fullscreen.asp

**Comment by ChetanSharma-msft** [comment]
@AlexisGlez - Hope you are doing well !!
Please let us know if you need any help here or shall we close this issue?

**Comment by AlexisGlez** [comment]
Hello! I was able to do a workaround (a little bit hacky) by inspecting the window object and looking at the properties that Teams exposes. I found the function to request full screen and just called it directly.

Would be nice if in the future the teams sdk could offer an API to do this more easily 😋

For now the ticket can be closed if you want, but I don't require any more assistance.

Thanks!

**Comment by ChetanSharma-msft** [comment]
Thanks for sharing the information.

We are closing this issue for now, Please feel free to reopen it, if required.
