### ISSUE TITLE
Teams media SDK for microphone

### ISSUE THREAD

**Issue by Joyeconnect** [OfficeDev/microsoft-teams-library-js#625]
1) We need to set the max recording time in seconds.... the current SDK has a function 'maxDuration' which only takes whole integers in minutes. With this we can set it for a minimum of 1min, we need this to be allowed in seconds
2) control the 'stop' action from our code and our own UI functionality, and to hide the Team's recording display bar.
3) the audio recording output is not clear. How can we choose the output to be in mp3? Currently the recommended SDk produces output which is video/mp4. This is not the desired type for audio microphone recording. How can we get the output in mp3.

<<< REQUEST URGENT HELP PLEASE>>>

**Comment by HunaidHanfee-MSFT** [comment]
Hello @Joyeconnect,
Currently the max durations takes value only in minutes, therefore minimum value will be 1 minute. So, we will raise it from our side but currently that's the default behavior. 
All the above things like format are by default and we need to use custom logic to convert to other formats.
However you can use the output of media to bind to a custom control with features like play/pause as per your requirement.


You can raise user voice :
[https://microsoftteams.uservoice.com/](https://microsoftteams.uservoice.com/)

**Comment by Joyeconnect** [comment]
Hello Hunaid,
Can you confirm what is the default format of the microphone recording?

**Comment by Joyeconnect** [comment]
Hello @HunaidHanfee-MSFT
Can you confirm what is the default format of the microphone recording?

**Comment by HunaidHanfee-MSFT** [comment]
We have a [sample](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-device-permissions/nodejs) ready. Yes, I have checked `attachments[0].mimeType` inside the  [method](https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/f4ffab03943093d971c7ea1ae6c4ac2129e78ffe/samples/tab-device-permissions/nodejs/src/components/CaptureAudio.tsx#L21-L39) and its coming as video/mp4. You need to write custom code to convert it.

Let us know if you have any query, else please close the issue.

**Comment by Joyeconnect** [comment]
Hello Hunaid, Thanks for sharing this. Some questions and help needed:

a) while we see the code to 'start' the 'mediaCapture', we also need the code to 'stop' the recording

b) while we see the code to customise the UI for 'mediaCapture' controls, we also need guidance to hide the standard-bar showing with recording status and the 'stop' button.

**Comment by Joyeconnect** [comment]
We tried the code and not getting the ‘preview’. Please guide us

audioResult {
content: "4e258589-19a6-4f8c-a8e0-4d4fcbfcebc5"
format: "id"
mimeType: "video/mp4" 
name: undefined
preview: ""
size: "10"
[[Prototype]]: t
}


"I am not getting a Preview in audioResult."

**Comment by HunaidHanfee-MSFT** [comment]
Hello,
We are checking these with internal team. We will let you the answer.
Thanks

**Comment by Joyeconnect** [comment]
Thanks! Awaiting!

**Comment by HunaidHanfee-MSFT** [comment]
Got answer for your query:
1. There is no way currently for the app to stop audio recording, other than the Stop button on the standard bar provided by Teams. Till then partner has to continue using the Stop button provided by Teams. Discussion is on going to STOP recording using API but its in very early stage, we can't share ETA.

2. Because the standard bar today has the controls for stopping a recording, we don’t currently allow apps to hide this bar

**Comment by HunaidHanfee-MSFT** [comment]
I am closing this issue here. Reopen if you have any query.
Thanks
