### ISSUE TITLE
Pop out app automatically

### ISSUE THREAD

**Issue by stefan2410** [OfficeDev/microsoft-teams-library-js#627]
Is it possible,  a tabs application to open a pop up window, clicking in the navigation bar, instead the right click ?

**Comment by Prithvi-MSFT** [comment]
Hi, Currently this is not supported in teams however you can raise your voice here https://microsoftteams.uservoice.com/
The site temporarily down for now, will be running soon

**Comment by stefan2410** [comment]
@Wajeed-msft  @v-chetsh  @Prithvi-MSFT 
Is it possible using  Teams Client SDK functions to move the tabs application in an pop-out window?

**Comment by ChetanSharma-msft** [comment]
Hello @stefan2410 - Hope you are doing well !!
Currently it is not supported.
You can raise your feature request here: [Microsoft Teams Community](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472)
