### ISSUE TITLE
Alternate when microsoftTeams.authentication.notifySuccess("{{verificationCode}}"); does not work

### ISSUE THREAD

**Issue by sanjeev9160** [OfficeDev/microsoft-teams-library-js#630]
Code sample:

Some of our customer using our App are complaining about the signin window not closing and we have referred to this code for our implementation. Reference: https://github.com/integrations/microsoft-teams/issues/141

https://github.com/OfficeDev/microsoft-teams-sample-auth-node/blob/master/src/views/oauth-callback-success.hbs#L33-L41

```javascript
<body class="theme-light"> 
     <div id="instructionText" style="display: none"> 
         <div class="instruction-text"> 
             <p>You're almost there!</p> 
             <p>To finish linking your account with<br/> {{providerName}}, type</p> 
             <span class="verification-code">{{verificationCode}}</span> 
             <p>in the Microsoft Teams chat window.</p> 
         </div> 
     </div> 
```

`In this customer is being asked to manually enter the verification code in the chat window.`

**Questions:**

- Why it is happening for few people? Also, we are unable to repro this issue from our end.
- Is this message asking users to enter verification code in private chat window with the bot ?
- Any code pointer where this is getting used ?

**Comment by HunaidHanfee-MSFT** [comment]
Hello. We are looking into this. We will get back to you soon.

**Comment by HunaidHanfee-MSFT** [comment]
Is it happening only with GitHub?

**Comment by HunaidHanfee-MSFT** [comment]
@sanjeev9160 - Can you please check console for error and can you share Teams SDK version?

**Comment by sanjeev9160** [comment]
@HunaidHanfee-MSFT We are currently using the v1.10.0 for Teams SDK. Currently I am unable to repro the issue but few customers have reported the issue. Adding links for it. 
- https://github.com/integrations/microsoft-teams/issues/141#issue-940390452 
- https://github.com/integrations/microsoft-teams/issues/141#issuecomment-877296883

**Comment by HunaidHanfee-MSFT** [comment]
I have tried with 2FA account but didn't faced any issue it worked. I will check internally what could be wrong or what should be the next step to resolve this bug. I will let you know once it is confirmed.

**Comment by HunaidHanfee-MSFT** [comment]
We have a bug raised and team is looking into it. I will let you know once it is fixed or got any update on this.
Thanks
