### ISSUE TITLE
Maintain state of subentityid value

### ISSUE THREAD

**Issue by amansani15** [OfficeDev/microsoft-teams-library-js#631]
Hello all, 

https://github.com/OfficeDev/microsoft-teams-library-js/issues/588

To continue to the above closed issue, I am looking to maintain the last passed subEntityId value even after switching to a different tab or clicking anywhere else outside of the current tab2.

**Steps:**
1) I have two tabs Tab1 and Tab2
2) I am passing the subEntityId value from tab1 to tab2 via deeplinkurl.
3) Loaded the file in tab2 based on the subEntityId value
4) Now clicked anywhere outside of tab2
5) Now when we go back to tab2, how can we still show the file which is loaded in the second step?

Any help or inputs are highly appreciated. Thank you.

**Comment by Meghana-MSFT** [comment]
@amansani15 - The subEntityId will be avaialable only when you deeplink from tab1 to tab2 and subEntityId will be empty when you directly open a tab2.

**Comment by amansani15** [comment]
Is it not possible to maintain the last passed subEntityId in tab2?

**Comment by Meghana-MSFT** [comment]
Hi @amansani15 - You can maintain/store the subEntityId using state management or store it locally and then fetch it when the tab2 loads.

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
