### ISSUE TITLE
[Request] Can we manually trigger the pop-out in the Tab instead by using the icon button on the top right side?

### ISSUE THREAD

**Issue by kafka-yu** [OfficeDev/microsoft-teams-library-js#633]
Hi Team,

Can we manually trigger the pop-out in the Tab instead by using the icon button on the top right side?
Looks like currently, no functions in the SDK can do this.

I think this is a new requirement?

**Comment by HunaidHanfee-MSFT** [comment]
Let me check if we have some method to do that. I think its not possible but let me confirm.

**Comment by HunaidHanfee-MSFT** [comment]
Currently it is not possible to pop-out a Tab using SDK.

Microsoft will always focus on customer’s feedback and experience, some new features would be added to the services based on customers' feedback in the future, we recommend you give your new idea in Teams UserVoice [here](https://microsoftteams.uservoice.com/).
