### ISSUE TITLE
[Feature Request/Question] Provide API for identifying Presenter for Meeting Stage

### ISSUE THREAD

**Issue by abdulkareemnalband** [OfficeDev/microsoft-teams-library-js#641]
We are building a meeting stage extension, and we need to show different content based on whether the current user is a presenter or not.

It would be helpful if we had an API to indentify that.

It could be either
Test whether the current user is the presenter

or
Get the user who is presenting now

**Comment by Prithvi-MSFT** [comment]
Hi, We currently do not have any graph API that will give details of a ongoing meeting (like presenter info).

Thanks

**Comment by abdulkareemnalband** [comment]
@Prithvi-MSFT 
It need not to be an graph API
Will it be possible to provide that through Teams JS SDK itself , either in [Context](https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/microsoftteams.context?view=msteams-client-js-latest)  or a sperate function in [microsoftTeams](https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/microsoftteams?view=msteams-client-js-latest)  module

**Comment by abdulkareemnalband** [comment]
@Prithvi-MSFT  Is it on your roadmap to provide such API?

**Comment by Prithvi-MSFT** [comment]
Hi, you can raise your voice [here ](https://microsoftteams.uservoice.com/). Microsoft will always focus on customer’s feedback and experience, some new features would be added to the services based on customers' feedback in the future.

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.

**Comment by abdulkareemnalband** [comment]
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/44147142-provide-api-for-identifying-presenter-for-meeting
