### ISSUE TITLE
deeplink to create a meeting in a channel

### ISSUE THREAD

**Issue by mdissel** [OfficeDev/microsoft-teams-library-js#642]
What is the correct deeplink to create a new meeting in a specific channel?
![image](https://user-images.githubusercontent.com/126084/130613316-911bd48b-2ca1-4bef-ab1c-f8eeb21dbc1a.png)

This link is not working:

`https://teams.microsoft.com/l/pre-join-calling/{channelid}/conversations?groupId={groupid}&tenantId={tenantid}`

**Comment by v-chetsh** [comment]
@mdissel - Could you please share the documentation URL which you are referring so that I can try it from my end also.

**Comment by mdissel** [comment]
This link doesn't seem to be documented, but that doesn't say anything, documentation is always behind or not up-to-date.

I constructed this link based on other deeplinks and checking what happens when you press the Meet button.

**Comment by v-chetsh** [comment]
@mdissel - I also tried with above deep-link, it is not working for me as well.
Also I have gone through the deep-link documentation but did not find any such deep-link:

Reference URL:
https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links

This documentation was last updated on current Month (08-09-2021), so I think this contains latest contents.

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
