### ISSUE TITLE
microsoftTeams.navigateCrossDomain does not work in mobile teams app

### ISSUE THREAD

**Issue by vonguyen1982** [OfficeDev/microsoft-teams-library-js#650]
I managed to make it work in web and desktop application but it won't work in mobile app?

Also I got a message 
**"The navigateCrossDomain API has been deprecated and will not work in future versions of this SDK"**

what is other options to cross domain ? It is the main function of our app.

**Comment by vonguyen1982** [comment]
Also does not work in pop up windows in desktop.

**Comment by HunaidHanfee-MSFT** [comment]
We are looking into this. I will try the same and get back to you with findings. 
Thanks for understanding

**Comment by vonguyen1982** [comment]
Also I realized that with pop-out in desktop teams app. You need to hit twice to make it redirect or call twice the navigatecrossdomain. For (Android) mobile it definitely not work. I have not tried with iOS. Thanks

**Comment by Wajeed-msft** [comment]
@vonguyen1982 - did you try using `window.location.href="http://example.com"`?

**Comment by vonguyen1982** [comment]
I did but window.location.href never work with cross domain even I put valid domain in manifest.

**Comment by vonguyen1982** [comment]
I have a test with location.href
- On Windows MS Teams Desktop App or pop out windows or Web : you can redirect cross domain but I cannot read context after redirect.
- On (android) mobile app : window.location.href does not work at all

**Comment by HunaidHanfee-MSFT** [comment]
To update you - We have also experiencing the same issue with Android mobile. I am checking internally and I will get back to you as soon as I have something on the issue.
Thanks.

**Comment by HunaidHanfee-MSFT** [comment]
I got to know internally that the alternate is `window.location.href="http://example.com"` only and I have tested on my mobile device and its working. Please make sure that you have put the domain in manifest's `validDomains` section.

Have you intilialized the microsoftTeams on the other page - `microsoftTeams.initialize()` and 
```
microsoftTeams.getContext((context) => {
    if (context) {
        console.log(context);
    }
});
```
are you using this to get context on other page?

**Comment by vonguyen1982** [comment]
Yes, I used that microsoftTeams.getContext to get context in next page. I did add validDomains into domain section but window.location.href only work with same domain. It won't work when cross domain.

**Comment by HunaidHanfee-MSFT** [comment]
I again tried it and it is opening fine and I was able to access context too on both Desktop and Mobile. 
I have created a button - On click of button this method get called
```
navigateToDomain= async () => {
        window.location.href = "https://navigatecrossdomain.azurewebsites.net/navigateDomain";

    }
```
Feel free to check with our `https://navigatecrossdomain.azurewebsites.net/navigateDomain` domain too. It has a button that open trigger an alert showing context.TenantId. 

While you have updated the code `window.location.href` and updated the manifest, have sign out and login back on mobile. If not please do so. 



 I have tested it on Android 10, Teams Client v1416/1.0.0.2021114201.

**Comment by vonguyen1982** [comment]
Thank for your help. Could you please confirm from which domain you will redirect to navigatecrossdomain.azurewebsites.net domain ?
If you are using the domain then it won't be cross domain. Previous I did remember to logout/and login again in mobile.
I will try again and let you know more details.

**Comment by vonguyen1982** [comment]
I have re-done the some tests with domain azurewebsites.net and my own domain.
1. With azurewebsites.net domain everything is working fine as you said. I can redirect even without put domain into valid domain list and get context after redirect if I put domain into valid domain. Everything same as your result.
2. My issue is I host my application in Azure AKS and its domain is different domain from azurewebsites.net. It is kind my company domain(msteamapp.companyname.net). When I try with same code and change to my company domain and even I put my company domain into valid domain. It did not work in mobile and no context after redirect with location.href.

I only use simple javascript
```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
    <script>
        function navigateToDomain() {
            window.location.href = "https://vo-test2.xyz.com:5002/2.html";
        }
    </script>
</head>
<body>
    <button onclick="javascript: navigateToDomain();">Button test</button>
</body>
</html>
```

**Comment by HunaidHanfee-MSFT** [comment]
Please follow - [Access DevTools from an Android device](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/developer-tools#access-devtools-from-an-android-device) and see if you are getting any error.

**Comment by vonguyen1982** [comment]
I think I found it. I have wrong DNS set up.
Also if I do `window.location.href = "https://test2.mycompany.com/2.html?theme={theme}";`
**{theme}** does get resolved by ms teams so the **{theme}** messed up the route in my application.
