### ISSUE TITLE
microsoftTeams.authentication.authenticate method open popup windows in left upper corner in desktop MsTeams

### ISSUE THREAD

**Issue by maksim-pushkin-team-wrike** [OfficeDev/microsoft-teams-library-js#665]
The similar issue was earlier but was closed due to no answer from the author. https://github.com/OfficeDev/microsoft-teams-library-js/issues/461

The authenticate popup opens in left-upper corner when running in desktop version of msteams. In web version it works just fine. Using sdk version 1.10

But the bug is still there, could you please take a look?

**Comment by HunaidHanfee-MSFT** [comment]
We are looking into this. I will try to repro it and update you about the status.
Thanks

**Comment by HunaidHanfee-MSFT** [comment]
Please share the Microsoft Teams Desktop client version you are facing issue on? Is it happening for everyone?

**Comment by HunaidHanfee-MSFT** [comment]
The bug is already in our backlog item. I do not believe that's something we will tackle in the short-term. 

Feel free to re-open issue, incase of any query.
Thanks
