### ISSUE TITLE
Cannot set cookie with ms teams tab

### ISSUE THREAD

**Issue by vonguyen1982** [OfficeDev/microsoft-teams-library-js#674]
I have a blazor server-app website which run in ms teams personal tab and requires sticky session. It is working fine in MS Teams Desktop app and Mobile App because the app could create cookie. 

However in browser(Google and Edge) it failed because it could not create cookie. I checked/allowed all cookie setting already. 

I have done very simple test to create cookie and read cookie with javascript and I can prove that the cookie does not work with personal tab.

<script>
            document.cookie = "username=John Doe";
</script>

In browser in I check there is not cookie.  Do I need to set something to make the cookie work with ms teams  in browser.

**Comment by Wajeed-msft** [comment]
Could you please set the [SameSite cookie attribute](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/samesite-cookie-update#samesite-cookie-attribute-2020-release) and check?

**Comment by vonguyen1982** [comment]
I did try with SameSite=None; Secure but no luck

**Comment by HunaidHanfee-MSFT** [comment]
We have tried with the `document.cookie = "username=Sam Doe;SameSite=None;Secure";` and I can see cookie getting generated in dev tools. 

Try closing dev tools and opening it again, you will see.

**Comment by vonguyen1982** [comment]
Thanks for the tip closing dev tools and opening again.
