### ISSUE TITLE
Unable to perform task.submitTask from a web-based composeExtension on the iOS MS Teams app

### ISSUE THREAD

**Issue by ryansh100** [OfficeDev/microsoft-teams-library-js#676]
Manifest is setup like:
```
	"composeExtensions": [
		{
			"botId": "...",
			"canUpdateConfiguration": false,
			"commands": [
				{
					"id": "...",
					"type": "action",
					"title": "...",
					"description": "...",
					"initialRun": false,
					"fetchTask": false,
					"context": [
						"commandBox",
						"compose"
					],
					"taskInfo": {
						"title": "...",
						"width": "medium",
						"height": "medium",
						"url": "https://mywebsite.com/route/to/app"
					}
				}
			]
		}
	],
```

Prior to updating to version 1.11.0 this worked; but it appears that there has been a design decision made to limit what FrameContexts are allowed: https://github.com/OfficeDev/microsoft-teams-library-js/commit/90a1b0329c209547fd382d820ce6d295f58b45d2

Issue cannot be reproduced on Chrome browser or Windows Desktop application. Therefore, it appears that the "FrameContexts.task" is set properly on those clients but not on iOS where it appears to be "FrameContext.content".

Error received in remote logging on Sentry is
```
This call is not allowed in the 'content' context
```
Which appears to be the following code in @microsoft/team-js package: https://github.com/OfficeDev/microsoft-teams-library-js/blob/e6d607978af2ef87a63754c020abaea409179880/src/internal/internalAPIs.ts#L20

#### Other Details

manifest version: 1.9
@microsoft/teams-js version: 1.11.0
Applie iPhone 8, iOS version 14.8
iOS MS Teams app version: 3.15.1

**Comment by HunaidHanfee-MSFT** [comment]
We have  a repro at our end too. I am checking this will internal team. I will let you know the updates.
Thanks.

**Comment by konstanto** [comment]
Hi @HunaidHanfee-MSFT. Any progress here? This is quite damaging for our Teams app. We submitted an escalation post a while ago.

**Comment by HunaidHanfee-MSFT** [comment]
Teams is working on it. It's active our side. I will update you once it is fixed.

Thanks

**Comment by tjementum** [comment]
Any update on this? Our Teams app is also quite affected by this bug.

**Comment by HunaidHanfee-MSFT** [comment]
Internal engineering team is working on it, I will update as soon as I have update from them.

Thanks

**Comment by konstanto** [comment]
Hi @HunaidHanfee-MSFT. Do you have an update? It has now been more than three months and our customers are asking when they can expect the integration to work again. Can we expect a fix in the near future? 
Thank you!

**Comment by Meghana-MSFT** [comment]
Currently we do have any ETA to share. Team is looking into it. We will keep you posted.

**Comment by Gabriel2048** [comment]
Do we have any update on this? Seems like it's in active since around March?

**Comment by Meghana-MSFT** [comment]
Engineering team has identified this to be a new feature request in iOS. This feature will be picked up in near future. We do not have any exact timelines to share. Thank you.

**Comment by Meghana-MSFT** [comment]
This issue has been fixed and is publicly available now. We tested it in below version, and it works fine now. Please do verify and let us know. 
![image](https://user-images.githubusercontent.com/81138249/209774756-22e57b2e-2377-4708-8ae9-a60d262643ee.png)
