### ISSUE TITLE
Microsoft Teams version 1.4.00.26376 - Context.entityId is undefined

### ISSUE THREAD

**Issue by Oliver15-dev** [OfficeDev/microsoft-teams-library-js#681]
The entityId property is missing from the list of Context properties. Is this intended? I am getting errors in code stating that the entityId is undefined

It is still listed as a property in the docs:
https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context

![image](https://user-images.githubusercontent.com/55416849/137231883-b42095fb-eb2b-4b79-a7d9-b7d7f2056db6.png)

**Comment by v-chetsh** [comment]
@Oliver15-dev -  Could you try updating your Microsoft Teams desktop client and check it once.
Please let us know if you still need any help.

**Comment by Oliver15-dev** [comment]
@v-chetsh Too easy, uninstalling, then reinstalling Teams worked. After reinstalling, I clicked "Check for Updates". This installed version 1.4.00.28462, and I can now see the entityID option.

Thank you for your help
