### ISSUE TITLE
Auth0 and Google Login inside Teams tab

### ISSUE THREAD

**Issue by JCQuintas** [OfficeDev/microsoft-teams-library-js#682]
Hi, we currently have a Microsoft Teams application that contains a tab the user can use to view our website/application. The user can login through this tab using Auth0, that opens in a popup and the user has the options to login with `Google`, `Microsoft`, `Apple` and `Password`.

On most places it works fine, except for the mobile Teams application, where the `Google` login is blocked with: `Error 403: disallowed_useragent` seen on the screenshot below. 

Is there any way of working around or fixing this issue?

![Screenshot_20211014-175447_Teams 1](https://user-images.githubusercontent.com/9891233/137354625-6957dd5b-bfa1-4f37-a068-fa1b710d451e.png)

**Comment by Meghana-MSFT** [comment]
@JCQuintas - We have a bug raised for this issue. The concerned team is looking into it.

**Comment by Meghana-MSFT** [comment]
Engineering team has considered this has a feature requirement and has added Support for 3rd Party OAuth (such as Google) on Teams Mobile.
