### ISSUE TITLE
authentication.authenticate() not allowed to be called from meetingStage context

### ISSUE THREAD

**Issue by antonhedstrom** [OfficeDev/microsoft-teams-library-js#683]
Hi!

We are developing an app to be used in both **sidePanel** and **meetingStage** context. We are using the `sdk.authentication.authenticate()` method. In this [commit](https://github.com/OfficeDev/microsoft-teams-library-js/commit/744e3b4d5552f5e0259227cecec45a4f7d50e25a) the **meetingStage** context was added as allowed context for the `authenticate` method. But when we try to call it we are geting the following error message from the `failureCallback`:

> Authentication API not supported in meetingStage context

Here is the code snippet we are using:

```js
microsoftTeams.authentication.authenticate({
    url: `${window.location.origin}/auth-azure`,
    width: 600,
    height: 535,
    successCallback: () => {
        window.location.reload();
    },
    failureCallback: (reason) => {
        showErrorMessage(reason); // reason equals "Authentication API not supported in meetingStage context"
    },
});
```

How can we authenticate our users from the **meetingStage** context?

Thanks in advance!

**Comment by antonhedstrom** [comment]
Oh, sorry, forgot that part.

I am using 1.11.0. 

My guess is that this is a message coming from the Teams app (not the SDK). Seems that the error message is the response after the SDK calls `sendMessageToParent('authentication.authenticate')`.

**Comment by antonhedstrom** [comment]
Seems to be solved by now? We haven't updated any versions of the SDK on our side so I guess the Teams app was updated?
Anyhow, works from our end :)

**Comment by HunaidHanfee-MSFT** [comment]
Sounds good, fix is rolling out for all. So it should get available for every user soon.
