### ISSUE TITLE
Clarify error message when calling registerOnSaveHandler from outside a configuration page

### ISSUE THREAD

**Issue by naamunds** [OfficeDev/microsoft-teams-library-js#688]
When calling registerOnSaveHandler from outside of a configuration page, an error is thrown with message "This call is not allowed in the 'content' context."  After following up on this, my understanding is that this API is only available in [configuration pages](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page).  It would be helpful if the error message specifically stated that it's only available in configuration pages.

**Comment by MarcinJuraszek** [comment]
This applies to all the cases where an API call is rejected and errors out because it's being used in a wrong FrameContext.

**Comment by Nivedipa-MSFT** [comment]
@naamunds - We are looking into this issue.We will investigate and let you know

**Comment by MarcinJuraszek** [comment]
This is now resolve in the 2.0-preview branch
