### ISSUE TITLE
getContext throws: TypeError: can't assign to property "frameContext" on true: not an object

### ISSUE THREAD

**Issue by janandreschweiger** [OfficeDev/microsoft-teams-library-js#690]
Hi everyone, we use @microsoft/teams-js version 1.11.0.

When we call getContext like in the following code sample your library throws the error mentioned in the title.
```
await new Promise((resolve, reject) =>  // works
  microsoftTeams.authentication.getAuthToken({
    successCallback: resolve,
    failureCallback: reject
  })
);
microsoftTeams.getContext(context => {  // works, but throws error
  console.log(context);
});
```

The strange thing is that getContext actually calls the callback and provides the right context. So everything works for us. Nevertheless, I wanted to report this issue, as this error indicates a possible failure. In addition, the error spams our logs, as we get it for every new Task-module / Teams-tabs sign in.

I would be great if you could provide a fix in the next version.

Thank you
Jan

**Comment by Nivedipa-MSFT** [comment]
@janandreschweiger  - We are looking into the issue.We will update you.

**Comment by HunaidHanfee-MSFT** [comment]
We tried this and it works. But not sure exactly what errors you are getting? Can you share

**Comment by janandreschweiger** [comment]
Thanks for investigating this issue @HunaidHanfee-MSFT.

Unfortunately, your authentication library doesn't work in most environments (e.g. Windows, Linux, Chrome). Because of this issue: #675 

In some scenarios / environments (e.g. in Firefox) the authentication works, but logs the error I have mentioned above.

An example would Teams tabs and Messaging Extensions in Firefox. Both work, but raise this error, when I call the following method:
```
const login = async () => {
  await new Promise((resolve, reject) =>  // works
    microsoftTeams.authentication.getAuthToken({
      successCallback: resolve,
      failureCallback: reject
    })
  );
  microsoftTeams.getContext(context => {  // works, but throws error
    console.log(context);
  });
};
```

Here is a short table as an overview:
```          
                 Teams tabs  |  Tab modules (opened by link/button)  |  Tab modules (opened by Messaging Extensions)
Windows         Yes                                   No                                                                     Yes
Linux               Yes                                   No                                                                     Yes
Chrome           Yes                                   No                                                                     Yes
Firefox             Yes                                   Yes                                                                    Yes
```

No ... Authentication fails with "Definition not found" (#675)
Yes ... Authentication works, but logs "TypeError: can't assign to property frameContet on true: not an object"

**Comment by HunaidHanfee-MSFT** [comment]
I checked this on Edge, I will check it on other browser and let you know.

Thanks

**Comment by HunaidHanfee-MSFT** [comment]
I tested this in chrome and still not getting this error on Tab. Did you initialize the teams SDK before calling this?

**Comment by HunaidHanfee-MSFT** [comment]
Could you please share the complete logs you are getting?

Thanks

**Comment by janandreschweiger** [comment]
I noticed that I had some parallel calls of microsoftTeams.authentication.getAuthToken. Now everything seems to work properly.

Thanks for your help @HunaidHanfee-MSFT. I will reopen this issue, if this issue comes back.
