### ISSUE TITLE
Some HTML styles on mobile don't work

### ISSUE THREAD

**Issue by sergesama** [OfficeDev/microsoft-teams-library-js#695]
When I send html code with message in teams on desktop version it looks like this:
![image](https://user-images.githubusercontent.com/16437297/140934479-d30c014e-9f79-49d2-8110-8ebff9041d9f.png)

But on Android(10 QKQ1.191215.002) mobile Teams app it looks like this:
![image](https://user-images.githubusercontent.com/16437297/140934984-0eeee247-7b14-49c9-97c7-5397ff5e35f3.png)

That means that some styles that I insert in html code by adding attribute `style` in `<div>` doesn't work, because how you can see on 2nd screenshot style "background-color" works, but others don't.
Could you say what HTML styles on mobile Teams app on IOS and Android are supported?

**Comment by HunaidHanfee-MSFT** [comment]
Are you trying to do it with Hero card or in normal message? Can you share minimal code snippet to repro? It will help us repro issue faster and accordingly we can raise the bug.

Thanks

**Comment by sergesama** [comment]
I tried it with Office card and tried to send in normal message. The result is the same.
Calendar.txt - file with functions that only generate html code. GenerateCardBody is result function for all html text.
[calendar.txt](https://github.com/OfficeDev/microsoft-teams-library-js/files/7507950/calendar.txt)
messageExtensionBot.txt i take code from example. just add Office card to attachments in handleTeamsMessagingExtensionQuery function
[messageExtensionBot.txt](https://github.com/OfficeDev/microsoft-teams-library-js/files/7507894/messageExtensionBot.txt)

**Comment by HunaidHanfee-MSFT** [comment]
@sergesama , I have a repro at my end and I think this is by design - As you can see in [doc](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-text-formats#support-by-individual-platform) not all the markdowns are supported for different platform.

I will let you after confirming this internally.

**Comment by HunaidHanfee-MSFT** [comment]
We have raised a bug and internal engineer team is looking into it. I will let you know once it is fixed.

Thanks
