### ISSUE TITLE
[Question] Timeout on registerOnSaveHandler

### ISSUE THREAD

**Issue by bajzat** [OfficeDev/microsoft-teams-library-js#704]
Hi!

I'd like to inquire, is there any time limit on registerOnSaveHandler to complete the handler and call the notifySuccess/notifyFailure function?

Our workflow to add a new tab instance of the application is the following:

1. User open the 'Add a tab' popup 
2. Select the application
3. Application opens in iframe
4. User fills a small form, if the form is valid the app sets the validity true using MS Teams SDK
5. User clicks to the save button we are getting the event from the SDK set the settings and call BE to create entities (it could take 2-3 mins in the worst case)
6. Sometimes it's quick and we cannot see this message but when the BE operations take one or two minutes then the user is getting an error message from Teams and the Save button is getting enabled again

![image](https://user-images.githubusercontent.com/1759750/141278278-e9bc20ac-df6f-4d5f-9d7f-3b84d0175378.png)

Thanks,

Tamas

**Comment by HunaidHanfee-MSFT** [comment]
I will check this internally and get back to you with findings.

Thanks

**Comment by wictorwilen** [comment]
I think this is how it is supposed to work. There should be a timeout on that one. A call to the back-end/web service should not take long - and if it does an error should be shown. Otherwise the user might be stuck on that page forever. I would recommend that you re-write your webservice so that it accepts the command and responds with an HTTP 201 or 202 (which is the standard way to do it). And then in your actual tab - you just need to have some logic that, if the tab isn't created by the backend yet, shows a "working on it" screen or similar.

**Comment by bajzat** [comment]
Thanks for the quick responses.

@HunaidHanfee-MSFT I'm looking forward to it.

@wictorwilen yes our idea is similar, our BE team is working on it, Unfortunately till the new BE calls are ready, I don't have any other option. 

Anyway, It would be great to get a confirmation there is a timeout and the exact value of the timeout if it's possible.

**Comment by HunaidHanfee-MSFT** [comment]
We got to know from team that - 

> The developer has 30 seconds to complete the async save operation (i.e. the callback passed to registerOnSaveHandler). After that we timeout and show a generic error to the user. 

> On the remove flow (i.e. the callback passed to registerOnRemoveHandler) we only give them 15 seconds and also automatically light up the "Remove" button after 5 seconds even if the app developer hasn't yet called setValidityState(true)

That's make it clear, let us know if you have any query, we will update this in doc as well. 

Feel free to reopen, I am closing it as of now.

Thanks

**Comment by HunaidHanfee-MSFT** [comment]
Here are the details of doc bug raised - 
1. https://github.com/MicrosoftDocs/msteams-docs/issues/4709
2. https://github.com/MicrosoftDocs/msteams-docs/issues/4708
