### ISSUE TITLE
There are two README files and they are supposed to be identical but they are not

### ISSUE THREAD

**Issue by TrevorJoelHarris** [OfficeDev/microsoft-teams-library-js#721]
We have README.md and packages\teams-js\README.md. I found one difference between the two earlier and fixed it, but we should probably only have the copy in the root and then copy it into packages\teams-js during the build or publish steps.

**Comment by sayali-MSFT** [comment]
@TrevorJoelHarris  - We are looking into this I will get back to you soon.

**Comment by v-chetsh** [comment]
@SurbhiJainMSFT - Could you please help us to redirect it to doc team.

**Comment by v-chetsh** [comment]
@surbhigupta12 - Could you please look into this issue.

**Comment by surbhigupta12** [comment]
@v-chetsh, we are not the right team to update this.

**Comment by v-chetsh** [comment]
@TrevorJoelHarris - We can see only one Readme.md file at the root level but could not able to find **packages\teams-js\README.md** file in main branch.
I think, once we build the project, it's generating this file?
