### ISSUE TITLE
Are there any plans to let a Teams app get access to the clipboard apis?

### ISSUE THREAD

**Issue by tdwhite0** [OfficeDev/microsoft-teams-library-js#738]
Currently when you try to use the clipboard api Teams will give you an error like this:

Uncaught (in promise) DOMException: The Clipboard API has been blocked because of a Feature Policy applied to the current document. See https://goo.gl/EuHzyv for more details.

Maybe there could be a permission request like Teams already does with camera, microphone, and location?

https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API

**Comment by Nivedipa-MSFT** [comment]
@tdwhite0 - Discussed with platform team. Currently platform teams is working to release this setting has new feature.

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.

**Comment by AE-MS** [comment]
@tdwhite0 Does the new [clipboard capability](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/clipboard?view=msteams-client-js-latest) meet your needs?
