### ISSUE TITLE
Blank screen on Android

### ISSUE THREAD

**Issue by gabbsmo** [OfficeDev/microsoft-teams-library-js#745]
I have an existing SPA and Web API with Azure AD authentication that I want in a Teams app with SSO. It works perfectly on web and desktop but in Teams for Android I just get a blank screen. It works as expected in regular browsers for Android. I am using a self signed SSL certificate but I have installed my CA on the device and I get no errors in browsers.

I managed to attach the chrome debugger to the Teams app's web view and could see that `location.href === 'about:blank'`.

I am enrolled in the Microsoft Starbuster program for Teams ISVs. I first sent my question to my technical contact at Microsoft, who contacted Teams engineering who then requested that I post here instead.

**Comment by v-chetsh** [comment]
@gabbsmo - Could you please share the repro steps and screenshot of issue, if any.

**Comment by gabbsmo** [comment]
@v-chetsh I cannot share the source unfortunately.

The screen is just plain white. No errors or anything.

Is there a sample ASP.NET MVC Visual Studio project so that I can verify that this type of app works at all?

**Comment by v-chetsh** [comment]
@gabbsmo - I am sharing a one Teams tab sso sample for your reference and testing:
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-sso/csharp

**Comment by gabbsmo** [comment]
@v-chetsh Cannot get the sample to work. manifest.json says there should be a tab configuration page at /Home/ConfigTab. If I add the app to a team I get a blank page. If I try to browse to /Home/ConfigTab I get 404.

**Comment by Nivedipa-MSFT** [comment]
@gabbsmo - Could you please share your manifest file?

**Comment by gabbsmo** [comment]
@Nivedipa-MSFT Managed to figure out the errors in the README and reported them here: https://github.com/OfficeDev/Microsoft-Teams-Samples/issues/207

@v-chetsh @Nivedipa-MSFT 
Managed to get the sample running on Android but it seems that ngrok has some kind special standing in Azure AD. Normally when specifying an App ID URI you need to verify the domain first. I did not have to do that for ngrok.

In my own app I am running IIS Express exposed on the internet and DNS is configured to point my own domain to the local machine with a self signed certificate bound to port 44300. This works on desktop but not Android. This is a MVC 4/Web API 2 app and uses applicationhost.config to enable connections from other custom hostname instead of localhost. This config file is not available in your sample. Can this type of configuration be made for the sample?

**Comment by Nivedipa-MSFT** [comment]
@gabbsmo - Could you please confirm if you are able to  manage to run application using ngrok.

**Comment by gabbsmo** [comment]
@Nivedipa-MSFT Yes it works with ngrok.

**Comment by gabbsmo** [comment]
@Nivedipa-MSFT I can now confirm that on Teams for Windows desktop it works with both my custom domain and ngrok. On Teams for Android ngrok work but not my custom domain. I can open the custom domain in a regular web browser on Android.

Are there restrictions on port numbers in the Android app? I use port 44300 for https during development.

**Comment by v-chetsh** [comment]
@gabbsmo - I don't think there is a port number restrictions here but could you please try it with some other port numbers like: 5000 or 5001 etc.

**Comment by gabbsmo** [comment]
@v-chetsh I will be able to test with a environment that uses default port numbers (80 and 443) and Azure App Service certificate within a week or two. I will report back.

**Comment by gabbsmo** [comment]
@Nivedipa-MSFT @v-chetsh I can now confirm that it works in Teams for Android when my web app is deployed to Azure App Service with a custom domain rather than on my development machine.

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
