### ISSUE TITLE
How to get User's recording policy?

### ISSUE THREAD

**Issue by stefan2410** [OfficeDev/microsoft-teams-library-js#749]
Hi, 
is there a way to get user's recording policy from the teams library?   or from Graph API ?

**Comment by Meghana-MSFT** [comment]
Could you please share more details of the issue or point us to the documentation for better understanding? Also could you please let us know if this is what you are looking for [Get-CsTeamsComplianceRecordingPolicy](https://docs.microsoft.com/en-us/powershell/module/skype/get-csteamscompliancerecordingpolicy?view=skype-ps)?

**Comment by stefan2410** [comment]
@Meghana-MSFT   yes the same as the   Get-CsTeamsComplianceRecordingPolicy  for the user. SDK to give us the information about its recording policy.

**Comment by Meghana-MSFT** [comment]
We are checking this internally. We will update you.

**Comment by Meghana-MSFT** [comment]
@stefan2410 - We got an update from the engineering team. There is no SDK or Graph API support at the moment. We can use Admin portal and cmdlets only.

**Comment by Meghana-MSFT** [comment]
We are closing this issue. Please feel free to reopen this issue if you have any queries.
