### ISSUE TITLE
[Mobile] Teams js sdk returns wrong theme when opening task in a meeting tab during meeting

### ISSUE THREAD

**Issue by matthiasdilger** [OfficeDev/microsoft-teams-library-js#753]
Tested with version 1.11.0

Teams apps should use dark theme in meeting tabs during a meeting: https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/design/designing-apps-in-meetings#theming
But Teams js sdk returns 'default' on mobile in context.theme when opening a task in a meeting tab during a meeting

To reproduce:
Create app that supports tab in meetings
Create meeting
Add app to meeting
Join meeting on mobile
Navigate to app tab on mobile
Inside tab call getContext() and notice context.theme === 'dark'
In the tab open a task using microsoftTeams.tasks.startTask(taskInfo, submitHandler); where taskInfo.url is some website
In the task website call getContext() and notice context.theme === 'default'

On desktop and web context.theme === 'dark' after meeting has been joined, which is correct

**Comment by sayali-MSFT** [comment]
@matthiasdilger - We are looking into this I will get back to you soon.

**Comment by HunaidHanfee-MSFT** [comment]
We are unable to repro this issue. After joining meeting there's no such control to navigate to the tab. We have minimize the meeting Go to More - and select the desired tab. Inside the tab even after opening the task module everything is working fine. 

Can you please share screenshot or video for repro reference?

**Comment by HunaidHanfee-MSFT** [comment]
@matthiasdilger  - Could you please share?

**Comment by matthiasdilger** [comment]
@HunaidHanfee-MSFT I will check again in the next couple of days

**Comment by matthiasdilger** [comment]
@HunaidHanfee-MSFT 
I have re-tested this flow on Android only. Added some pseudocode.

Step 1:
Add tab to a meeting on desktop
<img width="504" alt="Screen Shot 2021-12-15 at 11 57 46" src="https://user-images.githubusercontent.com/5625718/146121285-13545277-8cf8-4282-8af1-1130a3f5a009.png">

Step 2:
On mobile select the meeting and press "Join"
![Screenshot_20211215-115842](https://user-images.githubusercontent.com/5625718/146121493-a7bf21a9-7b6c-471b-95c7-22ed9b23fd98.png)

Step 3:
Press "Join now"

Step 4:
In the meeting, press the three dots and select the tab you added above
![Screenshot_20211215-115924](https://user-images.githubusercontent.com/5625718/146121729-5b2810e2-9ba6-4458-b0d5-403bfe7a30f6.png)

Step 5:
In the tab that opens (new activity on Android) execute the following:
```
microsoftTeams.getContext(function(context) {
    alert(context.theme);
});
```
Notice that context.theme == 'dark', which is correct

Step 6:
In the same tab implement a button that executes the following when pressed:
```
var taskInfo = {
            title: 'test',
            height: 'medium',
            width: 'medium',
            url: '/test.html',
            card: null,
            fallbackUrl: null,
            completionBotId: null,
};
submitHandler = (err, result) => {};
microsoftTeams.tasks.startTask(taskInfo, submitHandler);
```

Step 7:
In your test.html task page execute this:
```
microsoftTeams.getContext(function(context) {
    alert(context.theme);
});
```
Press the button in the tab to open the task above (another new activity opens in the app) and notice that now context.theme === 'default', which is wrong.

So the app opens one new window/activity for the tab and another on top for the task after the user has pressed the button. I suspect that this is not a bug in the JS lib but rather in the mobile app. When the new activity is opened for the task it does not consider that it is "in-meeting" and needs to switch to dark theme.

**Comment by HunaidHanfee-MSFT** [comment]
Thanks for providing the detailed steps I am checking it at our end. Will let you know soon.

**Comment by HunaidHanfee-MSFT** [comment]
What I see is not exactly what you have mention. For me it's showing the correct theme inside task module. But showing the content as well as theme **dark** when opening the just the tab after joining meeting using the three dots. It seems like its taking the theme when the tab got added. I am looking into it and trying to understand this behavior. I will keep you posted on findings.

Thanks

**Comment by matthiasdilger** [comment]
@HunaidHanfee-MSFT Your step 4 is the issue. The teamsubm app review team has flagged an issue with my app because according to https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/design/designing-apps-in-meetings#theming **the theme should be forced to 'dark'**. Maybe you can talk to the teamsubm folks?  I have added a workaround to force the theme to dark in the task during a meeting on mobile (your step 4) which satisfied teamsubm, but it's clunky. It would be nice if both the tab and the task could set context.theme to 'dark' on mobile during meetings.

**Comment by HunaidHanfee-MSFT** [comment]
Can you confirm that when forcing it to change theme you are getting the incorrect theme? if this not true, can you tell where you are getting incorrect theme or no longer facing this issue? We are checking this internally as well.

**Comment by matthiasdilger** [comment]
@HunaidHanfee-MSFT  The issue is really very simple. In your step no. 4 context.theme should return 'dark' because the user is in a meeting. It works this way on desktop and it should also works this way on mobile.
I currently work around this issue in the task this way:
```
microsoftTeams.getContext(function(context) {
  if(context.theme === 'dark' || (typeof context.meetingId !== 'undefined' && context.meetingId !== '' && (context.hostClientType === 'android' || context.hostClientType === 'ios'))) {
          //set css theme to dark        
   }
});
```
So that the theme is dark in meetings on mobile as well. I don't like this workaround, so please make context.theme === 'dark' in meetings on mobile as well.
If this is still not clear, I will close the ticket and keep the workaround.

**Comment by HunaidHanfee-MSFT** [comment]
Thank you for clearing. We got your issue and we have the repro of this behavior. We are working on it internally. I will keep you updated. 

Thanks

**Comment by HunaidHanfee-MSFT** [comment]
We have raise a bug and internal engineering team is working on it. We will share the updates on this issue.

Thanks

**Comment by Prasad-MSFT** [comment]
@matthiasdilger - We got update from engineering team that "As per the design guidelines from Mobile any tab launched from in meeting experience will follow teams default theme rather than in meeting theme."

**Comment by matthiasdilger** [comment]
@Prasad-MSFT This seems to clash with the advice in https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/design/designing-apps-in-meetings#theming
"Focus on dark theme"
Maybe the documentation needs to be more specific?

**Comment by Prasad-MSFT** [comment]
Ok @matthiasdilger - We will bring this to notice of engineering team and will update the documentation if required. Thanks!

**Comment by matthiasdilger** [comment]
Closing this for now, will reference this issue if it comes up again during the next app review
