### ISSUE TITLE
Way to make Apps RTL compliance on the Host

### ISSUE THREAD

**Issue by sribabuk** [OfficeDev/microsoft-teams-library-js#787]
Team, 

Use case: Showing Apps in RTL compliance view, on the Host.

I happened to scan through this [ContextInterface ](https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/microsoftteams.context?view=msteams-client-js-latest) and couldn't find a way, for the Host, to pass RTL related information to the Apps or otherwise. Am i missing something?

Just an FYI, this is an important compliance item tracked for Mobile use cases.

**Comment by MarcinJuraszek** [comment]
@ydogandjiev  is this something that came up before for TeamsJs?

**Comment by HunaidHanfee-MSFT** [comment]
Hello @sribabuk, 
Could you please share screenshot what you are trying to do and where you are facing the issue?

If you want to get locale information you have it using `context.locale` - here the link to [locale](https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/microsoftteams.context?view=msteams-client-js-latest#locale).

**Comment by sribabuk** [comment]
Team, this is the flow:

1. Android device
2. In settings, enabled the RTL mode
3. Loaded the App
4. App is not complaint with RTL mode settings

**Comment by HunaidHanfee-MSFT** [comment]
Could you please share screenshot? I can't see RTL setting in Teams client

**Comment by sribabuk** [comment]
Host screen:
![Screenshot_1640154326](https://user-images.githubusercontent.com/81160246/147045998-49489e9e-9489-4a5d-9c0f-75c83e861537.png)

App screen:
![Screenshot_1640154271](https://user-images.githubusercontent.com/81160246/147046043-49b8e3d9-ca9d-4731-b169-0dd7a65d005d.png)

Enabling RTL setting in Android:
You need to enable developer options setting in Android for that. 
Other option could be that, you can use the appropriate language that is compatible with RTL direction.
See if this [helps](https://www.phonearena.com/news/How-to-force-right-to-left-RTL-layouts-on-Android_id64154)

**Comment by HunaidHanfee-MSFT** [comment]
Did you implemented RTL in your application? If yes, is it not working when you are changing settings?

**Comment by sribabuk** [comment]
I am team member for one of the Hosts. We are testing various apps in our Host. As depicted above, our Host application is compatible with RTL the moment the setting is applied.

Will that percolate to the loaded app as well? Today, i do not see a mechanism to make this info available to the App.

**Comment by HunaidHanfee-MSFT** [comment]
Not sure I understood your issue correctly or not but I can share you some reference where we are getting the locale with [`context.locale`](https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/microsoftteams.context?view=msteams-client-js-latest#locale) and using i18next module we are getting if the locale is RTL or not and accordingly applying custom CSS on it. 

Here's the reference - 
`i18n.dir(context.locale!) === LanguageDirection.Rtl ? LanguageDirection.Rtl : LanguageDirection.Ltr`
Link to app template's- 
[_Code Snippet_](https://github.com/OfficeDev/microsoft-teams-apps-employeetraining/blob/467ebb6830422a4ab3d6ec60d62cda35dcb85e59/Source/Microsoft.Teams.Apps.EmployeeTraining/ClientApp/src/providers/context-provider.tsx#L26)

```
componentDidMount() {
            microsoftTeams.initialize();
            microsoftTeams.getContext((context: microsoftTeams.Context) => {
                this.setState({ teamsContext: context, dir: i18n.dir(context.locale!) === "rtl" ? "rtl" : "ltr"});
            });
        }
```

Please have a look and you can try this out and implement same to get the locale if its in RTL or not


Please let us know if this resolved your issue.
Thanks

**Comment by HunaidHanfee-MSFT** [comment]
@sribabuk - Could you please confirm if your issue has resolved or still looking for any help?

**Comment by sribabuk** [comment]
@HunaidHanfee-MSFT 
Thanks for the sample code reference.

But as per the [context documentation](https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/microsoftteams.context?view=msteams-client-js-latest#locale) in teamsjs ->  locale is referring to language details set in the Host which contradicts with above example.

Am i missing something here?

**Comment by HunaidHanfee-MSFT** [comment]
@sribabuk Right, we are passing the locale(language) to determine if its RTL language or not.

**Comment by sribabuk** [comment]
Thanks, Its clear now. To summarize, its App responsibility to extract the direction information from the locale passed by the Host (via Context). Am i correct?

**Comment by HunaidHanfee-MSFT** [comment]
To be 100% sure taking final confirmation with the internal engineering team. Will let you know soon. 

Thanks

**Comment by HunaidHanfee-MSFT** [comment]
Hello @sribabuk - 
Could you please tell us what is the behavior of your tab application on desktop Teams client and on Teams web browser?

When you are changing locale to say Arabic is it adapting the RTL style?

**Comment by HunaidHanfee-MSFT** [comment]
Hello @sribabuk,

> Could you please tell us what's the behavior of your tab application on desktop Teams client and on Teams web browser?
> 
> When you are changing locale to say Arabic is it adapting the RTL style?
