### ISSUE TITLE
"Auth Library Error" issue on iOS 15

### ISSUE THREAD

**Issue by bxav** [OfficeDev/microsoft-teams-library-js#791]
Hello,
I'm getting an "Auth Library Error" on iOS 15 using "microsoftTeams.authentication.getAuthToken" from the @microsoft/teams-js npm package (^1.11.0). It's impacting an app in prod.
And other platform works well (desktop window/mac, web, android, iOS < 15).

I think it might have happened since the last iOS update (13/12).

Am I the only one?

**Comment by HunaidHanfee-MSFT** [comment]
We have a bug already raised for this behavior. Team is working on it. 

I will share the updates as soon as it is fixed and rolled out.

Thanks

**Comment by HunaidHanfee-MSFT** [comment]
We have check and confirm that this issue is fixed and we are no longer seeing "_Auth library Error_" and we are getting the access token. Could you please try and check if you are still able to reproduce this issue in the latest build?

Thanks

**Comment by bxav** [comment]
Thanks, it works on iOS v15.0 (tested on browserstack)
