### ISSUE TITLE
Detect when task module is closed via the X or clicking off the task

### ISSUE THREAD

**Issue by helloworldsmart** [OfficeDev/microsoft-teams-library-js#795]
### How to detect when task module is closed via the X or clicking off the task modules 

We have had the form features on the task modules but user usually via the X or clicking off the task modules .
So, We have implemented popup prompt dialog on the task modules when via the X or clicking off the task modules 
But ... How to detect when task module is closed via the X or clicking off the task modules ?

have event received when user close the task module from X ?

stackoverflow same problem 
https://stackoverflow.com/questions/56980091/detect-when-task-module-is-closed-via-the-x-or-clicking-off-the-task

Thank you

**Comment by HunaidHanfee-MSFT** [comment]
Is it inside tab or opening it through bot?

**Comment by helloworldsmart** [comment]
@HunaidHanfee-MSFT  inside tab

**Comment by HunaidHanfee-MSFT** [comment]
Yes, you can get this information with the `submitHandler` `err` string. When user press Esc or click on _X_. It give error as _"User cancelled/close the task module"_

Have a look at code reference - 
```
microsoftTeams.tasks.startTask(taskInfo, (err: string, re: string) => { 
    if (err) {
        // It will execute this part if there's some error or user click on X button
        alert(err);
    }
});
```
Let me know if you have any query around it.

**Comment by helloworldsmart** [comment]
We features is:
click on X button then task module don't immediately close, we want alert on the task module,
ask user : "Do you want to save the form ?"
Thank you ~

**Comment by HunaidHanfee-MSFT** [comment]
There is no such event handler available to handle it. Here the link that show available methods inside `tasks` - 
https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/microsoftteams.tasks?view=msteams-client-js-latest

Thanks

**Comment by helloworldsmart** [comment]
The issue can't solve . 🥺

**Comment by HunaidHanfee-MSFT** [comment]
As of now there no such handler is available. You can share feedback and give new feature idea on this portal- 
https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472

Please let us know if you have any query around or we will close this issue. 

Thanks

**Comment by HunaidHanfee-MSFT** [comment]
Hello,
We are closing this issue as of now. Please let us know if you have any query and feel free to open the issue. 

Thanks
