### ISSUE TITLE
Detect save events on tab configuration

### ISSUE THREAD

**Issue by romain-faust** [OfficeDev/microsoft-teams-library-js#796]
Hello,

We are wondering if it's possible to detect save events for the static tabs configuration modal. Our use case involves the side panel from Teams Meetings.
We tried various hacky solutions to detect such events but they didn't work as expected.

Could you please provide some guidance because we couldn't find any example in the documentation.

Thanks by advance

**Comment by HunaidHanfee-MSFT** [comment]
Could you please make it more clear what you mean when saving tab configuration? Like when you add a tab in Team it's shows a pop-up/ configure page and on click of save button it calls the method mention below 

_callBack of registerOnSaveHandler_

```
microsoftTeams.settings.registerOnSaveHandler(function (saveEvent) {
            microsoftTeams.settings.setSettings(settings);
            saveEvent.notifySuccess(); 
});
```
Some link for your references - https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/create-tab-pages/configuration-page
Are you looking for something else? Or are looking foe some event for static tabs? If for static tab please elaborate more.

Thanks

**Comment by v-chetsh** [comment]
@romain-faust - Could you please confirm if your issue has resolved with above suggestion or still looking for any help?

**Comment by romain-faust** [comment]
Hello, I confirm that my issue is resolved.
Thank you for your quick feedback 🙂
