### ISSUE TITLE
Unable to run media capabilities API in mobile devices

### ISSUE THREAD

**Issue by g138** [OfficeDev/microsoft-teams-library-js#799]
I am working with `microsoftTeams.media.selectMedia(...` API on clicking button getting

9000 | OLD_PLATFORM | Platform code is outdated and does not implement this API.
-- | -- | --

> Here I am iPhone Xr with Microsoft Version 3.20.0

**TypeScript Code:**

```
  onFileSelected() {
    microsoftTeams.initialize();
    microsoftTeams.media.selectMedia(
      this.mediaInput,
      (
        error: microsoftTeams.SdkError,
        attachments: microsoftTeams.media.Media[]
      ) => {
        if (error) {
          if (error.message) {
            alert(' ErrorCode: ' + error.errorCode + error.message);
          } else {
            alert(' ErrorCode: ' + error.errorCode);
          }
        }
        if (attachments) {
          this.y = attachments[0];
        }
      }
    );
  }
```

**HTML Code:**

```
<button
  (click)="onFileSelected()"
  class="btn-cm"
  style="
    color: #58ef47;
    margin-top: 15px;
    width: 150px;
    height: 40px;
    font-size: medium;
  "
>
  Select File
</button>


{{ "data:" + y?.mimeType + ";base64," + y?.preview }}

```

**Note: I am running thins code in Angular App as a Task Module in Extension**

**But after  several refreshes it shows the camera options that means it works**

**Comment by HunaidHanfee-MSFT** [comment]
Can you try moving microsoftTeams.initialize() when the page loaded and see if it work? You can also try setting up this sample and confirm if facing same in it - https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-device-permissions/nodejs

**Comment by g138** [comment]
Yes moving `microsoftTeams.initialize()` fixed the issue.

**Comment by HunaidHanfee-MSFT** [comment]
We would like your [feedback on your experience with our support team and Platform.](https://aka.ms/DevSupportFeedback)

Thanks
