### ISSUE TITLE
How do you print things from a teams tab?

### ISSUE THREAD

**Issue by nbelyh** [OfficeDev/microsoft-teams-library-js#811]
I have a microsoft Teams tab application. I would like to **print an svg image** from this tab (generated on the client)
Normally, this is done by opening a new window and constructing a document to print there (I want to print a generated svg picture)
But in teams client, this option is disabled as opening popups is disabled.

I have tried some workarounds to open popups mentioned here to no avail:
- using `microsoftTeams.tasks.startTask` to open a popup and try printing from there (does not load because the file is not located on the server at all, it is generated on the client). Maybe this can be still done somehow?
- `microsoftTeams.authentication.authenticate` to open a new window. Downloads the content instead of opening it.

Thank you in advance for any ideas?

**Comment by sayali-MSFT** [comment]
@nbelyh - We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
Duplicate -https://stackoverflow.com/questions/70593813/printing-generated-image-from-teams-tab
