### ISSUE TITLE
Print generated image from teams tab?

### ISSUE THREAD

**Issue by nbelyh** [OfficeDev/microsoft-teams-library-js#812]
I have a microsoft Teams tab application. I would like to **print an svg image** from this tab (generated on the client)
Normally, this is done by opening a new window and constructing a document to print there (I want to print a generated svg picture)
But in teams client, this option is disabled as opening popups is disabled.

I have tried some workarounds to open popups mentioned here to no avail:
- using `microsoftTeams.tasks.startTask` to open a popup and try printing from there (does not load because the file is not located on the server at all, it is generated on the client). Maybe this can be still done somehow?
- `microsoftTeams.authentication.authenticate` to open a new window. Downloads the content instead of opening it.

Thank you in advance for any ideas?

**Comment by Meghana-MSFT** [comment]
Could you please share more details like the sample you are referring to if any?

**Comment by nbelyh** [comment]
Sorry this was occasionally opened as duplicate of #811
