### ISSUE TITLE
The Plan about Teams SDK V2

### ISSUE THREAD

**Issue by NewFuture** [OfficeDev/microsoft-teams-library-js#825]
When will the teams-js v2 be released?

**Comment by sayali-MSFT** [comment]
@NewFuture - We are checking it internally and let you know if we get any updates.

**Comment by NewFuture** [comment]
@sayali-MSFT  thanks

**Comment by AE-MS** [comment]
> When will the teams-js v2 be released?

Hi @NewFuture, thanks for your interest in the newest release of TeamsJS v2! We haven't yet announced a release date for v2, but we're working hard to ensure we can update our developer community with a plan and date for it. We want to ensure we have the right amount of confidence that we can deliver a high-quality release for the date we announce to avoid having to later change that date. We're strongly motivated to deliver TeamsJS v2 ASAP to ensure we maintain a single, high-quality, platform for our developers. If you stay tuned to our [developer blog](https://devblogs.microsoft.com/microsoft365dev/), you'll be the first to know when do announce a date!

**Comment by AE-MS** [comment]
Closing this issue based on the response above; please let us know if you'd like more info!
