### ISSUE TITLE
Not able to use requestStartLiveStreaming api in the 'settings' nor 'sidePanel' frameContext to stream live meeting to a different platform

### ISSUE THREAD

**Issue by connected-shossain** [OfficeDev/microsoft-teams-library-js#836]
I trying to build an MS Teams meeting app which would live stream MS Teams calendar video meetings to another live stream platform. I have a legitimate RTMP stream key and url from those platforms. I am trying to use the requestStartLiveStreaming api from this repo in an MS Teams meeting tab app, but not able to call it; even from different contexts like 'settings' nor 'sidePanel'. Either it throws an error or doesn't do nor print anything to console.

### Background:
I got the sample code from this [video](https://www.youtube.com/watch?v=QvkMIg2NVj4) which uses [Microsoft Teams Yeoman generator v3](https://github.com/pnp/generator-teams/tree/master/packages/generator-teams) and modified it accordingly.

First, I tried calling requestStartLiveStreaming from the <b>DemoAppTabConfig.tsx</b> (shows the tab config in an iframe):
```
import * as React from "react";
import { Provider, Flex, Header, Input } from "@fluentui/react-northstar";
import { useState, useEffect, useRef } from "react";
import { useTeams } from "msteams-react-base-component";
import * as microsoftTeams from "@microsoft/teams-js";

/**
 * Implementation of demo app Tab configuration page
 */
export const DemoAppTabConfig = () => {

    const [{ inTeams, theme, context }] = useTeams({});
    const [text, setText] = useState<string>();
    const entityId = useRef("");

    const onSaveHandler = (saveEvent: microsoftTeams.settings.SaveEvent) => {
        console.log("DemoAppTabConfig - onSaveHandler", saveEvent);
        const host = "https://" + window.location.host;
        microsoftTeams.settings.setSettings({
            contentUrl: host + "/demoAppTab/?name={loginHint}&tenant={tid}&group={groupId}&theme={theme}",
            websiteUrl: host + "/demoAppTab/?name={loginHint}&tenant={tid}&group={groupId}&theme={theme}",
            suggestedDisplayName: "demo app Tab",
            removeUrl: host + "/demoAppTab/remove.html?theme={theme}",
            entityId: entityId.current
        });
        saveEvent.notifySuccess();
    };

    useEffect(() => {
        console.log("DemoAppTabConfig - useEffect: inTeams", inTeams);
        console.log("DemoAppTabConfig - useEffect: context", context);
        if (context) {
            console.log("DemoAppTabConfig - useEffect: if context: ", context);
            setText(context.entityId);
            entityId.current = context.entityId;
            microsoftTeams.settings.registerOnSaveHandler(onSaveHandler);
            microsoftTeams.settings.setValidityState(true);
            microsoftTeams.appInitialization.notifySuccess();
        }
        microsoftTeams.initialize(() => {
            console.log("after init");
            microsoftTeams.meeting.requestStartLiveStreaming((error) => {
                console.log("requestStartLiveStreaming error is: ", error);
            }, "rtmps://live-api-s.facebook.com:443/rtmp/", "FB-138908605240584-0-Abxb1_-5lA6z7HcT");
        });
    // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [context]);

    return (
        <Provider theme={theme}>
            <Flex fill={true}>
                <Flex.Item>
                    <div>
                        <Header content="Configure your tab3" />
                        <Input
                            placeholder="Enter a value here"
                            fluid
                            clearable
                            value={text}
                            onChange={(e, data) => {
                                if (data) {
                                    setText(data.value);
                                    entityId.current = data.value;
                                }
                            }}
                            required />
                    </div>
                </Flex.Item>
            </Flex>
        </Provider>
    );
};
```

When I join the meeting and try to add my app, I get the above configuration page in an iframe like this:  
![Screen Shot 2022-01-13 at 1 55 56 AM](https://user-images.githubusercontent.com/85316115/149280497-b964045d-3072-49a2-b6f3-7eff08fa9f9f.png)

and devtools console shows me the error and logs:
![Screen Shot 2022-01-13 at 1 58 05 AM](https://user-images.githubusercontent.com/85316115/149281426-0b3bbaa0-a7eb-41ff-a976-4f74b304e8ec.png)

After this didnt work, I then click on save on the UI which opens up <b>side panel</b> iframe. So I tried calling requestStartLiveStreaming from the DemoAppTab.tsx (shows the tab config in an sidepanel): The code for that is below: 
```
import * as React from "react";
import { Provider, Flex, Text, Button, Header, Input } from "@fluentui/react-northstar";
import { useState, useEffect } from "react";
import { useTeams } from "msteams-react-base-component";
import * as microsoftTeams from "@microsoft/teams-js";

/**
 * Implementation of the demo app Tab content page
 */
export const DemoAppTab = () => {

    const [{ inTeams, theme, context }] = useTeams();
    const [text, setText] = useState<string>();
    const [entityId, setEntityId] = useState<string | undefined>();

    useEffect(() => {
        console.log("DemoAppTab - useEffect: inTeams", inTeams);
        if (inTeams === true) {
            microsoftTeams.appInitialization.notifySuccess();
        } else {
            setEntityId("Not in Microsoft Teams");
        }
    }, [inTeams]);

    useEffect(() => {
        console.log("DemoAppTab - useEffect: context", context);
        microsoftTeams.initialize(() => {
            console.log("after init");
            microsoftTeams.meeting.requestStartLiveStreaming((error) => {
                console.log("requestStartLiveStreaming error is: ", error);
            }, "rtmps://live-api-s.facebook.com:443/rtmp/", "FB-138908605240584-0-Abxb1_-5lA6z7HcT");
        });
        microsoftTeams.meeting.getLiveStreamState((error, liveStreamState) => {
            console.log("getLiveStreamState error is: ", error);
            console.log("getLiveStreamState liveStreamState is: ", liveStreamState);
        });
        if (context) {
            setEntityId(context.entityId);
        }
    }, [context]);

    useEffect(() => {
        console.log("DemoAppTab - useEffect: text", text);
        microsoftTeams.meeting.getLiveStreamState((error, liveStreamState) => {
            console.log("getLiveStreamState error is: ", error);
            console.log("getLiveStreamState liveStreamState is: ", liveStreamState);
        });
    }, [text]);

    /**
     * The render() method to create the UI of the tab
     */
    return (
        <Provider theme={theme}>
            <Flex fill={true} column styles={{
                padding: ".8rem 0 .8rem .5rem"
            }}>
                <Flex.Item>
                    <Header content="This is your tab1" />
                </Flex.Item>
                <Flex.Item>
                    <div>
                        <div>
                            <Text content={entityId} />
                        </div>

                        <div>
                            <Button onClick={() => alert("It worked!")}>A sample button</Button>
                        </div>
                    </div>
                </Flex.Item>
                <Flex.Item styles={{
                    padding: ".8rem 0 .8rem .5rem"
                }}>
                    <Text size="smaller" content="(C) Copyright Shafaaf Comp" />
                </Flex.Item>
                {/* my code below */}
                <Input
                    placeholder="Enter a test value here to trigger useEffect for value"
                    fluid
                    clearable
                    value={text}
                    onChange={(e, data) => {
                        if (data) {
                            setText(data.value);
                        }
                    }}
                    required />
            </Flex>
        </Provider>
    );
};
```

It has the following UI: 
![Screen Shot 2022-01-13 at 2 16 51 AM](https://user-images.githubusercontent.com/85316115/149283367-3bfddecf-6922-4d56-b793-824d79f05047.png)

And the console logs from devtools:
![Screen Shot 2022-01-13 at 2 25 51 AM](https://user-images.githubusercontent.com/85316115/149353850-f33c213f-55b1-41de-89c7-c7fc1072a916.png)

The calls to <b>requestStartLiveStreaming</b> dont log anything and <b>getLiveStreamState</b> dont call the callback nor throw any errors. 

This is my manifest file:
```
{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.11/MicrosoftTeams.schema.json",
  "manifestVersion": "1.11",
  "version": "0.0.1",
  "id": "d7da9f10-73fa-11ec-9bac-a3bfd9d0ed3f",
  "packageName": "demo",
  "developer": {
    "name": "Shafaaf Comp",
    "websiteUrl": "https://demo.azurewebsites.net",
    "privacyUrl": "https://demo.azurewebsites.net/privacy.html",
    "termsOfUseUrl": "https://demo.azurewebsites.net/tou.html"
  },
  "icons": {
    "color": "color.png",
    "outline": "outline.png"
  },
  "name": {
    "short": "Demo meeting app",
    "full": "Demo meeting app"
  },
  "description": {
    "short": "Meeting app made from Yeoman",
    "full": "Meeting app made from Yeoman"
  },
  "accentColor": "#D85028",
  "configurableTabs": [
    {
      "configurationUrl": "https://7202-2607-9880-1948-a0-146a-470a-2c2a-12e5.ngrok.io/demoAppTab/config.html",
      "canUpdateConfiguration": true,
      "scopes": [
        "team",
        "groupchat"
      ],
      "context": [
        "channelTab",
        "meetingSidePanel",
        "meetingDetailsTab",
        "meetingChatTab",
        "meetingStage"
      ]
    }
  ],
  "permissions": [
    "identity",
    "messageTeamMembers"
  ],
  "validDomains": [
    "7202-2607-9880-1948-a0-146a-470a-2c2a-12e5.ngrok.io",
    "demo.azurewebsites.net"
  ]
}
```

Im unsure which context to use to call these apis: requestStartLiveStreaming and getLiveStreamState to be able to stream my meeting to another platform using an available stream key and url.

Thanks!

**Comment by v-chetsh** [comment]
@connected-shossain - We will investigate on it and get back to you.

**Comment by connected-shossain** [comment]
Hi, can someone look into this? Or add some labels on the issue? Thanks!

**Comment by HunaidHanfee-MSFT** [comment]
Hello @connected-shossain,
We were confirming internally about it and we came to know that this API is currently not supported for third party developer. It works only for Microsoft first party app.

Please let us know if you are looking for anything else we will close this issue here.

**Comment by connected-shossain** [comment]
Sorry could you elaborate a bit more on what you mean by third party developer vs Microsoft first party app? The more details, the better for us.

What would be the steps and authorization required to be able to use this api?

The app we are trying to build would be an app for MS Teams to stream their meeting to another service.

**Comment by HunaidHanfee-MSFT** [comment]
@connected-shossain, Currently `requestStartLiveStreaming` is only available to use by apps created by Microsoft, on the other hand custom application outside of Microsoft cannot use it. There's no such steps and authorization available that will make it available as of now. 

Hope this answers your question. Let us know if you have any query.

**Comment by connected-shossain** [comment]
Thank you for the response. We may look into this more with an inquiry with Microsoft.

Could we know the name of the MS dev team owning this sdk?

**Comment by connected-shossain** [comment]
Also 1 more question ask: Other than this, any advice on any api or even a different sdk I can use to livestream MS Teams meetings to a third party using an available stream key and url?

**Comment by HunaidHanfee-MSFT** [comment]
> Also 1 more question ask: Other than this, any advice on any api or even a different sdk that I can use to livestream MS Teams meetings to a third party using an available stream key and url?

I am checking internally will let you know soon.

**Comment by Meghana-MSFT** [comment]
Engineering team has begun the process of adding the "supoortsStreaming" property to the app manifest schema page. We do not have any ETA about when this would be available publicly.

Aaron Linne is the owner of the live stream SDK APIs.

**Comment by Meghana-MSFT** [comment]
> Also 1 more question ask: Other than this, any advice on any api or even a different sdk that I can use to livestream MS Teams meetings to a third party using an available stream key and url?

No. Engineering team has begun the process of adding the "supoortsStreaming" property to the app manifest schema page. We do not have any ETA about when this would be available publicly.

Aaron Linne is the owner of the live stream SDK APIs.

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
