### ISSUE TITLE
Link unfurling is not working for GCC tenant

### ISSUE THREAD

**Issue by Abhiram219** [OfficeDev/microsoft-teams-library-js#855]
Hi,

We have implemented Link unfurling, this feature is working as expected in normal tenants. Coming to GCC tenant it's not working.
The invoke request itself is not firing from the network tab. In GCC tenant, Unfurling is not working for youtube and GitHub links as well.

Docs used for Link Unfurling - [docs](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?tabs=dotnet)

We also cross-checked that URL previews toggle is turned on in messaging policies that is being used ( (Global Org-wide default) ) in our case).

**Comment by Nivedipa-MSFT** [comment]
@Abhiram219 - Link Unfurling is not supported for GCC tenant.
Its documented here [Government Community Cloud (GCC)](https://domoreexp.visualstudio.com/MSTeams/_queries/edit/2177937/?triage=true)

**Comment by Abhiram219** [comment]
@Nivedipa-MSFT Unable to access this link. Getting 401.

**Comment by Nivedipa-MSFT** [comment]
@Abhiram219 - I have updated the link. Could you please check again.

**Comment by Abhiram219** [comment]
@Nivedipa-MSFT I was able to look into it. 
It mentions ❌ for Custom messaging extensions. Does this mean unfurling doesn't work at all?

**Comment by v-chetsh** [comment]
@Abhiram219 - As per documentation, Messaging Extension unfurling is not supported for GCC tenant as of now.
You can raise a user voice here: https://microsoftteams.uservoice.com/forums/555103-public/filters/new

**Comment by Abhiram219** [comment]
Thanks
