### ISSUE TITLE
Signing in with SSO Flow requires Sign In Button to be clicked twice

### ISSUE THREAD

**Issue by cooperhurt** [OfficeDev/microsoft-teams-library-js#873]
I am having an issue where the SSO flow is working inside of the teams web application perfectly fine, but when you move into the desktop app I am having to click the 'Sign In' button twice. The Sign in Button calls this method (this is not React or Angular just native JS):

```  sessionStorage.removeItem('teams');
  new Promise((resolve, reject) => {
    microsoftTeams.authentication.authenticate({
      url: window.location.origin + '/endAuth',
      width: 859,
      height: 535,
      successCallback: () => {
        // Logic
        return resolve(this.initialize());
      },
      failureCallback: (err) => {
        switch (err) {
          case 'CancelledByUser':
            // Logic
            break;
          default:
            // Logic
            break;
        }
        reject();
      },
    });
  });
```
  
  The first click works but opens inside of your default browser which cause the auth flow not work. The second click popups the Electron popup and works as expected.

This works as expected in the teams web application with no problem, only appears to be a problem with the desktop application.

**Comment by Nivedipa-MSFT** [comment]
@cooperhurt - We are investigating your query. We will get back to you once we have any update.

**Comment by Nivedipa-MSFT** [comment]
@cooperhurt - Could you please share the screenshots

**Comment by Nivedipa-MSFT** [comment]
@cooperhurt  - Could you please confirm is your issue resolved or are you still facing the issue?

**Comment by cooperhurt** [comment]
@Nivedipa-MSFT Sorry took me a second to get it ready. Here is a quick video of it.

https://youtu.be/6ydJ0R81klM

You can see the first click is the users browser, the second click on the same tab is the Electron Popup.

**Comment by Nivedipa-MSFT** [comment]
@cooperhurt - The problem was that initialize() method is not a synchronous operation. API docs shows that .initialize() takes a callback function as a parameter.  So wrapping this in a promise and chaining the authentication call to happen afterward fixed the problem.
 ```
microsoftTeams.initialize(() => {
  microsoftTeams.authentication.authenticate({
    url: myUrl,
```
Ref doc: https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/microsoftteams?view=msteams-client-js-latest#@microsoft-teams-js-microsoftteams-initialize

Could you please try this and check again.
