### ISSUE TITLE
Multiple registerOnSaveHandler() calls

### ISSUE THREAD

**Issue by benpolinsky** [OfficeDev/microsoft-teams-library-js#89]
In the docs for `registerOnSaveHandler()` :
> A subsequent registration replaces an existing registration.

However I have found that subsequent registrations do not replace/override initial registrations.  I was able to work around my specific issue by combining my logic inside of a single registration call, but thought it would be good to get some clarification.

Of course, I could be missing something.

Thanks.

**Comment by Wajeed-msft** [comment]
@benpolinsky -I tried adding multiple handlers for Save with latest [Teams SDK 0.1.7](https://www.npmjs.com/package/botbuilder-teams).

```
                      microsoftTeams.settings.registerOnSaveHandler(function(saveEvent){
				microsoftTeams.getContext(function(context) {
					alert("This is save handler 1");

					saveEvent.notifySuccess();
				});
			});

			microsoftTeams.settings.registerOnSaveHandler(function(saveEvent){
				microsoftTeams.getContext(function(context) {
					alert("This is save handler 2");
					
					saveEvent.notifySuccess();
				});
			});
```
Only subsequent registration was called as [documented](https://docs.microsoft.com/en-us/javascript/api/msteams-client/microsoftteams.microsoftteams.settings.global) i.e. **"This is save handler 2".**

Are you expecting first save handler to be called? 
Could you please share your code snippet?

**Comment by benpolinsky** [comment]
@Wajeed-msft You are correct.

Not sure exactly what I was doing, and I've since refactored that code, but I'm able to confirm the second handler overwrites the first as documented.  

Closing and thanks.
