### ISSUE TITLE
Creating a tab application within Angular

### ISSUE THREAD

**Issue by Mimetis** [OfficeDev/microsoft-teams-library-js#90]
Hi Team !

I try to create a tab application for Microsoft Teams.  
Actually, I successfully create a config page, but I don't know why, no Javascript component is actually done.

For instance, here is my `ConfigComponent` class:

``` javascript
export class ConfigComponent implements OnInit {

  constructor() { }

  ngOnInit() {
    console.log('ngOnInit');
    // initialize teams
    microsoftTeams.initialize();
    // get context
    microsoftTeams.getContext((context: microsoftTeams.Context) => {
      console.log('getContext');
      this.setValidityState(true);
    });

    microsoftTeams.settings.registerOnSaveHandler((saveEvent: microsoftTeams.settings.SaveEvent) => {
      // Calculate host dynamically to enable local debugging
      let host = "https://" + window.location.host;

      microsoftTeams.settings.setSettings({
        contentUrl: host + "/home",
        suggestedDisplayName: "NgTab",
        removeUrl: host + "/remove",
        entityId: "1"
      });

      saveEvent.notifySuccess();
    });

  }

  public setValidityState(val: boolean) {
    microsoftTeams.settings.setValidityState(val);
  }

}
```

During the initialization step (when I add the `tab`, the config webpage is called) but Nothing happens:

![image](https://user-images.githubusercontent.com/4592555/35116199-dd8ce490-fc8a-11e7-8fbb-f0d56f83b730.png)

As you can see, I don't have *anything* in the `Console`, on the right of the screen (I used the AllWebContents Dev Tools from the MS Teams menu)

Actually, I should have, at least, Something like that (when I test in a classic web browser)

![image](https://user-images.githubusercontent.com/4592555/35116271-23d5f964-fc8b-11e7-8a7a-db74004a3e11.png)

For informations, my angular application is composed by:
* An Angular 5 application, generated with Angular CLI
* An Express server, configured with a local trusted HTTPS certificates

Any idea ?

**Comment by billbliss** [comment]
Do you see anything in the console when you load https://localhost:3978/config in an iframe? Trying to narrow it down between Teams or Angular script initialization.

**Comment by Mimetis** [comment]
Okay, we can see both dev Tools for MS Teams and the Tab application.
So fine, I finally manage to see the console **from** my application.

The problem is that I called the `settings.setValidityState(true)` method, but Nothing happens.

![image](https://user-images.githubusercontent.com/4592555/35154559-f28b138a-fd2a-11e7-9696-4e8efebc92e2.png)


The question is : Why ? 
First of all, can you confirm we can working on localhost, on https ?

**Comment by Mimetis** [comment]
Using `ngrok` seems to resolve the problem.  
Eventually, can you cofirm, we can't work on `localhost` to develop a **Tab** Ms Teams application ?   

It's a little bit complicated, to setup a correct environment, to be able to *start* coding, isn't it ?

**Comment by billbliss** [comment]
It didn't occur to me that you weren't using ngrok -- I should have thought of that. Yes, it is complex, but as an application running in the cloud, Teams has to be able to reach the configuration endpoint (Teams has to call you, right?). We discuss that here: https://docs.microsoft.com/en-us/microsoftteams/platform/resources/general/debug. 

We've considered a WebSockets-based polling approach for development scenarios (something that would poll periodically and establish a connection on demand) but that still would require some kind of tool that you didn't know about.

Is your `settings.setValidityState(true)` code working now?

**Comment by Mimetis** [comment]
Yep, it's working as expected.   
The problem, in my opinion, is that the default configuration to be able to work & debug on a local dev machine is a little bit complicated and tricky.

Seb

**Comment by billbliss** [comment]
I agree with you. Will look for ways to simplify things.
