### ISSUE TITLE
Teams angular js throws QuotaExceededError on trying to login to salesforce app.

### ISSUE THREAD

**Issue by hipatelsf** [OfficeDev/microsoft-teams-library-js#919]
When trying to login to salesforce app on teams. The button click does nothing. Network logs show the following error:
on retrying after a minute or two seems to work fine.

Attempting to handle auth response: error:endpoints_resolution_error|Error: could not resolve endpoints. Please check network and try again. Details: QuotaExceededError: The quota has been exceeded., resource:api://chatapp-staging.force.com/984d605b-afa5-4f92-93e8-799525463059, error mapped to action:renewalTimeout
<img width="1434" alt="Screen Shot 2022-02-10 at 1 13 41 PM" src="https://user-images.githubusercontent.com/63263890/153500525-46ed20c7-24b7-414c-8ebc-8dd309d78358.png">

**Comment by v-chetsh** [comment]
@hipatelsf - Could you please share the repro steps, manifest file, so that we can check it from our end?
