### ISSUE TITLE
Detecting current theme / theme style guides

### ISSUE THREAD

**Issue by benpolinsky** [OfficeDev/microsoft-teams-library-js#93]
1. Currently, I'm using the onRegisterThemeHandler to detect theme changes. Works great. To detect the current theme, however, I'm storing "default" in localStorage and keeping it updated on change. 

This works most of the time. However, there are a couple of edge cases where this method falls short:

- If a user manually clears their localStorage
- This issue: https://techcommunity.microsoft.com/t5/Microsoft-Teams/Bug-report-Theme-setting-isn-t-kept-upon-logout-login/m-p/66203 where the theme reverts to default on logout/login

It would feel more robust to be able to grab the current theme on initialization, for instance, and make updates from there.

2. Is there a style guide for themes? 

Thanks

**Comment by billbliss** [comment]
See here for how to access the theme when the tab is invoked so you can handle changes at render time: https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/tabs/tabs-context#accessing-context. If you use a URL placeholder that should work better than storing "default" in localStorage.

This topic is also discussed here, although it's not the central focus: https://techcommunity.microsoft.com/t5/Microsoft-Teams-Blog/Microsoft-Teams-App-Studio-s-Control-Library/ba-p/155753.

By style guide, do you mean [this](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/design/overview)? Or a specific CSS stylesheet?

**Comment by benpolinsky** [comment]
Oh great. No, not a specific CSS Stylesheet - that's fine. Not sure how I missed that :)

Much appreciated.

**Comment by billbliss** [comment]
Excellent! Let us know if you run into any problems.
