### ISSUE TITLE
Cannot start retry fetch of ADAL tokens, isPassive: false

### ISSUE THREAD

**Issue by janandreschweiger** [OfficeDev/microsoft-teams-library-js#938]
Hi everyone,

I was notified today that some of our users failed to log in.

We use your library to log users into our teams tabs using SSO. Strangely, the login (first query for token) failed:

This is our code:
```
const microsoftTeams = await import('@microsoft/teams-js');
microsoftTeams.initialize();

const token = await new Promise((resolve, reject) =>
  this.microsoftTeams.authentication.getAuthToken({  // fails with the error below
    successCallback: resolve,
    failureCallback: reject
  })
);
```
Do you have an idea, why the getAuthToken method fails with:
```
Cannot start retry fetch of ADAL tokens, isPassive: false
```

Stability is our key priority. Any help is appreciated. Thanks in advance!!

**Comment by Nivedipa-MSFT** [comment]
@janandreschweiger - We are investigating your query. We will get back to you once we have any update.

**Comment by janandreschweiger** [comment]
Thanks for your fast response @Nivedipa-MSFT. Unfortunately, we cannot reproduce it. So hopefully the error message can give you a hint how this happened.

**Comment by Nivedipa-MSFT** [comment]
@janandreschweiger - Could you please confirm is this issue occuring frequently or not? Is it a blocker for you?
