### ISSUE TITLE
notifySuccess/notifyFailure returns object instead of string on mobile in Auth End page

### ISSUE THREAD

**Issue by KennethBWSong** [OfficeDev/microsoft-teams-library-js#942]
Hi everyone,

I have a Teams Tab app working fine on Desktop and browser, but failed to login on mobile client.
In the app, I called microsoftteams.authentication.authentication to pop up auth pages, and use notifyFailure to return an string to tab as shown below. 
![image](https://user-images.githubusercontent.com/63089166/155064166-851152fa-ba81-4212-a72c-45458d8bf1fd.png)

The code can show the string on Desktop and browser, but will regard the string as an object on mobile.
![image](https://user-images.githubusercontent.com/63089166/155064212-16f0714c-7739-43f3-80e3-2e8ee78c5722.png)
mobile:
![image](https://user-images.githubusercontent.com/63089166/155064099-e376bc86-508a-487e-bbd6-60d4bcff76a9.png)
browser:
![image](https://user-images.githubusercontent.com/63089166/155064119-47fdcde2-ea0a-46bf-8700-4770b8cf9aed.png)

Do you have any idea how to solve this problem?
Any help is appreciated. Thanks in advance!

**Comment by sayali-MSFT** [comment]
@KennethBWSong - We are looking into this I will get back to you soon.

**Comment by KennethBWSong** [comment]
Hi @sayali-MSFT Any update in this thread?

**Comment by sayali-MSFT** [comment]
@KennethBWSong - We are checking it internally and let you know once we get any updates.

**Comment by sayali-MSFT** [comment]
@KennethBWSong - We are able to repro that issue , We have raised bug for the same and concerned team is looking into it. We will inform you once we get any update.

**Comment by KennethBWSong** [comment]
Hi @sayali-MSFT Any update in this thread?

**Comment by sayali-MSFT** [comment]
@KennethBWSong - Currently we don’t have ETA or Update on this thread. 
We will update this thread once the bug is fixed.

**Comment by sayali-MSFT** [comment]
Sorry for the delay. Engineering team working on this issue. Currently we don’t have ETA or Update on this thread.
We will update this thread once the bug is fixed.

**Comment by sayali-MSFT** [comment]
We are checking the status of the fix release with the engineering team. We will let you know once we have any updates on it. Thanks.

**Comment by danielkrausz** [comment]
@sayali-MSFT Do you have an update on this issue? We are facing the same problem on Android (works fine on iOS) with the latest version (v2.8.0) of the library.

**Comment by sayali-MSFT** [comment]
@danielkrausz -We are actively checking the status of bug with engineering team and let you know the updates, if we have any.
Thanks!!

**Comment by sayali-MSFT** [comment]
> @sayali-MSFT Do you have an update on this issue? We are facing the same problem on Android (works fine on iOS) with the latest version (v2.8.0) of the library.

@danielkrausz -If Possible, could you please share the manifest of the app?

**Comment by danielkrausz** [comment]
@sayali-MSFT Sure, our app is available on [AppSource](https://appsource.microsoft.com/en-GB/product/office/WA200005122) and here is our app package with the manifest file:
[tresorit.production.zip](https://github.com/OfficeDev/microsoft-teams-library-js/files/10706105/tresorit.production.zip)

**Comment by AE-MS** [comment]
@KennethBWSong @danielkrausz : the fix for this bug, which will ensure that functions return a string instead of an object on Android, has been checked in and will be rolling out across the Android Teams app in March (this month!) I will report back with a version number once I receive confirmation that it's 100% rolled out.

**Comment by danielkrausz** [comment]
@AE-MS Thank you for the update, looking forward to the new version with the fix!
