### ISSUE TITLE
`App webApplicationInfo or resource not defined in manifest` from getAuthToken

### ISSUE THREAD

**Issue by tiennguyen1293** [OfficeDev/microsoft-teams-library-js#974]
I have an issue with `getAuthToken` method when I execute this method console.log shows `App webApplicationInfo or resource not defined in manifest`.

I also investigate about [MSAL SDK](https://github.com/AzureAD/microsoft-authentication-library-for-js) but it can not open popup login from iframe or redirect also.

Please help me understand the issue here. thank you guys.

```
Platform: Microsoft Teams App Desktop (v1.5.00.4767) and I built App from App Studio from Web URL

Version: "@microsoft/teams-js": "^1.5.2"
```

```
microsoftTeams.authentication.authenticate({
      url,
      width: 600,
      height: 535,
      successCallback: (result) => {
        try {
          microsoftTeams.authentication.getAuthToken({
            successCallback: (token) => {
              console.log('========= getAuthToken successCallback', token)
            },
            failureCallback: (reason) => {
              console.log('========= getAuthToken failureCallback', reason)
            },
          })
        } catch (error) {
          console.error('=== Error getAuthTokenFromMSTeams', error)
        }
    },
    failureCallback: (reason) => {},
})
```

<img width="788" alt="image" src="https://user-images.githubusercontent.com/26110369/156501970-e20ce33f-3f57-4865-a567-6198a882d70d.png">

**Comment by v-chetsh** [comment]
We will check on it  from our end and get back to you.

**Comment by Prasad-MSFT** [comment]
@tiennguyen1293 - Could you please verify  your manifest if you are correcting adding webApplicationInfo section as mentioned [here](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#webapplicationinfo) ?
```
"webApplicationInfo": {
  "id": "00000000-0000-0000-0000-000000000000",
  "resource": "api://subdomain.example.com/00000000-0000-0000-0000-000000000000"
}
```
https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso?tabs=dotnet#2-update-your-teams-application-manifest

**Comment by tiennguyen1293** [comment]
Hi @Prasad-MSFT and @v-chetsh 
Thanks for responding to me.
So...in App Studio in Microsoft Teams App, we haven't seen a section to set `webApplicationInfo`. 🤔 

<img width="1326" alt="image" src="https://user-images.githubusercontent.com/26110369/156718559-3814d598-0611-4fc9-ba45-e8daf7b1330d.png">

**Comment by Prasad-MSFT** [comment]
It is present under 'Domains and permissions' section.
![image](https://user-images.githubusercontent.com/62237649/156757482-f5bc4fd8-d07d-4992-ac89-ae7056725bfa.png)

**Comment by tiennguyen1293** [comment]
Thank for you guys supproted. I will close this issue.

Many thank...
