### ISSUE TITLE
stopSharingAppContentToStage private api

### ISSUE THREAD

**Issue by tdwhite0** [OfficeDev/microsoft-teams-library-js#976]
In this pull request I can see that meeting.stopSharingAppContentToStage is intended to be private: https://github.com/OfficeDev/microsoft-teams-library-js/pull/889. Is there a reason why this can't be made public? In my app I want to call this to stop the sharing after a set period of time. I can start the sharing programmatically, but I can't stop it programmatically.

**Comment by v-chetsh** [comment]
@tdwhite0 - We will check on it with engineering team and get back to you.

**Comment by Prasad-MSFT** [comment]
For now the only supported methods are shareAppContentToStage and getAppContentStageSharingState.
Other methods are private, so that's the only available thing for now
