### ISSUE TITLE
executeDeepLink not working on Mobile App

### ISSUE THREAD

**Issue by tiennguyen1293** [OfficeDev/microsoft-teams-library-js#980]
I'm using `executeDeepLink` to redirect from Chat to Personal Tab on App. And then it just working on Desktop App but not working on Mobile App.
Please help me to check.

# Platform Version
> iOS 15.3.1

# Version
> "@microsoft/teams-js": "^1.5.2",

<img width="365" alt="image" src="https://user-images.githubusercontent.com/26110369/157161705-61c0b1d8-b4fe-4569-9aae-2191bea2a6a0.png">

**Comment by Meghana-MSFT** [comment]
Could you please share the sample you are referring?

**Comment by tiennguyen1293** [comment]
I'm doing follow to Create deep link DOC [here](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links)

> https://teams.microsoft.com/l/entity/<AppId>/<EntityId>?webUrl=<entityWebUrl>/<EntityName>

My deep link:
> https://teams.microsoft.com/l/entity/243eb934-765b-4215-9dea-35212d3e5dff/editMembers/?context=%7B%22subEntityId%22%3A%22%21yTAWzOeWQLnFAyOvrI%3Aleapxpert-development%22%7D&label=Edit%20Members&webUrl=http%3A%2F%2Flocalhost%3A3000%2Fedit-members%3FisNativeTheme%3D1

**Comment by Meghana-MSFT** [comment]
As per the document, we can use `microsoftTeams.executeDeepLink(/*deepLink*/)` method to deep link to content in Teams from your tab. As this method is accessible within a tab. Could you please let us know how your are using executeDeeplink in a chat?

**Comment by Meghana-MSFT** [comment]
We used this sample https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-conversations/nodejs in iOS. Clicking on Deeplink to conversation takes me to the chat. Attaching the screenshots for your reference. Could you please let us know if this is what you are doing?

![MicrosoftTeams-image (19)](https://user-images.githubusercontent.com/81138249/157706516-121dda2a-0548-4e4b-944c-f9c6446ea162.png)
![MicrosoftTeams-image (20)](https://user-images.githubusercontent.com/81138249/157706534-939d0709-7424-4193-80ca-dd647f4938d8.png)

**Comment by tiennguyen1293** [comment]
hmmm... So how about from the conversation tab redirect to Customize App 🤔 (The app built from App Studio).
Could you please share the example?

<img width="863" alt="image" src="https://user-images.githubusercontent.com/26110369/158098184-8099d968-2158-4978-ab81-10c100957daf.png">

**Comment by Meghana-MSFT** [comment]
Please go through this to [create Deep linking to an app
](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links#deep-linking-to-an-app).

**Comment by v-chetsh** [comment]
@tiennguyen1293 - Shall we close this issue?

**Comment by tiennguyen1293** [comment]
Sorry for late response
The sample of @Meghana-MSFT above, its working for the way from custom app to chat but it will not work for the opposite way on mobile.

**Comment by Meghana-MSFT** [comment]
Please go through [Deep linking to your tab](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links#deep-linking-to-your-tab). But as mentioned in document, currently shareDeepLink does not work on mobile platforms. You can keep a button instead and redirect using the deeplink on button click.

**Comment by Meghana-MSFT** [comment]
Could you please confirm if we can close this issue?

**Comment by tiennguyen1293** [comment]
i have opened another issue for Android here.

https://github.com/OfficeDev/microsoft-teams-library-js/issues/1447
