### ISSUE TITLE
add userChannelRole to context for private channels

### ISSUE THREAD

**Issue by matthiasdilger** [OfficeDev/microsoft-teams-library-js#988]
After adding my tab to a private channel I would like to know if the user is an owner of this private channel so that I can display different information. The context interface already has userTeamRole and it would be great to have a userChannelRole for private channels as well.
I understand that I can use the graph API to get this information, but for [get member](https://docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-1.0&tabs=http) to work my app needs the ChannelMember.Read.All permission, which requires admin consent and gives me access to a lot of information that I don't actually need or want.
Is it possible to get a simple userChannelRole  flag on the context interface in private channels? Thank you.

**Comment by v-chetsh** [comment]
We will check on it and get back to you.

**Comment by Prasad-MSFT** [comment]
@matthiasdilger - As mentioned [here](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context#retrieve-context-in-private-channels), When your content page is loaded in a private channel, the data you receive from the getContext call is obfuscated to protect the privacy of the channel.
There doesn't seem to be any other way to add userChannelRole flag on the context interface in private channels.
You can raise a [UserVoice](https://microsoftteams.uservoice.com/forums/555103-public/filters/new ) for the same.
Thanks!

**Comment by matthiasdilger** [comment]
@Prasad-MSFT I don't think having a simple 0/1 flag for private channel admin would endanger the privacy of the channel, after all I can get user details like the user's name, upn and team admin status without needing additional permission, so why would this be different? (Maybe I don't fully understand the concept of private channels in the first place)
I'm hesitant to add it to UserVoice because 99% of posts there seem to be going nowhere, but since you mentioned there is no other option, I have added it here: [https://feedbackportal.microsoft.com/feedback/idea/8437774c-a7ad-ec11-a81c-000d3a7ce453](https://feedbackportal.microsoft.com/feedback/idea/8437774c-a7ad-ec11-a81c-000d3a7ce453)

**Comment by Prasad-MSFT** [comment]
We are closing the issue for now. Please feel free to re-open if required.
