### ISSUE TITLE
ContentSharingService: Failed to handle incoming session 

### ISSUE THREAD

**Issue by danbratton** [OfficeDev/microsoft-teams-library-js#992]
Users are unable to view shared app content when using Microsoft Teams from a web browser.  

To reproduce:

1. Install the MURAL app for Teams
2. Schedule a meeting and join it.
3. Add MURAL as a tab to the meeting and select a mural to share in the meeting
4. Share the mural tab in the meeting (share-to-stage)
5. Have another user on the same Microsoft tenant join the meeting using Teams in a web browser (Chrome or Edge)
6. The user from step 5 will see an error page ("Can't display content")

The error logs are:
`2022-03-11T14:56:10.009Z ContentSharingService: Failed to handle incoming session f60e4f98-f10d-4249-87ce-df726da03f4c
2022-03-11T14:56:10.009Z ContentSharingService: Content sharing session f60e4f98-f10d-4249-87ce-df726da03f4c failed with a provider-specific error
2022-03-11T14:56:10.010Z calling-screen: Displaying shared content failed in session f60e4f98-f10d-4249-87ce-df726da03f4c`

![image (16)](https://user-images.githubusercontent.com/36574980/158212847-ca84a27c-f089-4729-97aa-955f103c87c6.png)
![image (15)](https://user-images.githubusercontent.com/36574980/158212874-4e84350c-1a76-408b-a3e8-42fd3e2a968b.png)

**Comment by Prasad-MSFT** [comment]
We are checking the issue. We will get back to you shortly

**Comment by Prasad-MSFT** [comment]
@danbratton - We have repro for this issue and raised  a bug for the same. We will inform you once we get any update from engineering team.

**Comment by danbratton** [comment]
Hi @Prasad-MSFT we've noticed this is now happening for any user who is a Guest in a Teams meeting, regardless of whether they are using Teams in a web browser, Windows app, or Mac app.

Have you heard any updates from engineering?

**Comment by Prasad-MSFT** [comment]
Hi @danbratton - Engineering team is investigating the issue. We will inform you if we get any update.
